APM:Libraries: libraries/AP_Motors/examples/AP_Motors_Time_test/AP_Motors_Time_test.cpp File Reference
AP_Motors_Time_test.cpp File Reference
#include <AP_Common/AP_Common.h>
#include <AP_Param/AP_Param.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>
#include <RC_Channel/RC_Channel.h>
#include <AP_Motors/AP_Motors.h>
#include <AP_Curve/AP_Curve.h>
#include <AP_Notify/AP_Notify.h>
#include <AP_GPS/AP_GPS.h>
#include <DataFlash/DataFlash.h>
#include <AP_InertialSensor/AP_InertialSensor.h>
#include <AP_ADC/AP_ADC.h>
#include <GCS_MAVLink/GCS_MAVLink.h>
#include <AP_Baro/AP_Baro.h>
#include <Filter/Filter.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_Compass/AP_Compass.h>
#include <AP_Declination/AP_Declination.h>
#include <AP_Airspeed/AP_Airspeed.h>
#include <AP_Vehicle/AP_Vehicle.h>
#include <AP_ADC_AnalogSource/AP_ADC_AnalogSource.h>
#include <AP_Mission/AP_Mission.h>
#include <StorageManager/StorageManager.h>
#include <AP_Terrain/AP_Terrain.h>
#include <AP_NavEKF/AP_NavEKF.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <AP_RangeFinder/AP_RangeFinder.h>
Functions
void setup ()
void loop ()
void motor_order_test ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
RC_Channel rc1 (0)
RC_Channel rc2 (1)
RC_Channel rc3 (2)
RC_Channel rc4 (3)
AP_MotorsQuad motors (rc1, rc2, rc3, rc4, 400)
Function Documentation
AP_HAL_MAIN ()
void loop (void)
Definition at line 84 of file AP_Motors_Time_test.cpp.
void motor_order_test ()
Definition at line 92 of file AP_Motors_Time_test.cpp.
Referenced by loop().
void setup (void)
Definition at line 50 of file AP_Motors_Time_test.cpp.
Variable Documentation
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 35 of file AP_Motors_Time_test.cpp.
AP_MotorsQuad motors(rc1, rc2, rc3, rc4, 400)
Referenced by motor_order_test(), and setup().
RC_Channel rc1(0)
Referenced by setup().
RC_Channel rc2(1)
Referenced by setup().
RC_Channel rc3(2)
Referenced by setup().
RC_Channel rc4(3)
Referenced by setup().