APM:Libraries: libraries/AP_Progmem/AP_Progmem.h File Reference
AP_Progmem.h File Reference
#include <string.h>
#include <stdint.h>
Functions
static uint8_t pgm_read_byte (const void *s)
static uint8_t pgm_read_byte_far (const void *s)
static uint16_t pgm_read_word (const void *s)
static uint32_t pgm_read_dword (const void *s)
static float pgm_read_float (const void *s)
static uintptr_t pgm_read_pointer (const void *s)
static void pgm_read_block (const void *s, void *dest, uint8_t len)
Function Documentation
static void pgm_read_block (const void * s, void * dest, uint8_t len) inline static
Definition at line 39 of file AP_Progmem.h.
Referenced by Menu::_call(), and AP_Scheduler::run().
static uint8_t pgm_read_byte (const void * s) inline static
Definition at line 7 of file AP_Progmem.h.
Referenced by AP_Param::AP_Param(), mavlink_get_message_crc(), print_vprintf(), StorageAccess::read_block(), AP_GPS::send_blob_update(), StorageAccess::StorageAccess(), and StorageAccess::write_block().
static uint8_t pgm_read_byte_far (const void * s) inline static
Definition at line 12 of file AP_Progmem.h.
static uint32_t pgm_read_dword (const void * s) inline static
Definition at line 22 of file AP_Progmem.h.
Referenced by AP_GPS::detect_instance().
static float pgm_read_float (const void * s) inline static
Definition at line 27 of file AP_Progmem.h.
Referenced by AP_AutoTune::check_state_exit(), and AP_AutoTune::start().
static uintptr_t pgm_read_pointer (const void * s) inline static
Definition at line 33 of file AP_Progmem.h.
static uint16_t pgm_read_word (const void * s) inline static
Definition at line 17 of file AP_Progmem.h.
Referenced by crc16_ccitt(), StorageManager::erase(), StorageAccess::read_block(), AP_Scheduler::run(), StorageAccess::StorageAccess(), and StorageAccess::write_block().