APM:Libraries: libraries/AP_Math/AP_Math.h File Reference
AP_Math.h File Reference
#include <AP_Common/AP_Common.h>
#include <AP_Param/AP_Param.h>
#include <math.h>
#include <stdint.h>
#include "rotations.h"
#include "vector2.h"
#include "vector3.h"
#include "matrix3.h"
#include "quaternion.h"
#include "polygon.h"
#include "edc.h"
#include "float.h"
Macros
#define M_PI_F 3.141592653589793f
#define M_2PI_F (2*M_PI_F)
#define PI M_PI_F
#define M_PI_2 1.570796326794897f
#define DEG_TO_RAD 0.017453292519943295769236907684886f
#define RAD_TO_DEG 57.295779513082320876798154814105f
#define DEG_TO_RAD_DOUBLE 0.0174532925199432954743716805978692718781530857086181640625
#define RAD_TO_DEG_DOUBLE 57.29577951308232286464772187173366546630859375
#define RadiansToCentiDegrees(x) ((x) * 5729.5779513082320876798154814105f)
#define GRAVITY_MSS 9.80665f
#define RADIUS_OF_EARTH 6378100
#define ROTATION_COMBINATION_SUPPORT 0
#define LATLON_TO_M 0.01113195f
#define LATLON_TO_CM 1.113195f
#define WGS84_A 6378137.0
#define WGS84_IF 298.257223563
#define WGS84_F (1/WGS84_IF)
#define WGS84_B (WGS84_A*(1-WGS84_F))
#define WGS84_E (sqrt(2*WGS84_F - WGS84_F*WGS84_F))
#define max(a, b) ((a)>(b)?(a):(b))
#define min(a, b) ((a)<(b)?(a):(b))
#define NSEC_PER_SEC 1000000000ULL
#define NSEC_PER_USEC 1000ULL
Functions
AP_PARAMDEFV (Matrix3f, Matrix3f, AP_PARAM_MATRIX3F)
AP_PARAMDEFV (Vector3f, Vector3f, AP_PARAM_VECTOR3F)
static bool is_equal (const float fVal1, const float fVal2)
static bool is_zero (const float fVal1)
float safe_asin (float v)
float safe_sqrt (float v)
float longitude_scale (const struct Location &loc)
float get_distance (const struct Location &loc1, const struct Location &loc2)
uint32_t get_distance_cm (const struct Location &loc1, const struct Location &loc2)
int32_t get_bearing_cd (const struct Location &loc1, const struct Location &loc2)
bool location_passed_point (const struct Location &location, const struct Location &point1, const struct Location &point2)
float location_path_proportion (const struct Location &location, const struct Location &point1, const struct Location &point2)
void location_update (struct Location &loc, float bearing, float distance)
void location_offset (struct Location &loc, float ofs_north, float ofs_east)
Vector2f location_diff (const struct Location &loc1, const struct Location &loc2)
int32_t wrap_360_cd (int32_t error)
int32_t wrap_180_cd (int32_t error)
float wrap_360_cd_float (float angle)
float wrap_180_cd_float (float angle)
float wrap_PI (float angle_in_radians)
bool locations_are_same (const struct Location &loc1, const struct Location &loc2)
void print_latlon (AP_HAL::BetterStream *s, int32_t lat_or_lon)
void wgsllh2ecef (const Vector3d &llh, Vector3d &ecef)
void wgsecef2llh (const Vector3d &ecef, Vector3d &llh)
static float constrain_float (float amt, float low, float high)
static int16_t constrain_int16 (int16_t amt, int16_t low, int16_t high)
static int32_t constrain_int32 (int32_t amt, int32_t low, int32_t high)
bool inverse (float x[], float y[], uint16_t dim)
static float radians (float deg)
static float degrees (float rad)
static float sq (float v)
static float pythagorous2 (float a, float b)
static float pythagorous3 (float a, float b, float c)
static float maxf (float a, float b)
static float minf (float a, float b)
uint32_t hz_to_nsec (uint32_t freq)
uint32_t nsec_to_hz (uint32_t usec)
uint32_t usec_to_nsec (uint32_t usec)
uint32_t nsec_to_usec (uint32_t nsec)
Macro Definition Documentation
#define DEG_TO_RAD 0.017453292519943295769236907684886f
Definition at line 35 of file AP_Math.h.
Referenced by AP_InertialSensor_LSM9DS0::_set_gyro_scale(), longitude_scale(), and radians().
#define DEG_TO_RAD_DOUBLE 0.0174532925199432954743716805978692718781530857086181640625
Definition at line 41 of file AP_Math.h.
#define GRAVITY_MSS 9.80665f
Definition at line 47 of file AP_Math.h.
Referenced by AP_InertialSensor::_calibrate_accel(), AP_PitchController::_get_coordination_rate_offset(), AP_InertialSensor_LSM9DS0::_set_accel_scale(), AP_TECS::_update_energies(), AP_TECS::_update_pitch(), AP_TECS::_update_STE_rate_lim(), AC_PosControl::accel_to_lean_angles(), AC_PosControl::accel_to_throttle(), NavEKF2_core::calcOutputStatesFast(), AP_AHRS_DCM::drift_correction(), AP_YawController::get_servo_out(), NavEKF2_core::getAccelNED(), NavEKF_core::getAccelNED(), SITL::Helicopter::Helicopter(), AC_PosControl::lean_angles_to_accel(), SITL::MultiCopter::MultiCopter(), SmallEKF::predictStates(), AC_PosControl::relax_alt_hold_controllers(), GCS_MAVLINK::send_raw_imu(), SITL::Tracker::update(), SITL::Balloon::update(), SITL::SimRover::update(), SITL::Helicopter::update(), SITL::MultiCopter::update(), AP_TECS::update_50hz(), NavEKF_core::UpdateStrapdownEquationsNED(), and NavEKF2_core::UpdateStrapdownEquationsNED().
#define LATLON_TO_CM 1.113195f
Definition at line 57 of file AP_Math.h.
#define LATLON_TO_M 0.01113195f
Definition at line 56 of file AP_Math.h.
#define M_2PI_F (2*M_PI_F)
Definition at line 26 of file AP_Math.h.
Referenced by DigitalLPF< T >::apply(), AC_PI_2D::calc_filt_alpha(), and AC_PID::get_filt_alpha().
#define M_PI_2 1.570796326794897f
Definition at line 32 of file AP_Math.h.
Referenced by AP_L1_Control::update_heading_hold(), AP_L1_Control::update_loiter(), and wgsecef2llh().
#define M_PI_F 3.141592653589793f
Definition at line 23 of file AP_Math.h.
Referenced by AP_L1_Control::_prevent_indecision(), AC_PosControl::accel_to_lean_angles(), CompassCalibrator::accept_sample(), SITL::SimRover::calc_yaw_rate(), NavEKF2_core::calcMagHeadingInnov(), AP_MotorsHeli_Single::servo_test(), and AP_Mount_Servo::stabilize().
#define max (a, b) ((a)>(b)?(a):(b))
Definition at line 224 of file AP_Math.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_InertialSensor_PX4::_get_sample(), AP_InertialSensor_PX4::_new_accel_sample(), AP_InertialSensor_PX4::_new_gyro_sample(), AP_TECS::_update_pitch(), AP_TECS::_update_speed(), AC_PrecLand::calc_angles_and_pos(), AC_WPNav::calc_loiter_desired_velocity(), AC_Circle::calc_velocities(), NavEKF_core::calcGpsGoodForFlight(), NavEKF2_core::calcGpsGoodForFlight(), NavEKF_core::ConstrainStates(), NavEKF2_core::ConstrainStates(), NavEKF_core::EstimateTerrainOffset(), NavEKF2_core::EstimateTerrainOffset(), AC_PI_2D::filt_hz(), AC_PID::filt_hz(), NavEKF2_core::fuseCompass(), NavEKF2_core::FuseMagnetometer(), NavEKF_core::FuseOptFlow(), NavEKF2_core::FuseOptFlow(), AC_Fence::get_breach_distance(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), NavEKF2_core::getEkfControlLimits(), NavEKF_core::getEkfControlLimits(), NavEKF2_core::getFlowDebug(), NavEKF_core::getFlowDebug(), NavEKF2_core::getHeightControlLimit(), NavEKF_core::getHeightControlLimit(), NavEKF2_core::getVariances(), NavEKF2_core::InitialiseVariables(), AC_PosControl::lean_angles_to_accel(), loop(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Airspeed::read(), NavEKF2_core::readDeltaVelocity(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), NavEKF_core::readHgtData(), NavEKF2_core::readHgtData(), NavEKF_core::readIMUData(), NavEKF2_core::readIMUData(), NavEKF_core::readRangeFinder(), NavEKF2_core::readRangeFinder(), NavEKF2_core::RecallIMU(), NavEKF_core::SelectFlowFusion(), NavEKF2_core::SelectFlowFusion(), show_data(), Airspeed_Calibration::update(), AC_Circle::update(), AC_Sprayer::update(), AP_TECS::update_50hz(), AP_MotorsMulticopter::update_lift_max_from_batt_voltage(), AP_L1_Control::update_loiter(), RC_Channel::update_min_max(), AP_TECS::update_pitch_throttle(), RangeFinder::update_pre_arm_check(), AP_L1_Control::update_waypoint(), and NavEKF2_core::writeOptFlowMeas().
#define min (a, b) ((a)<(b)?(a):(b))
Definition at line 225 of file AP_Math.h.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_InertialSensor::_init_gyro(), AP_GPS_NMEA::_parse_degrees(), AP_TECS::_update_pitch(), AC_PosControl::accel_to_lean_angles(), AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AC_WPNav::calc_loiter_desired_velocity(), AC_Circle::calc_velocities(), NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), AC_WPNav::calculate_wp_leash_length(), AP_InertialSensor::calibrate_accel(), NavEKF_core::EstimateTerrainOffset(), NavEKF2_core::EstimateTerrainOffset(), AC_PI_2D::get_i_shrink(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), NavEKF2_core::InitialiseFilterBootstrap(), AP_GPS_SBP::logging_log_raw_sbp(), loop(), AP_GPS_Backend::make_gps_time(), AP_MotorsMatrix::output_armed_stabilizing(), AC_PosControl::set_alt_target_from_climb_rate_ff(), show_data(), AP_L1_Control::turn_distance(), AC_Circle::update(), AC_Sprayer::update(), RC_Channel::update_min_max(), AP_TECS::update_pitch_throttle(), RangeFinder::update_pre_arm_check(), and AP_MotorsMulticopter::update_throttle_thr_mix().
#define NSEC_PER_SEC 1000000000ULL
Definition at line 237 of file AP_Math.h.
Referenced by hz_to_nsec(), nsec_to_hz(), and timespec_to_nsec().
#define NSEC_PER_USEC 1000ULL
Definition at line 238 of file AP_Math.h.
Referenced by nsec_to_usec(), and usec_to_nsec().
#define PI M_PI_F
Definition at line 29 of file AP_Math.h.
Referenced by Compass::calculate_heading(), check_result(), DigitalBiquadFilter< T >::compute_params(), PID::get_pid(), AC_Circle::init_start_angle(), loop(), rad_diff(), safe_asin(), setup(), test_quaternion_eulers(), AC_Circle::update(), and wrap_PI().
#define RAD_TO_DEG 57.295779513082320876798154814105f
Definition at line 36 of file AP_Math.h.
Referenced by AP_Mount_Alexmos::control_axis(), and degrees().
#define RAD_TO_DEG_DOUBLE 57.29577951308232286464772187173366546630859375
Definition at line 42 of file AP_Math.h.
Referenced by AP_GPS_GSOF::process_message(), and AP_GPS_SBF::process_message().
#define RadiansToCentiDegrees (x) ((x) * 5729.5779513082320876798154814105f)
Definition at line 44 of file AP_Math.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AP_L1_Control::bearing_error_cd(), and AP_L1_Control::nav_bearing_cd().
#define RADIUS_OF_EARTH 6378100
Definition at line 50 of file AP_Math.h.
Referenced by AP_Mission::mavlink_to_mission_cmd().
#define ROTATION_COMBINATION_SUPPORT 0
Definition at line 52 of file AP_Math.h.
#define WGS84_A 6378137.0
Definition at line 60 of file AP_Math.h.
Referenced by wgsecef2llh(), and wgsllh2ecef().
#define WGS84_B (WGS84_A*(1-WGS84_F))
Definition at line 66 of file AP_Math.h.
Referenced by wgsecef2llh().
#define WGS84_E (sqrt(2*WGS84_F - WGS84_F*WGS84_F))
Definition at line 68 of file AP_Math.h.
Referenced by wgsecef2llh(), and wgsllh2ecef().
#define WGS84_F (1/WGS84_IF)
Definition at line 64 of file AP_Math.h.
#define WGS84_IF 298.257223563
Definition at line 62 of file AP_Math.h.
Function Documentation
AP_PARAMDEFV (Matrix3f , Matrix3f , AP_PARAM_MATRIX3F)
AP_PARAMDEFV (Vector3f , Vector3f , AP_PARAM_VECTOR3F)
static float constrain_float (float amt, float low, float high) inline static
Definition at line 170 of file AP_Math.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), HALSITL::SITL_State::_ground_sonar(), AP_TECS::_update_pitch(), AP_TECS::_update_speed_demand(), AP_TECS::_update_throttle(), AP_TECS::_update_throttle_option(), AC_PosControl::accel_to_lean_angles(), AP_AHRS::add_trim(), AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw_smooth(), AC_AttitudeControl::angle_ef_roll_pitch_yaw(), DigitalLPF< T >::apply(), AP_MotorsMulticopter::apply_thrust_curve_and_volt_scaling(), AC_Circle::calc_velocities(), NavEKF_core::calcGpsGoodForFlight(), NavEKF2_core::calcGpsGoodForFlight(), NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), Compass::calculate_heading(), Compass::consistent(), NavEKF_core::ConstrainStates(), NavEKF2_core::ConstrainStates(), NavEKF_core::ConstrainVariances(), NavEKF2_core::ConstrainVariances(), NavEKF_core::CovariancePrediction(), NavEKF2_core::CovariancePrediction(), AP_MotorsMulticopter::current_limit_max_throttle(), AP_AHRS_DCM::drift_correction(), NavEKF_core::FuseAirspeed(), NavEKF2_core::FuseAirspeed(), NavEKF_core::FuseMagnetometer(), NavEKF2_core::FuseMagnetometer(), NavEKF_core::FuseOptFlow(), NavEKF2_core::FuseOptFlow(), NavEKF_core::FuseVelPosNED(), NavEKF2_core::FuseVelPosNED(), AC_AttitudeControl_Multi::get_althold_lean_angle_max(), AC_AttitudeControl_Heli::get_althold_lean_angle_max(), AC_AttitudeControl_Multi::get_boosted_throttle(), AP_MotorsMulticopter::get_compensation_gain(), AP_Declination::get_declination(), get_declination(), PID::get_pid_4500(), AC_InputManager_Heli::get_pilot_desired_collective(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), AC_PosControl::get_stopping_point_xy(), AC_PosControl::get_stopping_point_z(), AC_AttitudeControl::integrate_bf_rate_error_to_angle_errors(), Compass::learn_offsets(), longitude_scale(), AP_MotorsHeli_Single::move_actuators(), AP_L1_Control::nav_roll_cd(), RC_Channel::norm_input(), RC_Channel::norm_input_dz(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl::rate_bf_roll_pitch_yaw(), AC_AttitudeControl::rate_bf_to_motor_pitch(), AC_AttitudeControl::rate_bf_to_motor_roll(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_bf_to_motor_yaw(), AC_AttitudeControl::rate_bf_to_motor_yaw(), AC_AttitudeControl::rate_ef_roll_pitch_yaw(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), NavEKF_core::readHgtData(), NavEKF2_core::readHgtData(), NavEKF_core::readIMUData(), AP_RSSI::scale_and_constrain_float_rssi(), SITL::CRRCSim::send_servos_fixed_wing(), SITL::CRRCSim::send_servos_heli(), AC_PosControl::set_alt_target_from_climb_rate_ff(), AC_PosControl::set_alt_target_with_slew(), AP_Param::set_float(), AC_AttitudeControl_Heli::set_hover_roll_trim_scalar(), AC_InputManager_Heli::set_stab_col_ramp(), AP_Motors::set_throttle(), AP_AHRS::set_trim(), AC_WPNav::set_wp_origin_and_destination(), AP_AutoTune::start(), Airspeed_Calibration::update(), SITL::Gimbal::update(), AP_Airspeed::update_calibration(), AC_AttitudeControl::update_ef_pitch_angle_and_error(), AC_AttitudeControl::update_ef_roll_angle_and_error(), AC_AttitudeControl::update_ef_yaw_angle_and_error(), AP_L1_Control::update_heading_hold(), AP_MotorsMulticopter::update_lift_max_from_batt_voltage(), AP_L1_Control::update_loiter(), SITL::Tracker::update_position_servos(), AC_AttitudeControl::update_rate_bf_targets(), AP_Mount_Backend::update_targets_from_rc(), AP_MotorsMulticopter::update_throttle_filter(), AP_MotorsHeli::update_throttle_filter(), AP_MotorsMulticopter::update_throttle_thr_mix(), AP_AHRS::update_trig(), AP_L1_Control::update_waypoint(), NavEKF_core::UpdateStrapdownEquationsNED(), NavEKF2_core::writeOptFlowMeas(), and NavEKF_core::writeOptFlowMeas().
static int16_t constrain_int16 (int16_t amt, int16_t low, int16_t high) inline static
Definition at line 182 of file AP_Math.h.
Referenced by RC_Channel::calc_pwm(), AP_MotorsHeli_Single::calculate_scalars(), AC_InputManager_Heli::get_pilot_desired_collective(), AC_AttitudeControl_Heli::get_roll_trim(), AP_MotorsHeli_Single::move_yaw(), AP_MotorsMatrix::output_armed_stabilizing(), RC_Channel::pwm_to_range_dz(), NavEKF_core::readGpsData(), AP_Camera::relay_pic(), AP_Camera::servo_pic(), AP_MotorsHeli_Single::set_delta_phase_angle(), RC_Channel_aux::set_radio(), and RC_Channel_aux::set_radio_trimmed().
static int32_t constrain_int32 (int32_t amt, int32_t low, int32_t high) inline static
Definition at line 187 of file AP_Math.h.
static float degrees (float rad) inline static
Definition at line 200 of file AP_Math.h.
Referenced by AP_InertialSensor::_calculate_trim(), AP_TECS::_update_pitch(), SITL::JSBSim::create_templates(), SITL::Aircraft::fill_fdm(), DataFlash_Class::Log_Write_AHRS2(), AP_L1_Control::nav_roll_cd(), AP_GPS_PX4::read(), SITL::JSBSim::recv_fdm(), AP_GPS::setHIL(), AP_Mount_Servo::stabilize(), SITL::Tracker::update(), AP_AHRS::update_cd_values(), and SITL::Aircraft::update_position().
int32_t get_bearing_cd (const struct Location & loc1, const struct Location & loc2)
Definition at line 72 of file location.cpp.
Referenced by AP_Mission::get_next_ground_course_cd(), test_one_offset(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
float get_distance (const struct Location & loc1, const struct Location & loc2)
Definition at line 58 of file location.cpp.
Referenced by AP_Rally::find_nearest_rally_point(), get_distance_cm(), AP_Mission::get_landing_sequence_start(), test_accuracy(), test_one_offset(), AP_Limit_Geofence::triggered(), and AP_Camera::update_location().
uint32_t get_distance_cm (const struct Location & loc1, const struct Location & loc2)
Definition at line 66 of file location.cpp.
uint32_t hz_to_nsec (uint32_t freq) inline
Definition at line 240 of file AP_Math.h.
Referenced by Linux::PWM_Sysfs::set_freq().
bool inverse (float x[], float y[], uint16_t dim)
Definition at line 445 of file matrix_alg.cpp.
Referenced by CompassCalibrator::run_ellipsoid_fit(), and CompassCalibrator::run_sphere_fit().
static bool is_equal (const float fVal1, const float fVal2) inline static
Definition at line 75 of file AP_Math.h.
Referenced by AP_InertialSensor::accel_calibrated_ok_all(), AP_Camera::control(), AP_Param::convert_old_parameter(), AP_AHRS_DCM::drift_correction(), GCS_MAVLINK::handle_param_set(), AC_Circle::init_start_angle(), Vector2< T >::operator!=(), Vector3< T >::operator!=(), Vector2< T >::operator==(), Vector3< T >::operator==(), NavEKF_core::readMagData(), AP_Param::save(), AC_Circle::set_rate(), Compass::setHIL(), AP_L1_Control::update_waypoint(), and AP_AHRS_DCM::yaw_error_compass().
static bool is_zero (const float fVal1) inline static
Definition at line 78 of file AP_Math.h.
Referenced by AP_InertialSensor::_calibrate_find_delta(), AP_Compass_LSM303D::_read_raw(), AP_Compass_AK8963::_update(), AP_InertialSensor::accel_calibrated_ok_all(), AC_AttitudeControl::accel_limiting(), AC_WPNav::advance_spline_target_along_track(), DigitalBiquadFilter< T >::apply(), AP_Arming::board_voltage_checks(), AC_PI_2D::calc_filt_alpha(), AC_WPNav::calc_loiter_desired_velocity(), AC_WPNav::calculate_wp_leash_length(), AC_Fence::check_fence(), Compass::configured(), AP_Compass_Backend::correct_field(), AP_AHRS_DCM::drift_correction(), AC_AttitudeControl::frame_conversion_bf_to_ef(), AC_Circle::get_closest_point_on_circle(), AP_Baro::get_EAS2TAS(), AC_PID::get_filt_alpha(), AC_PI_2D::get_i(), AC_PID::get_i(), AC_PI_2D::get_i_shrink(), AC_HELI_PID::get_leaky_i(), AC_PosControl::get_stopping_point_xy(), inverse3x3(), inverse4x4(), inversenxn(), location_offset(), AP_MotorsTri::output_armed_stabilizing(), AP_RSSI::scale_and_constrain_float_rssi(), AC_PosControl::set_alt_target_from_climb_rate_ff(), AC_WPNav::set_wp_origin_and_destination(), AC_PosControl::shift_pos_xy_target(), AC_AttitudeControl::sqrt_controller(), AP_Mount_Servo::stabilize(), AP_Baro::update(), AC_Circle::update(), AP_Camera::update_location(), AP_AHRS::update_trig(), and wgsecef2llh().
Vector2f location_diff (const struct Location & loc1, const struct Location & loc2)
Definition at line 145 of file location.cpp.
Referenced by NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF2_core::getPosNED(), NavEKF_core::getPosNED(), location_path_proportion(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), SITL::CRRCSim::recv_fdm(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
void location_offset (struct Location & loc, float ofs_north, float ofs_east)
Definition at line 131 of file location.cpp.
Referenced by AP_AHRS_DCM::get_position(), NavEKF2_core::getLLH(), NavEKF_core::getLLH(), location_update(), and test_one_offset().
bool location_passed_point (const struct Location & location, const struct Location & point1, const struct Location & point2)
Definition at line 86 of file location.cpp.
Referenced by test_passed_waypoint().
float location_path_proportion (const struct Location & location, const struct Location & point1, const struct Location & point2)
Definition at line 100 of file location.cpp.
Referenced by location_passed_point().
void location_update (struct Location & loc, float bearing, float distance)
Definition at line 121 of file location.cpp.
Referenced by AP_AHRS_DCM::get_position(), and SITL::Aircraft::update_position().
bool locations_are_same (const struct Location & loc1, const struct Location & loc2)
Definition at line 224 of file location.cpp.
float longitude_scale (const struct Location & loc)
Definition at line 33 of file location.cpp.
Referenced by get_bearing_cd(), get_distance(), location_diff(), and location_offset().
static float maxf (float a, float b) inline static
Definition at line 227 of file AP_Math.h.
Referenced by NavEKF_core::readIMUData().
static float minf (float a, float b) inline static
Definition at line 232 of file AP_Math.h.
uint32_t nsec_to_hz (uint32_t usec) inline
Definition at line 245 of file AP_Math.h.
Referenced by Linux::PWM_Sysfs::get_freq().
uint32_t nsec_to_usec (uint32_t nsec) inline
Definition at line 255 of file AP_Math.h.
Referenced by Linux::RCOutput_Sysfs::read().
void print_latlon (AP_HAL::BetterStream * s, int32_t lat_or_lon)
Definition at line 231 of file location.cpp.
Referenced by DataFlash_Backend::_print_log_entry(), and loop().
static float pythagorous2 (float a, float b) inline static
Definition at line 210 of file AP_Math.h.
Referenced by AP_InertialSensor::_calculate_trim(), HALSITL::SITL_State::_update_gps_mtk(), HALSITL::SITL_State::_update_gps_mtk16(), HALSITL::SITL_State::_update_gps_mtk19(), HALSITL::SITL_State::_update_gps_nmea(), HALSITL::SITL_State::_update_gps_ubx(), AP_AHRS_DCM::_yaw_gain(), AC_PosControl::accel_to_lean_angles(), AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), NavEKF_core::alignMagStateDeclination(), NavEKF2_core::alignMagStateDeclination(), AP_Mount_Backend::calc_angle_to_location(), AC_WPNav::calc_loiter_desired_velocity(), NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), AC_WPNav::calculate_wp_leash_length(), AP_AHRS_DCM::drift_correction(), AC_Circle::get_closest_point_on_circle(), get_distance(), AC_PosControl::get_stopping_point_xy(), AC_WPNav::get_wp_distance_to_destination(), Vector2< T >::length(), AP_MotorsHeli_Single::move_actuators(), AC_PosControl::pos_to_rate_xy(), AP_AHRS_DCM::reset(), AP_GPS::setHIL(), NavEKF_core::setWindVelStates(), AC_Sprayer::update(), NavEKF_core::UpdateStrapdownEquationsNED(), and NavEKF2_core::UpdateStrapdownEquationsNED().
static float pythagorous3 (float a, float b, float c) inline static
Definition at line 215 of file AP_Math.h.
Referenced by HALSITL::SITL_State::_update_gps_ubx(), NavEKF_core::FuseAirspeed(), NavEKF2_core::FuseAirspeed(), Vector3< T >::length(), and Airspeed_Calibration::update().
static float radians (float deg) inline static
Definition at line 195 of file AP_Math.h.
Referenced by AP_InertialSensor::_calculate_trim(), AP_PitchController::_get_coordination_rate_offset(), HALSITL::SITL_State::_ground_sonar(), HALSITL::SITL_State::_update_compass(), HALSITL::SITL_State::_update_flow(), HALSITL::SITL_State::_update_ins(), OpticalFlow_backend::_yawAngleRad(), AP_MotorsMatrix::add_motor(), SITL::Aircraft::Aircraft(), NavEKF_core::alignYawGPS(), AP_Mount_Backend::angle_input_rad(), SITL::SimRover::calc_lat_accel(), NavEKF_core::calcEarthRateNED(), NavEKF2_core::calcEarthRateNED(), AP_MotorsHeli_Single::calculate_roll_pitch_collective_factors(), NavEKF_core::CovarianceInit(), NavEKF2_core::CovarianceInit(), SITL::Gimbal::Gimbal(), AP_AHRS::groundspeed_vector(), SITL::Helicopter::Helicopter(), AP_Arming::ins_checks(), location_update(), NavEKF2_core::resetGyroBias(), NavEKF_core::resetGyroBias(), SITL::JSBSim::send_servos(), AP_Mount_Backend::set_angle_targets(), Compass::set_initial_location(), SITL::Aircraft::set_yaw_degrees(), SITL::SITL::simstate_send(), test_euler(), SITL::SimRover::turn_circle(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::Helicopter::update(), SITL::Balloon::update(), SITL::SimRover::update(), SITL::MultiCopter::update(), AP_L1_Control::update_heading_hold(), AP_TECS::update_pitch_throttle(), AP_Mount_Backend::update_targets_from_rc(), and AP_L1_Control::update_waypoint().
float safe_asin (float v)
Definition at line 7 of file AP_Math.cpp.
Referenced by Quaternion::get_euler_pitch(), and Matrix3< T >::to_euler().
float safe_sqrt (float v)
Definition at line 26 of file AP_Math.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AC_WPNav::advance_spline_target_along_track(), AP_MotorsMulticopter::apply_thrust_curve_and_volt_scaling(), AC_Circle::calc_velocities(), AP_Baro::get_EAS2TAS(), AC_WPNav::get_slow_down_speed(), AP_InertialSensor::get_vibration_levels(), AC_PosControl::pos_to_rate_xy(), AP_GPS_SBF::process_message(), AC_PosControl::set_alt_target_from_climb_rate_ff(), AC_AttitudeControl::sqrt_controller(), and AP_AHRS::update_trig().
static float sq (float v) inline static
Definition at line 205 of file AP_Math.h.
Referenced by NavEKF_core::alignYawGPS(), NavEKF2_core::alignYawGPS(), AC_WPNav::calc_loiter_desired_velocity(), CompassCalibrator::calc_mean_squared_residuals(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF_core::ConstrainVariances(), NavEKF2_core::ConstrainVariances(), NavEKF_core::CovarianceInit(), NavEKF2_core::CovarianceInit(), NavEKF_core::CovariancePrediction(), NavEKF2_core::CovariancePrediction(), NavEKF2_core::detectFlight(), NavEKF_core::EstimateTerrainOffset(), NavEKF2_core::EstimateTerrainOffset(), CompassCalibrator::fit_acceptable(), Quaternion::from_axis_angle_fast(), NavEKF_core::FuseAirspeed(), NavEKF2_core::FuseAirspeed(), SmallEKF::fuseCompass(), NavEKF2_core::fuseCompass(), NavEKF_core::FuseMagnetometer(), NavEKF2_core::FuseMagnetometer(), NavEKF_core::FuseOptFlow(), NavEKF2_core::FuseOptFlow(), NavEKF_core::FuseSideslip(), NavEKF2_core::FuseSideslip(), SmallEKF::fuseVelocity(), NavEKF_core::FuseVelPosNED(), NavEKF2_core::FuseVelPosNED(), AP_Baro::get_air_density_ratio(), NavEKF2_core::healthy(), NavEKF_core::healthy(), Quaternion::length(), location_path_proportion(), SmallEKF::predictCovariance(), pythagorous2(), pythagorous3(), NavEKF2_core::resetGyroBias(), NavEKF_core::resetGyroBias(), Quaternion::rotate_fast(), SmallEKF::RunEKF(), NavEKF_core::SelectFlowFusion(), NavEKF2_core::SelectFlowFusion(), NavEKF_core::SetFlightAndFusionModes(), AC_AttitudeControl::sqrt_controller(), Quaternion::to_axis_angle(), AP_L1_Control::turn_distance(), Airspeed_Calibration::update(), AP_Airspeed::update_calibration(), AP_L1_Control::update_loiter(), and SITL::Aircraft::update_position().
uint32_t usec_to_nsec (uint32_t usec) inline
Definition at line 250 of file AP_Math.h.
Referenced by Linux::RCOutput_Sysfs::write().
void wgsecef2llh (const Vector3d & ecef, Vector3d & llh)
Definition at line 259 of file location.cpp.
Referenced by test_wgs_conversion_functions().
void wgsllh2ecef (const Vector3d & llh, Vector3d & ecef)
Definition at line 249 of file location.cpp.
Referenced by test_wgs_conversion_functions().
int32_t wrap_180_cd (int32_t error)
Definition at line 168 of file location.cpp.
Referenced by AP_L1_Control::_prevent_indecision(), AP_L1_Control::nav_bearing_cd(), AP_L1_Control::target_bearing_cd(), test_wrap_cd(), AC_AttitudeControl::update_ef_pitch_angle_and_error(), AC_AttitudeControl::update_ef_roll_angle_and_error(), AC_AttitudeControl::update_ef_yaw_angle_and_error(), AP_L1_Control::update_heading_hold(), and AP_AHRS_DCM::use_compass().
float wrap_180_cd_float (float angle)
Definition at line 196 of file location.cpp.
Referenced by AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw_smooth(), AC_AttitudeControl::angle_ef_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and AC_AttitudeControl::rate_bf_roll_pitch_yaw().
int32_t wrap_360_cd (int32_t error)
Definition at line 154 of file location.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SIRF::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_NMEA::_term_complete(), DataFlash_Class::Log_Write_AHRS2(), SITL::SITL::Log_Write_SIMSTATE(), AP_GPS_SBF::process_message(), AP_GPS_PX4::read(), AP_GPS_MTK::read(), AP_GPS_MTK19::read(), AP_GPS::setHIL(), test_wrap_cd(), and AC_AttitudeControl::update_ef_yaw_angle_and_error().
float wrap_360_cd_float (float angle)
Definition at line 182 of file location.cpp.
Referenced by AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl::rate_bf_roll_pitch_yaw(), and AC_AttitudeControl::shift_ef_yaw_target().
float wrap_PI (float angle_in_radians)
Definition at line 210 of file location.cpp.
Referenced by NavEKF_core::alignYawGPS(), NavEKF2_core::alignYawGPS(), AP_Mount_Backend::calc_angle_to_location(), NavEKF_core::calcQuatAndFieldStates(), NavEKF2_core::calcQuatAndFieldStates(), AP_AHRS_DCM::drift_correction_yaw(), AC_Circle::init_start_angle(), test_wrap_cd(), Quaternion::to_axis_angle(), and AC_Circle::update().