APM:Libraries: libraries/AP_HAL_FLYMAPLE/GPIO.cpp File Reference
GPIO.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "GPIO.h"
#include "FlymapleWirish.h"
Functions
void libmaple_pinMode (uint8_t pin, uint8_t output)
uint8_t libmaple_digitalRead (uint8_t pin)
void libmaple_digitalWrite (uint8_t pin, uint8_t value)
Function Documentation
uint8_t libmaple_digitalRead (uint8_t pin)
Definition at line 34 of file GPIO.cpp.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO::read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEDigitalSource::read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO::toggle(), and AP_HAL_FLYMAPLE_NS::FLYMAPLEDigitalSource::toggle().
void libmaple_digitalWrite (uint8_t pin, uint8_t value)
Definition at line 38 of file GPIO.cpp.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO::toggle(), AP_HAL_FLYMAPLE_NS::FLYMAPLEDigitalSource::toggle(), AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO::write(), and AP_HAL_FLYMAPLE_NS::FLYMAPLEDigitalSource::write().
void libmaple_pinMode (uint8_t pin, uint8_t output)
Definition at line 28 of file GPIO.cpp.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLEDigitalSource::mode(), and AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO::pinMode().