APM:Libraries: libraries/AP_HAL_FLYMAPLE/examples/Scheduler/Scheduler.cpp File Reference
Scheduler.cpp File Reference
#include <AP_Common/AP_Common.h>
#include <AP_Math/AP_Math.h>
#include <AP_Param/AP_Param.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL_FLYMAPLE/AP_HAL_FLYMAPLE.h>
Macros
#define DELAY_TOGGLE_PIN 15 /* A0 = pin 15 */
#define FAILSAFE_TOGGLE_PIN 16 /* A1 = pin 16 */
#define SCHEDULED_TOGGLE_PIN_1 17 /* A2 = pin 17 */
#define SCHEDULED_TOGGLE_PIN_2 18 /* A3 = pin 18 */
Functions
void delay_toggle ()
void failsafe_toggle (void)
void schedule_toggle_1 (void)
void schedule_toggle_2 (void)
void schedule_toggle_hang (void)
void setup_pin (int pin_num)
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Macro Definition Documentation
#define DELAY_TOGGLE_PIN 15 /* A0 = pin 15 */
Definition at line 16 of file Scheduler.cpp.
Referenced by delay_toggle(), and setup().
#define FAILSAFE_TOGGLE_PIN 16 /* A1 = pin 16 */
Definition at line 17 of file Scheduler.cpp.
Referenced by failsafe_toggle(), and setup().
#define SCHEDULED_TOGGLE_PIN_1 17 /* A2 = pin 17 */
Definition at line 18 of file Scheduler.cpp.
Referenced by schedule_toggle_1(), and setup().
#define SCHEDULED_TOGGLE_PIN_2 18 /* A3 = pin 18 */
Definition at line 19 of file Scheduler.cpp.
Referenced by schedule_toggle_2(), schedule_toggle_hang(), and setup().
Function Documentation
AP_HAL_MAIN ()
void delay_toggle ()
Definition at line 21 of file Scheduler.cpp.
void failsafe_toggle (void)
Definition at line 28 of file Scheduler.cpp.
Referenced by setup().
void loop (void)
Definition at line 114 of file Scheduler.cpp.
void schedule_toggle_1 (void)
Definition at line 36 of file Scheduler.cpp.
Referenced by setup().
void schedule_toggle_2 (void)
Definition at line 43 of file Scheduler.cpp.
Referenced by setup().
void schedule_toggle_hang (void)
Definition at line 50 of file Scheduler.cpp.
Referenced by setup().
void setup (void)
Definition at line 63 of file Scheduler.cpp.
void setup_pin (int pin_num)
Definition at line 55 of file Scheduler.cpp.
Referenced by setup().
Variable Documentation
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 9 of file Scheduler.cpp.