APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/testsuite.h File Reference
testsuite.h File Reference
MAVLink comm protocol testsuite generated from ardupilotmega.xml.
#include "../common/testsuite.h"
Macros
#define MAVLINK_TEST_ALL
Functions
static void mavlink_test_common (uint8_t, uint8_t, mavlink_message_t *last_msg)
static void mavlink_test_ardupilotmega (uint8_t, uint8_t, mavlink_message_t *last_msg)
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_sensor_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_mag_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_meminfo (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ap_adc (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_digicam_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_digicam_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mount_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mount_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mount_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_fence_point (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_fence_fetch_point (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_fence_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ahrs (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_simstate (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hwstatus (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_radio (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_limits_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_wind (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_data16 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_data32 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_data64 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_data96 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rangefinder (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_airspeed_autocal (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rally_point (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rally_fetch_point (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_compassmot_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ahrs2 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_camera_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_camera_feedback (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_battery2 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ahrs3 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_autopilot_version_request (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_led_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mag_cal_progress (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mag_cal_report (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ekf_status_report (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_pid_tuning (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_report (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_reset (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_axis_calibration_progress (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_set_home_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_home_offset_calibration_result (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_set_factory_parameters (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_factory_parameters_loaded (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_erase_firmware_and_config (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_perform_factory_tests (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_report_factory_tests_progress (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_request_axis_calibration_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_report_axis_calibration_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gimbal_request_axis_calibration (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gopro_heartbeat (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gopro_get_request (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gopro_get_response (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gopro_set_request (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gopro_set_response (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rpm (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
Detailed Description
MAVLink comm protocol testsuite generated from ardupilotmega.xml.
See also
http://qgroundcontrol.org/mavlink/
Definition in file testsuite.h.
Macro Definition Documentation
#define MAVLINK_TEST_ALL
Definition at line 13 of file testsuite.h.
Function Documentation
static void mavlink_test_ahrs (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 607 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_ahrs2 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1321 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_ahrs3 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1519 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_airspeed_autocal (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1122 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 17 of file testsuite.h.
static void mavlink_test_ap_adc (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 172 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_ardupilotmega (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2777 of file testsuite.h.
Referenced by mavlink_test_all().
static void mavlink_test_autopilot_version_request (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1571 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_battery2 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1475 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_camera_feedback (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1420 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_camera_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1369 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_common (uint8_t , uint8_t , mavlink_message_t * last_msg) static
Referenced by mavlink_test_all().
static void mavlink_test_compassmot_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1273 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_data16 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 898 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_data32 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 943 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_data64 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 988 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_data96 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1033 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_digicam_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 220 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_digicam_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 273 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_ekf_status_report (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1770 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_fence_fetch_point (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 516 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_fence_point (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 468 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_fence_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 561 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_axis_calibration_progress (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2012 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1921 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_erase_firmware_and_config (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2243 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_factory_parameters_loaded (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2200 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_home_offset_calibration_result (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2101 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_perform_factory_tests (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2288 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_report (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1867 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_report_axis_calibration_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2422 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_report_factory_tests_progress (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2332 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_request_axis_calibration (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2467 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_request_axis_calibration_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2378 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_reset (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1968 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_set_factory_parameters (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2144 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gimbal_set_home_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2057 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gopro_get_request (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2554 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gopro_get_response (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2599 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gopro_heartbeat (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2511 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gopro_set_request (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2643 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_gopro_set_response (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2689 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_hwstatus (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 709 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_led_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1615 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_limits_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 802 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mag_cal_progress (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1663 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mag_cal_report (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1714 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_meminfo (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 128 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mount_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 325 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mount_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 373 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mount_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 421 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_pid_tuning (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1818 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_radio (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 753 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_rally_fetch_point (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1228 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_rally_point (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1176 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_rangefinder (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1078 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_rpm (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2733 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_sensor_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 27 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_set_mag_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 81 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_simstate (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 656 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_wind (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 853 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().