APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/checksum.h File Reference
checksum.h File Reference
#include <stdint.h>
Macros
#define _CHECKSUM_H_
#define X25_INIT_CRC 0xffff
#define X25_VALIDATE_CRC 0xf0b8
Functions
static void crc_accumulate (uint8_t data, uint16_t *crcAccum)
Accumulate the X.25 CRC by adding one char at a time.
static void crc_init (uint16_t *crcAccum)
Initiliaze the buffer for the X.25 CRC.
static uint16_t crc_calculate (const uint8_t *pBuffer, uint16_t length)
Calculates the X.25 checksum on a byte buffer.
static void crc_accumulate_buffer (uint16_t *crcAccum, const char *pBuffer, uint16_t length)
Accumulate the X.25 CRC by adding an array of bytes.
Macro Definition Documentation
#define _CHECKSUM_H_
Definition at line 6 of file checksum.h.
#define X25_INIT_CRC 0xffff
CALCULATE THE CHECKSUM
Definition at line 21 of file checksum.h.
Referenced by crc_init().
#define X25_VALIDATE_CRC 0xf0b8
Definition at line 22 of file checksum.h.
Function Documentation
static void crc_accumulate (uint8_t data, uint16_t * crcAccum) inline static
Accumulate the X.25 CRC by adding one char at a time.
The checksum function adds the hash of one char at a time to the 16 bit checksum (uint16_t).
Parameters
data new char to hash
crcAccum the already accumulated checksum
Definition at line 34 of file checksum.h.
Referenced by crc_accumulate_buffer(), crc_calculate(), mavlink_finalize_message_chan(), and mavlink_update_checksum().
static void crc_accumulate_buffer (uint16_t * crcAccum, const char * pBuffer, uint16_t length) inline static
Accumulate the X.25 CRC by adding an array of bytes.
The checksum function adds the hash of one char at a time to the 16 bit checksum (uint16_t).
Parameters
data new bytes to hash
crcAccum the already accumulated checksum
Definition at line 84 of file checksum.h.
Referenced by mavlink_finalize_message_chan().
static uint16_t crc_calculate (const uint8_t * pBuffer, uint16_t length) inline static
Calculates the X.25 checksum on a byte buffer.
Parameters
pBuffer buffer containing the byte array to hash
length length of the byte array
Returns
the checksum over the buffer bytes
Definition at line 64 of file checksum.h.
Referenced by mavlink_finalize_message_chan(), AP_Mount_SToRM32_serial::parse_reply(), and AP_Mount_SToRM32_serial::send_target_angles().
static void crc_init (uint16_t * crcAccum) inline static
Initiliaze the buffer for the X.25 CRC.
Parameters
crcAccum the 16 bit X.25 CRC
Definition at line 51 of file checksum.h.
Referenced by crc_calculate(), and mavlink_start_checksum().