APM:Libraries: Linux::GPIO_Sysfs Class Reference
Linux::GPIO_Sysfs Class Reference
#include <GPIO_Sysfs.h>
Public Member Functions
void init ()
void pinMode (uint8_t vpin, uint8_t output) override
uint8_t read (uint8_t vpin) override
void write (uint8_t vpin, uint8_t value) override
void toggle (uint8_t vpin) override
AP_HAL::DigitalSource * channel (uint16_t vpin) override
int8_t analogPinToDigitalPin (uint8_t vpin) override
bool attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode) override
bool usb_connected () override
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
virtual void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
virtual void setPWMPeriod (uint8_t pin, uint32_t time_us)
virtual void setPWMDuty (uint8_t pin, uint8_t percent)
Static Public Member Functions
static GPIO_Sysfs * from (AP_HAL::GPIO *gpio)
static bool export_pin (uint8_t vpin)
static bool export_pins (uint8_t vpins[], size_t num_vpins)
Static Public Attributes
static const unsigned pin_table []
static const uint8_t n_pins = _MINNOW_GPIO_MAX
Protected Member Functions
void _pinMode (unsigned int pin, uint8_t output)
int _open_pin_value (unsigned int pin, int flags)
Friends
class Linux::DigitalSource_Sysfs
Detailed Description
Generic implementation of AP_HAL::GPIO for Linux based boards.
Definition at line 28 of file GPIO_Sysfs.h.
Member Function Documentation
int GPIO_Sysfs::_open_pin_value (unsigned int pin, int flags) protected
Definition at line 105 of file GPIO_Sysfs.cpp.
Referenced by read(), and write().
void GPIO_Sysfs::_pinMode (unsigned int pin, uint8_t output) protected
Definition at line 85 of file GPIO_Sysfs.cpp.
Referenced by pinMode().
int8_t GPIO_Sysfs::analogPinToDigitalPin (uint8_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 169 of file GPIO_Sysfs.cpp.
bool GPIO_Sysfs::attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode) override virtual
Implements AP_HAL::GPIO.
Definition at line 197 of file GPIO_Sysfs.cpp.
AP_HAL::DigitalSource * GPIO_Sysfs::channel (uint16_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 174 of file GPIO_Sysfs.cpp.
bool GPIO_Sysfs::export_pin (uint8_t vpin) static
Definition at line 208 of file GPIO_Sysfs.cpp.
Referenced by channel().
bool GPIO_Sysfs::export_pins (uint8_t vpins[], size_t num_vpins) static
Definition at line 214 of file GPIO_Sysfs.cpp.
Referenced by export_pin().
static GPIO_Sysfs* Linux::GPIO_Sysfs::from (AP_HAL::GPIO * gpio) inline static
Definition at line 35 of file GPIO_Sysfs.h.
Referenced by Linux::DigitalSource_Sysfs::mode().
void GPIO_Sysfs::init (void) virtual
Implements AP_HAL::GPIO.
Definition at line 73 of file GPIO_Sysfs.cpp.
void GPIO_Sysfs::pinMode (uint8_t vpin, uint8_t output) override virtual
Implements AP_HAL::GPIO.
Definition at line 77 of file GPIO_Sysfs.cpp.
uint8_t GPIO_Sysfs::read (uint8_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 121 of file GPIO_Sysfs.cpp.
Referenced by toggle().
void GPIO_Sysfs::toggle (uint8_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 164 of file GPIO_Sysfs.cpp.
bool GPIO_Sysfs::usb_connected (void) override virtual
Implements AP_HAL::GPIO.
Definition at line 203 of file GPIO_Sysfs.cpp.
void GPIO_Sysfs::write (uint8_t vpin, uint8_t value) override virtual
Implements AP_HAL::GPIO.
Definition at line 146 of file GPIO_Sysfs.cpp.
Referenced by toggle().
Friends And Related Function Documentation
friend class Linux::DigitalSource_Sysfs friend
Definition at line 29 of file GPIO_Sysfs.h.
Member Data Documentation
const uint8_t Linux::GPIO_Sysfs::n_pins = _MINNOW_GPIO_MAX static
Definition at line 33 of file GPIO_Sysfs.h.
Referenced by channel(), export_pins(), pinMode(), read(), and write().
const unsigned Linux::GPIO_Sysfs::pin_table static
Initial value:
= {
    [MINNOW_GPIO_SPI_CS] =    476,
    [MINNOW_GPIO_SPI_MISO] =  477,
    [MINNOW_GPIO_SPI_MOSI] =  478,
    [MINNOW_GPIO_SPI_CLK] =   479,
    [MINNOW_GPIO_I2C_SCL] =   499,
    [MINNOW_GPIO_I2C_SDA] =   498,
    [MINNOW_GPIO_UART2_TXD] = 485,
    [MINNOW_GPIO_UART2_RXD] = 484,
    [MINNOW_GPIO_S5_0] =      338,
    [MINNOW_GPIO_S5_1] =      339,
    [MINNOW_GPIO_S5_2] =      340,
    [MINNOW_GPIO_UART1_TXD] = 481,
    [MINNOW_GPIO_UART1_RXD] = 480,
    [MINNOW_GPIO_UART1_CTS] = 483,
    [MINNOW_GPIO_UART1_RTS] = 482,
    [MINNOW_GPIO_I2S_CLK] =   472,
    [MINNOW_GPIO_I2S_FRM] =   473,
    [MINNOW_GPIO_I2S_DO] =    475,
    [MINNOW_GPIO_I2S_DI] =    474,
    [MINNOW_GPIO_PWM0] =      504,
    [MINNOW_GPIO_PWM1] =      505,
    [MINNOW_GPIO_IBL_8254] =  464,
}
Definition at line 32 of file GPIO_Sysfs.h.
Referenced by channel(), export_pins(), pinMode(), read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/GPIO_Sysfs.h
libraries/AP_HAL_Linux/GPIO_Minnow.cpp
libraries/AP_HAL_Linux/GPIO_Sysfs.cpp