APM:Libraries: AP_InertialSensor_HIL Class Reference
AP_InertialSensor_HIL Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_InertialSensor_HIL.h>
Public Member Functions
AP_InertialSensor_HIL (AP_InertialSensor &imu)
bool update ()
bool gyro_sample_available (void)
bool accel_sample_available (void)
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void start ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t product_id (void) const
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Member Functions
bool _init_sensor (void)
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
void _set_accel_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
int16_t _product_id
int16_t _id = -1
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 8 of file AP_InertialSensor_HIL.h.
Constructor & Destructor Documentation
AP_InertialSensor_HIL::AP_InertialSensor_HIL (AP_InertialSensor & imu)
Definition at line 8 of file AP_InertialSensor_HIL.cpp.
Referenced by detect().
Member Function Documentation
bool AP_InertialSensor_HIL::_init_sensor (void) private
Definition at line 29 of file AP_InertialSensor_HIL.cpp.
Referenced by detect().
bool AP_InertialSensor_HIL::accel_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 17 of file AP_InertialSensor_HIL.h.
AP_InertialSensor_Backend * AP_InertialSensor_HIL::detect (AP_InertialSensor & imu) static
Definition at line 16 of file AP_InertialSensor_HIL.cpp.
Referenced by AP_InertialSensor::detect_backends().
bool AP_InertialSensor_HIL::gyro_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 16 of file AP_InertialSensor_HIL.h.
bool AP_InertialSensor_HIL::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 41 of file AP_InertialSensor_HIL.cpp.
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_HIL.h
libraries/AP_InertialSensor/AP_InertialSensor_HIL.cpp