APM:Libraries: DFMessageWriter_WriteEntireMission Class Reference
DFMessageWriter_WriteEntireMission Class Reference
#include <DFMessageWriter.h>
Public Member Functions
DFMessageWriter_WriteEntireMission (DataFlash_Class &DataFlash)
void reset ()
void process ()
void set_mission (const AP_Mission *mission)
Public Member Functions inherited from DFMessageWriter
DFMessageWriter (DataFlash_Class &DataFlash)
virtual bool finished ()
Private Types
enum entire_mission_blockwriter_stage { em_blockwriter_stage_init, em_blockwriter_stage_write_new_mission_message, em_blockwriter_stage_write_mission_items, em_blockwriter_stage_done }
Private Attributes
const AP_Mission * _mission = nullptr
uint16_t _mission_number_to_send = 0
entire_mission_blockwriter_stage stage = em_blockwriter_stage_init
Additional Inherited Members
Protected Attributes inherited from DFMessageWriter
bool _finished = false
DataFlash_Class & _DataFlash
Detailed Description
Definition at line 47 of file DFMessageWriter.h.
Member Enumeration Documentation
enum DFMessageWriter_WriteEntireMission::entire_mission_blockwriter_stage private
Enumerator
em_blockwriter_stage_init
em_blockwriter_stage_write_new_mission_message
em_blockwriter_stage_write_mission_items
em_blockwriter_stage_done
Definition at line 58 of file DFMessageWriter.h.
Constructor & Destructor Documentation
DFMessageWriter_WriteEntireMission::DFMessageWriter_WriteEntireMission (DataFlash_Class & DataFlash) inline
Definition at line 49 of file DFMessageWriter.h.
Member Function Documentation
void DFMessageWriter_WriteEntireMission::process () virtual
Implements DFMessageWriter.
Definition at line 153 of file DFMessageWriter.cpp.
Referenced by DataFlash_Class::Log_Write_EntireMission(), and DFMessageWriter_DFLogStart::process().
void DFMessageWriter_WriteEntireMission::reset () virtual
Implements DFMessageWriter.
Definition at line 194 of file DFMessageWriter.cpp.
Referenced by DFMessageWriter_DFLogStart::reset().
void DFMessageWriter_WriteEntireMission::set_mission (const AP_Mission * mission)
Definition at line 202 of file DFMessageWriter.cpp.
Referenced by DataFlash_Class::Log_Write_EntireMission(), and DFMessageWriter_DFLogStart::set_mission().
Member Data Documentation
const AP_Mission* DFMessageWriter_WriteEntireMission::_mission = nullptr private
Definition at line 65 of file DFMessageWriter.h.
Referenced by process(), and set_mission().
uint16_t DFMessageWriter_WriteEntireMission::_mission_number_to_send = 0 private
Definition at line 66 of file DFMessageWriter.h.
Referenced by process(), and reset().
entire_mission_blockwriter_stage DFMessageWriter_WriteEntireMission::stage = em_blockwriter_stage_init private
Definition at line 67 of file DFMessageWriter.h.
Referenced by process(), and reset().
The documentation for this class was generated from the following files:
libraries/DataFlash/DFMessageWriter.h
libraries/DataFlash/DFMessageWriter.cpp