APM:Libraries: AP_InertialSensor_MPU9150 Class Reference
AP_InertialSensor_MPU9150 Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_InertialSensor_MPU9150.h>
Public Member Functions
AP_InertialSensor_MPU9150 (AP_InertialSensor &imu)
Constructor.
bool update ()
bool gyro_sample_available (void)
bool accel_sample_available (void)
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void start ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t product_id (void) const
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Member Functions
bool _init_sensor ()
void _accumulate (void)
Accumulate values from accels and gyros.
int16_t mpu_set_gyro_fsr (uint16_t fsr)
Set the gyro full-scale range.
int16_t mpu_set_accel_fsr (uint8_t fsr)
Set the accel full-scale range.
int16_t mpu_set_lpf (uint16_t lpf)
Set digital low pass filter. The following LPF settings are supported: 188, 98, 42, 20, 10, 5.
int16_t mpu_set_sample_rate (uint16_t rate)
Set sampling rate. Sampling rate must be between 4Hz and 1kHz.
int16_t mpu_set_compass_sample_rate (uint16_t rate, uint16_t chip_sample_rate)
Set compass sampling rate. The compass on the auxiliary I2C bus is read by the MPU hardware at a maximum of 100Hz. The actual rate can be set to a fraction of the gyro sampling rate.
int16_t mpu_configure_fifo (uint8_t sensors)
Select which sensors are pushed to FIFO. sensors can contain a combination of the following flags:
INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL.
int16_t set_int_enable (uint8_t enable)
Enable/disable data ready interrupt. If the DMP is on, the DMP interrupt is enabled. Otherwise, the data ready interrupt is used.
int16_t mpu_reset_fifo (uint8_t sensors)
Reset FIFO read/write pointers.
int16_t mpu_set_sensors (uint8_t sensors)
Turn specific sensors on/off. sensors can contain a combination of the following flags:
INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL
INV_XYZ_COMPASS.
int16_t mpu_set_int_latched (uint8_t enable)
int16_t mpu_read_fifo (int16_t *gyro, int16_t *accel, uint32_t *timestamp, uint8_t *sensors, uint8_t *more)
Get one packet from the FIFO. If sensors does not contain a particular sensor, disregard the data returned to that pointer.
sensors can contain a combination of the following flags:
INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL
If the FIFO has no new data, sensors will be zero.
If the FIFO is disabled, sensors will be zero and this function will return a non-zero error code.
void _set_accel_filter_frequency (uint8_t filter_hz)
void _set_gyro_filter_frequency (uint8_t filter_hz)
Private Attributes
Vector3f _accel_filtered
Vector3f _gyro_filtered
bool _have_sample_available
uint8_t _last_accel_filter_hz
uint8_t _last_gyro_filter_hz
LowPassFilter2pVector3f _accel_filter
LowPassFilter2pVector3f _gyro_filter
uint8_t _gyro_instance
uint8_t _accel_instance
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
void _set_accel_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
int16_t _product_id
int16_t _id = -1
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 14 of file AP_InertialSensor_MPU9150.h.
Constructor & Destructor Documentation
AP_InertialSensor_MPU9150::AP_InertialSensor_MPU9150 (AP_InertialSensor & imu)
Constructor.
Definition at line 327 of file AP_InertialSensor_MPU9150.cpp.
Referenced by detect().
Member Function Documentation
void AP_InertialSensor_MPU9150::_accumulate (void) private
Accumulate values from accels and gyros.
This method is called periodically by the scheduler.
Definition at line 1023 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
bool AP_InertialSensor_MPU9150::_init_sensor (void) private
Init method
Definition at line 371 of file AP_InertialSensor_MPU9150.cpp.
Referenced by detect().
void AP_InertialSensor_MPU9150::_set_accel_filter_frequency (uint8_t filter_hz) private
Definition at line 355 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor(), and update().
void AP_InertialSensor_MPU9150::_set_gyro_filter_frequency (uint8_t filter_hz) private
Definition at line 363 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor(), and update().
bool AP_InertialSensor_MPU9150::accel_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 23 of file AP_InertialSensor_MPU9150.h.
AP_InertialSensor_Backend * AP_InertialSensor_MPU9150::detect (AP_InertialSensor & imu) static
Definition at line 339 of file AP_InertialSensor_MPU9150.cpp.
bool AP_InertialSensor_MPU9150::gyro_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 22 of file AP_InertialSensor_MPU9150.h.
int16_t AP_InertialSensor_MPU9150::mpu_configure_fifo (uint8_t sensors) private
Select which sensors are pushed to FIFO. sensors can contain a combination of the following flags:
INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL.
Parameters
[in] sensors Mask of sensors to push to FIFO.
Returns
0 if successful.
Definition at line 648 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
int16_t AP_InertialSensor_MPU9150::mpu_read_fifo (int16_t * gyro, int16_t * accel, uint32_t * timestamp, uint8_t * sensors, uint8_t * more) private
Get one packet from the FIFO. If sensors does not contain a particular sensor, disregard the data returned to that pointer.
sensors can contain a combination of the following flags:
INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL
If the FIFO has no new data, sensors will be zero.
If the FIFO is disabled, sensors will be zero and this function will return a non-zero error code.
Parameters
[out] gyro Gyro data in hardware units.
[out] accel Accel data in hardware units.
[out] timestamp Timestamp in milliseconds.
[out] sensors Mask of sensors read from FIFO.
[out] more Number of remaining packets.
Returns
0 if successful.
Definition at line 957 of file AP_InertialSensor_MPU9150.cpp.
int16_t AP_InertialSensor_MPU9150::mpu_reset_fifo (uint8_t sensors) private
Reset FIFO read/write pointers.
Returns
0 if successful.
Definition at line 693 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _accumulate(), mpu_configure_fifo(), and mpu_read_fifo().
int16_t AP_InertialSensor_MPU9150::mpu_set_accel_fsr (uint8_t fsr) private
Set the accel full-scale range.
Parameters
[in] fsr Desired full-scale range.
Returns
0 if successful.
Definition at line 519 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
int16_t AP_InertialSensor_MPU9150::mpu_set_compass_sample_rate (uint16_t rate, uint16_t chip_sample_rate) private
Set compass sampling rate. The compass on the auxiliary I2C bus is read by the MPU hardware at a maximum of 100Hz. The actual rate can be set to a fraction of the gyro sampling rate.
WARNING: The new rate may be different than what was requested. Call mpu_get_compass_sample_rate to check the actual setting.
Parameters
[in] rate Desired compass sampling rate (Hz).
Returns
0 if successful.
Definition at line 625 of file AP_InertialSensor_MPU9150.cpp.
int16_t AP_InertialSensor_MPU9150::mpu_set_gyro_fsr (uint16_t fsr) private
Set the gyro full-scale range.
Parameters
[in] fsr Desired full-scale range.
Returns
0 if successful.
Definition at line 487 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
int16_t AP_InertialSensor_MPU9150::mpu_set_int_latched (uint8_t enable) private
Referenced by mpu_set_sensors().
int16_t AP_InertialSensor_MPU9150::mpu_set_lpf (uint16_t lpf) private
Set digital low pass filter. The following LPF settings are supported: 188, 98, 42, 20, 10, 5.
Parameters
[in] lpf Desired LPF setting.
Returns
0 if successful.
Definition at line 552 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
int16_t AP_InertialSensor_MPU9150::mpu_set_sample_rate (uint16_t rate) private
Set sampling rate. Sampling rate must be between 4Hz and 1kHz.
Parameters
[in] rate Desired sampling rate (Hz).
Returns
0 if successful.
Definition at line 591 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
int16_t AP_InertialSensor_MPU9150::mpu_set_sensors (uint8_t sensors) private
Turn specific sensors on/off. sensors can contain a combination of the following flags:
INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL
INV_XYZ_COMPASS.
Parameters
[in] sensors Mask of sensors to wake.
Returns
0 if successful.
Definition at line 833 of file AP_InertialSensor_MPU9150.cpp.
Referenced by _init_sensor().
int16_t AP_InertialSensor_MPU9150::set_int_enable (uint8_t enable) private
Enable/disable data ready interrupt. If the DMP is on, the DMP interrupt is enabled. Otherwise, the data ready interrupt is used.
Parameters
[in] enable 1 to enable interrupt.
Returns
0 if successful.
Definition at line 673 of file AP_InertialSensor_MPU9150.cpp.
Referenced by mpu_configure_fifo().
bool AP_InertialSensor_MPU9150::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 1111 of file AP_InertialSensor_MPU9150.cpp.
Member Data Documentation
LowPassFilter2pVector3f AP_InertialSensor_MPU9150::_accel_filter private
Definition at line 55 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), and _set_accel_filter_frequency().
Vector3f AP_InertialSensor_MPU9150::_accel_filtered private
Definition at line 31 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), and update().
uint8_t AP_InertialSensor_MPU9150::_accel_instance private
Definition at line 59 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), _init_sensor(), and update().
LowPassFilter2pVector3f AP_InertialSensor_MPU9150::_gyro_filter private
Definition at line 56 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), and _set_gyro_filter_frequency().
Vector3f AP_InertialSensor_MPU9150::_gyro_filtered private
Definition at line 32 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), and update().
uint8_t AP_InertialSensor_MPU9150::_gyro_instance private
Definition at line 58 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), _init_sensor(), and update().
bool AP_InertialSensor_MPU9150::_have_sample_available private
Definition at line 33 of file AP_InertialSensor_MPU9150.h.
Referenced by _accumulate(), accel_sample_available(), gyro_sample_available(), and update().
uint8_t AP_InertialSensor_MPU9150::_last_accel_filter_hz private
Definition at line 36 of file AP_InertialSensor_MPU9150.h.
Referenced by update().
uint8_t AP_InertialSensor_MPU9150::_last_gyro_filter_hz private
Definition at line 37 of file AP_InertialSensor_MPU9150.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_MPU9150.h
libraries/AP_InertialSensor/AP_InertialSensor_MPU9150.cpp