APM:Libraries: AP_ADC_ADS7844 Class Reference
AP_ADC_ADS7844 Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_ADC_ADS7844.h>
Public Member Functions
AP_ADC_ADS7844 ()
void Init ()
float Ch (unsigned char ch_num)
uint32_t Ch6 (const uint8_t *channel_numbers, float *result)
bool new_data_available (const uint8_t *channel_numbers)
uint16_t num_samples_available (const uint8_t *channel_numbers)
Get minimum number of samples read from the sensors.
Public Member Functions inherited from AP_ADC
AP_ADC ()
virtual float Ch (uint8_t ch_num)=0
Private Member Functions
void read (void)
Private Attributes
AP_HAL::SPIDeviceDriver * _spi
AP_HAL::Semaphore * _spi_sem
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 10 of file AP_ADC_ADS7844.h.
Constructor & Destructor Documentation
AP_ADC_ADS7844::AP_ADC_ADS7844 ()
Definition at line 132 of file AP_ADC_ADS7844.cpp.
Member Function Documentation
float AP_ADC_ADS7844::Ch (unsigned char ch_num)
Definition at line 179 of file AP_ADC_ADS7844.cpp.
Referenced by show_data().
uint32_t AP_ADC_ADS7844::Ch6 (const uint8_t * channel_numbers, float * result) virtual
Implements AP_ADC.
Definition at line 217 of file AP_ADC_ADS7844.cpp.
Referenced by show_data(), and show_timing().
void AP_ADC_ADS7844::Init () virtual
Implements AP_ADC.
Definition at line 135 of file AP_ADC_ADS7844.cpp.
Referenced by setup().
bool AP_ADC_ADS7844::new_data_available (const uint8_t * channel_numbers) virtual
Implements AP_ADC.
Definition at line 199 of file AP_ADC_ADS7844.cpp.
uint16_t AP_ADC_ADS7844::num_samples_available (const uint8_t * channel_numbers) virtual
Get minimum number of samples read from the sensors.
Implements AP_ADC.
Definition at line 257 of file AP_ADC_ADS7844.cpp.
void AP_ADC_ADS7844::read (void) private
Take nonblocking: ::read happens from the TimerProcess context!
Definition at line 83 of file AP_ADC_ADS7844.cpp.
Referenced by Init().
Member Data Documentation
AP_HAL::SPIDeviceDriver* AP_ADC_ADS7844::_spi private
Definition at line 30 of file AP_ADC_ADS7844.h.
Referenced by Init(), and read().
AP_HAL::Semaphore* AP_ADC_ADS7844::_spi_sem private
Definition at line 31 of file AP_ADC_ADS7844.h.
Referenced by Init(), and read().
The documentation for this class was generated from the following files:
libraries/AP_ADC/AP_ADC_ADS7844.h
libraries/AP_ADC/AP_ADC_ADS7844.cpp