APM:Libraries: Linux::Semaphore Class Reference
Linux::Semaphore Class Reference
#include <Semaphores.h>
Public Member Functions
Semaphore ()
bool give ()
bool take (uint32_t timeout_ms)
bool take_nonblocking ()
Private Attributes
pthread_mutex_t _lock
Detailed Description
Definition at line 11 of file Semaphores.h.
Constructor & Destructor Documentation
Linux::Semaphore::Semaphore () inline
Definition at line 13 of file Semaphores.h.
Member Function Documentation
bool Semaphore::give () virtual
Implements AP_HAL::Semaphore.
Definition at line 11 of file Semaphores.cpp.
Referenced by Linux::Scheduler::_run_io(), Linux::Scheduler::_run_timers(), and Linux::Scheduler::resume_timer_procs().
bool Semaphore::take (uint32_t timeout_ms) virtual
Implements AP_HAL::Semaphore.
Definition at line 16 of file Semaphores.cpp.
Referenced by Linux::Scheduler::_run_io(), Linux::Scheduler::_run_timers(), and Linux::Scheduler::suspend_timer_procs().
bool Semaphore::take_nonblocking () virtual
Implements AP_HAL::Semaphore.
Definition at line 34 of file Semaphores.cpp.
Referenced by take().
Member Data Documentation
pthread_mutex_t Linux::Semaphore::_lock private
Definition at line 20 of file Semaphores.h.
Referenced by give(), Semaphore(), take(), and take_nonblocking().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Semaphores.h
libraries/AP_HAL_Linux/Semaphores.cpp