APM:Libraries: SerialDevice Class Reference
SerialDevice Class Reference abstract
#include <SerialDevice.h>
Public Member Functions
virtual ~SerialDevice ()
virtual bool open ()=0
virtual bool close ()=0
virtual ssize_t write (const uint8_t *buf, uint16_t n)=0
virtual ssize_t read (uint8_t *buf, uint16_t n)=0
virtual void set_blocking (bool blocking)=0
virtual void set_speed (uint32_t speed)=0
Detailed Description
Definition at line 7 of file SerialDevice.h.
Constructor & Destructor Documentation
virtual SerialDevice::~SerialDevice () inline virtual
Definition at line 9 of file SerialDevice.h.
Member Function Documentation
virtual bool SerialDevice::close () pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::end().
virtual bool SerialDevice::open () pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_serial_start_connection(), Linux::UARTDriver::_tcp_start_connection(), Linux::UARTDriver::_udp_start_connection(), Linux::UARTDriver::_write_fd(), Linux::UARTDriver::begin(), and Linux::UARTDriver::UARTDriver().
virtual ssize_t SerialDevice::read (uint8_t * buf, uint16_t n) pure virtual
Implemented in TCPServerDevice, UDPDevice, ConsoleDevice, and UARTDevice.
Referenced by Linux::UARTDriver::_read_fd().
virtual void SerialDevice::set_blocking (bool blocking) pure virtual
Implemented in ConsoleDevice, UARTDevice, TCPServerDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_serial_start_connection(), Linux::UARTDriver::_udp_start_connection(), and Linux::UARTDriver::begin().
virtual void SerialDevice::set_speed (uint32_t speed) pure virtual
Implemented in ConsoleDevice, UARTDevice, TCPServerDevice, and UDPDevice.
Referenced by Linux::UARTDriver::begin().
virtual ssize_t SerialDevice::write (const uint8_t * buf, uint16_t n) pure virtual
Implemented in TCPServerDevice, UDPDevice, ConsoleDevice, and UARTDevice.
Referenced by Linux::UARTDriver::_write_fd().
The documentation for this class was generated from the following file:
libraries/AP_HAL_Linux/SerialDevice.h