APM:Libraries: AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver Class Reference
AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver Class Reference
#include <SPIDriver.h>
Public Member Functions
FLYMAPLESPIDeviceDriver ()
void init ()
AP_HAL::Semaphore * get_semaphore ()
bool transaction (const uint8_t *tx, uint8_t *rx, uint16_t len)
void cs_assert ()
void cs_release ()
uint8_t transfer (uint8_t data)
void transfer (const uint8_t *data, uint16_t len)
Public Member Functions inherited from AP_HAL::SPIDeviceDriver
virtual void set_bus_speed (enum bus_speed speed)
virtual void set_state (State state)
virtual State get_state ()
Private Attributes
FLYMAPLESemaphore _semaphore
Additional Inherited Members
Public Types inherited from AP_HAL::SPIDeviceDriver
enum bus_speed { SPI_SPEED_LOW, SPI_SPEED_HIGH }
enum State : uint8_t { State::UNKNOWN, State::RUNNING, State::FAILED }
Detailed Description
Definition at line 27 of file SPIDriver.h.
Constructor & Destructor Documentation
FLYMAPLESPIDeviceDriver::FLYMAPLESPIDeviceDriver ()
Definition at line 36 of file SPIDriver.cpp.
Member Function Documentation
void FLYMAPLESPIDeviceDriver::cs_assert () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 68 of file SPIDriver.cpp.
Referenced by transaction().
void FLYMAPLESPIDeviceDriver::cs_release () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 73 of file SPIDriver.cpp.
Referenced by transaction().
AP_HAL::Semaphore * FLYMAPLESPIDeviceDriver::get_semaphore () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 46 of file SPIDriver.cpp.
void FLYMAPLESPIDeviceDriver::init (void) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 39 of file SPIDriver.cpp.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceManager::device().
bool FLYMAPLESPIDeviceDriver::transaction (const uint8_t * tx, uint8_t * rx, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 51 of file SPIDriver.cpp.
uint8_t FLYMAPLESPIDeviceDriver::transfer (uint8_t data) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 78 of file SPIDriver.cpp.
Referenced by transaction().
void FLYMAPLESPIDeviceDriver::transfer (const uint8_t * data, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 83 of file SPIDriver.cpp.
Member Data Documentation
FLYMAPLESemaphore AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver::_semaphore private
Definition at line 39 of file SPIDriver.h.
Referenced by get_semaphore().
The documentation for this class was generated from the following files:
libraries/AP_HAL_FLYMAPLE/SPIDriver.h
libraries/AP_HAL_FLYMAPLE/SPIDriver.cpp