APM:Libraries: DataFlash_Class Class Reference
DataFlash_Class Class Reference
#include <DataFlash.h>
Classes
struct PID_Info
Public Member Functions
FUNCTOR_TYPEDEF (print_mode_fn, void, AP_HAL::BetterStream *, uint8_t)
FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer, void)
DataFlash_Class (const char *firmware_string)
void set_mission (const AP_Mission *mission)
void Init (const struct LogStructure *structure, uint8_t num_types)
bool CardInserted (void)
bool NeedErase (void)
void EraseAll ()
bool NeedPrep ()
void Prep ()
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
uint16_t find_last_log () const
void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
uint16_t get_num_logs (void)
void LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, print_mode_fn printMode, AP_HAL::BetterStream *port)
void DumpPageInfo (AP_HAL::BetterStream *port)
void ShowDeviceInfo (AP_HAL::BetterStream *port)
void ListAvailableLogs (AP_HAL::BetterStream *port)
uint16_t bufferspace_available ()
void setVehicle_Startup_Log_Writer (vehicle_startup_message_Log_Writer writer)
uint16_t StartNewLog (void)
void AddLogFormats (const struct LogStructure *structures, uint8_t num_types)
void EnableWrites (bool enable)
void Log_Write_SysInfo (const char *firmware_string)
bool Log_Write_Format (const struct LogStructure *structure)
bool Log_Write_Parameter (const char *name, float value)
void Log_Write_GPS (const AP_GPS &gps, uint8_t instance, int32_t relative_alt)
void Log_Write_RFND (const RangeFinder &rangefinder)
void Log_Write_IMU (const AP_InertialSensor &ins)
void Log_Write_IMUDT (const AP_InertialSensor &ins)
void Log_Write_Vibration (const AP_InertialSensor &ins)
void Log_Write_RCIN (void)
void Log_Write_RCOUT (void)
void Log_Write_RSSI (AP_RSSI &rssi)
void Log_Write_Baro (AP_Baro &baro)
void Log_Write_Power (void)
void Log_Write_AHRS2 (AP_AHRS &ahrs)
void Log_Write_POS (AP_AHRS &ahrs)
bool Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
void Log_Write_Radio (const mavlink_radio_t &packet)
bool Log_Write_Message (const char *message)
void Log_Write_Camera (const AP_AHRS &ahrs, const AP_GPS &gps, const Location &current_loc)
void Log_Write_ESC (void)
void Log_Write_Airspeed (AP_Airspeed &airspeed)
void Log_Write_Attitude (AP_AHRS &ahrs, const Vector3f &targets)
void Log_Write_Current (const AP_BattMonitor &battery, int16_t throttle)
void Log_Write_Compass (const Compass &compass)
bool Log_Write_Mode (uint8_t mode)
void Log_Write_Parameters (void)
void Log_Write_EntireMission (const AP_Mission &mission)
bool Log_Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
void Log_Write_Origin (uint8_t origin_type, const Location &loc)
void Log_Write_RPM (const AP_RPM &rpm_sensor)
void Log_Write_PID (uint8_t msg_type, const PID_Info &info)
bool logging_started (void)
void flush (void)
void periodic_tasks ()
bool Log_Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type)
Public Attributes
DFMessageWriter_DFLogStart _startup_messagewriter
vehicle_startup_message_Log_Writer _vehicle_messages
Protected Member Functions
void Log_Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
uint16_t start_new_log (void)
void WroteStartupFormat ()
void WroteStartupParam ()
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
Protected Attributes
const struct LogStructure * _structures
uint8_t _num_types
Private Attributes
DataFlash_Backend * backend
Friends
class DFMessageWriter_DFLogStart
Detailed Description
Definition at line 34 of file DataFlash.h.
Constructor & Destructor Documentation
DataFlash_Class::DataFlash_Class (const char * firmware_string) inline
Definition at line 41 of file DataFlash.h.
Member Function Documentation
void DataFlash_Class::AddLogFormats (const struct LogStructure * structures, uint8_t num_types)
Definition at line 623 of file LogFile.cpp.
Referenced by AP_GPS_SBP::logging_write_headers().
uint16_t DataFlash_Class::bufferspace_available (void)
Definition at line 48 of file DataFlash.cpp.
Referenced by DFMessageWriter_DFLogStart::process().
bool DataFlash_Class::CardInserted (void)
Definition at line 36 of file DataFlash.cpp.
void DataFlash_Class::DumpPageInfo (AP_HAL::BetterStream * port)
Definition at line 77 of file DataFlash.cpp.
void DataFlash_Class::EnableWrites (bool enable)
Definition at line 91 of file DataFlash.cpp.
void DataFlash_Class::EraseAll ()
Definition at line 32 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_log_request_erase().
uint16_t DataFlash_Class::find_last_log () const
Definition at line 52 of file DataFlash.cpp.
void DataFlash_Class::flush (void)
Definition at line 109 of file DataFlash.cpp.
Referenced by DataFlashTest::setup().
DataFlash_Class::FUNCTOR_TYPEDEF (print_mode_fn , void , AP_HAL::BetterStream * , uint8_t)
DataFlash_Class::FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer , void)
void DataFlash_Class::get_log_boundaries (uint16_t log_num, uint16_t & start_page, uint16_t & end_page)
Definition at line 55 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_log_request_data(), and DataFlashTest::loop().
int16_t DataFlash_Class::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data)
Definition at line 61 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_log_send_data().
void DataFlash_Class::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc)
Definition at line 58 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_log_request_data(), and GCS_MAVLINK::handle_log_send_listing().
uint16_t DataFlash_Class::get_num_logs (void)
Definition at line 64 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_log_request_data(), and GCS_MAVLINK::handle_log_request_list().
void DataFlash_Class::Init (const struct LogStructure * structure, uint8_t num_types)
Definition at line 22 of file LogFile.cpp.
Referenced by DataFlashTest::setup().
void DataFlash_Class::ListAvailableLogs (AP_HAL::BetterStream * port)
Definition at line 83 of file DataFlash.cpp.
void DataFlash_Class::Log_Fill_Format (const struct LogStructure * structure, struct log_Format & pkt) protected
Definition at line 67 of file DataFlash.cpp.
Referenced by Log_Write_Format().
void DataFlash_Class::Log_Write_AHRS2 (AP_AHRS & ahrs)
Definition at line 1071 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Airspeed (AP_Airspeed & airspeed)
Definition at line 1741 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Attitude (AP_AHRS & ahrs, const Vector3f & targets)
Definition at line 1588 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Baro (AP_Baro & baro)
Definition at line 815 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Camera (const AP_AHRS & ahrs, const AP_GPS & gps, const Location & current_loc)
Definition at line 1560 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Compass (const Compass & compass)
Definition at line 1623 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Current (const AP_BattMonitor & battery, int16_t throttle)
Definition at line 1606 of file LogFile.cpp.
void DataFlash_Class::Log_Write_EntireMission (const AP_Mission & mission)
Definition at line 1037 of file LogFile.cpp.
void DataFlash_Class::Log_Write_ESC (void)
Definition at line 1700 of file LogFile.cpp.
Referenced by Log_Write_RCOUT().
bool DataFlash_Class::Log_Write_Format (const struct LogStructure * structure)
Definition at line 650 of file LogFile.cpp.
Referenced by AddLogFormats(), and DFMessageWriter_DFLogStart::process().
void DataFlash_Class::Log_Write_GPS (const AP_GPS & gps, uint8_t instance, int32_t relative_alt)
Definition at line 705 of file LogFile.cpp.
void DataFlash_Class::Log_Write_IMU (const AP_InertialSensor & ins)
Definition at line 854 of file LogFile.cpp.
void DataFlash_Class::Log_Write_IMUDT (const AP_InertialSensor & ins)
Definition at line 921 of file LogFile.cpp.
bool DataFlash_Class::Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t & mav_cmd)
Definition at line 1524 of file LogFile.cpp.
Referenced by Log_Write_Mission_Cmd().
bool DataFlash_Class::Log_Write_Message (const char * message)
Definition at line 1045 of file LogFile.cpp.
Referenced by Log_Write_SysInfo(), DFMessageWriter_WriteSysInfo::process(), and DFMessageWriter_WriteEntireMission::process().
bool DataFlash_Class::Log_Write_Mission_Cmd (const AP_Mission & mission, const AP_Mission::Mission_Command & cmd)
Definition at line 1029 of file LogFile.cpp.
Referenced by DFMessageWriter_WriteEntireMission::process().
bool DataFlash_Class::Log_Write_Mode (uint8_t mode)
Definition at line 1688 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Origin (uint8_t origin_type, const Location & loc)
Definition at line 1775 of file LogFile.cpp.
bool DataFlash_Class::Log_Write_Parameter (const char * name, float value)
Definition at line 660 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), AP_AutoTune::log_param_change(), Log_Write_Parameter(), Log_Write_Parameters(), and DFMessageWriter_DFLogStart::process().
bool DataFlash_Class::Log_Write_Parameter (const AP_Param * ap, const AP_Param::ParamToken & token, enum ap_var_type type)
Definition at line 675 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Parameters (void)
Definition at line 688 of file LogFile.cpp.
Referenced by Log_Write_SysInfo().
void DataFlash_Class::Log_Write_PID (uint8_t msg_type, const PID_Info & info)
Definition at line 1760 of file LogFile.cpp.
void DataFlash_Class::Log_Write_POS (AP_AHRS & ahrs)
Definition at line 1092 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Power (void)
Definition at line 1056 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Radio (const mavlink_radio_t & packet)
Definition at line 1543 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_radio_status().
void DataFlash_Class::Log_Write_RCIN (void)
Definition at line 757 of file LogFile.cpp.
void DataFlash_Class::Log_Write_RCOUT (void)
Definition at line 781 of file LogFile.cpp.
void DataFlash_Class::Log_Write_RFND (const RangeFinder & rangefinder)
Definition at line 745 of file LogFile.cpp.
void DataFlash_Class::Log_Write_RPM (const AP_RPM & rpm_sensor)
Definition at line 1789 of file LogFile.cpp.
void DataFlash_Class::Log_Write_RSSI (AP_RSSI & rssi)
Definition at line 804 of file LogFile.cpp.
void DataFlash_Class::Log_Write_SysInfo (const char * firmware_string)
Definition at line 1010 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Vibration (const AP_InertialSensor & ins)
Definition at line 993 of file LogFile.cpp.
bool DataFlash_Class::logging_started (void)
Definition at line 87 of file DataFlash.cpp.
Referenced by AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_AutoTune::log_param_change(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), and AP_AutoTune::write_log().
void DataFlash_Class::LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, print_mode_fn printMode, AP_HAL::BetterStream * port)
Definition at line 71 of file DataFlash.cpp.
Referenced by DataFlashTest::loop().
bool DataFlash_Class::NeedErase (void)
bool DataFlash_Class::NeedPrep ()
Definition at line 40 of file DataFlash.cpp.
Referenced by DataFlashTest::setup().
void DataFlash_Class::periodic_tasks ()
Definition at line 95 of file DataFlash.cpp.
void DataFlash_Class::Prep ()
Definition at line 44 of file DataFlash.cpp.
Referenced by DataFlashTest::setup().
void DataFlash_Class::set_mission (const AP_Mission * mission)
Definition at line 10 of file DataFlash.cpp.
void DataFlash_Class::setVehicle_Startup_Log_Writer (vehicle_startup_message_Log_Writer writer)
Definition at line 5 of file DataFlash.cpp.
void DataFlash_Class::ShowDeviceInfo (AP_HAL::BetterStream * port)
Definition at line 80 of file DataFlash.cpp.
Referenced by DataFlashTest::setup().
uint16_t DataFlash_Class::start_new_log (void) protected
Definition at line 27 of file DataFlash.cpp.
Referenced by StartNewLog().
uint16_t DataFlash_Class::StartNewLog (void)
Definition at line 606 of file LogFile.cpp.
Referenced by DataFlashTest::setup().
bool DataFlash_Class::WriteBlock (const void * pBuffer, uint16_t size)
Definition at line 15 of file DataFlash.cpp.
Referenced by AP_InertialSensor_PX4::_get_accel_sample(), AP_InertialSensor_PX4::_get_gyro_sample(), AP_TECS::log_data(), AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), Log_Write_AHRS2(), Log_Write_Airspeed(), Log_Write_Attitude(), Log_Write_Baro(), Log_Write_Compass(), Log_Write_Current(), Log_Write_ESC(), Log_Write_GPS(), Log_Write_IMU(), Log_Write_IMUDT(), Log_Write_MavCmd(), Log_Write_Origin(), Log_Write_PID(), Log_Write_POS(), Log_Write_Power(), Log_Write_Radio(), Log_Write_RCIN(), Log_Write_RCOUT(), Log_Write_RFND(), Log_Write_RPM(), Log_Write_RSSI(), SITL::SITL::Log_Write_SIMSTATE(), Log_Write_Vibration(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), DataFlashTest::setup(), and AP_AutoTune::write_log().
bool DataFlash_Class::WriteCriticalBlock (const void * pBuffer, uint16_t size)
Definition at line 19 of file DataFlash.cpp.
Referenced by Log_Write_Camera(), Log_Write_Format(), Log_Write_Message(), Log_Write_Mode(), and Log_Write_Parameter().
bool DataFlash_Class::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) protected
Definition at line 23 of file DataFlash.cpp.
void DataFlash_Class::WroteStartupFormat () protected
Definition at line 99 of file DataFlash.cpp.
Referenced by DFMessageWriter_DFLogStart::process().
void DataFlash_Class::WroteStartupParam () protected
Definition at line 103 of file DataFlash.cpp.
Referenced by DFMessageWriter_DFLogStart::process().
Friends And Related Function Documentation
friend class DFMessageWriter_DFLogStart friend
Definition at line 36 of file DataFlash.h.
Member Data Documentation
uint8_t DataFlash_Class::_num_types protected
Definition at line 160 of file DataFlash.h.
Referenced by Init(), and DFMessageWriter_DFLogStart::process().
DFMessageWriter_DFLogStart DataFlash_Class::_startup_messagewriter
Definition at line 149 of file DataFlash.h.
Referenced by set_mission(), StartNewLog(), DataFlash_Backend::WriteBlockCheckStartupMessages(), and DataFlash_Backend::WriteMoreStartupMessages().
const struct LogStructure* DataFlash_Class::_structures protected
Definition at line 159 of file DataFlash.h.
Referenced by Init(), and DFMessageWriter_DFLogStart::process().
vehicle_startup_message_Log_Writer DataFlash_Class::_vehicle_messages
Definition at line 150 of file DataFlash.h.
Referenced by DFMessageWriter_DFLogStart::process(), and setVehicle_Startup_Log_Writer().
DataFlash_Backend* DataFlash_Class::backend private
Definition at line 169 of file DataFlash.h.
Referenced by bufferspace_available(), CardInserted(), DumpPageInfo(), EnableWrites(), EraseAll(), find_last_log(), flush(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), Init(), ListAvailableLogs(), Log_Fill_Format(), logging_started(), LogReadProcess(), NeedPrep(), periodic_tasks(), Prep(), ShowDeviceInfo(), start_new_log(), WriteBlock(), WriteCriticalBlock(), WritePrioritisedBlock(), WroteStartupFormat(), and WroteStartupParam().
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash.h
libraries/DataFlash/DataFlash.cpp
libraries/DataFlash/LogFile.cpp