APM:Libraries: AP_HMC5843_SerialBus Class Reference
AP_HMC5843_SerialBus Class Reference abstract
#include <AP_Compass_HMC5843.h>
Classes
struct raw_value
Public Member Functions
virtual ~AP_HMC5843_SerialBus ()
virtual void set_high_speed (bool val)=0
virtual uint8_t register_read (uint8_t reg, uint8_t *buf, uint8_t size)=0
uint8_t register_read (uint8_t reg, uint8_t *val)
virtual uint8_t register_write (uint8_t reg, uint8_t val)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual uint8_t read_raw (struct raw_value *rv)=0
virtual bool configure ()
virtual bool start_measurements ()
Detailed Description
Definition at line 68 of file AP_Compass_HMC5843.h.
Constructor & Destructor Documentation
virtual AP_HMC5843_SerialBus::~AP_HMC5843_SerialBus () inline virtual
Definition at line 75 of file AP_Compass_HMC5843.h.
Member Function Documentation
virtual bool AP_HMC5843_SerialBus::configure () inline virtual
Reimplemented in AP_HMC5843_SerialBus_MPU6000.
Definition at line 86 of file AP_Compass_HMC5843.h.
Referenced by AP_Compass_HMC5843::init().
virtual AP_HAL::Semaphore* AP_HMC5843_SerialBus::get_semaphore () pure virtual
Implemented in AP_HMC5843_SerialBus_MPU6000, and AP_HMC5843_SerialBus_I2C.
Referenced by AP_Compass_HMC5843::init().
virtual uint8_t AP_HMC5843_SerialBus::read_raw (struct raw_value * rv) pure virtual
Implemented in AP_HMC5843_SerialBus_MPU6000, and AP_HMC5843_SerialBus_I2C.
Referenced by AP_Compass_HMC5843::read_raw().
virtual uint8_t AP_HMC5843_SerialBus::register_read (uint8_t reg, uint8_t * buf, uint8_t size) pure virtual
Implemented in AP_HMC5843_SerialBus_MPU6000, and AP_HMC5843_SerialBus_I2C.
Referenced by AP_Compass_HMC5843::read_register(), and register_read().
uint8_t AP_HMC5843_SerialBus::register_read (uint8_t reg, uint8_t * val) inline
Definition at line 78 of file AP_Compass_HMC5843.h.
virtual uint8_t AP_HMC5843_SerialBus::register_write (uint8_t reg, uint8_t val) pure virtual
Implemented in AP_HMC5843_SerialBus_MPU6000, and AP_HMC5843_SerialBus_I2C.
Referenced by AP_Compass_HMC5843::write_register().
virtual void AP_HMC5843_SerialBus::set_high_speed (bool val) pure virtual
Implemented in AP_HMC5843_SerialBus_MPU6000, and AP_HMC5843_SerialBus_I2C.
Referenced by AP_Compass_HMC5843::read(), and AP_Compass_HMC5843::read_raw().
virtual bool AP_HMC5843_SerialBus::start_measurements () inline virtual
Reimplemented in AP_HMC5843_SerialBus_MPU6000.
Definition at line 87 of file AP_Compass_HMC5843.h.
Referenced by AP_Compass_HMC5843::init().
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_HMC5843.h