APM:Libraries: AP_HAL::AnalogSource Class Reference
AP_HAL::AnalogSource Class Reference abstract
#include <AnalogIn.h>
Public Member Functions
virtual float read_average ()=0
virtual float read_latest ()=0
virtual void set_pin (uint8_t p)=0
virtual void set_stop_pin (uint8_t p)=0
virtual void set_settle_time (uint16_t settle_time_ms)=0
virtual float voltage_average ()=0
virtual float voltage_latest ()=0
virtual float voltage_average_ratiometric ()=0
Detailed Description
Definition at line 9 of file AnalogIn.h.
Member Function Documentation
virtual float AP_HAL::AnalogSource::read_average () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, AP_ADC_AnalogSource, ADS1115AnalogSource, RaspilotAnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
virtual float AP_HAL::AnalogSource::read_latest () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, AP_ADC_AnalogSource, ADS1115AnalogSource, RaspilotAnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
virtual void AP_HAL::AnalogSource::set_pin (uint8_t p) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, AP_ADC_AnalogSource, ADS1115AnalogSource, RaspilotAnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
Referenced by RaspilotAnalogIn::board_voltage(), AP_Airspeed_Analog::get_differential_pressure(), loop(), AP_BattMonitor_Analog::read(), AP_RSSI::read_pin_rssi(), and AP_RangeFinder_analog::update_voltage().
virtual void AP_HAL::AnalogSource::set_settle_time (uint16_t settle_time_ms) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, AP_ADC_AnalogSource, ADS1115AnalogSource, RaspilotAnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), and AP_RangeFinder_analog::update_voltage().
virtual void AP_HAL::AnalogSource::set_stop_pin (uint8_t p) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, AP_ADC_AnalogSource, ADS1115AnalogSource, RaspilotAnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), and AP_RangeFinder_analog::update_voltage().
virtual float AP_HAL::AnalogSource::voltage_average () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, ADS1115AnalogSource, RaspilotAnalogSource, AP_ADC_AnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
Referenced by loop(), AP_BattMonitor_Analog::read(), AP_RSSI::read_pin_rssi(), and AP_RangeFinder_analog::update_voltage().
virtual float AP_HAL::AnalogSource::voltage_average_ratiometric () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, ADS1115AnalogSource, RaspilotAnalogSource, AP_ADC_AnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
Referenced by AP_Airspeed_Analog::get_differential_pressure(), and AP_RangeFinder_analog::update_voltage().
virtual float AP_HAL::AnalogSource::voltage_latest () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource, VRBRAIN::VRBRAINAnalogSource, PX4::PX4AnalogSource, HALSITL::ADCSource, ADS1115AnalogSource, RaspilotAnalogSource, AP_ADC_AnalogSource, Empty::EmptyAnalogSource, and Linux::AnalogSource.
The documentation for this class was generated from the following file:
libraries/AP_HAL/AnalogIn.h