APM:Libraries: AP_Mount_Backend Class Reference
AP_Mount_Backend Class Reference abstract
#include <AP_Mount_Backend.h>
Public Member Functions
AP_Mount_Backend (AP_Mount &frontend, AP_Mount::mount_state &state, uint8_t instance)
virtual ~AP_Mount_Backend (void)
virtual void init (const AP_SerialManager &serial_manager)=0
virtual void update ()=0
virtual bool has_pan_control () const =0
virtual void set_mode (enum MAV_MOUNT_MODE mode)=0
virtual void set_angle_targets (float roll, float tilt, float pan)
virtual void set_roi_target (const struct Location &target_loc)
virtual void control (int32_t pitch_or_lat, int32_t roll_or_lon, int32_t yaw_or_alt, MAV_MOUNT_MODE mount_mode)
virtual void configure_msg (mavlink_message_t *msg)
virtual void control_msg (mavlink_message_t *msg)
virtual void status_msg (mavlink_channel_t chan)
virtual void handle_gimbal_report (mavlink_channel_t chan, mavlink_message_t *msg)
virtual void send_gimbal_report (mavlink_channel_t chan)
Protected Member Functions
void update_targets_from_rc ()
int32_t angle_input (RC_Channel *rc, int16_t angle_min, int16_t angle_max)
float angle_input_rad (RC_Channel *rc, int16_t angle_min, int16_t angle_max)
void calc_angle_to_location (const struct Location &target, Vector3f &angles_to_target_rad, bool calc_tilt, bool calc_pan)
MAV_MOUNT_MODE get_mode (void) const
Protected Attributes
AP_Mount & _frontend
AP_Mount::mount_state & _state
uint8_t _instance
Vector3f _angle_ef_target_rad
Detailed Description
Definition at line 28 of file AP_Mount_Backend.h.
Constructor & Destructor Documentation
AP_Mount_Backend::AP_Mount_Backend (AP_Mount & frontend, AP_Mount::mount_state & state, uint8_t instance) inline
Definition at line 32 of file AP_Mount_Backend.h.
virtual AP_Mount_Backend::~AP_Mount_Backend (void) inline virtual
Definition at line 39 of file AP_Mount_Backend.h.
Member Function Documentation
int32_t AP_Mount_Backend::angle_input (RC_Channel * rc, int16_t angle_min, int16_t angle_max) protected
Definition at line 124 of file AP_Mount_Backend.cpp.
Referenced by angle_input_rad().
float AP_Mount_Backend::angle_input_rad (RC_Channel * rc, int16_t angle_min, int16_t angle_max) protected
Definition at line 130 of file AP_Mount_Backend.cpp.
Referenced by update_targets_from_rc().
void AP_Mount_Backend::calc_angle_to_location (const struct Location & target, Vector3f & angles_to_target_rad, bool calc_tilt, bool calc_pan) protected
Definition at line 136 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), and AP_Mount_Alexmos::update().
void AP_Mount_Backend::configure_msg (mavlink_message_t * msg) virtual
Definition at line 30 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::configure_msg().
void AP_Mount_Backend::control (int32_t pitch_or_lat, int32_t roll_or_lon, int32_t yaw_or_alt, MAV_MOUNT_MODE mount_mode) virtual
Definition at line 47 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::control(), and control_msg().
void AP_Mount_Backend::control_msg (mavlink_message_t * msg) virtual
Definition at line 39 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::control_msg().
MAV_MOUNT_MODE AP_Mount_Backend::get_mode (void) const inline protected
Definition at line 90 of file AP_Mount_Backend.h.
Referenced by AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), and AP_Mount_Alexmos::update().
virtual void AP_Mount_Backend::handle_gimbal_report (mavlink_channel_t chan, mavlink_message_t * msg) inline virtual
Definition at line 72 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_gimbal_report().
virtual bool AP_Mount_Backend::has_pan_control () const pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::has_pan_control().
virtual void AP_Mount_Backend::init (const AP_SerialManager & serial_manager) pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::init().
virtual void AP_Mount_Backend::send_gimbal_report (mavlink_channel_t chan) inline virtual
Definition at line 75 of file AP_Mount_Backend.h.
Referenced by AP_Mount::send_gimbal_report().
void AP_Mount_Backend::set_angle_targets (float roll, float tilt, float pan) virtual
Definition at line 8 of file AP_Mount_Backend.cpp.
Referenced by control(), and AP_Mount::set_angle_targets().
virtual void AP_Mount_Backend::set_mode (enum MAV_MOUNT_MODE mode) pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by configure_msg(), and AP_Mount::set_mode().
void AP_Mount_Backend::set_roi_target (const struct Location & target_loc) virtual
Definition at line 20 of file AP_Mount_Backend.cpp.
Referenced by control(), and AP_Mount::set_roi_target().
virtual void AP_Mount_Backend::status_msg (mavlink_channel_t chan) inline virtual
Reimplemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Definition at line 69 of file AP_Mount_Backend.h.
Referenced by AP_Mount::status_msg().
virtual void AP_Mount_Backend::update () pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::update().
void AP_Mount_Backend::update_targets_from_rc () protected
Definition at line 86 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), and AP_Mount_Alexmos::update().
Member Data Documentation
Vector3f AP_Mount_Backend::_angle_ef_target_rad protected
Definition at line 95 of file AP_Mount_Backend.h.
Referenced by set_angle_targets(), AP_Mount_Servo::stabilize(), AP_Mount_SToRM32::status_msg(), AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), AP_Mount_Alexmos::update(), and update_targets_from_rc().
AP_Mount& AP_Mount_Backend::_frontend protected
Definition at line 92 of file AP_Mount_Backend.h.
Referenced by calc_angle_to_location(), control(), get_mode(), set_angle_targets(), set_roi_target(), AP_Mount_Servo::stabilize(), AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), AP_Mount_Alexmos::update(), and update_targets_from_rc().
uint8_t AP_Mount_Backend::_instance protected
Definition at line 94 of file AP_Mount_Backend.h.
Referenced by control(), get_mode(), AP_Mount_Servo::init(), set_angle_targets(), and set_roi_target().
AP_Mount::mount_state& AP_Mount_Backend::_state protected
Definition at line 93 of file AP_Mount_Backend.h.
Referenced by control_msg(), AP_Mount_SToRM32_serial::init(), AP_Mount_SToRM32_serial::set_mode(), AP_Mount_SToRM32::set_mode(), AP_Mount_Servo::set_mode(), AP_Mount_Alexmos::set_mode(), set_roi_target(), AP_Mount_Servo::stabilize(), AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), AP_Mount_Alexmos::update(), and update_targets_from_rc().
The documentation for this class was generated from the following files:
libraries/AP_Mount/AP_Mount_Backend.h
libraries/AP_Mount/AP_Mount_Backend.cpp