APM:Libraries: AP_MPU6000_BusDriver Class Reference
AP_MPU6000_BusDriver Class Reference abstract
#include <AP_InertialSensor_MPU6000.h>
Public Member Functions
virtual ~AP_MPU6000_BusDriver ()
virtual void init ()=0
virtual void start (bool &fifo_mode, uint8_t &max_samples)=0
virtual void read8 (uint8_t reg, uint8_t *val)=0
virtual void read_block (uint8_t reg, uint8_t *buf, uint32_t size)=0
virtual void write8 (uint8_t reg, uint8_t val)=0
virtual void set_bus_speed (AP_HAL::SPIDeviceDriver::bus_speed speed)=0
virtual void read_data_transaction (uint8_t *samples, AP_HAL::DigitalSource *_drdy_pin, uint8_t &n_samples)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual bool has_auxiliary_bus ()=0
Detailed Description
Definition at line 27 of file AP_InertialSensor_MPU6000.h.
Constructor & Destructor Documentation
virtual AP_MPU6000_BusDriver::~AP_MPU6000_BusDriver () inline virtual
Definition at line 30 of file AP_InertialSensor_MPU6000.h.
Member Function Documentation
virtual AP_HAL::Semaphore* AP_MPU6000_BusDriver::get_semaphore () pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_init_sensor().
virtual bool AP_MPU6000_BusDriver::has_auxiliary_bus () pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::get_auxiliary_bus().
virtual void AP_MPU6000_BusDriver::init () pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_hardware_init().
virtual void AP_MPU6000_BusDriver::read8 (uint8_t reg, uint8_t * val) pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_register_read().
virtual void AP_MPU6000_BusDriver::read_block (uint8_t reg, uint8_t * buf, uint32_t size) pure virtual
Copy data from the device to buf starting at reg with length.
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_read_block().
virtual void AP_MPU6000_BusDriver::read_data_transaction (uint8_t * samples, AP_HAL::DigitalSource * _drdy_pin, uint8_t & n_samples) pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_read_data_transaction().
virtual void AP_MPU6000_BusDriver::set_bus_speed (AP_HAL::SPIDeviceDriver::bus_speed speed) pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_hardware_init(), and AP_InertialSensor_MPU6000::start().
virtual void AP_MPU6000_BusDriver::start (bool & fifo_mode, uint8_t & max_samples) pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::start().
virtual void AP_MPU6000_BusDriver::write8 (uint8_t reg, uint8_t val) pure virtual
Implemented in AP_MPU6000_BusDriver_I2C, and AP_MPU6000_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU6000::_register_write().
The documentation for this class was generated from the following file:
libraries/AP_InertialSensor/AP_InertialSensor_MPU6000.h