APM:Libraries: AP_AK8963_SerialBus Class Reference
AP_AK8963_SerialBus Class Reference abstract
#include <AP_Compass_AK8963.h>
Classes
struct raw_value
Public Member Functions
virtual ~AP_AK8963_SerialBus ()
virtual void register_read (uint8_t reg, uint8_t *value, uint8_t count)=0
uint8_t register_read (uint8_t reg)
virtual void register_write (uint8_t reg, uint8_t value)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual bool start_measurements ()=0
virtual void read_raw (struct raw_value *rv)=0
virtual uint32_t get_dev_id ()=0
Detailed Description
Definition at line 16 of file AP_Compass_AK8963.h.
Constructor & Destructor Documentation
virtual AP_AK8963_SerialBus::~AP_AK8963_SerialBus () inline virtual
Definition at line 24 of file AP_Compass_AK8963.h.
Member Function Documentation
virtual uint32_t AP_AK8963_SerialBus::get_dev_id () pure virtual
Implemented in AP_AK8963_SerialBus_I2C, and AP_AK8963_SerialBus_MPU9250.
Referenced by AP_Compass_AK8963::init().
virtual AP_HAL::Semaphore* AP_AK8963_SerialBus::get_semaphore () pure virtual
Implemented in AP_AK8963_SerialBus_I2C, and AP_AK8963_SerialBus_MPU9250.
Referenced by AP_Compass_AK8963::init().
virtual void AP_AK8963_SerialBus::read_raw (struct raw_value * rv) pure virtual
Implemented in AP_AK8963_SerialBus_I2C, and AP_AK8963_SerialBus_MPU9250.
Referenced by AP_Compass_AK8963::_update().
virtual void AP_AK8963_SerialBus::register_read (uint8_t reg, uint8_t * value, uint8_t count) pure virtual
Implemented in AP_AK8963_SerialBus_I2C, and AP_AK8963_SerialBus_MPU9250.
Referenced by AP_Compass_AK8963::_calibrate(), AP_Compass_AK8963::_check_id(), and register_read().
uint8_t AP_AK8963_SerialBus::register_read (uint8_t reg) inline
Definition at line 26 of file AP_Compass_AK8963.h.
virtual void AP_AK8963_SerialBus::register_write (uint8_t reg, uint8_t value) pure virtual
Implemented in AP_AK8963_SerialBus_I2C, and AP_AK8963_SerialBus_MPU9250.
Referenced by AP_Compass_AK8963::_calibrate(), AP_Compass_AK8963::_reset(), and AP_Compass_AK8963::_setup_mode().
virtual bool AP_AK8963_SerialBus::start_measurements () pure virtual
Implemented in AP_AK8963_SerialBus_I2C, and AP_AK8963_SerialBus_MPU9250.
Referenced by AP_Compass_AK8963::init().
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_AK8963.h