APM:Libraries: DataFlashTest Class Reference
DataFlashTest Class Reference
Public Member Functions
void setup ()
void loop ()
Private Member Functions
void print_mode (AP_HAL::BetterStream *port, uint8_t mode)
Private Attributes
DataFlash_Class dataflash {"DF Test 0.1"}
Detailed Description
Definition at line 30 of file DataFlash_test.cpp.
Member Function Documentation
void DataFlashTest::loop (void)
Definition at line 97 of file DataFlash_test.cpp.
Referenced by loop().
void DataFlashTest::print_mode (AP_HAL::BetterStream * port, uint8_t mode) private
Definition at line 111 of file DataFlash_test.cpp.
Referenced by loop().
void DataFlashTest::setup (void)
Definition at line 43 of file DataFlash_test.cpp.
Referenced by setup().
Member Data Documentation
DataFlash_Class DataFlashTest::dataflash {"DF Test 0.1"} private
Definition at line 37 of file DataFlash_test.cpp.
Referenced by loop(), and setup().
The documentation for this class was generated from the following file:
libraries/DataFlash/examples/DataFlash_test/DataFlash_test.cpp