APM:Libraries: VRBRAIN::VRBRAINStorage Class Reference
VRBRAIN::VRBRAINStorage Class Reference
#include <Storage.h>
Public Member Functions
VRBRAINStorage ()
void init (void *machtnichts)
void read_block (void *dst, uint16_t src, size_t n)
void write_block (uint16_t dst, const void *src, size_t n)
void _timer_tick (void)
Private Member Functions
void _storage_create (void)
void _storage_open (void)
void _mark_dirty (uint16_t loc, uint16_t length)
uint8_t _buffer[VRBRAIN_STORAGE_SIZE] __attribute__ ((aligned(4)))
void _upgrade_to_mtd (void)
uint32_t _mtd_signature (void)
void _mtd_write_signature (void)
Private Attributes
int _fd
volatile bool _initialised
volatile uint32_t _dirty_mask
perf_counter_t _perf_storage
perf_counter_t _perf_errors
bool _have_mtd
Detailed Description
Definition at line 16 of file Storage.h.
Constructor & Destructor Documentation
VRBRAINStorage::VRBRAINStorage (void)
Definition at line 33 of file Storage.cpp.
Member Function Documentation
uint8_t _buffer [VRBRAIN_STORAGE_SIZE] VRBRAIN::VRBRAINStorage::__attribute__ ((aligned(4))) private
void VRBRAINStorage::_mark_dirty (uint16_t loc, uint16_t length) private
Definition at line 177 of file Storage.cpp.
Referenced by write_block().
uint32_t VRBRAINStorage::_mtd_signature (void) private
Definition at line 44 of file Storage.cpp.
Referenced by _storage_open().
void VRBRAINStorage::_mtd_write_signature (void) private
Definition at line 64 of file Storage.cpp.
Referenced by _storage_open().
void VRBRAIN::VRBRAINStorage::_storage_create (void) private
void VRBRAINStorage::_storage_open (void) private
Definition at line 118 of file Storage.cpp.
Referenced by read_block(), and write_block().
void VRBRAINStorage::_timer_tick (void)
Definition at line 208 of file Storage.cpp.
void VRBRAINStorage::_upgrade_to_mtd (void) private
Definition at line 83 of file Storage.cpp.
Referenced by _storage_open().
void VRBRAIN::VRBRAINStorage::init (void * machtnichts) inline virtual
Implements AP_HAL::Storage.
Definition at line 20 of file Storage.h.
void VRBRAINStorage::read_block (void * dst, uint16_t src, size_t n) virtual
Implements AP_HAL::Storage.
Definition at line 187 of file Storage.cpp.
void VRBRAINStorage::write_block (uint16_t dst, const void * src, size_t n) virtual
Implements AP_HAL::Storage.
Definition at line 196 of file Storage.cpp.
Member Data Documentation
volatile uint32_t VRBRAIN::VRBRAINStorage::_dirty_mask private
Definition at line 33 of file Storage.h.
Referenced by _mark_dirty(), _storage_open(), and _timer_tick().
int VRBRAIN::VRBRAINStorage::_fd private
Definition at line 27 of file Storage.h.
Referenced by _timer_tick().
bool VRBRAIN::VRBRAINStorage::_have_mtd private
Definition at line 36 of file Storage.h.
Referenced by _storage_open().
volatile bool VRBRAIN::VRBRAINStorage::_initialised private
Definition at line 28 of file Storage.h.
Referenced by _storage_open(), and _timer_tick().
perf_counter_t VRBRAIN::VRBRAINStorage::_perf_errors private
Definition at line 35 of file Storage.h.
Referenced by _timer_tick().
perf_counter_t VRBRAIN::VRBRAINStorage::_perf_storage private
Definition at line 34 of file Storage.h.
Referenced by _timer_tick().
The documentation for this class was generated from the following files:
libraries/AP_HAL_VRBRAIN/Storage.h
libraries/AP_HAL_VRBRAIN/Storage.cpp