APM:Libraries: AP_Airspeed Class Reference
AP_Airspeed Class Reference
#include <AP_Airspeed.h>
Public Types
enum pitot_tube_order { PITOT_TUBE_ORDER_POSITIVE =0, PITOT_TUBE_ORDER_NEGATIVE =1, PITOT_TUBE_ORDER_AUTO =2 }
Public Member Functions
AP_Airspeed (const AP_Vehicle::FixedWing &parms)
void init (void)
void read (void)
void calibrate (bool in_startup)
float get_airspeed (void) const
float get_raw_airspeed (void) const
float get_airspeed_cm (void) const
float get_airspeed_ratio (void) const
bool get_temperature (float &temperature)
void set_airspeed_ratio (float ratio)
bool use (void) const
bool enabled (void) const
void disable (void)
void set_HIL (float airspeed)
float get_differential_pressure (void) const
float get_offset (void) const
float get_raw_pressure (void) const
void set_EAS2TAS (float v)
float get_EAS2TAS (void) const
void update_calibration (const Vector3f &vground)
void log_mavlink_send (mavlink_channel_t chan, const Vector3f &vground)
bool healthy (void) const
void setHIL (float pressure)
uint32_t last_update_ms (void) const
void setHIL (float airspeed, float diff_pressure, float temperature)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
float get_pressure (void)
Private Attributes
AP_Float _offset
AP_Float _ratio
AP_Int8 _use
AP_Int8 _enable
AP_Int8 _pin
AP_Int8 _autocal
AP_Int8 _tube_order
AP_Int8 _skip_cal
float _raw_airspeed
float _airspeed
float _last_pressure
float _raw_pressure
float _EAS2TAS
bool _healthy:1
bool _hil_set:1
float _hil_pressure
uint32_t _last_update_ms
Airspeed_Calibration _calibration
float _last_saved_ratio
uint8_t _counter
AP_Airspeed_Analog analog
AP_Airspeed_PX4 digital
Detailed Description
Definition at line 39 of file AP_Airspeed.h.
Member Enumeration Documentation
enum AP_Airspeed::pitot_tube_order
Enumerator
PITOT_TUBE_ORDER_POSITIVE
PITOT_TUBE_ORDER_NEGATIVE
PITOT_TUBE_ORDER_AUTO
Definition at line 161 of file AP_Airspeed.h.
Constructor & Destructor Documentation
AP_Airspeed::AP_Airspeed (const AP_Vehicle::FixedWing & parms) inline
Definition at line 43 of file AP_Airspeed.h.
Member Function Documentation
void AP_Airspeed::calibrate (bool in_startup)
Definition at line 171 of file AP_Airspeed.cpp.
Referenced by setup().
void AP_Airspeed::disable (void) inline
Definition at line 108 of file AP_Airspeed.h.
bool AP_Airspeed::enabled (void) const inline
Definition at line 103 of file AP_Airspeed.h.
Referenced by AP_Arming::airspeed_checks().
float AP_Airspeed::get_airspeed (void) const inline
Definition at line 70 of file AP_Airspeed.h.
Referenced by AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), NavEKF2_core::detectFlight(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), loop(), NavEKF_core::readAirSpdData(), NavEKF2_core::readAirSpdData(), and NavEKF_core::SetFlightAndFusionModes().
float AP_Airspeed::get_airspeed_cm (void) const inline
Definition at line 80 of file AP_Airspeed.h.
float AP_Airspeed::get_airspeed_ratio (void) const inline
Definition at line 85 of file AP_Airspeed.h.
float AP_Airspeed::get_differential_pressure (void) const inline
Definition at line 119 of file AP_Airspeed.h.
Referenced by log_mavlink_send(), DataFlash_Class::Log_Write_Airspeed(), and update_calibration().
float AP_Airspeed::get_EAS2TAS (void) const inline
Definition at line 139 of file AP_Airspeed.h.
Referenced by NavEKF2_core::detectFlight(), AP_AHRS::get_EAS2TAS(), NavEKF_core::readAirSpdData(), NavEKF2_core::readAirSpdData(), and NavEKF_core::SetFlightAndFusionModes().
float AP_Airspeed::get_offset (void) const inline
Definition at line 124 of file AP_Airspeed.h.
Referenced by DataFlash_Class::Log_Write_Airspeed().
float AP_Airspeed::get_pressure (void) private
Definition at line 139 of file AP_Airspeed.cpp.
Referenced by calibrate(), and read().
float AP_Airspeed::get_raw_airspeed (void) const inline
Definition at line 75 of file AP_Airspeed.h.
Referenced by DataFlash_Class::Log_Write_Airspeed().
float AP_Airspeed::get_raw_pressure (void) const inline
Definition at line 129 of file AP_Airspeed.h.
Referenced by DataFlash_Class::Log_Write_Airspeed().
bool AP_Airspeed::get_temperature (float & temperature)
Definition at line 158 of file AP_Airspeed.cpp.
Referenced by DataFlash_Class::Log_Write_Airspeed().
bool AP_Airspeed::healthy (void) const inline
Definition at line 150 of file AP_Airspeed.h.
Referenced by AP_Arming::airspeed_checks(), AP_AHRS::airspeed_sensor_enabled(), and loop().
void AP_Airspeed::init (void)
Definition at line 127 of file AP_Airspeed.cpp.
Referenced by setup().
uint32_t AP_Airspeed::last_update_ms (void) const inline
Definition at line 155 of file AP_Airspeed.h.
Referenced by NavEKF_core::readAirSpdData(), and NavEKF2_core::readAirSpdData().
void AP_Airspeed::log_mavlink_send (mavlink_channel_t chan, const Vector3f & vground)
Definition at line 154 of file Airspeed_Calibration.cpp.
void AP_Airspeed::read (void)
Definition at line 204 of file AP_Airspeed.cpp.
Referenced by loop().
void AP_Airspeed::set_airspeed_ratio (float ratio) inline
Definition at line 93 of file AP_Airspeed.h.
void AP_Airspeed::set_EAS2TAS (float v) inline
Definition at line 134 of file AP_Airspeed.h.
void AP_Airspeed::set_HIL (float airspeed) inline
Definition at line 113 of file AP_Airspeed.h.
void AP_Airspeed::setHIL (float pressure) inline
Definition at line 152 of file AP_Airspeed.h.
void AP_Airspeed::setHIL (float airspeed, float diff_pressure, float temperature)
Definition at line 242 of file AP_Airspeed.cpp.
void AP_Airspeed::update_calibration (const Vector3f & vground)
Definition at line 114 of file Airspeed_Calibration.cpp.
bool AP_Airspeed::use (void) const inline
Definition at line 98 of file AP_Airspeed.h.
Referenced by AP_Arming::airspeed_checks(), AP_AHRS::airspeed_sensor_enabled(), NavEKF_core::readAirSpdData(), and NavEKF2_core::readAirSpdData().
Member Data Documentation
float AP_Airspeed::_airspeed private
Definition at line 175 of file AP_Airspeed.h.
Referenced by calibrate(), get_airspeed(), get_airspeed_cm(), read(), set_HIL(), and setHIL().
AP_Int8 AP_Airspeed::_autocal private
Definition at line 171 of file AP_Airspeed.h.
Referenced by update_calibration().
Airspeed_Calibration AP_Airspeed::_calibration private
Definition at line 184 of file AP_Airspeed.h.
Referenced by init(), log_mavlink_send(), and update_calibration().
uint8_t AP_Airspeed::_counter private
Definition at line 186 of file AP_Airspeed.h.
Referenced by init(), and update_calibration().
float AP_Airspeed::_EAS2TAS private
Definition at line 178 of file AP_Airspeed.h.
Referenced by get_EAS2TAS(), log_mavlink_send(), set_EAS2TAS(), and update_calibration().
AP_Int8 AP_Airspeed::_enable private
Definition at line 169 of file AP_Airspeed.h.
Referenced by calibrate(), disable(), enabled(), get_pressure(), get_temperature(), read(), and use().
bool AP_Airspeed::_healthy private
Definition at line 179 of file AP_Airspeed.h.
Referenced by calibrate(), get_pressure(), healthy(), read(), and setHIL().
float AP_Airspeed::_hil_pressure private
Definition at line 181 of file AP_Airspeed.h.
Referenced by get_pressure(), and setHIL().
bool AP_Airspeed::_hil_set private
Definition at line 180 of file AP_Airspeed.h.
Referenced by get_pressure(), and setHIL().
float AP_Airspeed::_last_pressure private
Definition at line 176 of file AP_Airspeed.h.
Referenced by get_differential_pressure(), init(), read(), and setHIL().
float AP_Airspeed::_last_saved_ratio private
Definition at line 185 of file AP_Airspeed.h.
Referenced by init(), and update_calibration().
uint32_t AP_Airspeed::_last_update_ms private
Definition at line 182 of file AP_Airspeed.h.
Referenced by last_update_ms(), read(), and setHIL().
AP_Float AP_Airspeed::_offset private
Definition at line 166 of file AP_Airspeed.h.
Referenced by calibrate(), get_offset(), healthy(), and read().
AP_Int8 AP_Airspeed::_pin private
Definition at line 170 of file AP_Airspeed.h.
Referenced by get_pressure(), and get_temperature().
AP_Float AP_Airspeed::_ratio private
Definition at line 167 of file AP_Airspeed.h.
Referenced by get_airspeed_ratio(), init(), log_mavlink_send(), read(), set_airspeed_ratio(), and update_calibration().
float AP_Airspeed::_raw_airspeed private
Definition at line 174 of file AP_Airspeed.h.
Referenced by calibrate(), get_raw_airspeed(), read(), and setHIL().
float AP_Airspeed::_raw_pressure private
Definition at line 177 of file AP_Airspeed.h.
Referenced by get_raw_pressure(), and read().
AP_Int8 AP_Airspeed::_skip_cal private
Definition at line 173 of file AP_Airspeed.h.
Referenced by calibrate().
AP_Int8 AP_Airspeed::_tube_order private
Definition at line 172 of file AP_Airspeed.h.
Referenced by read().
AP_Int8 AP_Airspeed::_use private
Definition at line 168 of file AP_Airspeed.h.
Referenced by use().
AP_Airspeed_Analog AP_Airspeed::analog private
Definition at line 190 of file AP_Airspeed.h.
Referenced by get_pressure(), and init().
AP_Airspeed_PX4 AP_Airspeed::digital private
Definition at line 192 of file AP_Airspeed.h.
Referenced by get_pressure(), get_temperature(), and init().
const AP_Param::GroupInfo AP_Airspeed::var_info static
Definition at line 159 of file AP_Airspeed.h.
Referenced by AP_Airspeed(), and setup().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed.h
libraries/AP_Airspeed/Airspeed_Calibration.cpp
libraries/AP_Airspeed/AP_Airspeed.cpp