APM:Libraries: AP_HAL::Print Class Reference
AP_HAL::Print Class Reference abstract
#include <Print.h>
Public Member Functions
Print ()
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Private Member Functions
size_t printNumber (unsigned long, uint8_t)
size_t printFloat (float, uint8_t)
Detailed Description
Definition at line 44 of file Print.h.
Constructor & Destructor Documentation
AP_HAL::Print::Print () inline
Definition at line 49 of file Print.h.
Member Function Documentation
size_t Print::print (const char str[])
Definition at line 32 of file Print.cpp.
Referenced by AP_InertialSensor::_init_gyro(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogIn::_register_channel(), console_loopback(), AP_GPS::detect_instance(), AP_Curve< T, SIZE >::dump_curve(), MissionTest::init_mission(), MissionTest::init_mission_endless_loop(), MissionTest::init_mission_ends_with_do_commands(), MissionTest::init_mission_ends_with_jump_command(), MissionTest::init_mission_jump_to_nonnav(), MissionTest::init_mission_no_nav_commands(), MissionTest::init_mission_starts_with_do_commands(), loop(), MissionTest::mission_complete(), print(), printFloat(), println(), MissionTest::run_mission_test(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), MissionTest::run_set_current_cmd_while_stopped_test(), and setup().
size_t Print::print (char c)
Definition at line 37 of file Print.cpp.
size_t Print::print (unsigned char b, int base = BASE_DEC)
Definition at line 42 of file Print.cpp.
size_t Print::print (int n, int base = BASE_DEC)
Definition at line 47 of file Print.cpp.
size_t Print::print (unsigned int n, int base = BASE_DEC)
Definition at line 52 of file Print.cpp.
size_t Print::print (long n, int base = BASE_DEC)
Definition at line 57 of file Print.cpp.
size_t Print::print (unsigned long n, int base = BASE_DEC)
Definition at line 73 of file Print.cpp.
size_t Print::print (float n, int digits = 2)
Definition at line 79 of file Print.cpp.
size_t Print::print (double n, int digits = 2)
Definition at line 87 of file Print.cpp.
size_t Print::printFloat (float number, uint8_t digits) private
Definition at line 184 of file Print.cpp.
Referenced by print().
size_t Print::println (const char c[])
Definition at line 99 of file Print.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), Compass::_detect_backends(), AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_MPU6000::_hardware_init(), Menu::_help(), AP_InertialSensor::_init_gyro(), DataFlash_Backend::_print_log_entry(), AP_Compass_LSM303D::_read_raw(), Menu::_run_command(), Linux::RCOutput_Bebop::_run_rcout(), Linux::Storage_FRAM::_storage_create(), AP_InertialSensor_UserInteract_MAVLink::blocking_read(), AP_Airspeed::calibrate(), ADS1115AnalogIn::channel(), RaspilotAnalogIn::channel(), PX4::PX4AnalogIn::channel(), VRBRAIN::VRBRAINAnalogIn::channel(), console_loopback(), AP_Curve< T, SIZE >::dump_curve(), Compass::handle_mag_cal_command(), AP_Airspeed_PX4::init(), AP_Compass_LSM303D::init(), DataFlash_Block::ListAvailableLogs(), loop(), missing_rotations(), motor_order_test(), Linux::Storage_FRAM::open(), AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), AP_MPU6000_AuxiliaryBusSlave::passthrough_read(), AP_MPU9250_AuxiliaryBusSlave::passthrough_write(), AP_MPU6000_AuxiliaryBusSlave::passthrough_write(), AP_MPU9250_AuxiliaryBusSlave::read(), AP_MPU6000_AuxiliaryBusSlave::read(), HALSITL::SITLScheduler::reboot(), AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler::reboot(), AP_Param::save(), MissionTest::setup(), setup(), DataFlashTest::setup(), show_timing(), DataFlash_Block::ShowDeviceInfo(), HALSITL::SITLScheduler::sitl_end_atomic(), stability_test(), test_conversions(), test_eulers(), test_frame_transforms(), test_matrix_eulers(), test_passed_waypoint(), test_quaternion_eulers(), and test_rotation_accuracy().
size_t Print::println (char c)
Definition at line 106 of file Print.cpp.
size_t Print::println (unsigned char b, int base = BASE_DEC)
Definition at line 113 of file Print.cpp.
size_t Print::println (int num, int base = BASE_DEC)
Definition at line 120 of file Print.cpp.
size_t Print::println (unsigned int num, int base = BASE_DEC)
Definition at line 127 of file Print.cpp.
size_t Print::println (long num, int base = BASE_DEC)
Definition at line 134 of file Print.cpp.
size_t Print::println (unsigned long num, int base = BASE_DEC)
Definition at line 141 of file Print.cpp.
size_t Print::println (float num, int digits = 2)
Definition at line 148 of file Print.cpp.
size_t Print::println (double num, int digits = 2)
Definition at line 158 of file Print.cpp.
size_t Print::println (void)
Definition at line 92 of file Print.cpp.
Referenced by println().
size_t Print::printNumber (unsigned long n, uint8_t base) private
Definition at line 165 of file Print.cpp.
Referenced by print().
virtual size_t AP_HAL::Print::write (uint8_t) pure virtual
Implemented in HALSITL::SITLUARTDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLEUARTDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, Empty::EmptyUARTDriver, PX4::NSHShellStream, and BufferPrinter.
Referenced by Menu::_check_for_input(), AP_GPS_UBLOX::_send_message(), AP_GPS_SBF::AP_GPS_SBF(), comm_send_buffer(), comm_send_ch(), console_loopback(), AP_Frsky_Telem::frsky_send_byte(), AP_Frsky_Telem::frsky_send_hub_startstop(), AP_Mount_SToRM32_serial::get_angles(), AP_RangeFinder_LightWareSerial::get_reading(), GCS_MAVLINK::handle_serial_control(), AP_GPS_SBF::inject_data(), AP_GPS_SBP::inject_data(), AP_GPS_GSOF::inject_data(), loop(), print(), print_vprintf(), printNumber(), AP_GPS_SBF::read(), AP_GPS_GSOF::requestBaud(), AP_GPS_GSOF::requestGSOF(), AP_GPS::send_blob_update(), AP_Mount_Alexmos::send_command(), AP_Mount_SToRM32_serial::send_target_angles(), GCS_MAVLINK::setup_uart(), and test_snprintf().
virtual size_t AP_HAL::Print::write (const uint8_t * buffer, size_t size) pure virtual
Implemented in HALSITL::SITLUARTDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLEUARTDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, Empty::EmptyUARTDriver, BufferPrinter, and PX4::NSHShellStream.
size_t AP_HAL::Print::write (const char * str) inline
Definition at line 54 of file Print.h.
Referenced by write().
The documentation for this class was generated from the following files:
libraries/AP_HAL/utility/Print.h
libraries/AP_HAL/utility/Print.cpp