APM:Libraries: AP_MPU9250_BusDriver Class Reference
AP_MPU9250_BusDriver Class Reference abstract
#include <AP_InertialSensor_MPU9250.h>
Public Member Functions
virtual ~AP_MPU9250_BusDriver ()
virtual void init ()=0
virtual void read8 (uint8_t reg, uint8_t *val)=0
virtual void write8 (uint8_t reg, uint8_t val)=0
virtual void read_block (uint8_t reg, uint8_t *val, uint8_t count)=0
virtual void set_bus_speed (AP_HAL::SPIDeviceDriver::bus_speed speed)=0
virtual bool read_data_transaction (uint8_t *samples, uint8_t &n_samples)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual bool has_auxiliary_bus ()=0
Detailed Description
Definition at line 20 of file AP_InertialSensor_MPU9250.h.
Constructor & Destructor Documentation
virtual AP_MPU9250_BusDriver::~AP_MPU9250_BusDriver () inline virtual
Definition at line 23 of file AP_InertialSensor_MPU9250.h.
Member Function Documentation
virtual AP_HAL::Semaphore* AP_MPU9250_BusDriver::get_semaphore () pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::_init_sensor().
virtual bool AP_MPU9250_BusDriver::has_auxiliary_bus () pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::get_auxiliary_bus().
virtual void AP_MPU9250_BusDriver::init () pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::_hardware_init().
virtual void AP_MPU9250_BusDriver::read8 (uint8_t reg, uint8_t * val) pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::_register_read().
virtual void AP_MPU9250_BusDriver::read_block (uint8_t reg, uint8_t * val, uint8_t count) pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), and AP_MPU9250_AuxiliaryBusSlave::read().
virtual bool AP_MPU9250_BusDriver::read_data_transaction (uint8_t * samples, uint8_t & n_samples) pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::_read_data_transaction().
virtual void AP_MPU9250_BusDriver::set_bus_speed (AP_HAL::SPIDeviceDriver::bus_speed speed) pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::_hardware_init().
virtual void AP_MPU9250_BusDriver::write8 (uint8_t reg, uint8_t val) pure virtual
Implemented in AP_MPU9250_BusDriver_I2C, and AP_MPU9250_BusDriver_SPI.
Referenced by AP_InertialSensor_MPU9250::_register_write().
The documentation for this class was generated from the following file:
libraries/AP_InertialSensor/AP_InertialSensor_MPU9250.h