APM:Libraries: AP_HAL::BetterStream Class Reference
AP_HAL::BetterStream Class Reference abstract
#include <BetterStream.h>
Public Member Functions
BetterStream (void)
virtual void printf (const char *,...) FORMAT(2
virtual void virtual void vprintf (const char *, va_list)=0
Public Member Functions inherited from AP_HAL::Stream
virtual int16_t available ()=0
virtual int16_t txspace ()=0
virtual int16_t read ()=0
Public Member Functions inherited from AP_HAL::Print
Print ()
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Detailed Description
Definition at line 31 of file BetterStream.h.
Constructor & Destructor Documentation
AP_HAL::BetterStream::BetterStream (void) inline
Definition at line 33 of file BetterStream.h.
Member Function Documentation
virtual void AP_HAL::BetterStream::printf (const char * , ...) virtual
Reimplemented in AP_HAL::UARTDriver.
Referenced by Menu::_display_prompt(), Menu::_help(), DataFlash_Backend::_print_log_entry(), DataFlash_Block::_print_log_formats(), DataFlash_Block::DumpPageInfo(), DataFlash_Block::ListAvailableLogs(), print_latlon(), DataFlashTest::print_mode(), AP_Param::show(), AP_Param::show_all(), and DataFlash_Block::ShowDeviceInfo().
virtual void virtual void AP_HAL::BetterStream::vprintf (const char * , va_list) pure virtual
Implemented in AP_HAL::UARTDriver.
Referenced by AP_InertialSensor_UserInteractStream::printf().
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/BetterStream.h