APM:Libraries: LowPassFilter2p< T > Class Template Reference
LowPassFilter2p< T > Class Template Reference
#include <LowPassFilter2p.h>
Public Member Functions
LowPassFilter2p ()
LowPassFilter2p (float sample_freq, float cutoff_freq)
void set_cutoff_frequency (float sample_freq, float cutoff_freq)
float get_cutoff_freq (void) const
float get_sample_freq (void) const
T apply (const T &sample)
Protected Attributes
struct DigitalBiquadFilter< T >::biquad_params _params
Private Attributes
DigitalBiquadFilter< T > _filter
Detailed Description
template<class T>
class LowPassFilter2p< T >
Definition at line 54 of file LowPassFilter2p.h.
Constructor & Destructor Documentation
template<class T > LowPassFilter2p< T >::LowPassFilter2p ()
Definition at line 56 of file LowPassFilter2p.cpp.
template<class T > LowPassFilter2p< T >::LowPassFilter2p (float sample_freq, float cutoff_freq)
Definition at line 62 of file LowPassFilter2p.cpp.
Member Function Documentation
template<class T> T LowPassFilter2p< T >::apply (const T & sample)
Definition at line 85 of file LowPassFilter2p.cpp.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), AP_InertialSensor_MPU6000::_accumulate(), AP_InertialSensor_PX4::_new_accel_sample(), AP_InertialSensor_PX4::_new_gyro_sample(), AP_InertialSensor_MPU9250::_read_data_transaction(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), and loop().
template<class T > float LowPassFilter2p< T >::get_cutoff_freq (void) const
Definition at line 75 of file LowPassFilter2p.cpp.
template<class T > float LowPassFilter2p< T >::get_sample_freq (void) const
Definition at line 80 of file LowPassFilter2p.cpp.
template<class T > void LowPassFilter2p< T >::set_cutoff_frequency (float sample_freq, float cutoff_freq)
Definition at line 69 of file LowPassFilter2p.cpp.
Referenced by AP_InertialSensor_MPU9250::_set_accel_filter(), AP_InertialSensor_LSM9DS0::_set_accel_filter(), AP_InertialSensor_MPU9150::_set_accel_filter_frequency(), AP_InertialSensor_PX4::_set_accel_filter_frequency(), AP_InertialSensor_Flymaple::_set_filter_frequency(), AP_InertialSensor_L3G4200D::_set_filter_frequency(), AP_InertialSensor_MPU9250::_set_gyro_filter(), AP_InertialSensor_LSM9DS0::_set_gyro_filter(), AP_InertialSensor_MPU9150::_set_gyro_filter_frequency(), AP_InertialSensor_PX4::_set_gyro_filter_frequency(), and AP_InertialSensor_MPU6000::update().
Member Data Documentation
template<class T> DigitalBiquadFilter<T> LowPassFilter2p< T >::_filter private
Definition at line 70 of file LowPassFilter2p.h.
template<class T> struct DigitalBiquadFilter< T >::biquad_params LowPassFilter2p< T >::_params protected
Definition at line 67 of file LowPassFilter2p.h.
The documentation for this class was generated from the following files:
libraries/Filter/LowPassFilter2p.h
libraries/Filter/LowPassFilter2p.cpp