APM:Libraries: AP_HAL::SPIDeviceManager Class Reference
AP_HAL::SPIDeviceManager Class Reference abstract
#include <SPIDriver.h>
Public Member Functions
virtual void init (void *)=0
virtual AP_HAL::SPIDeviceDriver * device (enum AP_HAL::SPIDevice, uint8_t index=0)=0
Detailed Description
Definition at line 8 of file SPIDriver.h.
Member Function Documentation
virtual AP_HAL::SPIDeviceDriver* AP_HAL::SPIDeviceManager::device (enum AP_HAL::SPIDevice , uint8_t index = 0) pure virtual
Implemented in Linux::SPIDeviceManager, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceManager, and Empty::EmptySPIDeviceManager.
Referenced by AP_InertialSensor_LSM9DS0::_init_sensor(), AP_MPU6000_BusDriver_SPI::AP_MPU6000_BusDriver_SPI(), Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), AP_InertialSensor::detect_backends(), Linux::RCOutput_Raspilot::init(), Linux::RCInput_Raspilot::init(), AP_ADC_ADS7844::Init(), RaspilotAnalogIn::init(), AP_SerialBus_SPI::init(), AP_Compass_LSM303D::init(), loop(), Linux::Storage_FRAM::open(), and setup().
virtual void AP_HAL::SPIDeviceManager::init (void *) pure virtual
Implemented in Linux::SPIDeviceManager, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceManager, and Empty::EmptySPIDeviceManager.
Referenced by HAL_Linux::run(), and HAL_FLYMAPLE::run().
The documentation for this class was generated from the following file:
libraries/AP_HAL/SPIDriver.h