APM:Libraries: AP_HAL::Scheduler Class Reference
AP_HAL::Scheduler Class Reference abstract
#include <Scheduler.h>
Public Member Functions
Scheduler ()
virtual void init (void *implspecific)=0
virtual void delay (uint16_t ms)=0
virtual uint32_t millis ()=0
virtual uint32_t micros ()=0
virtual uint64_t millis64 ()=0
virtual uint64_t micros64 ()=0
virtual void delay_microseconds (uint16_t us)=0
virtual void delay_microseconds_boost (uint16_t us)
virtual void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)=0
virtual void register_timer_process (AP_HAL::MemberProc)=0
virtual void register_io_process (AP_HAL::MemberProc)=0
virtual void suspend_timer_procs ()=0
virtual void resume_timer_procs ()=0
virtual bool in_timerprocess ()=0
virtual void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us)=0
virtual bool system_initializing ()=0
virtual void system_initialized ()=0
virtual void panic (const char *errormsg,...) FORMAT(2
virtual void reboot (bool hold_in_bootloader)=0
virtual void set_timer_speed (uint16_t speed_hz)
virtual void stop_clock (uint64_t time_usec)
Public Attributes
virtual void NORETURN = 0
Detailed Description
Definition at line 13 of file Scheduler.h.
Constructor & Destructor Documentation
AP_HAL::Scheduler::Scheduler () inline
Definition at line 15 of file Scheduler.h.
Member Function Documentation
virtual void AP_HAL::Scheduler::delay (uint16_t ms) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor_LSM9DS0::_accel_init(), AP_Compass_HMC5843::_calibrate(), AP_InertialSensor_LSM9DS0::_gyro_init(), AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_MPU6000::_hardware_init(), Menu::_help(), AP_InertialSensor::_init_gyro(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogIn::_register_channel(), AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore::_take_from_mainloop(), Linux::RPIOUARTDriver::_timer_tick(), AP_Baro_MS56XX::AP_Baro_MS56XX(), PX4::PX4UARTDriver::begin(), VRBRAIN::VRBRAINUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), Linux::UARTDriver::begin(), AP_InertialSensor_UserInteractStream::blocking_read(), AP_InertialSensor_UserInteract_MAVLink::blocking_read(), AP_Baro::calibrate(), AP_Airspeed::calibrate(), AP_InertialSensor::calibrate_accel(), AP_InertialSensor::calibrate_trim(), DataFlash_SITL::ChipErase(), Compass::compass_cal_update(), AP_RangeFinder_MaxsonarI2CXL::detect(), AP_RangeFinder_BBB_PRU::detect(), AP_RangeFinder_PulsedLightLRF::detect(), PX4::PX4UARTDriver::end(), VRBRAIN::VRBRAINUARTDriver::end(), Linux::UARTDriver::end(), DataFlash_Block::EraseAll(), full_spectrum(), DataFlash_Block::get_log_boundaries(), GCS_MAVLINK::handle_serial_control(), AP_Compass_PX4::init(), AP_BoardConfig::init(), AP_Airspeed_I2C::init(), AP_Compass_LSM303D::init(), Compass::init(), Linux::RCInput_RPI::init(), DataFlash_Class::Log_Write_Parameters(), DataFlash_Block::LogReadProcess(), MissionTest::loop(), loop(), DataFlashTest::loop(), motor_order_test(), AP_InertialSensor_MPU9150::mpu_reset_fifo(), AP_InertialSensor_MPU9150::mpu_set_sensors(), Linux::Storage_FRAM::open(), AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), AP_MPU6000_AuxiliaryBusSlave::passthrough_read(), AP_MPU9250_AuxiliaryBusSlave::passthrough_write(), AP_MPU6000_AuxiliaryBusSlave::passthrough_write(), AP_InertialSensor_UserInteract_MAVLink::printf(), AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler::reboot(), Linux::RCOutput_PCA9685::reset_all_channels(), Menu::run(), setup(), DataFlashTest::setup(), GCS_MAVLINK::setup_uart(), AP_InertialSensor_MPU6000::start(), testFn(), testFn2(), PX4::PX4UARTDriver::write(), VRBRAIN::VRBRAINUARTDriver::write(), and Linux::UARTDriver::write().
virtual void AP_HAL::Scheduler::delay_microseconds (uint16_t us) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
Referenced by Linux::RPIOUARTDriver::_timer_tick(), RaspilotAnalogIn::_update(), delay_microseconds_boost(), AP_RangeFinder_PulsedLightLRF::get_reading(), Linux::RCInput_RPI::init_DMA(), Linux::RCInput_RPI::init_PCM(), loop(), main_loop(), VRBRAIN::VRBRAINScheduler::panic(), Linux::Scheduler::panic(), PX4::PX4Scheduler::panic(), Linux::Semaphore::take(), and AP_InertialSensor::wait_for_sample().
virtual void AP_HAL::Scheduler::delay_microseconds_boost (uint16_t us) inline virtual
Reimplemented in PX4::PX4Scheduler.
Definition at line 36 of file Scheduler.h.
Referenced by AP_InertialSensor::wait_for_sample().
virtual bool AP_HAL::Scheduler::in_timerprocess () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore::take(), AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore::take_nonblocking(), and VRBRAIN::VRBRAINUARTDriver::write().
virtual void AP_HAL::Scheduler::init (void * implspecific) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
Referenced by main_loop(), HAL_Linux::run(), HAL_Empty::run(), HAL_SITL::run(), and HAL_FLYMAPLE::run().
virtual uint32_t AP_HAL::Scheduler::micros () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), AP_Compass_LSM303D::_collect_samples(), AP_InertialSensor_PX4::_new_accel_sample(), AP_InertialSensor_PX4::_new_gyro_sample(), Linux::RCInput_Raspilot::_poll_data(), HALSITL::SITL_State::_simulator_servos(), AP_Baro_MS56XX::_timer(), Linux::SPIUARTDriver::_timer_tick(), Linux::RPIOUARTDriver::_timer_tick(), VRBRAIN::VRBRAINRCOutput::_timer_tick(), PX4::PX4RCOutput::_timer_tick(), PX4::PX4AnalogIn::_timer_tick(), VRBRAIN::VRBRAINAnalogIn::_timer_tick(), Linux::RCOutput_Raspilot::_update(), AP_Compass_LSM303D::_update(), AP_ADC_ADS1115::_update(), ADS1115AnalogIn::_update(), RaspilotAnalogIn::_update(), AP_Compass_AK8963::_update(), AP_TECS::_update_speed(), AP_Compass_HMC5843::accumulate(), AP_Baro_MS56XX::AP_Baro_MS56XX(), AP_PerfMon::AP_PerfMon(), AP_PerfMon::ClearAll(), AP_PerfMon::DisplayAndClear(), AP_PerfMon::DisplayResults(), AP_ADC_ADS7844::Init(), loop(), motor_order_test(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_HIL::read(), AP_ADC_ADS7844::read(), AP_BattMonitor_SMBus_PX4::read(), AP_BattMonitor_Bebop::read(), AP_BattMonitor_Analog::read(), AP_Scheduler::run(), GCS_MAVLINK::send_raw_imu(), SITL::Gimbal::send_report(), Compass::setHIL(), setup(), DataFlashTest::setup(), AP_PerfMon::start(), AP_PerfMon::stop(), test_one_offset(), AP_Scheduler::time_available_usec(), SITL::Gimbal::update(), AP_TECS::update_50hz(), AP_TECS::update_pitch_throttle(), and AP_InertialSensor::wait_for_sample().
virtual uint64_t AP_HAL::Scheduler::micros64 () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor_PX4::_get_accel_sample(), AP_InertialSensor_PX4::_get_gyro_sample(), AP_InertialSensor_PX4::_get_sample(), Linux::RCInput::_process_dsm_pulse(), PX4::PX4UARTDriver::_write_fd(), VRBRAIN::VRBRAINUARTDriver::_write_fd(), AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), DataFlash_Class::Log_Write_AHRS2(), DataFlash_Class::Log_Write_Airspeed(), DataFlash_Class::Log_Write_Attitude(), DataFlash_Class::Log_Write_Baro(), DataFlash_Class::Log_Write_Camera(), DataFlash_Class::Log_Write_Compass(), DataFlash_Class::Log_Write_Current(), DataFlash_Class::Log_Write_ESC(), DataFlash_Class::Log_Write_GPS(), DataFlash_Class::Log_Write_IMU(), DataFlash_Class::Log_Write_IMUDT(), DataFlash_Class::Log_Write_MavCmd(), DataFlash_Class::Log_Write_Message(), DataFlash_Class::Log_Write_Mode(), DataFlash_Class::Log_Write_Origin(), DataFlash_Class::Log_Write_Parameter(), DataFlash_Class::Log_Write_PID(), DataFlash_Class::Log_Write_POS(), DataFlash_Class::Log_Write_Power(), DataFlash_Class::Log_Write_Radio(), DataFlash_Class::Log_Write_RCIN(), DataFlash_Class::Log_Write_RCOUT(), DataFlash_Class::Log_Write_RFND(), DataFlash_Class::Log_Write_RPM(), DataFlash_Class::Log_Write_RSSI(), SITL::SITL::Log_Write_SIMSTATE(), DataFlash_Class::Log_Write_Vibration(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), loop(), GCS_MAVLINK::send_vibration(), Linux::Semaphore::take(), AP_RangeFinder_PX4::update(), AP_RangeFinder_PX4_PWM::update(), AP_TECS::update_pitch_throttle(), HALSITL::SITL_State::wait_clock(), and AP_AutoTune::write_log().
virtual uint32_t AP_HAL::Scheduler::millis () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
Referenced by HALSITL::SITL_State::_airspeed_sensor(), AP_GPS_SBP::_attempt_state_update(), AP_Airspeed_I2C::_collect(), AP_GPS_UBLOX::_configure_gps(), AP_Baro_Backend::_copy_to_frontend(), HALSITL::SITL_State::_fdm_input(), HALSITL::SITL_State::_fdm_input_step(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_GPS_NMEA::_have_new_message(), AP_Airspeed_I2C::_measure(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SBP::_sbp_process_message(), HALSITL::SITL_State::_simulator_output(), AP_GPS_NMEA::_term_complete(), AP_Airspeed_I2C::_timer(), AP_HAL_FLYMAPLE_NS::FLYMAPLERCInput::_timer_capt_cb(), PX4::PX4AnalogIn::_timer_tick(), VRBRAIN::VRBRAINAnalogIn::_timer_tick(), HALSITL::SITL_State::_update_barometer(), HALSITL::SITL_State::_update_compass(), HALSITL::SITL_State::_update_flow(), OpticalFlow_backend::_update_frontend(), HALSITL::SITL_State::_update_gps(), HALSITL::SITL_State::_update_gps_ubx(), AP_GPS_GSOF::AP_GPS_GSOF(), AP_GPS_SBP::AP_GPS_SBP(), AP_InertialSensor_UserInteract_MAVLink::blocking_read(), AP_Baro::calibrate(), APM_OBC::check(), APM_OBC::check_altlimit(), ToneAlarm_PX4::check_cont_tone(), AC_Fence::check_fence(), CompassCalibrator::check_for_timeout(), AP_AutoTune::check_save(), AP_Baro_BMP085::Command_ReadPress(), AP_Baro_BMP085::Command_ReadTemp(), AP_GPS::detect_instance(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), AP_BattMonitor::exhausted(), AP_Mount_SToRM32::find_gimbal(), SchedTest::five_second_call(), AP_Baro::get_calibration_temperature(), AP_Airspeed_I2C::get_differential_pressure(), PID::get_pid(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), AP_Airspeed_I2C::get_temperature(), SmallEKF::getStatus(), AP_EPM::grab(), GCS_MAVLINK::handle_log_send_data(), GCS_MAVLINK::handle_log_send_listing(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_write_partial_list(), GCS_MAVLINK::handle_radio_status(), AP_RPM::healthy(), AP_AHRS_DCM::healthy(), AP_Mission::init(), AP_AHRS_NavEKF::initialised(), NavEKF_core::InitialiseVariables(), NavEKF2_core::InitialiseVariables(), AP_GPS_GSOF::inject_data(), AP_GPS_SBF::inject_data(), AP_GPS_SBP::inject_data(), AP_Arming::ins_checks(), AC_PosControl::is_active_xy(), AC_PosControl::is_active_z(), loop(), AC_Fence::manual_recovery_start(), AP_InertialSensor_MPU9150::mpu_read_fifo(), AP_HAL_FLYMAPLE_NS::FLYMAPLERCInput::new_input(), CompassCalibrator::new_sample(), PX4::PX4AnalogIn::next_stop_pin(), VRBRAIN::VRBRAINAnalogIn::next_stop_pin(), AP_AHRS_DCM::normalize(), SchedTest::one_hz_print(), TCPServerDevice::open(), DataFlash_Backend::periodic_tasks(), Linux::ToneAlarm::play(), ToneAlarm_PX4::play_tone(), AP_GPS_SBF::process_message(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), GCS_MAVLINK::queued_param_send(), AP_GPS_PX4::read(), AP_GPS_MTK19::read(), AP_GPS_GSOF::read(), AP_GPS_SBF::read(), AP_Airspeed::read(), AP_Compass_HMC5843::read(), AP_GPS_UBLOX::read(), Compass::read(), AP_Compass_HMC5843::read_raw(), AP_Compass_HMC5843::read_register(), NavEKF_core::readIMUData(), NavEKF2_core::readIMUData(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::reading_settled(), AP_Baro_BMP085::ReadPress(), AC_Fence::record_breach(), AP_EPM::release(), AP_Parachute::release(), AP_AHRS_DCM::reset(), GCS_MAVLINK::reset_cli_timeout(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_while_stopped_test(), SmallEKF::RunEKF(), AP_Mount_SToRM32::send_do_mount_control(), AP_Frsky_Telem::send_hub_frame(), GCS_MAVLINK::send_local_position(), AP_GPS::send_mavlink_gps_raw(), GCS_MAVLINK::send_radio_in(), GCS_MAVLINK::send_raw_imu(), SITL::Gimbal::send_report(), GCS_MAVLINK::send_scaled_pressure(), GCS_MAVLINK::send_system_time(), AP_Mount_SToRM32_serial::send_target_angles(), AP_Baro::set_external_temperature(), Linux::HeatPwm::set_imu_temp(), AP_Rally::set_rally_point_with_index(), AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_origin_and_destination(), CompassCalibrator::set_status(), AC_WPNav::set_wp_destination(), AP_Airspeed::setHIL(), AP_GPS::setHIL(), setup(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::setup_read(), show_data(), show_timing(), CompassCalibrator::start(), AP_AutoTune::start(), test_uart(), AP_GPS::time_epoch_usec(), AC_PosControl::time_since_last_xy_update(), VRBRAIN::VRBRAINUARTDriver::try_initialise(), PX4::PX4UARTDriver::try_initialise(), AP_RangeFinder_LightWareSerial::update(), AP_IRLock_PX4::update(), AP_OpticalFlow_Linux::update(), AP_RPM_PX4_PWM::update(), AP_Mount_SToRM32_serial::update(), AP_Baro::update(), AP_Mount_SToRM32::update(), AP_RangeFinder_PX4_PWM::update(), AP_Mount_Servo::update(), OpticalFlow::update(), Buzzer::update(), AP_EPM::update(), AP_AutoTune::update(), AP_GPS::update(), AP_Parachute::update(), AC_Sprayer::update(), AP_AHRS_DCM::update(), GCS_MAVLINK::update(), AP_Baro::update_calibration(), AP_AHRS_NavEKF::update_EKF1(), AP_AHRS_NavEKF::update_EKF2(), AP_ServoRelayEvents::update_events(), AP_GPS::update_instance(), AC_WPNav::update_spline(), AC_PosControl::update_vel_controller_xyz(), AC_WPNav::update_wpnav(), AC_PosControl::update_xy_controller(), AC_PosControl::update_z_controller(), NavEKF2_core::UpdateFilter(), NavEKF_core::UpdateFilter(), AP_AHRS_DCM::uptime_ms(), AP_AHRS_DCM::use_compass(), AP_AHRS_DCM::use_fast_gains(), AP_Mission::write_cmd_to_storage(), and AP_Compass_HMC5843::write_register().
virtual uint64_t AP_HAL::Scheduler::millis64 () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
virtual void AP_HAL::Scheduler::panic (const char * errormsg, ...) virtual
Reimplemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, Linux::Scheduler, HALSITL::SITLScheduler, VRBRAIN::VRBRAINScheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor::_add_backend(), Compass::_add_backend(), AP_ADC_ADS1115::_convert_register_data_to_mv(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), PX4::PX4Storage::_mtd_signature(), VRBRAIN::VRBRAINStorage::_mtd_signature(), PX4::PX4Storage::_mtd_write_signature(), VRBRAIN::VRBRAINStorage::_mtd_write_signature(), HALSITL::SITL_State::_parse_command_line(), AP_Compass_AK8963::_sem_take_nonblocking(), AP_InertialSensor::_start_backends(), Linux::Storage_FRAM::_storage_create(), Linux::Storage::_storage_create(), VRBRAIN::VRBRAINStorage::_storage_open(), PX4::PX4Storage::_storage_open(), Linux::Storage_FRAM::_storage_open(), Linux::Storage::_storage_open(), HALSITL::SITLUARTDriver::_uart_start_connection(), VRBRAIN::VRBRAINStorage::_upgrade_to_mtd(), PX4::PX4Storage::_upgrade_to_mtd(), AP_AK8963_SerialBus_MPU9250::AP_AK8963_SerialBus_MPU9250(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_Baro_MS56XX::AP_Baro_MS56XX(), AP_InertialSensor::AP_InertialSensor(), Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), HALSITL::SITLUARTDriver::begin(), AP_Baro::calibrate(), catch_sigbus(), SITL::JSBSim::create_templates(), Linux::SPIDeviceManager::cs_assert(), Linux::SPIDeviceManager::cs_release(), AP_InertialSensor::detect_backends(), Linux::HeatPwm::HeatPwm(), Linux::I2CDriver::I2CDriver(), Linux::RCOutput_Raspilot::init(), Linux::RCInput_Raspilot::init(), PX4::PX4RCInput::init(), VRBRAIN::VRBRAINRCInput::init(), VRBRAIN::VRBRAINRCOutput::init(), AP_ADC_ADS7844::Init(), PX4::PX4RCOutput::init(), Linux::RCOutput_PCA9685::init(), Linux::RCInput_UART::init(), Linux::RCOutput_Sysfs::init(), Linux::RCInput_ZYNQ::init(), AP_BoardConfig::init(), Linux::RCInput_PRU::init(), Linux::SPIDeviceDriver::init(), VRBRAIN::VRBRAINGPIO::init(), RaspilotAnalogIn::init(), AP_Baro::init(), Linux::RCInput_AioPRU::init(), PX4::PX4GPIO::init(), AP_SerialBus_SPI::init(), DataFlash_Class::Init(), Linux::SPIDeviceManager::init(), AP_Compass_LSM303D::init(), PX4::PX4AnalogIn::init(), Linux::RCOutput_Bebop::init(), VRBRAIN::VRBRAINAnalogIn::init(), AP_SerialBus_I2C::init(), Linux::GPIO_RPI::init(), Linux::GPIO_BBB::init(), AP_Mission::init(), Linux::Storage_FRAM::open(), Linux::PWM_Sysfs::PWM_Sysfs(), PX4::PX4I2CDriver::PX4I2CDriver(), Linux::RCInput_UART::RCInput_UART(), AP_ADC_ADS7844::read(), AP_InertialSensor::register_accel(), Compass::register_compass(), AP_InertialSensor::register_gyro(), AP_Baro::register_sensor(), setup(), AP_InertialSensor_MPU6000::start(), SITL::JSBSim::start_JSBSim(), AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore::take(), and Linux::RCInput_RPI::termination_handler().
virtual void AP_HAL::Scheduler::reboot (bool hold_in_bootloader) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, Linux::Scheduler, HALSITL::SITLScheduler, VRBRAIN::VRBRAINScheduler, and Empty::EmptyScheduler.
Referenced by Compass::compass_cal_update(), and loop().
virtual void AP_HAL::Scheduler::register_delay_callback (AP_HAL::Proc , uint16_t min_time_ms) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, HALSITL::SITLScheduler, Linux::Scheduler, and Empty::EmptyScheduler.
virtual void AP_HAL::Scheduler::register_io_process (AP_HAL::MemberProc) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by ToshibaLED_PX4::hw_init(), OreoLED_PX4::init(), and AP_Frsky_Telem::init().
virtual void AP_HAL::Scheduler::register_timer_failsafe (AP_HAL::Proc , uint32_t period_us) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, Linux::Scheduler, HALSITL::SITLScheduler, VRBRAIN::VRBRAINScheduler, and Empty::EmptyScheduler.
Referenced by setup().
virtual void AP_HAL::Scheduler::register_timer_process (AP_HAL::MemberProc) pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_MPU9250::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_Baro_MS56XX::AP_Baro_MS56XX(), Linux::RCOutput_Raspilot::init(), Linux::RCInput_Raspilot::init(), AP_ADC_ADS7844::Init(), AP_ADC_ADS1115::init(), ADS1115AnalogIn::init(), RaspilotAnalogIn::init(), AP_Airspeed_I2C::init(), AP_Compass_AK8963::init(), AP_Compass_LSM303D::init(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogIn::init(), setup(), and AP_InertialSensor_MPU6000::start().
virtual void AP_HAL::Scheduler::resume_timer_procs () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_InertialSensor_MPU6000::_init_sensor(), AP_Baro_MS56XX::AP_Baro_MS56XX(), AP_ADC_ADS7844::Ch(), AP_ADC_ADS7844::Ch6(), AP_ADC_ADS7844::Init(), AP_ADC_ADS1115::init(), ADS1115AnalogIn::init(), RaspilotAnalogIn::init(), AP_Compass_LSM303D::init(), AP_Compass_AK8963::init(), AP_Compass_HMC5843::init(), AP_Compass_AK8963::read(), AP_Compass_LSM303D::read(), PX4::PX4AnalogSource::read_average(), VRBRAIN::VRBRAINAnalogSource::read_average(), PX4::PX4AnalogSource::set_pin(), VRBRAIN::VRBRAINAnalogSource::set_pin(), AP_InertialSensor_MPU6000::start(), AP_InertialSensor_Flymaple::update(), AP_InertialSensor_MPU9150::update(), AP_InertialSensor_MPU6000::update(), and AP_Baro_MS56XX::update().
virtual void AP_HAL::Scheduler::set_timer_speed (uint16_t speed_hz) inline virtual
optional function to set timer speed in Hz
Definition at line 65 of file Scheduler.h.
virtual void AP_HAL::Scheduler::stop_clock (uint64_t time_usec) inline virtual
optional function to stop clock at a given time, used by log replay
Reimplemented in HALSITL::SITLScheduler, and Linux::Scheduler.
Definition at line 70 of file Scheduler.h.
Referenced by HALSITL::SITL_State::_fdm_input(), HALSITL::SITL_State::_fdm_input_local(), and HALSITL::SITL_State::_sitl_setup().
virtual void AP_HAL::Scheduler::suspend_timer_procs () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_InertialSensor_MPU6000::_init_sensor(), AP_Baro_MS56XX::AP_Baro_MS56XX(), AP_ADC_ADS7844::Ch(), AP_ADC_ADS7844::Ch6(), AP_ADC_ADS7844::Init(), AP_ADC_ADS1115::init(), ADS1115AnalogIn::init(), RaspilotAnalogIn::init(), AP_Compass_LSM303D::init(), AP_Compass_AK8963::init(), AP_Compass_HMC5843::init(), AP_Compass_AK8963::read(), AP_Compass_LSM303D::read(), PX4::PX4AnalogSource::read_average(), VRBRAIN::VRBRAINAnalogSource::read_average(), PX4::PX4AnalogSource::set_pin(), VRBRAIN::VRBRAINAnalogSource::set_pin(), AP_InertialSensor_MPU6000::start(), AP_InertialSensor_Flymaple::update(), AP_InertialSensor_MPU9150::update(), AP_InertialSensor_MPU6000::update(), and AP_Baro_MS56XX::update().
virtual void AP_HAL::Scheduler::system_initialized () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by main_loop(), HAL_Linux::run(), HAL_Empty::run(), HAL_SITL::run(), and HAL_FLYMAPLE::run().
virtual bool AP_HAL::Scheduler::system_initializing () pure virtual
Implemented in PX4::PX4Scheduler, AP_HAL_FLYMAPLE_NS::FLYMAPLEScheduler, VRBRAIN::VRBRAINScheduler, Linux::Scheduler, HALSITL::SITLScheduler, and Empty::EmptyScheduler.
Referenced by AP_Compass_AK8963::_sem_take_nonblocking().
Member Data Documentation
virtual void AP_HAL::Scheduler::NORETURN = 0
Definition at line 59 of file Scheduler.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/Scheduler.h