APM:Libraries: VRBRAIN::VRBRAINScheduler Class Reference
VRBRAIN::VRBRAINScheduler Class Reference
#include <Scheduler.h>
Public Member Functions
VRBRAINScheduler ()
void init (void *unused)
void delay (uint16_t ms)
uint32_t millis ()
uint32_t micros ()
uint64_t millis64 ()
uint64_t micros64 ()
void delay_microseconds (uint16_t us)
void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
void register_timer_process (AP_HAL::MemberProc)
void register_io_process (AP_HAL::MemberProc)
void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us)
void suspend_timer_procs ()
void resume_timer_procs ()
void reboot (bool hold_in_bootloader)
void panic (const char *errormsg,...) FORMAT(2
bool in_timerprocess ()
bool system_initializing ()
void system_initialized ()
void hal_initialized ()
Public Member Functions inherited from AP_HAL::Scheduler
Scheduler ()
virtual void delay_microseconds_boost (uint16_t us)
virtual void set_timer_speed (uint16_t speed_hz)
virtual void stop_clock (uint64_t time_usec)
Public Attributes
void NORETURN
Public Attributes inherited from AP_HAL::Scheduler
virtual void NORETURN = 0
Private Member Functions
void * _timer_thread (void)
void * _io_thread (void)
void * _uart_thread (void)
void _run_timers (bool called_from_timer_thread)
void _run_io (void)
void delay_microseconds_semaphore (uint16_t us)
Private Attributes
bool _initialized
volatile bool _hal_initialized
AP_HAL::Proc _delay_cb
uint16_t _min_delay_cb_ms
AP_HAL::Proc _failsafe
volatile bool _timer_pending
volatile bool _timer_suspended
AP_HAL::MemberProc _timer_proc [VRBRAIN_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_timer_procs
volatile bool _in_timer_proc
AP_HAL::MemberProc _io_proc [VRBRAIN_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_io_procs
volatile bool _in_io_proc
volatile bool _timer_event_missed
pid_t _main_task_pid
pthread_t _timer_thread_ctx
pthread_t _io_thread_ctx
pthread_t _uart_thread_ctx
perf_counter_t _perf_timers
perf_counter_t _perf_io_timers
perf_counter_t _perf_delay
Detailed Description
Definition at line 23 of file Scheduler.h.
Constructor & Destructor Documentation
VRBRAINScheduler::VRBRAINScheduler ()
Definition at line 33 of file Scheduler.cpp.
Member Function Documentation
void * VRBRAINScheduler::_io_thread (void) private
Definition at line 309 of file Scheduler.cpp.
Referenced by init().
void VRBRAINScheduler::_run_io (void) private
Definition at line 272 of file Scheduler.cpp.
Referenced by _io_thread().
void VRBRAINScheduler::_run_timers (bool called_from_timer_thread) private
Definition at line 212 of file Scheduler.cpp.
Referenced by _timer_thread(), and resume_timer_procs().
void * VRBRAINScheduler::_timer_thread (void) private
Definition at line 243 of file Scheduler.cpp.
Referenced by init().
void * VRBRAINScheduler::_uart_thread (void) private
Definition at line 291 of file Scheduler.cpp.
Referenced by init().
void VRBRAINScheduler::delay (uint16_t ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 125 of file Scheduler.cpp.
void VRBRAINScheduler::delay_microseconds (uint16_t us) virtual
Implements AP_HAL::Scheduler.
Definition at line 109 of file Scheduler.cpp.
void VRBRAINScheduler::delay_microseconds_semaphore (uint16_t usec) private
delay for a specified number of microseconds using a semaphore wait
Definition at line 100 of file Scheduler.cpp.
Referenced by _timer_thread(), _uart_thread(), delay(), and delay_microseconds().
void VRBRAIN::VRBRAINScheduler::hal_initialized () inline
Definition at line 47 of file Scheduler.h.
Referenced by main_loop().
bool VRBRAINScheduler::in_timerprocess () virtual
Implements AP_HAL::Scheduler.
Definition at line 342 of file Scheduler.cpp.
Referenced by delay().
void VRBRAINScheduler::init (void * unused) virtual
Implements AP_HAL::Scheduler.
Definition at line 39 of file Scheduler.cpp.
uint32_t VRBRAINScheduler::micros () virtual
Implements AP_HAL::Scheduler.
Definition at line 87 of file Scheduler.cpp.
uint64_t VRBRAINScheduler::micros64 () virtual
Implements AP_HAL::Scheduler.
Definition at line 77 of file Scheduler.cpp.
Referenced by delay(), delay_microseconds(), micros(), and millis64().
uint32_t VRBRAINScheduler::millis () virtual
Implements AP_HAL::Scheduler.
Definition at line 92 of file Scheduler.cpp.
Referenced by _timer_thread().
uint64_t VRBRAINScheduler::millis64 () virtual
Implements AP_HAL::Scheduler.
Definition at line 82 of file Scheduler.cpp.
Referenced by millis().
void VRBRAINScheduler::panic (const char * errormsg, ...) virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 328 of file Scheduler.cpp.
Referenced by system_initialized().
void VRBRAINScheduler::reboot (bool hold_in_bootloader) virtual
Implements AP_HAL::Scheduler.
Definition at line 207 of file Scheduler.cpp.
void VRBRAINScheduler::register_delay_callback (AP_HAL::Proc proc, uint16_t min_time_ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 149 of file Scheduler.cpp.
void VRBRAINScheduler::register_io_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 172 of file Scheduler.cpp.
void VRBRAINScheduler::register_timer_failsafe (AP_HAL::Proc failsafe, uint32_t period_us) virtual
Implements AP_HAL::Scheduler.
Definition at line 188 of file Scheduler.cpp.
void VRBRAINScheduler::register_timer_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 156 of file Scheduler.cpp.
void VRBRAINScheduler::resume_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 198 of file Scheduler.cpp.
void VRBRAINScheduler::suspend_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 193 of file Scheduler.cpp.
void VRBRAINScheduler::system_initialized () virtual
Implements AP_HAL::Scheduler.
Definition at line 351 of file Scheduler.cpp.
bool VRBRAINScheduler::system_initializing () virtual
Implements AP_HAL::Scheduler.
Definition at line 347 of file Scheduler.cpp.
Member Data Documentation
AP_HAL::Proc VRBRAIN::VRBRAINScheduler::_delay_cb private
Definition at line 52 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
AP_HAL::Proc VRBRAIN::VRBRAINScheduler::_failsafe private
Definition at line 54 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_failsafe().
volatile bool VRBRAIN::VRBRAINScheduler::_hal_initialized private
Definition at line 51 of file Scheduler.h.
Referenced by _io_thread(), _timer_thread(), _uart_thread(), and hal_initialized().
volatile bool VRBRAIN::VRBRAINScheduler::_in_io_proc private
Definition at line 65 of file Scheduler.h.
Referenced by _run_io().
volatile bool VRBRAIN::VRBRAINScheduler::_in_timer_proc private
Definition at line 61 of file Scheduler.h.
Referenced by _run_timers().
bool VRBRAIN::VRBRAINScheduler::_initialized private
Definition at line 50 of file Scheduler.h.
Referenced by system_initialized(), and system_initializing().
AP_HAL::MemberProc VRBRAIN::VRBRAINScheduler::_io_proc[VRBRAIN_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 63 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
pthread_t VRBRAIN::VRBRAINScheduler::_io_thread_ctx private
Definition at line 71 of file Scheduler.h.
Referenced by init().
pid_t VRBRAIN::VRBRAINScheduler::_main_task_pid private
Definition at line 69 of file Scheduler.h.
Referenced by in_timerprocess(), and init().
uint16_t VRBRAIN::VRBRAINScheduler::_min_delay_cb_ms private
Definition at line 53 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
uint8_t VRBRAIN::VRBRAINScheduler::_num_io_procs private
Definition at line 64 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
uint8_t VRBRAIN::VRBRAINScheduler::_num_timer_procs private
Definition at line 60 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
perf_counter_t VRBRAIN::VRBRAINScheduler::_perf_delay private
Definition at line 85 of file Scheduler.h.
Referenced by delay(), and delay_microseconds().
perf_counter_t VRBRAIN::VRBRAINScheduler::_perf_io_timers private
Definition at line 84 of file Scheduler.h.
Referenced by _io_thread().
perf_counter_t VRBRAIN::VRBRAINScheduler::_perf_timers private
Definition at line 83 of file Scheduler.h.
Referenced by _timer_thread().
volatile bool VRBRAIN::VRBRAINScheduler::_timer_event_missed private
Definition at line 67 of file Scheduler.h.
Referenced by _run_timers(), and resume_timer_procs().
volatile bool VRBRAIN::VRBRAINScheduler::_timer_pending private
Definition at line 55 of file Scheduler.h.
AP_HAL::MemberProc VRBRAIN::VRBRAINScheduler::_timer_proc[VRBRAIN_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 59 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
volatile bool VRBRAIN::VRBRAINScheduler::_timer_suspended private
Definition at line 57 of file Scheduler.h.
Referenced by _run_io(), _run_timers(), resume_timer_procs(), and suspend_timer_procs().
pthread_t VRBRAIN::VRBRAINScheduler::_timer_thread_ctx private
Definition at line 70 of file Scheduler.h.
Referenced by init().
pthread_t VRBRAIN::VRBRAINScheduler::_uart_thread_ctx private
Definition at line 72 of file Scheduler.h.
Referenced by init().
void VRBRAIN::VRBRAINScheduler::NORETURN
Definition at line 42 of file Scheduler.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL_VRBRAIN/Scheduler.h
libraries/AP_HAL_VRBRAIN/Scheduler.cpp