APM:Libraries: AP_GPS_GSOF Class Reference
AP_GPS_GSOF Class Reference
#include <AP_GPS_GSOF.h>
Classes
struct gsof_msg_parser_t
Public Member Functions
AP_GPS_GSOF (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
AP_GPS::GPS_Status highest_supported_status (void)
bool read ()
void inject_data (uint8_t *data, uint8_t len)
Public Member Functions inherited from AP_GPS_Backend
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual void send_mavlink_gps_rtk (mavlink_channel_t chan)
virtual void send_mavlink_gps2_rtk (mavlink_channel_t chan)
Private Member Functions
bool parse (uint8_t temp)
bool process_message ()
void requestBaud ()
void requestGSOF (uint8_t messagetype)
double SwapDouble (uint8_t *src, uint32_t pos)
float SwapFloat (uint8_t *src, uint32_t pos)
uint32_t SwapUint32 (uint8_t *src, uint32_t pos)
uint16_t SwapUint16 (uint8_t *src, uint32_t pos)
Private Attributes
struct AP_GPS_GSOF::gsof_msg_parser_t gsof_msg
uint8_t packetcount = 0
uint32_t gsofmsg_time = 0
uint8_t gsofmsgreq_index = 0
uint8_t gsofmsgreq [5] = {1,2,8,9,12}
uint32_t last_hdop = 9999
uint32_t crc_error_counter = 0
uint32_t last_injected_data_ms = 0
Static Private Attributes
static const uint8_t GSOF_STX = 0x02
static const uint8_t GSOF_ETX = 0x03
Additional Inherited Members
Protected Member Functions inherited from AP_GPS_Backend
int32_t swap_int32 (int32_t v) const
int16_t swap_int16 (int16_t v) const
void fill_3d_velocity (void)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
Protected Attributes inherited from AP_GPS_Backend
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
Detailed Description
Definition at line 27 of file AP_GPS_GSOF.h.
Constructor & Destructor Documentation
AP_GPS_GSOF::AP_GPS_GSOF (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port)
Definition at line 42 of file AP_GPS_GSOF.cpp.
Member Function Documentation
AP_GPS::GPS_Status AP_GPS_GSOF::highest_supported_status (void) inline virtual
Reimplemented from AP_GPS_Backend.
Definition at line 32 of file AP_GPS_GSOF.h.
void AP_GPS_GSOF::inject_data (uint8_t * data, uint8_t len) virtual
Reimplemented from AP_GPS_Backend.
Definition at line 344 of file AP_GPS_GSOF.cpp.
bool AP_GPS_GSOF::parse (uint8_t temp) private
Definition at line 79 of file AP_GPS_GSOF.cpp.
Referenced by read().
bool AP_GPS_GSOF::process_message (void) private
Definition at line 240 of file AP_GPS_GSOF.cpp.
Referenced by parse().
bool AP_GPS_GSOF::read (void) virtual
Implements AP_GPS_Backend.
Definition at line 57 of file AP_GPS_GSOF.cpp.
void AP_GPS_GSOF::requestBaud () private
Definition at line 135 of file AP_GPS_GSOF.cpp.
Referenced by AP_GPS_GSOF().
void AP_GPS_GSOF::requestGSOF (uint8_t messagetype) private
Definition at line 156 of file AP_GPS_GSOF.cpp.
Referenced by read().
double AP_GPS_GSOF::SwapDouble (uint8_t * src, uint32_t pos) private
Definition at line 178 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
float AP_GPS_GSOF::SwapFloat (uint8_t * src, uint32_t pos) private
Definition at line 197 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
uint16_t AP_GPS_GSOF::SwapUint16 (uint8_t * src, uint32_t pos) private
Definition at line 227 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
uint32_t AP_GPS_GSOF::SwapUint32 (uint8_t * src, uint32_t pos) private
Definition at line 212 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
Member Data Documentation
uint32_t AP_GPS_GSOF::crc_error_counter = 0 private
Definition at line 88 of file AP_GPS_GSOF.h.
const uint8_t AP_GPS_GSOF::GSOF_ETX = 0x03 static private
Definition at line 79 of file AP_GPS_GSOF.h.
struct AP_GPS_GSOF::gsof_msg_parser_t AP_GPS_GSOF::gsof_msg private
Referenced by AP_GPS_GSOF(), parse(), and process_message().
const uint8_t AP_GPS_GSOF::GSOF_STX = 0x02 static private
Definition at line 78 of file AP_GPS_GSOF.h.
Referenced by parse().
uint32_t AP_GPS_GSOF::gsofmsg_time = 0 private
Definition at line 83 of file AP_GPS_GSOF.h.
Referenced by AP_GPS_GSOF(), and read().
uint8_t AP_GPS_GSOF::gsofmsgreq[5] = {1,2,8,9,12} private
Definition at line 85 of file AP_GPS_GSOF.h.
Referenced by read().
uint8_t AP_GPS_GSOF::gsofmsgreq_index = 0 private
Definition at line 84 of file AP_GPS_GSOF.h.
Referenced by read().
uint32_t AP_GPS_GSOF::last_hdop = 9999 private
Definition at line 87 of file AP_GPS_GSOF.h.
uint32_t AP_GPS_GSOF::last_injected_data_ms = 0 private
Definition at line 89 of file AP_GPS_GSOF.h.
Referenced by inject_data().
uint8_t AP_GPS_GSOF::packetcount = 0 private
Definition at line 81 of file AP_GPS_GSOF.h.
Referenced by requestBaud(), and requestGSOF().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS_GSOF.h
libraries/AP_GPS/AP_GPS_GSOF.cpp