APM:Libraries: AP_BattMonitor_Bebop Class Reference
AP_BattMonitor_Bebop Class Reference
#include <AP_BattMonitor_Bebop.h>
Public Member Functions
AP_BattMonitor_Bebop (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
virtual ~AP_BattMonitor_Bebop (void)
void init ()
void read ()
Public Member Functions inherited from AP_BattMonitor_Backend
AP_BattMonitor_Backend (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
virtual ~AP_BattMonitor_Backend (void)
uint8_t capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
void set_capacity (uint32_t capacity)
set capacity for this instance
Private Member Functions
float _compute_compensation (const uint16_t *rpm, float vbat_raw)
float _filter_voltage (float vbat_raw)
float _compute_battery_percentage (float vbat)
Private Attributes
float _prev_vbat_raw
float _prev_vbat
float _battery_voltage_max
Additional Inherited Members
Protected Attributes inherited from AP_BattMonitor_Backend
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
uint8_t _instance
Detailed Description
Definition at line 24 of file AP_BattMonitor_Bebop.h.
Constructor & Destructor Documentation
AP_BattMonitor_Bebop::AP_BattMonitor_Bebop (AP_BattMonitor & mon, uint8_t instance, AP_BattMonitor::BattMonitor_State & mon_state) inline
Definition at line 28 of file AP_BattMonitor_Bebop.h.
virtual AP_BattMonitor_Bebop::~AP_BattMonitor_Bebop (void) inline virtual
Definition at line 35 of file AP_BattMonitor_Bebop.h.
Member Function Documentation
float AP_BattMonitor_Bebop::_compute_battery_percentage (float vbat) private
Definition at line 116 of file AP_BattMonitor_Bebop.cpp.
Referenced by read().
float AP_BattMonitor_Bebop::_compute_compensation (const uint16_t * rpm, float vbat_raw) private
Definition at line 98 of file AP_BattMonitor_Bebop.cpp.
Referenced by read().
float AP_BattMonitor_Bebop::_filter_voltage (float vbat_raw) private
Definition at line 68 of file AP_BattMonitor_Bebop.cpp.
Referenced by read().
void AP_BattMonitor_Bebop::init (void) virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 60 of file AP_BattMonitor_Bebop.cpp.
void AP_BattMonitor_Bebop::read (void) virtual
Implements AP_BattMonitor_Backend.
Definition at line 139 of file AP_BattMonitor_Bebop.cpp.
Member Data Documentation
float AP_BattMonitor_Bebop::_battery_voltage_max private
Definition at line 46 of file AP_BattMonitor_Bebop.h.
Referenced by init(), and read().
float AP_BattMonitor_Bebop::_prev_vbat private
Definition at line 45 of file AP_BattMonitor_Bebop.h.
Referenced by _filter_voltage(), and init().
float AP_BattMonitor_Bebop::_prev_vbat_raw private
Definition at line 44 of file AP_BattMonitor_Bebop.h.
Referenced by _filter_voltage(), and init().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_Bebop.h
libraries/AP_BattMonitor/AP_BattMonitor_Bebop.cpp