APM:Libraries: AP_AHRS_DCM Class Reference
AP_AHRS_DCM Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_AHRS_DCM.h>
Public Member Functions
AP_AHRS_DCM (AP_InertialSensor &ins, AP_Baro &baro, AP_GPS &gps)
const Vector3f & get_gyro (void) const
const Matrix3f & get_dcm_matrix (void) const
const Vector3f & get_gyro_drift (void) const
void reset_gyro_drift (void)
void update (void)
void reset (bool recover_eulers=false)
void reset_attitude (const float &roll, const float &pitch, const float &yaw)
virtual bool get_position (struct Location &loc) const
float get_error_rp (void) const
float get_error_yaw (void) const
Vector3f wind_estimate (void)
bool airspeed_estimate (float *airspeed_ret) const
bool use_compass (void)
void set_home (const Location &loc)
void estimate_wind (void)
bool healthy (void) const
uint32_t uptime_ms (void) const
Public Member Functions inherited from AP_AHRS
AP_AHRS (AP_InertialSensor &ins, AP_Baro &baro, AP_GPS &gps)
virtual ~AP_AHRS ()
virtual void init ()
void set_fly_forward (bool b)
bool get_fly_forward (void) const
AHRS_VehicleClass get_vehicle_class (void) const
void set_vehicle_class (AHRS_VehicleClass vclass)
void set_wind_estimation (bool b)
void set_compass (Compass *compass)
const Compass * get_compass () const
void set_optflow (const OpticalFlow *optflow)
const OpticalFlow * get_optflow () const
void set_orientation ()
void set_airspeed (AP_Airspeed *airspeed)
const AP_Airspeed * get_airspeed (void) const
const AP_GPS & get_gps () const
const AP_InertialSensor & get_ins () const
const AP_Baro & get_baro () const
virtual const Vector3f & get_accel_ef (uint8_t i) const
virtual const Vector3f & get_accel_ef (void) const
virtual const Vector3f & get_accel_ef_blended (void) const
float get_yaw_rate_earth (void) const
virtual const char * prearm_failure_reason (void) const
bool airspeed_estimate_true (float *airspeed_ret) const
float get_EAS2TAS (void) const
bool airspeed_sensor_enabled (void) const
virtual Vector2f groundspeed_vector (void)
virtual bool get_velocity_NED (Vector3f &vec) const
virtual bool get_relative_position_NED (Vector3f &vec) const
float groundspeed (void) const
bool yaw_initialised (void) const
void set_correct_centrifugal (bool setting)
bool get_correct_centrifugal (void) const
const Vector3f & get_trim () const
virtual void set_trim (Vector3f new_trim)
virtual void add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom=true)
float cos_roll () const
float cos_pitch () const
float cos_yaw () const
float sin_roll () const
float sin_pitch () const
float sin_yaw () const
virtual bool get_secondary_attitude (Vector3f &eulers)
virtual bool get_secondary_position (struct Location &loc)
const struct Location & get_home (void) const
virtual bool have_inertial_nav (void) const
uint8_t get_active_accel_instance (void) const
virtual bool initialised (void) const
virtual uint32_t getLastYawResetAngle (float &yawAng) const
virtual uint32_t getLastPosNorthEastReset (Vector2f &pos) const
virtual uint32_t getLastVelNorthEastReset (Vector2f &vel) const
virtual bool resetHeightDatum (void)
Private Member Functions
void matrix_update (float _G_Dt)
void normalize (void)
void check_matrix (void)
bool renorm (Vector3f const &a, Vector3f &result)
void drift_correction (float deltat)
void drift_correction_yaw (void)
float yaw_error_compass ()
void euler_angles (void)
bool have_gps (void) const
bool use_fast_gains (void) const
Vector3f ra_delayed (uint8_t instance, const Vector3f &ra)
float _P_gain (float spin_rate)
float _yaw_gain (void) const
Private Attributes
float _ki
float _ki_yaw
Matrix3f _dcm_matrix
Matrix3f _body_dcm_matrix
Vector3f _omega_P
Vector3f _omega_yaw_P
Vector3f _omega_I
Vector3f _omega_I_sum
float _omega_I_sum_time
Vector3f _omega
Vector3f _ra_delay_buffer [INS_MAX_INSTANCES]
float _renorm_val_sum
uint16_t _renorm_val_count
float _error_rp
float _error_yaw
uint32_t _gps_last_update
Vector3f _ra_sum [INS_MAX_INSTANCES]
Vector3f _last_velocity
float _ra_deltat
uint32_t _ra_sum_start
float _last_declination
Vector2f _mag_earth
bool _have_gps_lock
int32_t _last_lat
int32_t _last_lng
float _position_offset_north
float _position_offset_east
bool _have_position
Vector3f _last_fuse
Vector3f _last_vel
uint32_t _last_wind_time
float _last_airspeed
uint32_t _last_consistent_heading
Vector3f _wind
float _imu1_weight
uint32_t _last_failure_ms
uint32_t _last_startup_ms
Additional Inherited Members
Public Attributes inherited from AP_AHRS
float roll
float pitch
float yaw
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
Static Public Attributes inherited from AP_AHRS
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions inherited from AP_AHRS
void update_trig (void)
void update_cd_values (void)
Protected Attributes inherited from AP_AHRS
AHRS_VehicleClass _vehicle_class
AP_Float _kp_yaw
AP_Float _kp
AP_Float gps_gain
AP_Float beta
AP_Int8 _gps_use
AP_Int8 _wind_max
AP_Int8 _board_orientation
AP_Int8 _gps_minsats
AP_Int8 _gps_delay
AP_Int8 _ekf_type
struct AP_AHRS::ahrs_flags _flags
Compass * _compass
const OpticalFlow * _optflow
AP_Airspeed * _airspeed
uint32_t _compass_last_update
AP_InertialSensor & _ins
AP_Baro & _baro
const AP_GPS & _gps
AP_Vector3f _trim
float _gyro_drift_limit
Vector3f _accel_ef [INS_MAX_INSTANCES]
Vector3f _accel_ef_blended
Vector2f _lp
Vector2f _hp
Vector2f _lastGndVelADS
struct Location _home
float _cos_roll
float _cos_pitch
float _cos_yaw
float _sin_roll
float _sin_pitch
float _sin_yaw
uint8_t _active_accel_instance
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 25 of file AP_AHRS_DCM.h.
Constructor & Destructor Documentation
AP_AHRS_DCM::AP_AHRS_DCM (AP_InertialSensor & ins, AP_Baro & baro, AP_GPS & gps) inline
Definition at line 29 of file AP_AHRS_DCM.h.
Member Function Documentation
float AP_AHRS_DCM::_P_gain (float spin_rate) private
Definition at line 336 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), and drift_correction_yaw().
float AP_AHRS_DCM::_yaw_gain (void) const private
Definition at line 355 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction_yaw().
bool AP_AHRS_DCM::airspeed_estimate (float * airspeed_ret) const virtual
Reimplemented from AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 971 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::airspeed_estimate().
void AP_AHRS_DCM::check_matrix (void) private
Definition at line 193 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), and update().
void AP_AHRS_DCM::drift_correction (float deltat) private
Definition at line 570 of file AP_AHRS_DCM.cpp.
Referenced by update().
void AP_AHRS_DCM::drift_correction_yaw (void) private
Definition at line 428 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction().
void AP_AHRS_DCM::estimate_wind (void)
Definition at line 878 of file AP_AHRS_DCM.cpp.
void AP_AHRS_DCM::euler_angles (void) private
Definition at line 945 of file AP_AHRS_DCM.cpp.
Referenced by update().
const Matrix3f& AP_AHRS_DCM::get_dcm_matrix (void) const inline virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 68 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_dcm_matrix(), and loop().
float AP_AHRS_DCM::get_error_rp (void) const inline virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 92 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_error_rp().
float AP_AHRS_DCM::get_error_yaw (void) const inline virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 95 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_error_yaw().
const Vector3f& AP_AHRS_DCM::get_gyro (void) const inline virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 63 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_gyro().
const Vector3f& AP_AHRS_DCM::get_gyro_drift (void) const inline virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 73 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_gyro_drift(), and loop().
bool AP_AHRS_DCM::get_position (struct Location & loc) const virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 956 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::get_position(), and AP_AHRS_NavEKF::get_secondary_position().
bool AP_AHRS_DCM::have_gps (void) const private
Definition at line 367 of file AP_AHRS_DCM.cpp.
Referenced by airspeed_estimate(), drift_correction(), drift_correction_yaw(), and use_compass().
bool AP_AHRS_DCM::healthy (void) const virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1011 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::healthy().
void AP_AHRS_DCM::matrix_update (float _G_Dt) private
Definition at line 95 of file AP_AHRS_DCM.cpp.
Referenced by update().
void AP_AHRS_DCM::normalize (void) private
Definition at line 279 of file AP_AHRS_DCM.cpp.
Referenced by check_matrix(), and update().
Vector3f AP_AHRS_DCM::ra_delayed (uint8_t instance, const Vector3f & ra) private
return an accel vector delayed by AHRS_ACCEL_DELAY samples for a specific accelerometer instance
Definition at line 547 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction().
bool AP_AHRS_DCM::renorm (Vector3f const & a, Vector3f & result) private
Definition at line 223 of file AP_AHRS_DCM.cpp.
Referenced by normalize().
void AP_AHRS_DCM::reset (bool recover_eulers = false) virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 135 of file AP_AHRS_DCM.cpp.
Referenced by check_matrix(), normalize(), and AP_AHRS_NavEKF::reset().
void AP_AHRS_DCM::reset_attitude (const float & roll, const float & pitch, const float & yaw) virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 184 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::reset_attitude().
void AP_AHRS_DCM::reset_gyro_drift (void) virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 42 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::reset_gyro_drift().
void AP_AHRS_DCM::set_home (const Location & loc) virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1002 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::set_home().
void AP_AHRS_DCM::update (void) virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 51 of file AP_AHRS_DCM.cpp.
Referenced by loop(), and AP_AHRS_NavEKF::update_DCM().
uint32_t AP_AHRS_DCM::uptime_ms (void) const virtual
Implements AP_AHRS.
Definition at line 1020 of file AP_AHRS_DCM.cpp.
bool AP_AHRS_DCM::use_compass (void) virtual
Reimplemented from AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 390 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), drift_correction_yaw(), and AP_AHRS_NavEKF::use_compass().
bool AP_AHRS_DCM::use_fast_gains (void) const private
Definition at line 383 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), and drift_correction_yaw().
Vector3f AP_AHRS_DCM::wind_estimate (void) inline virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 100 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::wind_estimate().
float AP_AHRS_DCM::yaw_error_compass (void) private
Definition at line 304 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction_yaw().
Member Data Documentation
Matrix3f AP_AHRS_DCM::_body_dcm_matrix private
Definition at line 139 of file AP_AHRS_DCM.h.
Referenced by euler_angles(), and get_dcm_matrix().
Matrix3f AP_AHRS_DCM::_dcm_matrix private
Definition at line 136 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_DCM(), check_matrix(), drift_correction(), drift_correction_yaw(), estimate_wind(), euler_angles(), matrix_update(), normalize(), reset(), reset_attitude(), and yaw_error_compass().
float AP_AHRS_DCM::_error_rp private
Definition at line 161 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_error_rp().
float AP_AHRS_DCM::_error_yaw private
Definition at line 162 of file AP_AHRS_DCM.h.
Referenced by drift_correction_yaw(), and get_error_yaw().
uint32_t AP_AHRS_DCM::_gps_last_update private
Definition at line 165 of file AP_AHRS_DCM.h.
Referenced by drift_correction_yaw().
bool AP_AHRS_DCM::_have_gps_lock private
Definition at line 178 of file AP_AHRS_DCM.h.
Referenced by drift_correction().
bool AP_AHRS_DCM::_have_position private
Definition at line 189 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
float AP_AHRS_DCM::_imu1_weight private
Definition at line 201 of file AP_AHRS_DCM.h.
Referenced by drift_correction().
float AP_AHRS_DCM::_ki private
Definition at line 120 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_DCM(), and drift_correction().
float AP_AHRS_DCM::_ki_yaw private
Definition at line 121 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_DCM(), and drift_correction_yaw().
float AP_AHRS_DCM::_last_airspeed private
Definition at line 195 of file AP_AHRS_DCM.h.
Referenced by airspeed_estimate(), and drift_correction().
uint32_t AP_AHRS_DCM::_last_consistent_heading private
Definition at line 196 of file AP_AHRS_DCM.h.
Referenced by use_compass().
float AP_AHRS_DCM::_last_declination private
Definition at line 174 of file AP_AHRS_DCM.h.
Referenced by yaw_error_compass().
uint32_t AP_AHRS_DCM::_last_failure_ms private
Definition at line 204 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), healthy(), and normalize().
Vector3f AP_AHRS_DCM::_last_fuse private
Definition at line 192 of file AP_AHRS_DCM.h.
Referenced by estimate_wind().
int32_t AP_AHRS_DCM::_last_lat private
Definition at line 181 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
int32_t AP_AHRS_DCM::_last_lng private
Definition at line 182 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
uint32_t AP_AHRS_DCM::_last_startup_ms private
Definition at line 207 of file AP_AHRS_DCM.h.
Referenced by reset(), update(), uptime_ms(), and use_fast_gains().
Vector3f AP_AHRS_DCM::_last_vel private
Definition at line 193 of file AP_AHRS_DCM.h.
Referenced by estimate_wind().
Vector3f AP_AHRS_DCM::_last_velocity private
Definition at line 169 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and estimate_wind().
uint32_t AP_AHRS_DCM::_last_wind_time private
Definition at line 194 of file AP_AHRS_DCM.h.
Referenced by estimate_wind().
Vector2f AP_AHRS_DCM::_mag_earth private
Definition at line 175 of file AP_AHRS_DCM.h.
Referenced by yaw_error_compass().
Vector3f AP_AHRS_DCM::_omega private
Definition at line 146 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), drift_correction_yaw(), get_gyro(), matrix_update(), and reset().
Vector3f AP_AHRS_DCM::_omega_I private
Definition at line 143 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), get_gyro_drift(), matrix_update(), reset(), and reset_gyro_drift().
Vector3f AP_AHRS_DCM::_omega_I_sum private
Definition at line 144 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), drift_correction_yaw(), and reset_gyro_drift().
float AP_AHRS_DCM::_omega_I_sum_time private
Definition at line 145 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and reset_gyro_drift().
Vector3f AP_AHRS_DCM::_omega_P private
Definition at line 141 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), matrix_update(), and reset().
Vector3f AP_AHRS_DCM::_omega_yaw_P private
Definition at line 142 of file AP_AHRS_DCM.h.
Referenced by drift_correction_yaw(), matrix_update(), and reset().
float AP_AHRS_DCM::_position_offset_east private
Definition at line 186 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
float AP_AHRS_DCM::_position_offset_north private
Definition at line 185 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
Vector3f AP_AHRS_DCM::_ra_delay_buffer[INS_MAX_INSTANCES] private
Definition at line 150 of file AP_AHRS_DCM.h.
Referenced by ra_delayed().
float AP_AHRS_DCM::_ra_deltat private
Definition at line 170 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and update().
Vector3f AP_AHRS_DCM::_ra_sum[INS_MAX_INSTANCES] private
Definition at line 168 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and update().
uint32_t AP_AHRS_DCM::_ra_sum_start private
Definition at line 171 of file AP_AHRS_DCM.h.
Referenced by drift_correction().
uint16_t AP_AHRS_DCM::_renorm_val_count private
Definition at line 160 of file AP_AHRS_DCM.h.
Referenced by renorm().
float AP_AHRS_DCM::_renorm_val_sum private
Definition at line 159 of file AP_AHRS_DCM.h.
Referenced by renorm().
Vector3f AP_AHRS_DCM::_wind private
Definition at line 199 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), estimate_wind(), use_compass(), and wind_estimate().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS_DCM.h
libraries/AP_AHRS/AP_AHRS_DCM.cpp