APM:Libraries: AP_Compass_HIL Class Reference
AP_Compass_HIL Class Reference
#include <AP_Compass_HIL.h>
Public Member Functions
AP_Compass_HIL (Compass &compass)
void read (void)
bool init (void)
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend (Compass &compass)
virtual ~AP_Compass_Backend (void)
virtual void accumulate (void)
Static Public Member Functions
static AP_Compass_Backend * detect (Compass &compass)
Private Attributes
uint8_t _compass_instance [HIL_NUM_COMPASSES]
Additional Inherited Members
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_unfiltered_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void set_external (uint8_t instance, bool external)
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
Detailed Description
Definition at line 9 of file AP_Compass_HIL.h.
Constructor & Destructor Documentation
AP_Compass_HIL::AP_Compass_HIL (Compass & compass)
Definition at line 29 of file AP_Compass_HIL.cpp.
Referenced by detect().
Member Function Documentation
AP_Compass_Backend * AP_Compass_HIL::detect (Compass & compass) static
Definition at line 37 of file AP_Compass_HIL.cpp.
Referenced by Compass::_detect_backends().
bool AP_Compass_HIL::init (void) virtual
Implements AP_Compass_Backend.
Definition at line 51 of file AP_Compass_HIL.cpp.
Referenced by detect().
void AP_Compass_HIL::read (void) virtual
Implements AP_Compass_Backend.
Definition at line 60 of file AP_Compass_HIL.cpp.
Member Data Documentation
uint8_t AP_Compass_HIL::_compass_instance[HIL_NUM_COMPASSES] private
Definition at line 20 of file AP_Compass_HIL.h.
Referenced by AP_Compass_HIL(), init(), and read().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_HIL.h
libraries/AP_Compass/AP_Compass_HIL.cpp