APM:Libraries: DFMessageWriter Class Reference
DFMessageWriter Class Reference abstract
#include <DFMessageWriter.h>
Public Member Functions
DFMessageWriter (DataFlash_Class &DataFlash)
virtual void reset ()=0
virtual void process ()=0
virtual bool finished ()
Protected Attributes
bool _finished = false
DataFlash_Class & _DataFlash
Detailed Description
Definition at line 9 of file DFMessageWriter.h.
Constructor & Destructor Documentation
DFMessageWriter::DFMessageWriter (DataFlash_Class & DataFlash) inline
Definition at line 11 of file DFMessageWriter.h.
Member Function Documentation
virtual bool DFMessageWriter::finished () inline virtual
Definition at line 16 of file DFMessageWriter.h.
Referenced by DFMessageWriter_DFLogStart::process(), and DataFlash_Backend::WriteMoreStartupMessages().
virtual void DFMessageWriter::process () pure virtual
Implemented in DFMessageWriter_DFLogStart, DFMessageWriter_WriteEntireMission, and DFMessageWriter_WriteSysInfo.
void DFMessageWriter::reset () pure virtual
Implemented in DFMessageWriter_DFLogStart, DFMessageWriter_WriteEntireMission, and DFMessageWriter_WriteSysInfo.
Definition at line 11 of file DFMessageWriter.cpp.
Referenced by DFMessageWriter_WriteSysInfo::reset(), DFMessageWriter_WriteEntireMission::reset(), and DFMessageWriter_DFLogStart::reset().
Member Data Documentation
DataFlash_Class& DFMessageWriter::_DataFlash protected
Definition at line 20 of file DFMessageWriter.h.
Referenced by DFMessageWriter_WriteSysInfo::process(), DFMessageWriter_WriteEntireMission::process(), and DFMessageWriter_DFLogStart::process().
bool DFMessageWriter::_finished = false protected
Definition at line 19 of file DFMessageWriter.h.
Referenced by finished(), DFMessageWriter_WriteSysInfo::process(), DFMessageWriter_WriteEntireMission::process(), DFMessageWriter_DFLogStart::process(), and reset().
The documentation for this class was generated from the following files:
libraries/DataFlash/DFMessageWriter.h
libraries/DataFlash/DFMessageWriter.cpp