APM:Libraries: RC_Channel_aux Class Reference
RC_Channel_aux Class Reference
Object managing one aux. RC channel (CH5-8), with information about its function.
#include <RC_Channel_aux.h>
Public Types
enum Aux_servo_function_t {
k_none = 0, k_manual = 1, k_flap = 2, k_flap_auto = 3,
k_aileron = 4, k_unused1 = 5, k_mount_pan = 6, k_mount_tilt = 7,
k_mount_roll = 8, k_mount_open = 9, k_cam_trigger = 10, k_egg_drop = 11,
k_mount2_pan = 12, k_mount2_tilt = 13, k_mount2_roll = 14, k_mount2_open = 15,
k_dspoiler1 = 16, k_dspoiler2 = 17, k_aileron_with_input = 18, k_elevator = 19,
k_elevator_with_input = 20, k_rudder = 21, k_sprayer_pump = 22, k_sprayer_spinner = 23,
k_flaperon1 = 24, k_flaperon2 = 25, k_steering = 26, k_parachute_release = 27,
k_epm = 28, k_landing_gear_control = 29, k_engine_run_enable = 30, k_nr_aux_servo_functions
}
Public Types inherited from RC_Channel
enum LimitValue { RC_CHANNEL_LIMIT_TRIM, RC_CHANNEL_LIMIT_MIN, RC_CHANNEL_LIMIT_MAX }
Public Member Functions
RC_Channel_aux (uint8_t ch_out)
void output_ch (void)
map a function to a servo channel and output it
Public Member Functions inherited from RC_Channel
RC_Channel (uint8_t ch_out)
void update_min_max ()
void zero_min_max ()
void load_eeprom (void)
void save_eeprom (void)
void save_trim (void)
void set_type (uint8_t t)
void set_range (int16_t low, int16_t high)
void set_range_out (int16_t low, int16_t high)
void set_angle (int16_t angle)
void set_reverse (bool reverse)
bool get_reverse (void) const
void set_default_dead_zone (int16_t dzone)
uint8_t get_ch_out (void) const
int16_t get_control_mid () const
void set_pwm (int16_t pwm)
void set_pwm_no_deadzone (int16_t pwm)
uint16_t get_limit_pwm (LimitValue limit) const
void trim ()
int16_t control_mix (float value)
void calc_pwm (void)
int16_t pwm_to_angle_dz (uint16_t dead_zone)
int16_t pwm_to_angle ()
float norm_input ()
float norm_input_dz ()
uint8_t percent_input ()
float norm_output ()
int16_t angle_to_pwm ()
int16_t pwm_to_range ()
int16_t pwm_to_range_dz (uint16_t dead_zone)
int16_t range_to_pwm ()
void output () const
void output_trim () const
uint16_t read () const
void input ()
void enable_out ()
void disable_out ()
bool in_trim_dz ()
Static Public Member Functions
static void output_ch_all (void)
static void set_radio (Aux_servo_function_t function, int16_t value)
static void set_radio_trimmed (Aux_servo_function_t function, int16_t value)
static void set_radio_trim (Aux_servo_function_t function)
static void set_radio_to_min (Aux_servo_function_t function)
static void set_radio_to_max (Aux_servo_function_t function)
static void set_radio_to_trim (Aux_servo_function_t function)
static void copy_radio_in_out (Aux_servo_function_t function, bool do_input_output=false)
static void set_servo_out (Aux_servo_function_t function, int16_t value)
static void set_servo_failsafe (Aux_servo_function_t function, RC_Channel::LimitValue limit)
static void set_servo_limit (Aux_servo_function_t function, RC_Channel::LimitValue limit)
static bool function_assigned (Aux_servo_function_t function)
static void move_servo (Aux_servo_function_t function, int16_t value, int16_t angle_min, int16_t angle_max)
static void enable_aux_servos (void)
Should be called after the the servo functions have been initialized.
static void disable_aux_channel (uint8_t channel)
static Aux_servo_function_t channel_function (uint8_t channel)
static void update_aux_servo_function (void)
Static Public Member Functions inherited from RC_Channel
static void set_pwm_all (void)
static void output_trim_all ()
static void setup_failsafe_trim_all ()
static RC_Channel * rc_channel (uint8_t i)
Public Attributes
AP_Int8 function
see Aux_servo_function_t enum
Public Attributes inherited from RC_Channel
int16_t radio_in
int16_t control_in
int16_t servo_out
int16_t pwm_out
int16_t radio_out
AP_Int16 radio_min
AP_Int16 radio_trim
AP_Int16 radio_max
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Static Public Attributes inherited from RC_Channel
static const struct AP_Param::GroupInfo var_info []
Static Private Attributes
static uint32_t _function_mask
static RC_Channel_aux * _aux_channels [RC_AUX_MAX_CHANNELS]
Additional Inherited Members
Protected Attributes inherited from RC_Channel
uint8_t _ch_out
Detailed Description
Object managing one aux. RC channel (CH5-8), with information about its function.
Definition at line 17 of file RC_Channel_aux.h.
Member Enumeration Documentation
enum RC_Channel_aux::Aux_servo_function_t
Enumerator
k_none
disabled
k_manual
manual, just pass-thru the RC in signal
k_flap
flap
k_flap_auto
flap automated
k_aileron
aileron
k_unused1
unused function
k_mount_pan
mount yaw (pan)
k_mount_tilt
mount pitch (tilt)
k_mount_roll
mount roll
k_mount_open
mount open (deploy) / close (retract)
k_cam_trigger
camera trigger
k_egg_drop
egg drop
k_mount2_pan
mount2 yaw (pan)
k_mount2_tilt
mount2 pitch (tilt)
k_mount2_roll
mount2 roll
k_mount2_open
mount2 open (deploy) / close (retract)
k_dspoiler1
differential spoiler 1 (left wing)
k_dspoiler2
differential spoiler 2 (right wing)
k_aileron_with_input
aileron, with rc input
k_elevator
elevator
k_elevator_with_input
elevator, with rc input
k_rudder
secondary rudder channel
k_sprayer_pump
crop sprayer pump channel
k_sprayer_spinner
crop sprayer spinner channel
k_flaperon1
flaperon, left wing
k_flaperon2
flaperon, right wing
k_steering
ground steering, used to separate from rudder
k_parachute_release
parachute release
k_epm
epm gripper
k_landing_gear_control
landing gear controller
k_engine_run_enable
engine kill switch, used for gas airplanes and helicopters
k_nr_aux_servo_functions
This must be the last enum value (only add new values before this one)
Definition at line 36 of file RC_Channel_aux.h.
Constructor & Destructor Documentation
RC_Channel_aux::RC_Channel_aux (uint8_t ch_out) inline
Constructor
Parameters
key EEPROM storage key for the channel trim parameters.
name Optional name for the group.
Definition at line 24 of file RC_Channel_aux.h.
Member Function Documentation
RC_Channel_aux::Aux_servo_function_t RC_Channel_aux::channel_function (uint8_t channel) static
Definition at line 71 of file RC_Channel_aux.cpp.
void RC_Channel_aux::copy_radio_in_out (RC_Channel_aux::Aux_servo_function_t function, bool do_input_output = false) static
Definition at line 258 of file RC_Channel_aux.cpp.
void RC_Channel_aux::disable_aux_channel (uint8_t channel) static
Definition at line 59 of file RC_Channel_aux.cpp.
Referenced by AP_MotorsMatrix::add_motor_raw(), AP_MotorsHeli_Single::enable(), AP_MotorsTri::Init(), and AP_MotorsSingle::Init().
void RC_Channel_aux::enable_aux_servos (void) static
Should be called after the the servo functions have been initialized.
Definition at line 130 of file RC_Channel_aux.cpp.
bool RC_Channel_aux::function_assigned (RC_Channel_aux::Aux_servo_function_t function) static
Definition at line 339 of file RC_Channel_aux.cpp.
Referenced by AP_Mount_Servo::check_servo_map(), copy_radio_in_out(), AP_Mount::init(), move_servo(), set_radio(), set_radio_to_max(), set_radio_to_min(), set_radio_to_trim(), set_radio_trim(), set_radio_trimmed(), set_servo_failsafe(), set_servo_limit(), set_servo_out(), and AC_Sprayer::update().
void RC_Channel_aux::move_servo (RC_Channel_aux::Aux_servo_function_t function, int16_t value, int16_t angle_min, int16_t angle_max) static
Definition at line 352 of file RC_Channel_aux.cpp.
Referenced by AP_Mount_Servo::move_servo(), and AC_Sprayer::update().
void RC_Channel_aux::output_ch (void)
map a function to a servo channel and output it
Definition at line 27 of file RC_Channel_aux.cpp.
Referenced by output_ch_all().
void RC_Channel_aux::output_ch_all (void) static
Definition at line 45 of file RC_Channel_aux.cpp.
void RC_Channel_aux::set_radio (RC_Channel_aux::Aux_servo_function_t function, int16_t value) static
Definition at line 152 of file RC_Channel_aux.cpp.
Referenced by AP_LandingGear::deploy(), AP_EPM::grab(), AP_EPM::neutral(), AP_EPM::release(), AP_LandingGear::retract(), AP_Camera::servo_pic(), AP_Camera::trigger_pic_cleanup(), AP_Parachute::update(), and AC_Sprayer::update().
void RC_Channel_aux::set_radio_to_max (RC_Channel_aux::Aux_servo_function_t function) static
Definition at line 224 of file RC_Channel_aux.cpp.
Referenced by AP_MotorsHeli_Single::update_motor_control().
void RC_Channel_aux::set_radio_to_min (RC_Channel_aux::Aux_servo_function_t function) static
Definition at line 207 of file RC_Channel_aux.cpp.
Referenced by AC_Sprayer::enable(), AC_Sprayer::update(), and AP_MotorsHeli_Single::update_motor_control().
void RC_Channel_aux::set_radio_to_trim (RC_Channel_aux::Aux_servo_function_t function) static
Definition at line 241 of file RC_Channel_aux.cpp.
void RC_Channel_aux::set_radio_trim (RC_Channel_aux::Aux_servo_function_t function) static
Definition at line 188 of file RC_Channel_aux.cpp.
void RC_Channel_aux::set_radio_trimmed (RC_Channel_aux::Aux_servo_function_t function, int16_t value) static
Definition at line 169 of file RC_Channel_aux.cpp.
void RC_Channel_aux::set_servo_failsafe (RC_Channel_aux::Aux_servo_function_t function, RC_Channel::LimitValue limit) static
Definition at line 298 of file RC_Channel_aux.cpp.
Referenced by APM_OBC::setup_failsafe().
void RC_Channel_aux::set_servo_limit (RC_Channel_aux::Aux_servo_function_t function, RC_Channel::LimitValue limit) static
Definition at line 316 of file RC_Channel_aux.cpp.
Referenced by APM_OBC::check_crash_plane().
void RC_Channel_aux::set_servo_out (RC_Channel_aux::Aux_servo_function_t function, int16_t value) static
Definition at line 280 of file RC_Channel_aux.cpp.
void RC_Channel_aux::update_aux_servo_function (void) static
Update the _aux_channels array of pointers to rc_x channels This is to be done before rc_init so that the channels get correctly initialized. It also should be called periodically because the user might change the configuration and expects the changes to take effect instantly Supports up to eight aux servo outputs (typically CH5 ... CH11) All servos must be configured with a single call to this function (do not call this twice with different parameters, the second call will reset the effect of the first call)
Definition at line 88 of file RC_Channel_aux.cpp.
Referenced by enable_aux_servos().
Member Data Documentation
RC_Channel_aux * RC_Channel_aux::_aux_channels static private
Definition at line 133 of file RC_Channel_aux.h.
Referenced by channel_function(), copy_radio_in_out(), disable_aux_channel(), enable_aux_servos(), move_servo(), output_ch_all(), RC_Channel_aux(), set_radio(), set_radio_to_max(), set_radio_to_min(), set_radio_to_trim(), set_radio_trim(), set_radio_trimmed(), set_servo_failsafe(), set_servo_limit(), set_servo_out(), and update_aux_servo_function().
uint32_t RC_Channel_aux::_function_mask static private
Definition at line 132 of file RC_Channel_aux.h.
Referenced by function_assigned(), and update_aux_servo_function().
AP_Int8 RC_Channel_aux::function
see Aux_servo_function_t enum
Definition at line 72 of file RC_Channel_aux.h.
Referenced by channel_function(), set_servo_failsafe(), and set_servo_limit().
const AP_Param::GroupInfo RC_Channel_aux::var_info static
Initial value:
= {
    AP_NESTEDGROUPINFO(RC_Channel, 0),
    AP_GROUPINFO("FUNCTION",       1, RC_Channel_aux, function, 0),
    AP_GROUPEND
}
Definition at line 117 of file RC_Channel_aux.h.
Referenced by RC_Channel_aux().
The documentation for this class was generated from the following files:
libraries/RC_Channel/RC_Channel_aux.h
libraries/RC_Channel/RC_Channel_aux.cpp