APM:Libraries: AP_Airspeed_PX4 Class Reference
AP_Airspeed_PX4 Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_Airspeed_PX4.h>
Public Member Functions
AP_Airspeed_PX4 ()
bool init (void)
bool get_differential_pressure (float &pressure)
bool get_temperature (float &temperature)
Private Attributes
int _fd
uint64_t _last_timestamp
float _temperature
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 28 of file AP_Airspeed_PX4.h.
Constructor & Destructor Documentation
AP_Airspeed_PX4::AP_Airspeed_PX4 () inline
Definition at line 31 of file AP_Airspeed_PX4.h.
Member Function Documentation
bool AP_Airspeed_PX4::get_differential_pressure (float & pressure) virtual
Implements AP_Airspeed_Backend.
Definition at line 49 of file AP_Airspeed_PX4.cpp.
Referenced by AP_Airspeed::get_pressure().
bool AP_Airspeed_PX4::get_temperature (float & temperature) virtual
Implements AP_Airspeed_Backend.
Definition at line 77 of file AP_Airspeed_PX4.cpp.
Referenced by AP_Airspeed::get_temperature().
bool AP_Airspeed_PX4::init (void) virtual
Implements AP_Airspeed_Backend.
Definition at line 35 of file AP_Airspeed_PX4.cpp.
Referenced by AP_Airspeed::init().
Member Data Documentation
int AP_Airspeed_PX4::_fd private
Definition at line 43 of file AP_Airspeed_PX4.h.
Referenced by get_differential_pressure(), and init().
uint64_t AP_Airspeed_PX4::_last_timestamp private
Definition at line 44 of file AP_Airspeed_PX4.h.
Referenced by get_differential_pressure().
float AP_Airspeed_PX4::_temperature private
Definition at line 45 of file AP_Airspeed_PX4.h.
Referenced by get_differential_pressure(), and get_temperature().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed_PX4.h
libraries/AP_Airspeed/AP_Airspeed_PX4.cpp