APM:Libraries: AP_GPS Class Reference
AP_GPS Class Reference
#include <AP_GPS.h>
Classes
struct detect_state
struct GPS_State
struct GPS_timing
Public Types
enum GPS_Type {
GPS_TYPE_NONE = 0, GPS_TYPE_AUTO = 1, GPS_TYPE_UBLOX = 2, GPS_TYPE_MTK = 3,
GPS_TYPE_MTK19 = 4, GPS_TYPE_NMEA = 5, GPS_TYPE_SIRF = 6, GPS_TYPE_HIL = 7,
GPS_TYPE_SBP = 8, GPS_TYPE_PX4 = 9, GPS_TYPE_SBF = 10, GPS_TYPE_GSOF = 11
}
enum GPS_Status {
NO_GPS = 0, NO_FIX = 1, GPS_OK_FIX_2D = 2, GPS_OK_FIX_3D = 3,
GPS_OK_FIX_3D_DGPS = 4, GPS_OK_FIX_3D_RTK = 5
}
GPS status codes.
enum GPS_Engine_Setting {
GPS_ENGINE_NONE = -1, GPS_ENGINE_PORTABLE = 0, GPS_ENGINE_STATIONARY = 2, GPS_ENGINE_PEDESTRIAN = 3,
GPS_ENGINE_AUTOMOTIVE = 4, GPS_ENGINE_SEA = 5, GPS_ENGINE_AIRBORNE_1G = 6, GPS_ENGINE_AIRBORNE_2G = 7,
GPS_ENGINE_AIRBORNE_4G = 8
}
Public Member Functions
AP_GPS ()
void init (DataFlash_Class *dataflash, const AP_SerialManager &serial_manager)
Startup initialisation.
void update (void)
uint8_t num_sensors (void) const
uint8_t primary_sensor (void) const
GPS_Status status (uint8_t instance) const
Query GPS status.
GPS_Status status (void) const
GPS_Status highest_supported_status (uint8_t instance) const
GPS_Status highest_supported_status (void) const
const Location & location (uint8_t instance) const
const Location & location () const
bool speed_accuracy (uint8_t instance, float &sacc) const
bool speed_accuracy (float &sacc) const
bool horizontal_accuracy (uint8_t instance, float &hacc) const
bool horizontal_accuracy (float &hacc) const
bool vertical_accuracy (uint8_t instance, float &vacc) const
bool vertical_accuracy (float &vacc) const
const Vector3f & velocity (uint8_t instance) const
const Vector3f & velocity () const
float ground_speed (uint8_t instance) const
float ground_speed () const
uint32_t ground_speed_cm (void)
int32_t ground_course_cd (uint8_t instance) const
int32_t ground_course_cd () const
uint8_t num_sats (uint8_t instance) const
uint8_t num_sats () const
uint32_t time_week_ms (uint8_t instance) const
uint32_t time_week_ms () const
uint16_t time_week (uint8_t instance) const
uint16_t time_week () const
uint16_t get_hdop (uint8_t instance) const
uint16_t get_hdop () const
uint16_t get_vdop (uint8_t instance) const
uint16_t get_vdop () const
uint32_t last_fix_time_ms (uint8_t instance) const
uint32_t last_fix_time_ms (void) const
uint32_t last_message_time_ms (uint8_t instance) const
uint32_t last_message_time_ms (void) const
uint64_t time_epoch_usec (uint8_t instance)
uint64_t time_epoch_usec (void)
bool have_vertical_velocity (uint8_t instance) const
bool have_vertical_velocity (void) const
float get_lag () const
void setHIL (uint8_t instance, GPS_Status status, uint64_t time_epoch_ms, const Location &location, const Vector3f &velocity, uint8_t num_sats, uint16_t hdop, bool _have_vertical_velocity)
void send_blob_start (uint8_t instance, const char *_blob, uint16_t size)
void send_blob_update (uint8_t instance)
void lock_port (uint8_t instance, bool locked)
void inject_data (uint8_t *data, uint8_t len)
void inject_data (uint8_t instance, uint8_t *data, uint8_t len)
void send_mavlink_gps_raw (mavlink_channel_t chan)
void send_mavlink_gps2_raw (mavlink_channel_t chan)
void send_mavlink_gps_rtk (mavlink_channel_t chan)
void send_mavlink_gps2_rtk (mavlink_channel_t chan)
Public Attributes
DataFlash_Class * _DataFlash
AP_Int8 _type [GPS_MAX_INSTANCES]
AP_Int8 _navfilter
AP_Int8 _auto_switch
AP_Int8 _min_dgps
AP_Int16 _sbp_logmask
AP_Int8 _inject_to
uint32_t _last_instance_swap_ms
AP_Int8 _sbas_mode
AP_Int8 _min_elevation
AP_Int8 _raw_data
AP_Int8 _gnss_mode
AP_Int8 _save_config
const char * blob
uint16_t remaining
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void detect_instance (uint8_t instance)
void update_instance (uint8_t instance)
Private Attributes
GPS_timing timing [GPS_MAX_INSTANCES]
GPS_State state [GPS_MAX_INSTANCES]
AP_GPS_Backend * drivers [GPS_MAX_INSTANCES]
AP_HAL::UARTDriver * _port [GPS_MAX_INSTANCES]
uint8_t primary_instance:2
primary GPS instance
uint8_t num_instances:2
number of GPS instances present
uint8_t locked_ports:2
struct AP_GPS::detect_state detect_state [GPS_MAX_INSTANCES]
struct {
const char * blob
uint16_t remaining
} initblob_state [GPS_MAX_INSTANCES]
Static Private Attributes
static const uint32_t _baudrates [] = {4800U, 38400U, 115200U, 57600U, 9600U, 230400U}
static const char _initialisation_blob [] = UBLOX_SET_BINARY MTK_SET_BINARY SIRF_SET_BINARY
static const char _initialisation_raw_blob [] = UBLOX_SET_BINARY_RAW_BAUD MTK_SET_BINARY SIRF_SET_BINARY
Detailed Description
GPS driver main class
Definition at line 42 of file AP_GPS.h.
Member Enumeration Documentation
enum AP_GPS::GPS_Engine_Setting
Enumerator
GPS_ENGINE_NONE
GPS_ENGINE_PORTABLE
GPS_ENGINE_STATIONARY
GPS_ENGINE_PEDESTRIAN
GPS_ENGINE_AUTOMOTIVE
GPS_ENGINE_SEA
GPS_ENGINE_AIRBORNE_1G
GPS_ENGINE_AIRBORNE_2G
GPS_ENGINE_AIRBORNE_4G
Definition at line 86 of file AP_GPS.h.
enum AP_GPS::GPS_Status
GPS status codes.
Enumerator
NO_GPS
No GPS connected/detected.
NO_FIX
Receiving valid GPS messages but no lock.
GPS_OK_FIX_2D
Receiving valid messages and 2D lock.
GPS_OK_FIX_3D
Receiving valid messages and 3D lock.
GPS_OK_FIX_3D_DGPS
Receiving valid messages and 3D lock with differential improvements.
GPS_OK_FIX_3D_RTK
Receiving valid messages and 3D lock, with relative-positioning improvements.
Definition at line 75 of file AP_GPS.h.
enum AP_GPS::GPS_Type
Enumerator
GPS_TYPE_NONE
GPS_TYPE_AUTO
GPS_TYPE_UBLOX
GPS_TYPE_MTK
GPS_TYPE_MTK19
GPS_TYPE_NMEA
GPS_TYPE_SIRF
GPS_TYPE_HIL
GPS_TYPE_SBP
GPS_TYPE_PX4
GPS_TYPE_SBF
GPS_TYPE_GSOF
Definition at line 59 of file AP_GPS.h.
Constructor & Destructor Documentation
AP_GPS::AP_GPS () inline
Definition at line 46 of file AP_GPS.h.
Member Function Documentation
void AP_GPS::detect_instance (uint8_t instance) private
Definition at line 183 of file AP_GPS.cpp.
Referenced by update_instance().
uint16_t AP_GPS::get_hdop (uint8_t instance) const inline
Definition at line 248 of file AP_GPS.h.
Referenced by NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), and DataFlash_Class::Log_Write_GPS().
uint16_t AP_GPS::get_hdop () const inline
Definition at line 251 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
float AP_GPS::get_lag () const inline
Definition at line 296 of file AP_GPS.h.
Referenced by AP_AHRS_DCM::get_position().
uint16_t AP_GPS::get_vdop (uint8_t instance) const inline
Definition at line 256 of file AP_GPS.h.
Referenced by DataFlash_Class::Log_Write_GPS().
uint16_t AP_GPS::get_vdop () const inline
Definition at line 259 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
int32_t AP_GPS::ground_course_cd (uint8_t instance) const inline
Definition at line 216 of file AP_GPS.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::get_position(), AP_AHRS::groundspeed_vector(), DataFlash_Class::Log_Write_GPS(), loop(), and AP_AHRS_DCM::use_compass().
int32_t AP_GPS::ground_course_cd () const inline
Definition at line 219 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
float AP_GPS::ground_speed (uint8_t instance) const inline
Definition at line 203 of file AP_GPS.h.
Referenced by AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), AP_Frsky_Telem::calc_gps_position(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::get_position(), AP_AHRS::groundspeed(), AP_AHRS::groundspeed_vector(), DataFlash_Class::Log_Write_GPS(), loop(), and AP_AHRS_DCM::use_compass().
float AP_GPS::ground_speed () const inline
Definition at line 206 of file AP_GPS.h.
Referenced by ground_speed_cm(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
uint32_t AP_GPS::ground_speed_cm (void) inline
Definition at line 211 of file AP_GPS.h.
bool AP_GPS::have_vertical_velocity (uint8_t instance) const inline
Definition at line 288 of file AP_GPS.h.
Referenced by NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF_core::readGpsData(), and NavEKF2_core::readGpsData().
bool AP_GPS::have_vertical_velocity (void) const inline
Definition at line 291 of file AP_GPS.h.
AP_GPS::GPS_Status AP_GPS::highest_supported_status (uint8_t instance) const
Definition at line 302 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::send_gps_raw().
AP_GPS::GPS_Status AP_GPS::highest_supported_status (void) const
Definition at line 310 of file AP_GPS.cpp.
Referenced by send_mavlink_gps2_rtk(), and send_mavlink_gps_rtk().
bool AP_GPS::horizontal_accuracy (uint8_t instance, float & hacc) const inline
Definition at line 170 of file AP_GPS.h.
Referenced by NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), horizontal_accuracy(), and DataFlash_Class::Log_Write_GPS().
bool AP_GPS::horizontal_accuracy (float & hacc) const inline
Definition at line 178 of file AP_GPS.h.
void AP_GPS::init (DataFlash_Class * dataflash, const AP_SerialManager & serial_manager)
Startup initialisation.
Definition at line 122 of file AP_GPS.cpp.
Referenced by setup().
void AP_GPS::inject_data (uint8_t * data, uint8_t len)
Definition at line 479 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::handle_gps_inject().
void AP_GPS::inject_data (uint8_t instance, uint8_t * data, uint8_t len)
Definition at line 492 of file AP_GPS.cpp.
uint32_t AP_GPS::last_fix_time_ms (uint8_t instance) const inline
Definition at line 265 of file AP_GPS.h.
Referenced by APM_OBC::check(), AP_AHRS_DCM::drift_correction(), and AP_AHRS_DCM::drift_correction_yaw().
uint32_t AP_GPS::last_fix_time_ms (void) const inline
Definition at line 268 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
uint32_t AP_GPS::last_message_time_ms (uint8_t instance) const inline
Definition at line 274 of file AP_GPS.h.
Referenced by loop(), NavEKF_core::readGpsData(), and NavEKF2_core::readGpsData().
uint32_t AP_GPS::last_message_time_ms (void) const inline
Definition at line 277 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), send_mavlink_gps_raw(), and update_instance().
const Location& AP_GPS::location (uint8_t instance) const inline
Definition at line 151 of file AP_GPS.h.
Referenced by AP_Frsky_Telem::calc_gps_position(), NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), APM_OBC::check_altlimit(), AP_AHRS_DCM::drift_correction(), NavEKF2_core::getLLH(), NavEKF_core::getLLH(), NavEKF2_core::getPosNED(), NavEKF_core::getPosNED(), DataFlash_Class::Log_Write_GPS(), loop(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), NavEKF_core::setOrigin(), and NavEKF2_core::setOrigin().
const Location& AP_GPS::location () const inline
Definition at line 154 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
void AP_GPS::lock_port (uint8_t instance, bool lock)
Lock a GPS port, prevening the GPS driver from using it. This can be used to allow a user to control a GPS port via the SERIAL_CONTROL protocol
Definition at line 464 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::handle_serial_control().
uint8_t AP_GPS::num_sats (uint8_t instance) const inline
Definition at line 224 of file AP_GPS.h.
Referenced by AP_Frsky_Telem::calc_gps_sats(), NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), AP_AHRS_DCM::drift_correction(), DataFlash_Class::Log_Write_GPS(), loop(), NavEKF_core::readGpsData(), and NavEKF2_core::readGpsData().
uint8_t AP_GPS::num_sats () const inline
Definition at line 227 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
uint8_t AP_GPS::num_sensors (void) const inline
Definition at line 130 of file AP_GPS.h.
Referenced by GCS_MAVLINK::send_gps_raw(), and send_mavlink_gps2_raw().
uint8_t AP_GPS::primary_sensor (void) const inline
Definition at line 134 of file AP_GPS.h.
Referenced by DataFlash_Class::Log_Write_GPS().
void AP_GPS::send_blob_start (uint8_t instance, const char * _blob, uint16_t size)
Definition at line 145 of file AP_GPS.cpp.
Referenced by AP_GPS_MTK::AP_GPS_MTK(), AP_GPS_NMEA::AP_GPS_NMEA(), AP_GPS_SIRF::AP_GPS_SIRF(), AP_GPS_UBLOX::AP_GPS_UBLOX(), detect_instance(), and AP_GPS_MTK::send_init_blob().
void AP_GPS::send_blob_update (uint8_t instance)
Definition at line 155 of file AP_GPS.cpp.
Referenced by detect_instance(), and update_instance().
void AP_GPS::send_mavlink_gps2_raw (mavlink_channel_t chan)
Definition at line 532 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::send_gps_raw().
void AP_GPS::send_mavlink_gps2_rtk (mavlink_channel_t chan)
Definition at line 570 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::send_gps_raw().
void AP_GPS::send_mavlink_gps_raw (mavlink_channel_t chan)
Definition at line 499 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::send_gps_raw().
void AP_GPS::send_mavlink_gps_rtk (mavlink_channel_t chan)
Definition at line 562 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::send_gps_raw().
void AP_GPS::setHIL (uint8_t instance, GPS_Status status, uint64_t time_epoch_ms, const Location & location, const Vector3f & velocity, uint8_t num_sats, uint16_t hdop, bool _have_vertical_velocity)
Definition at line 431 of file AP_GPS.cpp.
bool AP_GPS::speed_accuracy (uint8_t instance, float & sacc) const inline
Definition at line 158 of file AP_GPS.h.
Referenced by NavEKF_core::calcGpsGoodForFlight(), NavEKF2_core::calcGpsGoodForFlight(), DataFlash_Class::Log_Write_GPS(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), and speed_accuracy().
bool AP_GPS::speed_accuracy (float & sacc) const inline
Definition at line 166 of file AP_GPS.h.
GPS_Status AP_GPS::status (uint8_t instance) const inline
Query GPS status.
Definition at line 139 of file AP_GPS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), AP_Frsky_Telem::calc_gps_position(), AP_Frsky_Telem::calc_gps_sats(), APM_OBC::check_altlimit(), AP_AHRS_DCM::drift_correction(), NavEKF2_core::getLLH(), NavEKF_core::getLLH(), NavEKF2_core::getPosNED(), NavEKF_core::getPosNED(), AP_Arming::gps_checks(), AP_AHRS::groundspeed(), AP_AHRS::groundspeed_vector(), AP_AHRS_DCM::have_gps(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF_core::InitialiseFilterBootstrap(), NavEKF_core::InitialiseFilterDynamic(), DataFlash_Class::Log_Write_GPS(), loop(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), and GCS_MAVLINK::send_gps_raw().
GPS_Status AP_GPS::status (void) const inline
Definition at line 142 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), send_mavlink_gps_raw(), update(), and update_instance().
uint64_t AP_GPS::time_epoch_usec (uint8_t instance)
calculate current time since the unix epoch in microseconds
Definition at line 64 of file GPS_Backend.cpp.
Referenced by AP_Camera::send_feedback(), and GCS_MAVLINK::send_system_time().
uint64_t AP_GPS::time_epoch_usec (void) inline
Definition at line 283 of file AP_GPS.h.
uint16_t AP_GPS::time_week (uint8_t instance) const inline
Definition at line 240 of file AP_GPS.h.
Referenced by DataFlash_Class::Log_Write_Camera(), DataFlash_Class::Log_Write_GPS(), and loop().
uint16_t AP_GPS::time_week () const inline
Definition at line 243 of file AP_GPS.h.
uint32_t AP_GPS::time_week_ms (uint8_t instance) const inline
Definition at line 232 of file AP_GPS.h.
Referenced by DataFlash_Class::Log_Write_Camera(), DataFlash_Class::Log_Write_GPS(), and loop().
uint32_t AP_GPS::time_week_ms () const inline
Definition at line 235 of file AP_GPS.h.
void AP_GPS::update (void)
Update GPS state based on possible bytes received from the module. This routine must be called periodically (typically at 10Hz or more) to process incoming data.
Definition at line 379 of file AP_GPS.cpp.
Referenced by loop().
void AP_GPS::update_instance (uint8_t instance) private
Definition at line 322 of file AP_GPS.cpp.
Referenced by update().
const Vector3f& AP_GPS::velocity (uint8_t instance) const inline
Definition at line 195 of file AP_GPS.h.
Referenced by AP_AHRS_DCM::drift_correction(), DataFlash_Class::Log_Write_GPS(), NavEKF_core::readGpsData(), and NavEKF2_core::readGpsData().
const Vector3f& AP_GPS::velocity () const inline
Definition at line 198 of file AP_GPS.h.
bool AP_GPS::vertical_accuracy (uint8_t instance, float & vacc) const inline
Definition at line 182 of file AP_GPS.h.
Referenced by DataFlash_Class::Log_Write_GPS(), and vertical_accuracy().
bool AP_GPS::vertical_accuracy (float & vacc) const inline
Definition at line 190 of file AP_GPS.h.
Member Data Documentation
AP_Int8 AP_GPS::_auto_switch
Definition at line 311 of file AP_GPS.h.
Referenced by update().
const uint32_t AP_GPS::_baudrates = {4800U, 38400U, 115200U, 57600U, 9600U, 230400U} static private
Definition at line 380 of file AP_GPS.h.
Referenced by detect_instance().
DataFlash_Class* AP_GPS::_DataFlash
Definition at line 306 of file AP_GPS.h.
Referenced by init(), AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), and AP_GPS_SBP::logging_write_headers().
AP_Int8 AP_GPS::_gnss_mode
Definition at line 319 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
const char AP_GPS::_initialisation_blob = UBLOX_SET_BINARY MTK_SET_BINARY SIRF_SET_BINARY static private
Definition at line 381 of file AP_GPS.h.
Referenced by detect_instance().
const char AP_GPS::_initialisation_raw_blob = UBLOX_SET_BINARY_RAW_BAUD MTK_SET_BINARY SIRF_SET_BINARY static private
Definition at line 382 of file AP_GPS.h.
Referenced by detect_instance().
AP_Int8 AP_GPS::_inject_to
Definition at line 314 of file AP_GPS.h.
Referenced by inject_data().
uint32_t AP_GPS::_last_instance_swap_ms
Definition at line 315 of file AP_GPS.h.
Referenced by init(), and update().
AP_Int8 AP_GPS::_min_dgps
Definition at line 312 of file AP_GPS.h.
AP_Int8 AP_GPS::_min_elevation
Definition at line 317 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
AP_Int8 AP_GPS::_navfilter
Definition at line 310 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
AP_HAL::UARTDriver* AP_GPS::_port[GPS_MAX_INSTANCES] private
Definition at line 351 of file AP_GPS.h.
Referenced by detect_instance(), init(), and send_blob_update().
AP_Int8 AP_GPS::_raw_data
Definition at line 318 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), detect_instance(), and AP_GPS_UBLOX::send_next_rate_update().
AP_Int8 AP_GPS::_save_config
Definition at line 320 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::read().
AP_Int8 AP_GPS::_sbas_mode
Definition at line 316 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
AP_Int16 AP_GPS::_sbp_logmask
Definition at line 313 of file AP_GPS.h.
Referenced by AP_GPS_SBP::logging_log_raw_sbp().
AP_Int8 AP_GPS::_type[GPS_MAX_INSTANCES]
Definition at line 309 of file AP_GPS.h.
Referenced by detect_instance(), setHIL(), and update_instance().
const char* AP_GPS::blob
Definition at line 376 of file AP_GPS.h.
Referenced by send_blob_update().
struct AP_GPS::detect_state AP_GPS::detect_state[GPS_MAX_INSTANCES] private
AP_GPS_Backend* AP_GPS::drivers[GPS_MAX_INSTANCES] private
Definition at line 350 of file AP_GPS.h.
Referenced by detect_instance(), highest_supported_status(), inject_data(), send_mavlink_gps2_rtk(), send_mavlink_gps_rtk(), and update_instance().
struct { ... } AP_GPS::initblob_state[GPS_MAX_INSTANCES]
Referenced by detect_instance(), send_blob_start(), and send_blob_update().
uint8_t AP_GPS::locked_ports private
Definition at line 360 of file AP_GPS.h.
Referenced by lock_port(), and update_instance().
uint8_t AP_GPS::num_instances private
number of GPS instances present
Definition at line 357 of file AP_GPS.h.
Referenced by num_sensors(), and update().
uint8_t AP_GPS::primary_instance private
primary GPS instance
Definition at line 354 of file AP_GPS.h.
Referenced by get_hdop(), get_vdop(), ground_course_cd(), ground_speed(), have_vertical_velocity(), highest_supported_status(), horizontal_accuracy(), init(), last_fix_time_ms(), last_message_time_ms(), location(), num_sats(), primary_sensor(), speed_accuracy(), status(), time_epoch_usec(), time_week(), time_week_ms(), update(), velocity(), and vertical_accuracy().
uint16_t AP_GPS::remaining
Definition at line 377 of file AP_GPS.h.
Referenced by detect_instance(), and send_blob_update().
GPS_State AP_GPS::state[GPS_MAX_INSTANCES] private
Definition at line 349 of file AP_GPS.h.
Referenced by detect_instance(), get_hdop(), get_vdop(), ground_course_cd(), ground_speed(), have_vertical_velocity(), horizontal_accuracy(), location(), num_sats(), setHIL(), speed_accuracy(), status(), time_epoch_usec(), time_week(), time_week_ms(), update(), update_instance(), velocity(), and vertical_accuracy().
GPS_timing AP_GPS::timing[GPS_MAX_INSTANCES] private
Definition at line 348 of file AP_GPS.h.
Referenced by detect_instance(), last_fix_time_ms(), last_message_time_ms(), setHIL(), and update_instance().
const AP_Param::GroupInfo AP_GPS::var_info static
Definition at line 303 of file AP_GPS.h.
Referenced by AP_GPS().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS.h
libraries/AP_GPS/AP_GPS.cpp
libraries/AP_GPS/GPS_Backend.cpp