APM:Libraries: AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver Class Reference
AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver Class Reference
#include <I2CDriver.h>
Public Member Functions
FLYMAPLEI2CDriver (AP_HAL::Semaphore *semaphore)
void begin ()
void end ()
void setTimeout (uint16_t ms)
void setHighSpeed (bool active)
uint8_t write (uint8_t addr, uint8_t len, uint8_t *data)
uint8_t writeRegister (uint8_t addr, uint8_t reg, uint8_t val)
uint8_t writeRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t *data)
uint8_t read (uint8_t addr, uint8_t len, uint8_t *data)
uint8_t readRegister (uint8_t addr, uint8_t reg, uint8_t *data)
uint8_t readRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t *data)
uint8_t lockup_count ()
AP_HAL::Semaphore * get_semaphore ()
Public Member Functions inherited from AP_HAL::I2CDriver
virtual uint8_t readRegistersMultiple (uint8_t addr, uint8_t reg, uint8_t len, uint8_t count, uint8_t *data)=0
void ignore_errors (bool b)
Private Member Functions
uint8_t _transfer (i2c_msg *msgs, uint16 num)
void _reset ()
Private Attributes
uint8_t _lockup_count
AP_HAL::Semaphore * _semaphore
uint16_t _timeout_ms
Additional Inherited Members
Protected Attributes inherited from AP_HAL::I2CDriver
bool _ignore_errors
Detailed Description
Definition at line 26 of file I2CDriver.h.
Constructor & Destructor Documentation
FLYMAPLEI2CDriver::FLYMAPLEI2CDriver (AP_HAL::Semaphore * semaphore)
Definition at line 36 of file I2CDriver.cpp.
Member Function Documentation
void FLYMAPLEI2CDriver::_reset () private
Definition at line 140 of file I2CDriver.cpp.
Referenced by _transfer(), and begin().
uint8_t FLYMAPLEI2CDriver::_transfer (i2c_msg * msgs, uint16 num) private
Definition at line 125 of file I2CDriver.cpp.
Referenced by read(), readRegisters(), write(), and writeRegisters().
void FLYMAPLEI2CDriver::begin () virtual
Implements AP_HAL::I2CDriver.
Definition at line 42 of file I2CDriver.cpp.
void FLYMAPLEI2CDriver::end () virtual
Implements AP_HAL::I2CDriver.
Definition at line 47 of file I2CDriver.cpp.
AP_HAL::Semaphore* AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver::get_semaphore () inline virtual
Implements AP_HAL::I2CDriver.
Definition at line 54 of file I2CDriver.h.
uint8_t FLYMAPLEI2CDriver::lockup_count () virtual
Implements AP_HAL::I2CDriver.
Definition at line 121 of file I2CDriver.cpp.
uint8_t FLYMAPLEI2CDriver::read (uint8_t addr, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 86 of file I2CDriver.cpp.
uint8_t FLYMAPLEI2CDriver::readRegister (uint8_t addr, uint8_t reg, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 98 of file I2CDriver.cpp.
uint8_t FLYMAPLEI2CDriver::readRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 103 of file I2CDriver.cpp.
Referenced by readRegister().
void FLYMAPLEI2CDriver::setHighSpeed (bool active) virtual
Implements AP_HAL::I2CDriver.
Definition at line 54 of file I2CDriver.cpp.
void FLYMAPLEI2CDriver::setTimeout (uint16_t ms) virtual
Implements AP_HAL::I2CDriver.
Definition at line 49 of file I2CDriver.cpp.
uint8_t FLYMAPLEI2CDriver::write (uint8_t addr, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 56 of file I2CDriver.cpp.
uint8_t FLYMAPLEI2CDriver::writeRegister (uint8_t addr, uint8_t reg, uint8_t val) virtual
Implements AP_HAL::I2CDriver.
Definition at line 66 of file I2CDriver.cpp.
uint8_t FLYMAPLEI2CDriver::writeRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 71 of file I2CDriver.cpp.
Referenced by writeRegister().
Member Data Documentation
uint8_t AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver::_lockup_count private
Definition at line 57 of file I2CDriver.h.
Referenced by _transfer(), and lockup_count().
AP_HAL::Semaphore* AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver::_semaphore private
Definition at line 60 of file I2CDriver.h.
Referenced by get_semaphore().
uint16_t AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver::_timeout_ms private
Definition at line 61 of file I2CDriver.h.
Referenced by _transfer(), and setTimeout().
The documentation for this class was generated from the following files:
libraries/AP_HAL_FLYMAPLE/I2CDriver.h
libraries/AP_HAL_FLYMAPLE/I2CDriver.cpp