APM:Libraries: AC_P Class Reference
AC_P Class Reference
Object managing one P controller.
#include <AC_P.h>
Public Member Functions
AC_P (const float &initial_p=0.0f)
float get_p (float error) const
void load_gains ()
void save_gains ()
parameter accessors
static const struct AP_Param::GroupInfo var_info []
AP_Float _kp
void operator() (const float p)
Overload the function call operator to permit relatively easy initialisation.
float kP () const
void kP (const float v)
Detailed Description
Object managing one P controller.
Definition at line 16 of file AC_P.h.
Constructor & Destructor Documentation
AC_P::AC_P (const float & initial_p = 0.0f) inline
Constructor for P that saves its settings to EEPROM
Note
PIs must be named to avoid either multiple parameters with the same name, or an overly complex constructor.
Parameters
initial_p Initial value for the P term.
Definition at line 26 of file AC_P.h.
Member Function Documentation
float AC_P::get_p (float error) const
Iterate the P controller, return the new control value
Positive error produces positive output.
Parameters
error The measured error value
dt The time delta in milliseconds (note that update interval cannot be more than 65.535 seconds due to limited range of the data type).
Returns
The updated control output.
Definition at line 17 of file AC_P.cpp.
float AC_P::kP () const inline
Definition at line 62 of file AC_P.h.
Referenced by AC_PosControl::calc_leash_length_xy(), AC_PosControl::calc_leash_length_z(), AC_PosControl::get_pos_xy_kP(), AC_PosControl::get_stopping_point_xy(), AC_PosControl::get_stopping_point_z(), AC_AttitudeControl::max_angle_step_bf_pitch(), AC_AttitudeControl::max_angle_step_bf_roll(), AC_AttitudeControl::max_angle_step_bf_yaw(), AC_PosControl::pos_to_rate_xy(), AC_PosControl::pos_to_rate_z(), AC_PosControl::rate_to_accel_z(), and AC_AttitudeControl::update_rate_bf_targets().
void AC_P::kP (const float v) inline
Definition at line 63 of file AC_P.h.
void AC_P::load_gains ()
Load gain properties
Definition at line 22 of file AC_P.cpp.
void AC_P::operator() (const float p) inline
Overload the function call operator to permit relatively easy initialisation.
Definition at line 59 of file AC_P.h.
void AC_P::save_gains ()
Save gain properties
Definition at line 27 of file AC_P.cpp.
Member Data Documentation
AP_Float AC_P::_kp private
Definition at line 68 of file AC_P.h.
Referenced by AC_P(), get_p(), kP(), load_gains(), operator()(), and save_gains().
const AP_Param::GroupInfo AC_P::var_info static
Initial value:
= {
    AP_GROUPINFO("P",    0, AC_P, _kp, 0),
    AP_GROUPEND
}
Definition at line 65 of file AC_P.h.
Referenced by AC_P().
The documentation for this class was generated from the following files:
libraries/AC_PID/AC_P.h
libraries/AC_PID/AC_P.cpp