APM:Libraries: AP_Compass_AK8963 Class Reference
AP_Compass_AK8963 Class Reference
#include <AP_Compass_AK8963.h>
Public Member Functions
AP_Compass_AK8963 (Compass &compass, AP_AK8963_SerialBus *bus)
~AP_Compass_AK8963 ()
bool init (void)
void read (void)
void accumulate (void)
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend (Compass &compass)
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * detect_mpu9250 (Compass &compass, uint8_t mpu9250_instance)
static AP_Compass_Backend * detect_mpu9250_i2c (Compass &compass, AP_HAL::I2CDriver *i2c, uint8_t addr)
static AP_Compass_Backend * detect_i2c (Compass &compass, AP_HAL::I2CDriver *i2c, uint8_t addr)
Private Member Functions
void _make_factory_sensitivity_adjustment (Vector3f &field) const
void _make_adc_sensitivity_adjustment (Vector3f &field) const
Vector3f _get_filtered_field () const
void _reset_filter ()
bool _reset ()
bool _setup_mode ()
bool _check_id ()
bool _calibrate ()
void _update ()
void _dump_registers ()
bool _sem_take_blocking ()
bool _sem_take_nonblocking ()
bool _sem_give ()
Static Private Member Functions
static AP_Compass_Backend * _detect (Compass &compass, AP_AK8963_SerialBus *bus)
Private Attributes
float _magnetometer_ASA [3]
float uint8_t _compass_instance
float _mag_x_accum
float _mag_y_accum
float _mag_z_accum
uint32_t _accum_count
bool _initialized
uint32_t _last_update_timestamp
uint32_t _last_accum_time
AP_AK8963_SerialBus * _bus = nullptr
AP_HAL::Semaphore * _bus_sem
Additional Inherited Members
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_unfiltered_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void set_external (uint8_t instance, bool external)
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
Detailed Description
Definition at line 38 of file AP_Compass_AK8963.h.
Constructor & Destructor Documentation
AP_Compass_AK8963::AP_Compass_AK8963 (Compass & compass, AP_AK8963_SerialBus * bus)
Definition at line 63 of file AP_Compass_AK8963.cpp.
Referenced by _detect().
AP_Compass_AK8963::~AP_Compass_AK8963 ()
Definition at line 117 of file AP_Compass_AK8963.cpp.
Member Function Documentation
bool AP_Compass_AK8963::_calibrate () private
Definition at line 320 of file AP_Compass_AK8963.cpp.
Referenced by init().
bool AP_Compass_AK8963::_check_id () private
Definition at line 294 of file AP_Compass_AK8963.cpp.
Referenced by init().
AP_Compass_Backend * AP_Compass_AK8963::_detect (Compass & compass, AP_AK8963_SerialBus * bus) static private
Definition at line 101 of file AP_Compass_AK8963.cpp.
Referenced by detect_i2c(), and detect_mpu9250().
void AP_Compass_AK8963::_dump_registers () private
Definition at line 368 of file AP_Compass_AK8963.cpp.
Vector3f AP_Compass_AK8963::_get_filtered_field () const private
Definition at line 197 of file AP_Compass_AK8963.cpp.
Referenced by read().
void AP_Compass_AK8963::_make_adc_sensitivity_adjustment (Vector3f & field) const private
Definition at line 211 of file AP_Compass_AK8963.cpp.
Referenced by _update().
void AP_Compass_AK8963::_make_factory_sensitivity_adjustment (Vector3f & field) const private
Definition at line 218 of file AP_Compass_AK8963.cpp.
Referenced by _update().
bool AP_Compass_AK8963::_reset () private
Definition at line 313 of file AP_Compass_AK8963.cpp.
void AP_Compass_AK8963::_reset_filter () private
Definition at line 205 of file AP_Compass_AK8963.cpp.
Referenced by AP_Compass_AK8963(), and read().
bool AP_Compass_AK8963::_sem_give () private
Definition at line 342 of file AP_Compass_AK8963.cpp.
Referenced by _update().
bool AP_Compass_AK8963::_sem_take_blocking () private
Definition at line 337 of file AP_Compass_AK8963.cpp.
bool AP_Compass_AK8963::_sem_take_nonblocking () private
Definition at line 347 of file AP_Compass_AK8963.cpp.
Referenced by _update().
bool AP_Compass_AK8963::_setup_mode () private
Definition at line 308 of file AP_Compass_AK8963.cpp.
Referenced by init().
void AP_Compass_AK8963::_update () private
Definition at line 225 of file AP_Compass_AK8963.cpp.
Referenced by init().
void AP_Compass_AK8963::accumulate (void) virtual
Reimplemented from AP_Compass_Backend.
Definition at line 123 of file AP_Compass_AK8963.cpp.
AP_Compass_Backend * AP_Compass_AK8963::detect_i2c (Compass & compass, AP_HAL::I2CDriver * i2c, uint8_t addr) static
Definition at line 82 of file AP_Compass_AK8963.cpp.
Referenced by Compass::_detect_backends(), and detect_mpu9250_i2c().
AP_Compass_Backend * AP_Compass_AK8963::detect_mpu9250 (Compass & compass, uint8_t mpu9250_instance) static
Definition at line 73 of file AP_Compass_AK8963.cpp.
Referenced by Compass::_detect_backends().
AP_Compass_Backend * AP_Compass_AK8963::detect_mpu9250_i2c (Compass & compass, AP_HAL::I2CDriver * i2c, uint8_t addr) static
Definition at line 92 of file AP_Compass_AK8963.cpp.
Referenced by Compass::_detect_backends().
bool AP_Compass_AK8963::init (void) virtual
Implements AP_Compass_Backend.
Definition at line 127 of file AP_Compass_AK8963.cpp.
Referenced by _detect().
void AP_Compass_AK8963::read (void) virtual
Implements AP_Compass_Backend.
Definition at line 178 of file AP_Compass_AK8963.cpp.
Member Data Documentation
uint32_t AP_Compass_AK8963::_accum_count private
Definition at line 81 of file AP_Compass_AK8963.h.
Referenced by _get_filtered_field(), _reset_filter(), _update(), and read().
AP_AK8963_SerialBus* AP_Compass_AK8963::_bus = nullptr private
Definition at line 87 of file AP_Compass_AK8963.h.
Referenced by _calibrate(), _check_id(), _reset(), _setup_mode(), _update(), init(), and ~AP_Compass_AK8963().
AP_HAL::Semaphore* AP_Compass_AK8963::_bus_sem private
Definition at line 88 of file AP_Compass_AK8963.h.
Referenced by _sem_give(), _sem_take_blocking(), _sem_take_nonblocking(), and init().
float uint8_t AP_Compass_AK8963::_compass_instance private
Definition at line 75 of file AP_Compass_AK8963.h.
Referenced by _update(), init(), and read().
bool AP_Compass_AK8963::_initialized private
Definition at line 83 of file AP_Compass_AK8963.h.
Referenced by init(), and read().
uint32_t AP_Compass_AK8963::_last_accum_time private
Definition at line 85 of file AP_Compass_AK8963.h.
uint32_t AP_Compass_AK8963::_last_update_timestamp private
Definition at line 84 of file AP_Compass_AK8963.h.
Referenced by _update().
float AP_Compass_AK8963::_mag_x_accum private
Definition at line 78 of file AP_Compass_AK8963.h.
Referenced by _get_filtered_field(), _reset_filter(), and _update().
float AP_Compass_AK8963::_mag_y_accum private
Definition at line 79 of file AP_Compass_AK8963.h.
Referenced by _get_filtered_field(), _reset_filter(), and _update().
float AP_Compass_AK8963::_mag_z_accum private
Definition at line 80 of file AP_Compass_AK8963.h.
Referenced by _get_filtered_field(), _reset_filter(), and _update().
float AP_Compass_AK8963::_magnetometer_ASA[3] private
Definition at line 75 of file AP_Compass_AK8963.h.
Referenced by _calibrate(), and _make_factory_sensitivity_adjustment().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_AK8963.h
libraries/AP_Compass/AP_Compass_AK8963.cpp