APM:Libraries: Linux::GPIO_RPI Class Reference
Linux::GPIO_RPI Class Reference
#include <GPIO_RPI.h>
Public Member Functions
GPIO_RPI ()
void init ()
void pinMode (uint8_t pin, uint8_t output)
void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
int8_t analogPinToDigitalPin (uint8_t pin)
uint8_t read (uint8_t pin)
void write (uint8_t pin, uint8_t value)
void toggle (uint8_t pin)
void setPWMPeriod (uint8_t pin, uint32_t time_us)
void setPWMDuty (uint8_t pin, uint8_t percent)
AP_HAL::DigitalSource * channel (uint16_t n)
bool attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode)
bool usb_connected (void)
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
Private Member Functions
void setPWM0Period (uint32_t time_us)
void setPWM0Duty (uint8_t percent)
Private Attributes
int mem_fd
void * gpio_map
void * pwm_map
void * clk_map
volatile uint32_t * gpio
volatile uint32_t * pwm
volatile uint32_t * clk
Detailed Description
Definition at line 67 of file GPIO_RPI.h.
Constructor & Destructor Documentation
GPIO_RPI::GPIO_RPI ()
Definition at line 22 of file GPIO_RPI.cpp.
Member Function Documentation
int8_t GPIO_RPI::analogPinToDigitalPin (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 98 of file GPIO_RPI.cpp.
bool GPIO_RPI::attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode) virtual
Implements AP_HAL::GPIO.
Definition at line 191 of file GPIO_RPI.cpp.
AP_HAL::DigitalSource * GPIO_RPI::channel (uint16_t n) virtual
Implements AP_HAL::GPIO.
Definition at line 186 of file GPIO_RPI.cpp.
void GPIO_RPI::init (void) virtual
Implements AP_HAL::GPIO.
Definition at line 25 of file GPIO_RPI.cpp.
void GPIO_RPI::pinMode (uint8_t pin, uint8_t output) virtual
Implements AP_HAL::GPIO.
Definition at line 75 of file GPIO_RPI.cpp.
void GPIO_RPI::pinMode (uint8_t pin, uint8_t output, uint8_t alt) virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 85 of file GPIO_RPI.cpp.
uint8_t GPIO_RPI::read (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 103 of file GPIO_RPI.cpp.
Referenced by toggle().
void GPIO_RPI::setPWM0Duty (uint8_t percent) private
Definition at line 168 of file GPIO_RPI.cpp.
Referenced by setPWM0Period(), and setPWMDuty().
void GPIO_RPI::setPWM0Period (uint32_t time_us) private
Definition at line 133 of file GPIO_RPI.cpp.
Referenced by setPWMPeriod().
void GPIO_RPI::setPWMDuty (uint8_t pin, uint8_t percent) virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 128 of file GPIO_RPI.cpp.
void GPIO_RPI::setPWMPeriod (uint8_t pin, uint32_t time_us) virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 123 of file GPIO_RPI.cpp.
void GPIO_RPI::toggle (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 118 of file GPIO_RPI.cpp.
bool GPIO_RPI::usb_connected (void) virtual
Implements AP_HAL::GPIO.
Definition at line 196 of file GPIO_RPI.cpp.
void GPIO_RPI::write (uint8_t pin, uint8_t value) virtual
Implements AP_HAL::GPIO.
Definition at line 109 of file GPIO_RPI.cpp.
Referenced by toggle().
Member Data Documentation
volatile uint32_t* Linux::GPIO_RPI::clk private
Definition at line 75 of file GPIO_RPI.h.
Referenced by init(), and setPWM0Period().
void* Linux::GPIO_RPI::clk_map private
Definition at line 72 of file GPIO_RPI.h.
Referenced by init().
volatile uint32_t* Linux::GPIO_RPI::gpio private
Definition at line 73 of file GPIO_RPI.h.
Referenced by init().
void* Linux::GPIO_RPI::gpio_map private
Definition at line 70 of file GPIO_RPI.h.
Referenced by init().
int Linux::GPIO_RPI::mem_fd private
Definition at line 69 of file GPIO_RPI.h.
Referenced by init().
volatile uint32_t* Linux::GPIO_RPI::pwm private
Definition at line 74 of file GPIO_RPI.h.
Referenced by init(), setPWM0Duty(), and setPWM0Period().
void* Linux::GPIO_RPI::pwm_map private
Definition at line 71 of file GPIO_RPI.h.
Referenced by init().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/GPIO_RPI.h
libraries/AP_HAL_Linux/GPIO_RPI.cpp