APM:Libraries: RCMapper Class Reference
RCMapper Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_RCMapper.h>
Public Member Functions
RCMapper ()
uint8_t roll () const
roll - return input channel number for roll / aileron input
uint8_t pitch () const
pitch - return input channel number for pitch / elevator input
uint8_t throttle () const
throttle - return input channel number for throttle input
uint8_t yaw () const
yaw - return input channel number for yaw / rudder input
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Private Attributes
AP_Int8 _ch_roll
AP_Int8 _ch_pitch
AP_Int8 _ch_yaw
AP_Int8 _ch_throttle
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 9 of file AP_RCMapper.h.
Constructor & Destructor Documentation
RCMapper::RCMapper (void)
Constructor
Definition at line 47 of file AP_RCMapper.cpp.
Member Function Documentation
uint8_t RCMapper::pitch () const inline
pitch - return input channel number for pitch / elevator input
Definition at line 20 of file AP_RCMapper.h.
Referenced by APM_OBC::check_crash_plane(), and APM_OBC::setup_failsafe().
uint8_t RCMapper::roll () const inline
roll - return input channel number for roll / aileron input
Definition at line 17 of file AP_RCMapper.h.
Referenced by APM_OBC::check_crash_plane(), and APM_OBC::setup_failsafe().
uint8_t RCMapper::throttle () const inline
throttle - return input channel number for throttle input
Definition at line 23 of file AP_RCMapper.h.
Referenced by APM_OBC::check_crash_plane(), and APM_OBC::setup_failsafe().
uint8_t RCMapper::yaw () const inline
yaw - return input channel number for yaw / rudder input
Definition at line 26 of file AP_RCMapper.h.
Referenced by APM_OBC::check_crash_plane(), and APM_OBC::setup_failsafe().
Member Data Documentation
AP_Int8 RCMapper::_ch_pitch private
Definition at line 33 of file AP_RCMapper.h.
Referenced by pitch().
AP_Int8 RCMapper::_ch_roll private
Definition at line 32 of file AP_RCMapper.h.
Referenced by roll().
AP_Int8 RCMapper::_ch_throttle private
Definition at line 35 of file AP_RCMapper.h.
Referenced by throttle().
AP_Int8 RCMapper::_ch_yaw private
Definition at line 34 of file AP_RCMapper.h.
Referenced by yaw().
const AP_Param::GroupInfo RCMapper::var_info static
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 28 of file AP_RCMapper.h.
Referenced by RCMapper().
The documentation for this class was generated from the following files:
libraries/AP_RCMapper/AP_RCMapper.h
libraries/AP_RCMapper/AP_RCMapper.cpp