APM:Libraries: AP_Buffer< T, SIZE > Class Template Reference
AP_Buffer< T, SIZE > Class Template Reference
#include <AP_Buffer.h>
Public Member Functions
AP_Buffer ()
void clear ()
void push_back (const T &item)
bool pop_front (T &ret)
const T & peek (uint8_t position) const
T & peek_mutable (uint8_t position)
const T & front () const
uint8_t size () const
bool is_full () const
bool is_empty () const
Private Attributes
uint8_t _num_items
uint8_t _head
T _buff [SIZE]
Detailed Description
template<class T, uint8_t SIZE>
class AP_Buffer< T, SIZE >
Definition at line 13 of file AP_Buffer.h.
Constructor & Destructor Documentation
template<class T , uint8_t SIZE> AP_Buffer< T, SIZE >::AP_Buffer ()
Constructor
Definition at line 72 of file AP_Buffer.h.
Member Function Documentation
template<class T , uint8_t SIZE> void AP_Buffer< T, SIZE >::clear ()
clear - removes all elements from the queue
Definition at line 78 of file AP_Buffer.h.
template<class T, uint8_t SIZE> const T& AP_Buffer< T, SIZE >::front () const inline
front - return a reference to the element at the begin of the queue (i.e. the oldest element) If the queue is empty, 0 is returned.
Returns
: oldest element
Definition at line 47 of file AP_Buffer.h.
template<class T, uint8_t SIZE> bool AP_Buffer< T, SIZE >::is_empty () const inline
is_empty - returns true if the queue is empty
Returns
Definition at line 59 of file AP_Buffer.h.
Referenced by AP_Baro_HIL::update().
template<class T, uint8_t SIZE> bool AP_Buffer< T, SIZE >::is_full () const inline
is_full - return true if the queue is full (i.e. size() == SIZE)
Returns
Definition at line 55 of file AP_Buffer.h.
template<class T , uint8_t SIZE> const T & AP_Buffer< T, SIZE >::peek (uint8_t position) const
peek - returns a reference to an element of the buffer if position isn't valid (i.e. >= size()) 0 is returned
Parameters
position : index of the element "0" is the oldest, size()-1 is the newest
Returns
Definition at line 132 of file AP_Buffer.h.
Referenced by AP_Buffer< float, 10 >::front().
template<class T , uint8_t SIZE> T & AP_Buffer< T, SIZE >::peek_mutable (uint8_t position)
Definition at line 145 of file AP_Buffer.h.
template<class T, uint8_t SIZE> bool AP_Buffer< T, SIZE >::pop_front (T & ret)
pop_front - removes an element from the beginning of the buffer (i.e. the oldest element) and returns it in ret.
Parameters
ret : the removed element, if exists
Returns
: true if successful, false if not
Definition at line 109 of file AP_Buffer.h.
Referenced by AP_Baro_HIL::update().
template<class T, uint8_t SIZE> void AP_Buffer< T, SIZE >::push_back (const T & item)
push_back - adds an item to the end of the buffer. If the buffer is full, the oldest element (i.e. the element at the begin) is removed
Parameters
item
Definition at line 85 of file AP_Buffer.h.
template<class T, uint8_t SIZE> uint8_t AP_Buffer< T, SIZE >::size () const inline
size - returns the number of elements in the queue
Returns
Definition at line 51 of file AP_Buffer.h.
Member Data Documentation
template<class T, uint8_t SIZE> T AP_Buffer< T, SIZE >::_buff[SIZE] private
Definition at line 64 of file AP_Buffer.h.
template<class T, uint8_t SIZE> uint8_t AP_Buffer< T, SIZE >::_head private
Definition at line 63 of file AP_Buffer.h.
template<class T, uint8_t SIZE> uint8_t AP_Buffer< T, SIZE >::_num_items private
Definition at line 62 of file AP_Buffer.h.
Referenced by AP_Buffer< float, 10 >::is_empty(), AP_Buffer< float, 10 >::is_full(), and AP_Buffer< float, 10 >::size().
The documentation for this class was generated from the following file:
libraries/AP_Buffer/AP_Buffer.h