APM:Libraries: AP_HAL::I2CDriver Class Reference
AP_HAL::I2CDriver Class Reference abstract
#include <I2CDriver.h>
Public Member Functions
virtual void begin ()=0
virtual void end ()=0
virtual void setTimeout (uint16_t ms)=0
virtual void setHighSpeed (bool active)=0
virtual uint8_t write (uint8_t addr, uint8_t len, uint8_t *data)=0
virtual uint8_t writeRegister (uint8_t addr, uint8_t reg, uint8_t val)=0
virtual uint8_t writeRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t *data)=0
virtual uint8_t read (uint8_t addr, uint8_t len, uint8_t *data)=0
virtual uint8_t readRegister (uint8_t addr, uint8_t reg, uint8_t *data)=0
virtual uint8_t readRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t *data)=0
virtual uint8_t readRegistersMultiple (uint8_t addr, uint8_t reg, uint8_t len, uint8_t count, uint8_t *data)=0
virtual uint8_t lockup_count ()=0
void ignore_errors (bool b)
virtual AP_HAL::Semaphore * get_semaphore ()=0
Protected Attributes
bool _ignore_errors
Detailed Description
Definition at line 9 of file I2CDriver.h.
Member Function Documentation
virtual void AP_HAL::I2CDriver::begin () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
Referenced by HAL_Linux::run(), and HAL_FLYMAPLE::run().
virtual void AP_HAL::I2CDriver::end () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
virtual AP_HAL::Semaphore* AP_HAL::I2CDriver::get_semaphore () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_Airspeed_I2C::_timer(), AP_Baro_BMP085::accumulate(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_RangeFinder_LightWareI2C::get_reading(), AP_RangeFinder_MaxsonarI2CXL::get_reading(), AP_RangeFinder_PulsedLightLRF::get_reading(), AP_HMC5843_SerialBus_I2C::get_semaphore(), AP_AK8963_SerialBus_I2C::get_semaphore(), AP_MPU9250_BusDriver_I2C::get_semaphore(), AP_MPU6000_BusDriver_I2C::get_semaphore(), ToshibaLED_I2C::hw_init(), NavioLED_I2C::hw_init(), ToshibaLED_I2C::hw_set_rgb(), NavioLED_I2C::hw_set_rgb(), Linux::RCOutput_PCA9685::init(), AP_ADC_ADS1115::init(), AP_OpticalFlow_Linux::init(), AP_Airspeed_I2C::init(), Linux::RCOutput_Bebop::init(), AP_SerialBus_I2C::init(), AP_OpticalFlow_Linux::read(), AP_RangeFinder_MaxsonarI2CXL::start_reading(), and AP_RangeFinder_PulsedLightLRF::start_reading().
void AP_HAL::I2CDriver::ignore_errors (bool b) inline
Definition at line 44 of file I2CDriver.h.
Referenced by ToshibaLED_I2C::hw_init(), and NavioLED_I2C::hw_init().
virtual uint8_t AP_HAL::I2CDriver::lockup_count () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
Referenced by loop().
virtual uint8_t AP_HAL::I2CDriver::read (uint8_t addr, uint8_t len, uint8_t * data) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, PX4::PX4I2CDriver, Linux::I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_Airspeed_I2C::_collect(), AP_RangeFinder_LightWareI2C::detect(), AP_RangeFinder_LightWareI2C::get_reading(), and AP_RangeFinder_MaxsonarI2CXL::get_reading().
virtual uint8_t AP_HAL::I2CDriver::readRegister (uint8_t addr, uint8_t reg, uint8_t * data) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, PX4::PX4I2CDriver, Linux::I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_MPU9150::mpu_read_fifo(), AP_MPU9250_BusDriver_I2C::read8(), and AP_MPU6000_BusDriver_I2C::read8().
virtual uint8_t AP_HAL::I2CDriver::readRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t * data) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, PX4::PX4I2CDriver, Linux::I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), AP_InertialSensor_MPU9150::_init_sensor(), AP_ADC_ADS1115::_update(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_RangeFinder_PulsedLightLRF::get_reading(), AP_OpticalFlow_Linux::init(), loop(), AP_InertialSensor_MPU9150::mpu_read_fifo(), AP_OpticalFlow_Linux::read(), AP_SerialBus_I2C::read_16bits(), AP_SerialBus_I2C::read_24bits(), AP_MPU9250_BusDriver_I2C::read_block(), AP_MPU6000_BusDriver_I2C::read_block(), AP_MPU9250_BusDriver_I2C::read_data_transaction(), AP_MPU6000_BusDriver_I2C::read_data_transaction(), Linux::RCOutput_Bebop::read_obs_data(), AP_AK8963_SerialBus_I2C::read_raw(), AP_Baro_BMP085::ReadPress(), AP_Baro_BMP085::ReadTemp(), AP_HMC5843_SerialBus_I2C::register_read(), and AP_AK8963_SerialBus_I2C::register_read().
virtual uint8_t AP_HAL::I2CDriver::readRegistersMultiple (uint8_t addr, uint8_t reg, uint8_t len, uint8_t count, uint8_t * data) pure virtual
Implemented in Linux::I2CDriver.
Referenced by AP_InertialSensor_L3G4200D::_accumulate().
virtual void AP_HAL::I2CDriver::setHighSpeed (bool active) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_Baro_BMP085::ReadPress(), AP_Baro_BMP085::ReadTemp(), and AP_HMC5843_SerialBus_I2C::set_high_speed().
virtual void AP_HAL::I2CDriver::setTimeout (uint16_t ms) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
Referenced by HAL_FLYMAPLE::run().
virtual uint8_t AP_HAL::I2CDriver::write (uint8_t addr, uint8_t len, uint8_t * data) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, Linux::I2CDriver, PX4::PX4I2CDriver, and Empty::EmptyI2CDriver.
Referenced by Linux::RCOutput_Bebop::_clear_error(), Linux::RCOutput_Bebop::_set_ref_speed(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), AP_RangeFinder_MaxsonarI2CXL::start_reading(), and AP_SerialBus_I2C::write().
virtual uint8_t AP_HAL::I2CDriver::writeRegister (uint8_t addr, uint8_t reg, uint8_t val) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, PX4::PX4I2CDriver, Linux::I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), Linux::RCOutput_Bebop::_play_sound(), Linux::RCOutput_Bebop::_toggle_gpio(), AP_Baro_BMP085::Command_ReadPress(), AP_Baro_BMP085::Command_ReadTemp(), ToshibaLED_I2C::hw_init(), AP_InertialSensor_MPU9150::mpu_reset_fifo(), AP_InertialSensor_MPU9150::mpu_set_accel_fsr(), AP_InertialSensor_MPU9150::mpu_set_compass_sample_rate(), AP_InertialSensor_MPU9150::mpu_set_gyro_fsr(), AP_InertialSensor_MPU9150::mpu_set_lpf(), AP_InertialSensor_MPU9150::mpu_set_sample_rate(), AP_InertialSensor_MPU9150::mpu_set_sensors(), AP_HMC5843_SerialBus_I2C::register_write(), AP_AK8963_SerialBus_I2C::register_write(), Linux::RCOutput_PCA9685::set_freq(), AP_InertialSensor_MPU9150::set_int_enable(), setup(), AP_RangeFinder_PulsedLightLRF::start_reading(), AP_MPU9250_BusDriver_I2C::write8(), and AP_MPU6000_BusDriver_I2C::write8().
virtual uint8_t AP_HAL::I2CDriver::writeRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t * data) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver, PX4::PX4I2CDriver, Linux::I2CDriver, and Empty::EmptyI2CDriver.
Referenced by AP_Airspeed_I2C::_measure(), AP_ADC_ADS1115::_start_conversion(), ToshibaLED_I2C::hw_init(), ToshibaLED_I2C::hw_set_rgb(), NavioLED_I2C::hw_set_rgb(), Linux::RCOutput_PCA9685::push(), AP_OpticalFlow_Linux::request_measurement(), and Linux::RCOutput_PCA9685::reset_all_channels().
Member Data Documentation
bool AP_HAL::I2CDriver::_ignore_errors protected
Definition at line 47 of file I2CDriver.h.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLEI2CDriver::_transfer(), and ignore_errors().
The documentation for this class was generated from the following file:
libraries/AP_HAL/I2CDriver.h