APM:Libraries: AP_HAL::Semaphore Class Reference
AP_HAL::Semaphore Class Reference abstract
#include <Semaphores.h>
Public Member Functions
virtual bool take (uint32_t timeout_ms) WARN_IF_UNUSED=0
virtual bool take_nonblocking () WARN_IF_UNUSED=0
virtual bool give ()=0
Detailed Description
Definition at line 9 of file Semaphores.h.
Member Function Documentation
virtual bool AP_HAL::Semaphore::give () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore, Linux::Semaphore, and Empty::EmptySemaphore.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), Linux::RCOutput_Bebop::_clear_error(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::RCOutput_Bebop::_play_sound(), Linux::RCInput_Raspilot::_poll_data(), AP_InertialSensor_MPU9250::_poll_data(), AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_MPU6000::_poll_data(), AP_Compass_AK8963::_sem_give(), Linux::RCOutput_Bebop::_set_ref_speed(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), AP_Airspeed_I2C::_timer(), Linux::RPIOUARTDriver::_timer_tick(), Linux::RCOutput_Bebop::_toggle_gpio(), Linux::RCOutput_Raspilot::_update(), AP_Compass_LSM303D::_update(), AP_ADC_ADS1115::_update(), RaspilotAnalogIn::_update(), AP_Baro_BMP085::accumulate(), AP_Compass_HMC5843::accumulate(), AP_Baro_BMP085::AP_Baro_BMP085(), async_blinker(), AP_RangeFinder_LightWareI2C::get_reading(), AP_RangeFinder_MaxsonarI2CXL::get_reading(), AP_RangeFinder_PulsedLightLRF::get_reading(), ToshibaLED_I2C::hw_init(), NavioLED_I2C::hw_init(), ToshibaLED_I2C::hw_set_rgb(), NavioLED_I2C::hw_set_rgb(), AP_ADC_ADS7844::Init(), AP_OpticalFlow_Linux::init(), AP_Airspeed_I2C::init(), AP_Compass_AK8963::init(), AP_Compass_LSM303D::init(), AP_Compass_HMC5843::init(), loop(), Linux::RCOutput_PCA9685::push(), AP_ADC_ADS7844::read(), AP_OpticalFlow_Linux::read(), Linux::RCOutput_Bebop::read_obs_data(), Linux::RCOutput_PCA9685::reset_all_channels(), Linux::SPIUARTDriver::sem_give(), Linux::RPIOUARTDriver::sem_give(), AP_SerialBus_SPI::sem_give(), AP_SerialBus_I2C::sem_give(), Linux::RCOutput_Raspilot::set_freq(), Linux::RCOutput_PCA9685::set_freq(), AP_InertialSensor_MPU6000::start(), AP_RangeFinder_MaxsonarI2CXL::start_reading(), AP_RangeFinder_PulsedLightLRF::start_reading(), and Linux::Storage_FRAM::transaction().
virtual bool AP_HAL::Semaphore::take (uint32_t timeout_ms) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore, Linux::Semaphore, and Empty::EmptySemaphore.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), Linux::RCOutput_Bebop::_clear_error(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::RCOutput_Bebop::_play_sound(), AP_Compass_AK8963::_sem_take_blocking(), Linux::RCOutput_Bebop::_set_ref_speed(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), Linux::RCOutput_Bebop::_toggle_gpio(), AP_Baro_BMP085::accumulate(), AP_Compass_HMC5843::accumulate(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_RangeFinder_LightWareI2C::get_reading(), AP_RangeFinder_MaxsonarI2CXL::get_reading(), AP_RangeFinder_PulsedLightLRF::get_reading(), ToshibaLED_I2C::hw_init(), NavioLED_I2C::hw_init(), ToshibaLED_I2C::hw_set_rgb(), NavioLED_I2C::hw_set_rgb(), AP_ADC_ADS7844::Init(), AP_OpticalFlow_Linux::init(), AP_Airspeed_I2C::init(), AP_Compass_LSM303D::init(), AP_Compass_AK8963::init(), AP_Compass_HMC5843::init(), loop(), Linux::RCOutput_Bebop::read_obs_data(), Linux::RCOutput_PCA9685::reset_all_channels(), AP_SerialBus_SPI::sem_take_blocking(), AP_SerialBus_I2C::sem_take_blocking(), Linux::RCOutput_Raspilot::set_freq(), Linux::RCOutput_PCA9685::set_freq(), AP_InertialSensor_MPU6000::start(), AP_RangeFinder_MaxsonarI2CXL::start_reading(), AP_RangeFinder_PulsedLightLRF::start_reading(), and Linux::Storage_FRAM::transaction().
virtual bool AP_HAL::Semaphore::take_nonblocking () pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore, Linux::Semaphore, and Empty::EmptySemaphore.
Referenced by AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), Linux::RCInput_Raspilot::_poll_data(), AP_InertialSensor_MPU9250::_poll_data(), AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_MPU6000::_poll_data(), AP_Compass_AK8963::_sem_take_nonblocking(), AP_Airspeed_I2C::_timer(), Linux::RPIOUARTDriver::_timer_tick(), Linux::RCOutput_Raspilot::_update(), AP_Compass_LSM303D::_update(), AP_ADC_ADS1115::_update(), RaspilotAnalogIn::_update(), async_blinker(), Linux::RCOutput_PCA9685::push(), AP_ADC_ADS7844::read(), AP_OpticalFlow_Linux::read(), Linux::SPIUARTDriver::sem_take_nonblocking(), Linux::RPIOUARTDriver::sem_take_nonblocking(), AP_SerialBus_SPI::sem_take_nonblocking(), and AP_SerialBus_I2C::sem_take_nonblocking().
The documentation for this class was generated from the following file:
libraries/AP_HAL/Semaphores.h