APM:Libraries: AP_InertialSensor_UserInteract Class Reference
AP_InertialSensor_UserInteract Class Reference abstract
#include <AP_InertialSensor_UserInteract.h>
Public Member Functions
virtual bool blocking_read ()=0
virtual void printf (const char *,...) FORMAT(2
Detailed Description
Definition at line 8 of file AP_InertialSensor_UserInteract.h.
Member Function Documentation
virtual bool AP_InertialSensor_UserInteract::blocking_read () pure virtual
Implemented in AP_InertialSensor_UserInteract_MAVLink, and AP_InertialSensor_UserInteractStream.
Referenced by AP_InertialSensor::calibrate_accel().
virtual void AP_InertialSensor_UserInteract::printf (const char * , ...) virtual
Reimplemented in AP_InertialSensor_UserInteract_MAVLink, and AP_InertialSensor_UserInteractStream.
Referenced by AP_InertialSensor::_check_sample_range(), and AP_InertialSensor::calibrate_accel().
The documentation for this class was generated from the following file:
libraries/AP_InertialSensor/AP_InertialSensor_UserInteract.h