APM:Libraries: MAVLink_routing Class Reference
MAVLink_routing Class Reference
#include <MAVLink_routing.h>
Classes
struct route
Public Member Functions
MAVLink_routing (void)
bool check_and_forward (mavlink_channel_t in_channel, const mavlink_message_t *msg)
void send_to_components (const mavlink_message_t *msg)
bool find_by_mavtype (uint8_t mavtype, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
Private Member Functions
void learn_route (mavlink_channel_t in_channel, const mavlink_message_t *msg)
void get_targets (const mavlink_message_t *msg, int16_t &sysid, int16_t &compid)
void handle_heartbeat (mavlink_channel_t in_channel, const mavlink_message_t *msg)
Private Attributes
uint8_t num_routes
struct MAVLink_routing::route routes [MAVLINK_MAX_ROUTES]
Detailed Description
Definition at line 20 of file MAVLink_routing.h.
Constructor & Destructor Documentation
MAVLink_routing::MAVLink_routing (void)
Definition at line 32 of file MAVLink_routing.cpp.
Member Function Documentation
bool MAVLink_routing::check_and_forward (mavlink_channel_t in_channel, const mavlink_message_t * msg)
Definition at line 93 of file MAVLink_routing.cpp.
Referenced by loop(), and GCS_MAVLINK::update().
bool MAVLink_routing::find_by_mavtype (uint8_t mavtype, uint8_t & sysid, uint8_t & compid, mavlink_channel_t & channel)
Definition at line 194 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::find_by_mavtype().
void MAVLink_routing::get_targets (const mavlink_message_t * msg, int16_t & sysid, int16_t & compid) private
Definition at line 298 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
void MAVLink_routing::handle_heartbeat (mavlink_channel_t in_channel, const mavlink_message_t * msg) private
Definition at line 254 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
void MAVLink_routing::learn_route (mavlink_channel_t in_channel, const mavlink_message_t * msg) private
Definition at line 213 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
void MAVLink_routing::send_to_components (const mavlink_message_t * msg)
Definition at line 167 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::send_to_components().
Member Data Documentation
uint8_t MAVLink_routing::num_routes private
Definition at line 49 of file MAVLink_routing.h.
Referenced by check_and_forward(), find_by_mavtype(), handle_heartbeat(), learn_route(), and send_to_components().
struct MAVLink_routing::route MAVLink_routing::routes[MAVLINK_MAX_ROUTES] private
Referenced by check_and_forward(), find_by_mavtype(), handle_heartbeat(), learn_route(), and send_to_components().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/MAVLink_routing.h
libraries/GCS_MAVLink/MAVLink_routing.cpp