APM:Libraries: AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore Class Reference
AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore Class Reference
#include <Semaphores.h>
Public Member Functions
FLYMAPLESemaphore ()
bool give ()
bool take (uint32_t timeout_ms)
bool take_nonblocking ()
Private Member Functions
bool _take_from_mainloop (uint32_t timeout_ms)
bool _take_nonblocking ()
Private Attributes
bool _taken
Detailed Description
Definition at line 24 of file Semaphores.h.
Constructor & Destructor Documentation
FLYMAPLESemaphore::FLYMAPLESemaphore ()
Definition at line 34 of file Semaphores.cpp.
Member Function Documentation
bool FLYMAPLESemaphore::_take_from_mainloop (uint32_t timeout_ms) private
Definition at line 62 of file Semaphores.cpp.
Referenced by take(), and take_nonblocking().
bool FLYMAPLESemaphore::_take_nonblocking () private
Definition at line 83 of file Semaphores.cpp.
Referenced by _take_from_mainloop(), and take_nonblocking().
bool FLYMAPLESemaphore::give () virtual
Implements AP_HAL::Semaphore.
Definition at line 36 of file Semaphores.cpp.
bool FLYMAPLESemaphore::take (uint32_t timeout_ms) virtual
Implements AP_HAL::Semaphore.
Definition at line 45 of file Semaphores.cpp.
bool FLYMAPLESemaphore::take_nonblocking () virtual
Implements AP_HAL::Semaphore.
Definition at line 54 of file Semaphores.cpp.
Member Data Documentation
bool AP_HAL_FLYMAPLE_NS::FLYMAPLESemaphore::_taken private
Definition at line 34 of file Semaphores.h.
Referenced by _take_nonblocking(), and give().
The documentation for this class was generated from the following files:
libraries/AP_HAL_FLYMAPLE/Semaphores.h
libraries/AP_HAL_FLYMAPLE/Semaphores.cpp