APM:Libraries: AP_InertialSensor_MPU6000 Class Reference
AP_InertialSensor_MPU6000 Class Reference
#include <AP_InertialSensor_MPU6000.h>
Public Member Functions
AP_InertialSensor_MPU6000 (AP_InertialSensor &imu, AP_MPU6000_BusDriver *bus)
~AP_InertialSensor_MPU6000 ()
bool update ()
bool gyro_sample_available (void)
bool accel_sample_available (void)
AuxiliaryBus * get_auxiliary_bus () override
void start () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
int16_t product_id (void) const
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_Backend * detect_i2c (AP_InertialSensor &_imu, AP_HAL::I2CDriver *i2c, uint8_t addr)
static AP_InertialSensor_Backend * detect_spi (AP_InertialSensor &_imu)
static AP_InertialSensor_MPU6000 & from (AP_InertialSensor_Backend &backend)
Private Member Functions
bool _init_sensor (void)
bool _sample_available ()
void _read_data_transaction ()
bool _data_ready ()
void _poll_data (void)
void _read_block (uint8_t reg, uint8_t *buf, uint32_t size)
uint8_t _register_read (uint8_t reg)
void _register_write (uint8_t reg, uint8_t val)
void _register_write_check (uint8_t reg, uint8_t val)
bool _hardware_init (void)
void _accumulate (uint8_t *samples, uint8_t n_samples)
void _set_filter_register (uint16_t filter_hz)
Static Private Member Functions
static AP_InertialSensor_Backend * _detect (AP_InertialSensor &_imu, AP_MPU6000_BusDriver *bus, int16_t id=-1)
Private Attributes
friend AP_MPU6000_AuxiliaryBus
friend AP_MPU6000_AuxiliaryBusSlave
uint8_t _gyro_instance
uint8_t _accel_instance
AP_HAL::DigitalSource * _drdy_pin
AP_MPU6000_BusDriver * _bus
AP_HAL::Semaphore * _bus_sem
AP_MPU6000_AuxiliaryBus * _auxiliary_bus = nullptr
int8_t _last_accel_filter_hz
int8_t _last_gyro_filter_hz
uint8_t _sample_count
Vector3f _accel_filtered
Vector3f _gyro_filtered
float _temp_filtered
LowPassFilter2pVector3f _accel_filter
LowPassFilter2pVector3f _gyro_filter
LowPassFilter2pFloat _temp_filter
volatile uint16_t _sum_count
bool _fifo_mode
uint8_t * _samples = nullptr
Static Private Attributes
static const float _gyro_scale = (0.0174532f / 16.4f)
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
void _set_accel_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
int16_t _product_id
int16_t _id = -1
Detailed Description
Definition at line 47 of file AP_InertialSensor_MPU6000.h.
Constructor & Destructor Documentation
AP_InertialSensor_MPU6000::AP_InertialSensor_MPU6000 (AP_InertialSensor & imu, AP_MPU6000_BusDriver * bus)
Definition at line 437 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _detect().
AP_InertialSensor_MPU6000::~AP_InertialSensor_MPU6000 ()
Definition at line 453 of file AP_InertialSensor_MPU6000.cpp.
Member Function Documentation
void AP_InertialSensor_MPU6000::_accumulate (uint8_t * samples, uint8_t n_samples) private
Definition at line 689 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _read_data_transaction().
bool AP_InertialSensor_MPU6000::_data_ready () private
Return true if the MPU6000 has new data available for reading.
We use the data ready pin if it is available. Otherwise, read the status register.
Definition at line 666 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _hardware_init(), and _poll_data().
AP_InertialSensor_Backend * AP_InertialSensor_MPU6000::_detect (AP_InertialSensor & _imu, AP_MPU6000_BusDriver * bus, int16_t id = -1) static private
Definition at line 483 of file AP_InertialSensor_MPU6000.cpp.
Referenced by detect_i2c(), and detect_spi().
bool AP_InertialSensor_MPU6000::_hardware_init (void) private
Definition at line 803 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _init_sensor().
bool AP_InertialSensor_MPU6000::_init_sensor (void) private
Definition at line 502 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _detect().
void AP_InertialSensor_MPU6000::_poll_data (void) private
Timer process to poll for new data from the MPU6000.
Definition at line 678 of file AP_InertialSensor_MPU6000.cpp.
Referenced by start().
void AP_InertialSensor_MPU6000::_read_block (uint8_t reg, uint8_t * buf, uint32_t size) private
Definition at line 742 of file AP_InertialSensor_MPU6000.cpp.
Referenced by AP_MPU6000_AuxiliaryBusSlave::passthrough_read(), and AP_MPU6000_AuxiliaryBusSlave::read().
void AP_InertialSensor_MPU6000::_read_data_transaction () private
Definition at line 734 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _poll_data().
uint8_t AP_InertialSensor_MPU6000::_register_read (uint8_t reg) private
Definition at line 748 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _data_ready(), _hardware_init(), _register_write_check(), and start().
void AP_InertialSensor_MPU6000::_register_write (uint8_t reg, uint8_t val) private
Definition at line 756 of file AP_InertialSensor_MPU6000.cpp.
Referenced by _hardware_init(), _register_write_check(), _set_filter_register(), AP_MPU6000_AuxiliaryBusSlave::_set_passthrough(), AP_MPU6000_AuxiliaryBusSlave::passthrough_write(), and start().
void AP_InertialSensor_MPU6000::_register_write_check (uint8_t reg, uint8_t val) private
Definition at line 764 of file AP_InertialSensor_MPU6000.cpp.
bool AP_InertialSensor_MPU6000::_sample_available () private
void AP_InertialSensor_MPU6000::_set_filter_register (uint16_t filter_hz) private
Definition at line 780 of file AP_InertialSensor_MPU6000.cpp.
Referenced by start().
bool AP_InertialSensor_MPU6000::accel_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 67 of file AP_InertialSensor_MPU6000.h.
AP_InertialSensor_Backend * AP_InertialSensor_MPU6000::detect_i2c (AP_InertialSensor & _imu, AP_HAL::I2CDriver * i2c, uint8_t addr) static
Definition at line 471 of file AP_InertialSensor_MPU6000.cpp.
Referenced by AP_InertialSensor::detect_backends().
AP_InertialSensor_Backend * AP_InertialSensor_MPU6000::detect_spi (AP_InertialSensor & _imu) static
Definition at line 462 of file AP_InertialSensor_MPU6000.cpp.
Referenced by AP_InertialSensor::detect_backends().
static AP_InertialSensor_MPU6000& AP_InertialSensor_MPU6000::from (AP_InertialSensor_Backend & backend) inline static
Definition at line 59 of file AP_InertialSensor_MPU6000.h.
Referenced by AP_MPU6000_AuxiliaryBus::_configure_slaves(), AP_MPU6000_AuxiliaryBusSlave::_set_passthrough(), AP_MPU6000_AuxiliaryBusSlave::passthrough_read(), AP_MPU6000_AuxiliaryBusSlave::passthrough_write(), and AP_MPU6000_AuxiliaryBusSlave::read().
AuxiliaryBus * AP_InertialSensor_MPU6000::get_auxiliary_bus () override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 647 of file AP_InertialSensor_MPU6000.cpp.
bool AP_InertialSensor_MPU6000::gyro_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 66 of file AP_InertialSensor_MPU6000.h.
void AP_InertialSensor_MPU6000::start () override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 522 of file AP_InertialSensor_MPU6000.cpp.
bool AP_InertialSensor_MPU6000::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 609 of file AP_InertialSensor_MPU6000.cpp.
Member Data Documentation
LowPassFilter2pVector3f AP_InertialSensor_MPU6000::_accel_filter private
Definition at line 123 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), and update().
Vector3f AP_InertialSensor_MPU6000::_accel_filtered private
Definition at line 118 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), and update().
uint8_t AP_InertialSensor_MPU6000::_accel_instance private
Definition at line 87 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), start(), and update().
AP_MPU6000_AuxiliaryBus* AP_InertialSensor_MPU6000::_auxiliary_bus = nullptr private
Definition at line 105 of file AP_InertialSensor_MPU6000.h.
Referenced by get_auxiliary_bus(), and ~AP_InertialSensor_MPU6000().
AP_MPU6000_BusDriver* AP_InertialSensor_MPU6000::_bus private
Definition at line 102 of file AP_InertialSensor_MPU6000.h.
Referenced by _hardware_init(), _init_sensor(), _read_block(), _read_data_transaction(), _register_read(), _register_write(), get_auxiliary_bus(), start(), and ~AP_InertialSensor_MPU6000().
AP_HAL::Semaphore* AP_InertialSensor_MPU6000::_bus_sem private
Definition at line 103 of file AP_InertialSensor_MPU6000.h.
Referenced by _hardware_init(), _init_sensor(), _poll_data(), and start().
AP_HAL::DigitalSource* AP_InertialSensor_MPU6000::_drdy_pin private
Definition at line 89 of file AP_InertialSensor_MPU6000.h.
Referenced by _data_ready(), _init_sensor(), and _read_data_transaction().
bool AP_InertialSensor_MPU6000::_fifo_mode private
Definition at line 128 of file AP_InertialSensor_MPU6000.h.
Referenced by _poll_data(), and start().
LowPassFilter2pVector3f AP_InertialSensor_MPU6000::_gyro_filter private
Definition at line 124 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), and update().
Vector3f AP_InertialSensor_MPU6000::_gyro_filtered private
Definition at line 119 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), and update().
uint8_t AP_InertialSensor_MPU6000::_gyro_instance private
Definition at line 86 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), start(), and update().
const float AP_InertialSensor_MPU6000::_gyro_scale = (0.0174532f / 16.4f) static private
Definition at line 107 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate().
int8_t AP_InertialSensor_MPU6000::_last_accel_filter_hz private
Definition at line 110 of file AP_InertialSensor_MPU6000.h.
Referenced by update().
int8_t AP_InertialSensor_MPU6000::_last_gyro_filter_hz private
Definition at line 111 of file AP_InertialSensor_MPU6000.h.
Referenced by update().
uint8_t AP_InertialSensor_MPU6000::_sample_count private
Definition at line 116 of file AP_InertialSensor_MPU6000.h.
Referenced by accel_sample_available(), gyro_sample_available(), and start().
uint8_t* AP_InertialSensor_MPU6000::_samples = nullptr private
Definition at line 129 of file AP_InertialSensor_MPU6000.h.
Referenced by _read_data_transaction(), start(), and ~AP_InertialSensor_MPU6000().
volatile uint16_t AP_InertialSensor_MPU6000::_sum_count private
Definition at line 127 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), accel_sample_available(), gyro_sample_available(), and update().
LowPassFilter2pFloat AP_InertialSensor_MPU6000::_temp_filter private
Definition at line 125 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate().
float AP_InertialSensor_MPU6000::_temp_filtered private
Definition at line 120 of file AP_InertialSensor_MPU6000.h.
Referenced by _accumulate(), and update().
friend AP_InertialSensor_MPU6000::AP_MPU6000_AuxiliaryBus private
Definition at line 49 of file AP_InertialSensor_MPU6000.h.
Referenced by get_auxiliary_bus().
friend AP_InertialSensor_MPU6000::AP_MPU6000_AuxiliaryBusSlave private
Definition at line 50 of file AP_InertialSensor_MPU6000.h.
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_MPU6000.h
libraries/AP_InertialSensor/AP_InertialSensor_MPU6000.cpp