APM:Libraries: AP_ADC_AnalogSource Class Reference
AP_ADC_AnalogSource Class Reference
#include <AP_ADC_AnalogSource.h>
Public Member Functions
AP_ADC_AnalogSource (AP_ADC *adc, uint8_t ch, float prescale=1.0)
float read_average (void)
float read_latest (void)
void set_pin (uint8_t)
float voltage_average ()
float voltage_latest ()
float voltage_average_ratiometric ()
void set_stop_pin (uint8_t p)
void set_settle_time (uint16_t settle_time_ms)
Private Attributes
AP_ADC * _adc
uint8_t _ch
float _prescale
Detailed Description
Definition at line 8 of file AP_ADC_AnalogSource.h.
Constructor & Destructor Documentation
AP_ADC_AnalogSource::AP_ADC_AnalogSource (AP_ADC * adc, uint8_t ch, float prescale = 1.0) inline
Definition at line 11 of file AP_ADC_AnalogSource.h.
Member Function Documentation
float AP_ADC_AnalogSource::read_average (void) virtual
Implements AP_HAL::AnalogSource.
Definition at line 14 of file AP_ADC_AnalogSource.cpp.
Referenced by read_latest().
float AP_ADC_AnalogSource::read_latest (void) virtual
Implements AP_HAL::AnalogSource.
Definition at line 10 of file AP_ADC_AnalogSource.cpp.
void AP_ADC_AnalogSource::set_pin (uint8_t machtnichts) virtual
Implements AP_HAL::AnalogSource.
Definition at line 31 of file AP_ADC_AnalogSource.cpp.
void AP_ADC_AnalogSource::set_settle_time (uint16_t settle_time_ms) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 23 of file AP_ADC_AnalogSource.h.
void AP_ADC_AnalogSource::set_stop_pin (uint8_t p) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 22 of file AP_ADC_AnalogSource.h.
float AP_ADC_AnalogSource::voltage_average (void) virtual
Implements AP_HAL::AnalogSource.
Definition at line 23 of file AP_ADC_AnalogSource.cpp.
Referenced by voltage_average_ratiometric(), and voltage_latest().
float AP_ADC_AnalogSource::voltage_average_ratiometric (void) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 19 of file AP_ADC_AnalogSource.h.
float AP_ADC_AnalogSource::voltage_latest (void) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 18 of file AP_ADC_AnalogSource.h.
Member Data Documentation
AP_ADC* AP_ADC_AnalogSource::_adc private
Definition at line 26 of file AP_ADC_AnalogSource.h.
Referenced by read_average(), and voltage_average().
uint8_t AP_ADC_AnalogSource::_ch private
Definition at line 27 of file AP_ADC_AnalogSource.h.
Referenced by read_average(), and voltage_average().
float AP_ADC_AnalogSource::_prescale private
Definition at line 28 of file AP_ADC_AnalogSource.h.
Referenced by read_average().
The documentation for this class was generated from the following files:
libraries/AP_ADC_AnalogSource/AP_ADC_AnalogSource.h
libraries/AP_ADC_AnalogSource/AP_ADC_AnalogSource.cpp