APM:Libraries: HALSITL::SITL_State Class Reference
HALSITL::SITL_State Class Reference
#include <SITL_State.h>
Classes
struct gps_data
struct readings_baro
struct readings_mag
struct readings_wind
Public Types
enum vehicle_type { ArduCopter, APMrover2, ArduPlane }
Public Member Functions
void init (int argc, char *const argv[])
int gps_pipe (void)
int gps2_pipe (void)
ssize_t gps_read (int fd, void *buf, size_t count)
void loop_hook (void)
uint16_t base_port (void) const
const char * get_client_address (void) const
Public Attributes
uint16_t pwm_output [SITL_NUM_CHANNELS]
uint16_t last_pwm_output [SITL_NUM_CHANNELS]
uint16_t pwm_input [8]
bool new_rc_input
uint16_t sonar_pin_value
uint16_t airspeed_pin_value
uint16_t voltage_pin_value
uint16_t current_pin_value
const char * _uart_path [5]
Private Member Functions
void _parse_command_line (int argc, char *const argv[])
void _set_param_default (const char *parm)
void _usage (void)
void _sitl_setup (void)
void _setup_fdm (void)
void _setup_timer (void)
void _setup_adc (void)
float height_agl (void)
void _update_barometer (float height)
void _update_compass (float rollDeg, float pitchDeg, float yawDeg)
void _update_flow (void)
void _gps_write (const uint8_t *p, uint16_t size)
void _gps_send_ubx (uint8_t msgid, uint8_t *buf, uint16_t size)
void _update_gps_ubx (const struct gps_data *d)
void _update_gps_mtk (const struct gps_data *d)
void _update_gps_mtk16 (const struct gps_data *d)
void _update_gps_mtk19 (const struct gps_data *d)
uint16_t _gps_nmea_checksum (const char *s)
void _gps_nmea_printf (const char *fmt,...)
void _update_gps_nmea (const struct gps_data *d)
void _sbp_send_message (uint16_t msg_type, uint16_t sender_id, uint8_t len, uint8_t *payload)
void _update_gps_sbp (const struct gps_data *d)
void _update_gps_file (const struct gps_data *d)
void _update_gps (double latitude, double longitude, float altitude, double speedN, double speedE, double speedD, bool have_lock)
void _update_ins (float roll, float pitch, float yaw, double rollRate, double pitchRate, double yawRate, double xAccel, double yAccel, double zAccel, float airspeed, float altitude)
void _fdm_input (void)
void _fdm_input_local (void)
void _simulator_servos (SITL::Aircraft::sitl_input &input)
void _simulator_output (bool synthetic_clock_mode)
void _apply_servo_filter (float deltat)
uint16_t _airspeed_sensor (float airspeed)
uint16_t _ground_sonar ()
float _gyro_drift (void)
float _rand_float (void)
Vector3f _rand_vec3f (void)
void _fdm_input_step (void)
void wait_clock (uint64_t wait_time_usec)
void _fdm_thread (void)
Private Attributes
gps_data _gps_data [MAX_GPS_DELAY]
bool _gps_has_basestation_position
gps_data _gps_basestation_data
pthread_t _fdm_thread_ctx
enum vehicle_type _vehicle
uint16_t _framerate
uint8_t _instance
uint16_t _base_port
struct sockaddr_in _rcout_addr
pid_t _parent_pid
uint32_t _update_count
bool _motors_on
AP_Baro * _barometer
AP_InertialSensor * _ins
SITLScheduler * _scheduler
Compass * _compass
OpticalFlow * _optical_flow
AP_Terrain * _terrain
int _sitl_fd
SITL::SITL * _sitl
uint16_t _rcout_port
uint16_t _simin_port
float _current
bool _synthetic_clock_mode
const char * _fdm_address
uint8_t store_index_mag
uint32_t last_store_time_mag
VectorN< readings_mag, mag_buffer_length > buffer_mag
uint32_t time_delta_mag
uint32_t delayed_time_mag
uint8_t store_index_wind
uint32_t last_store_time_wind
VectorN< readings_wind, wind_buffer_length > buffer_wind
uint32_t time_delta_wind
uint32_t delayed_time_wind
uint8_t store_index_baro
uint32_t last_store_time_baro
VectorN< readings_baro, baro_buffer_length > buffer_baro
uint32_t time_delta_baro
uint32_t delayed_time_baro
SITL::Aircraft * sitl_model
bool enable_gimbal
SITL::Gimbal * gimbal
const char * _client_address
Static Private Attributes
static const uint8_t mag_buffer_length = 250
static const uint8_t wind_buffer_length = 50
static const uint8_t baro_buffer_length = 50
Friends
class HALSITL::SITLScheduler
Detailed Description
Definition at line 29 of file SITL_State.h.
Member Enumeration Documentation
enum HALSITL::SITL_State::vehicle_type
Enumerator
ArduCopter
APMrover2
ArduPlane
Definition at line 34 of file SITL_State.h.
Member Function Documentation
uint16_t SITL_State::_airspeed_sensor (float airspeed) private
Definition at line 34 of file sitl_ins.cpp.
Referenced by _update_ins().
void SITL_State::_apply_servo_filter (float deltat) private
Definition at line 335 of file SITL_State.cpp.
void SITL_State::_fdm_input (void) private
Definition at line 226 of file SITL_State.cpp.
void SITL_State::_fdm_input_local (void) private
Definition at line 303 of file SITL_State.cpp.
void SITL_State::_fdm_input_step (void) private
Definition at line 146 of file SITL_State.cpp.
void HALSITL::SITL_State::_fdm_thread (void) private
uint16_t SITL_State::_gps_nmea_checksum (const char * s) private
Definition at line 486 of file sitl_gps.cpp.
Referenced by _gps_nmea_printf().
void SITL_State::_gps_nmea_printf (const char * fmt, ...) private
Definition at line 499 of file sitl_gps.cpp.
Referenced by _update_gps_nmea().
void SITL_State::_gps_send_ubx (uint8_t msgid, uint8_t * buf, uint16_t size) private
Definition at line 127 of file sitl_gps.cpp.
Referenced by _update_gps_ubx().
void SITL_State::_gps_write (const uint8_t * p, uint16_t size) private
Definition at line 105 of file sitl_gps.cpp.
Referenced by _gps_nmea_printf(), _gps_send_ubx(), _sbp_send_message(), _update_gps_file(), _update_gps_mtk(), _update_gps_mtk16(), and _update_gps_mtk19().
uint16_t SITL_State::_ground_sonar (void) private
Definition at line 98 of file sitl_ins.cpp.
Referenced by _update_ins().
float SITL_State::_gyro_drift (void) private
Definition at line 80 of file sitl_ins.cpp.
Referenced by _update_ins().
void SITL_State::_parse_command_line (int argc, char *const argv[]) private
Definition at line 80 of file SITL_cmdline.cpp.
float SITL_State::_rand_float (void) private
Definition at line 504 of file SITL_State.cpp.
Referenced by _ground_sonar(), _update_barometer(), and _update_ins().
Vector3f SITL_State::_rand_vec3f (void) private
Definition at line 510 of file SITL_State.cpp.
Referenced by _update_compass().
void SITL_State::_sbp_send_message (uint16_t msg_type, uint16_t sender_id, uint8_t len, uint8_t * payload) private
Definition at line 577 of file sitl_gps.cpp.
Referenced by _update_gps_sbp().
void SITL_State::_set_param_default (const char * parm) private
Definition at line 27 of file SITL_State.cpp.
void HALSITL::SITL_State::_setup_adc (void) private
void SITL_State::_setup_fdm (void) private
Definition at line 109 of file SITL_State.cpp.
void HALSITL::SITL_State::_setup_timer (void) private
void SITL_State::_simulator_output (bool synthetic_clock_mode) private
Definition at line 462 of file SITL_State.cpp.
void SITL_State::_simulator_servos (SITL::Aircraft::sitl_input & input) private
Definition at line 360 of file SITL_State.cpp.
void SITL_State::_sitl_setup (void) private
Definition at line 63 of file SITL_State.cpp.
void SITL_State::_update_barometer (float height) private
Definition at line 30 of file sitl_barometer.cpp.
void SITL_State::_update_compass (float rollDeg, float pitchDeg, float yawDeg) private
Definition at line 29 of file sitl_compass.cpp.
void SITL_State::_update_flow (void) private
Definition at line 34 of file sitl_optical_flow.cpp.
void SITL_State::_update_gps (double latitude, double longitude, float altitude, double speedN, double speedE, double speedD, bool have_lock) private
Definition at line 733 of file sitl_gps.cpp.
void SITL_State::_update_gps_file (const struct gps_data * d) private
Definition at line 709 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_gps_mtk (const struct gps_data * d) private
Definition at line 313 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_gps_mtk16 (const struct gps_data * d) private
Definition at line 370 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_gps_mtk19 (const struct gps_data * d) private
Definition at line 428 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_gps_nmea (const struct gps_data * d) private
Definition at line 521 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_gps_sbp (const struct gps_data * d) private
Definition at line 601 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_gps_ubx (const struct gps_data * d) private
Definition at line 167 of file sitl_gps.cpp.
Referenced by _update_gps().
void SITL_State::_update_ins (float roll, float pitch, float yaw, double rollRate, double pitchRate, double yawRate, double xAccel, double yAccel, double zAccel, float airspeed, float altitude) private
Definition at line 149 of file sitl_ins.cpp.
void SITL_State::_usage (void) private
Definition at line 38 of file SITL_cmdline.cpp.
uint16_t HALSITL::SITL_State::base_port (void) const inline
Definition at line 48 of file SITL_State.h.
Referenced by HALSITL::SITLUARTDriver::_tcp_start_connection().
const char* HALSITL::SITL_State::get_client_address (void) const inline
Definition at line 59 of file SITL_State.h.
int SITL_State::gps2_pipe (void)
Definition at line 87 of file sitl_gps.cpp.
Referenced by HALSITL::SITLUARTDriver::begin().
int SITL_State::gps_pipe (void)
Definition at line 69 of file sitl_gps.cpp.
Referenced by HALSITL::SITLUARTDriver::begin().
ssize_t SITL_State::gps_read (int fd, void * buf, size_t count)
Definition at line 50 of file sitl_gps.cpp.
Referenced by HALSITL::SITLUARTDriver::read().
float SITL_State::height_agl (void) private
Definition at line 535 of file SITL_State.cpp.
Referenced by _ground_sonar(), and _update_flow().
void SITL_State::init (int argc, char *const argv[])
Definition at line 522 of file SITL_State.cpp.
Referenced by HAL_SITL::run().
void HALSITL::SITL_State::loop_hook (void)
void SITL_State::wait_clock (uint64_t wait_time_usec) private
Definition at line 215 of file SITL_State.cpp.
Referenced by HALSITL::SITLScheduler::delay_microseconds().
Friends And Related Function Documentation
friend class HALSITL::SITLScheduler friend
Definition at line 30 of file SITL_State.h.
Member Data Documentation
AP_Baro* HALSITL::SITL_State::_barometer private
Definition at line 146 of file SITL_State.h.
Referenced by _update_barometer().
uint16_t HALSITL::SITL_State::_base_port private
Definition at line 140 of file SITL_State.h.
Referenced by base_port().
const char* HALSITL::SITL_State::_client_address private
Definition at line 209 of file SITL_State.h.
Referenced by get_client_address().
Compass* HALSITL::SITL_State::_compass private
Definition at line 149 of file SITL_State.h.
Referenced by _update_compass().
float HALSITL::SITL_State::_current private
Definition at line 157 of file SITL_State.h.
Referenced by _update_compass().
const char* HALSITL::SITL_State::_fdm_address private
Definition at line 161 of file SITL_State.h.
pthread_t HALSITL::SITL_State::_fdm_thread_ctx private
Definition at line 133 of file SITL_State.h.
uint16_t HALSITL::SITL_State::_framerate private
Definition at line 138 of file SITL_State.h.
gps_data HALSITL::SITL_State::_gps_basestation_data private
Definition at line 98 of file SITL_State.h.
Referenced by _update_gps().
gps_data HALSITL::SITL_State::_gps_data[MAX_GPS_DELAY] private
Definition at line 95 of file SITL_State.h.
Referenced by _update_gps().
bool HALSITL::SITL_State::_gps_has_basestation_position private
Definition at line 97 of file SITL_State.h.
Referenced by _update_gps().
AP_InertialSensor* HALSITL::SITL_State::_ins private
Definition at line 147 of file SITL_State.h.
Referenced by _update_ins().
uint8_t HALSITL::SITL_State::_instance private
Definition at line 139 of file SITL_State.h.
bool HALSITL::SITL_State::_motors_on private
Definition at line 144 of file SITL_State.h.
Referenced by _update_ins().
OpticalFlow* HALSITL::SITL_State::_optical_flow private
Definition at line 150 of file SITL_State.h.
Referenced by _update_flow().
pid_t HALSITL::SITL_State::_parent_pid private
Definition at line 142 of file SITL_State.h.
struct sockaddr_in HALSITL::SITL_State::_rcout_addr private
Definition at line 141 of file SITL_State.h.
uint16_t HALSITL::SITL_State::_rcout_port private
Definition at line 155 of file SITL_State.h.
SITLScheduler* HALSITL::SITL_State::_scheduler private
Definition at line 148 of file SITL_State.h.
Referenced by _gyro_drift(), gps2_pipe(), and gps_pipe().
uint16_t HALSITL::SITL_State::_simin_port private
Definition at line 156 of file SITL_State.h.
SITL::SITL* HALSITL::SITL_State::_sitl private
Definition at line 154 of file SITL_State.h.
Referenced by _airspeed_sensor(), _gps_write(), _ground_sonar(), _gyro_drift(), _update_barometer(), _update_compass(), _update_flow(), _update_gps(), _update_gps_mtk(), _update_gps_mtk16(), _update_gps_mtk19(), _update_gps_nmea(), _update_gps_sbp(), _update_gps_ubx(), _update_ins(), and HALSITL::SITLScheduler::system_initialized().
int HALSITL::SITL_State::_sitl_fd private
Definition at line 153 of file SITL_State.h.
bool HALSITL::SITL_State::_synthetic_clock_mode private
Definition at line 159 of file SITL_State.h.
AP_Terrain* HALSITL::SITL_State::_terrain private
Definition at line 151 of file SITL_State.h.
const char* HALSITL::SITL_State::_uart_path[5]
Initial value:
{
        "tcp:0:wait",
        "GPS1",
        "tcp:2",
        "tcp:3",
        "GPS2"
    }
Definition at line 62 of file SITL_State.h.
Referenced by HALSITL::SITLUARTDriver::begin().
uint32_t HALSITL::SITL_State::_update_count private
Definition at line 143 of file SITL_State.h.
enum vehicle_type HALSITL::SITL_State::_vehicle private
Definition at line 137 of file SITL_State.h.
uint16_t HALSITL::SITL_State::airspeed_pin_value
Definition at line 54 of file SITL_State.h.
Referenced by _update_ins(), and HALSITL::ADCSource::read_latest().
const uint8_t HALSITL::SITL_State::baro_buffer_length = 50 static private
Definition at line 166 of file SITL_State.h.
Referenced by _update_barometer().
VectorN<readings_baro,baro_buffer_length> HALSITL::SITL_State::buffer_baro private
Definition at line 197 of file SITL_State.h.
Referenced by _update_barometer().
VectorN<readings_mag,mag_buffer_length> HALSITL::SITL_State::buffer_mag private
Definition at line 175 of file SITL_State.h.
Referenced by _update_compass().
VectorN<readings_wind,wind_buffer_length> HALSITL::SITL_State::buffer_wind private
Definition at line 186 of file SITL_State.h.
Referenced by _airspeed_sensor().
uint16_t HALSITL::SITL_State::current_pin_value
Definition at line 56 of file SITL_State.h.
Referenced by HALSITL::ADCSource::read_latest().
uint32_t HALSITL::SITL_State::delayed_time_baro private
Definition at line 199 of file SITL_State.h.
Referenced by _update_barometer().
uint32_t HALSITL::SITL_State::delayed_time_mag private
Definition at line 177 of file SITL_State.h.
Referenced by _update_compass().
uint32_t HALSITL::SITL_State::delayed_time_wind private
Definition at line 188 of file SITL_State.h.
Referenced by _airspeed_sensor().
bool HALSITL::SITL_State::enable_gimbal private
Definition at line 205 of file SITL_State.h.
SITL::Gimbal* HALSITL::SITL_State::gimbal private
Definition at line 206 of file SITL_State.h.
uint16_t HALSITL::SITL_State::last_pwm_output[SITL_NUM_CHANNELS]
Definition at line 44 of file SITL_State.h.
uint32_t HALSITL::SITL_State::last_store_time_baro private
Definition at line 196 of file SITL_State.h.
Referenced by _update_barometer().
uint32_t HALSITL::SITL_State::last_store_time_mag private
Definition at line 174 of file SITL_State.h.
Referenced by _update_compass().
uint32_t HALSITL::SITL_State::last_store_time_wind private
Definition at line 185 of file SITL_State.h.
Referenced by _airspeed_sensor().
const uint8_t HALSITL::SITL_State::mag_buffer_length = 250 static private
Definition at line 164 of file SITL_State.h.
Referenced by _update_compass().
bool HALSITL::SITL_State::new_rc_input
Definition at line 46 of file SITL_State.h.
Referenced by HALSITL::SITLRCInput::new_input().
uint16_t HALSITL::SITL_State::pwm_input[8]
Definition at line 45 of file SITL_State.h.
Referenced by HALSITL::SITLRCInput::read().
uint16_t HALSITL::SITL_State::pwm_output[SITL_NUM_CHANNELS]
Definition at line 43 of file SITL_State.h.
Referenced by HALSITL::SITLRCOutput::read(), and HALSITL::SITLRCOutput::write().
SITL::Aircraft* HALSITL::SITL_State::sitl_model private
Definition at line 202 of file SITL_State.h.
uint16_t HALSITL::SITL_State::sonar_pin_value
Definition at line 53 of file SITL_State.h.
Referenced by _update_ins(), and HALSITL::ADCSource::read_latest().
uint8_t HALSITL::SITL_State::store_index_baro private
Definition at line 195 of file SITL_State.h.
Referenced by _update_barometer().
uint8_t HALSITL::SITL_State::store_index_mag private
Definition at line 173 of file SITL_State.h.
Referenced by _update_compass().
uint8_t HALSITL::SITL_State::store_index_wind private
Definition at line 184 of file SITL_State.h.
Referenced by _airspeed_sensor().
uint32_t HALSITL::SITL_State::time_delta_baro private
Definition at line 198 of file SITL_State.h.
Referenced by _update_barometer().
uint32_t HALSITL::SITL_State::time_delta_mag private
Definition at line 176 of file SITL_State.h.
Referenced by _update_compass().
uint32_t HALSITL::SITL_State::time_delta_wind private
Definition at line 187 of file SITL_State.h.
Referenced by _airspeed_sensor().
uint16_t HALSITL::SITL_State::voltage_pin_value
Definition at line 55 of file SITL_State.h.
Referenced by HALSITL::ADCSource::read_latest().
const uint8_t HALSITL::SITL_State::wind_buffer_length = 50 static private
Definition at line 165 of file SITL_State.h.
Referenced by _airspeed_sensor().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/SITL_State.h
libraries/AP_HAL_SITL/sitl_barometer.cpp
libraries/AP_HAL_SITL/SITL_cmdline.cpp
libraries/AP_HAL_SITL/sitl_compass.cpp
libraries/AP_HAL_SITL/sitl_gps.cpp
libraries/AP_HAL_SITL/sitl_ins.cpp
libraries/AP_HAL_SITL/sitl_optical_flow.cpp
libraries/AP_HAL_SITL/SITL_State.cpp