APM:Libraries: AuxiliaryBus Class Reference
AuxiliaryBus Class Reference abstract
#include <AuxiliaryBus.h>
Public Member Functions
AP_InertialSensor_Backend & get_backend ()
AuxiliaryBusSlave * request_next_slave (uint8_t addr)
int register_periodic_read (AuxiliaryBusSlave *slave, uint8_t reg, uint8_t size)
virtual AP_HAL::Semaphore * get_semaphore ()=0
Protected Member Functions
AuxiliaryBus (AP_InertialSensor_Backend &backend, uint8_t max_slaves)
virtual ~AuxiliaryBus ()
virtual AuxiliaryBusSlave * _instantiate_slave (uint8_t addr, uint8_t instance)=0
virtual int _configure_periodic_read (AuxiliaryBusSlave *slave, uint8_t reg, uint8_t size)=0
Protected Attributes
uint8_t _n_slaves = 0
const uint8_t _max_slaves
AuxiliaryBusSlave ** _slaves
AP_InertialSensor_Backend & _ins_backend
Friends
class AP_InertialSensor_Backend
Detailed Description
Definition at line 95 of file AuxiliaryBus.h.
Constructor & Destructor Documentation
AuxiliaryBus::AuxiliaryBus (AP_InertialSensor_Backend & backend, uint8_t max_slaves) protected
Definition at line 19 of file AuxiliaryBus.cpp.
AuxiliaryBus::~AuxiliaryBus () protected virtual
Definition at line 26 of file AuxiliaryBus.cpp.
Member Function Documentation
virtual int AuxiliaryBus::_configure_periodic_read (AuxiliaryBusSlave * slave, uint8_t reg, uint8_t size) protected pure virtual
Implemented in AP_MPU6000_AuxiliaryBus, and AP_MPU9250_AuxiliaryBus.
Referenced by register_periodic_read().
virtual AuxiliaryBusSlave* AuxiliaryBus::_instantiate_slave (uint8_t addr, uint8_t instance) protected pure virtual
Implemented in AP_MPU6000_AuxiliaryBus, and AP_MPU9250_AuxiliaryBus.
Referenced by request_next_slave().
AP_InertialSensor_Backend& AuxiliaryBus::get_backend () inline
Definition at line 100 of file AuxiliaryBus.h.
Referenced by AP_MPU9250_AuxiliaryBusSlave::_set_passthrough(), AP_MPU6000_AuxiliaryBusSlave::_set_passthrough(), AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), AP_MPU6000_AuxiliaryBusSlave::passthrough_read(), AP_MPU9250_AuxiliaryBusSlave::passthrough_write(), AP_MPU6000_AuxiliaryBusSlave::passthrough_write(), AP_MPU9250_AuxiliaryBusSlave::read(), and AP_MPU6000_AuxiliaryBusSlave::read().
virtual AP_HAL::Semaphore* AuxiliaryBus::get_semaphore () pure virtual
Implemented in AP_MPU6000_AuxiliaryBus, and AP_MPU9250_AuxiliaryBus.
Referenced by AP_AK8963_SerialBus_MPU9250::get_semaphore(), and AP_HMC5843_SerialBus_MPU6000::get_semaphore().
int AuxiliaryBus::register_periodic_read (AuxiliaryBusSlave * slave, uint8_t reg, uint8_t size)
Definition at line 85 of file AuxiliaryBus.cpp.
Referenced by AP_AK8963_SerialBus_MPU9250::start_measurements(), and AP_HMC5843_SerialBus_MPU6000::start_measurements().
AuxiliaryBusSlave * AuxiliaryBus::request_next_slave (uint8_t addr)
Definition at line 47 of file AuxiliaryBus.cpp.
Referenced by AP_AK8963_SerialBus_MPU9250::AP_AK8963_SerialBus_MPU9250(), and AP_HMC5843_SerialBus_MPU6000::AP_HMC5843_SerialBus_MPU6000().
Friends And Related Function Documentation
friend class AP_InertialSensor_Backend friend
Definition at line 97 of file AuxiliaryBus.h.
Member Data Documentation
AP_InertialSensor_Backend& AuxiliaryBus::_ins_backend protected
Definition at line 129 of file AuxiliaryBus.h.
Referenced by AP_MPU9250_AuxiliaryBus::_configure_slaves(), AP_MPU6000_AuxiliaryBus::_configure_slaves(), get_backend(), AP_MPU9250_AuxiliaryBus::get_semaphore(), and AP_MPU6000_AuxiliaryBus::get_semaphore().
const uint8_t AuxiliaryBus::_max_slaves protected
Definition at line 127 of file AuxiliaryBus.h.
Referenced by register_periodic_read(), and request_next_slave().
uint8_t AuxiliaryBus::_n_slaves = 0 protected
Definition at line 126 of file AuxiliaryBus.h.
Referenced by register_periodic_read(), request_next_slave(), and ~AuxiliaryBus().
AuxiliaryBusSlave** AuxiliaryBus::_slaves protected
Definition at line 128 of file AuxiliaryBus.h.
Referenced by AuxiliaryBus(), register_periodic_read(), and ~AuxiliaryBus().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AuxiliaryBus.h
libraries/AP_InertialSensor/AuxiliaryBus.cpp