APM:Libraries: AP_Frsky_Telem Class Reference
AP_Frsky_Telem Class Reference
#include <AP_Frsky_Telem.h>
Public Types
enum FrSkyProtocol { FrSkyUnknown = 0, FrSkyDPORT = 2, FrSkySPORT = 3 }
Public Member Functions
AP_Frsky_Telem (AP_AHRS &ahrs, AP_BattMonitor &battery)
void init (const AP_SerialManager &serial_manager)
void send_frames (uint8_t control_mode)
Private Member Functions
void init_uart_for_sport ()
void send_hub_frame ()
void sport_tick ()
void calc_crc (uint8_t byte)
void send_crc ()
void frsky_send_byte (uint8_t value)
void frsky_send_hub_startstop ()
void frsky_send_sport_prim ()
void frsky_send_data (uint8_t id, int16_t data)
void calc_baro_alt ()
float frsky_format_gps (float dec)
void calc_gps_position ()
void calc_battery ()
void calc_gps_sats ()
void send_gps_sats (void)
void send_mode (void)
void send_baro_alt_m (void)
void send_baro_alt_cm (void)
void send_batt_remain (void)
void send_batt_volts (void)
void send_current (void)
void send_prearm_error (void)
void send_heading (void)
void send_gps_lat_dd (void)
void send_gps_lat_mm (void)
void send_gps_lat_ns (void)
void send_gps_lon_dd (void)
void send_gps_lon_mm (void)
void send_gps_lon_ew (void)
void send_gps_speed_meter (void)
void send_gps_speed_cm (void)
void send_gps_alt_meter (void)
void send_gps_alt_cm (void)
Private Attributes
AP_AHRS & _ahrs
AP_BattMonitor & _battery
AP_HAL::UARTDriver * _port
bool _initialised_uart
enum FrSkyProtocol _protocol
uint16_t _crc
uint32_t _last_frame1_ms
uint32_t _last_frame2_ms
bool _battery_data_ready
uint16_t _batt_remaining
uint16_t _batt_volts
uint16_t _batt_amps
bool _sats_data_ready
uint16_t gps_sats
bool _gps_data_ready
bool _pos_gps_ok
uint16_t _course_in_degrees
char _lat_ns
char _lon_ew
uint16_t _latdddmm
uint16_t _latmmmm
uint16_t _londddmm
uint16_t _lonmmmm
uint16_t _alt_gps_meters
uint16_t _alt_gps_cm
int16_t _speed_in_meter
uint16_t _speed_in_centimeter
bool _baro_data_ready
int16_t _baro_alt_meters
uint16_t _baro_alt_cm
bool _mode_data_ready
uint8_t _mode
uint8_t _fas_call
uint8_t _gps_call
uint8_t _vario_call
uint8_t _various_call
uint8_t _sport_status
Detailed Description
Definition at line 73 of file AP_Frsky_Telem.h.
Member Enumeration Documentation
enum AP_Frsky_Telem::FrSkyProtocol
Enumerator
FrSkyUnknown
FrSkyDPORT
FrSkySPORT
Definition at line 80 of file AP_Frsky_Telem.h.
Constructor & Destructor Documentation
AP_Frsky_Telem::AP_Frsky_Telem (AP_AHRS & ahrs, AP_BattMonitor & battery)
Definition at line 27 of file AP_Frsky_Telem.cpp.
Member Function Documentation
void AP_Frsky_Telem::calc_baro_alt () private
Definition at line 452 of file AP_Frsky_Telem.cpp.
Referenced by send_frames(), and send_hub_frame().
void AP_Frsky_Telem::calc_battery () private
Definition at line 530 of file AP_Frsky_Telem.cpp.
Referenced by send_frames(), and send_hub_frame().
void AP_Frsky_Telem::calc_crc (uint8_t byte) private
Definition at line 338 of file AP_Frsky_Telem.cpp.
Referenced by frsky_send_byte().
void AP_Frsky_Telem::calc_gps_position () private
Definition at line 484 of file AP_Frsky_Telem.cpp.
Referenced by send_frames(), and send_hub_frame().
void AP_Frsky_Telem::calc_gps_sats () private
Definition at line 540 of file AP_Frsky_Telem.cpp.
Referenced by send_frames(), and send_hub_frame().
float AP_Frsky_Telem::frsky_format_gps (float dec) private
Formats the decimal latitude/longitude to the required degrees/minutes.
Definition at line 474 of file AP_Frsky_Telem.cpp.
Referenced by calc_gps_position().
void AP_Frsky_Telem::frsky_send_byte (uint8_t value) private
Definition at line 361 of file AP_Frsky_Telem.cpp.
Referenced by frsky_send_data(), frsky_send_sport_prim(), and send_crc().
void AP_Frsky_Telem::frsky_send_data (uint8_t id, int16_t data) private
Sends one data id/value pair.
Definition at line 422 of file AP_Frsky_Telem.cpp.
Referenced by send_baro_alt_cm(), send_baro_alt_m(), send_batt_remain(), send_batt_volts(), send_current(), send_gps_alt_cm(), send_gps_alt_meter(), send_gps_lat_dd(), send_gps_lat_mm(), send_gps_lat_ns(), send_gps_lon_dd(), send_gps_lon_ew(), send_gps_lon_mm(), send_gps_sats(), send_gps_speed_cm(), send_gps_speed_meter(), send_heading(), and send_mode().
void AP_Frsky_Telem::frsky_send_hub_startstop () private
Sends a 0x5E start/stop byte.
Definition at line 403 of file AP_Frsky_Telem.cpp.
Referenced by frsky_send_data().
void AP_Frsky_Telem::frsky_send_sport_prim () private
Definition at line 412 of file AP_Frsky_Telem.cpp.
Referenced by frsky_send_data().
void AP_Frsky_Telem::init (const AP_SerialManager & serial_manager)
Definition at line 68 of file AP_Frsky_Telem.cpp.
void AP_Frsky_Telem::init_uart_for_sport () private
Definition at line 140 of file AP_Frsky_Telem.cpp.
Referenced by sport_tick().
void AP_Frsky_Telem::send_baro_alt_cm (void) private
Definition at line 574 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_baro_alt_m (void) private
Definition at line 566 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_batt_remain (void) private
Definition at line 582 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame().
void AP_Frsky_Telem::send_batt_volts (void) private
Definition at line 590 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_crc () private
Definition at line 350 of file AP_Frsky_Telem.cpp.
Referenced by frsky_send_data().
void AP_Frsky_Telem::send_current (void) private
Definition at line 598 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_frames (uint8_t control_mode)
Definition at line 101 of file AP_Frsky_Telem.cpp.
void AP_Frsky_Telem::send_gps_alt_cm (void) private
Definition at line 686 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_alt_meter (void) private
Definition at line 678 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_lat_dd (void) private
Definition at line 614 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_lat_mm (void) private
Definition at line 622 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_lat_ns (void) private
Definition at line 630 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_lon_dd (void) private
Definition at line 638 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_lon_ew (void) private
Definition at line 654 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_lon_mm (void) private
Definition at line 646 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_sats (void) private
Definition at line 550 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_speed_cm (void) private
Definition at line 670 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_gps_speed_meter (void) private
Definition at line 662 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_heading (void) private
Definition at line 606 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_hub_frame () private
Definition at line 157 of file AP_Frsky_Telem.cpp.
Referenced by send_frames().
void AP_Frsky_Telem::send_mode (void) private
Definition at line 558 of file AP_Frsky_Telem.cpp.
Referenced by send_hub_frame(), and sport_tick().
void AP_Frsky_Telem::send_prearm_error (void) private
void AP_Frsky_Telem::sport_tick (void) private
Definition at line 201 of file AP_Frsky_Telem.cpp.
Referenced by init().
Member Data Documentation
AP_AHRS& AP_Frsky_Telem::_ahrs private
Definition at line 142 of file AP_Frsky_Telem.h.
Referenced by calc_baro_alt(), calc_gps_position(), and calc_gps_sats().
uint16_t AP_Frsky_Telem::_alt_gps_cm private
Definition at line 169 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_alt_cm().
uint16_t AP_Frsky_Telem::_alt_gps_meters private
Definition at line 168 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_alt_meter().
uint16_t AP_Frsky_Telem::_baro_alt_cm private
Definition at line 175 of file AP_Frsky_Telem.h.
Referenced by calc_baro_alt(), and send_baro_alt_cm().
int16_t AP_Frsky_Telem::_baro_alt_meters private
Definition at line 174 of file AP_Frsky_Telem.h.
Referenced by calc_baro_alt(), and send_baro_alt_m().
bool AP_Frsky_Telem::_baro_data_ready private
Definition at line 173 of file AP_Frsky_Telem.h.
Referenced by init(), send_frames(), and sport_tick().
uint16_t AP_Frsky_Telem::_batt_amps private
Definition at line 155 of file AP_Frsky_Telem.h.
Referenced by calc_battery(), and send_current().
uint16_t AP_Frsky_Telem::_batt_remaining private
Definition at line 153 of file AP_Frsky_Telem.h.
Referenced by calc_battery(), and send_batt_remain().
uint16_t AP_Frsky_Telem::_batt_volts private
Definition at line 154 of file AP_Frsky_Telem.h.
Referenced by calc_battery(), and send_batt_volts().
AP_BattMonitor& AP_Frsky_Telem::_battery private
Definition at line 143 of file AP_Frsky_Telem.h.
Referenced by calc_battery().
bool AP_Frsky_Telem::_battery_data_ready private
Definition at line 152 of file AP_Frsky_Telem.h.
Referenced by init(), send_frames(), and sport_tick().
uint16_t AP_Frsky_Telem::_course_in_degrees private
Definition at line 162 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_heading().
uint16_t AP_Frsky_Telem::_crc private
Definition at line 148 of file AP_Frsky_Telem.h.
Referenced by calc_crc(), and send_crc().
uint8_t AP_Frsky_Telem::_fas_call private
Definition at line 180 of file AP_Frsky_Telem.h.
Referenced by init(), and sport_tick().
uint8_t AP_Frsky_Telem::_gps_call private
Definition at line 181 of file AP_Frsky_Telem.h.
Referenced by init(), and sport_tick().
bool AP_Frsky_Telem::_gps_data_ready private
Definition at line 160 of file AP_Frsky_Telem.h.
Referenced by init(), send_frames(), and sport_tick().
bool AP_Frsky_Telem::_initialised_uart private
Definition at line 145 of file AP_Frsky_Telem.h.
Referenced by init(), init_uart_for_sport(), send_frames(), and sport_tick().
uint32_t AP_Frsky_Telem::_last_frame1_ms private
Definition at line 149 of file AP_Frsky_Telem.h.
Referenced by send_hub_frame().
uint32_t AP_Frsky_Telem::_last_frame2_ms private
Definition at line 150 of file AP_Frsky_Telem.h.
Referenced by send_hub_frame().
char AP_Frsky_Telem::_lat_ns private
Definition at line 163 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_lat_ns().
uint16_t AP_Frsky_Telem::_latdddmm private
Definition at line 164 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_lat_dd().
uint16_t AP_Frsky_Telem::_latmmmm private
Definition at line 165 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_lat_mm().
char AP_Frsky_Telem::_lon_ew private
Definition at line 163 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_lon_ew().
uint16_t AP_Frsky_Telem::_londddmm private
Definition at line 166 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_lon_dd().
uint16_t AP_Frsky_Telem::_lonmmmm private
Definition at line 167 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_lon_mm().
uint8_t AP_Frsky_Telem::_mode private
Definition at line 178 of file AP_Frsky_Telem.h.
Referenced by send_frames(), and send_mode().
bool AP_Frsky_Telem::_mode_data_ready private
Definition at line 177 of file AP_Frsky_Telem.h.
Referenced by init(), send_frames(), and sport_tick().
AP_HAL::UARTDriver* AP_Frsky_Telem::_port private
Definition at line 144 of file AP_Frsky_Telem.h.
Referenced by frsky_send_byte(), frsky_send_hub_startstop(), init(), init_uart_for_sport(), and sport_tick().
bool AP_Frsky_Telem::_pos_gps_ok private
Definition at line 161 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_hub_frame().
enum FrSkyProtocol AP_Frsky_Telem::_protocol private
Definition at line 146 of file AP_Frsky_Telem.h.
Referenced by frsky_send_byte(), frsky_send_data(), init(), init_uart_for_sport(), and send_frames().
bool AP_Frsky_Telem::_sats_data_ready private
Definition at line 157 of file AP_Frsky_Telem.h.
Referenced by init(), send_frames(), and sport_tick().
uint16_t AP_Frsky_Telem::_speed_in_centimeter private
Definition at line 171 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_speed_cm().
int16_t AP_Frsky_Telem::_speed_in_meter private
Definition at line 170 of file AP_Frsky_Telem.h.
Referenced by calc_gps_position(), and send_gps_speed_meter().
uint8_t AP_Frsky_Telem::_sport_status private
Definition at line 185 of file AP_Frsky_Telem.h.
Referenced by init(), and sport_tick().
uint8_t AP_Frsky_Telem::_vario_call private
Definition at line 182 of file AP_Frsky_Telem.h.
Referenced by init(), and sport_tick().
uint8_t AP_Frsky_Telem::_various_call private
Definition at line 183 of file AP_Frsky_Telem.h.
Referenced by init(), and sport_tick().
uint16_t AP_Frsky_Telem::gps_sats private
Definition at line 158 of file AP_Frsky_Telem.h.
Referenced by calc_gps_sats(), and send_gps_sats().
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp