APM:Libraries: AP_MotorsHeli_RSC Class Reference
AP_MotorsHeli_RSC Class Reference
#include <AP_MotorsHeli_RSC.h>
Public Member Functions
AP_MotorsHeli_RSC (RC_Channel &servo_output, int8_t servo_output_channel, uint16_t loop_rate)
void init_servo ()
void set_control_mode (RotorControlMode mode)
void set_critical_speed (int16_t critical_speed)
int16_t get_critical_speed () const
void set_idle_output (int16_t idle_output)
int16_t get_desired_speed () const
void set_desired_speed (int16_t desired_speed)
int16_t get_control_output () const
int16_t get_rotor_speed () const
bool is_runup_complete () const
void set_ramp_time (int8_t ramp_time)
void set_runup_time (int8_t runup_time)
void set_power_output_range (uint16_t power_low, uint16_t power_high)
void set_motor_load (float load)
void recalc_scalers ()
void output (RotorControlState state)
Private Member Functions
void update_rotor_ramp (float rotor_ramp_input)
void update_rotor_runup ()
void write_rsc (int16_t servo_out)
Private Attributes
RC_Channel & _servo_output
int8_t _servo_output_channel
float _loop_rate
RotorControlMode _control_mode = ROTOR_CONTROL_MODE_DISABLED
int16_t _critical_speed = 0
int16_t _idle_output = 0
int16_t _max_speed = 1000
int16_t _desired_speed = 0
int16_t _control_output = 0
float _rotor_ramp_output = 0
float _rotor_runup_output = 0
float _ramp_increment = 0
int8_t _ramp_time = 0
int8_t _runup_time = 0
float _runup_increment = 0
bool _runup_complete = false
uint16_t _power_output_low = 0
uint16_t _power_output_high = 0
uint16_t _power_output_range = 0
float _load_feedforward = 0
Detailed Description
Definition at line 26 of file AP_MotorsHeli_RSC.h.
Constructor & Destructor Documentation
AP_MotorsHeli_RSC::AP_MotorsHeli_RSC (RC_Channel & servo_output, int8_t servo_output_channel, uint16_t loop_rate) inline
Definition at line 28 of file AP_MotorsHeli_RSC.h.
Member Function Documentation
int16_t AP_MotorsHeli_RSC::get_control_output () const inline
Definition at line 58 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::move_actuators().
int16_t AP_MotorsHeli_RSC::get_critical_speed () const inline
Definition at line 46 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::rotor_speed_above_critical().
int16_t AP_MotorsHeli_RSC::get_desired_speed () const inline
Definition at line 52 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::get_desired_rotor_speed(), and AP_MotorsHeli_Single::move_yaw().
int16_t AP_MotorsHeli_RSC::get_rotor_speed () const
Definition at line 158 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Single::get_main_rotor_speed(), AP_MotorsHeli_Single::rotor_speed_above_critical(), and update_rotor_runup().
void AP_MotorsHeli_RSC::init_servo ()
Definition at line 25 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Single::init_outputs().
bool AP_MotorsHeli_RSC::is_runup_complete () const inline
Definition at line 64 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::update_motor_control().
void AP_MotorsHeli_RSC::output (RotorControlState state)
Definition at line 62 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Single::update_motor_control().
void AP_MotorsHeli_RSC::recalc_scalers ()
Definition at line 32 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::set_control_mode (RotorControlMode mode) inline
Definition at line 40 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::set_critical_speed (int16_t critical_speed) inline
Definition at line 43 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::set_desired_speed (int16_t desired_speed) inline
Definition at line 55 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::set_desired_rotor_speed().
void AP_MotorsHeli_RSC::set_idle_output (int16_t idle_output) inline
Definition at line 49 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::set_motor_load (float load) inline
Definition at line 76 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::move_actuators().
void AP_MotorsHeli_RSC::set_power_output_range (uint16_t power_low, uint16_t power_high)
Definition at line 54 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::set_ramp_time (int8_t ramp_time) inline
Definition at line 67 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::set_runup_time (int8_t runup_time) inline
Definition at line 70 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
void AP_MotorsHeli_RSC::update_rotor_ramp (float rotor_ramp_input) private
Definition at line 103 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
void AP_MotorsHeli_RSC::update_rotor_runup () private
Definition at line 123 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
void AP_MotorsHeli_RSC::write_rsc (int16_t servo_out) private
Definition at line 166 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
Member Data Documentation
RotorControlMode AP_MotorsHeli_RSC::_control_mode = ROTOR_CONTROL_MODE_DISABLED private
Definition at line 92 of file AP_MotorsHeli_RSC.h.
Referenced by output(), set_control_mode(), update_rotor_runup(), and write_rsc().
int16_t AP_MotorsHeli_RSC::_control_output = 0 private
Definition at line 97 of file AP_MotorsHeli_RSC.h.
Referenced by get_control_output(), and output().
int16_t AP_MotorsHeli_RSC::_critical_speed = 0 private
Definition at line 93 of file AP_MotorsHeli_RSC.h.
Referenced by get_critical_speed(), set_critical_speed(), and update_rotor_runup().
int16_t AP_MotorsHeli_RSC::_desired_speed = 0 private
Definition at line 96 of file AP_MotorsHeli_RSC.h.
Referenced by get_desired_speed(), output(), and set_desired_speed().
int16_t AP_MotorsHeli_RSC::_idle_output = 0 private
Definition at line 94 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_idle_output().
float AP_MotorsHeli_RSC::_load_feedforward = 0 private
Definition at line 108 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_motor_load().
float AP_MotorsHeli_RSC::_loop_rate private
Definition at line 89 of file AP_MotorsHeli_RSC.h.
Referenced by recalc_scalers().
int16_t AP_MotorsHeli_RSC::_max_speed = 1000 private
Definition at line 95 of file AP_MotorsHeli_RSC.h.
Referenced by get_rotor_speed().
uint16_t AP_MotorsHeli_RSC::_power_output_high = 0 private
Definition at line 106 of file AP_MotorsHeli_RSC.h.
Referenced by set_power_output_range().
uint16_t AP_MotorsHeli_RSC::_power_output_low = 0 private
Definition at line 105 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_power_output_range().
uint16_t AP_MotorsHeli_RSC::_power_output_range = 0 private
Definition at line 107 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_power_output_range().
float AP_MotorsHeli_RSC::_ramp_increment = 0 private
Definition at line 100 of file AP_MotorsHeli_RSC.h.
Referenced by recalc_scalers(), and update_rotor_ramp().
int8_t AP_MotorsHeli_RSC::_ramp_time = 0 private
Definition at line 101 of file AP_MotorsHeli_RSC.h.
Referenced by recalc_scalers(), and set_ramp_time().
float AP_MotorsHeli_RSC::_rotor_ramp_output = 0 private
Definition at line 98 of file AP_MotorsHeli_RSC.h.
Referenced by output(), update_rotor_ramp(), and update_rotor_runup().
float AP_MotorsHeli_RSC::_rotor_runup_output = 0 private
Definition at line 99 of file AP_MotorsHeli_RSC.h.
Referenced by get_rotor_speed(), update_rotor_ramp(), and update_rotor_runup().
bool AP_MotorsHeli_RSC::_runup_complete = false private
Definition at line 104 of file AP_MotorsHeli_RSC.h.
Referenced by is_runup_complete(), and update_rotor_runup().
float AP_MotorsHeli_RSC::_runup_increment = 0 private
Definition at line 103 of file AP_MotorsHeli_RSC.h.
Referenced by recalc_scalers(), and update_rotor_runup().
int8_t AP_MotorsHeli_RSC::_runup_time = 0 private
Definition at line 102 of file AP_MotorsHeli_RSC.h.
Referenced by recalc_scalers(), and set_runup_time().
RC_Channel& AP_MotorsHeli_RSC::_servo_output private
Definition at line 87 of file AP_MotorsHeli_RSC.h.
Referenced by init_servo(), and write_rsc().
int8_t AP_MotorsHeli_RSC::_servo_output_channel private
Definition at line 88 of file AP_MotorsHeli_RSC.h.
Referenced by write_rsc().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp