APM:Libraries: Linux::Scheduler Class Reference
Linux::Scheduler Class Reference
#include <Scheduler.h>
Public Member Functions
Scheduler ()
void init (void *machtnichts)
void delay (uint16_t ms)
uint32_t millis ()
uint32_t micros ()
uint64_t millis64 ()
uint64_t micros64 ()
void delay_microseconds (uint16_t us)
void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
void register_timer_process (AP_HAL::MemberProc)
void register_io_process (AP_HAL::MemberProc)
void suspend_timer_procs ()
void resume_timer_procs ()
bool in_timerprocess ()
void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us)
void begin_atomic ()
void end_atomic ()
bool system_initializing ()
void system_initialized ()
void panic (const char *errormsg,...) FORMAT(2
void reboot (bool hold_in_bootloader)
void stop_clock (uint64_t time_usec)
Public Member Functions inherited from AP_HAL::Scheduler
Scheduler ()
virtual void delay_microseconds_boost (uint16_t us)
virtual void set_timer_speed (uint16_t speed_hz)
Public Attributes
void NORETURN
Public Attributes inherited from AP_HAL::Scheduler
virtual void NORETURN = 0
Private Types
typedef void *(* pthread_startroutine_t) (void *)
Private Member Functions
void _timer_handler (int signum)
void _microsleep (uint32_t usec)
void _run_timers (bool called_from_timer_thread)
void _run_io (void)
void _create_realtime_thread (pthread_t *ctx, int rtprio, const char *name, pthread_startroutine_t start_routine)
Static Private Member Functions
static void * _timer_thread (void *arg)
static void * _io_thread (void *arg)
static void * _rcin_thread (void *arg)
static void * _uart_thread (void *arg)
static void * _tonealarm_thread (void *arg)
Private Attributes
struct timespec _sketch_start_time
AP_HAL::Proc _delay_cb
uint16_t _min_delay_cb_ms
AP_HAL::Proc _failsafe
bool _initialized
volatile bool _timer_pending
AP_HAL::MemberProc _timer_proc [LINUX_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_timer_procs
volatile bool _in_timer_proc
AP_HAL::MemberProc _io_proc [LINUX_SCHEDULER_MAX_IO_PROCS]
uint8_t _num_io_procs
volatile bool _in_io_proc
volatile bool _timer_event_missed
pthread_t _timer_thread_ctx
pthread_t _io_thread_ctx
pthread_t _rcin_thread_ctx
pthread_t _uart_thread_ctx
pthread_t _tonealarm_thread_ctx
uint64_t stopped_clock_usec
Semaphore _timer_semaphore
Semaphore _io_semaphore
Detailed Description
Definition at line 15 of file Scheduler.h.
Member Typedef Documentation
typedef void*(* Linux::Scheduler::pthread_startroutine_t) (void *) private
Definition at line 17 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler::Scheduler ()
Definition at line 46 of file Scheduler.cpp.
Member Function Documentation
void Scheduler::_create_realtime_thread (pthread_t * ctx, int rtprio, const char * name, pthread_startroutine_t start_routine) private
Definition at line 49 of file Scheduler.cpp.
Referenced by init().
void * Scheduler::_io_thread (void * arg) static private
Definition at line 391 of file Scheduler.cpp.
Referenced by init().
void Scheduler::_microsleep (uint32_t usec) private
Definition at line 133 of file Scheduler.cpp.
Referenced by _io_thread(), _rcin_thread(), _timer_thread(), _tonealarm_thread(), _uart_thread(), delay(), and delay_microseconds().
void * Scheduler::_rcin_thread (void * arg) static private
Definition at line 335 of file Scheduler.cpp.
Referenced by init().
void Scheduler::_run_io (void) private
Definition at line 319 of file Scheduler.cpp.
Referenced by _io_thread(), and stop_clock().
void Scheduler::_run_timers (bool called_from_timer_thread) private
Definition at line 257 of file Scheduler.cpp.
Referenced by _timer_thread().
void Linux::Scheduler::_timer_handler (int signum) private
void * Scheduler::_timer_thread (void * arg) static private
Definition at line 292 of file Scheduler.cpp.
Referenced by init().
void * Scheduler::_tonealarm_thread (void * arg) static private
Definition at line 375 of file Scheduler.cpp.
Referenced by init().
void * Scheduler::_uart_thread (void * arg) static private
Definition at line 349 of file Scheduler.cpp.
Referenced by init().
void Scheduler::begin_atomic ()
Definition at line 429 of file Scheduler.cpp.
void Scheduler::delay (uint16_t ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 141 of file Scheduler.cpp.
void Scheduler::delay_microseconds (uint16_t us) virtual
Implements AP_HAL::Scheduler.
Definition at line 193 of file Scheduler.cpp.
void Scheduler::end_atomic ()
Definition at line 432 of file Scheduler.cpp.
bool Scheduler::in_timerprocess () virtual
Implements AP_HAL::Scheduler.
Definition at line 424 of file Scheduler.cpp.
void Scheduler::init (void * machtnichts) virtual
Implements AP_HAL::Scheduler.
Definition at line 81 of file Scheduler.cpp.
uint32_t Scheduler::micros () virtual
Implements AP_HAL::Scheduler.
Definition at line 188 of file Scheduler.cpp.
uint64_t Scheduler::micros64 () virtual
Implements AP_HAL::Scheduler.
Definition at line 171 of file Scheduler.cpp.
Referenced by _timer_thread(), and micros().
uint32_t Scheduler::millis () virtual
Implements AP_HAL::Scheduler.
Definition at line 183 of file Scheduler.cpp.
uint64_t Scheduler::millis64 () virtual
Implements AP_HAL::Scheduler.
Definition at line 159 of file Scheduler.cpp.
Referenced by delay(), and millis().
void Scheduler::panic (const char * errormsg, ...) virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 410 of file Scheduler.cpp.
Referenced by _create_realtime_thread(), and system_initialized().
void Scheduler::reboot (bool hold_in_bootloader) virtual
Implements AP_HAL::Scheduler.
Definition at line 447 of file Scheduler.cpp.
void Scheduler::register_delay_callback (AP_HAL::Proc proc, uint16_t min_time_ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 201 of file Scheduler.cpp.
void Scheduler::register_io_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 224 of file Scheduler.cpp.
void Scheduler::register_timer_failsafe (AP_HAL::Proc failsafe, uint32_t period_us) virtual
Implements AP_HAL::Scheduler.
Definition at line 240 of file Scheduler.cpp.
void Scheduler::register_timer_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 208 of file Scheduler.cpp.
void Scheduler::resume_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 252 of file Scheduler.cpp.
void Scheduler::stop_clock (uint64_t time_usec) virtual
optional function to stop clock at a given time, used by log replay
Reimplemented from AP_HAL::Scheduler.
Definition at line 452 of file Scheduler.cpp.
void Scheduler::suspend_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 245 of file Scheduler.cpp.
void Scheduler::system_initialized () virtual
Implements AP_HAL::Scheduler.
Definition at line 439 of file Scheduler.cpp.
bool Scheduler::system_initializing () virtual
Implements AP_HAL::Scheduler.
Definition at line 435 of file Scheduler.cpp.
Referenced by _io_thread(), _rcin_thread(), _timer_thread(), _tonealarm_thread(), and _uart_thread().
Member Data Documentation
AP_HAL::Proc Linux::Scheduler::_delay_cb private
Definition at line 56 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
AP_HAL::Proc Linux::Scheduler::_failsafe private
Definition at line 59 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_failsafe().
volatile bool Linux::Scheduler::_in_io_proc private
Definition at line 70 of file Scheduler.h.
volatile bool Linux::Scheduler::_in_timer_proc private
Definition at line 66 of file Scheduler.h.
Referenced by _run_timers(), and in_timerprocess().
bool Linux::Scheduler::_initialized private
Definition at line 61 of file Scheduler.h.
Referenced by system_initialized(), and system_initializing().
AP_HAL::MemberProc Linux::Scheduler::_io_proc[LINUX_SCHEDULER_MAX_IO_PROCS] private
Definition at line 68 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
Semaphore Linux::Scheduler::_io_semaphore private
Definition at line 94 of file Scheduler.h.
Referenced by _run_io().
pthread_t Linux::Scheduler::_io_thread_ctx private
Definition at line 75 of file Scheduler.h.
Referenced by init().
uint16_t Linux::Scheduler::_min_delay_cb_ms private
Definition at line 57 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
uint8_t Linux::Scheduler::_num_io_procs private
Definition at line 69 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
uint8_t Linux::Scheduler::_num_timer_procs private
Definition at line 65 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
pthread_t Linux::Scheduler::_rcin_thread_ctx private
Definition at line 76 of file Scheduler.h.
Referenced by init().
struct timespec Linux::Scheduler::_sketch_start_time private
Definition at line 52 of file Scheduler.h.
Referenced by init(), micros64(), and millis64().
volatile bool Linux::Scheduler::_timer_event_missed private
Definition at line 72 of file Scheduler.h.
volatile bool Linux::Scheduler::_timer_pending private
Definition at line 62 of file Scheduler.h.
AP_HAL::MemberProc Linux::Scheduler::_timer_proc[LINUX_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 64 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
Semaphore Linux::Scheduler::_timer_semaphore private
Definition at line 93 of file Scheduler.h.
Referenced by _run_timers(), resume_timer_procs(), and suspend_timer_procs().
pthread_t Linux::Scheduler::_timer_thread_ctx private
Definition at line 74 of file Scheduler.h.
Referenced by init().
pthread_t Linux::Scheduler::_tonealarm_thread_ctx private
Definition at line 78 of file Scheduler.h.
Referenced by init().
pthread_t Linux::Scheduler::_uart_thread_ctx private
Definition at line 77 of file Scheduler.h.
Referenced by init().
void Linux::Scheduler::NORETURN
Definition at line 46 of file Scheduler.h.
uint64_t Linux::Scheduler::stopped_clock_usec private
Definition at line 91 of file Scheduler.h.
Referenced by delay(), delay_microseconds(), micros64(), millis64(), and stop_clock().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Scheduler.h
libraries/AP_HAL_Linux/Scheduler.cpp