APM:Libraries: Memory_table Class Reference
Memory_table Class Reference
#include <RCInput_RPI.h>
Public Member Functions
Memory_table ()
Memory_table (uint32_t, int)
~Memory_table ()
void * get_virt_addr (const uint32_t phys_addr) const
void * get_page (void **pages, const uint32_t addr) const
uint32_t get_offset (void **pages, const uint32_t addr) const
uint32_t bytes_available (const uint32_t read_addr, const uint32_t write_addr) const
uint32_t get_page_count () const
Private Attributes
void ** _virt_pages
void ** _phys_pages
uint32_t _page_count
Friends
class Linux::RCInput_RPI
Detailed Description
Definition at line 47 of file RCInput_RPI.h.
Constructor & Destructor Documentation
Memory_table::Memory_table ()
Definition at line 86 of file RCInput_RPI.cpp.
Memory_table::Memory_table (uint32_t page_count, int version)
Definition at line 92 of file RCInput_RPI.cpp.
Memory_table::~Memory_table ()
Definition at line 136 of file RCInput_RPI.cpp.
Member Function Documentation
uint32_t Memory_table::bytes_available (const uint32_t read_addr, const uint32_t write_addr) const
Definition at line 179 of file RCInput_RPI.cpp.
Referenced by Linux::RCInput_RPI::_timer_tick().
uint32_t Memory_table::get_offset (void ** pages, const uint32_t addr) const
Definition at line 167 of file RCInput_RPI.cpp.
Referenced by Linux::RCInput_RPI::_timer_tick().
void * Memory_table::get_page (void ** pages, const uint32_t addr) const
Definition at line 143 of file RCInput_RPI.cpp.
Referenced by Linux::RCInput_RPI::_timer_tick(), Linux::RCInput_RPI::init(), Linux::RCInput_RPI::init_ctrl_data(), and Linux::RCInput_RPI::init_DMA().
uint32_t Memory_table::get_page_count () const
Definition at line 189 of file RCInput_RPI.cpp.
Referenced by Linux::RCInput_RPI::_timer_tick().
void * Memory_table::get_virt_addr (const uint32_t phys_addr) const
Definition at line 152 of file RCInput_RPI.cpp.
Referenced by Linux::RCInput_RPI::_timer_tick().
Friends And Related Function Documentation
friend class Linux::RCInput_RPI friend
Definition at line 49 of file RCInput_RPI.h.
Member Data Documentation
uint32_t Memory_table::_page_count private
Definition at line 54 of file RCInput_RPI.h.
void** Memory_table::_phys_pages private
Definition at line 53 of file RCInput_RPI.h.
Referenced by Linux::RCInput_RPI::init_ctrl_data(), and Linux::RCInput_RPI::init_DMA().
void** Memory_table::_virt_pages private
Definition at line 52 of file RCInput_RPI.h.
Referenced by Linux::RCInput_RPI::_timer_tick(), Linux::RCInput_RPI::init(), and Linux::RCInput_RPI::init_ctrl_data().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/RCInput_RPI.h
libraries/AP_HAL_Linux/RCInput_RPI.cpp