APM:Libraries: EEPROMClass Class Reference
EEPROMClass Class Reference
#include <EEPROM.h>
Public Member Functions
EEPROMClass (void)
uint16 init (void)
uint16 init (uint32, uint32, uint32)
uint16 format (void)
Erases PAGE0 and PAGE1 and writes EEPROM_VALID_PAGE / 0 header to PAGE0.
uint16 erases (uint16 *)
Returns the erase counter for current page.
uint16 read (uint16 address)
Returns the last stored variable data, if found, which correspond to the passed virtual address.
uint16 read (uint16 address, uint16 *data)
Returns the last stored variable data, if found, which correspond to the passed virtual address.
uint16 write (uint16 address, uint16 data)
Writes/upadtes variable data in EEPROM.
uint16 count (uint16 *)
Return number of variable.
uint16 maxcount (void)
Public Attributes
uint32 PageBase0
uint32 PageBase1
uint32 PageSize
uint16 Status
Private Member Functions
FLASH_Status EE_ErasePage (uint32)
Erase page with increment erase counter (page + 2)
uint16 EE_CheckPage (uint32, uint16)
Check page for blank.
uint16 EE_CheckErasePage (uint32, uint16)
Check page for blank and erase it.
uint16 EE_Format (void)
uint32 EE_FindValidPage (void)
Find valid Page for write or read operation.
uint16 EE_GetVariablesCount (uint32, uint16)
Calculate unique variables in EEPROM.
uint16 EE_PageTransfer (uint32, uint32, uint16)
Transfers last updated variables data from the full Page to an empty one.
uint16 EE_VerifyPageFullWriteVariable (uint16, uint16)
Verify if active page is full and Writes variable in EEPROM.
Detailed Description
Definition at line 64 of file EEPROM.h.
Constructor & Destructor Documentation
EEPROMClass::EEPROMClass (void)
Definition at line 286 of file EEPROM.cpp.
Member Function Documentation
uint16 EEPROMClass::count (uint16 * Count)
Return number of variable.
Return values
Number of variables
Definition at line 532 of file EEPROM.cpp.
uint16 EEPROMClass::EE_CheckErasePage (uint32 pageBase, uint16 status) private
Check page for blank and erase it.
Parameters
page base address
Return values
Success or error
Flash error code: on write Flash error
EEPROM_BAD_FLASH: page not empty after erase
EEPROM_OK: page blank
Definition at line 59 of file EEPROM.cpp.
Referenced by EE_PageTransfer(), format(), and init().
uint16 EEPROMClass::EE_CheckPage (uint32 pageBase, uint16 status) private
Check page for blank.
Parameters
page base address
Return values
Success or error EEPROM_BAD_FLASH: page not empty after erase EEPROM_OK: page blank
Definition at line 15 of file EEPROM.cpp.
Referenced by EE_CheckErasePage().
FLASH_Status EEPROMClass::EE_ErasePage (uint32 pageBase) private
Erase page with increment erase counter (page + 2)
Parameters
page base address
Return values
Success or error FLASH_COMPLETE: success erase
Flash error code: on write Flash error
Definition at line 35 of file EEPROM.cpp.
Referenced by EE_CheckErasePage().
uint32 EEPROMClass::EE_FindValidPage (void) private
Find valid Page for write or read operation.
Parameters
Page0 Page0 base address Page1: Page1 base address
Return values
Valid page address (PAGE0 or PAGE1) or NULL in case of no valid page was found
Definition at line 78 of file EEPROM.cpp.
Referenced by count(), EE_VerifyPageFullWriteVariable(), erases(), and read().
uint16 EEPROMClass::EE_Format (void) private
uint16 EEPROMClass::EE_GetVariablesCount (uint32 pageBase, uint16 skipAddress) private
Calculate unique variables in EEPROM.
Parameters
start address of first slot to check (page + 4)
end page end address
address 16 bit virtual address of the variable to excluse (or 0XFFFF)
Return values
count of variables
Definition at line 98 of file EEPROM.cpp.
Referenced by count(), and EE_VerifyPageFullWriteVariable().
uint16 EEPROMClass::EE_PageTransfer (uint32 newPage, uint32 oldPage, uint16 SkipAddress) private
Transfers last updated variables data from the full Page to an empty one.
Parameters
newPage new page base address
oldPage old page base address
SkipAddress 16 bit virtual address of the variable (or 0xFFFF)
Return values
Success or error status:
FLASH_COMPLETE: on success
EEPROM_OUT_SIZE: if valid new page is full
Flash error code: on write Flash error
Definition at line 135 of file EEPROM.cpp.
Referenced by EE_VerifyPageFullWriteVariable(), and init().
uint16 EEPROMClass::EE_VerifyPageFullWriteVariable (uint16 Address, uint16 Data) private
Verify if active page is full and Writes variable in EEPROM.
Parameters
Address 16 bit virtual address of the variable
Data 16 bit data to be written as variable value
Return values
Success or error status:
FLASH_COMPLETE: on success
EEPROM_PAGE_FULL: if valid page is full (need page transfer)
EEPROM_NO_VALID_PAGE: if no valid page was found
EEPROM_OUT_SIZE: if EEPROM size exceeded
Flash error code: on write Flash error
Definition at line 214 of file EEPROM.cpp.
Referenced by write().
uint16 EEPROMClass::erases (uint16 * Erases)
Returns the erase counter for current page.
Parameters
Data Global variable contains the read variable value
Return values
Success or error status:
EEPROM_OK: if erases counter return.
EEPROM_NO_VALID_PAGE: if no valid page was found.
Definition at line 432 of file EEPROM.cpp.
uint16 EEPROMClass::format (void)
Erases PAGE0 and PAGE1 and writes EEPROM_VALID_PAGE / 0 header to PAGE0.
Parameters
PAGE0 and PAGE1 base addresses
Return values
Status of the last operation (Flash write or erase) done during EEPROM formating
Definition at line 403 of file EEPROM.cpp.
Referenced by init().
uint16 EEPROMClass::init (void)
Definition at line 302 of file EEPROM.cpp.
Referenced by count(), erases(), AP_HAL_FLYMAPLE_NS::FLYMAPLEStorage::init(), init(), read(), and write().
uint16 EEPROMClass::init (uint32 pageBase0, uint32 pageBase1, uint32 pageSize)
Definition at line 294 of file EEPROM.cpp.
uint16 EEPROMClass::maxcount (void)
Definition at line 547 of file EEPROM.cpp.
uint16 EEPROMClass::read (uint16 Address)
Returns the last stored variable data, if found, which correspond to the passed virtual address.
Parameters
Address Variable virtual address
Return values
Data for variable or EEPROM_DEFAULT_DATA, if any errors
Definition at line 454 of file EEPROM.cpp.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLEStorage::read_byte(), and AP_HAL_FLYMAPLE_NS::FLYMAPLEStorage::write_byte().
uint16 EEPROMClass::read (uint16 Address, uint16 * Data)
Returns the last stored variable data, if found, which correspond to the passed virtual address.
Parameters
Address Variable virtual address
Data Pointer to data variable
Return values
Success or error status:
EEPROM_OK: if variable was found
EEPROM_BAD_ADDRESS: if the variable was not found
EEPROM_NO_VALID_PAGE: if no valid page was found.
Definition at line 471 of file EEPROM.cpp.
uint16 EEPROMClass::write (uint16 Address, uint16 Data)
Writes/upadtes variable data in EEPROM.
Parameters
VirtAddress Variable virtual address
Data 16 bit data to be written
Return values
Success or error status:
FLASH_COMPLETE: on success
EEPROM_BAD_ADDRESS: if address = 0xFFFF
EEPROM_PAGE_FULL: if valid page is full
EEPROM_NO_VALID_PAGE: if no valid page was found
EEPROM_OUT_SIZE: if no empty EEPROM variables
Flash error code: on write Flash error
Definition at line 514 of file EEPROM.cpp.
Referenced by AP_HAL_FLYMAPLE_NS::FLYMAPLEStorage::write_byte().
Member Data Documentation
uint32 EEPROMClass::PageBase0
Definition at line 81 of file EEPROM.h.
Referenced by EE_FindValidPage(), EE_VerifyPageFullWriteVariable(), EEPROMClass(), format(), and init().
uint32 EEPROMClass::PageBase1
Definition at line 82 of file EEPROM.h.
Referenced by EE_FindValidPage(), EE_VerifyPageFullWriteVariable(), EEPROMClass(), format(), and init().
uint32 EEPROMClass::PageSize
Definition at line 83 of file EEPROM.h.
Referenced by EE_CheckPage(), EE_GetVariablesCount(), EE_PageTransfer(), EE_VerifyPageFullWriteVariable(), EEPROMClass(), init(), maxcount(), and read().
uint16 EEPROMClass::Status
Definition at line 84 of file EEPROM.h.
Referenced by count(), EEPROMClass(), erases(), init(), read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_FLYMAPLE/utility/EEPROM.h
libraries/AP_HAL_FLYMAPLE/utility/EEPROM.cpp