APM:Libraries: AP_InertialSensor_LSM9DS0 Class Reference
AP_InertialSensor_LSM9DS0 Class Reference
#include <AP_InertialSensor_LSM9DS0.h>
Classes
struct sensor_raw_data
Public Types
enum gyro_scale { G_SCALE_245DPS = 0, G_SCALE_500DPS, G_SCALE_2000DPS }
enum accel_scale {
A_SCALE_2G = 0, A_SCALE_4G, A_SCALE_6G, A_SCALE_8G,
A_SCALE_16G
}
Public Member Functions
AP_InertialSensor_LSM9DS0 (AP_InertialSensor &imu, int drdy_pin_num_a, int drdy_pin_num_b)
bool update ()
bool gyro_sample_available ()
bool accel_sample_available ()
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void start ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t product_id (void) const
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Member Functions
bool _accel_data_ready ()
bool _gyro_data_ready ()
void _poll_data ()
bool _init_sensor ()
bool _hardware_init ()
void _gyro_init ()
void _accel_init ()
void _set_gyro_scale (gyro_scale scale)
void _set_accel_scale (accel_scale scale)
uint8_t _register_read_xm (uint8_t reg)
uint8_t _register_read_g (uint8_t reg)
void _register_write_xm (uint8_t reg, uint8_t val)
void _register_write_g (uint8_t reg, uint8_t val)
void _accel_raw_data (struct sensor_raw_data *raw_data)
void _gyro_raw_data (struct sensor_raw_data *raw_data)
void _read_data_transaction_a ()
void _read_data_transaction_g ()
void _set_accel_filter (uint8_t filter_hz)
void _set_gyro_filter (uint8_t filter_hz)
Private Attributes
AP_HAL::SPIDeviceDriver * _accel_spi
AP_HAL::SPIDeviceDriver * _gyro_spi
AP_HAL::Semaphore * _spi_sem
int _drdy_pin_num_a
AP_HAL::DigitalSource * _drdy_pin_a
int _drdy_pin_num_g
AP_HAL::DigitalSource * _drdy_pin_g
bool _gyro_sample_available
bool _accel_sample_available
uint8_t _gyro_instance
uint8_t _accel_instance
float _gyro_scale
float _accel_scale
int16_t _last_gyro_filter_hz
int16_t _last_accel_filter_hz
Vector3f _accel_filtered
Vector3f _gyro_filtered
LowPassFilter2pVector3f _accel_filter
LowPassFilter2pVector3f _gyro_filter
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
void _set_accel_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
int16_t _product_id
int16_t _id = -1
Detailed Description
Definition at line 10 of file AP_InertialSensor_LSM9DS0.h.
Member Enumeration Documentation
enum AP_InertialSensor_LSM9DS0::accel_scale
Enumerator
A_SCALE_2G
A_SCALE_4G
A_SCALE_6G
A_SCALE_8G
A_SCALE_16G
Definition at line 21 of file AP_InertialSensor_LSM9DS0.h.
enum AP_InertialSensor_LSM9DS0::gyro_scale
Enumerator
G_SCALE_245DPS
G_SCALE_500DPS
G_SCALE_2000DPS
Definition at line 14 of file AP_InertialSensor_LSM9DS0.h.
Constructor & Destructor Documentation
AP_InertialSensor_LSM9DS0::AP_InertialSensor_LSM9DS0 (AP_InertialSensor & imu, int drdy_pin_num_a, int drdy_pin_num_b)
Definition at line 373 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by detect().
Member Function Documentation
bool AP_InertialSensor_LSM9DS0::_accel_data_ready () private
Definition at line 694 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor(), and _poll_data().
void AP_InertialSensor_LSM9DS0::_accel_init () private
Definition at line 597 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_accel_raw_data (struct sensor_raw_data * raw_data) private
Definition at line 714 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _read_data_transaction_a().
bool AP_InertialSensor_LSM9DS0::_gyro_data_ready () private
Definition at line 704 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor(), and _poll_data().
void AP_InertialSensor_LSM9DS0::_gyro_init () private
Definition at line 568 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_gyro_raw_data (struct sensor_raw_data * raw_data) private
Definition at line 725 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _read_data_transaction_g().
bool AP_InertialSensor_LSM9DS0::_hardware_init (void) private
Definition at line 498 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor().
bool AP_InertialSensor_LSM9DS0::_init_sensor (void) private
Definition at line 410 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by detect().
void AP_InertialSensor_LSM9DS0::_poll_data (void) private
Timer process to poll for new data from the LSM9DS0.
Definition at line 657 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor().
void AP_InertialSensor_LSM9DS0::_read_data_transaction_a () private
Definition at line 736 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _poll_data().
void AP_InertialSensor_LSM9DS0::_read_data_transaction_g () private
Definition at line 752 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _poll_data().
uint8_t AP_InertialSensor_LSM9DS0::_register_read_g (uint8_t reg) private
Definition at line 533 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor().
uint8_t AP_InertialSensor_LSM9DS0::_register_read_xm (uint8_t reg) private
Definition at line 519 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_data_ready(), _gyro_data_ready(), and _init_sensor().
void AP_InertialSensor_LSM9DS0::_register_write_g (uint8_t reg, uint8_t val) private
Definition at line 558 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _gyro_init().
void AP_InertialSensor_LSM9DS0::_register_write_xm (uint8_t reg, uint8_t val) private
Definition at line 548 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_init().
void AP_InertialSensor_LSM9DS0::_set_accel_filter (uint8_t filter_hz) private
Definition at line 789 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by update().
void AP_InertialSensor_LSM9DS0::_set_accel_scale (accel_scale scale) private
Definition at line 640 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_init().
void AP_InertialSensor_LSM9DS0::_set_gyro_filter (uint8_t filter_hz) private
Definition at line 797 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by update().
void AP_InertialSensor_LSM9DS0::_set_gyro_scale (gyro_scale scale) private
Definition at line 621 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _gyro_init().
bool AP_InertialSensor_LSM9DS0::accel_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 39 of file AP_InertialSensor_LSM9DS0.h.
AP_InertialSensor_Backend * AP_InertialSensor_LSM9DS0::detect (AP_InertialSensor & imu) static
Definition at line 391 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by AP_InertialSensor::detect_backends().
bool AP_InertialSensor_LSM9DS0::gyro_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 35 of file AP_InertialSensor_LSM9DS0.h.
bool AP_InertialSensor_LSM9DS0::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 765 of file AP_InertialSensor_LSM9DS0.cpp.
Member Data Documentation
LowPassFilter2pVector3f AP_InertialSensor_LSM9DS0::_accel_filter private
Definition at line 112 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a(), and _set_accel_filter().
Vector3f AP_InertialSensor_LSM9DS0::_accel_filtered private
Definition at line 108 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a(), and update().
uint8_t AP_InertialSensor_LSM9DS0::_accel_instance private
Definition at line 79 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor(), _read_data_transaction_a(), and update().
bool AP_InertialSensor_LSM9DS0::_accel_sample_available private
Definition at line 68 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a(), accel_sample_available(), and update().
float AP_InertialSensor_LSM9DS0::_accel_scale private
Definition at line 84 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a(), and _set_accel_scale().
AP_HAL::SPIDeviceDriver* AP_InertialSensor_LSM9DS0::_accel_spi private
Definition at line 52 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _accel_raw_data(), _hardware_init(), _init_sensor(), _register_read_xm(), and _register_write_xm().
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_a private
Definition at line 63 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _accel_data_ready(), and _init_sensor().
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_g private
Definition at line 65 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _gyro_data_ready(), and _init_sensor().
int AP_InertialSensor_LSM9DS0::_drdy_pin_num_a private
Definition at line 62 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor(), and _poll_data().
int AP_InertialSensor_LSM9DS0::_drdy_pin_num_g private
Definition at line 64 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor(), and _poll_data().
LowPassFilter2pVector3f AP_InertialSensor_LSM9DS0::_gyro_filter private
Definition at line 113 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), and _set_gyro_filter().
Vector3f AP_InertialSensor_LSM9DS0::_gyro_filtered private
Definition at line 109 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), and update().
uint8_t AP_InertialSensor_LSM9DS0::_gyro_instance private
Definition at line 78 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor(), _read_data_transaction_g(), and update().
bool AP_InertialSensor_LSM9DS0::_gyro_sample_available private
Definition at line 67 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), gyro_sample_available(), and update().
float AP_InertialSensor_LSM9DS0::_gyro_scale private
Definition at line 84 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), and _set_gyro_scale().
AP_HAL::SPIDeviceDriver* AP_InertialSensor_LSM9DS0::_gyro_spi private
Definition at line 53 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _gyro_raw_data(), _hardware_init(), _init_sensor(), _register_read_g(), and _register_write_g().
int16_t AP_InertialSensor_LSM9DS0::_last_accel_filter_hz private
Definition at line 102 of file AP_InertialSensor_LSM9DS0.h.
Referenced by update().
int16_t AP_InertialSensor_LSM9DS0::_last_gyro_filter_hz private
Definition at line 101 of file AP_InertialSensor_LSM9DS0.h.
Referenced by update().
AP_HAL::Semaphore* AP_InertialSensor_LSM9DS0::_spi_sem private
Definition at line 54 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), _init_sensor(), and _poll_data().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.h
libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.cpp