APM:Libraries: AP_Limit_Module Class Reference
AP_Limit_Module Class Reference
#include <AP_Limit_Module.h>
Public Member Functions
AP_Limit_Module (enum moduleid id)
bool init ()
virtual moduleid get_module_id ()
virtual bool enabled ()
virtual bool required ()
virtual AP_Limit_Module * next ()
virtual void link (AP_Limit_Module *m)
virtual bool triggered ()
virtual void action ()
Protected Attributes
AP_Int8 _enabled
AP_Int8 _required
AP_Int8 _triggered
Private Attributes
enum moduleid _id
AP_Limit_Module * _next
Detailed Description
Definition at line 34 of file AP_Limit_Module.h.
Constructor & Destructor Documentation
AP_Limit_Module::AP_Limit_Module (enum moduleid id)
Definition at line 31 of file AP_Limit_Module.cpp.
Member Function Documentation
void AP_Limit_Module::action () virtual
Definition at line 66 of file AP_Limit_Module.cpp.
bool AP_Limit_Module::enabled (void) virtual
Definition at line 46 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::check_triggered().
moduleid AP_Limit_Module::get_module_id () virtual
Definition at line 42 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::check_triggered().
bool AP_Limit_Module::init (void)
Definition at line 36 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::init().
void AP_Limit_Module::link (AP_Limit_Module * m) virtual
Definition at line 58 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::modules_add().
AP_Limit_Module * AP_Limit_Module::next () virtual
Definition at line 54 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::check_triggered(), AP_Limits::modules_count(), AP_Limits::modules_last(), and AP_Limits::modules_next().
bool AP_Limit_Module::required () virtual
Definition at line 50 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::check_triggered().
bool AP_Limit_Module::triggered () virtual
Reimplemented in AP_Limit_Geofence, AP_Limit_Altitude, and AP_Limit_GPSLock.
Definition at line 62 of file AP_Limit_Module.cpp.
Referenced by AP_Limits::check_triggered().
Member Data Documentation
AP_Int8 AP_Limit_Module::_enabled protected
Definition at line 60 of file AP_Limit_Module.h.
Referenced by enabled(), and AP_Limit_Geofence::triggered().
enum moduleid AP_Limit_Module::_id private
Definition at line 66 of file AP_Limit_Module.h.
Referenced by AP_Limit_Module(), and get_module_id().
AP_Limit_Module* AP_Limit_Module::_next private
Definition at line 67 of file AP_Limit_Module.h.
Referenced by AP_Limit_Module(), link(), and next().
AP_Int8 AP_Limit_Module::_required protected
Definition at line 62 of file AP_Limit_Module.h.
Referenced by required(), and AP_Limit_Geofence::triggered().
AP_Int8 AP_Limit_Module::_triggered protected
Definition at line 63 of file AP_Limit_Module.h.
Referenced by init(), AP_Limit_GPSLock::triggered(), AP_Limit_Altitude::triggered(), AP_Limit_Geofence::triggered(), and triggered().
The documentation for this class was generated from the following files:
libraries/AP_Limits/AP_Limit_Module.h
libraries/AP_Limits/AP_Limit_Module.cpp