APM:Libraries: AP_HAL_FLYMAPLE_NS::FLYMAPLERCOutput Class Reference
AP_HAL_FLYMAPLE_NS::FLYMAPLERCOutput Class Reference
#include <RCOutput.h>
Private Member Functions
void init (void *machtnichts)
void set_freq (uint32_t chmask, uint16_t freq_hz)
uint16_t get_freq (uint8_t ch)
void enable_ch (uint8_t ch)
void disable_ch (uint8_t ch)
void write (uint8_t ch, uint16_t period_us)
uint16_t read (uint8_t ch)
void read (uint16_t *period_us, uint8_t len)
uint8_t _channel_to_flymaple_pin (uint8_t ch)
void _set_freq (uint8_t ch, uint16_t freq_hz)
Private Attributes
uint32_t _clocks_per_msecond [FLYMAPLE_RC_OUTPUT_NUM_CHANNELS]
Additional Inherited Members
Public Member Functions inherited from AP_HAL::RCOutput
virtual void cork ()
virtual void push ()
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
Detailed Description
Definition at line 26 of file RCOutput.h.
Member Function Documentation
uint8_t FLYMAPLERCOutput::_channel_to_flymaple_pin (uint8_t ch) private
Definition at line 115 of file RCOutput.cpp.
Referenced by _set_freq(), disable_ch(), enable_ch(), get_freq(), read(), and write().
void FLYMAPLERCOutput::_set_freq (uint8_t ch, uint16_t freq_hz) private
Definition at line 130 of file RCOutput.cpp.
Referenced by enable_ch(), and set_freq().
void FLYMAPLERCOutput::disable_ch (uint8_t ch) private virtual
Implements AP_HAL::RCOutput.
Definition at line 75 of file RCOutput.cpp.
void FLYMAPLERCOutput::enable_ch (uint8_t ch) private virtual
Implements AP_HAL::RCOutput.
Definition at line 59 of file RCOutput.cpp.
uint16_t FLYMAPLERCOutput::get_freq (uint8_t ch) private virtual
Implements AP_HAL::RCOutput.
Definition at line 45 of file RCOutput.cpp.
void FLYMAPLERCOutput::init (void * machtnichts) private virtual
Implements AP_HAL::RCOutput.
Definition at line 34 of file RCOutput.cpp.
uint16_t FLYMAPLERCOutput::read (uint8_t ch) private virtual
Implements AP_HAL::RCOutput.
Definition at line 98 of file RCOutput.cpp.
Referenced by read().
void FLYMAPLERCOutput::read (uint16_t * period_us, uint8_t len) private virtual
Implements AP_HAL::RCOutput.
Definition at line 109 of file RCOutput.cpp.
void FLYMAPLERCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) private virtual
Implements AP_HAL::RCOutput.
Definition at line 36 of file RCOutput.cpp.
void FLYMAPLERCOutput::write (uint8_t ch, uint16_t period_us) private virtual
Implements AP_HAL::RCOutput.
Definition at line 90 of file RCOutput.cpp.
Member Data Documentation
uint32_t AP_HAL_FLYMAPLE_NS::FLYMAPLERCOutput::_clocks_per_msecond[FLYMAPLE_RC_OUTPUT_NUM_CHANNELS] private
Definition at line 46 of file RCOutput.h.
Referenced by _set_freq(), read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_FLYMAPLE/RCOutput.h
libraries/AP_HAL_FLYMAPLE/RCOutput.cpp