APM:Libraries: Linux::PWM_Sysfs Class Reference
Linux::PWM_Sysfs Class Reference
#include <PWM_Sysfs.h>
Public Types
enum Polarity { NORMAL = 0, INVERSE = 1 }
Public Member Functions
PWM_Sysfs (uint8_t chip, uint8_t channel)
~PWM_Sysfs ()
void enable (bool value)
bool is_enabled ()
void set_period (uint32_t nsec_period)
uint32_t get_period ()
void set_freq (uint32_t freq)
uint32_t get_freq ()
bool set_duty_cycle (uint32_t nsec_duty_cycle)
uint32_t get_duty_cycle ()
void set_polarity (PWM_Sysfs::Polarity polarity)
PWM_Sysfs::Polarity get_polarity ()
Private Attributes
uint32_t _nsec_duty_cycle_value
int _duty_cycle_fd
const uint16_t _channel
const uint8_t _chip
Detailed Description
Definition at line 8 of file PWM_Sysfs.h.
Member Enumeration Documentation
enum Linux::PWM_Sysfs::Polarity
Enumerator
NORMAL
INVERSE
Definition at line 13 of file PWM_Sysfs.h.
Constructor & Destructor Documentation
Linux::PWM_Sysfs::PWM_Sysfs (uint8_t chip, uint8_t channel)
Definition at line 49 of file PWM_Sysfs.cpp.
Linux::PWM_Sysfs::~PWM_Sysfs ()
Definition at line 88 of file PWM_Sysfs.cpp.
Member Function Documentation
void Linux::PWM_Sysfs::enable (bool value)
Definition at line 95 of file PWM_Sysfs.cpp.
Referenced by Linux::RCOutput_Sysfs::disable_ch(), Linux::RCOutput_Sysfs::enable_ch(), and Linux::RCOutput_Sysfs::init().
uint32_t Linux::PWM_Sysfs::get_duty_cycle ()
Definition at line 180 of file PWM_Sysfs.cpp.
uint32_t Linux::PWM_Sysfs::get_freq ()
Definition at line 164 of file PWM_Sysfs.cpp.
Referenced by Linux::RCOutput_Sysfs::get_freq().
uint32_t Linux::PWM_Sysfs::get_period ()
Definition at line 141 of file PWM_Sysfs.cpp.
Referenced by get_freq().
PWM_Sysfs::Polarity Linux::PWM_Sysfs::get_polarity ()
Definition at line 200 of file PWM_Sysfs.cpp.
bool Linux::PWM_Sysfs::is_enabled ()
Definition at line 110 of file PWM_Sysfs.cpp.
bool Linux::PWM_Sysfs::set_duty_cycle (uint32_t nsec_duty_cycle)
Definition at line 169 of file PWM_Sysfs.cpp.
Referenced by Linux::RCOutput_Sysfs::init(), and Linux::RCOutput_Sysfs::write().
void Linux::PWM_Sysfs::set_freq (uint32_t freq)
Definition at line 159 of file PWM_Sysfs.cpp.
Referenced by Linux::RCOutput_Sysfs::init(), and Linux::RCOutput_Sysfs::set_freq().
void Linux::PWM_Sysfs::set_period (uint32_t nsec_period)
Definition at line 127 of file PWM_Sysfs.cpp.
Referenced by set_freq().
void Linux::PWM_Sysfs::set_polarity (PWM_Sysfs::Polarity polarity)
Definition at line 185 of file PWM_Sysfs.cpp.
Referenced by Linux::RCOutput_Sysfs::init().
Member Data Documentation
const uint16_t Linux::PWM_Sysfs::_channel private
Definition at line 44 of file PWM_Sysfs.h.
Referenced by enable(), get_period(), get_polarity(), is_enabled(), PWM_Sysfs(), set_period(), and set_polarity().
const uint8_t Linux::PWM_Sysfs::_chip private
Definition at line 45 of file PWM_Sysfs.h.
Referenced by enable(), get_period(), get_polarity(), is_enabled(), PWM_Sysfs(), set_period(), and set_polarity().
int Linux::PWM_Sysfs::_duty_cycle_fd private
Definition at line 43 of file PWM_Sysfs.h.
Referenced by PWM_Sysfs(), set_duty_cycle(), and ~PWM_Sysfs().
uint32_t Linux::PWM_Sysfs::_nsec_duty_cycle_value private
Definition at line 42 of file PWM_Sysfs.h.
Referenced by get_duty_cycle(), and set_duty_cycle().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/PWM_Sysfs.h
libraries/AP_HAL_Linux/PWM_Sysfs.cpp