APM:Libraries: AP_SerialBus Class Reference
AP_SerialBus Class Reference abstract
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_Baro_MS5611.h>
Public Member Functions
virtual void init ()=0
virtual uint16_t read_16bits (uint8_t reg)=0
virtual uint32_t read_24bits (uint8_t reg)=0
virtual bool write (uint8_t reg)=0
virtual bool sem_take_nonblocking ()=0
virtual bool sem_take_blocking ()=0
virtual void sem_give ()=0
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Abstract serial bus device driver for I2C/SPI.
Definition at line 10 of file AP_Baro_MS5611.h.
Member Function Documentation
virtual void AP_SerialBus::init () pure virtual
Initialize the driver.
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::AP_Baro_MS56XX().
virtual uint16_t AP_SerialBus::read_16bits (uint8_t reg) pure virtual
Read a 16-bit value from register "reg".
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::_check_crc(), and AP_Baro_MS56XX::AP_Baro_MS56XX().
virtual uint32_t AP_SerialBus::read_24bits (uint8_t reg) pure virtual
Read a 24-bit value
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::_timer().
virtual void AP_SerialBus::sem_give () pure virtual
Release the internal semaphore for this device.
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::_timer(), and AP_Baro_MS56XX::AP_Baro_MS56XX().
virtual bool AP_SerialBus::sem_take_blocking () pure virtual
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::AP_Baro_MS56XX().
virtual bool AP_SerialBus::sem_take_nonblocking () pure virtual
Acquire the internal semaphore for this device. take_nonblocking should be used from the timer process, take_blocking from synchronous code (i.e. init)
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::_timer().
virtual bool AP_SerialBus::write (uint8_t reg) pure virtual
Write to a register with no data.
Implemented in AP_SerialBus_I2C, and AP_SerialBus_SPI.
Referenced by AP_Baro_MS56XX::_timer(), and AP_Baro_MS56XX::AP_Baro_MS56XX().
The documentation for this class was generated from the following file:
libraries/AP_Baro/AP_Baro_MS5611.h