APM:Libraries: Matrix3< T > Class Template Reference
Matrix3< T > Class Template Reference
#include <matrix3.h>
Public Member Functions
Matrix3 ()
Matrix3 (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz)
void operator() (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
bool operator== (const Matrix3< T > &m)
bool operator!= (const Matrix3< T > &m)
Matrix3< T > operator- (void) const
Matrix3< T > operator+ (const Matrix3< T > &m) const
Matrix3< T > & operator+= (const Matrix3< T > &m)
Matrix3< T > operator- (const Matrix3< T > &m) const
Matrix3< T > & operator-= (const Matrix3< T > &m)
Matrix3< T > operator* (const T num) const
Matrix3< T > & operator*= (const T num)
Matrix3< T > operator/ (const T num) const
Matrix3< T > & operator/= (const T num)
Vector3< T > & operator[] (uint8_t i)
const Vector3< T > & operator[] (uint8_t i) const
Vector3< T > operator* (const Vector3< T > &v) const
Vector3< T > mul_transpose (const Vector3< T > &v) const
Vector2< T > mulXY (const Vector3< T > &v) const
Vector3< T > colx (void) const
Vector3< T > coly (void) const
Vector3< T > colz (void) const
Matrix3< T > operator* (const Matrix3< T > &m) const
Matrix3< T > & operator*= (const Matrix3< T > &m)
Matrix3< T > transposed (void) const
void transpose (void)
void zero (void)
void identity (void)
bool is_nan (void)
void from_euler (float roll, float pitch, float yaw)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
void to_euler (float *roll, float *pitch, float *yaw) const
Vector3< T > to_euler312 () const
void from_euler312 (float roll, float pitch, float yaw)
void rotate (const Vector3< T > &g)
void rotateXY (const Vector3< T > &g)
void rotateXYinv (const Vector3< T > &g)
void normalize (void)
Public Attributes
Vector3< T > a
Vector3< T > b
Vector3< T > c
Detailed Description
template<typename T>
class Matrix3< T >
Definition at line 47 of file matrix3.h.
Constructor & Destructor Documentation
template<typename T> Matrix3< T >::Matrix3 () inline
Definition at line 55 of file matrix3.h.
template<typename T> Matrix3< T >::Matrix3 (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 59 of file matrix3.h.
template<typename T> Matrix3< T >::Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz) inline
Definition at line 63 of file matrix3.h.
Member Function Documentation
template<typename T> Vector3<T> Matrix3< T >::colx (void) const inline
Definition at line 155 of file matrix3.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), and Vector3< T >::operator*().
template<typename T> Vector3<T> Matrix3< T >::coly (void) const inline
Definition at line 161 of file matrix3.h.
Referenced by Vector3< T >::operator*().
template<typename T> Vector3<T> Matrix3< T >::colz (void) const inline
Definition at line 167 of file matrix3.h.
Referenced by Vector3< T >::operator*().
template<typename T > template void Matrix3< T >::from_euler (float roll, float pitch, float yaw)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 27 of file matrix3.cpp.
Referenced by Compass::_setup_earth_field(), HALSITL::SITL_State::_update_flow(), SITL::Aircraft::Aircraft(), NavEKF_core::calcQuatAndFieldStates(), NavEKF2_core::calcQuatAndFieldStates(), AP_AHRS_DCM::drift_correction_yaw(), SITL::Gimbal::Gimbal(), loop(), missing_rotations(), SITL::last_letter::recv_fdm(), SITL::CRRCSim::recv_fdm(), SITL::JSBSim::recv_fdm(), AP_AHRS_DCM::reset(), AP_AHRS_DCM::reset_attitude(), SITL::Aircraft::set_yaw_degrees(), Compass::setHIL(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_frame_transforms(), test_quaternion(), test_rotation_accuracy(), SITL::Gimbal::update(), SITL::Balloon::update(), SITL::Helicopter::update(), and SITL::MultiCopter::update().
template<typename T > void Matrix3< T >::from_euler312 (float roll, float pitch, float yaw)
Definition at line 80 of file matrix3.cpp.
Referenced by Quaternion::from_vector312().
template<typename T> void Matrix3< T >::identity (void) inline
Definition at line 192 of file matrix3.h.
Referenced by AP_AHRS_DCM::AP_AHRS_DCM(), and test_matrix_rotate().
template<typename T> bool Matrix3< T >::is_nan (void) inline
Definition at line 200 of file matrix3.h.
Referenced by AP_AHRS_DCM::check_matrix(), and test_conversion().
template<typename T> template Vector3< double > Matrix3< T >::mul_transpose (const Vector3< T > & v) const
Definition at line 191 of file matrix3.cpp.
Referenced by HALSITL::SITL_State::_update_flow(), AP_AHRS_DCM::drift_correction(), and Compass::setHIL().
template<typename T> template Vector2< double > Matrix3< T >::mulXY (const Vector3< T > & v) const
Definition at line 183 of file matrix3.cpp.
Referenced by AP_AHRS_DCM::yaw_error_compass().
template<typename T > void Matrix3< T >::normalize (void)
Definition at line 161 of file matrix3.cpp.
Referenced by SITL::Gimbal::update(), SITL::Tracker::update(), SITL::SimRover::update(), SITL::Balloon::update(), SITL::Helicopter::update(), and SITL::MultiCopter::update().
template<typename T> bool Matrix3< T >::operator!= (const Matrix3< T > & m) inline
Definition at line 79 of file matrix3.h.
template<typename T> void Matrix3< T >::operator() (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 67 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator* (const T num) const inline
Definition at line 111 of file matrix3.h.
template<typename T> Vector3< T > Matrix3< T >::operator* (const Vector3< T > & v) const
Definition at line 174 of file matrix3.cpp.
template<typename T> Matrix3< T > Matrix3< T >::operator* (const Matrix3< T > & m) const
Definition at line 200 of file matrix3.cpp.
template<typename T> Matrix3<T>& Matrix3< T >::operator*= (const T num) inline
Definition at line 115 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator*= (const Matrix3< T > & m) inline
Definition at line 175 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator+ (const Matrix3< T > & m) const inline
Definition at line 91 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator+= (const Matrix3< T > & m) inline
Definition at line 95 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator- (void) const inline
Definition at line 85 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator- (const Matrix3< T > & m) const inline
Definition at line 101 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator-= (const Matrix3< T > & m) inline
Definition at line 105 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator/ (const T num) const inline
Definition at line 119 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator/= (const T num) inline
Definition at line 123 of file matrix3.h.
template<typename T> bool Matrix3< T >::operator== (const Matrix3< T > & m) inline
Definition at line 73 of file matrix3.h.
template<typename T> Vector3<T>& Matrix3< T >::operator[] (uint8_t i) inline
Definition at line 129 of file matrix3.h.
template<typename T> const Vector3<T>& Matrix3< T >::operator[] (uint8_t i) const inline
Definition at line 137 of file matrix3.h.
template<typename T> template void Matrix3< T >::rotate (const Vector3< T > & g)
Definition at line 103 of file matrix3.cpp.
Referenced by AP_AHRS_DCM::matrix_update(), test_matrix_rotate(), test_rotation_accuracy(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::Balloon::update(), SITL::Helicopter::update(), SITL::SimRover::update(), and SITL::MultiCopter::update().
template<typename T> template void Matrix3< T >::rotateXY (const Vector3< T > & g)
Definition at line 122 of file matrix3.cpp.
template<typename T> template void Matrix3< T >::rotateXYinv (const Vector3< T > & g)
Definition at line 141 of file matrix3.cpp.
Referenced by AP_AHRS_DCM::euler_angles(), NavEKF2_core::getRotationBodyToNED(), and NavEKF_core::getRotationBodyToNED().
template<typename T > template void Matrix3< T >::to_euler (float * roll, float * pitch, float * yaw) const
Definition at line 50 of file matrix3.cpp.
Referenced by SITL::SITL::convert_earth_frame(), SITL::JSBSim::create_templates(), AP_AHRS_DCM::euler_angles(), SITL::Aircraft::fill_fdm(), SITL::Aircraft::set_yaw_degrees(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_quaternion(), test_rotation_accuracy(), SITL::Tracker::update(), SITL::Balloon::update(), SITL::Helicopter::update(), and SITL::MultiCopter::update().
template<typename T > Vector3< T > Matrix3< T >::to_euler312 () const
Definition at line 69 of file matrix3.cpp.
Referenced by Quaternion::to_vector312(), and SITL::Gimbal::update().
template<typename T> void Matrix3< T >::transpose (void) inline
Definition at line 183 of file matrix3.h.
Referenced by AP_Mount_Servo::stabilize().
template<typename T > template Matrix3< double > Matrix3< T >::transposed (void) const
Definition at line 215 of file matrix3.cpp.
Referenced by SmallEKF::alignHeading(), have_rotation(), Matrix3< float >::transpose(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::Balloon::update(), SITL::Helicopter::update(), SITL::SimRover::update(), SITL::MultiCopter::update(), NavEKF_core::UpdateStrapdownEquationsNED(), NavEKF2_core::UpdateStrapdownEquationsNED(), NavEKF2_core::writeOptFlowMeas(), and NavEKF_core::writeOptFlowMeas().
template<typename T > template void Matrix3< T >::zero (void)
Definition at line 223 of file matrix3.cpp.
Referenced by NavEKF_core::InitialiseVariables(), and NavEKF2_core::InitialiseVariables().
Member Data Documentation
template<typename T> Vector3<T> Matrix3< T >::a
Definition at line 51 of file matrix3.h.
Referenced by AP_TECS::_update_throttle(), AP_TECS::_update_throttle_option(), Quaternion::from_rotation_matrix(), AP_Airspeed::log_mavlink_send(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator!=(), Matrix3< T >::operator*(), Matrix3< float >::operator+(), Matrix3< float >::operator-(), Matrix3< float >::operator==(), Matrix3< float >::operator[](), Matrix3< T >::rotate(), Matrix3< T >::rotateXY(), Matrix3< T >::rotateXYinv(), Quaternion::rotation_matrix(), test_matrix_rotate(), Airspeed_Calibration::update(), and AP_AHRS::update_trig().
template<typename T> Vector3<T> Matrix3< T >::b
Definition at line 51 of file matrix3.h.
Referenced by AP_TECS::_update_throttle(), AP_TECS::_update_throttle_option(), Quaternion::from_rotation_matrix(), AP_Airspeed::log_mavlink_send(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator!=(), Matrix3< T >::operator*(), Matrix3< float >::operator+(), Matrix3< float >::operator-(), Matrix3< float >::operator==(), Matrix3< T >::rotate(), Matrix3< T >::rotateXY(), Matrix3< T >::rotateXYinv(), Quaternion::rotation_matrix(), test_matrix_rotate(), Airspeed_Calibration::update(), and AP_AHRS::update_trig().
template<typename T> Vector3<T> Matrix3< T >::c
Definition at line 51 of file matrix3.h.
Referenced by HALSITL::SITL_State::_update_flow(), Compass::calculate_heading(), AP_AHRS_DCM::check_matrix(), AP_AHRS_DCM::drift_correction_yaw(), NavEKF_core::EstimateTerrainOffset(), NavEKF2_core::EstimateTerrainOffset(), Quaternion::from_rotation_matrix(), NavEKF_core::FuseOptFlow(), NavEKF2_core::FuseOptFlow(), NavEKF_core::FuseVelPosNED(), AP_AHRS::get_yaw_rate_earth(), AP_Airspeed::log_mavlink_send(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator!=(), Matrix3< T >::operator*(), Matrix3< float >::operator+(), Matrix3< float >::operator-(), Matrix3< float >::operator==(), NavEKF_core::readHgtData(), NavEKF2_core::readHgtData(), Matrix3< T >::rotate(), Matrix3< T >::rotateXY(), Matrix3< T >::rotateXYinv(), Quaternion::rotation_matrix(), NavEKF_core::SelectFlowFusion(), NavEKF2_core::SelectFlowFusion(), test_matrix_rotate(), Airspeed_Calibration::update(), SITL::Balloon::update(), AP_TECS::update_50hz(), and AP_AHRS::update_trig().
The documentation for this class was generated from the following files:
libraries/AP_Math/matrix3.h
libraries/AP_Math/matrix3.cpp