APM:Libraries: AP_InertialSensor_MPU9250 Class Reference
AP_InertialSensor_MPU9250 Class Reference
#include <AP_InertialSensor_MPU9250.h>
Public Member Functions
AP_InertialSensor_MPU9250 (AP_InertialSensor &imu, AP_MPU9250_BusDriver *bus)
bool update ()
bool gyro_sample_available (void)
bool accel_sample_available (void)
AuxiliaryBus * get_auxiliary_bus ()
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void start ()
int16_t product_id (void) const
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_MPU9250 & from (AP_InertialSensor_Backend &backend)
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu, AP_HAL::SPIDeviceDriver *spi)
static AP_InertialSensor_Backend * detect_i2c (AP_InertialSensor &imu, AP_HAL::I2CDriver *i2c, uint8_t addr)
Private Member Functions
bool _init_sensor ()
void _read_data_transaction ()
bool _data_ready ()
void _poll_data (void)
uint8_t _register_read (uint8_t reg)
void _register_write (uint8_t reg, uint8_t val)
bool _hardware_init (void)
bool _sample_available ()
void _set_accel_filter (uint8_t filter_hz)
void _set_gyro_filter (uint8_t filter_hz)
Static Private Member Functions
static AP_InertialSensor_Backend * _detect (AP_InertialSensor &_imu, AP_MPU9250_BusDriver *bus, int16_t id)
Private Attributes
friend AP_MPU9250_AuxiliaryBus
friend AP_MPU9250_AuxiliaryBusSlave
AP_MPU9250_BusDriver * _bus
AP_HAL::Semaphore * _bus_sem
AP_MPU9250_AuxiliaryBus * _auxiliar_bus = nullptr
int16_t _last_gyro_filter_hz
int16_t _last_accel_filter_hz
struct {
Vector3f _accel_filtered
Vector3f _gyro_filtered
} _shared_data [2]
volatile uint8_t _shared_data_idx
LowPassFilter2pVector3f _accel_filter
LowPassFilter2pVector3f _gyro_filter
bool _have_sample_available
uint8_t _gyro_instance
uint8_t _accel_instance
enum Rotation _default_rotation
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
void _set_accel_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint32_t rate)
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
int16_t _product_id
int16_t _id = -1
Detailed Description
Definition at line 35 of file AP_InertialSensor_MPU9250.h.
Constructor & Destructor Documentation
AP_InertialSensor_MPU9250::AP_InertialSensor_MPU9250 (AP_InertialSensor & imu, AP_MPU9250_BusDriver * bus)
Definition at line 363 of file AP_InertialSensor_MPU9250.cpp.
Referenced by _detect().
Member Function Documentation
bool AP_InertialSensor_MPU9250::_data_ready () private
AP_InertialSensor_Backend * AP_InertialSensor_MPU9250::_detect (AP_InertialSensor & _imu, AP_MPU9250_BusDriver * bus, int16_t id) static private
Definition at line 410 of file AP_InertialSensor_MPU9250.cpp.
Referenced by detect(), and detect_i2c().
bool AP_InertialSensor_MPU9250::_hardware_init (void) private
Definition at line 585 of file AP_InertialSensor_MPU9250.cpp.
Referenced by _init_sensor().
bool AP_InertialSensor_MPU9250::_init_sensor (void) private
Definition at line 433 of file AP_InertialSensor_MPU9250.cpp.
Referenced by _detect().
void AP_InertialSensor_MPU9250::_poll_data (void) private
Timer process to poll for new data from the MPU9250.
Definition at line 490 of file AP_InertialSensor_MPU9250.cpp.
Referenced by _init_sensor().
void AP_InertialSensor_MPU9250::_read_data_transaction () private
Definition at line 508 of file AP_InertialSensor_MPU9250.cpp.
Referenced by _poll_data().
uint8_t AP_InertialSensor_MPU9250::_register_read (uint8_t reg) private
Definition at line 550 of file AP_InertialSensor_MPU9250.cpp.
Referenced by AP_MPU9250_AuxiliaryBus::_configure_slaves(), and _hardware_init().
void AP_InertialSensor_MPU9250::_register_write (uint8_t reg, uint8_t val) private
Definition at line 560 of file AP_InertialSensor_MPU9250.cpp.
Referenced by AP_MPU9250_AuxiliaryBus::_configure_slaves(), _hardware_init(), AP_MPU9250_AuxiliaryBusSlave::_set_passthrough(), AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), and AP_MPU9250_AuxiliaryBusSlave::passthrough_write().
bool AP_InertialSensor_MPU9250::_sample_available () private
void AP_InertialSensor_MPU9250::_set_accel_filter (uint8_t filter_hz) private
Definition at line 568 of file AP_InertialSensor_MPU9250.cpp.
Referenced by update().
void AP_InertialSensor_MPU9250::_set_gyro_filter (uint8_t filter_hz) private
Definition at line 576 of file AP_InertialSensor_MPU9250.cpp.
Referenced by update().
bool AP_InertialSensor_MPU9250::accel_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 48 of file AP_InertialSensor_MPU9250.h.
AP_InertialSensor_Backend * AP_InertialSensor_MPU9250::detect (AP_InertialSensor & imu, AP_HAL::SPIDeviceDriver * spi) static
Definition at line 390 of file AP_InertialSensor_MPU9250.cpp.
Referenced by AP_InertialSensor::detect_backends().
AP_InertialSensor_Backend * AP_InertialSensor_MPU9250::detect_i2c (AP_InertialSensor & imu, AP_HAL::I2CDriver * i2c, uint8_t addr) static
Definition at line 398 of file AP_InertialSensor_MPU9250.cpp.
Referenced by AP_InertialSensor::detect_backends().
static AP_InertialSensor_MPU9250& AP_InertialSensor_MPU9250::from (AP_InertialSensor_Backend & backend) inline static
Definition at line 52 of file AP_InertialSensor_MPU9250.h.
Referenced by AP_MPU9250_AuxiliaryBus::_configure_slaves(), AP_MPU9250_AuxiliaryBusSlave::_set_passthrough(), AP_MPU9250_AuxiliaryBus::get_semaphore(), AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), AP_MPU9250_AuxiliaryBusSlave::passthrough_write(), and AP_MPU9250_AuxiliaryBusSlave::read().
AuxiliaryBus * AP_InertialSensor_MPU9250::get_auxiliary_bus () virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 690 of file AP_InertialSensor_MPU9250.cpp.
bool AP_InertialSensor_MPU9250::gyro_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 47 of file AP_InertialSensor_MPU9250.h.
bool AP_InertialSensor_MPU9250::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 460 of file AP_InertialSensor_MPU9250.cpp.
Member Data Documentation
LowPassFilter2pVector3f AP_InertialSensor_MPU9250::_accel_filter private
Definition at line 99 of file AP_InertialSensor_MPU9250.h.
Referenced by _read_data_transaction(), and _set_accel_filter().
Vector3f AP_InertialSensor_MPU9250::_accel_filtered
Definition at line 93 of file AP_InertialSensor_MPU9250.h.
uint8_t AP_InertialSensor_MPU9250::_accel_instance private
Definition at line 107 of file AP_InertialSensor_MPU9250.h.
Referenced by _init_sensor(), _read_data_transaction(), and update().
AP_MPU9250_AuxiliaryBus* AP_InertialSensor_MPU9250::_auxiliar_bus = nullptr private
Definition at line 78 of file AP_InertialSensor_MPU9250.h.
Referenced by get_auxiliary_bus().
AP_MPU9250_BusDriver* AP_InertialSensor_MPU9250::_bus private
Definition at line 76 of file AP_InertialSensor_MPU9250.h.
Referenced by _hardware_init(), _init_sensor(), _read_data_transaction(), _register_read(), _register_write(), get_auxiliary_bus(), AP_MPU9250_AuxiliaryBusSlave::passthrough_read(), and AP_MPU9250_AuxiliaryBusSlave::read().
AP_HAL::Semaphore* AP_InertialSensor_MPU9250::_bus_sem private
Definition at line 77 of file AP_InertialSensor_MPU9250.h.
Referenced by _hardware_init(), _init_sensor(), _poll_data(), and AP_MPU9250_AuxiliaryBus::get_semaphore().
enum Rotation AP_InertialSensor_MPU9250::_default_rotation private
Definition at line 111 of file AP_InertialSensor_MPU9250.h.
Referenced by _read_data_transaction().
LowPassFilter2pVector3f AP_InertialSensor_MPU9250::_gyro_filter private
Definition at line 100 of file AP_InertialSensor_MPU9250.h.
Referenced by _read_data_transaction(), and _set_gyro_filter().
Vector3f AP_InertialSensor_MPU9250::_gyro_filtered
Definition at line 94 of file AP_InertialSensor_MPU9250.h.
uint8_t AP_InertialSensor_MPU9250::_gyro_instance private
Definition at line 106 of file AP_InertialSensor_MPU9250.h.
Referenced by _init_sensor(), _read_data_transaction(), and update().
bool AP_InertialSensor_MPU9250::_have_sample_available private
Definition at line 103 of file AP_InertialSensor_MPU9250.h.
Referenced by _read_data_transaction(), accel_sample_available(), gyro_sample_available(), and update().
int16_t AP_InertialSensor_MPU9250::_last_accel_filter_hz private
Definition at line 82 of file AP_InertialSensor_MPU9250.h.
Referenced by update().
int16_t AP_InertialSensor_MPU9250::_last_gyro_filter_hz private
Definition at line 81 of file AP_InertialSensor_MPU9250.h.
Referenced by update().
struct { ... } AP_InertialSensor_MPU9250::_shared_data[2]
Referenced by _read_data_transaction(), and update().
volatile uint8_t AP_InertialSensor_MPU9250::_shared_data_idx private
Definition at line 96 of file AP_InertialSensor_MPU9250.h.
Referenced by _read_data_transaction(), and update().
friend AP_InertialSensor_MPU9250::AP_MPU9250_AuxiliaryBus private
Definition at line 37 of file AP_InertialSensor_MPU9250.h.
Referenced by get_auxiliary_bus().
friend AP_InertialSensor_MPU9250::AP_MPU9250_AuxiliaryBusSlave private
Definition at line 38 of file AP_InertialSensor_MPU9250.h.
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_MPU9250.h
libraries/AP_InertialSensor/AP_InertialSensor_MPU9250.cpp