APM:Libraries: AP_Compass_Backend Class Reference
AP_Compass_Backend Class Reference abstract
#include <AP_Compass_Backend.h>
Public Member Functions
AP_Compass_Backend (Compass &compass)
virtual ~AP_Compass_Backend (void)
virtual bool init (void)=0
virtual void read (void)=0
virtual void accumulate (void)
Protected Member Functions
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_unfiltered_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void set_external (uint8_t instance, bool external)
Protected Attributes
Compass & _compass
Private Member Functions
void apply_corrections (Vector3f &mag, uint8_t i)
Detailed Description
Definition at line 27 of file AP_Compass_Backend.h.
Constructor & Destructor Documentation
AP_Compass_Backend::AP_Compass_Backend (Compass & compass)
Definition at line 9 of file AP_Compass_Backend.cpp.
virtual AP_Compass_Backend::~AP_Compass_Backend (void) inline virtual
Definition at line 34 of file AP_Compass_Backend.h.
Member Function Documentation
virtual void AP_Compass_Backend::accumulate (void) inline virtual
Reimplemented in AP_Compass_HMC5843, AP_Compass_AK8963, and AP_Compass_PX4.
Definition at line 44 of file AP_Compass_Backend.h.
Referenced by Compass::accumulate().
void AP_Compass_Backend::apply_corrections (Vector3f & mag, uint8_t i) private
void AP_Compass_Backend::correct_field (Vector3f & mag, uint8_t i) protected
Definition at line 60 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM303D::_collect_samples(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), AP_Compass_HMC5843::accumulate(), and AP_Compass_HIL::read().
virtual bool AP_Compass_Backend::init (void) pure virtual
Implemented in AP_Compass_HMC5843, AP_Compass_AK8963, AP_Compass_LSM303D, AP_Compass_HIL, and AP_Compass_PX4.
void AP_Compass_Backend::publish_filtered_field (const Vector3f & mag, uint8_t instance) protected
Definition at line 107 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_HIL::read(), AP_Compass_PX4::read(), AP_Compass_LSM303D::read(), AP_Compass_AK8963::read(), and AP_Compass_HMC5843::read().
void AP_Compass_Backend::publish_raw_field (const Vector3f & mag, uint32_t time_us, uint8_t instance) protected
Definition at line 42 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM303D::_collect_samples(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), AP_Compass_HMC5843::accumulate(), and AP_Compass_HIL::read().
void AP_Compass_Backend::publish_unfiltered_field (const Vector3f & mag, uint32_t time_us, uint8_t instance) protected
Definition at line 94 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM303D::_collect_samples(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), and AP_Compass_HMC5843::accumulate().
virtual void AP_Compass_Backend::read (void) pure virtual
Implemented in AP_Compass_HMC5843, AP_Compass_AK8963, AP_Compass_LSM303D, AP_Compass_HIL, and AP_Compass_PX4.
Referenced by Compass::read().
uint8_t AP_Compass_Backend::register_compass (void) const protected
Definition at line 127 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_PX4::init(), AP_Compass_HIL::init(), AP_Compass_LSM303D::init(), AP_Compass_AK8963::init(), and AP_Compass_HMC5843::init().
void AP_Compass_Backend::rotate_field (Vector3f & mag, uint8_t instance) protected
Definition at line 28 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM303D::_collect_samples(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), AP_Compass_HMC5843::accumulate(), and AP_Compass_HIL::read().
void AP_Compass_Backend::set_dev_id (uint8_t instance, uint32_t dev_id) protected
Definition at line 136 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_PX4::init(), AP_Compass_AK8963::init(), AP_Compass_LSM303D::init(), and AP_Compass_HMC5843::init().
void AP_Compass_Backend::set_external (uint8_t instance, bool external) protected
Definition at line 144 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_PX4::init(), AP_Compass_LSM303D::init(), and AP_Compass_HMC5843::init().
Member Data Documentation
Compass& AP_Compass_Backend::_compass protected
Definition at line 79 of file AP_Compass_Backend.h.
Referenced by AP_Compass_HIL::AP_Compass_HIL(), correct_field(), publish_filtered_field(), publish_raw_field(), publish_unfiltered_field(), AP_Compass_HIL::read(), register_compass(), rotate_field(), set_dev_id(), and set_external().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_Backend.h
libraries/AP_Compass/AP_Compass_Backend.cpp