APM:Libraries: Linux::SPIDeviceManager Class Reference
Linux::SPIDeviceManager Class Reference
#include <SPIDriver.h>
Public Member Functions
void init (void *)
AP_HAL::SPIDeviceDriver * device (enum AP_HAL::SPIDevice, uint8_t index=0)
Static Public Member Functions
static AP_HAL::Semaphore * get_semaphore (uint16_t bus)
static void cs_assert (enum AP_HAL::SPIDevice type)
static void cs_release (enum AP_HAL::SPIDevice type)
static bool transaction (SPIDeviceDriver &driver, const uint8_t *tx, uint8_t *rx, uint16_t len)
Static Private Attributes
static SPIDeviceDriver _device []
static Semaphore _semaphore [LINUX_SPI_MAX_BUSES]
Detailed Description
Definition at line 49 of file SPIDriver.h.
Member Function Documentation
void SPIDeviceManager::cs_assert (enum AP_HAL::SPIDevice type) static
Definition at line 171 of file SPIDriver.cpp.
Referenced by Linux::SPIDeviceDriver::cs_assert(), and transaction().
void SPIDeviceManager::cs_release (enum AP_HAL::SPIDevice type) static
Definition at line 207 of file SPIDriver.cpp.
Referenced by Linux::SPIDeviceDriver::cs_release(), and transaction().
AP_HAL::SPIDeviceDriver * SPIDeviceManager::device (enum AP_HAL::SPIDevice dev, uint8_t index = 0) virtual
Implements AP_HAL::SPIDeviceManager.
Definition at line 274 of file SPIDriver.cpp.
AP_HAL::Semaphore * SPIDeviceManager::get_semaphore (uint16_t bus) static
Definition at line 292 of file SPIDriver.cpp.
Referenced by Linux::SPIDeviceDriver::get_semaphore().
void SPIDeviceManager::init (void *) virtual
Implements AP_HAL::SPIDeviceManager.
Definition at line 149 of file SPIDriver.cpp.
bool SPIDeviceManager::transaction (SPIDeviceDriver & driver, const uint8_t * tx, uint8_t * rx, uint16_t len) static
Definition at line 233 of file SPIDriver.cpp.
Referenced by Linux::SPIDeviceDriver::transaction().
Member Data Documentation
SPIDeviceDriver SPIDeviceManager::_device static private
Initial value:
= {
    SPIDeviceDriver(1, 0, AP_HAL::SPIDevice_LSM9DS0_AM, SPI_MODE_3, 8, BBB_P9_17,  10*MHZ,10*MHZ),
    SPIDeviceDriver(1, 0, AP_HAL::SPIDevice_LSM9DS0_G,  SPI_MODE_3, 8, BBB_P8_9,   10*MHZ,10*MHZ),
    SPIDeviceDriver(2, 0, AP_HAL::SPIDevice_MS5611,     SPI_MODE_3, 8, BBB_P9_42,  10*MHZ,10*MHZ),
    SPIDeviceDriver(2, 0, AP_HAL::SPIDevice_MPU6000,    SPI_MODE_3, 8, BBB_P9_28,  500*1000, 20*MHZ),
    SPIDeviceDriver(2, 0, AP_HAL::SPIDevice_MPU9250,    SPI_MODE_3, 8, BBB_P9_23,  1*MHZ, 20*MHZ),
    SPIDeviceDriver(2, 0, AP_HAL::SPIDevice_Dataflash,  SPI_MODE_3, 8, BBB_P8_12,  6*MHZ, 6*MHZ),
}
Definition at line 61 of file SPIDriver.h.
Referenced by cs_assert(), cs_release(), device(), and init().
Semaphore SPIDeviceManager::_semaphore static private
Definition at line 62 of file SPIDriver.h.
Referenced by get_semaphore().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/SPIDriver.h
libraries/AP_HAL_Linux/SPIDriver.cpp