APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/testsuite.h File Reference
testsuite.h File Reference
MAVLink comm protocol testsuite generated from common.xml.
Macros
#define MAVLINK_TEST_ALL
Functions
static void mavlink_test_common (uint8_t, uint8_t, mavlink_message_t *last_msg)
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_heartbeat (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_sys_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_system_time (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ping (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_change_operator_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_change_operator_control_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_auth_key (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_mode (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_request_read (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_value (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_set (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_raw_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_raw_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_raw_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_attitude (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_attitude_quaternion (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_local_position_ned (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_global_position_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels_scaled (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_servo_output_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_request_partial_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_write_partial_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_item (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_request (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_set_current (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_current (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_count (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_clear_all (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_item_reached (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_gps_global_origin (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_global_origin (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_map_rc (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_safety_set_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_safety_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_attitude_quaternion_cov (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_nav_controller_output (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_global_position_int_cov (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_local_position_ned_cov (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_request_data_stream (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_data_stream (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_manual_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels_override (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mission_item_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_vfr_hud (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_command_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_command_long (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_command_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_manual_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_attitude_target (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_attitude_target (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_position_target_local_ned (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_position_target_local_ned (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_position_target_global_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_position_target_global_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_local_position_ned_system_global_offset (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_state (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_controls (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_rc_inputs_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_optical_flow (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_global_vision_position_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_vision_position_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_vision_speed_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_vicon_position_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_highres_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_optical_flow_rad (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_sensor (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_sim_state (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_radio_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_file_transfer_protocol (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_timesync (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_gps (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_optical_flow (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_state_quaternion (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_imu2 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_log_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_log_entry (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_log_request_data (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_log_data (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_log_erase (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_log_request_end (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_inject_data (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps2_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_power_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_serial_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_rtk (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps2_rtk (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_imu3 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_data_transmission_handshake (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_encapsulated_data (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_distance_sensor (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_terrain_request (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_terrain_data (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_terrain_check (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_terrain_report (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_pressure2 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_att_pos_mocap (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_actuator_control_target (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_actuator_control_target (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_pressure3 (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_battery_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_autopilot_version (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_landing_target (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_vibration (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_home_position (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_home_position (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_v2_extension (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_memory_vect (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_debug_vect (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_named_value_float (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_named_value_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_statustext (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_debug (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
Detailed Description
MAVLink comm protocol testsuite generated from common.xml.
See also
http://qgroundcontrol.org/mavlink/
Definition in file testsuite.h.
Macro Definition Documentation
#define MAVLINK_TEST_ALL
Definition at line 13 of file testsuite.h.
Function Documentation
static void mavlink_test_actuator_control_target (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5218 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 17 of file testsuite.h.
static void mavlink_test_att_pos_mocap (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5124 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_attitude (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 880 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_attitude_quaternion (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 929 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_attitude_quaternion_cov (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1981 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_attitude_target (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2795 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_auth_key (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 311 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_autopilot_version (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5360 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_battery_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5309 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_change_operator_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 220 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_change_operator_control_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 266 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_command_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2651 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_command_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2543 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_command_long (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2598 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_common (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5936 of file testsuite.h.
Referenced by mavlink_test_all().
static void mavlink_test_data_stream (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2294 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_data_transmission_handshake (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4749 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_debug (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5891 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_debug_vect (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5710 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_distance_sensor (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4842 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_encapsulated_data (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4798 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_file_transfer_protocol (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3811 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_global_position_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1028 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_global_position_int_cov (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2079 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_global_vision_position_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3338 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps2_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4440 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps2_rtk (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4642 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_global_origin (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1785 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_inject_data (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4394 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_raw_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 583 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_rtk (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4587 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 635 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_heartbeat (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 27 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_highres_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3531 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_controls (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3179 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_gps (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3901 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_optical_flow (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3956 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_rc_inputs_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3232 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_sensor (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3642 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_state (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3121 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_state_quaternion (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4010 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_home_position (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5512 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_landing_target (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5413 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_local_position_ned (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 979 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_local_position_ned_cov (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2132 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_local_position_ned_system_global_offset (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3072 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_log_data (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4260 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_log_entry (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4166 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_log_erase (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4306 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_log_request_data (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4213 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_log_request_end (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4350 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_log_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4120 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_manual_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2339 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_manual_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2695 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_memory_vect (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5664 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1694 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_clear_all (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1607 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_count (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1562 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_current (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1475 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_item (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1329 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_item_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2439 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_item_reached (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1651 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_request (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1385 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1518 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_request_partial_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1237 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_set_current (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1430 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_mission_write_partial_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1283 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_named_value_float (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5757 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_named_value_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5802 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_nav_controller_output (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2029 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_optical_flow (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3288 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_optical_flow_rad (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3588 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_map_rc (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1830 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 445 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_request_read (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 399 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_set (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 536 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_value (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 489 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_ping (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 174 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_position_target_global_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3016 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_position_target_local_ned (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2902 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_power_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4494 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_radio_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3762 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_raw_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 735 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_raw_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 787 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2184 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels_override (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2387 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1132 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels_scaled (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1079 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_request_data_stream (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2247 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_safety_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1932 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_safety_set_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1881 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 683 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_imu2 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4068 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_imu3 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4697 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 834 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_pressure2 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5078 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_pressure3 (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5263 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_serial_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4539 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_servo_output_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1185 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_actuator_control_target (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5171 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_attitude_target (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2744 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_gps_global_origin (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1739 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_home_position (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5564 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_mode (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 354 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_position_target_global_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2958 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_position_target_local_ned (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2844 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_sim_state (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3699 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_statustext (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5847 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_sys_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 75 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_system_time (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 130 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_terrain_check (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4985 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_terrain_data (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4938 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_terrain_report (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5029 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_terrain_request (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 4892 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_timesync (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3857 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_v2_extension (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5617 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_vfr_hud (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2495 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_vibration (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 5463 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_vicon_position_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3482 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_vision_position_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3387 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_vision_speed_estimate (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3436 of file testsuite.h.
Referenced by mavlink_test_common().