APM:Libraries: libraries/AP_Math/edc.cpp File Reference
edc.cpp File Reference
#include "edc.h"
#include <AP_Progmem/AP_Progmem.h>
Functions
uint16_t crc16_ccitt (const uint8_t *buf, uint32_t len, uint16_t crc)
Variables
static const uint16_t crc16tab [256]
Function Documentation
uint16_t crc16_ccitt (const uint8_t * buf, uint32_t len, uint16_t crc)
Definition at line 53 of file edc.cpp.
Referenced by AP_GPS_SBP::_detect(), AP_GPS_SBP::_sbp_process(), HALSITL::SITL_State::_sbp_send_message(), and AP_GPS_SBF::parse().
Variable Documentation
const uint16_t crc16tab[256] static
Definition at line 18 of file edc.cpp.
Referenced by crc16_ccitt().