APM:Libraries: libraries/AP_Math/examples/eulers/eulers.cpp File Reference
eulers.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>
Macros
#define SHOW_POLES_BREAKDOWN 0
Functions
static float rad_diff (float rad1, float rad2)
static void check_result (const char *msg, float roll, float pitch, float yaw, float roll2, float pitch2, float yaw2)
static void test_euler (float roll, float pitch, float yaw)
void test_matrix_eulers (void)
static void test_quaternion (float roll, float pitch, float yaw)
void test_quaternion_eulers (void)
static void test_conversion (float roll, float pitch, float yaw)
void test_conversions (void)
void test_frame_transforms (void)
static float rand_num (void)
void test_matrix_rotate (void)
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static const float angles []
Macro Definition Documentation
#define SHOW_POLES_BREAKDOWN 0
Definition at line 11 of file eulers.cpp.
Function Documentation
AP_HAL_MAIN ()
static void check_result (const char * msg, float roll, float pitch, float yaw, float roll2, float pitch2, float yaw2) static
Definition at line 25 of file eulers.cpp.
Referenced by test_conversion(), test_euler(), and test_quaternion().
void loop (void)
Definition at line 296 of file eulers.cpp.
static float rad_diff (float rad1, float rad2) static
Definition at line 13 of file eulers.cpp.
Referenced by check_result().
static float rand_num (void) static
Definition at line 235 of file eulers.cpp.
Referenced by test_matrix_rotate().
void setup (void)
Definition at line 283 of file eulers.cpp.
static void test_conversion (float roll, float pitch, float yaw) static
Definition at line 156 of file eulers.cpp.
Referenced by setup(), and test_conversions().
void test_conversions (void)
Definition at line 182 of file eulers.cpp.
Referenced by setup().
static void test_euler (float roll, float pitch, float yaw) static
Definition at line 70 of file eulers.cpp.
Referenced by test_matrix_eulers().
void test_frame_transforms (void)
Definition at line 203 of file eulers.cpp.
Referenced by setup().
void test_matrix_eulers (void)
Definition at line 83 of file eulers.cpp.
Referenced by setup().
void test_matrix_rotate (void)
Definition at line 241 of file eulers.cpp.
Referenced by setup().
static void test_quaternion (float roll, float pitch, float yaw) static
Definition at line 98 of file eulers.cpp.
Referenced by test_quaternion_eulers().
void test_quaternion_eulers (void)
Definition at line 122 of file eulers.cpp.
Referenced by setup().
Variable Documentation
const float angles[] static
Initial value:
= { 0, PI/8, PI/4, PI/2, PI,
                                -PI/8, -PI/4, -PI/2, -PI}
Definition at line 80 of file eulers.cpp.
Referenced by test_conversions(), test_matrix_eulers(), and test_quaternion_eulers().
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 9 of file eulers.cpp.