APM:Libraries: libraries/RC_Channel/examples/RC_Channel/RC_Channel.cpp File Reference
RC_Channel.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <RC_Channel/RC_Channel.h>
Macros
#define CH_1 0
#define CH_2 1
#define CH_3 2
#define CH_4 3
#define CH_5 4
#define CH_6 5
#define CH_7 6
#define CH_8 7
#define NUM_CHANNELS 8
Functions
static void print_pwm (void)
static void print_radio_values ()
static void copy_input_output (void)
void setup ()
void loop ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static RC_Channel rc_1 (CH_1)
static RC_Channel rc_2 (CH_2)
static RC_Channel rc_3 (CH_3)
static RC_Channel rc_4 (CH_4)
static RC_Channel rc_5 (CH_5)
static RC_Channel rc_6 (CH_6)
static RC_Channel rc_7 (CH_7)
static RC_Channel rc_8 (CH_8)
static RC_Channel * rc = &rc_1
Macro Definition Documentation
#define CH_1 0
Definition at line 5 of file RC_Channel.cpp.
#define CH_2 1
Definition at line 6 of file RC_Channel.cpp.
#define CH_3 2
Definition at line 7 of file RC_Channel.cpp.
#define CH_4 3
Definition at line 8 of file RC_Channel.cpp.
#define CH_5 4
Definition at line 9 of file RC_Channel.cpp.
#define CH_6 5
Definition at line 10 of file RC_Channel.cpp.
#define CH_7 6
Definition at line 11 of file RC_Channel.cpp.
#define CH_8 7
Definition at line 12 of file RC_Channel.cpp.
#define NUM_CHANNELS 8
Definition at line 19 of file RC_Channel.cpp.
Referenced by copy_input_output(), print_pwm(), print_radio_values(), and setup().
Function Documentation
AP_HAL_MAIN ()
static void copy_input_output (void) static
Definition at line 102 of file RC_Channel.cpp.
Referenced by loop().
void loop (void)
Definition at line 69 of file RC_Channel.cpp.
static void print_pwm (void) static
Definition at line 79 of file RC_Channel.cpp.
Referenced by loop().
static void print_radio_values () static
Definition at line 88 of file RC_Channel.cpp.
Referenced by setup().
void setup (void)
Definition at line 36 of file RC_Channel.cpp.
Variable Documentation
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 17 of file RC_Channel.cpp.
RC_Channel* rc = &rc_1 static
Definition at line 29 of file RC_Channel.cpp.
Referenced by ADS1115AnalogIn::_update(), DigitalLPF< T >::apply(), AC_PI_2D::calc_filt_alpha(), and AC_PID::get_filt_alpha().
RC_Channel rc_1(CH_1) static
Referenced by setup().
RC_Channel rc_2(CH_2) static
Referenced by setup().
RC_Channel rc_3(CH_3) static
Referenced by setup().
RC_Channel rc_4(CH_4) static
Referenced by setup().
RC_Channel rc_5(CH_5) static
Referenced by setup().
RC_Channel rc_6(CH_6) static
Referenced by setup().
RC_Channel rc_7(CH_7) static
Referenced by setup().
RC_Channel rc_8(CH_8) static
Referenced by setup().