APM:Libraries: libraries/AP_HAL_FLYMAPLE/utility/flash_stm32.h File Reference
flash_stm32.h File Reference
Macros
#define IS_FLASH_ADDRESS(ADDRESS) (((ADDRESS) >= 0x08000000) && ((ADDRESS) < 0x0807FFFF))
Enumerations
enum FLASH_Status {
FLASH_BUSY = 1, FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_ERROR_OPT,
FLASH_COMPLETE, FLASH_TIMEOUT, FLASH_BAD_ADDRESS, FLASH_ERROR_PGS,
FLASH_ERROR_PGP, FLASH_ERROR_PGA, FLASH_ERROR_PROGRAM, FLASH_ERROR_OPERATION
}
Functions
FLASH_Status FLASH_WaitForLastOperation (uint32 Timeout)
Waits for a Flash operation to complete or a TIMEOUT to occur.
FLASH_Status FLASH_ErasePage (uint32 Page_Address)
Erases a specified FLASH page.
FLASH_Status FLASH_ProgramHalfWord (uint32 Address, uint16 Data)
Programs a half word at a specified address.
void FLASH_Unlock (void)
Unlocks the FLASH Program Erase Controller.
void FLASH_Lock (void)
Locks the FLASH Program Erase Controller.
Macro Definition Documentation
#define IS_FLASH_ADDRESS (ADDRESS) (((ADDRESS) >= 0x08000000) && ((ADDRESS) < 0x0807FFFF))
Definition at line 24 of file flash_stm32.h.
Referenced by FLASH_ErasePage(), and FLASH_ProgramHalfWord().
Enumeration Type Documentation
enum FLASH_Status
Enumerator
FLASH_BUSY
FLASH_ERROR_PG
FLASH_ERROR_WRP
FLASH_ERROR_OPT
FLASH_COMPLETE
FLASH_TIMEOUT
FLASH_BAD_ADDRESS
FLASH_ERROR_PGS
FLASH_ERROR_PGP
FLASH_ERROR_PGA
FLASH_ERROR_PROGRAM
FLASH_ERROR_OPERATION
Definition at line 8 of file flash_stm32.h.
Function Documentation
FLASH_Status FLASH_ErasePage (uint32 Page_Address)
Erases a specified FLASH page.
Parameters
Page_Address The page address to be erased.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
Definition at line 124 of file flash_stm32F1.h.
Referenced by EEPROMClass::EE_ErasePage().
void FLASH_Lock (void)
Locks the FLASH Program Erase Controller.
Parameters
None
Return values
None Locks the FLASH Program Erase Controller.
Parameters
None
Return values
None
Definition at line 202 of file flash_stm32F1.h.
FLASH_Status FLASH_ProgramHalfWord (uint32 Address, uint16 Data)
Programs a half word at a specified address.
Parameters
Address specifies the address to be programmed.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
Programs a half word at a specified address.
Note
This function must be used when the device voltage range is from 2.1V to 3.6V.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 159 of file flash_stm32F1.h.
Referenced by EEPROMClass::EE_ErasePage(), EEPROMClass::EE_PageTransfer(), EEPROMClass::EE_VerifyPageFullWriteVariable(), EEPROMClass::format(), and EEPROMClass::init().
void FLASH_Unlock (void)
Unlocks the FLASH Program Erase Controller.
Parameters
None
Return values
None Unlocks the FLASH Program Erase Controller.
Parameters
None
Return values
None
Definition at line 190 of file flash_stm32F1.h.
Referenced by EEPROMClass::format(), and EEPROMClass::init().
FLASH_Status FLASH_WaitForLastOperation (uint32 Timeout)
Waits for a Flash operation to complete or a TIMEOUT to occur.
Parameters
Timeout FLASH progamming Timeout
Return values
FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
Definition at line 99 of file flash_stm32F1.h.
Referenced by FLASH_ErasePage(), FLASH_EraseSector(), and FLASH_ProgramHalfWord().