APM:Libraries: libraries/GCS_Console/GCS_Console.h File Reference
GCS_Console.h File Reference
#include <GCS_MAVLink/GCS_MAVLink.h>
Macros
#define DATAMSG_TYPE_CONSOLE 0xFE
Functions
void gcs_console_handle_data16 (mavlink_message_t *msg)
void gcs_console_handle_data32 (mavlink_message_t *msg)
void gcs_console_send (mavlink_channel_t chan)
Macro Definition Documentation
#define DATAMSG_TYPE_CONSOLE 0xFE
Definition at line 18 of file GCS_Console.h.
Referenced by gcs_console_handle_data16(), gcs_console_handle_data32(), and gcs_console_send().
Function Documentation
void gcs_console_handle_data16 (mavlink_message_t * msg)
Definition at line 7 of file GCS_Console.cpp.
Referenced by handle_message().
void gcs_console_handle_data32 (mavlink_message_t * msg)
Definition at line 17 of file GCS_Console.cpp.
Referenced by handle_message().
void gcs_console_send (mavlink_channel_t chan)
Definition at line 27 of file GCS_Console.cpp.
Referenced by loop().