APM:Libraries: libraries/AP_HAL_PX4/HAL_PX4_Class.h File Reference
HAL_PX4_Class.h File Reference
#include <AP_HAL/AP_HAL.h>
#include "AP_HAL_PX4.h"
#include "AP_HAL_PX4_Namespace.h"
#include <systemlib/visibility.h>
#include <systemlib/perf_counter.h>
Classes
class HAL_PX4
Functions
void hal_px4_set_priority (uint8_t priority)
Variables
const HAL_PX4 AP_HAL_PX4
Function Documentation
void hal_px4_set_priority (uint8_t priority)
Definition at line 98 of file HAL_PX4_Class.cpp.
Referenced by loop_overtime(), main_loop(), sem_post_boost(), and set_normal_priority().
Variable Documentation
const HAL_PX4 AP_HAL_PX4