APM:Libraries: libraries/AP_Math/location.cpp File Reference
location.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <stdlib.h>
#include "AP_Math.h"
Macros
#define LOCATION_SCALING_FACTOR 0.011131884502145034f
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#define LOCATION_SCALING_FACTOR_INV 89.83204953368922f
Functions
float longitude_scale (const struct Location &loc)
float get_distance (const struct Location &loc1, const struct Location &loc2)
uint32_t get_distance_cm (const struct Location &loc1, const struct Location &loc2)
int32_t get_bearing_cd (const struct Location &loc1, const struct Location &loc2)
bool location_passed_point (const struct Location &location, const struct Location &point1, const struct Location &point2)
float location_path_proportion (const struct Location &location, const struct Location &point1, const struct Location &point2)
void location_update (struct Location &loc, float bearing, float distance)
void location_offset (struct Location &loc, float ofs_north, float ofs_east)
Vector2f location_diff (const struct Location &loc1, const struct Location &loc2)
int32_t wrap_360_cd (int32_t error)
int32_t wrap_180_cd (int32_t error)
float wrap_360_cd_float (float angle)
float wrap_180_cd_float (float angle)
float wrap_PI (float angle_in_radians)
bool locations_are_same (const struct Location &loc1, const struct Location &loc2)
void print_latlon (AP_HAL::BetterStream *s, int32_t lat_or_lon)
void wgsllh2ecef (const Vector3d &llh, Vector3d &ecef)
void wgsecef2llh (const Vector3d &ecef, Vector3d &llh)
Macro Definition Documentation
#define LOCATION_SCALING_FACTOR 0.011131884502145034f
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 29 of file location.cpp.
Referenced by get_distance(), and location_diff().
#define LOCATION_SCALING_FACTOR_INV 89.83204953368922f
Definition at line 31 of file location.cpp.
Referenced by location_offset().
Function Documentation
int32_t get_bearing_cd (const struct Location & loc1, const struct Location & loc2)
Definition at line 72 of file location.cpp.
Referenced by AP_Mission::get_next_ground_course_cd(), test_one_offset(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
float get_distance (const struct Location & loc1, const struct Location & loc2)
Definition at line 58 of file location.cpp.
Referenced by AP_Rally::find_nearest_rally_point(), get_distance_cm(), AP_Mission::get_landing_sequence_start(), test_accuracy(), test_one_offset(), AP_Limit_Geofence::triggered(), and AP_Camera::update_location().
uint32_t get_distance_cm (const struct Location & loc1, const struct Location & loc2)
Definition at line 66 of file location.cpp.
Vector2f location_diff (const struct Location & loc1, const struct Location & loc2)
Definition at line 145 of file location.cpp.
Referenced by NavEKF_core::calcGpsGoodToAlign(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF2_core::getPosNED(), NavEKF_core::getPosNED(), location_path_proportion(), NavEKF_core::readGpsData(), NavEKF2_core::readGpsData(), SITL::CRRCSim::recv_fdm(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
void location_offset (struct Location & loc, float ofs_north, float ofs_east)
Definition at line 131 of file location.cpp.
Referenced by AP_AHRS_DCM::get_position(), NavEKF2_core::getLLH(), NavEKF_core::getLLH(), location_update(), and test_one_offset().
bool location_passed_point (const struct Location & location, const struct Location & point1, const struct Location & point2)
Definition at line 86 of file location.cpp.
Referenced by test_passed_waypoint().
float location_path_proportion (const struct Location & location, const struct Location & point1, const struct Location & point2)
Definition at line 100 of file location.cpp.
Referenced by location_passed_point().
void location_update (struct Location & loc, float bearing, float distance)
Definition at line 121 of file location.cpp.
Referenced by AP_AHRS_DCM::get_position(), and SITL::Aircraft::update_position().
bool locations_are_same (const struct Location & loc1, const struct Location & loc2)
Definition at line 224 of file location.cpp.
float longitude_scale (const struct Location & loc)
Definition at line 33 of file location.cpp.
Referenced by get_bearing_cd(), get_distance(), location_diff(), and location_offset().
void print_latlon (AP_HAL::BetterStream * s, int32_t lat_or_lon)
Definition at line 231 of file location.cpp.
Referenced by DataFlash_Backend::_print_log_entry(), and loop().
void wgsecef2llh (const Vector3d & ecef, Vector3d & llh)
Definition at line 259 of file location.cpp.
Referenced by test_wgs_conversion_functions().
void wgsllh2ecef (const Vector3d & llh, Vector3d & ecef)
Definition at line 249 of file location.cpp.
Referenced by test_wgs_conversion_functions().
int32_t wrap_180_cd (int32_t error)
Definition at line 168 of file location.cpp.
Referenced by AP_L1_Control::_prevent_indecision(), AP_L1_Control::nav_bearing_cd(), AP_L1_Control::target_bearing_cd(), test_wrap_cd(), AC_AttitudeControl::update_ef_pitch_angle_and_error(), AC_AttitudeControl::update_ef_roll_angle_and_error(), AC_AttitudeControl::update_ef_yaw_angle_and_error(), AP_L1_Control::update_heading_hold(), and AP_AHRS_DCM::use_compass().
float wrap_180_cd_float (float angle)
Definition at line 196 of file location.cpp.
Referenced by AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw_smooth(), AC_AttitudeControl::angle_ef_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and AC_AttitudeControl::rate_bf_roll_pitch_yaw().
int32_t wrap_360_cd (int32_t error)
Definition at line 154 of file location.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SIRF::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_NMEA::_term_complete(), DataFlash_Class::Log_Write_AHRS2(), SITL::SITL::Log_Write_SIMSTATE(), AP_GPS_SBF::process_message(), AP_GPS_PX4::read(), AP_GPS_MTK::read(), AP_GPS_MTK19::read(), AP_GPS::setHIL(), test_wrap_cd(), and AC_AttitudeControl::update_ef_yaw_angle_and_error().
float wrap_360_cd_float (float angle)
Definition at line 182 of file location.cpp.
Referenced by AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl::rate_bf_roll_pitch_yaw(), and AC_AttitudeControl::shift_ef_yaw_target().
float wrap_PI (float angle_in_radians)
Definition at line 210 of file location.cpp.
Referenced by NavEKF_core::alignYawGPS(), NavEKF2_core::alignYawGPS(), AP_Mount_Backend::calc_angle_to_location(), NavEKF_core::calcQuatAndFieldStates(), NavEKF2_core::calcQuatAndFieldStates(), AP_AHRS_DCM::drift_correction_yaw(), AC_Circle::init_start_angle(), test_wrap_cd(), Quaternion::to_axis_angle(), and AC_Circle::update().