APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_param_value.h File Reference
mavlink_msg_param_value.h File Reference
Classes
struct __mavlink_param_value_t
Macros
#define MAVLINK_MSG_ID_PARAM_VALUE 22
#define MAVLINK_MSG_ID_PARAM_VALUE_LEN 25
#define MAVLINK_MSG_ID_22_LEN 25
#define MAVLINK_MSG_ID_PARAM_VALUE_CRC 220
#define MAVLINK_MSG_ID_22_CRC 220
#define MAVLINK_MSG_PARAM_VALUE_FIELD_PARAM_ID_LEN 16
#define MAVLINK_MESSAGE_INFO_PARAM_VALUE
Typedefs
typedef struct __mavlink_param_value_t mavlink_param_value_t
Functions
static uint16_t mavlink_msg_param_value_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const char *param_id, float param_value, uint8_t param_type, uint16_t param_count, uint16_t param_index)
Pack a param_value message.
static uint16_t mavlink_msg_param_value_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const char *param_id, float param_value, uint8_t param_type, uint16_t param_count, uint16_t param_index)
Pack a param_value message on a channel.
static uint16_t mavlink_msg_param_value_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_param_value_t *param_value)
Encode a param_value struct.
static uint16_t mavlink_msg_param_value_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_param_value_t *param_value)
Encode a param_value struct on a channel.
static uint16_t mavlink_msg_param_value_get_param_id (const mavlink_message_t *msg, char *param_id)
Send a param_value message.
static float mavlink_msg_param_value_get_param_value (const mavlink_message_t *msg)
Get field param_value from param_value message.
static uint8_t mavlink_msg_param_value_get_param_type (const mavlink_message_t *msg)
Get field param_type from param_value message.
static uint16_t mavlink_msg_param_value_get_param_count (const mavlink_message_t *msg)
Get field param_count from param_value message.
static uint16_t mavlink_msg_param_value_get_param_index (const mavlink_message_t *msg)
Get field param_index from param_value message.
static void mavlink_msg_param_value_decode (const mavlink_message_t *msg, mavlink_param_value_t *param_value)
Decode a param_value message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_PARAM_VALUE
Value:
{ \
    "PARAM_VALUE", \
    5, \
    {  { "param_value", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_param_value_t, param_value) }, \
         { "param_count", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_param_value_t, param_count) }, \
         { "param_index", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_param_value_t, param_index) }, \
         { "param_id", NULL, MAVLINK_TYPE_CHAR, 16, 8, offsetof(mavlink_param_value_t, param_id) }, \
         { "param_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 24, offsetof(mavlink_param_value_t, param_type) }, \
         } \
}
Definition at line 22 of file mavlink_msg_param_value.h.
#define MAVLINK_MSG_ID_22_CRC 220
Definition at line 18 of file mavlink_msg_param_value.h.
#define MAVLINK_MSG_ID_22_LEN 25
Definition at line 15 of file mavlink_msg_param_value.h.
#define MAVLINK_MSG_ID_PARAM_VALUE 22
Definition at line 3 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_pack(), and mavlink_msg_param_value_pack_chan().
#define MAVLINK_MSG_ID_PARAM_VALUE_CRC 220
Definition at line 17 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_pack(), and mavlink_msg_param_value_pack_chan().
#define MAVLINK_MSG_ID_PARAM_VALUE_LEN 25
Definition at line 14 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode(), mavlink_msg_param_value_pack(), mavlink_msg_param_value_pack_chan(), GCS_MAVLINK::queued_param_send(), and GCS_MAVLINK::send_parameter_value_all().
#define MAVLINK_MSG_PARAM_VALUE_FIELD_PARAM_ID_LEN 16
Definition at line 20 of file mavlink_msg_param_value.h.
Typedef Documentation
typedef struct __mavlink_param_value_t mavlink_param_value_t
Function Documentation
static void mavlink_msg_param_value_decode (const mavlink_message_t * msg, mavlink_param_value_t * param_value) inline static
Decode a param_value message into a struct.
Parameters
msg The message to decode
param_value C-struct to decode the message contents into
Definition at line 286 of file mavlink_msg_param_value.h.
Referenced by mavlink_test_param_value().
static uint16_t mavlink_msg_param_value_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_param_value_t * param_value) inline static
Encode a param_value struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
param_value C-struct to read the message contents from
Definition at line 127 of file mavlink_msg_param_value.h.
Referenced by mavlink_test_param_value().
static uint16_t mavlink_msg_param_value_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_param_value_t * param_value) inline static
Encode a param_value struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
param_value C-struct to read the message contents from
Definition at line 141 of file mavlink_msg_param_value.h.
static uint16_t mavlink_msg_param_value_get_param_count (const mavlink_message_t * msg) inline static
Get field param_count from param_value message.
Returns
Total number of onboard parameters
Definition at line 265 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint16_t mavlink_msg_param_value_get_param_id (const mavlink_message_t * msg, char * param_id) inline static
Send a param_value message.
Parameters
chan MAVLink channel to send the message
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_value Onboard parameter value
param_type Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
param_count Total number of onboard parameters
param_index Index of this onboard parameter Get field param_id from param_value message
Returns
Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
Definition at line 235 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint16_t mavlink_msg_param_value_get_param_index (const mavlink_message_t * msg) inline static
Get field param_index from param_value message.
Returns
Index of this onboard parameter
Definition at line 275 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint8_t mavlink_msg_param_value_get_param_type (const mavlink_message_t * msg) inline static
Get field param_type from param_value message.
Returns
Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
Definition at line 255 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static float mavlink_msg_param_value_get_param_value (const mavlink_message_t * msg) inline static
Get field param_value from param_value message.
Returns
Onboard parameter value
Definition at line 245 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint16_t mavlink_msg_param_value_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const char * param_id, float param_value, uint8_t param_type, uint16_t param_count, uint16_t param_index) inline static
Pack a param_value message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_value Onboard parameter value
param_type Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
param_count Total number of onboard parameters
param_index Index of this onboard parameter
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_encode(), and mavlink_test_param_value().
static uint16_t mavlink_msg_param_value_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const char * param_id, float param_value, uint8_t param_type, uint16_t param_count, uint16_t param_index) inline static
Pack a param_value message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_value Onboard parameter value
param_type Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
param_count Total number of onboard parameters
param_index Index of this onboard parameter
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 89 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_encode_chan(), and mavlink_test_param_value().