APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_erase_firmware_and_config.h File Reference
mavlink_msg_gimbal_erase_firmware_and_config.h File Reference
Classes
struct __mavlink_gimbal_erase_firmware_and_config_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_ERASE_FIRMWARE_AND_CONFIG 208
#define MAVLINK_MSG_ID_GIMBAL_ERASE_FIRMWARE_AND_CONFIG_LEN 6
#define MAVLINK_MSG_ID_208_LEN 6
#define MAVLINK_MSG_ID_GIMBAL_ERASE_FIRMWARE_AND_CONFIG_CRC 221
#define MAVLINK_MSG_ID_208_CRC 221
#define MAVLINK_MESSAGE_INFO_GIMBAL_ERASE_FIRMWARE_AND_CONFIG
Typedefs
typedef struct __mavlink_gimbal_erase_firmware_and_config_t mavlink_gimbal_erase_firmware_and_config_t
Functions
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint32_t knock)
Pack a gimbal_erase_firmware_and_config message.
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint32_t knock)
Pack a gimbal_erase_firmware_and_config message on a channel.
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_erase_firmware_and_config_t *gimbal_erase_firmware_and_config)
Encode a gimbal_erase_firmware_and_config struct.
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_erase_firmware_and_config_t *gimbal_erase_firmware_and_config)
Encode a gimbal_erase_firmware_and_config struct on a channel.
static uint8_t mavlink_msg_gimbal_erase_firmware_and_config_get_target_system (const mavlink_message_t *msg)
Send a gimbal_erase_firmware_and_config message.
static uint8_t mavlink_msg_gimbal_erase_firmware_and_config_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_erase_firmware_and_config message.
static uint32_t mavlink_msg_gimbal_erase_firmware_and_config_get_knock (const mavlink_message_t *msg)
Get field knock from gimbal_erase_firmware_and_config message.
static void mavlink_msg_gimbal_erase_firmware_and_config_decode (const mavlink_message_t *msg, mavlink_gimbal_erase_firmware_and_config_t *gimbal_erase_firmware_and_config)
Decode a gimbal_erase_firmware_and_config message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_ERASE_FIRMWARE_AND_CONFIG
Value:
{ \
    "GIMBAL_ERASE_FIRMWARE_AND_CONFIG", \
    3, \
    {  { "knock", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_gimbal_erase_firmware_and_config_t, knock) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_gimbal_erase_firmware_and_config_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_gimbal_erase_firmware_and_config_t, target_component) }, \
         } \
}
Definition at line 20 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
#define MAVLINK_MSG_ID_208_CRC 221
Definition at line 16 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
#define MAVLINK_MSG_ID_208_LEN 6
Definition at line 13 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
#define MAVLINK_MSG_ID_GIMBAL_ERASE_FIRMWARE_AND_CONFIG 208
Definition at line 3 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_pack(), and mavlink_msg_gimbal_erase_firmware_and_config_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_ERASE_FIRMWARE_AND_CONFIG_CRC 221
Definition at line 15 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_pack(), and mavlink_msg_gimbal_erase_firmware_and_config_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_ERASE_FIRMWARE_AND_CONFIG_LEN 6
Definition at line 12 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_decode(), mavlink_msg_gimbal_erase_firmware_and_config_pack(), and mavlink_msg_gimbal_erase_firmware_and_config_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_erase_firmware_and_config_t mavlink_gimbal_erase_firmware_and_config_t
Function Documentation
static void mavlink_msg_gimbal_erase_firmware_and_config_decode (const mavlink_message_t * msg, mavlink_gimbal_erase_firmware_and_config_t * gimbal_erase_firmware_and_config) inline static
Decode a gimbal_erase_firmware_and_config message into a struct.
Parameters
msg The message to decode
gimbal_erase_firmware_and_config C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_test_gimbal_erase_firmware_and_config().
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_erase_firmware_and_config_t * gimbal_erase_firmware_and_config) inline static
Encode a gimbal_erase_firmware_and_config struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_erase_firmware_and_config C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_test_gimbal_erase_firmware_and_config().
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_erase_firmware_and_config_t * gimbal_erase_firmware_and_config) inline static
Encode a gimbal_erase_firmware_and_config struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_erase_firmware_and_config C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
static uint32_t mavlink_msg_gimbal_erase_firmware_and_config_get_knock (const mavlink_message_t * msg) inline static
Get field knock from gimbal_erase_firmware_and_config message.
Returns
Knock value to confirm this is a valid request
Definition at line 237 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_decode().
static uint8_t mavlink_msg_gimbal_erase_firmware_and_config_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_erase_firmware_and_config message.
Returns
Component ID
Definition at line 227 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_decode().
static uint8_t mavlink_msg_gimbal_erase_firmware_and_config_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_erase_firmware_and_config message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
knock Knock value to confirm this is a valid request Get field target_system from gimbal_erase_firmware_and_config message
Returns
System ID
Definition at line 217 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_decode().
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint32_t knock) inline static
Pack a gimbal_erase_firmware_and_config message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
knock Knock value to confirm this is a valid request
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_encode(), and mavlink_test_gimbal_erase_firmware_and_config().
static uint16_t mavlink_msg_gimbal_erase_firmware_and_config_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint32_t knock) inline static
Pack a gimbal_erase_firmware_and_config message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
knock Knock value to confirm this is a valid request
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_gimbal_erase_firmware_and_config.h.
Referenced by mavlink_msg_gimbal_erase_firmware_and_config_encode_chan(), and mavlink_test_gimbal_erase_firmware_and_config().