APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_attitude.h File Reference
mavlink_msg_attitude.h File Reference
Classes
struct __mavlink_attitude_t
Macros
#define MAVLINK_MSG_ID_ATTITUDE 30
#define MAVLINK_MSG_ID_ATTITUDE_LEN 28
#define MAVLINK_MSG_ID_30_LEN 28
#define MAVLINK_MSG_ID_ATTITUDE_CRC 39
#define MAVLINK_MSG_ID_30_CRC 39
#define MAVLINK_MESSAGE_INFO_ATTITUDE
Typedefs
typedef struct __mavlink_attitude_t mavlink_attitude_t
Functions
static uint16_t mavlink_msg_attitude_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed)
Pack a attitude message.
static uint16_t mavlink_msg_attitude_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed)
Pack a attitude message on a channel.
static uint16_t mavlink_msg_attitude_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_attitude_t *attitude)
Encode a attitude struct.
static uint16_t mavlink_msg_attitude_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_attitude_t *attitude)
Encode a attitude struct on a channel.
static uint32_t mavlink_msg_attitude_get_time_boot_ms (const mavlink_message_t *msg)
Send a attitude message.
static float mavlink_msg_attitude_get_roll (const mavlink_message_t *msg)
Get field roll from attitude message.
static float mavlink_msg_attitude_get_pitch (const mavlink_message_t *msg)
Get field pitch from attitude message.
static float mavlink_msg_attitude_get_yaw (const mavlink_message_t *msg)
Get field yaw from attitude message.
static float mavlink_msg_attitude_get_rollspeed (const mavlink_message_t *msg)
Get field rollspeed from attitude message.
static float mavlink_msg_attitude_get_pitchspeed (const mavlink_message_t *msg)
Get field pitchspeed from attitude message.
static float mavlink_msg_attitude_get_yawspeed (const mavlink_message_t *msg)
Get field yawspeed from attitude message.
static void mavlink_msg_attitude_decode (const mavlink_message_t *msg, mavlink_attitude_t *attitude)
Decode a attitude message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ATTITUDE
Value:
{ \
    "ATTITUDE", \
    7, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_attitude_t, time_boot_ms) }, \
         { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_attitude_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_attitude_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_attitude_t, yaw) }, \
         { "rollspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_attitude_t, rollspeed) }, \
         { "pitchspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_attitude_t, pitchspeed) }, \
         { "yawspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_attitude_t, yawspeed) }, \
         } \
}
Definition at line 24 of file mavlink_msg_attitude.h.
#define MAVLINK_MSG_ID_30_CRC 39
Definition at line 20 of file mavlink_msg_attitude.h.
#define MAVLINK_MSG_ID_30_LEN 28
Definition at line 17 of file mavlink_msg_attitude.h.
#define MAVLINK_MSG_ID_ATTITUDE 30
Definition at line 3 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_pack(), and mavlink_msg_attitude_pack_chan().
#define MAVLINK_MSG_ID_ATTITUDE_CRC 39
Definition at line 19 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_pack(), and mavlink_msg_attitude_pack_chan().
#define MAVLINK_MSG_ID_ATTITUDE_LEN 28
Definition at line 16 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode(), mavlink_msg_attitude_pack(), and mavlink_msg_attitude_pack_chan().
Typedef Documentation
typedef struct __mavlink_attitude_t mavlink_attitude_t
Function Documentation
static void mavlink_msg_attitude_decode (const mavlink_message_t * msg, mavlink_attitude_t * attitude) inline static
Decode a attitude message into a struct.
Parameters
msg The message to decode
attitude C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_attitude.h.
Referenced by mavlink_test_attitude().
static uint16_t mavlink_msg_attitude_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_attitude_t * attitude) inline static
Encode a attitude struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
attitude C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_attitude.h.
Referenced by loop(), and mavlink_test_attitude().
static uint16_t mavlink_msg_attitude_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_attitude_t * attitude) inline static
Encode a attitude struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
attitude C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_attitude.h.
static float mavlink_msg_attitude_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from attitude message.
Returns
Pitch angle (rad, -pi..+pi)
Definition at line 289 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_pitchspeed (const mavlink_message_t * msg) inline static
Get field pitchspeed from attitude message.
Returns
Pitch angular speed (rad/s)
Definition at line 319 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_roll (const mavlink_message_t * msg) inline static
Get field roll from attitude message.
Returns
Roll angle (rad, -pi..+pi)
Definition at line 279 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_rollspeed (const mavlink_message_t * msg) inline static
Get field rollspeed from attitude message.
Returns
Roll angular speed (rad/s)
Definition at line 309 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static uint32_t mavlink_msg_attitude_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a attitude message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
roll Roll angle (rad, -pi..+pi)
pitch Pitch angle (rad, -pi..+pi)
yaw Yaw angle (rad, -pi..+pi)
rollspeed Roll angular speed (rad/s)
pitchspeed Pitch angular speed (rad/s)
yawspeed Yaw angular speed (rad/s) Get field time_boot_ms from attitude message
Returns
Timestamp (milliseconds since system boot)
Definition at line 269 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from attitude message.
Returns
Yaw angle (rad, -pi..+pi)
Definition at line 299 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_yawspeed (const mavlink_message_t * msg) inline static
Get field yawspeed from attitude message.
Returns
Yaw angular speed (rad/s)
Definition at line 329 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static uint16_t mavlink_msg_attitude_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed) inline static
Pack a attitude message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
roll Roll angle (rad, -pi..+pi)
pitch Pitch angle (rad, -pi..+pi)
yaw Yaw angle (rad, -pi..+pi)
rollspeed Roll angular speed (rad/s)
pitchspeed Pitch angular speed (rad/s)
yawspeed Yaw angular speed (rad/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_encode(), and mavlink_test_attitude().
static uint16_t mavlink_msg_attitude_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed) inline static
Pack a attitude message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
roll Roll angle (rad, -pi..+pi)
pitch Pitch angle (rad, -pi..+pi)
yaw Yaw angle (rad, -pi..+pi)
rollspeed Roll angular speed (rad/s)
pitchspeed Pitch angular speed (rad/s)
yawspeed Yaw angular speed (rad/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_encode_chan(), and mavlink_test_attitude().