APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_rpm.h File Reference
mavlink_msg_rpm.h File Reference
Classes
struct __mavlink_rpm_t
Macros
#define MAVLINK_MSG_ID_RPM 226
#define MAVLINK_MSG_ID_RPM_LEN 8
#define MAVLINK_MSG_ID_226_LEN 8
#define MAVLINK_MSG_ID_RPM_CRC 207
#define MAVLINK_MSG_ID_226_CRC 207
#define MAVLINK_MESSAGE_INFO_RPM
Typedefs
typedef struct __mavlink_rpm_t mavlink_rpm_t
Functions
static uint16_t mavlink_msg_rpm_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float rpm1, float rpm2)
Pack a rpm message.
static uint16_t mavlink_msg_rpm_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float rpm1, float rpm2)
Pack a rpm message on a channel.
static uint16_t mavlink_msg_rpm_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rpm_t *rpm)
Encode a rpm struct.
static uint16_t mavlink_msg_rpm_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_rpm_t *rpm)
Encode a rpm struct on a channel.
static float mavlink_msg_rpm_get_rpm1 (const mavlink_message_t *msg)
Send a rpm message.
static float mavlink_msg_rpm_get_rpm2 (const mavlink_message_t *msg)
Get field rpm2 from rpm message.
static void mavlink_msg_rpm_decode (const mavlink_message_t *msg, mavlink_rpm_t *rpm)
Decode a rpm message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RPM
Value:
{ \
    "RPM", \
    2, \
    {  { "rpm1", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_rpm_t, rpm1) }, \
         { "rpm2", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_rpm_t, rpm2) }, \
         } \
}
Definition at line 19 of file mavlink_msg_rpm.h.
#define MAVLINK_MSG_ID_226_CRC 207
Definition at line 15 of file mavlink_msg_rpm.h.
#define MAVLINK_MSG_ID_226_LEN 8
Definition at line 12 of file mavlink_msg_rpm.h.
#define MAVLINK_MSG_ID_RPM 226
Definition at line 3 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_pack(), and mavlink_msg_rpm_pack_chan().
#define MAVLINK_MSG_ID_RPM_CRC 207
Definition at line 14 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_pack(), and mavlink_msg_rpm_pack_chan().
#define MAVLINK_MSG_ID_RPM_LEN 8
Definition at line 11 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_decode(), mavlink_msg_rpm_pack(), and mavlink_msg_rpm_pack_chan().
Typedef Documentation
typedef struct __mavlink_rpm_t mavlink_rpm_t
Function Documentation
static void mavlink_msg_rpm_decode (const mavlink_message_t * msg, mavlink_rpm_t * rpm) inline static
Decode a rpm message into a struct.
Parameters
msg The message to decode
rpm C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_rpm.h.
Referenced by mavlink_test_rpm().
static uint16_t mavlink_msg_rpm_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rpm_t * rpm) inline static
Encode a rpm struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rpm C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_rpm.h.
Referenced by mavlink_test_rpm().
static uint16_t mavlink_msg_rpm_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_rpm_t * rpm) inline static
Encode a rpm struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rpm C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_rpm.h.
static float mavlink_msg_rpm_get_rpm1 (const mavlink_message_t * msg) inline static
Send a rpm message.
Parameters
chan MAVLink channel to send the message
rpm1 RPM Sensor1
rpm2 RPM Sensor2 Get field rpm1 from rpm message
Returns
RPM Sensor1
Definition at line 204 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_decode().
static float mavlink_msg_rpm_get_rpm2 (const mavlink_message_t * msg) inline static
Get field rpm2 from rpm message.
Returns
RPM Sensor2
Definition at line 214 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_decode().
static uint16_t mavlink_msg_rpm_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float rpm1, float rpm2) inline static
Pack a rpm message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rpm1 RPM Sensor1
rpm2 RPM Sensor2
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_encode(), and mavlink_test_rpm().
static uint16_t mavlink_msg_rpm_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float rpm1, float rpm2) inline static
Pack a rpm message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rpm1 RPM Sensor1
rpm2 RPM Sensor2
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_rpm.h.
Referenced by mavlink_msg_rpm_encode_chan(), and mavlink_test_rpm().