APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_data16.h File Reference
mavlink_msg_data16.h File Reference
Classes
struct __mavlink_data16_t
Macros
#define MAVLINK_MSG_ID_DATA16 169
#define MAVLINK_MSG_ID_DATA16_LEN 18
#define MAVLINK_MSG_ID_169_LEN 18
#define MAVLINK_MSG_ID_DATA16_CRC 234
#define MAVLINK_MSG_ID_169_CRC 234
#define MAVLINK_MSG_DATA16_FIELD_DATA_LEN 16
#define MAVLINK_MESSAGE_INFO_DATA16
Typedefs
typedef struct __mavlink_data16_t mavlink_data16_t
Functions
static uint16_t mavlink_msg_data16_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t type, uint8_t len, const uint8_t *data)
Pack a data16 message.
static uint16_t mavlink_msg_data16_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t type, uint8_t len, const uint8_t *data)
Pack a data16 message on a channel.
static uint16_t mavlink_msg_data16_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_data16_t *data16)
Encode a data16 struct.
static uint16_t mavlink_msg_data16_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_data16_t *data16)
Encode a data16 struct on a channel.
static uint8_t mavlink_msg_data16_get_type (const mavlink_message_t *msg)
Send a data16 message.
static uint8_t mavlink_msg_data16_get_len (const mavlink_message_t *msg)
Get field len from data16 message.
static uint16_t mavlink_msg_data16_get_data (const mavlink_message_t *msg, uint8_t *data)
Get field data from data16 message.
static void mavlink_msg_data16_decode (const mavlink_message_t *msg, mavlink_data16_t *data16)
Decode a data16 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DATA16
Value:
{ \
    "DATA16", \
    3, \
    {  { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_data16_t, type) }, \
         { "len", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_data16_t, len) }, \
         { "data", NULL, MAVLINK_TYPE_UINT8_T, 16, 2, offsetof(mavlink_data16_t, data) }, \
         } \
}
Definition at line 20 of file mavlink_msg_data16.h.
#define MAVLINK_MSG_DATA16_FIELD_DATA_LEN 16
Definition at line 18 of file mavlink_msg_data16.h.
#define MAVLINK_MSG_ID_169_CRC 234
Definition at line 16 of file mavlink_msg_data16.h.
#define MAVLINK_MSG_ID_169_LEN 18
Definition at line 13 of file mavlink_msg_data16.h.
#define MAVLINK_MSG_ID_DATA16 169
Definition at line 3 of file mavlink_msg_data16.h.
Referenced by handle_message(), mavlink_msg_data16_pack(), and mavlink_msg_data16_pack_chan().
#define MAVLINK_MSG_ID_DATA16_CRC 234
Definition at line 15 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_pack(), and mavlink_msg_data16_pack_chan().
#define MAVLINK_MSG_ID_DATA16_LEN 18
Definition at line 12 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_decode(), mavlink_msg_data16_pack(), and mavlink_msg_data16_pack_chan().
Typedef Documentation
typedef struct __mavlink_data16_t mavlink_data16_t
Function Documentation
static void mavlink_msg_data16_decode (const mavlink_message_t * msg, mavlink_data16_t * data16) inline static
Decode a data16 message into a struct.
Parameters
msg The message to decode
data16 C-struct to decode the message contents into
Definition at line 240 of file mavlink_msg_data16.h.
Referenced by gcs_console_handle_data16(), and mavlink_test_data16().
static uint16_t mavlink_msg_data16_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_data16_t * data16) inline static
Encode a data16 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
data16 C-struct to read the message contents from
Definition at line 111 of file mavlink_msg_data16.h.
Referenced by mavlink_test_data16().
static uint16_t mavlink_msg_data16_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_data16_t * data16) inline static
Encode a data16 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
data16 C-struct to read the message contents from
Definition at line 125 of file mavlink_msg_data16.h.
static uint16_t mavlink_msg_data16_get_data (const mavlink_message_t * msg, uint8_t * data) inline static
Get field data from data16 message.
Returns
raw data
Definition at line 229 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_decode().
static uint8_t mavlink_msg_data16_get_len (const mavlink_message_t * msg) inline static
Get field len from data16 message.
Returns
data length
Definition at line 219 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_decode().
static uint8_t mavlink_msg_data16_get_type (const mavlink_message_t * msg) inline static
Send a data16 message.
Parameters
chan MAVLink channel to send the message
type data type
len data length
data raw data Get field type from data16 message
Returns
data type
Definition at line 209 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_decode().
static uint16_t mavlink_msg_data16_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t type, uint8_t len, const uint8_t * data) inline static
Pack a data16 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
type data type
len data length
data raw data
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_encode(), and mavlink_test_data16().
static uint16_t mavlink_msg_data16_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t type, uint8_t len, const uint8_t * data) inline static
Pack a data16 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
type data type
len data length
data raw data
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 77 of file mavlink_msg_data16.h.
Referenced by mavlink_msg_data16_encode_chan(), and mavlink_test_data16().