APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_set_factory_parameters.h File Reference
mavlink_msg_gimbal_set_factory_parameters.h File Reference
Classes
struct __mavlink_gimbal_set_factory_parameters_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_SET_FACTORY_PARAMETERS 206
#define MAVLINK_MSG_ID_GIMBAL_SET_FACTORY_PARAMETERS_LEN 33
#define MAVLINK_MSG_ID_206_LEN 33
#define MAVLINK_MSG_ID_GIMBAL_SET_FACTORY_PARAMETERS_CRC 112
#define MAVLINK_MSG_ID_206_CRC 112
#define MAVLINK_MESSAGE_INFO_GIMBAL_SET_FACTORY_PARAMETERS
Typedefs
typedef struct __mavlink_gimbal_set_factory_parameters_t mavlink_gimbal_set_factory_parameters_t
Functions
static uint16_t mavlink_msg_gimbal_set_factory_parameters_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint32_t magic_1, uint32_t magic_2, uint32_t magic_3, uint16_t assembly_year, uint8_t assembly_month, uint8_t assembly_day, uint8_t assembly_hour, uint8_t assembly_minute, uint8_t assembly_second, uint32_t serial_number_pt_1, uint32_t serial_number_pt_2, uint32_t serial_number_pt_3)
Pack a gimbal_set_factory_parameters message.
static uint16_t mavlink_msg_gimbal_set_factory_parameters_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint32_t magic_1, uint32_t magic_2, uint32_t magic_3, uint16_t assembly_year, uint8_t assembly_month, uint8_t assembly_day, uint8_t assembly_hour, uint8_t assembly_minute, uint8_t assembly_second, uint32_t serial_number_pt_1, uint32_t serial_number_pt_2, uint32_t serial_number_pt_3)
Pack a gimbal_set_factory_parameters message on a channel.
static uint16_t mavlink_msg_gimbal_set_factory_parameters_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_set_factory_parameters_t *gimbal_set_factory_parameters)
Encode a gimbal_set_factory_parameters struct.
static uint16_t mavlink_msg_gimbal_set_factory_parameters_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_set_factory_parameters_t *gimbal_set_factory_parameters)
Encode a gimbal_set_factory_parameters struct on a channel.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_target_system (const mavlink_message_t *msg)
Send a gimbal_set_factory_parameters message.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_set_factory_parameters message.
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_magic_1 (const mavlink_message_t *msg)
Get field magic_1 from gimbal_set_factory_parameters message.
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_magic_2 (const mavlink_message_t *msg)
Get field magic_2 from gimbal_set_factory_parameters message.
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_magic_3 (const mavlink_message_t *msg)
Get field magic_3 from gimbal_set_factory_parameters message.
static uint16_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_year (const mavlink_message_t *msg)
Get field assembly_year from gimbal_set_factory_parameters message.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_month (const mavlink_message_t *msg)
Get field assembly_month from gimbal_set_factory_parameters message.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_day (const mavlink_message_t *msg)
Get field assembly_day from gimbal_set_factory_parameters message.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_hour (const mavlink_message_t *msg)
Get field assembly_hour from gimbal_set_factory_parameters message.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_minute (const mavlink_message_t *msg)
Get field assembly_minute from gimbal_set_factory_parameters message.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_second (const mavlink_message_t *msg)
Get field assembly_second from gimbal_set_factory_parameters message.
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_serial_number_pt_1 (const mavlink_message_t *msg)
Get field serial_number_pt_1 from gimbal_set_factory_parameters message.
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_serial_number_pt_2 (const mavlink_message_t *msg)
Get field serial_number_pt_2 from gimbal_set_factory_parameters message.
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_serial_number_pt_3 (const mavlink_message_t *msg)
Get field serial_number_pt_3 from gimbal_set_factory_parameters message.
static void mavlink_msg_gimbal_set_factory_parameters_decode (const mavlink_message_t *msg, mavlink_gimbal_set_factory_parameters_t *gimbal_set_factory_parameters)
Decode a gimbal_set_factory_parameters message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_SET_FACTORY_PARAMETERS
Value:
{ \
    "GIMBAL_SET_FACTORY_PARAMETERS", \
    14, \
    {  { "magic_1", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_gimbal_set_factory_parameters_t, magic_1) }, \
         { "magic_2", NULL, MAVLINK_TYPE_UINT32_T, 0, 4, offsetof(mavlink_gimbal_set_factory_parameters_t, magic_2) }, \
         { "magic_3", NULL, MAVLINK_TYPE_UINT32_T, 0, 8, offsetof(mavlink_gimbal_set_factory_parameters_t, magic_3) }, \
         { "serial_number_pt_1", NULL, MAVLINK_TYPE_UINT32_T, 0, 12, offsetof(mavlink_gimbal_set_factory_parameters_t, serial_number_pt_1) }, \
         { "serial_number_pt_2", NULL, MAVLINK_TYPE_UINT32_T, 0, 16, offsetof(mavlink_gimbal_set_factory_parameters_t, serial_number_pt_2) }, \
         { "serial_number_pt_3", NULL, MAVLINK_TYPE_UINT32_T, 0, 20, offsetof(mavlink_gimbal_set_factory_parameters_t, serial_number_pt_3) }, \
         { "assembly_year", NULL, MAVLINK_TYPE_UINT16_T, 0, 24, offsetof(mavlink_gimbal_set_factory_parameters_t, assembly_year) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 26, offsetof(mavlink_gimbal_set_factory_parameters_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 27, offsetof(mavlink_gimbal_set_factory_parameters_t, target_component) }, \
         { "assembly_month", NULL, MAVLINK_TYPE_UINT8_T, 0, 28, offsetof(mavlink_gimbal_set_factory_parameters_t, assembly_month) }, \
         { "assembly_day", NULL, MAVLINK_TYPE_UINT8_T, 0, 29, offsetof(mavlink_gimbal_set_factory_parameters_t, assembly_day) }, \
         { "assembly_hour", NULL, MAVLINK_TYPE_UINT8_T, 0, 30, offsetof(mavlink_gimbal_set_factory_parameters_t, assembly_hour) }, \
         { "assembly_minute", NULL, MAVLINK_TYPE_UINT8_T, 0, 31, offsetof(mavlink_gimbal_set_factory_parameters_t, assembly_minute) }, \
         { "assembly_second", NULL, MAVLINK_TYPE_UINT8_T, 0, 32, offsetof(mavlink_gimbal_set_factory_parameters_t, assembly_second) }, \
         } \
}
Definition at line 31 of file mavlink_msg_gimbal_set_factory_parameters.h.
#define MAVLINK_MSG_ID_206_CRC 112
Definition at line 27 of file mavlink_msg_gimbal_set_factory_parameters.h.
#define MAVLINK_MSG_ID_206_LEN 33
Definition at line 24 of file mavlink_msg_gimbal_set_factory_parameters.h.
#define MAVLINK_MSG_ID_GIMBAL_SET_FACTORY_PARAMETERS 206
Definition at line 3 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_pack(), and mavlink_msg_gimbal_set_factory_parameters_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_SET_FACTORY_PARAMETERS_CRC 112
Definition at line 26 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_pack(), and mavlink_msg_gimbal_set_factory_parameters_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_SET_FACTORY_PARAMETERS_LEN 33
Definition at line 23 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode(), mavlink_msg_gimbal_set_factory_parameters_pack(), and mavlink_msg_gimbal_set_factory_parameters_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_set_factory_parameters_t mavlink_gimbal_set_factory_parameters_t
Function Documentation
static void mavlink_msg_gimbal_set_factory_parameters_decode (const mavlink_message_t * msg, mavlink_gimbal_set_factory_parameters_t * gimbal_set_factory_parameters) inline static
Decode a gimbal_set_factory_parameters message into a struct.
Parameters
msg The message to decode
gimbal_set_factory_parameters C-struct to decode the message contents into
Definition at line 501 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_test_gimbal_set_factory_parameters().
static uint16_t mavlink_msg_gimbal_set_factory_parameters_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_set_factory_parameters_t * gimbal_set_factory_parameters) inline static
Encode a gimbal_set_factory_parameters struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_set_factory_parameters C-struct to read the message contents from
Definition at line 203 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_test_gimbal_set_factory_parameters().
static uint16_t mavlink_msg_gimbal_set_factory_parameters_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_set_factory_parameters_t * gimbal_set_factory_parameters) inline static
Encode a gimbal_set_factory_parameters struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_set_factory_parameters C-struct to read the message contents from
Definition at line 217 of file mavlink_msg_gimbal_set_factory_parameters.h.
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_day (const mavlink_message_t * msg) inline static
Get field assembly_day from gimbal_set_factory_parameters message.
Returns
Assembly Date Day
Definition at line 430 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_hour (const mavlink_message_t * msg) inline static
Get field assembly_hour from gimbal_set_factory_parameters message.
Returns
Assembly Time Hour
Definition at line 440 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_minute (const mavlink_message_t * msg) inline static
Get field assembly_minute from gimbal_set_factory_parameters message.
Returns
Assembly Time Minute
Definition at line 450 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_month (const mavlink_message_t * msg) inline static
Get field assembly_month from gimbal_set_factory_parameters message.
Returns
Assembly Date Month
Definition at line 420 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_second (const mavlink_message_t * msg) inline static
Get field assembly_second from gimbal_set_factory_parameters message.
Returns
Assembly Time Second
Definition at line 460 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint16_t mavlink_msg_gimbal_set_factory_parameters_get_assembly_year (const mavlink_message_t * msg) inline static
Get field assembly_year from gimbal_set_factory_parameters message.
Returns
Assembly Date Year
Definition at line 410 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_magic_1 (const mavlink_message_t * msg) inline static
Get field magic_1 from gimbal_set_factory_parameters message.
Returns
Magic number 1 for validation
Definition at line 380 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_magic_2 (const mavlink_message_t * msg) inline static
Get field magic_2 from gimbal_set_factory_parameters message.
Returns
Magic number 2 for validation
Definition at line 390 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_magic_3 (const mavlink_message_t * msg) inline static
Get field magic_3 from gimbal_set_factory_parameters message.
Returns
Magic number 3 for validation
Definition at line 400 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_serial_number_pt_1 (const mavlink_message_t * msg) inline static
Get field serial_number_pt_1 from gimbal_set_factory_parameters message.
Returns
Unit Serial Number Part 1 (part code, design, language/country)
Definition at line 470 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_serial_number_pt_2 (const mavlink_message_t * msg) inline static
Get field serial_number_pt_2 from gimbal_set_factory_parameters message.
Returns
Unit Serial Number Part 2 (option, year, month)
Definition at line 480 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint32_t mavlink_msg_gimbal_set_factory_parameters_get_serial_number_pt_3 (const mavlink_message_t * msg) inline static
Get field serial_number_pt_3 from gimbal_set_factory_parameters message.
Returns
Unit Serial Number Part 3 (incrementing serial number per month)
Definition at line 490 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_set_factory_parameters message.
Returns
Component ID
Definition at line 370 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint8_t mavlink_msg_gimbal_set_factory_parameters_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_set_factory_parameters message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
magic_1 Magic number 1 for validation
magic_2 Magic number 2 for validation
magic_3 Magic number 3 for validation
assembly_year Assembly Date Year
assembly_month Assembly Date Month
assembly_day Assembly Date Day
assembly_hour Assembly Time Hour
assembly_minute Assembly Time Minute
assembly_second Assembly Time Second
serial_number_pt_1 Unit Serial Number Part 1 (part code, design, language/country)
serial_number_pt_2 Unit Serial Number Part 2 (option, year, month)
serial_number_pt_3 Unit Serial Number Part 3 (incrementing serial number per month) Get field target_system from gimbal_set_factory_parameters message
Returns
System ID
Definition at line 360 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_decode().
static uint16_t mavlink_msg_gimbal_set_factory_parameters_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint32_t magic_1, uint32_t magic_2, uint32_t magic_3, uint16_t assembly_year, uint8_t assembly_month, uint8_t assembly_day, uint8_t assembly_hour, uint8_t assembly_minute, uint8_t assembly_second, uint32_t serial_number_pt_1, uint32_t serial_number_pt_2, uint32_t serial_number_pt_3) inline static
Pack a gimbal_set_factory_parameters message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
magic_1 Magic number 1 for validation
magic_2 Magic number 2 for validation
magic_3 Magic number 3 for validation
assembly_year Assembly Date Year
assembly_month Assembly Date Month
assembly_day Assembly Date Day
assembly_hour Assembly Time Hour
assembly_minute Assembly Time Minute
assembly_second Assembly Time Second
serial_number_pt_1 Unit Serial Number Part 1 (part code, design, language/country)
serial_number_pt_2 Unit Serial Number Part 2 (option, year, month)
serial_number_pt_3 Unit Serial Number Part 3 (incrementing serial number per month)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 74 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_encode(), and mavlink_test_gimbal_set_factory_parameters().
static uint16_t mavlink_msg_gimbal_set_factory_parameters_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint32_t magic_1, uint32_t magic_2, uint32_t magic_3, uint16_t assembly_year, uint8_t assembly_month, uint8_t assembly_day, uint8_t assembly_hour, uint8_t assembly_minute, uint8_t assembly_second, uint32_t serial_number_pt_1, uint32_t serial_number_pt_2, uint32_t serial_number_pt_3) inline static
Pack a gimbal_set_factory_parameters message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
magic_1 Magic number 1 for validation
magic_2 Magic number 2 for validation
magic_3 Magic number 3 for validation
assembly_year Assembly Date Year
assembly_month Assembly Date Month
assembly_day Assembly Date Day
assembly_hour Assembly Time Hour
assembly_minute Assembly Time Minute
assembly_second Assembly Time Second
serial_number_pt_1 Unit Serial Number Part 1 (part code, design, language/country)
serial_number_pt_2 Unit Serial Number Part 2 (option, year, month)
serial_number_pt_3 Unit Serial Number Part 3 (incrementing serial number per month)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 145 of file mavlink_msg_gimbal_set_factory_parameters.h.
Referenced by mavlink_msg_gimbal_set_factory_parameters_encode_chan(), and mavlink_test_gimbal_set_factory_parameters().