APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_hil_rc_inputs_raw.h File Reference
mavlink_msg_hil_rc_inputs_raw.h File Reference
Classes
struct __mavlink_hil_rc_inputs_raw_t
Macros
#define MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW 92
#define MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW_LEN 33
#define MAVLINK_MSG_ID_92_LEN 33
#define MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW_CRC 54
#define MAVLINK_MSG_ID_92_CRC 54
#define MAVLINK_MESSAGE_INFO_HIL_RC_INPUTS_RAW
Typedefs
typedef struct __mavlink_hil_rc_inputs_raw_t mavlink_hil_rc_inputs_raw_t
Functions
static uint16_t mavlink_msg_hil_rc_inputs_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint8_t rssi)
Pack a hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint8_t rssi)
Pack a hil_rc_inputs_raw message on a channel.
static uint16_t mavlink_msg_hil_rc_inputs_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_hil_rc_inputs_raw_t *hil_rc_inputs_raw)
Encode a hil_rc_inputs_raw struct.
static uint16_t mavlink_msg_hil_rc_inputs_raw_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_hil_rc_inputs_raw_t *hil_rc_inputs_raw)
Encode a hil_rc_inputs_raw struct on a channel.
static uint64_t mavlink_msg_hil_rc_inputs_raw_get_time_usec (const mavlink_message_t *msg)
Send a hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan1_raw (const mavlink_message_t *msg)
Get field chan1_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan2_raw (const mavlink_message_t *msg)
Get field chan2_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan3_raw (const mavlink_message_t *msg)
Get field chan3_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan4_raw (const mavlink_message_t *msg)
Get field chan4_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan5_raw (const mavlink_message_t *msg)
Get field chan5_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan6_raw (const mavlink_message_t *msg)
Get field chan6_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan7_raw (const mavlink_message_t *msg)
Get field chan7_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan8_raw (const mavlink_message_t *msg)
Get field chan8_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan9_raw (const mavlink_message_t *msg)
Get field chan9_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan10_raw (const mavlink_message_t *msg)
Get field chan10_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan11_raw (const mavlink_message_t *msg)
Get field chan11_raw from hil_rc_inputs_raw message.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan12_raw (const mavlink_message_t *msg)
Get field chan12_raw from hil_rc_inputs_raw message.
static uint8_t mavlink_msg_hil_rc_inputs_raw_get_rssi (const mavlink_message_t *msg)
Get field rssi from hil_rc_inputs_raw message.
static void mavlink_msg_hil_rc_inputs_raw_decode (const mavlink_message_t *msg, mavlink_hil_rc_inputs_raw_t *hil_rc_inputs_raw)
Decode a hil_rc_inputs_raw message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_HIL_RC_INPUTS_RAW
Value:
{ \
    "HIL_RC_INPUTS_RAW", \
    14, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_hil_rc_inputs_raw_t, time_usec) }, \
         { "chan1_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_hil_rc_inputs_raw_t, chan1_raw) }, \
         { "chan2_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_hil_rc_inputs_raw_t, chan2_raw) }, \
         { "chan3_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_hil_rc_inputs_raw_t, chan3_raw) }, \
         { "chan4_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 14, offsetof(mavlink_hil_rc_inputs_raw_t, chan4_raw) }, \
         { "chan5_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_hil_rc_inputs_raw_t, chan5_raw) }, \
         { "chan6_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_hil_rc_inputs_raw_t, chan6_raw) }, \
         { "chan7_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 20, offsetof(mavlink_hil_rc_inputs_raw_t, chan7_raw) }, \
         { "chan8_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 22, offsetof(mavlink_hil_rc_inputs_raw_t, chan8_raw) }, \
         { "chan9_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 24, offsetof(mavlink_hil_rc_inputs_raw_t, chan9_raw) }, \
         { "chan10_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 26, offsetof(mavlink_hil_rc_inputs_raw_t, chan10_raw) }, \
         { "chan11_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 28, offsetof(mavlink_hil_rc_inputs_raw_t, chan11_raw) }, \
         { "chan12_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 30, offsetof(mavlink_hil_rc_inputs_raw_t, chan12_raw) }, \
         { "rssi", NULL, MAVLINK_TYPE_UINT8_T, 0, 32, offsetof(mavlink_hil_rc_inputs_raw_t, rssi) }, \
         } \
}
Definition at line 31 of file mavlink_msg_hil_rc_inputs_raw.h.
#define MAVLINK_MSG_ID_92_CRC 54
Definition at line 27 of file mavlink_msg_hil_rc_inputs_raw.h.
#define MAVLINK_MSG_ID_92_LEN 33
Definition at line 24 of file mavlink_msg_hil_rc_inputs_raw.h.
#define MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW 92
Definition at line 3 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_pack(), and mavlink_msg_hil_rc_inputs_raw_pack_chan().
#define MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW_CRC 54
Definition at line 26 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_pack(), and mavlink_msg_hil_rc_inputs_raw_pack_chan().
#define MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW_LEN 33
Definition at line 23 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode(), mavlink_msg_hil_rc_inputs_raw_pack(), and mavlink_msg_hil_rc_inputs_raw_pack_chan().
Typedef Documentation
typedef struct __mavlink_hil_rc_inputs_raw_t mavlink_hil_rc_inputs_raw_t
Function Documentation
static void mavlink_msg_hil_rc_inputs_raw_decode (const mavlink_message_t * msg, mavlink_hil_rc_inputs_raw_t * hil_rc_inputs_raw) inline static
Decode a hil_rc_inputs_raw message into a struct.
Parameters
msg The message to decode
hil_rc_inputs_raw C-struct to decode the message contents into
Definition at line 501 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_test_hil_rc_inputs_raw().
static uint16_t mavlink_msg_hil_rc_inputs_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_hil_rc_inputs_raw_t * hil_rc_inputs_raw) inline static
Encode a hil_rc_inputs_raw struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
hil_rc_inputs_raw C-struct to read the message contents from
Definition at line 203 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_test_hil_rc_inputs_raw().
static uint16_t mavlink_msg_hil_rc_inputs_raw_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_hil_rc_inputs_raw_t * hil_rc_inputs_raw) inline static
Encode a hil_rc_inputs_raw struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
hil_rc_inputs_raw C-struct to read the message contents from
Definition at line 217 of file mavlink_msg_hil_rc_inputs_raw.h.
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan10_raw (const mavlink_message_t * msg) inline static
Get field chan10_raw from hil_rc_inputs_raw message.
Returns
RC channel 10 value, in microseconds
Definition at line 460 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan11_raw (const mavlink_message_t * msg) inline static
Get field chan11_raw from hil_rc_inputs_raw message.
Returns
RC channel 11 value, in microseconds
Definition at line 470 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan12_raw (const mavlink_message_t * msg) inline static
Get field chan12_raw from hil_rc_inputs_raw message.
Returns
RC channel 12 value, in microseconds
Definition at line 480 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan1_raw (const mavlink_message_t * msg) inline static
Get field chan1_raw from hil_rc_inputs_raw message.
Returns
RC channel 1 value, in microseconds
Definition at line 370 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan2_raw (const mavlink_message_t * msg) inline static
Get field chan2_raw from hil_rc_inputs_raw message.
Returns
RC channel 2 value, in microseconds
Definition at line 380 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan3_raw (const mavlink_message_t * msg) inline static
Get field chan3_raw from hil_rc_inputs_raw message.
Returns
RC channel 3 value, in microseconds
Definition at line 390 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan4_raw (const mavlink_message_t * msg) inline static
Get field chan4_raw from hil_rc_inputs_raw message.
Returns
RC channel 4 value, in microseconds
Definition at line 400 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan5_raw (const mavlink_message_t * msg) inline static
Get field chan5_raw from hil_rc_inputs_raw message.
Returns
RC channel 5 value, in microseconds
Definition at line 410 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan6_raw (const mavlink_message_t * msg) inline static
Get field chan6_raw from hil_rc_inputs_raw message.
Returns
RC channel 6 value, in microseconds
Definition at line 420 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan7_raw (const mavlink_message_t * msg) inline static
Get field chan7_raw from hil_rc_inputs_raw message.
Returns
RC channel 7 value, in microseconds
Definition at line 430 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan8_raw (const mavlink_message_t * msg) inline static
Get field chan8_raw from hil_rc_inputs_raw message.
Returns
RC channel 8 value, in microseconds
Definition at line 440 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_get_chan9_raw (const mavlink_message_t * msg) inline static
Get field chan9_raw from hil_rc_inputs_raw message.
Returns
RC channel 9 value, in microseconds
Definition at line 450 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint8_t mavlink_msg_hil_rc_inputs_raw_get_rssi (const mavlink_message_t * msg) inline static
Get field rssi from hil_rc_inputs_raw message.
Returns
Receive signal strength indicator, 0: 0%, 255: 100%
Definition at line 490 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint64_t mavlink_msg_hil_rc_inputs_raw_get_time_usec (const mavlink_message_t * msg) inline static
Send a hil_rc_inputs_raw message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
chan1_raw RC channel 1 value, in microseconds
chan2_raw RC channel 2 value, in microseconds
chan3_raw RC channel 3 value, in microseconds
chan4_raw RC channel 4 value, in microseconds
chan5_raw RC channel 5 value, in microseconds
chan6_raw RC channel 6 value, in microseconds
chan7_raw RC channel 7 value, in microseconds
chan8_raw RC channel 8 value, in microseconds
chan9_raw RC channel 9 value, in microseconds
chan10_raw RC channel 10 value, in microseconds
chan11_raw RC channel 11 value, in microseconds
chan12_raw RC channel 12 value, in microseconds
rssi Receive signal strength indicator, 0: 0%, 255: 100% Get field time_usec from hil_rc_inputs_raw message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 360 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_decode().
static uint16_t mavlink_msg_hil_rc_inputs_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint8_t rssi) inline static
Pack a hil_rc_inputs_raw message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
chan1_raw RC channel 1 value, in microseconds
chan2_raw RC channel 2 value, in microseconds
chan3_raw RC channel 3 value, in microseconds
chan4_raw RC channel 4 value, in microseconds
chan5_raw RC channel 5 value, in microseconds
chan6_raw RC channel 6 value, in microseconds
chan7_raw RC channel 7 value, in microseconds
chan8_raw RC channel 8 value, in microseconds
chan9_raw RC channel 9 value, in microseconds
chan10_raw RC channel 10 value, in microseconds
chan11_raw RC channel 11 value, in microseconds
chan12_raw RC channel 12 value, in microseconds
rssi Receive signal strength indicator, 0: 0%, 255: 100%
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 74 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_encode(), and mavlink_test_hil_rc_inputs_raw().
static uint16_t mavlink_msg_hil_rc_inputs_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint8_t rssi) inline static
Pack a hil_rc_inputs_raw message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
chan1_raw RC channel 1 value, in microseconds
chan2_raw RC channel 2 value, in microseconds
chan3_raw RC channel 3 value, in microseconds
chan4_raw RC channel 4 value, in microseconds
chan5_raw RC channel 5 value, in microseconds
chan6_raw RC channel 6 value, in microseconds
chan7_raw RC channel 7 value, in microseconds
chan8_raw RC channel 8 value, in microseconds
chan9_raw RC channel 9 value, in microseconds
chan10_raw RC channel 10 value, in microseconds
chan11_raw RC channel 11 value, in microseconds
chan12_raw RC channel 12 value, in microseconds
rssi Receive signal strength indicator, 0: 0%, 255: 100%
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 145 of file mavlink_msg_hil_rc_inputs_raw.h.
Referenced by mavlink_msg_hil_rc_inputs_raw_encode_chan(), and mavlink_test_hil_rc_inputs_raw().