APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_battery2.h File Reference
mavlink_msg_battery2.h File Reference
Classes
struct __mavlink_battery2_t
Macros
#define MAVLINK_MSG_ID_BATTERY2 181
#define MAVLINK_MSG_ID_BATTERY2_LEN 4
#define MAVLINK_MSG_ID_181_LEN 4
#define MAVLINK_MSG_ID_BATTERY2_CRC 174
#define MAVLINK_MSG_ID_181_CRC 174
#define MAVLINK_MESSAGE_INFO_BATTERY2
Typedefs
typedef struct __mavlink_battery2_t mavlink_battery2_t
Functions
static uint16_t mavlink_msg_battery2_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t voltage, int16_t current_battery)
Pack a battery2 message.
static uint16_t mavlink_msg_battery2_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t voltage, int16_t current_battery)
Pack a battery2 message on a channel.
static uint16_t mavlink_msg_battery2_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_battery2_t *battery2)
Encode a battery2 struct.
static uint16_t mavlink_msg_battery2_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_battery2_t *battery2)
Encode a battery2 struct on a channel.
static uint16_t mavlink_msg_battery2_get_voltage (const mavlink_message_t *msg)
Send a battery2 message.
static int16_t mavlink_msg_battery2_get_current_battery (const mavlink_message_t *msg)
Get field current_battery from battery2 message.
static void mavlink_msg_battery2_decode (const mavlink_message_t *msg, mavlink_battery2_t *battery2)
Decode a battery2 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_BATTERY2
Value:
{ \
    "BATTERY2", \
    2, \
    {  { "voltage", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_battery2_t, voltage) }, \
         { "current_battery", NULL, MAVLINK_TYPE_INT16_T, 0, 2, offsetof(mavlink_battery2_t, current_battery) }, \
         } \
}
Definition at line 19 of file mavlink_msg_battery2.h.
#define MAVLINK_MSG_ID_181_CRC 174
Definition at line 15 of file mavlink_msg_battery2.h.
#define MAVLINK_MSG_ID_181_LEN 4
Definition at line 12 of file mavlink_msg_battery2.h.
#define MAVLINK_MSG_ID_BATTERY2 181
Definition at line 3 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_pack(), and mavlink_msg_battery2_pack_chan().
#define MAVLINK_MSG_ID_BATTERY2_CRC 174
Definition at line 14 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_pack(), and mavlink_msg_battery2_pack_chan().
#define MAVLINK_MSG_ID_BATTERY2_LEN 4
Definition at line 11 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_decode(), mavlink_msg_battery2_pack(), and mavlink_msg_battery2_pack_chan().
Typedef Documentation
typedef struct __mavlink_battery2_t mavlink_battery2_t
Function Documentation
static void mavlink_msg_battery2_decode (const mavlink_message_t * msg, mavlink_battery2_t * battery2) inline static
Decode a battery2 message into a struct.
Parameters
msg The message to decode
battery2 C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_battery2.h.
Referenced by mavlink_test_battery2().
static uint16_t mavlink_msg_battery2_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_battery2_t * battery2) inline static
Encode a battery2 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
battery2 C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_battery2.h.
Referenced by mavlink_test_battery2().
static uint16_t mavlink_msg_battery2_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_battery2_t * battery2) inline static
Encode a battery2 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
battery2 C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_battery2.h.
static int16_t mavlink_msg_battery2_get_current_battery (const mavlink_message_t * msg) inline static
Get field current_battery from battery2 message.
Returns
Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
Definition at line 214 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_decode().
static uint16_t mavlink_msg_battery2_get_voltage (const mavlink_message_t * msg) inline static
Send a battery2 message.
Parameters
chan MAVLink channel to send the message
voltage voltage in millivolts
current_battery Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current Get field voltage from battery2 message
Returns
voltage in millivolts
Definition at line 204 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_decode().
static uint16_t mavlink_msg_battery2_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t voltage, int16_t current_battery) inline static
Pack a battery2 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
voltage voltage in millivolts
current_battery Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_encode(), and mavlink_test_battery2().
static uint16_t mavlink_msg_battery2_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t voltage, int16_t current_battery) inline static
Pack a battery2 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
voltage voltage in millivolts
current_battery Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_battery2.h.
Referenced by mavlink_msg_battery2_encode_chan(), and mavlink_test_battery2().