APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_log_request_data.h File Reference
mavlink_msg_log_request_data.h File Reference
Classes
struct __mavlink_log_request_data_t
Macros
#define MAVLINK_MSG_ID_LOG_REQUEST_DATA 119
#define MAVLINK_MSG_ID_LOG_REQUEST_DATA_LEN 12
#define MAVLINK_MSG_ID_119_LEN 12
#define MAVLINK_MSG_ID_LOG_REQUEST_DATA_CRC 116
#define MAVLINK_MSG_ID_119_CRC 116
#define MAVLINK_MESSAGE_INFO_LOG_REQUEST_DATA
Typedefs
typedef struct __mavlink_log_request_data_t mavlink_log_request_data_t
Functions
static uint16_t mavlink_msg_log_request_data_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t id, uint32_t ofs, uint32_t count)
Pack a log_request_data message.
static uint16_t mavlink_msg_log_request_data_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t id, uint32_t ofs, uint32_t count)
Pack a log_request_data message on a channel.
static uint16_t mavlink_msg_log_request_data_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_log_request_data_t *log_request_data)
Encode a log_request_data struct.
static uint16_t mavlink_msg_log_request_data_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_log_request_data_t *log_request_data)
Encode a log_request_data struct on a channel.
static uint8_t mavlink_msg_log_request_data_get_target_system (const mavlink_message_t *msg)
Send a log_request_data message.
static uint8_t mavlink_msg_log_request_data_get_target_component (const mavlink_message_t *msg)
Get field target_component from log_request_data message.
static uint16_t mavlink_msg_log_request_data_get_id (const mavlink_message_t *msg)
Get field id from log_request_data message.
static uint32_t mavlink_msg_log_request_data_get_ofs (const mavlink_message_t *msg)
Get field ofs from log_request_data message.
static uint32_t mavlink_msg_log_request_data_get_count (const mavlink_message_t *msg)
Get field count from log_request_data message.
static void mavlink_msg_log_request_data_decode (const mavlink_message_t *msg, mavlink_log_request_data_t *log_request_data)
Decode a log_request_data message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOG_REQUEST_DATA
Value:
{ \
    "LOG_REQUEST_DATA", \
    5, \
    {  { "ofs", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_log_request_data_t, ofs) }, \
         { "count", NULL, MAVLINK_TYPE_UINT32_T, 0, 4, offsetof(mavlink_log_request_data_t, count) }, \
         { "id", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_log_request_data_t, id) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 10, offsetof(mavlink_log_request_data_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 11, offsetof(mavlink_log_request_data_t, target_component) }, \
         } \
}
Definition at line 22 of file mavlink_msg_log_request_data.h.
#define MAVLINK_MSG_ID_119_CRC 116
Definition at line 18 of file mavlink_msg_log_request_data.h.
#define MAVLINK_MSG_ID_119_LEN 12
Definition at line 15 of file mavlink_msg_log_request_data.h.
#define MAVLINK_MSG_ID_LOG_REQUEST_DATA 119
Definition at line 3 of file mavlink_msg_log_request_data.h.
Referenced by MAVLink_routing::get_targets(), GCS_MAVLINK::handle_log_message(), mavlink_msg_log_request_data_pack(), and mavlink_msg_log_request_data_pack_chan().
#define MAVLINK_MSG_ID_LOG_REQUEST_DATA_CRC 116
Definition at line 17 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_pack(), and mavlink_msg_log_request_data_pack_chan().
#define MAVLINK_MSG_ID_LOG_REQUEST_DATA_LEN 12
Definition at line 14 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_decode(), mavlink_msg_log_request_data_pack(), and mavlink_msg_log_request_data_pack_chan().
Typedef Documentation
typedef struct __mavlink_log_request_data_t mavlink_log_request_data_t
Function Documentation
static void mavlink_msg_log_request_data_decode (const mavlink_message_t * msg, mavlink_log_request_data_t * log_request_data) inline static
Decode a log_request_data message into a struct.
Parameters
msg The message to decode
log_request_data C-struct to decode the message contents into
Definition at line 294 of file mavlink_msg_log_request_data.h.
Referenced by GCS_MAVLINK::handle_log_request_data(), and mavlink_test_log_request_data().
static uint16_t mavlink_msg_log_request_data_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_log_request_data_t * log_request_data) inline static
Encode a log_request_data struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
log_request_data C-struct to read the message contents from
Definition at line 131 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_test_log_request_data().
static uint16_t mavlink_msg_log_request_data_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_log_request_data_t * log_request_data) inline static
Encode a log_request_data struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
log_request_data C-struct to read the message contents from
Definition at line 145 of file mavlink_msg_log_request_data.h.
static uint32_t mavlink_msg_log_request_data_get_count (const mavlink_message_t * msg) inline static
Get field count from log_request_data message.
Returns
Number of bytes
Definition at line 283 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_decode().
static uint16_t mavlink_msg_log_request_data_get_id (const mavlink_message_t * msg) inline static
Get field id from log_request_data message.
Returns
Log id (from LOG_ENTRY reply)
Definition at line 263 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_decode().
static uint32_t mavlink_msg_log_request_data_get_ofs (const mavlink_message_t * msg) inline static
Get field ofs from log_request_data message.
Returns
Offset into the log
Definition at line 273 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_decode().
static uint8_t mavlink_msg_log_request_data_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from log_request_data message.
Returns
Component ID
Definition at line 253 of file mavlink_msg_log_request_data.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_log_request_data_decode().
static uint8_t mavlink_msg_log_request_data_get_target_system (const mavlink_message_t * msg) inline static
Send a log_request_data message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
id Log id (from LOG_ENTRY reply)
ofs Offset into the log
count Number of bytes Get field target_system from log_request_data message
Returns
System ID
Definition at line 243 of file mavlink_msg_log_request_data.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_log_request_data_decode().
static uint16_t mavlink_msg_log_request_data_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t id, uint32_t ofs, uint32_t count) inline static
Pack a log_request_data message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
id Log id (from LOG_ENTRY reply)
ofs Offset into the log
count Number of bytes
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_encode(), and mavlink_test_log_request_data().
static uint16_t mavlink_msg_log_request_data_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t id, uint32_t ofs, uint32_t count) inline static
Pack a log_request_data message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
id Log id (from LOG_ENTRY reply)
ofs Offset into the log
count Number of bytes
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 91 of file mavlink_msg_log_request_data.h.
Referenced by mavlink_msg_log_request_data_encode_chan(), and mavlink_test_log_request_data().