APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_camera_feedback.h File Reference
mavlink_msg_camera_feedback.h File Reference
Classes
struct __mavlink_camera_feedback_t
Macros
#define MAVLINK_MSG_ID_CAMERA_FEEDBACK 180
#define MAVLINK_MSG_ID_CAMERA_FEEDBACK_LEN 45
#define MAVLINK_MSG_ID_180_LEN 45
#define MAVLINK_MSG_ID_CAMERA_FEEDBACK_CRC 52
#define MAVLINK_MSG_ID_180_CRC 52
#define MAVLINK_MESSAGE_INFO_CAMERA_FEEDBACK
Typedefs
typedef struct __mavlink_camera_feedback_t mavlink_camera_feedback_t
Functions
static uint16_t mavlink_msg_camera_feedback_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, int32_t lat, int32_t lng, float alt_msl, float alt_rel, float roll, float pitch, float yaw, float foc_len, uint8_t flags)
Pack a camera_feedback message.
static uint16_t mavlink_msg_camera_feedback_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, int32_t lat, int32_t lng, float alt_msl, float alt_rel, float roll, float pitch, float yaw, float foc_len, uint8_t flags)
Pack a camera_feedback message on a channel.
static uint16_t mavlink_msg_camera_feedback_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_camera_feedback_t *camera_feedback)
Encode a camera_feedback struct.
static uint16_t mavlink_msg_camera_feedback_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_camera_feedback_t *camera_feedback)
Encode a camera_feedback struct on a channel.
static uint64_t mavlink_msg_camera_feedback_get_time_usec (const mavlink_message_t *msg)
Send a camera_feedback message.
static uint8_t mavlink_msg_camera_feedback_get_target_system (const mavlink_message_t *msg)
Get field target_system from camera_feedback message.
static uint8_t mavlink_msg_camera_feedback_get_cam_idx (const mavlink_message_t *msg)
Get field cam_idx from camera_feedback message.
static uint16_t mavlink_msg_camera_feedback_get_img_idx (const mavlink_message_t *msg)
Get field img_idx from camera_feedback message.
static int32_t mavlink_msg_camera_feedback_get_lat (const mavlink_message_t *msg)
Get field lat from camera_feedback message.
static int32_t mavlink_msg_camera_feedback_get_lng (const mavlink_message_t *msg)
Get field lng from camera_feedback message.
static float mavlink_msg_camera_feedback_get_alt_msl (const mavlink_message_t *msg)
Get field alt_msl from camera_feedback message.
static float mavlink_msg_camera_feedback_get_alt_rel (const mavlink_message_t *msg)
Get field alt_rel from camera_feedback message.
static float mavlink_msg_camera_feedback_get_roll (const mavlink_message_t *msg)
Get field roll from camera_feedback message.
static float mavlink_msg_camera_feedback_get_pitch (const mavlink_message_t *msg)
Get field pitch from camera_feedback message.
static float mavlink_msg_camera_feedback_get_yaw (const mavlink_message_t *msg)
Get field yaw from camera_feedback message.
static float mavlink_msg_camera_feedback_get_foc_len (const mavlink_message_t *msg)
Get field foc_len from camera_feedback message.
static uint8_t mavlink_msg_camera_feedback_get_flags (const mavlink_message_t *msg)
Get field flags from camera_feedback message.
static void mavlink_msg_camera_feedback_decode (const mavlink_message_t *msg, mavlink_camera_feedback_t *camera_feedback)
Decode a camera_feedback message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_CAMERA_FEEDBACK
Value:
{ \
    "CAMERA_FEEDBACK", \
    13, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_camera_feedback_t, time_usec) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_camera_feedback_t, lat) }, \
         { "lng", NULL, MAVLINK_TYPE_INT32_T, 0, 12, offsetof(mavlink_camera_feedback_t, lng) }, \
         { "alt_msl", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_camera_feedback_t, alt_msl) }, \
         { "alt_rel", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_camera_feedback_t, alt_rel) }, \
         { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_camera_feedback_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_camera_feedback_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_camera_feedback_t, yaw) }, \
         { "foc_len", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_camera_feedback_t, foc_len) }, \
         { "img_idx", NULL, MAVLINK_TYPE_UINT16_T, 0, 40, offsetof(mavlink_camera_feedback_t, img_idx) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 42, offsetof(mavlink_camera_feedback_t, target_system) }, \
         { "cam_idx", NULL, MAVLINK_TYPE_UINT8_T, 0, 43, offsetof(mavlink_camera_feedback_t, cam_idx) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT8_T, 0, 44, offsetof(mavlink_camera_feedback_t, flags) }, \
         } \
}
Definition at line 30 of file mavlink_msg_camera_feedback.h.
#define MAVLINK_MSG_ID_180_CRC 52
Definition at line 26 of file mavlink_msg_camera_feedback.h.
#define MAVLINK_MSG_ID_180_LEN 45
Definition at line 23 of file mavlink_msg_camera_feedback.h.
#define MAVLINK_MSG_ID_CAMERA_FEEDBACK 180
Definition at line 3 of file mavlink_msg_camera_feedback.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_camera_feedback_pack(), and mavlink_msg_camera_feedback_pack_chan().
#define MAVLINK_MSG_ID_CAMERA_FEEDBACK_CRC 52
Definition at line 25 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_pack(), and mavlink_msg_camera_feedback_pack_chan().
#define MAVLINK_MSG_ID_CAMERA_FEEDBACK_LEN 45
Definition at line 22 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode(), mavlink_msg_camera_feedback_pack(), and mavlink_msg_camera_feedback_pack_chan().
Typedef Documentation
typedef struct __mavlink_camera_feedback_t mavlink_camera_feedback_t
Function Documentation
static void mavlink_msg_camera_feedback_decode (const mavlink_message_t * msg, mavlink_camera_feedback_t * camera_feedback) inline static
Decode a camera_feedback message into a struct.
Parameters
msg The message to decode
camera_feedback C-struct to decode the message contents into
Definition at line 478 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_test_camera_feedback().
static uint16_t mavlink_msg_camera_feedback_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_camera_feedback_t * camera_feedback) inline static
Encode a camera_feedback struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
camera_feedback C-struct to read the message contents from
Definition at line 195 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_test_camera_feedback().
static uint16_t mavlink_msg_camera_feedback_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_camera_feedback_t * camera_feedback) inline static
Encode a camera_feedback struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
camera_feedback C-struct to read the message contents from
Definition at line 209 of file mavlink_msg_camera_feedback.h.
static float mavlink_msg_camera_feedback_get_alt_msl (const mavlink_message_t * msg) inline static
Get field alt_msl from camera_feedback message.
Returns
Altitude Absolute (meters AMSL)
Definition at line 407 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static float mavlink_msg_camera_feedback_get_alt_rel (const mavlink_message_t * msg) inline static
Get field alt_rel from camera_feedback message.
Returns
Altitude Relative (meters above HOME location)
Definition at line 417 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static uint8_t mavlink_msg_camera_feedback_get_cam_idx (const mavlink_message_t * msg) inline static
Get field cam_idx from camera_feedback message.
Returns
Camera ID
Definition at line 367 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static uint8_t mavlink_msg_camera_feedback_get_flags (const mavlink_message_t * msg) inline static
Get field flags from camera_feedback message.
Returns
See CAMERA_FEEDBACK_FLAGS enum for definition of the bitmask
Definition at line 467 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static float mavlink_msg_camera_feedback_get_foc_len (const mavlink_message_t * msg) inline static
Get field foc_len from camera_feedback message.
Returns
Focal Length (mm)
Definition at line 457 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static uint16_t mavlink_msg_camera_feedback_get_img_idx (const mavlink_message_t * msg) inline static
Get field img_idx from camera_feedback message.
Returns
Image index
Definition at line 377 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static int32_t mavlink_msg_camera_feedback_get_lat (const mavlink_message_t * msg) inline static
Get field lat from camera_feedback message.
Returns
Latitude in (deg * 1E7)
Definition at line 387 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static int32_t mavlink_msg_camera_feedback_get_lng (const mavlink_message_t * msg) inline static
Get field lng from camera_feedback message.
Returns
Longitude in (deg * 1E7)
Definition at line 397 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static float mavlink_msg_camera_feedback_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from camera_feedback message.
Returns
Camera Pitch angle (earth frame, degrees, +-180)
Definition at line 437 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static float mavlink_msg_camera_feedback_get_roll (const mavlink_message_t * msg) inline static
Get field roll from camera_feedback message.
Returns
Camera Roll angle (earth frame, degrees, +-180)
Definition at line 427 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static uint8_t mavlink_msg_camera_feedback_get_target_system (const mavlink_message_t * msg) inline static
Get field target_system from camera_feedback message.
Returns
System ID
Definition at line 357 of file mavlink_msg_camera_feedback.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_camera_feedback_decode().
static uint64_t mavlink_msg_camera_feedback_get_time_usec (const mavlink_message_t * msg) inline static
Send a camera_feedback message.
Parameters
chan MAVLink channel to send the message
time_usec Image timestamp (microseconds since UNIX epoch), as passed in by CAMERA_STATUS message (or autopilot if no CCB)
target_system System ID
cam_idx Camera ID
img_idx Image index
lat Latitude in (deg * 1E7)
lng Longitude in (deg * 1E7)
alt_msl Altitude Absolute (meters AMSL)
alt_rel Altitude Relative (meters above HOME location)
roll Camera Roll angle (earth frame, degrees, +-180)
pitch Camera Pitch angle (earth frame, degrees, +-180)
yaw Camera Yaw (earth frame, degrees, 0-360, true)
foc_len Focal Length (mm)
flags See CAMERA_FEEDBACK_FLAGS enum for definition of the bitmask Get field time_usec from camera_feedback message
Returns
Image timestamp (microseconds since UNIX epoch), as passed in by CAMERA_STATUS message (or autopilot if no CCB)
Definition at line 347 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static float mavlink_msg_camera_feedback_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from camera_feedback message.
Returns
Camera Yaw (earth frame, degrees, 0-360, true)
Definition at line 447 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_decode().
static uint16_t mavlink_msg_camera_feedback_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, int32_t lat, int32_t lng, float alt_msl, float alt_rel, float roll, float pitch, float yaw, float foc_len, uint8_t flags) inline static
Pack a camera_feedback message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Image timestamp (microseconds since UNIX epoch), as passed in by CAMERA_STATUS message (or autopilot if no CCB)
target_system System ID
cam_idx Camera ID
img_idx Image index
lat Latitude in (deg * 1E7)
lng Longitude in (deg * 1E7)
alt_msl Altitude Absolute (meters AMSL)
alt_rel Altitude Relative (meters above HOME location)
roll Camera Roll angle (earth frame, degrees, +-180)
pitch Camera Pitch angle (earth frame, degrees, +-180)
yaw Camera Yaw (earth frame, degrees, 0-360, true)
foc_len Focal Length (mm)
flags See CAMERA_FEEDBACK_FLAGS enum for definition of the bitmask
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 71 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_encode(), and mavlink_test_camera_feedback().
static uint16_t mavlink_msg_camera_feedback_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, int32_t lat, int32_t lng, float alt_msl, float alt_rel, float roll, float pitch, float yaw, float foc_len, uint8_t flags) inline static
Pack a camera_feedback message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Image timestamp (microseconds since UNIX epoch), as passed in by CAMERA_STATUS message (or autopilot if no CCB)
target_system System ID
cam_idx Camera ID
img_idx Image index
lat Latitude in (deg * 1E7)
lng Longitude in (deg * 1E7)
alt_msl Altitude Absolute (meters AMSL)
alt_rel Altitude Relative (meters above HOME location)
roll Camera Roll angle (earth frame, degrees, +-180)
pitch Camera Pitch angle (earth frame, degrees, +-180)
yaw Camera Yaw (earth frame, degrees, 0-360, true)
foc_len Focal Length (mm)
flags See CAMERA_FEEDBACK_FLAGS enum for definition of the bitmask
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 139 of file mavlink_msg_camera_feedback.h.
Referenced by mavlink_msg_camera_feedback_encode_chan(), and mavlink_test_camera_feedback().