APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_request_axis_calibration_status.h File Reference
mavlink_msg_gimbal_request_axis_calibration_status.h File Reference
Classes
struct __mavlink_gimbal_request_axis_calibration_status_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS 211
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS_LEN 2
#define MAVLINK_MSG_ID_211_LEN 2
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS_CRC 103
#define MAVLINK_MSG_ID_211_CRC 103
#define MAVLINK_MESSAGE_INFO_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS
Typedefs
typedef struct __mavlink_gimbal_request_axis_calibration_status_t mavlink_gimbal_request_axis_calibration_status_t
Functions
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a gimbal_request_axis_calibration_status message.
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a gimbal_request_axis_calibration_status message on a channel.
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_request_axis_calibration_status_t *gimbal_request_axis_calibration_status)
Encode a gimbal_request_axis_calibration_status struct.
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_request_axis_calibration_status_t *gimbal_request_axis_calibration_status)
Encode a gimbal_request_axis_calibration_status struct on a channel.
static uint8_t mavlink_msg_gimbal_request_axis_calibration_status_get_target_system (const mavlink_message_t *msg)
Send a gimbal_request_axis_calibration_status message.
static uint8_t mavlink_msg_gimbal_request_axis_calibration_status_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_request_axis_calibration_status message.
static void mavlink_msg_gimbal_request_axis_calibration_status_decode (const mavlink_message_t *msg, mavlink_gimbal_request_axis_calibration_status_t *gimbal_request_axis_calibration_status)
Decode a gimbal_request_axis_calibration_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS
Value:
{ \
    "GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS", \
    2, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_request_axis_calibration_status_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gimbal_request_axis_calibration_status_t, target_component) }, \
         } \
}
Definition at line 19 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
#define MAVLINK_MSG_ID_211_CRC 103
Definition at line 15 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
#define MAVLINK_MSG_ID_211_LEN 2
Definition at line 12 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS 211
Definition at line 3 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_pack(), and mavlink_msg_gimbal_request_axis_calibration_status_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS_CRC 103
Definition at line 14 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_pack(), and mavlink_msg_gimbal_request_axis_calibration_status_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_STATUS_LEN 2
Definition at line 11 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_decode(), mavlink_msg_gimbal_request_axis_calibration_status_pack(), and mavlink_msg_gimbal_request_axis_calibration_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_request_axis_calibration_status_t mavlink_gimbal_request_axis_calibration_status_t
Function Documentation
static void mavlink_msg_gimbal_request_axis_calibration_status_decode (const mavlink_message_t * msg, mavlink_gimbal_request_axis_calibration_status_t * gimbal_request_axis_calibration_status) inline static
Decode a gimbal_request_axis_calibration_status message into a struct.
Parameters
msg The message to decode
gimbal_request_axis_calibration_status C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_test_gimbal_request_axis_calibration_status().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_request_axis_calibration_status_t * gimbal_request_axis_calibration_status) inline static
Encode a gimbal_request_axis_calibration_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_request_axis_calibration_status C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_test_gimbal_request_axis_calibration_status().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_request_axis_calibration_status_t * gimbal_request_axis_calibration_status) inline static
Encode a gimbal_request_axis_calibration_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_request_axis_calibration_status C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
static uint8_t mavlink_msg_gimbal_request_axis_calibration_status_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_request_axis_calibration_status message.
Returns
Component ID
Definition at line 214 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_decode().
static uint8_t mavlink_msg_gimbal_request_axis_calibration_status_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_request_axis_calibration_status message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID Get field target_system from gimbal_request_axis_calibration_status message
Returns
System ID
Definition at line 204 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_decode().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a gimbal_request_axis_calibration_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_encode(), and mavlink_test_gimbal_request_axis_calibration_status().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a gimbal_request_axis_calibration_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_gimbal_request_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_status_encode_chan(), and mavlink_test_gimbal_request_axis_calibration_status().