APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_axis_calibration_progress.h File Reference
mavlink_msg_gimbal_axis_calibration_progress.h File Reference
Classes
struct __mavlink_gimbal_axis_calibration_progress_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_AXIS_CALIBRATION_PROGRESS 203
#define MAVLINK_MSG_ID_GIMBAL_AXIS_CALIBRATION_PROGRESS_LEN 3
#define MAVLINK_MSG_ID_203_LEN 3
#define MAVLINK_MSG_ID_GIMBAL_AXIS_CALIBRATION_PROGRESS_CRC 128
#define MAVLINK_MSG_ID_203_CRC 128
#define MAVLINK_MESSAGE_INFO_GIMBAL_AXIS_CALIBRATION_PROGRESS
Typedefs
typedef struct __mavlink_gimbal_axis_calibration_progress_t mavlink_gimbal_axis_calibration_progress_t
Functions
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t calibration_axis, uint8_t calibration_progress, uint8_t calibration_status)
Pack a gimbal_axis_calibration_progress message.
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t calibration_axis, uint8_t calibration_progress, uint8_t calibration_status)
Pack a gimbal_axis_calibration_progress message on a channel.
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_axis_calibration_progress_t *gimbal_axis_calibration_progress)
Encode a gimbal_axis_calibration_progress struct.
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_axis_calibration_progress_t *gimbal_axis_calibration_progress)
Encode a gimbal_axis_calibration_progress struct on a channel.
static uint8_t mavlink_msg_gimbal_axis_calibration_progress_get_calibration_axis (const mavlink_message_t *msg)
Send a gimbal_axis_calibration_progress message.
static uint8_t mavlink_msg_gimbal_axis_calibration_progress_get_calibration_progress (const mavlink_message_t *msg)
Get field calibration_progress from gimbal_axis_calibration_progress message.
static uint8_t mavlink_msg_gimbal_axis_calibration_progress_get_calibration_status (const mavlink_message_t *msg)
Get field calibration_status from gimbal_axis_calibration_progress message.
static void mavlink_msg_gimbal_axis_calibration_progress_decode (const mavlink_message_t *msg, mavlink_gimbal_axis_calibration_progress_t *gimbal_axis_calibration_progress)
Decode a gimbal_axis_calibration_progress message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_AXIS_CALIBRATION_PROGRESS
Value:
{ \
    "GIMBAL_AXIS_CALIBRATION_PROGRESS", \
    3, \
    {  { "calibration_axis", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_axis_calibration_progress_t, calibration_axis) }, \
         { "calibration_progress", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gimbal_axis_calibration_progress_t, calibration_progress) }, \
         { "calibration_status", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_gimbal_axis_calibration_progress_t, calibration_status) }, \
         } \
}
Definition at line 20 of file mavlink_msg_gimbal_axis_calibration_progress.h.
#define MAVLINK_MSG_ID_203_CRC 128
Definition at line 16 of file mavlink_msg_gimbal_axis_calibration_progress.h.
#define MAVLINK_MSG_ID_203_LEN 3
Definition at line 13 of file mavlink_msg_gimbal_axis_calibration_progress.h.
#define MAVLINK_MSG_ID_GIMBAL_AXIS_CALIBRATION_PROGRESS 203
Definition at line 3 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_pack(), and mavlink_msg_gimbal_axis_calibration_progress_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_AXIS_CALIBRATION_PROGRESS_CRC 128
Definition at line 15 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_pack(), and mavlink_msg_gimbal_axis_calibration_progress_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_AXIS_CALIBRATION_PROGRESS_LEN 3
Definition at line 12 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_decode(), mavlink_msg_gimbal_axis_calibration_progress_pack(), and mavlink_msg_gimbal_axis_calibration_progress_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_axis_calibration_progress_t mavlink_gimbal_axis_calibration_progress_t
Function Documentation
static void mavlink_msg_gimbal_axis_calibration_progress_decode (const mavlink_message_t * msg, mavlink_gimbal_axis_calibration_progress_t * gimbal_axis_calibration_progress) inline static
Decode a gimbal_axis_calibration_progress message into a struct.
Parameters
msg The message to decode
gimbal_axis_calibration_progress C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_test_gimbal_axis_calibration_progress().
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_axis_calibration_progress_t * gimbal_axis_calibration_progress) inline static
Encode a gimbal_axis_calibration_progress struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_axis_calibration_progress C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_test_gimbal_axis_calibration_progress().
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_axis_calibration_progress_t * gimbal_axis_calibration_progress) inline static
Encode a gimbal_axis_calibration_progress struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_axis_calibration_progress C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_gimbal_axis_calibration_progress.h.
static uint8_t mavlink_msg_gimbal_axis_calibration_progress_get_calibration_axis (const mavlink_message_t * msg) inline static
Send a gimbal_axis_calibration_progress message.
Parameters
chan MAVLink channel to send the message
calibration_axis Which gimbal axis we're reporting calibration progress for
calibration_progress The current calibration progress for this axis, 0x64=100%
calibration_status The status of the running calibration Get field calibration_axis from gimbal_axis_calibration_progress message
Returns
Which gimbal axis we're reporting calibration progress for
Definition at line 217 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_decode().
static uint8_t mavlink_msg_gimbal_axis_calibration_progress_get_calibration_progress (const mavlink_message_t * msg) inline static
Get field calibration_progress from gimbal_axis_calibration_progress message.
Returns
The current calibration progress for this axis, 0x64=100%
Definition at line 227 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_decode().
static uint8_t mavlink_msg_gimbal_axis_calibration_progress_get_calibration_status (const mavlink_message_t * msg) inline static
Get field calibration_status from gimbal_axis_calibration_progress message.
Returns
The status of the running calibration
Definition at line 237 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_decode().
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t calibration_axis, uint8_t calibration_progress, uint8_t calibration_status) inline static
Pack a gimbal_axis_calibration_progress message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
calibration_axis Which gimbal axis we're reporting calibration progress for
calibration_progress The current calibration progress for this axis, 0x64=100%
calibration_status The status of the running calibration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_encode(), and mavlink_test_gimbal_axis_calibration_progress().
static uint16_t mavlink_msg_gimbal_axis_calibration_progress_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t calibration_axis, uint8_t calibration_progress, uint8_t calibration_status) inline static
Pack a gimbal_axis_calibration_progress message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
calibration_axis Which gimbal axis we're reporting calibration progress for
calibration_progress The current calibration progress for this axis, 0x64=100%
calibration_status The status of the running calibration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_gimbal_axis_calibration_progress.h.
Referenced by mavlink_msg_gimbal_axis_calibration_progress_encode_chan(), and mavlink_test_gimbal_axis_calibration_progress().