APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_log_request_end.h File Reference
mavlink_msg_log_request_end.h File Reference
Classes
struct __mavlink_log_request_end_t
Macros
#define MAVLINK_MSG_ID_LOG_REQUEST_END 122
#define MAVLINK_MSG_ID_LOG_REQUEST_END_LEN 2
#define MAVLINK_MSG_ID_122_LEN 2
#define MAVLINK_MSG_ID_LOG_REQUEST_END_CRC 203
#define MAVLINK_MSG_ID_122_CRC 203
#define MAVLINK_MESSAGE_INFO_LOG_REQUEST_END
Typedefs
typedef struct __mavlink_log_request_end_t mavlink_log_request_end_t
Functions
static uint16_t mavlink_msg_log_request_end_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a log_request_end message.
static uint16_t mavlink_msg_log_request_end_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a log_request_end message on a channel.
static uint16_t mavlink_msg_log_request_end_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_log_request_end_t *log_request_end)
Encode a log_request_end struct.
static uint16_t mavlink_msg_log_request_end_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_log_request_end_t *log_request_end)
Encode a log_request_end struct on a channel.
static uint8_t mavlink_msg_log_request_end_get_target_system (const mavlink_message_t *msg)
Send a log_request_end message.
static uint8_t mavlink_msg_log_request_end_get_target_component (const mavlink_message_t *msg)
Get field target_component from log_request_end message.
static void mavlink_msg_log_request_end_decode (const mavlink_message_t *msg, mavlink_log_request_end_t *log_request_end)
Decode a log_request_end message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOG_REQUEST_END
Value:
{ \
    "LOG_REQUEST_END", \
    2, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_log_request_end_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_log_request_end_t, target_component) }, \
         } \
}
Definition at line 19 of file mavlink_msg_log_request_end.h.
#define MAVLINK_MSG_ID_122_CRC 203
Definition at line 15 of file mavlink_msg_log_request_end.h.
#define MAVLINK_MSG_ID_122_LEN 2
Definition at line 12 of file mavlink_msg_log_request_end.h.
#define MAVLINK_MSG_ID_LOG_REQUEST_END 122
Definition at line 3 of file mavlink_msg_log_request_end.h.
Referenced by MAVLink_routing::get_targets(), GCS_MAVLINK::handle_log_message(), mavlink_msg_log_request_end_pack(), and mavlink_msg_log_request_end_pack_chan().
#define MAVLINK_MSG_ID_LOG_REQUEST_END_CRC 203
Definition at line 14 of file mavlink_msg_log_request_end.h.
Referenced by mavlink_msg_log_request_end_pack(), and mavlink_msg_log_request_end_pack_chan().
#define MAVLINK_MSG_ID_LOG_REQUEST_END_LEN 2
Definition at line 11 of file mavlink_msg_log_request_end.h.
Referenced by mavlink_msg_log_request_end_decode(), mavlink_msg_log_request_end_pack(), and mavlink_msg_log_request_end_pack_chan().
Typedef Documentation
typedef struct __mavlink_log_request_end_t mavlink_log_request_end_t
Function Documentation
static void mavlink_msg_log_request_end_decode (const mavlink_message_t * msg, mavlink_log_request_end_t * log_request_end) inline static
Decode a log_request_end message into a struct.
Parameters
msg The message to decode
log_request_end C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_log_request_end.h.
Referenced by GCS_MAVLINK::handle_log_request_end(), and mavlink_test_log_request_end().
static uint16_t mavlink_msg_log_request_end_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_log_request_end_t * log_request_end) inline static
Encode a log_request_end struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
log_request_end C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_log_request_end.h.
Referenced by mavlink_test_log_request_end().
static uint16_t mavlink_msg_log_request_end_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_log_request_end_t * log_request_end) inline static
Encode a log_request_end struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
log_request_end C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_log_request_end.h.
static uint8_t mavlink_msg_log_request_end_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from log_request_end message.
Returns
Component ID
Definition at line 214 of file mavlink_msg_log_request_end.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_log_request_end_decode().
static uint8_t mavlink_msg_log_request_end_get_target_system (const mavlink_message_t * msg) inline static
Send a log_request_end message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID Get field target_system from log_request_end message
Returns
System ID
Definition at line 204 of file mavlink_msg_log_request_end.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_log_request_end_decode().
static uint16_t mavlink_msg_log_request_end_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a log_request_end message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_log_request_end.h.
Referenced by mavlink_msg_log_request_end_encode(), and mavlink_test_log_request_end().
static uint16_t mavlink_msg_log_request_end_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a log_request_end message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_log_request_end.h.
Referenced by mavlink_msg_log_request_end_encode_chan(), and mavlink_test_log_request_end().