APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_fence_fetch_point.h File Reference
mavlink_msg_fence_fetch_point.h File Reference
Classes
struct __mavlink_fence_fetch_point_t
Macros
#define MAVLINK_MSG_ID_FENCE_FETCH_POINT 161
#define MAVLINK_MSG_ID_FENCE_FETCH_POINT_LEN 3
#define MAVLINK_MSG_ID_161_LEN 3
#define MAVLINK_MSG_ID_FENCE_FETCH_POINT_CRC 68
#define MAVLINK_MSG_ID_161_CRC 68
#define MAVLINK_MESSAGE_INFO_FENCE_FETCH_POINT
Typedefs
typedef struct __mavlink_fence_fetch_point_t mavlink_fence_fetch_point_t
Functions
static uint16_t mavlink_msg_fence_fetch_point_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t idx)
Pack a fence_fetch_point message.
static uint16_t mavlink_msg_fence_fetch_point_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t idx)
Pack a fence_fetch_point message on a channel.
static uint16_t mavlink_msg_fence_fetch_point_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_fence_fetch_point_t *fence_fetch_point)
Encode a fence_fetch_point struct.
static uint16_t mavlink_msg_fence_fetch_point_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_fence_fetch_point_t *fence_fetch_point)
Encode a fence_fetch_point struct on a channel.
static uint8_t mavlink_msg_fence_fetch_point_get_target_system (const mavlink_message_t *msg)
Send a fence_fetch_point message.
static uint8_t mavlink_msg_fence_fetch_point_get_target_component (const mavlink_message_t *msg)
Get field target_component from fence_fetch_point message.
static uint8_t mavlink_msg_fence_fetch_point_get_idx (const mavlink_message_t *msg)
Get field idx from fence_fetch_point message.
static void mavlink_msg_fence_fetch_point_decode (const mavlink_message_t *msg, mavlink_fence_fetch_point_t *fence_fetch_point)
Decode a fence_fetch_point message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_FENCE_FETCH_POINT
Value:
{ \
    "FENCE_FETCH_POINT", \
    3, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_fence_fetch_point_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_fence_fetch_point_t, target_component) }, \
         { "idx", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_fence_fetch_point_t, idx) }, \
         } \
}
Definition at line 20 of file mavlink_msg_fence_fetch_point.h.
#define MAVLINK_MSG_ID_161_CRC 68
Definition at line 16 of file mavlink_msg_fence_fetch_point.h.
#define MAVLINK_MSG_ID_161_LEN 3
Definition at line 13 of file mavlink_msg_fence_fetch_point.h.
#define MAVLINK_MSG_ID_FENCE_FETCH_POINT 161
Definition at line 3 of file mavlink_msg_fence_fetch_point.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_fence_fetch_point_pack(), and mavlink_msg_fence_fetch_point_pack_chan().
#define MAVLINK_MSG_ID_FENCE_FETCH_POINT_CRC 68
Definition at line 15 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_msg_fence_fetch_point_pack(), and mavlink_msg_fence_fetch_point_pack_chan().
#define MAVLINK_MSG_ID_FENCE_FETCH_POINT_LEN 3
Definition at line 12 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_msg_fence_fetch_point_decode(), mavlink_msg_fence_fetch_point_pack(), and mavlink_msg_fence_fetch_point_pack_chan().
Typedef Documentation
typedef struct __mavlink_fence_fetch_point_t mavlink_fence_fetch_point_t
Function Documentation
static void mavlink_msg_fence_fetch_point_decode (const mavlink_message_t * msg, mavlink_fence_fetch_point_t * fence_fetch_point) inline static
Decode a fence_fetch_point message into a struct.
Parameters
msg The message to decode
fence_fetch_point C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_test_fence_fetch_point().
static uint16_t mavlink_msg_fence_fetch_point_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_fence_fetch_point_t * fence_fetch_point) inline static
Encode a fence_fetch_point struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
fence_fetch_point C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_test_fence_fetch_point().
static uint16_t mavlink_msg_fence_fetch_point_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_fence_fetch_point_t * fence_fetch_point) inline static
Encode a fence_fetch_point struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
fence_fetch_point C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_fence_fetch_point.h.
static uint8_t mavlink_msg_fence_fetch_point_get_idx (const mavlink_message_t * msg) inline static
Get field idx from fence_fetch_point message.
Returns
point index (first point is 1, 0 is for return point)
Definition at line 237 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_msg_fence_fetch_point_decode().
static uint8_t mavlink_msg_fence_fetch_point_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from fence_fetch_point message.
Returns
Component ID
Definition at line 227 of file mavlink_msg_fence_fetch_point.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_fence_fetch_point_decode().
static uint8_t mavlink_msg_fence_fetch_point_get_target_system (const mavlink_message_t * msg) inline static
Send a fence_fetch_point message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
idx point index (first point is 1, 0 is for return point) Get field target_system from fence_fetch_point message
Returns
System ID
Definition at line 217 of file mavlink_msg_fence_fetch_point.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_fence_fetch_point_decode().
static uint16_t mavlink_msg_fence_fetch_point_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t idx) inline static
Pack a fence_fetch_point message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
idx point index (first point is 1, 0 is for return point)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_msg_fence_fetch_point_encode(), and mavlink_test_fence_fetch_point().
static uint16_t mavlink_msg_fence_fetch_point_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t idx) inline static
Pack a fence_fetch_point message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
idx point index (first point is 1, 0 is for return point)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_fence_fetch_point.h.
Referenced by mavlink_msg_fence_fetch_point_encode_chan(), and mavlink_test_fence_fetch_point().