APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_mag_cal_report.h File Reference
mavlink_msg_mag_cal_report.h File Reference
Classes
struct __mavlink_mag_cal_report_t
Macros
#define MAVLINK_MSG_ID_MAG_CAL_REPORT 192
#define MAVLINK_MSG_ID_MAG_CAL_REPORT_LEN 44
#define MAVLINK_MSG_ID_192_LEN 44
#define MAVLINK_MSG_ID_MAG_CAL_REPORT_CRC 36
#define MAVLINK_MSG_ID_192_CRC 36
#define MAVLINK_MESSAGE_INFO_MAG_CAL_REPORT
Typedefs
typedef struct __mavlink_mag_cal_report_t mavlink_mag_cal_report_t
Functions
static uint16_t mavlink_msg_mag_cal_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t autosaved, float fitness, float ofs_x, float ofs_y, float ofs_z, float diag_x, float diag_y, float diag_z, float offdiag_x, float offdiag_y, float offdiag_z)
Pack a mag_cal_report message.
static uint16_t mavlink_msg_mag_cal_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t autosaved, float fitness, float ofs_x, float ofs_y, float ofs_z, float diag_x, float diag_y, float diag_z, float offdiag_x, float offdiag_y, float offdiag_z)
Pack a mag_cal_report message on a channel.
static uint16_t mavlink_msg_mag_cal_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mag_cal_report_t *mag_cal_report)
Encode a mag_cal_report struct.
static uint16_t mavlink_msg_mag_cal_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mag_cal_report_t *mag_cal_report)
Encode a mag_cal_report struct on a channel.
static uint8_t mavlink_msg_mag_cal_report_get_compass_id (const mavlink_message_t *msg)
Send a mag_cal_report message.
static uint8_t mavlink_msg_mag_cal_report_get_cal_mask (const mavlink_message_t *msg)
Get field cal_mask from mag_cal_report message.
static uint8_t mavlink_msg_mag_cal_report_get_cal_status (const mavlink_message_t *msg)
Get field cal_status from mag_cal_report message.
static uint8_t mavlink_msg_mag_cal_report_get_autosaved (const mavlink_message_t *msg)
Get field autosaved from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_fitness (const mavlink_message_t *msg)
Get field fitness from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_ofs_x (const mavlink_message_t *msg)
Get field ofs_x from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_ofs_y (const mavlink_message_t *msg)
Get field ofs_y from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_ofs_z (const mavlink_message_t *msg)
Get field ofs_z from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_diag_x (const mavlink_message_t *msg)
Get field diag_x from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_diag_y (const mavlink_message_t *msg)
Get field diag_y from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_diag_z (const mavlink_message_t *msg)
Get field diag_z from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_offdiag_x (const mavlink_message_t *msg)
Get field offdiag_x from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_offdiag_y (const mavlink_message_t *msg)
Get field offdiag_y from mag_cal_report message.
static float mavlink_msg_mag_cal_report_get_offdiag_z (const mavlink_message_t *msg)
Get field offdiag_z from mag_cal_report message.
static void mavlink_msg_mag_cal_report_decode (const mavlink_message_t *msg, mavlink_mag_cal_report_t *mag_cal_report)
Decode a mag_cal_report message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MAG_CAL_REPORT
Value:
{ \
    "MAG_CAL_REPORT", \
    14, \
    {  { "fitness", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_mag_cal_report_t, fitness) }, \
         { "ofs_x", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_mag_cal_report_t, ofs_x) }, \
         { "ofs_y", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_mag_cal_report_t, ofs_y) }, \
         { "ofs_z", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_mag_cal_report_t, ofs_z) }, \
         { "diag_x", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_mag_cal_report_t, diag_x) }, \
         { "diag_y", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_mag_cal_report_t, diag_y) }, \
         { "diag_z", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_mag_cal_report_t, diag_z) }, \
         { "offdiag_x", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_mag_cal_report_t, offdiag_x) }, \
         { "offdiag_y", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_mag_cal_report_t, offdiag_y) }, \
         { "offdiag_z", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_mag_cal_report_t, offdiag_z) }, \
         { "compass_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 40, offsetof(mavlink_mag_cal_report_t, compass_id) }, \
         { "cal_mask", NULL, MAVLINK_TYPE_UINT8_T, 0, 41, offsetof(mavlink_mag_cal_report_t, cal_mask) }, \
         { "cal_status", NULL, MAVLINK_TYPE_UINT8_T, 0, 42, offsetof(mavlink_mag_cal_report_t, cal_status) }, \
         { "autosaved", NULL, MAVLINK_TYPE_UINT8_T, 0, 43, offsetof(mavlink_mag_cal_report_t, autosaved) }, \
         } \
}
Definition at line 31 of file mavlink_msg_mag_cal_report.h.
#define MAVLINK_MSG_ID_192_CRC 36
Definition at line 27 of file mavlink_msg_mag_cal_report.h.
#define MAVLINK_MSG_ID_192_LEN 44
Definition at line 24 of file mavlink_msg_mag_cal_report.h.
#define MAVLINK_MSG_ID_MAG_CAL_REPORT 192
Definition at line 3 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_pack(), and mavlink_msg_mag_cal_report_pack_chan().
#define MAVLINK_MSG_ID_MAG_CAL_REPORT_CRC 36
Definition at line 26 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_pack(), and mavlink_msg_mag_cal_report_pack_chan().
#define MAVLINK_MSG_ID_MAG_CAL_REPORT_LEN 44
Definition at line 23 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode(), mavlink_msg_mag_cal_report_pack(), and mavlink_msg_mag_cal_report_pack_chan().
Typedef Documentation
typedef struct __mavlink_mag_cal_report_t mavlink_mag_cal_report_t
Function Documentation
static void mavlink_msg_mag_cal_report_decode (const mavlink_message_t * msg, mavlink_mag_cal_report_t * mag_cal_report) inline static
Decode a mag_cal_report message into a struct.
Parameters
msg The message to decode
mag_cal_report C-struct to decode the message contents into
Definition at line 501 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_test_mag_cal_report().
static uint16_t mavlink_msg_mag_cal_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mag_cal_report_t * mag_cal_report) inline static
Encode a mag_cal_report struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mag_cal_report C-struct to read the message contents from
Definition at line 203 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_test_mag_cal_report().
static uint16_t mavlink_msg_mag_cal_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mag_cal_report_t * mag_cal_report) inline static
Encode a mag_cal_report struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mag_cal_report C-struct to read the message contents from
Definition at line 217 of file mavlink_msg_mag_cal_report.h.
static uint8_t mavlink_msg_mag_cal_report_get_autosaved (const mavlink_message_t * msg) inline static
Get field autosaved from mag_cal_report message.
Returns
0=requires a MAV_CMD_DO_ACCEPT_MAG_CAL, 1=saved to parameters
Definition at line 390 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static uint8_t mavlink_msg_mag_cal_report_get_cal_mask (const mavlink_message_t * msg) inline static
Get field cal_mask from mag_cal_report message.
Returns
Bitmask of compasses being calibrated
Definition at line 370 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static uint8_t mavlink_msg_mag_cal_report_get_cal_status (const mavlink_message_t * msg) inline static
Get field cal_status from mag_cal_report message.
Returns
Status (see MAG_CAL_STATUS enum)
Definition at line 380 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static uint8_t mavlink_msg_mag_cal_report_get_compass_id (const mavlink_message_t * msg) inline static
Send a mag_cal_report message.
Parameters
chan MAVLink channel to send the message
compass_id Compass being calibrated
cal_mask Bitmask of compasses being calibrated
cal_status Status (see MAG_CAL_STATUS enum)
autosaved 0=requires a MAV_CMD_DO_ACCEPT_MAG_CAL, 1=saved to parameters
fitness RMS milligauss residuals
ofs_x X offset
ofs_y Y offset
ofs_z Z offset
diag_x X diagonal (matrix 11)
diag_y Y diagonal (matrix 22)
diag_z Z diagonal (matrix 33)
offdiag_x X off-diagonal (matrix 12 and 21)
offdiag_y Y off-diagonal (matrix 13 and 31)
offdiag_z Z off-diagonal (matrix 32 and 23) Get field compass_id from mag_cal_report message
Returns
Compass being calibrated
Definition at line 360 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_diag_x (const mavlink_message_t * msg) inline static
Get field diag_x from mag_cal_report message.
Returns
X diagonal (matrix 11)
Definition at line 440 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_diag_y (const mavlink_message_t * msg) inline static
Get field diag_y from mag_cal_report message.
Returns
Y diagonal (matrix 22)
Definition at line 450 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_diag_z (const mavlink_message_t * msg) inline static
Get field diag_z from mag_cal_report message.
Returns
Z diagonal (matrix 33)
Definition at line 460 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_fitness (const mavlink_message_t * msg) inline static
Get field fitness from mag_cal_report message.
Returns
RMS milligauss residuals
Definition at line 400 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_offdiag_x (const mavlink_message_t * msg) inline static
Get field offdiag_x from mag_cal_report message.
Returns
X off-diagonal (matrix 12 and 21)
Definition at line 470 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_offdiag_y (const mavlink_message_t * msg) inline static
Get field offdiag_y from mag_cal_report message.
Returns
Y off-diagonal (matrix 13 and 31)
Definition at line 480 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_offdiag_z (const mavlink_message_t * msg) inline static
Get field offdiag_z from mag_cal_report message.
Returns
Z off-diagonal (matrix 32 and 23)
Definition at line 490 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_ofs_x (const mavlink_message_t * msg) inline static
Get field ofs_x from mag_cal_report message.
Returns
X offset
Definition at line 410 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_ofs_y (const mavlink_message_t * msg) inline static
Get field ofs_y from mag_cal_report message.
Returns
Y offset
Definition at line 420 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static float mavlink_msg_mag_cal_report_get_ofs_z (const mavlink_message_t * msg) inline static
Get field ofs_z from mag_cal_report message.
Returns
Z offset
Definition at line 430 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_decode().
static uint16_t mavlink_msg_mag_cal_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t autosaved, float fitness, float ofs_x, float ofs_y, float ofs_z, float diag_x, float diag_y, float diag_z, float offdiag_x, float offdiag_y, float offdiag_z) inline static
Pack a mag_cal_report message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
compass_id Compass being calibrated
cal_mask Bitmask of compasses being calibrated
cal_status Status (see MAG_CAL_STATUS enum)
autosaved 0=requires a MAV_CMD_DO_ACCEPT_MAG_CAL, 1=saved to parameters
fitness RMS milligauss residuals
ofs_x X offset
ofs_y Y offset
ofs_z Z offset
diag_x X diagonal (matrix 11)
diag_y Y diagonal (matrix 22)
diag_z Z diagonal (matrix 33)
offdiag_x X off-diagonal (matrix 12 and 21)
offdiag_y Y off-diagonal (matrix 13 and 31)
offdiag_z Z off-diagonal (matrix 32 and 23)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 74 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_encode(), and mavlink_test_mag_cal_report().
static uint16_t mavlink_msg_mag_cal_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t autosaved, float fitness, float ofs_x, float ofs_y, float ofs_z, float diag_x, float diag_y, float diag_z, float offdiag_x, float offdiag_y, float offdiag_z) inline static
Pack a mag_cal_report message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
compass_id Compass being calibrated
cal_mask Bitmask of compasses being calibrated
cal_status Status (see MAG_CAL_STATUS enum)
autosaved 0=requires a MAV_CMD_DO_ACCEPT_MAG_CAL, 1=saved to parameters
fitness RMS milligauss residuals
ofs_x X offset
ofs_y Y offset
ofs_z Z offset
diag_x X diagonal (matrix 11)
diag_y Y diagonal (matrix 22)
diag_z Z diagonal (matrix 33)
offdiag_x X off-diagonal (matrix 12 and 21)
offdiag_y Y off-diagonal (matrix 13 and 31)
offdiag_z Z off-diagonal (matrix 32 and 23)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 145 of file mavlink_msg_mag_cal_report.h.
Referenced by mavlink_msg_mag_cal_report_encode_chan(), and mavlink_test_mag_cal_report().