APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_vision_speed_estimate.h File Reference
mavlink_msg_vision_speed_estimate.h File Reference
Classes
struct __mavlink_vision_speed_estimate_t
Macros
#define MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE 103
#define MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE_LEN 20
#define MAVLINK_MSG_ID_103_LEN 20
#define MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE_CRC 208
#define MAVLINK_MSG_ID_103_CRC 208
#define MAVLINK_MESSAGE_INFO_VISION_SPEED_ESTIMATE
Typedefs
typedef struct __mavlink_vision_speed_estimate_t mavlink_vision_speed_estimate_t
Functions
static uint16_t mavlink_msg_vision_speed_estimate_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t usec, float x, float y, float z)
Pack a vision_speed_estimate message.
static uint16_t mavlink_msg_vision_speed_estimate_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t usec, float x, float y, float z)
Pack a vision_speed_estimate message on a channel.
static uint16_t mavlink_msg_vision_speed_estimate_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_vision_speed_estimate_t *vision_speed_estimate)
Encode a vision_speed_estimate struct.
static uint16_t mavlink_msg_vision_speed_estimate_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_vision_speed_estimate_t *vision_speed_estimate)
Encode a vision_speed_estimate struct on a channel.
static uint64_t mavlink_msg_vision_speed_estimate_get_usec (const mavlink_message_t *msg)
Send a vision_speed_estimate message.
static float mavlink_msg_vision_speed_estimate_get_x (const mavlink_message_t *msg)
Get field x from vision_speed_estimate message.
static float mavlink_msg_vision_speed_estimate_get_y (const mavlink_message_t *msg)
Get field y from vision_speed_estimate message.
static float mavlink_msg_vision_speed_estimate_get_z (const mavlink_message_t *msg)
Get field z from vision_speed_estimate message.
static void mavlink_msg_vision_speed_estimate_decode (const mavlink_message_t *msg, mavlink_vision_speed_estimate_t *vision_speed_estimate)
Decode a vision_speed_estimate message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_VISION_SPEED_ESTIMATE
Value:
{ \
    "VISION_SPEED_ESTIMATE", \
    4, \
    {  { "usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_vision_speed_estimate_t, usec) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_vision_speed_estimate_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_vision_speed_estimate_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_vision_speed_estimate_t, z) }, \
         } \
}
Definition at line 21 of file mavlink_msg_vision_speed_estimate.h.
#define MAVLINK_MSG_ID_103_CRC 208
Definition at line 17 of file mavlink_msg_vision_speed_estimate.h.
#define MAVLINK_MSG_ID_103_LEN 20
Definition at line 14 of file mavlink_msg_vision_speed_estimate.h.
#define MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE 103
Definition at line 3 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_pack(), and mavlink_msg_vision_speed_estimate_pack_chan().
#define MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE_CRC 208
Definition at line 16 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_pack(), and mavlink_msg_vision_speed_estimate_pack_chan().
#define MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE_LEN 20
Definition at line 13 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_decode(), mavlink_msg_vision_speed_estimate_pack(), and mavlink_msg_vision_speed_estimate_pack_chan().
Typedef Documentation
typedef struct __mavlink_vision_speed_estimate_t mavlink_vision_speed_estimate_t
Function Documentation
static void mavlink_msg_vision_speed_estimate_decode (const mavlink_message_t * msg, mavlink_vision_speed_estimate_t * vision_speed_estimate) inline static
Decode a vision_speed_estimate message into a struct.
Parameters
msg The message to decode
vision_speed_estimate C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_test_vision_speed_estimate().
static uint16_t mavlink_msg_vision_speed_estimate_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_vision_speed_estimate_t * vision_speed_estimate) inline static
Encode a vision_speed_estimate struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
vision_speed_estimate C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_test_vision_speed_estimate().
static uint16_t mavlink_msg_vision_speed_estimate_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_vision_speed_estimate_t * vision_speed_estimate) inline static
Encode a vision_speed_estimate struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
vision_speed_estimate C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_vision_speed_estimate.h.
static uint64_t mavlink_msg_vision_speed_estimate_get_usec (const mavlink_message_t * msg) inline static
Send a vision_speed_estimate message.
Parameters
chan MAVLink channel to send the message
usec Timestamp (microseconds, synced to UNIX time or since system boot)
x Global X speed
y Global Y speed
z Global Z speed Get field usec from vision_speed_estimate message
Returns
Timestamp (microseconds, synced to UNIX time or since system boot)
Definition at line 230 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_decode().
static float mavlink_msg_vision_speed_estimate_get_x (const mavlink_message_t * msg) inline static
Get field x from vision_speed_estimate message.
Returns
Global X speed
Definition at line 240 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_decode().
static float mavlink_msg_vision_speed_estimate_get_y (const mavlink_message_t * msg) inline static
Get field y from vision_speed_estimate message.
Returns
Global Y speed
Definition at line 250 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_decode().
static float mavlink_msg_vision_speed_estimate_get_z (const mavlink_message_t * msg) inline static
Get field z from vision_speed_estimate message.
Returns
Global Z speed
Definition at line 260 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_decode().
static uint16_t mavlink_msg_vision_speed_estimate_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t usec, float x, float y, float z) inline static
Pack a vision_speed_estimate message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
usec Timestamp (microseconds, synced to UNIX time or since system boot)
x Global X speed
y Global Y speed
z Global Z speed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_encode(), and mavlink_test_vision_speed_estimate().
static uint16_t mavlink_msg_vision_speed_estimate_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t usec, float x, float y, float z) inline static
Pack a vision_speed_estimate message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
usec Timestamp (microseconds, synced to UNIX time or since system boot)
x Global X speed
y Global Y speed
z Global Z speed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_vision_speed_estimate.h.
Referenced by mavlink_msg_vision_speed_estimate_encode_chan(), and mavlink_test_vision_speed_estimate().