APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_perform_factory_tests.h File Reference
mavlink_msg_gimbal_perform_factory_tests.h File Reference
Classes
struct __mavlink_gimbal_perform_factory_tests_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_PERFORM_FACTORY_TESTS 209
#define MAVLINK_MSG_ID_GIMBAL_PERFORM_FACTORY_TESTS_LEN 2
#define MAVLINK_MSG_ID_209_LEN 2
#define MAVLINK_MSG_ID_GIMBAL_PERFORM_FACTORY_TESTS_CRC 226
#define MAVLINK_MSG_ID_209_CRC 226
#define MAVLINK_MESSAGE_INFO_GIMBAL_PERFORM_FACTORY_TESTS
Typedefs
typedef struct __mavlink_gimbal_perform_factory_tests_t mavlink_gimbal_perform_factory_tests_t
Functions
static uint16_t mavlink_msg_gimbal_perform_factory_tests_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a gimbal_perform_factory_tests message.
static uint16_t mavlink_msg_gimbal_perform_factory_tests_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a gimbal_perform_factory_tests message on a channel.
static uint16_t mavlink_msg_gimbal_perform_factory_tests_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_perform_factory_tests_t *gimbal_perform_factory_tests)
Encode a gimbal_perform_factory_tests struct.
static uint16_t mavlink_msg_gimbal_perform_factory_tests_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_perform_factory_tests_t *gimbal_perform_factory_tests)
Encode a gimbal_perform_factory_tests struct on a channel.
static uint8_t mavlink_msg_gimbal_perform_factory_tests_get_target_system (const mavlink_message_t *msg)
Send a gimbal_perform_factory_tests message.
static uint8_t mavlink_msg_gimbal_perform_factory_tests_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_perform_factory_tests message.
static void mavlink_msg_gimbal_perform_factory_tests_decode (const mavlink_message_t *msg, mavlink_gimbal_perform_factory_tests_t *gimbal_perform_factory_tests)
Decode a gimbal_perform_factory_tests message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_PERFORM_FACTORY_TESTS
Value:
{ \
    "GIMBAL_PERFORM_FACTORY_TESTS", \
    2, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_perform_factory_tests_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gimbal_perform_factory_tests_t, target_component) }, \
         } \
}
Definition at line 19 of file mavlink_msg_gimbal_perform_factory_tests.h.
#define MAVLINK_MSG_ID_209_CRC 226
Definition at line 15 of file mavlink_msg_gimbal_perform_factory_tests.h.
#define MAVLINK_MSG_ID_209_LEN 2
Definition at line 12 of file mavlink_msg_gimbal_perform_factory_tests.h.
#define MAVLINK_MSG_ID_GIMBAL_PERFORM_FACTORY_TESTS 209
Definition at line 3 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_pack(), and mavlink_msg_gimbal_perform_factory_tests_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_PERFORM_FACTORY_TESTS_CRC 226
Definition at line 14 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_pack(), and mavlink_msg_gimbal_perform_factory_tests_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_PERFORM_FACTORY_TESTS_LEN 2
Definition at line 11 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_decode(), mavlink_msg_gimbal_perform_factory_tests_pack(), and mavlink_msg_gimbal_perform_factory_tests_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_perform_factory_tests_t mavlink_gimbal_perform_factory_tests_t
Function Documentation
static void mavlink_msg_gimbal_perform_factory_tests_decode (const mavlink_message_t * msg, mavlink_gimbal_perform_factory_tests_t * gimbal_perform_factory_tests) inline static
Decode a gimbal_perform_factory_tests message into a struct.
Parameters
msg The message to decode
gimbal_perform_factory_tests C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_test_gimbal_perform_factory_tests().
static uint16_t mavlink_msg_gimbal_perform_factory_tests_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_perform_factory_tests_t * gimbal_perform_factory_tests) inline static
Encode a gimbal_perform_factory_tests struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_perform_factory_tests C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_test_gimbal_perform_factory_tests().
static uint16_t mavlink_msg_gimbal_perform_factory_tests_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_perform_factory_tests_t * gimbal_perform_factory_tests) inline static
Encode a gimbal_perform_factory_tests struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_perform_factory_tests C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_gimbal_perform_factory_tests.h.
static uint8_t mavlink_msg_gimbal_perform_factory_tests_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_perform_factory_tests message.
Returns
Component ID
Definition at line 214 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_decode().
static uint8_t mavlink_msg_gimbal_perform_factory_tests_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_perform_factory_tests message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID Get field target_system from gimbal_perform_factory_tests message
Returns
System ID
Definition at line 204 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_decode().
static uint16_t mavlink_msg_gimbal_perform_factory_tests_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a gimbal_perform_factory_tests message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_encode(), and mavlink_test_gimbal_perform_factory_tests().
static uint16_t mavlink_msg_gimbal_perform_factory_tests_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a gimbal_perform_factory_tests message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_gimbal_perform_factory_tests.h.
Referenced by mavlink_msg_gimbal_perform_factory_tests_encode_chan(), and mavlink_test_gimbal_perform_factory_tests().