APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_mount_control.h File Reference
mavlink_msg_mount_control.h File Reference
Classes
struct __mavlink_mount_control_t
Macros
#define MAVLINK_MSG_ID_MOUNT_CONTROL 157
#define MAVLINK_MSG_ID_MOUNT_CONTROL_LEN 15
#define MAVLINK_MSG_ID_157_LEN 15
#define MAVLINK_MSG_ID_MOUNT_CONTROL_CRC 21
#define MAVLINK_MSG_ID_157_CRC 21
#define MAVLINK_MESSAGE_INFO_MOUNT_CONTROL
Typedefs
typedef struct __mavlink_mount_control_t mavlink_mount_control_t
Functions
static uint16_t mavlink_msg_mount_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int32_t input_a, int32_t input_b, int32_t input_c, uint8_t save_position)
Pack a mount_control message.
static uint16_t mavlink_msg_mount_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int32_t input_a, int32_t input_b, int32_t input_c, uint8_t save_position)
Pack a mount_control message on a channel.
static uint16_t mavlink_msg_mount_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mount_control_t *mount_control)
Encode a mount_control struct.
static uint16_t mavlink_msg_mount_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mount_control_t *mount_control)
Encode a mount_control struct on a channel.
static uint8_t mavlink_msg_mount_control_get_target_system (const mavlink_message_t *msg)
Send a mount_control message.
static uint8_t mavlink_msg_mount_control_get_target_component (const mavlink_message_t *msg)
Get field target_component from mount_control message.
static int32_t mavlink_msg_mount_control_get_input_a (const mavlink_message_t *msg)
Get field input_a from mount_control message.
static int32_t mavlink_msg_mount_control_get_input_b (const mavlink_message_t *msg)
Get field input_b from mount_control message.
static int32_t mavlink_msg_mount_control_get_input_c (const mavlink_message_t *msg)
Get field input_c from mount_control message.
static uint8_t mavlink_msg_mount_control_get_save_position (const mavlink_message_t *msg)
Get field save_position from mount_control message.
static void mavlink_msg_mount_control_decode (const mavlink_message_t *msg, mavlink_mount_control_t *mount_control)
Decode a mount_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MOUNT_CONTROL
Value:
{ \
    "MOUNT_CONTROL", \
    6, \
    {  { "input_a", NULL, MAVLINK_TYPE_INT32_T, 0, 0, offsetof(mavlink_mount_control_t, input_a) }, \
         { "input_b", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_mount_control_t, input_b) }, \
         { "input_c", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_mount_control_t, input_c) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 12, offsetof(mavlink_mount_control_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 13, offsetof(mavlink_mount_control_t, target_component) }, \
         { "save_position", NULL, MAVLINK_TYPE_UINT8_T, 0, 14, offsetof(mavlink_mount_control_t, save_position) }, \
         } \
}
Definition at line 23 of file mavlink_msg_mount_control.h.
#define MAVLINK_MSG_ID_157_CRC 21
Definition at line 19 of file mavlink_msg_mount_control.h.
#define MAVLINK_MSG_ID_157_LEN 15
Definition at line 16 of file mavlink_msg_mount_control.h.
#define MAVLINK_MSG_ID_MOUNT_CONTROL 157
Definition at line 3 of file mavlink_msg_mount_control.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_mount_control_pack(), and mavlink_msg_mount_control_pack_chan().
#define MAVLINK_MSG_ID_MOUNT_CONTROL_CRC 21
Definition at line 18 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_pack(), and mavlink_msg_mount_control_pack_chan().
#define MAVLINK_MSG_ID_MOUNT_CONTROL_LEN 15
Definition at line 15 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_decode(), mavlink_msg_mount_control_pack(), and mavlink_msg_mount_control_pack_chan().
Typedef Documentation
typedef struct __mavlink_mount_control_t mavlink_mount_control_t
Function Documentation
static void mavlink_msg_mount_control_decode (const mavlink_message_t * msg, mavlink_mount_control_t * mount_control) inline static
Decode a mount_control message into a struct.
Parameters
msg The message to decode
mount_control C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_mount_control.h.
Referenced by AP_Mount_Backend::control_msg(), and mavlink_test_mount_control().
static uint16_t mavlink_msg_mount_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mount_control_t * mount_control) inline static
Encode a mount_control struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mount_control C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_mount_control.h.
Referenced by mavlink_test_mount_control().
static uint16_t mavlink_msg_mount_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mount_control_t * mount_control) inline static
Encode a mount_control struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mount_control C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_mount_control.h.
static int32_t mavlink_msg_mount_control_get_input_a (const mavlink_message_t * msg) inline static
Get field input_a from mount_control message.
Returns
pitch(deg*100) or lat, depending on mount mode
Definition at line 276 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_decode().
static int32_t mavlink_msg_mount_control_get_input_b (const mavlink_message_t * msg) inline static
Get field input_b from mount_control message.
Returns
roll(deg*100) or lon depending on mount mode
Definition at line 286 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_decode().
static int32_t mavlink_msg_mount_control_get_input_c (const mavlink_message_t * msg) inline static
Get field input_c from mount_control message.
Returns
yaw(deg*100) or alt (in cm) depending on mount mode
Definition at line 296 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_decode().
static uint8_t mavlink_msg_mount_control_get_save_position (const mavlink_message_t * msg) inline static
Get field save_position from mount_control message.
Returns
if "1" it will save current trimmed position on EEPROM (just valid for NEUTRAL and LANDING)
Definition at line 306 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_decode().
static uint8_t mavlink_msg_mount_control_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from mount_control message.
Returns
Component ID
Definition at line 266 of file mavlink_msg_mount_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mount_control_decode().
static uint8_t mavlink_msg_mount_control_get_target_system (const mavlink_message_t * msg) inline static
Send a mount_control message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
input_a pitch(deg*100) or lat, depending on mount mode
input_b roll(deg*100) or lon depending on mount mode
input_c yaw(deg*100) or alt (in cm) depending on mount mode
save_position if "1" it will save current trimmed position on EEPROM (just valid for NEUTRAL and LANDING) Get field target_system from mount_control message
Returns
System ID
Definition at line 256 of file mavlink_msg_mount_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mount_control_decode().
static uint16_t mavlink_msg_mount_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int32_t input_a, int32_t input_b, int32_t input_c, uint8_t save_position) inline static
Pack a mount_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
input_a pitch(deg*100) or lat, depending on mount mode
input_b roll(deg*100) or lon depending on mount mode
input_c yaw(deg*100) or alt (in cm) depending on mount mode
save_position if "1" it will save current trimmed position on EEPROM (just valid for NEUTRAL and LANDING)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_encode(), and mavlink_test_mount_control().
static uint16_t mavlink_msg_mount_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int32_t input_a, int32_t input_b, int32_t input_c, uint8_t save_position) inline static
Pack a mount_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
input_a pitch(deg*100) or lat, depending on mount mode
input_b roll(deg*100) or lon depending on mount mode
input_c yaw(deg*100) or alt (in cm) depending on mount mode
save_position if "1" it will save current trimmed position on EEPROM (just valid for NEUTRAL and LANDING)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_mount_control.h.
Referenced by mavlink_msg_mount_control_encode_chan(), and mavlink_test_mount_control().