APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_report_factory_tests_progress.h File Reference
mavlink_msg_gimbal_report_factory_tests_progress.h File Reference
Classes
struct __mavlink_gimbal_report_factory_tests_progress_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS 210
#define MAVLINK_MSG_ID_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS_LEN 4
#define MAVLINK_MSG_ID_210_LEN 4
#define MAVLINK_MSG_ID_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS_CRC 238
#define MAVLINK_MSG_ID_210_CRC 238
#define MAVLINK_MESSAGE_INFO_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS
Typedefs
typedef struct __mavlink_gimbal_report_factory_tests_progress_t mavlink_gimbal_report_factory_tests_progress_t
Functions
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t test, uint8_t test_section, uint8_t test_section_progress, uint8_t test_status)
Pack a gimbal_report_factory_tests_progress message.
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t test, uint8_t test_section, uint8_t test_section_progress, uint8_t test_status)
Pack a gimbal_report_factory_tests_progress message on a channel.
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_report_factory_tests_progress_t *gimbal_report_factory_tests_progress)
Encode a gimbal_report_factory_tests_progress struct.
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_report_factory_tests_progress_t *gimbal_report_factory_tests_progress)
Encode a gimbal_report_factory_tests_progress struct on a channel.
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test (const mavlink_message_t *msg)
Send a gimbal_report_factory_tests_progress message.
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test_section (const mavlink_message_t *msg)
Get field test_section from gimbal_report_factory_tests_progress message.
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test_section_progress (const mavlink_message_t *msg)
Get field test_section_progress from gimbal_report_factory_tests_progress message.
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test_status (const mavlink_message_t *msg)
Get field test_status from gimbal_report_factory_tests_progress message.
static void mavlink_msg_gimbal_report_factory_tests_progress_decode (const mavlink_message_t *msg, mavlink_gimbal_report_factory_tests_progress_t *gimbal_report_factory_tests_progress)
Decode a gimbal_report_factory_tests_progress message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS
Value:
{ \
    "GIMBAL_REPORT_FACTORY_TESTS_PROGRESS", \
    4, \
    {  { "test", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_report_factory_tests_progress_t, test) }, \
         { "test_section", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gimbal_report_factory_tests_progress_t, test_section) }, \
         { "test_section_progress", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_gimbal_report_factory_tests_progress_t, test_section_progress) }, \
         { "test_status", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_gimbal_report_factory_tests_progress_t, test_status) }, \
         } \
}
Definition at line 21 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
#define MAVLINK_MSG_ID_210_CRC 238
Definition at line 17 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
#define MAVLINK_MSG_ID_210_LEN 4
Definition at line 14 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
#define MAVLINK_MSG_ID_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS 210
Definition at line 3 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_pack(), and mavlink_msg_gimbal_report_factory_tests_progress_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS_CRC 238
Definition at line 16 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_pack(), and mavlink_msg_gimbal_report_factory_tests_progress_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REPORT_FACTORY_TESTS_PROGRESS_LEN 4
Definition at line 13 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_decode(), mavlink_msg_gimbal_report_factory_tests_progress_pack(), and mavlink_msg_gimbal_report_factory_tests_progress_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_report_factory_tests_progress_t mavlink_gimbal_report_factory_tests_progress_t
Function Documentation
static void mavlink_msg_gimbal_report_factory_tests_progress_decode (const mavlink_message_t * msg, mavlink_gimbal_report_factory_tests_progress_t * gimbal_report_factory_tests_progress) inline static
Decode a gimbal_report_factory_tests_progress message into a struct.
Parameters
msg The message to decode
gimbal_report_factory_tests_progress C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_test_gimbal_report_factory_tests_progress().
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_report_factory_tests_progress_t * gimbal_report_factory_tests_progress) inline static
Encode a gimbal_report_factory_tests_progress struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_report_factory_tests_progress C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_test_gimbal_report_factory_tests_progress().
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_report_factory_tests_progress_t * gimbal_report_factory_tests_progress) inline static
Encode a gimbal_report_factory_tests_progress struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_report_factory_tests_progress C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test (const mavlink_message_t * msg) inline static
Send a gimbal_report_factory_tests_progress message.
Parameters
chan MAVLink channel to send the message
test Which factory test is currently running
test_section Which section of the test is currently running. The meaning of this is test-dependent
test_section_progress The progress of the current test section, 0x64=100%
test_status The status of the currently executing test section. The meaning of this is test and section-dependent Get field test from gimbal_report_factory_tests_progress message
Returns
Which factory test is currently running
Definition at line 230 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_decode().
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test_section (const mavlink_message_t * msg) inline static
Get field test_section from gimbal_report_factory_tests_progress message.
Returns
Which section of the test is currently running. The meaning of this is test-dependent
Definition at line 240 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_decode().
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test_section_progress (const mavlink_message_t * msg) inline static
Get field test_section_progress from gimbal_report_factory_tests_progress message.
Returns
The progress of the current test section, 0x64=100%
Definition at line 250 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_decode().
static uint8_t mavlink_msg_gimbal_report_factory_tests_progress_get_test_status (const mavlink_message_t * msg) inline static
Get field test_status from gimbal_report_factory_tests_progress message.
Returns
The status of the currently executing test section. The meaning of this is test and section-dependent
Definition at line 260 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_decode().
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t test, uint8_t test_section, uint8_t test_section_progress, uint8_t test_status) inline static
Pack a gimbal_report_factory_tests_progress message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
test Which factory test is currently running
test_section Which section of the test is currently running. The meaning of this is test-dependent
test_section_progress The progress of the current test section, 0x64=100%
test_status The status of the currently executing test section. The meaning of this is test and section-dependent
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_encode(), and mavlink_test_gimbal_report_factory_tests_progress().
static uint16_t mavlink_msg_gimbal_report_factory_tests_progress_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t test, uint8_t test_section, uint8_t test_section_progress, uint8_t test_status) inline static
Pack a gimbal_report_factory_tests_progress message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
test Which factory test is currently running
test_section Which section of the test is currently running. The meaning of this is test-dependent
test_section_progress The progress of the current test section, 0x64=100%
test_status The status of the currently executing test section. The meaning of this is test and section-dependent
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_gimbal_report_factory_tests_progress.h.
Referenced by mavlink_msg_gimbal_report_factory_tests_progress_encode_chan(), and mavlink_test_gimbal_report_factory_tests_progress().