APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_hwstatus.h File Reference
mavlink_msg_hwstatus.h File Reference
Classes
struct __mavlink_hwstatus_t
Macros
#define MAVLINK_MSG_ID_HWSTATUS 165
#define MAVLINK_MSG_ID_HWSTATUS_LEN 3
#define MAVLINK_MSG_ID_165_LEN 3
#define MAVLINK_MSG_ID_HWSTATUS_CRC 21
#define MAVLINK_MSG_ID_165_CRC 21
#define MAVLINK_MESSAGE_INFO_HWSTATUS
Typedefs
typedef struct __mavlink_hwstatus_t mavlink_hwstatus_t
Functions
static uint16_t mavlink_msg_hwstatus_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t Vcc, uint8_t I2Cerr)
Pack a hwstatus message.
static uint16_t mavlink_msg_hwstatus_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t Vcc, uint8_t I2Cerr)
Pack a hwstatus message on a channel.
static uint16_t mavlink_msg_hwstatus_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_hwstatus_t *hwstatus)
Encode a hwstatus struct.
static uint16_t mavlink_msg_hwstatus_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_hwstatus_t *hwstatus)
Encode a hwstatus struct on a channel.
static uint16_t mavlink_msg_hwstatus_get_Vcc (const mavlink_message_t *msg)
Send a hwstatus message.
static uint8_t mavlink_msg_hwstatus_get_I2Cerr (const mavlink_message_t *msg)
Get field I2Cerr from hwstatus message.
static void mavlink_msg_hwstatus_decode (const mavlink_message_t *msg, mavlink_hwstatus_t *hwstatus)
Decode a hwstatus message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_HWSTATUS
Value:
{ \
    "HWSTATUS", \
    2, \
    {  { "Vcc", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_hwstatus_t, Vcc) }, \
         { "I2Cerr", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_hwstatus_t, I2Cerr) }, \
         } \
}
Definition at line 19 of file mavlink_msg_hwstatus.h.
#define MAVLINK_MSG_ID_165_CRC 21
Definition at line 15 of file mavlink_msg_hwstatus.h.
#define MAVLINK_MSG_ID_165_LEN 3
Definition at line 12 of file mavlink_msg_hwstatus.h.
#define MAVLINK_MSG_ID_HWSTATUS 165
Definition at line 3 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_pack(), and mavlink_msg_hwstatus_pack_chan().
#define MAVLINK_MSG_ID_HWSTATUS_CRC 21
Definition at line 14 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_pack(), and mavlink_msg_hwstatus_pack_chan().
#define MAVLINK_MSG_ID_HWSTATUS_LEN 3
Definition at line 11 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_decode(), mavlink_msg_hwstatus_pack(), and mavlink_msg_hwstatus_pack_chan().
Typedef Documentation
typedef struct __mavlink_hwstatus_t mavlink_hwstatus_t
Function Documentation
static void mavlink_msg_hwstatus_decode (const mavlink_message_t * msg, mavlink_hwstatus_t * hwstatus) inline static
Decode a hwstatus message into a struct.
Parameters
msg The message to decode
hwstatus C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_test_hwstatus().
static uint16_t mavlink_msg_hwstatus_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_hwstatus_t * hwstatus) inline static
Encode a hwstatus struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
hwstatus C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_test_hwstatus().
static uint16_t mavlink_msg_hwstatus_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_hwstatus_t * hwstatus) inline static
Encode a hwstatus struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
hwstatus C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_hwstatus.h.
static uint8_t mavlink_msg_hwstatus_get_I2Cerr (const mavlink_message_t * msg) inline static
Get field I2Cerr from hwstatus message.
Returns
I2C error count
Definition at line 214 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_decode().
static uint16_t mavlink_msg_hwstatus_get_Vcc (const mavlink_message_t * msg) inline static
Send a hwstatus message.
Parameters
chan MAVLink channel to send the message
Vcc board voltage (mV)
I2Cerr I2C error count Get field Vcc from hwstatus message
Returns
board voltage (mV)
Definition at line 204 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_decode().
static uint16_t mavlink_msg_hwstatus_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t Vcc, uint8_t I2Cerr) inline static
Pack a hwstatus message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
Vcc board voltage (mV)
I2Cerr I2C error count
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_encode(), and mavlink_test_hwstatus().
static uint16_t mavlink_msg_hwstatus_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t Vcc, uint8_t I2Cerr) inline static
Pack a hwstatus message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
Vcc board voltage (mV)
I2Cerr I2C error count
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_hwstatus.h.
Referenced by mavlink_msg_hwstatus_encode_chan(), and mavlink_test_hwstatus().