APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_optical_flow.h File Reference
mavlink_msg_optical_flow.h File Reference
Classes
struct __mavlink_optical_flow_t
Macros
#define MAVLINK_MSG_ID_OPTICAL_FLOW 100
#define MAVLINK_MSG_ID_OPTICAL_FLOW_LEN 26
#define MAVLINK_MSG_ID_100_LEN 26
#define MAVLINK_MSG_ID_OPTICAL_FLOW_CRC 175
#define MAVLINK_MSG_ID_100_CRC 175
#define MAVLINK_MESSAGE_INFO_OPTICAL_FLOW
Typedefs
typedef struct __mavlink_optical_flow_t mavlink_optical_flow_t
Functions
static uint16_t mavlink_msg_optical_flow_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t sensor_id, int16_t flow_x, int16_t flow_y, float flow_comp_m_x, float flow_comp_m_y, uint8_t quality, float ground_distance)
Pack a optical_flow message.
static uint16_t mavlink_msg_optical_flow_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t sensor_id, int16_t flow_x, int16_t flow_y, float flow_comp_m_x, float flow_comp_m_y, uint8_t quality, float ground_distance)
Pack a optical_flow message on a channel.
static uint16_t mavlink_msg_optical_flow_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_optical_flow_t *optical_flow)
Encode a optical_flow struct.
static uint16_t mavlink_msg_optical_flow_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_optical_flow_t *optical_flow)
Encode a optical_flow struct on a channel.
static uint64_t mavlink_msg_optical_flow_get_time_usec (const mavlink_message_t *msg)
Send a optical_flow message.
static uint8_t mavlink_msg_optical_flow_get_sensor_id (const mavlink_message_t *msg)
Get field sensor_id from optical_flow message.
static int16_t mavlink_msg_optical_flow_get_flow_x (const mavlink_message_t *msg)
Get field flow_x from optical_flow message.
static int16_t mavlink_msg_optical_flow_get_flow_y (const mavlink_message_t *msg)
Get field flow_y from optical_flow message.
static float mavlink_msg_optical_flow_get_flow_comp_m_x (const mavlink_message_t *msg)
Get field flow_comp_m_x from optical_flow message.
static float mavlink_msg_optical_flow_get_flow_comp_m_y (const mavlink_message_t *msg)
Get field flow_comp_m_y from optical_flow message.
static uint8_t mavlink_msg_optical_flow_get_quality (const mavlink_message_t *msg)
Get field quality from optical_flow message.
static float mavlink_msg_optical_flow_get_ground_distance (const mavlink_message_t *msg)
Get field ground_distance from optical_flow message.
static void mavlink_msg_optical_flow_decode (const mavlink_message_t *msg, mavlink_optical_flow_t *optical_flow)
Decode a optical_flow message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_OPTICAL_FLOW
Value:
{ \
    "OPTICAL_FLOW", \
    8, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_optical_flow_t, time_usec) }, \
         { "flow_comp_m_x", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_optical_flow_t, flow_comp_m_x) }, \
         { "flow_comp_m_y", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_optical_flow_t, flow_comp_m_y) }, \
         { "ground_distance", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_optical_flow_t, ground_distance) }, \
         { "flow_x", NULL, MAVLINK_TYPE_INT16_T, 0, 20, offsetof(mavlink_optical_flow_t, flow_x) }, \
         { "flow_y", NULL, MAVLINK_TYPE_INT16_T, 0, 22, offsetof(mavlink_optical_flow_t, flow_y) }, \
         { "sensor_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 24, offsetof(mavlink_optical_flow_t, sensor_id) }, \
         { "quality", NULL, MAVLINK_TYPE_UINT8_T, 0, 25, offsetof(mavlink_optical_flow_t, quality) }, \
         } \
}
Definition at line 25 of file mavlink_msg_optical_flow.h.
#define MAVLINK_MSG_ID_100_CRC 175
Definition at line 21 of file mavlink_msg_optical_flow.h.
#define MAVLINK_MSG_ID_100_LEN 26
Definition at line 18 of file mavlink_msg_optical_flow.h.
#define MAVLINK_MSG_ID_OPTICAL_FLOW 100
Definition at line 3 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_pack(), and mavlink_msg_optical_flow_pack_chan().
#define MAVLINK_MSG_ID_OPTICAL_FLOW_CRC 175
Definition at line 20 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_pack(), and mavlink_msg_optical_flow_pack_chan().
#define MAVLINK_MSG_ID_OPTICAL_FLOW_LEN 26
Definition at line 17 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode(), mavlink_msg_optical_flow_pack(), and mavlink_msg_optical_flow_pack_chan().
Typedef Documentation
typedef struct __mavlink_optical_flow_t mavlink_optical_flow_t
Function Documentation
static void mavlink_msg_optical_flow_decode (const mavlink_message_t * msg, mavlink_optical_flow_t * optical_flow) inline static
Decode a optical_flow message into a struct.
Parameters
msg The message to decode
optical_flow C-struct to decode the message contents into
Definition at line 363 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_test_optical_flow().
static uint16_t mavlink_msg_optical_flow_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_optical_flow_t * optical_flow) inline static
Encode a optical_flow struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
optical_flow C-struct to read the message contents from
Definition at line 155 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_test_optical_flow().
static uint16_t mavlink_msg_optical_flow_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_optical_flow_t * optical_flow) inline static
Encode a optical_flow struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
optical_flow C-struct to read the message contents from
Definition at line 169 of file mavlink_msg_optical_flow.h.
static float mavlink_msg_optical_flow_get_flow_comp_m_x (const mavlink_message_t * msg) inline static
Get field flow_comp_m_x from optical_flow message.
Returns
Flow in meters in x-sensor direction, angular-speed compensated
Definition at line 322 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static float mavlink_msg_optical_flow_get_flow_comp_m_y (const mavlink_message_t * msg) inline static
Get field flow_comp_m_y from optical_flow message.
Returns
Flow in meters in y-sensor direction, angular-speed compensated
Definition at line 332 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static int16_t mavlink_msg_optical_flow_get_flow_x (const mavlink_message_t * msg) inline static
Get field flow_x from optical_flow message.
Returns
Flow in pixels * 10 in x-sensor direction (dezi-pixels)
Definition at line 302 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static int16_t mavlink_msg_optical_flow_get_flow_y (const mavlink_message_t * msg) inline static
Get field flow_y from optical_flow message.
Returns
Flow in pixels * 10 in y-sensor direction (dezi-pixels)
Definition at line 312 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static float mavlink_msg_optical_flow_get_ground_distance (const mavlink_message_t * msg) inline static
Get field ground_distance from optical_flow message.
Returns
Ground distance in meters. Positive value: distance known. Negative value: Unknown distance
Definition at line 352 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static uint8_t mavlink_msg_optical_flow_get_quality (const mavlink_message_t * msg) inline static
Get field quality from optical_flow message.
Returns
Optical flow quality / confidence. 0: bad, 255: maximum quality
Definition at line 342 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static uint8_t mavlink_msg_optical_flow_get_sensor_id (const mavlink_message_t * msg) inline static
Get field sensor_id from optical_flow message.
Returns
Sensor ID
Definition at line 292 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static uint64_t mavlink_msg_optical_flow_get_time_usec (const mavlink_message_t * msg) inline static
Send a optical_flow message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (UNIX)
sensor_id Sensor ID
flow_x Flow in pixels * 10 in x-sensor direction (dezi-pixels)
flow_y Flow in pixels * 10 in y-sensor direction (dezi-pixels)
flow_comp_m_x Flow in meters in x-sensor direction, angular-speed compensated
flow_comp_m_y Flow in meters in y-sensor direction, angular-speed compensated
quality Optical flow quality / confidence. 0: bad, 255: maximum quality
ground_distance Ground distance in meters. Positive value: distance known. Negative value: Unknown distance Get field time_usec from optical_flow message
Returns
Timestamp (UNIX)
Definition at line 282 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_decode().
static uint16_t mavlink_msg_optical_flow_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t sensor_id, int16_t flow_x, int16_t flow_y, float flow_comp_m_x, float flow_comp_m_y, uint8_t quality, float ground_distance) inline static
Pack a optical_flow message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (UNIX)
sensor_id Sensor ID
flow_x Flow in pixels * 10 in x-sensor direction (dezi-pixels)
flow_y Flow in pixels * 10 in y-sensor direction (dezi-pixels)
flow_comp_m_x Flow in meters in x-sensor direction, angular-speed compensated
flow_comp_m_y Flow in meters in y-sensor direction, angular-speed compensated
quality Optical flow quality / confidence. 0: bad, 255: maximum quality
ground_distance Ground distance in meters. Positive value: distance known. Negative value: Unknown distance
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_encode(), and mavlink_test_optical_flow().
static uint16_t mavlink_msg_optical_flow_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t sensor_id, int16_t flow_x, int16_t flow_y, float flow_comp_m_x, float flow_comp_m_y, uint8_t quality, float ground_distance) inline static
Pack a optical_flow message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (UNIX)
sensor_id Sensor ID
flow_x Flow in pixels * 10 in x-sensor direction (dezi-pixels)
flow_y Flow in pixels * 10 in y-sensor direction (dezi-pixels)
flow_comp_m_x Flow in meters in x-sensor direction, angular-speed compensated
flow_comp_m_y Flow in meters in y-sensor direction, angular-speed compensated
quality Optical flow quality / confidence. 0: bad, 255: maximum quality
ground_distance Ground distance in meters. Positive value: distance known. Negative value: Unknown distance
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 109 of file mavlink_msg_optical_flow.h.
Referenced by mavlink_msg_optical_flow_encode_chan(), and mavlink_test_optical_flow().