APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_debug.h File Reference
mavlink_msg_debug.h File Reference
Classes
struct __mavlink_debug_t
Macros
#define MAVLINK_MSG_ID_DEBUG 254
#define MAVLINK_MSG_ID_DEBUG_LEN 9
#define MAVLINK_MSG_ID_254_LEN 9
#define MAVLINK_MSG_ID_DEBUG_CRC 46
#define MAVLINK_MSG_ID_254_CRC 46
#define MAVLINK_MESSAGE_INFO_DEBUG
Typedefs
typedef struct __mavlink_debug_t mavlink_debug_t
Functions
static uint16_t mavlink_msg_debug_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t ind, float value)
Pack a debug message.
static uint16_t mavlink_msg_debug_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t ind, float value)
Pack a debug message on a channel.
static uint16_t mavlink_msg_debug_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_debug_t *debug)
Encode a debug struct.
static uint16_t mavlink_msg_debug_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_debug_t *debug)
Encode a debug struct on a channel.
static uint32_t mavlink_msg_debug_get_time_boot_ms (const mavlink_message_t *msg)
Send a debug message.
static uint8_t mavlink_msg_debug_get_ind (const mavlink_message_t *msg)
Get field ind from debug message.
static float mavlink_msg_debug_get_value (const mavlink_message_t *msg)
Get field value from debug message.
static void mavlink_msg_debug_decode (const mavlink_message_t *msg, mavlink_debug_t *debug)
Decode a debug message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DEBUG
Value:
{ \
    "DEBUG", \
    3, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_debug_t, time_boot_ms) }, \
         { "value", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_debug_t, value) }, \
         { "ind", NULL, MAVLINK_TYPE_UINT8_T, 0, 8, offsetof(mavlink_debug_t, ind) }, \
         } \
}
Definition at line 20 of file mavlink_msg_debug.h.
#define MAVLINK_MSG_ID_254_CRC 46
Definition at line 16 of file mavlink_msg_debug.h.
#define MAVLINK_MSG_ID_254_LEN 9
Definition at line 13 of file mavlink_msg_debug.h.
#define MAVLINK_MSG_ID_DEBUG 254
Definition at line 3 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_pack(), and mavlink_msg_debug_pack_chan().
#define MAVLINK_MSG_ID_DEBUG_CRC 46
Definition at line 15 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_pack(), and mavlink_msg_debug_pack_chan().
#define MAVLINK_MSG_ID_DEBUG_LEN 9
Definition at line 12 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_decode(), mavlink_msg_debug_pack(), and mavlink_msg_debug_pack_chan().
Typedef Documentation
typedef struct __mavlink_debug_t mavlink_debug_t
Function Documentation
static void mavlink_msg_debug_decode (const mavlink_message_t * msg, mavlink_debug_t * debug) inline static
Decode a debug message into a struct.
Parameters
msg The message to decode
debug C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_debug.h.
Referenced by mavlink_test_debug().
static uint16_t mavlink_msg_debug_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_debug_t * debug) inline static
Encode a debug struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
debug C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_debug.h.
Referenced by mavlink_test_debug().
static uint16_t mavlink_msg_debug_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_debug_t * debug) inline static
Encode a debug struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
debug C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_debug.h.
static uint8_t mavlink_msg_debug_get_ind (const mavlink_message_t * msg) inline static
Get field ind from debug message.
Returns
index of debug variable
Definition at line 227 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_decode().
static uint32_t mavlink_msg_debug_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a debug message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
ind index of debug variable
value DEBUG value Get field time_boot_ms from debug message
Returns
Timestamp (milliseconds since system boot)
Definition at line 217 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_decode().
static float mavlink_msg_debug_get_value (const mavlink_message_t * msg) inline static
Get field value from debug message.
Returns
DEBUG value
Definition at line 237 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_decode().
static uint16_t mavlink_msg_debug_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t ind, float value) inline static
Pack a debug message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
ind index of debug variable
value DEBUG value
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_encode(), and mavlink_test_debug().
static uint16_t mavlink_msg_debug_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t ind, float value) inline static
Pack a debug message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
ind index of debug variable
value DEBUG value
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_debug.h.
Referenced by mavlink_msg_debug_encode_chan(), and mavlink_test_debug().