APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_terrain_check.h File Reference
mavlink_msg_terrain_check.h File Reference
Classes
struct __mavlink_terrain_check_t
Macros
#define MAVLINK_MSG_ID_TERRAIN_CHECK 135
#define MAVLINK_MSG_ID_TERRAIN_CHECK_LEN 8
#define MAVLINK_MSG_ID_135_LEN 8
#define MAVLINK_MSG_ID_TERRAIN_CHECK_CRC 203
#define MAVLINK_MSG_ID_135_CRC 203
#define MAVLINK_MESSAGE_INFO_TERRAIN_CHECK
Typedefs
typedef struct __mavlink_terrain_check_t mavlink_terrain_check_t
Functions
static uint16_t mavlink_msg_terrain_check_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, int32_t lat, int32_t lon)
Pack a terrain_check message.
static uint16_t mavlink_msg_terrain_check_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, int32_t lat, int32_t lon)
Pack a terrain_check message on a channel.
static uint16_t mavlink_msg_terrain_check_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_terrain_check_t *terrain_check)
Encode a terrain_check struct.
static uint16_t mavlink_msg_terrain_check_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_terrain_check_t *terrain_check)
Encode a terrain_check struct on a channel.
static int32_t mavlink_msg_terrain_check_get_lat (const mavlink_message_t *msg)
Send a terrain_check message.
static int32_t mavlink_msg_terrain_check_get_lon (const mavlink_message_t *msg)
Get field lon from terrain_check message.
static void mavlink_msg_terrain_check_decode (const mavlink_message_t *msg, mavlink_terrain_check_t *terrain_check)
Decode a terrain_check message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_TERRAIN_CHECK
Value:
{ \
    "TERRAIN_CHECK", \
    2, \
    {  { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 0, offsetof(mavlink_terrain_check_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_terrain_check_t, lon) }, \
         } \
}
Definition at line 19 of file mavlink_msg_terrain_check.h.
#define MAVLINK_MSG_ID_135_CRC 203
Definition at line 15 of file mavlink_msg_terrain_check.h.
#define MAVLINK_MSG_ID_135_LEN 8
Definition at line 12 of file mavlink_msg_terrain_check.h.
#define MAVLINK_MSG_ID_TERRAIN_CHECK 135
Definition at line 3 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_pack(), and mavlink_msg_terrain_check_pack_chan().
#define MAVLINK_MSG_ID_TERRAIN_CHECK_CRC 203
Definition at line 14 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_pack(), and mavlink_msg_terrain_check_pack_chan().
#define MAVLINK_MSG_ID_TERRAIN_CHECK_LEN 8
Definition at line 11 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_decode(), mavlink_msg_terrain_check_pack(), and mavlink_msg_terrain_check_pack_chan().
Typedef Documentation
typedef struct __mavlink_terrain_check_t mavlink_terrain_check_t
Function Documentation
static void mavlink_msg_terrain_check_decode (const mavlink_message_t * msg, mavlink_terrain_check_t * terrain_check) inline static
Decode a terrain_check message into a struct.
Parameters
msg The message to decode
terrain_check C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_test_terrain_check().
static uint16_t mavlink_msg_terrain_check_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_terrain_check_t * terrain_check) inline static
Encode a terrain_check struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
terrain_check C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_test_terrain_check().
static uint16_t mavlink_msg_terrain_check_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_terrain_check_t * terrain_check) inline static
Encode a terrain_check struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
terrain_check C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_terrain_check.h.
static int32_t mavlink_msg_terrain_check_get_lat (const mavlink_message_t * msg) inline static
Send a terrain_check message.
Parameters
chan MAVLink channel to send the message
lat Latitude (degrees *10^7)
lon Longitude (degrees *10^7) Get field lat from terrain_check message
Returns
Latitude (degrees *10^7)
Definition at line 204 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_decode().
static int32_t mavlink_msg_terrain_check_get_lon (const mavlink_message_t * msg) inline static
Get field lon from terrain_check message.
Returns
Longitude (degrees *10^7)
Definition at line 214 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_decode().
static uint16_t mavlink_msg_terrain_check_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, int32_t lat, int32_t lon) inline static
Pack a terrain_check message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
lat Latitude (degrees *10^7)
lon Longitude (degrees *10^7)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_encode(), and mavlink_test_terrain_check().
static uint16_t mavlink_msg_terrain_check_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, int32_t lat, int32_t lon) inline static
Pack a terrain_check message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
lat Latitude (degrees *10^7)
lon Longitude (degrees *10^7)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_terrain_check.h.
Referenced by mavlink_msg_terrain_check_encode_chan(), and mavlink_test_terrain_check().