APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_mission_set_current.h File Reference
mavlink_msg_mission_set_current.h File Reference
Classes
struct __mavlink_mission_set_current_t
Macros
#define MAVLINK_MSG_ID_MISSION_SET_CURRENT 41
#define MAVLINK_MSG_ID_MISSION_SET_CURRENT_LEN 4
#define MAVLINK_MSG_ID_41_LEN 4
#define MAVLINK_MSG_ID_MISSION_SET_CURRENT_CRC 28
#define MAVLINK_MSG_ID_41_CRC 28
#define MAVLINK_MESSAGE_INFO_MISSION_SET_CURRENT
Typedefs
typedef struct __mavlink_mission_set_current_t mavlink_mission_set_current_t
Functions
static uint16_t mavlink_msg_mission_set_current_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t seq)
Pack a mission_set_current message.
static uint16_t mavlink_msg_mission_set_current_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t seq)
Pack a mission_set_current message on a channel.
static uint16_t mavlink_msg_mission_set_current_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mission_set_current_t *mission_set_current)
Encode a mission_set_current struct.
static uint16_t mavlink_msg_mission_set_current_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mission_set_current_t *mission_set_current)
Encode a mission_set_current struct on a channel.
static uint8_t mavlink_msg_mission_set_current_get_target_system (const mavlink_message_t *msg)
Send a mission_set_current message.
static uint8_t mavlink_msg_mission_set_current_get_target_component (const mavlink_message_t *msg)
Get field target_component from mission_set_current message.
static uint16_t mavlink_msg_mission_set_current_get_seq (const mavlink_message_t *msg)
Get field seq from mission_set_current message.
static void mavlink_msg_mission_set_current_decode (const mavlink_message_t *msg, mavlink_mission_set_current_t *mission_set_current)
Decode a mission_set_current message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MISSION_SET_CURRENT
Value:
{ \
    "MISSION_SET_CURRENT", \
    3, \
    {  { "seq", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_mission_set_current_t, seq) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_mission_set_current_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_mission_set_current_t, target_component) }, \
         } \
}
Definition at line 20 of file mavlink_msg_mission_set_current.h.
#define MAVLINK_MSG_ID_41_CRC 28
Definition at line 16 of file mavlink_msg_mission_set_current.h.
#define MAVLINK_MSG_ID_41_LEN 4
Definition at line 13 of file mavlink_msg_mission_set_current.h.
#define MAVLINK_MSG_ID_MISSION_SET_CURRENT 41
Definition at line 3 of file mavlink_msg_mission_set_current.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_mission_set_current_pack(), and mavlink_msg_mission_set_current_pack_chan().
#define MAVLINK_MSG_ID_MISSION_SET_CURRENT_CRC 28
Definition at line 15 of file mavlink_msg_mission_set_current.h.
Referenced by mavlink_msg_mission_set_current_pack(), and mavlink_msg_mission_set_current_pack_chan().
#define MAVLINK_MSG_ID_MISSION_SET_CURRENT_LEN 4
Definition at line 12 of file mavlink_msg_mission_set_current.h.
Referenced by mavlink_msg_mission_set_current_decode(), mavlink_msg_mission_set_current_pack(), and mavlink_msg_mission_set_current_pack_chan().
Typedef Documentation
typedef struct __mavlink_mission_set_current_t mavlink_mission_set_current_t
Function Documentation
static void mavlink_msg_mission_set_current_decode (const mavlink_message_t * msg, mavlink_mission_set_current_t * mission_set_current) inline static
Decode a mission_set_current message into a struct.
Parameters
msg The message to decode
mission_set_current C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_mission_set_current.h.
Referenced by GCS_MAVLINK::handle_mission_set_current(), and mavlink_test_mission_set_current().
static uint16_t mavlink_msg_mission_set_current_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mission_set_current_t * mission_set_current) inline static
Encode a mission_set_current struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mission_set_current C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_mission_set_current.h.
Referenced by mavlink_test_mission_set_current().
static uint16_t mavlink_msg_mission_set_current_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mission_set_current_t * mission_set_current) inline static
Encode a mission_set_current struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mission_set_current C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_mission_set_current.h.
static uint16_t mavlink_msg_mission_set_current_get_seq (const mavlink_message_t * msg) inline static
Get field seq from mission_set_current message.
Returns
Sequence
Definition at line 237 of file mavlink_msg_mission_set_current.h.
Referenced by mavlink_msg_mission_set_current_decode().
static uint8_t mavlink_msg_mission_set_current_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from mission_set_current message.
Returns
Component ID
Definition at line 227 of file mavlink_msg_mission_set_current.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_set_current_decode().
static uint8_t mavlink_msg_mission_set_current_get_target_system (const mavlink_message_t * msg) inline static
Send a mission_set_current message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
seq Sequence Get field target_system from mission_set_current message
Returns
System ID
Definition at line 217 of file mavlink_msg_mission_set_current.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_set_current_decode().
static uint16_t mavlink_msg_mission_set_current_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t seq) inline static
Pack a mission_set_current message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_mission_set_current.h.
Referenced by mavlink_msg_mission_set_current_encode(), and mavlink_test_mission_set_current().
static uint16_t mavlink_msg_mission_set_current_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t seq) inline static
Pack a mission_set_current message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_mission_set_current.h.
Referenced by mavlink_msg_mission_set_current_encode_chan(), and mavlink_test_mission_set_current().