APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_local_position_ned_system_global_offset.h File Reference
mavlink_msg_local_position_ned_system_global_offset.h File Reference
Classes
struct __mavlink_local_position_ned_system_global_offset_t
Macros
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET 89
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET_LEN 28
#define MAVLINK_MSG_ID_89_LEN 28
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET_CRC 231
#define MAVLINK_MSG_ID_89_CRC 231
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET
Typedefs
typedef struct __mavlink_local_position_ned_system_global_offset_t mavlink_local_position_ned_system_global_offset_t
Functions
static uint16_t mavlink_msg_local_position_ned_system_global_offset_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, float x, float y, float z, float roll, float pitch, float yaw)
Pack a local_position_ned_system_global_offset message.
static uint16_t mavlink_msg_local_position_ned_system_global_offset_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, float x, float y, float z, float roll, float pitch, float yaw)
Pack a local_position_ned_system_global_offset message on a channel.
static uint16_t mavlink_msg_local_position_ned_system_global_offset_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_local_position_ned_system_global_offset_t *local_position_ned_system_global_offset)
Encode a local_position_ned_system_global_offset struct.
static uint16_t mavlink_msg_local_position_ned_system_global_offset_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_local_position_ned_system_global_offset_t *local_position_ned_system_global_offset)
Encode a local_position_ned_system_global_offset struct on a channel.
static uint32_t mavlink_msg_local_position_ned_system_global_offset_get_time_boot_ms (const mavlink_message_t *msg)
Send a local_position_ned_system_global_offset message.
static float mavlink_msg_local_position_ned_system_global_offset_get_x (const mavlink_message_t *msg)
Get field x from local_position_ned_system_global_offset message.
static float mavlink_msg_local_position_ned_system_global_offset_get_y (const mavlink_message_t *msg)
Get field y from local_position_ned_system_global_offset message.
static float mavlink_msg_local_position_ned_system_global_offset_get_z (const mavlink_message_t *msg)
Get field z from local_position_ned_system_global_offset message.
static float mavlink_msg_local_position_ned_system_global_offset_get_roll (const mavlink_message_t *msg)
Get field roll from local_position_ned_system_global_offset message.
static float mavlink_msg_local_position_ned_system_global_offset_get_pitch (const mavlink_message_t *msg)
Get field pitch from local_position_ned_system_global_offset message.
static float mavlink_msg_local_position_ned_system_global_offset_get_yaw (const mavlink_message_t *msg)
Get field yaw from local_position_ned_system_global_offset message.
static void mavlink_msg_local_position_ned_system_global_offset_decode (const mavlink_message_t *msg, mavlink_local_position_ned_system_global_offset_t *local_position_ned_system_global_offset)
Decode a local_position_ned_system_global_offset message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET
Value:
{ \
    "LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET", \
    7, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_local_position_ned_system_global_offset_t, time_boot_ms) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_local_position_ned_system_global_offset_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_local_position_ned_system_global_offset_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_local_position_ned_system_global_offset_t, z) }, \
         { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_local_position_ned_system_global_offset_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_local_position_ned_system_global_offset_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_local_position_ned_system_global_offset_t, yaw) }, \
         } \
}
Definition at line 24 of file mavlink_msg_local_position_ned_system_global_offset.h.
#define MAVLINK_MSG_ID_89_CRC 231
Definition at line 20 of file mavlink_msg_local_position_ned_system_global_offset.h.
#define MAVLINK_MSG_ID_89_LEN 28
Definition at line 17 of file mavlink_msg_local_position_ned_system_global_offset.h.
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET 89
Definition at line 3 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_pack(), and mavlink_msg_local_position_ned_system_global_offset_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET_CRC 231
Definition at line 19 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_pack(), and mavlink_msg_local_position_ned_system_global_offset_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET_LEN 28
Definition at line 16 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode(), mavlink_msg_local_position_ned_system_global_offset_pack(), and mavlink_msg_local_position_ned_system_global_offset_pack_chan().
Typedef Documentation
typedef struct __mavlink_local_position_ned_system_global_offset_t mavlink_local_position_ned_system_global_offset_t
Function Documentation
static void mavlink_msg_local_position_ned_system_global_offset_decode (const mavlink_message_t * msg, mavlink_local_position_ned_system_global_offset_t * local_position_ned_system_global_offset) inline static
Decode a local_position_ned_system_global_offset message into a struct.
Parameters
msg The message to decode
local_position_ned_system_global_offset C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_test_local_position_ned_system_global_offset().
static uint16_t mavlink_msg_local_position_ned_system_global_offset_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_local_position_ned_system_global_offset_t * local_position_ned_system_global_offset) inline static
Encode a local_position_ned_system_global_offset struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
local_position_ned_system_global_offset C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_test_local_position_ned_system_global_offset().
static uint16_t mavlink_msg_local_position_ned_system_global_offset_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_local_position_ned_system_global_offset_t * local_position_ned_system_global_offset) inline static
Encode a local_position_ned_system_global_offset struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
local_position_ned_system_global_offset C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_local_position_ned_system_global_offset.h.
static float mavlink_msg_local_position_ned_system_global_offset_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from local_position_ned_system_global_offset message.
Returns
Pitch
Definition at line 319 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static float mavlink_msg_local_position_ned_system_global_offset_get_roll (const mavlink_message_t * msg) inline static
Get field roll from local_position_ned_system_global_offset message.
Returns
Roll
Definition at line 309 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static uint32_t mavlink_msg_local_position_ned_system_global_offset_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a local_position_ned_system_global_offset message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
x X Position
y Y Position
z Z Position
roll Roll
pitch Pitch
yaw Yaw Get field time_boot_ms from local_position_ned_system_global_offset message
Returns
Timestamp (milliseconds since system boot)
Definition at line 269 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static float mavlink_msg_local_position_ned_system_global_offset_get_x (const mavlink_message_t * msg) inline static
Get field x from local_position_ned_system_global_offset message.
Returns
X Position
Definition at line 279 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static float mavlink_msg_local_position_ned_system_global_offset_get_y (const mavlink_message_t * msg) inline static
Get field y from local_position_ned_system_global_offset message.
Returns
Y Position
Definition at line 289 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static float mavlink_msg_local_position_ned_system_global_offset_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from local_position_ned_system_global_offset message.
Returns
Yaw
Definition at line 329 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static float mavlink_msg_local_position_ned_system_global_offset_get_z (const mavlink_message_t * msg) inline static
Get field z from local_position_ned_system_global_offset message.
Returns
Z Position
Definition at line 299 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_decode().
static uint16_t mavlink_msg_local_position_ned_system_global_offset_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, float x, float y, float z, float roll, float pitch, float yaw) inline static
Pack a local_position_ned_system_global_offset message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
x X Position
y Y Position
z Z Position
roll Roll
pitch Pitch
yaw Yaw
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_encode(), and mavlink_test_local_position_ned_system_global_offset().
static uint16_t mavlink_msg_local_position_ned_system_global_offset_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, float x, float y, float z, float roll, float pitch, float yaw) inline static
Pack a local_position_ned_system_global_offset message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
x X Position
y Y Position
z Z Position
roll Roll
pitch Pitch
yaw Yaw
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_local_position_ned_system_global_offset.h.
Referenced by mavlink_msg_local_position_ned_system_global_offset_encode_chan(), and mavlink_test_local_position_ned_system_global_offset().