APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_fence_point.h File Reference
mavlink_msg_fence_point.h File Reference
Classes
struct __mavlink_fence_point_t
Macros
#define MAVLINK_MSG_ID_FENCE_POINT 160
#define MAVLINK_MSG_ID_FENCE_POINT_LEN 12
#define MAVLINK_MSG_ID_160_LEN 12
#define MAVLINK_MSG_ID_FENCE_POINT_CRC 78
#define MAVLINK_MSG_ID_160_CRC 78
#define MAVLINK_MESSAGE_INFO_FENCE_POINT
Typedefs
typedef struct __mavlink_fence_point_t mavlink_fence_point_t
Functions
static uint16_t mavlink_msg_fence_point_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, float lat, float lng)
Pack a fence_point message.
static uint16_t mavlink_msg_fence_point_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, float lat, float lng)
Pack a fence_point message on a channel.
static uint16_t mavlink_msg_fence_point_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_fence_point_t *fence_point)
Encode a fence_point struct.
static uint16_t mavlink_msg_fence_point_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_fence_point_t *fence_point)
Encode a fence_point struct on a channel.
static uint8_t mavlink_msg_fence_point_get_target_system (const mavlink_message_t *msg)
Send a fence_point message.
static uint8_t mavlink_msg_fence_point_get_target_component (const mavlink_message_t *msg)
Get field target_component from fence_point message.
static uint8_t mavlink_msg_fence_point_get_idx (const mavlink_message_t *msg)
Get field idx from fence_point message.
static uint8_t mavlink_msg_fence_point_get_count (const mavlink_message_t *msg)
Get field count from fence_point message.
static float mavlink_msg_fence_point_get_lat (const mavlink_message_t *msg)
Get field lat from fence_point message.
static float mavlink_msg_fence_point_get_lng (const mavlink_message_t *msg)
Get field lng from fence_point message.
static void mavlink_msg_fence_point_decode (const mavlink_message_t *msg, mavlink_fence_point_t *fence_point)
Decode a fence_point message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_FENCE_POINT
Value:
{ \
    "FENCE_POINT", \
    6, \
    {  { "lat", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_fence_point_t, lat) }, \
         { "lng", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_fence_point_t, lng) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 8, offsetof(mavlink_fence_point_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 9, offsetof(mavlink_fence_point_t, target_component) }, \
         { "idx", NULL, MAVLINK_TYPE_UINT8_T, 0, 10, offsetof(mavlink_fence_point_t, idx) }, \
         { "count", NULL, MAVLINK_TYPE_UINT8_T, 0, 11, offsetof(mavlink_fence_point_t, count) }, \
         } \
}
Definition at line 23 of file mavlink_msg_fence_point.h.
#define MAVLINK_MSG_ID_160_CRC 78
Definition at line 19 of file mavlink_msg_fence_point.h.
#define MAVLINK_MSG_ID_160_LEN 12
Definition at line 16 of file mavlink_msg_fence_point.h.
#define MAVLINK_MSG_ID_FENCE_POINT 160
Definition at line 3 of file mavlink_msg_fence_point.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_fence_point_pack(), and mavlink_msg_fence_point_pack_chan().
#define MAVLINK_MSG_ID_FENCE_POINT_CRC 78
Definition at line 18 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_pack(), and mavlink_msg_fence_point_pack_chan().
#define MAVLINK_MSG_ID_FENCE_POINT_LEN 12
Definition at line 15 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_decode(), mavlink_msg_fence_point_pack(), and mavlink_msg_fence_point_pack_chan().
Typedef Documentation
typedef struct __mavlink_fence_point_t mavlink_fence_point_t
Function Documentation
static void mavlink_msg_fence_point_decode (const mavlink_message_t * msg, mavlink_fence_point_t * fence_point) inline static
Decode a fence_point message into a struct.
Parameters
msg The message to decode
fence_point C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_fence_point.h.
Referenced by mavlink_test_fence_point().
static uint16_t mavlink_msg_fence_point_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_fence_point_t * fence_point) inline static
Encode a fence_point struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
fence_point C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_fence_point.h.
Referenced by mavlink_test_fence_point().
static uint16_t mavlink_msg_fence_point_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_fence_point_t * fence_point) inline static
Encode a fence_point struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
fence_point C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_fence_point.h.
static uint8_t mavlink_msg_fence_point_get_count (const mavlink_message_t * msg) inline static
Get field count from fence_point message.
Returns
total number of points (for sanity checking)
Definition at line 286 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_decode().
static uint8_t mavlink_msg_fence_point_get_idx (const mavlink_message_t * msg) inline static
Get field idx from fence_point message.
Returns
point index (first point is 1, 0 is for return point)
Definition at line 276 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_decode().
static float mavlink_msg_fence_point_get_lat (const mavlink_message_t * msg) inline static
Get field lat from fence_point message.
Returns
Latitude of point
Definition at line 296 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_decode().
static float mavlink_msg_fence_point_get_lng (const mavlink_message_t * msg) inline static
Get field lng from fence_point message.
Returns
Longitude of point
Definition at line 306 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_decode().
static uint8_t mavlink_msg_fence_point_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from fence_point message.
Returns
Component ID
Definition at line 266 of file mavlink_msg_fence_point.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_fence_point_decode().
static uint8_t mavlink_msg_fence_point_get_target_system (const mavlink_message_t * msg) inline static
Send a fence_point message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
idx point index (first point is 1, 0 is for return point)
count total number of points (for sanity checking)
lat Latitude of point
lng Longitude of point Get field target_system from fence_point message
Returns
System ID
Definition at line 256 of file mavlink_msg_fence_point.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_fence_point_decode().
static uint16_t mavlink_msg_fence_point_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, float lat, float lng) inline static
Pack a fence_point message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
idx point index (first point is 1, 0 is for return point)
count total number of points (for sanity checking)
lat Latitude of point
lng Longitude of point
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_encode(), and mavlink_test_fence_point().
static uint16_t mavlink_msg_fence_point_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, float lat, float lng) inline static
Pack a fence_point message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
idx point index (first point is 1, 0 is for return point)
count total number of points (for sanity checking)
lat Latitude of point
lng Longitude of point
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_fence_point.h.
Referenced by mavlink_msg_fence_point_encode_chan(), and mavlink_test_fence_point().