APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_hil_gps.h File Reference
mavlink_msg_hil_gps.h File Reference
Classes
struct __mavlink_hil_gps_t
Macros
#define MAVLINK_MSG_ID_HIL_GPS 113
#define MAVLINK_MSG_ID_HIL_GPS_LEN 36
#define MAVLINK_MSG_ID_113_LEN 36
#define MAVLINK_MSG_ID_HIL_GPS_CRC 124
#define MAVLINK_MSG_ID_113_CRC 124
#define MAVLINK_MESSAGE_INFO_HIL_GPS
Typedefs
typedef struct __mavlink_hil_gps_t mavlink_hil_gps_t
Functions
static uint16_t mavlink_msg_hil_gps_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, uint16_t eph, uint16_t epv, uint16_t vel, int16_t vn, int16_t ve, int16_t vd, uint16_t cog, uint8_t satellites_visible)
Pack a hil_gps message.
static uint16_t mavlink_msg_hil_gps_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, uint16_t eph, uint16_t epv, uint16_t vel, int16_t vn, int16_t ve, int16_t vd, uint16_t cog, uint8_t satellites_visible)
Pack a hil_gps message on a channel.
static uint16_t mavlink_msg_hil_gps_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_hil_gps_t *hil_gps)
Encode a hil_gps struct.
static uint16_t mavlink_msg_hil_gps_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_hil_gps_t *hil_gps)
Encode a hil_gps struct on a channel.
static uint64_t mavlink_msg_hil_gps_get_time_usec (const mavlink_message_t *msg)
Send a hil_gps message.
static uint8_t mavlink_msg_hil_gps_get_fix_type (const mavlink_message_t *msg)
Get field fix_type from hil_gps message.
static int32_t mavlink_msg_hil_gps_get_lat (const mavlink_message_t *msg)
Get field lat from hil_gps message.
static int32_t mavlink_msg_hil_gps_get_lon (const mavlink_message_t *msg)
Get field lon from hil_gps message.
static int32_t mavlink_msg_hil_gps_get_alt (const mavlink_message_t *msg)
Get field alt from hil_gps message.
static uint16_t mavlink_msg_hil_gps_get_eph (const mavlink_message_t *msg)
Get field eph from hil_gps message.
static uint16_t mavlink_msg_hil_gps_get_epv (const mavlink_message_t *msg)
Get field epv from hil_gps message.
static uint16_t mavlink_msg_hil_gps_get_vel (const mavlink_message_t *msg)
Get field vel from hil_gps message.
static int16_t mavlink_msg_hil_gps_get_vn (const mavlink_message_t *msg)
Get field vn from hil_gps message.
static int16_t mavlink_msg_hil_gps_get_ve (const mavlink_message_t *msg)
Get field ve from hil_gps message.
static int16_t mavlink_msg_hil_gps_get_vd (const mavlink_message_t *msg)
Get field vd from hil_gps message.
static uint16_t mavlink_msg_hil_gps_get_cog (const mavlink_message_t *msg)
Get field cog from hil_gps message.
static uint8_t mavlink_msg_hil_gps_get_satellites_visible (const mavlink_message_t *msg)
Get field satellites_visible from hil_gps message.
static void mavlink_msg_hil_gps_decode (const mavlink_message_t *msg, mavlink_hil_gps_t *hil_gps)
Decode a hil_gps message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_HIL_GPS
Value:
{ \
    "HIL_GPS", \
    13, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_hil_gps_t, time_usec) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_hil_gps_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 12, offsetof(mavlink_hil_gps_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_INT32_T, 0, 16, offsetof(mavlink_hil_gps_t, alt) }, \
         { "eph", NULL, MAVLINK_TYPE_UINT16_T, 0, 20, offsetof(mavlink_hil_gps_t, eph) }, \
         { "epv", NULL, MAVLINK_TYPE_UINT16_T, 0, 22, offsetof(mavlink_hil_gps_t, epv) }, \
         { "vel", NULL, MAVLINK_TYPE_UINT16_T, 0, 24, offsetof(mavlink_hil_gps_t, vel) }, \
         { "vn", NULL, MAVLINK_TYPE_INT16_T, 0, 26, offsetof(mavlink_hil_gps_t, vn) }, \
         { "ve", NULL, MAVLINK_TYPE_INT16_T, 0, 28, offsetof(mavlink_hil_gps_t, ve) }, \
         { "vd", NULL, MAVLINK_TYPE_INT16_T, 0, 30, offsetof(mavlink_hil_gps_t, vd) }, \
         { "cog", NULL, MAVLINK_TYPE_UINT16_T, 0, 32, offsetof(mavlink_hil_gps_t, cog) }, \
         { "fix_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 34, offsetof(mavlink_hil_gps_t, fix_type) }, \
         { "satellites_visible", NULL, MAVLINK_TYPE_UINT8_T, 0, 35, offsetof(mavlink_hil_gps_t, satellites_visible) }, \
         } \
}
Definition at line 30 of file mavlink_msg_hil_gps.h.
#define MAVLINK_MSG_ID_113_CRC 124
Definition at line 26 of file mavlink_msg_hil_gps.h.
#define MAVLINK_MSG_ID_113_LEN 36
Definition at line 23 of file mavlink_msg_hil_gps.h.
#define MAVLINK_MSG_ID_HIL_GPS 113
Definition at line 3 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_pack(), and mavlink_msg_hil_gps_pack_chan().
#define MAVLINK_MSG_ID_HIL_GPS_CRC 124
Definition at line 25 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_pack(), and mavlink_msg_hil_gps_pack_chan().
#define MAVLINK_MSG_ID_HIL_GPS_LEN 36
Definition at line 22 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode(), mavlink_msg_hil_gps_pack(), and mavlink_msg_hil_gps_pack_chan().
Typedef Documentation
typedef struct __mavlink_hil_gps_t mavlink_hil_gps_t
Function Documentation
static void mavlink_msg_hil_gps_decode (const mavlink_message_t * msg, mavlink_hil_gps_t * hil_gps) inline static
Decode a hil_gps message into a struct.
Parameters
msg The message to decode
hil_gps C-struct to decode the message contents into
Definition at line 478 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_test_hil_gps().
static uint16_t mavlink_msg_hil_gps_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_hil_gps_t * hil_gps) inline static
Encode a hil_gps struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
hil_gps C-struct to read the message contents from
Definition at line 195 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_test_hil_gps().
static uint16_t mavlink_msg_hil_gps_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_hil_gps_t * hil_gps) inline static
Encode a hil_gps struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
hil_gps C-struct to read the message contents from
Definition at line 209 of file mavlink_msg_hil_gps.h.
static int32_t mavlink_msg_hil_gps_get_alt (const mavlink_message_t * msg) inline static
Get field alt from hil_gps message.
Returns
Altitude (AMSL, not WGS84), in meters * 1000 (positive for up)
Definition at line 387 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint16_t mavlink_msg_hil_gps_get_cog (const mavlink_message_t * msg) inline static
Get field cog from hil_gps message.
Returns
Course over ground (NOT heading, but direction of movement) in degrees * 100, 0.0..359.99 degrees. If unknown, set to: 65535
Definition at line 457 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint16_t mavlink_msg_hil_gps_get_eph (const mavlink_message_t * msg) inline static
Get field eph from hil_gps message.
Returns
GPS HDOP horizontal dilution of position in cm (m*100). If unknown, set to: 65535
Definition at line 397 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint16_t mavlink_msg_hil_gps_get_epv (const mavlink_message_t * msg) inline static
Get field epv from hil_gps message.
Returns
GPS VDOP vertical dilution of position in cm (m*100). If unknown, set to: 65535
Definition at line 407 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint8_t mavlink_msg_hil_gps_get_fix_type (const mavlink_message_t * msg) inline static
Get field fix_type from hil_gps message.
Returns
0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
Definition at line 357 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static int32_t mavlink_msg_hil_gps_get_lat (const mavlink_message_t * msg) inline static
Get field lat from hil_gps message.
Returns
Latitude (WGS84), in degrees * 1E7
Definition at line 367 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static int32_t mavlink_msg_hil_gps_get_lon (const mavlink_message_t * msg) inline static
Get field lon from hil_gps message.
Returns
Longitude (WGS84), in degrees * 1E7
Definition at line 377 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint8_t mavlink_msg_hil_gps_get_satellites_visible (const mavlink_message_t * msg) inline static
Get field satellites_visible from hil_gps message.
Returns
Number of satellites visible. If unknown, set to 255
Definition at line 467 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint64_t mavlink_msg_hil_gps_get_time_usec (const mavlink_message_t * msg) inline static
Send a hil_gps message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
fix_type 0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
lat Latitude (WGS84), in degrees * 1E7
lon Longitude (WGS84), in degrees * 1E7
alt Altitude (AMSL, not WGS84), in meters * 1000 (positive for up)
eph GPS HDOP horizontal dilution of position in cm (m*100). If unknown, set to: 65535
epv GPS VDOP vertical dilution of position in cm (m*100). If unknown, set to: 65535
vel GPS ground speed (m/s * 100). If unknown, set to: 65535
vn GPS velocity in cm/s in NORTH direction in earth-fixed NED frame
ve GPS velocity in cm/s in EAST direction in earth-fixed NED frame
vd GPS velocity in cm/s in DOWN direction in earth-fixed NED frame
cog Course over ground (NOT heading, but direction of movement) in degrees * 100, 0.0..359.99 degrees. If unknown, set to: 65535
satellites_visible Number of satellites visible. If unknown, set to 255 Get field time_usec from hil_gps message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 347 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static int16_t mavlink_msg_hil_gps_get_vd (const mavlink_message_t * msg) inline static
Get field vd from hil_gps message.
Returns
GPS velocity in cm/s in DOWN direction in earth-fixed NED frame
Definition at line 447 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static int16_t mavlink_msg_hil_gps_get_ve (const mavlink_message_t * msg) inline static
Get field ve from hil_gps message.
Returns
GPS velocity in cm/s in EAST direction in earth-fixed NED frame
Definition at line 437 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint16_t mavlink_msg_hil_gps_get_vel (const mavlink_message_t * msg) inline static
Get field vel from hil_gps message.
Returns
GPS ground speed (m/s * 100). If unknown, set to: 65535
Definition at line 417 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static int16_t mavlink_msg_hil_gps_get_vn (const mavlink_message_t * msg) inline static
Get field vn from hil_gps message.
Returns
GPS velocity in cm/s in NORTH direction in earth-fixed NED frame
Definition at line 427 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_decode().
static uint16_t mavlink_msg_hil_gps_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, uint16_t eph, uint16_t epv, uint16_t vel, int16_t vn, int16_t ve, int16_t vd, uint16_t cog, uint8_t satellites_visible) inline static
Pack a hil_gps message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
fix_type 0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
lat Latitude (WGS84), in degrees * 1E7
lon Longitude (WGS84), in degrees * 1E7
alt Altitude (AMSL, not WGS84), in meters * 1000 (positive for up)
eph GPS HDOP horizontal dilution of position in cm (m*100). If unknown, set to: 65535
epv GPS VDOP vertical dilution of position in cm (m*100). If unknown, set to: 65535
vel GPS ground speed (m/s * 100). If unknown, set to: 65535
vn GPS velocity in cm/s in NORTH direction in earth-fixed NED frame
ve GPS velocity in cm/s in EAST direction in earth-fixed NED frame
vd GPS velocity in cm/s in DOWN direction in earth-fixed NED frame
cog Course over ground (NOT heading, but direction of movement) in degrees * 100, 0.0..359.99 degrees. If unknown, set to: 65535
satellites_visible Number of satellites visible. If unknown, set to 255
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 71 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_encode(), and mavlink_test_hil_gps().
static uint16_t mavlink_msg_hil_gps_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, uint16_t eph, uint16_t epv, uint16_t vel, int16_t vn, int16_t ve, int16_t vd, uint16_t cog, uint8_t satellites_visible) inline static
Pack a hil_gps message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
fix_type 0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
lat Latitude (WGS84), in degrees * 1E7
lon Longitude (WGS84), in degrees * 1E7
alt Altitude (AMSL, not WGS84), in meters * 1000 (positive for up)
eph GPS HDOP horizontal dilution of position in cm (m*100). If unknown, set to: 65535
epv GPS VDOP vertical dilution of position in cm (m*100). If unknown, set to: 65535
vel GPS ground speed (m/s * 100). If unknown, set to: 65535
vn GPS velocity in cm/s in NORTH direction in earth-fixed NED frame
ve GPS velocity in cm/s in EAST direction in earth-fixed NED frame
vd GPS velocity in cm/s in DOWN direction in earth-fixed NED frame
cog Course over ground (NOT heading, but direction of movement) in degrees * 100, 0.0..359.99 degrees. If unknown, set to: 65535
satellites_visible Number of satellites visible. If unknown, set to 255
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 139 of file mavlink_msg_hil_gps.h.
Referenced by mavlink_msg_hil_gps_encode_chan(), and mavlink_test_hil_gps().