APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_rc_channels_raw.h File Reference
mavlink_msg_rc_channels_raw.h File Reference
Classes
struct __mavlink_rc_channels_raw_t
Macros
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW 35
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW_LEN 22
#define MAVLINK_MSG_ID_35_LEN 22
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW_CRC 244
#define MAVLINK_MSG_ID_35_CRC 244
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS_RAW
Typedefs
typedef struct __mavlink_rc_channels_raw_t mavlink_rc_channels_raw_t
Functions
static uint16_t mavlink_msg_rc_channels_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t port, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi)
Pack a rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t port, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi)
Pack a rc_channels_raw message on a channel.
static uint16_t mavlink_msg_rc_channels_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rc_channels_raw_t *rc_channels_raw)
Encode a rc_channels_raw struct.
static uint16_t mavlink_msg_rc_channels_raw_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_rc_channels_raw_t *rc_channels_raw)
Encode a rc_channels_raw struct on a channel.
static uint32_t mavlink_msg_rc_channels_raw_get_time_boot_ms (const mavlink_message_t *msg)
Send a rc_channels_raw message.
static uint8_t mavlink_msg_rc_channels_raw_get_port (const mavlink_message_t *msg)
Get field port from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan1_raw (const mavlink_message_t *msg)
Get field chan1_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan2_raw (const mavlink_message_t *msg)
Get field chan2_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan3_raw (const mavlink_message_t *msg)
Get field chan3_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan4_raw (const mavlink_message_t *msg)
Get field chan4_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan5_raw (const mavlink_message_t *msg)
Get field chan5_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan6_raw (const mavlink_message_t *msg)
Get field chan6_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan7_raw (const mavlink_message_t *msg)
Get field chan7_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan8_raw (const mavlink_message_t *msg)
Get field chan8_raw from rc_channels_raw message.
static uint8_t mavlink_msg_rc_channels_raw_get_rssi (const mavlink_message_t *msg)
Get field rssi from rc_channels_raw message.
static void mavlink_msg_rc_channels_raw_decode (const mavlink_message_t *msg, mavlink_rc_channels_raw_t *rc_channels_raw)
Decode a rc_channels_raw message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS_RAW
Value:
{ \
    "RC_CHANNELS_RAW", \
    11, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_rc_channels_raw_t, time_boot_ms) }, \
         { "chan1_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_rc_channels_raw_t, chan1_raw) }, \
         { "chan2_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_rc_channels_raw_t, chan2_raw) }, \
         { "chan3_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_rc_channels_raw_t, chan3_raw) }, \
         { "chan4_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_rc_channels_raw_t, chan4_raw) }, \
         { "chan5_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_rc_channels_raw_t, chan5_raw) }, \
         { "chan6_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 14, offsetof(mavlink_rc_channels_raw_t, chan6_raw) }, \
         { "chan7_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_rc_channels_raw_t, chan7_raw) }, \
         { "chan8_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_rc_channels_raw_t, chan8_raw) }, \
         { "port", NULL, MAVLINK_TYPE_UINT8_T, 0, 20, offsetof(mavlink_rc_channels_raw_t, port) }, \
         { "rssi", NULL, MAVLINK_TYPE_UINT8_T, 0, 21, offsetof(mavlink_rc_channels_raw_t, rssi) }, \
         } \
}
Definition at line 28 of file mavlink_msg_rc_channels_raw.h.
#define MAVLINK_MSG_ID_35_CRC 244
Definition at line 24 of file mavlink_msg_rc_channels_raw.h.
#define MAVLINK_MSG_ID_35_LEN 22
Definition at line 21 of file mavlink_msg_rc_channels_raw.h.
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW 35
Definition at line 3 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_pack(), and mavlink_msg_rc_channels_raw_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW_CRC 244
Definition at line 23 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_pack(), and mavlink_msg_rc_channels_raw_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW_LEN 22
Definition at line 20 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode(), mavlink_msg_rc_channels_raw_pack(), and mavlink_msg_rc_channels_raw_pack_chan().
Typedef Documentation
typedef struct __mavlink_rc_channels_raw_t mavlink_rc_channels_raw_t
Function Documentation
static void mavlink_msg_rc_channels_raw_decode (const mavlink_message_t * msg, mavlink_rc_channels_raw_t * rc_channels_raw) inline static
Decode a rc_channels_raw message into a struct.
Parameters
msg The message to decode
rc_channels_raw C-struct to decode the message contents into
Definition at line 432 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_test_rc_channels_raw().
static uint16_t mavlink_msg_rc_channels_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rc_channels_raw_t * rc_channels_raw) inline static
Encode a rc_channels_raw struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rc_channels_raw C-struct to read the message contents from
Definition at line 179 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_test_rc_channels_raw().
static uint16_t mavlink_msg_rc_channels_raw_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_rc_channels_raw_t * rc_channels_raw) inline static
Encode a rc_channels_raw struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rc_channels_raw C-struct to read the message contents from
Definition at line 193 of file mavlink_msg_rc_channels_raw.h.
static uint16_t mavlink_msg_rc_channels_raw_get_chan1_raw (const mavlink_message_t * msg) inline static
Get field chan1_raw from rc_channels_raw message.
Returns
RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 341 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan2_raw (const mavlink_message_t * msg) inline static
Get field chan2_raw from rc_channels_raw message.
Returns
RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 351 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan3_raw (const mavlink_message_t * msg) inline static
Get field chan3_raw from rc_channels_raw message.
Returns
RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 361 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan4_raw (const mavlink_message_t * msg) inline static
Get field chan4_raw from rc_channels_raw message.
Returns
RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 371 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan5_raw (const mavlink_message_t * msg) inline static
Get field chan5_raw from rc_channels_raw message.
Returns
RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 381 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan6_raw (const mavlink_message_t * msg) inline static
Get field chan6_raw from rc_channels_raw message.
Returns
RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 391 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan7_raw (const mavlink_message_t * msg) inline static
Get field chan7_raw from rc_channels_raw message.
Returns
RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 401 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan8_raw (const mavlink_message_t * msg) inline static
Get field chan8_raw from rc_channels_raw message.
Returns
RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 411 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint8_t mavlink_msg_rc_channels_raw_get_port (const mavlink_message_t * msg) inline static
Get field port from rc_channels_raw message.
Returns
Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows for more than 8 servos.
Definition at line 331 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint8_t mavlink_msg_rc_channels_raw_get_rssi (const mavlink_message_t * msg) inline static
Get field rssi from rc_channels_raw message.
Returns
Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
Definition at line 421 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint32_t mavlink_msg_rc_channels_raw_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a rc_channels_raw message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
port Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows for more than 8 servos.
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
rssi Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown. Get field time_boot_ms from rc_channels_raw message
Returns
Timestamp (milliseconds since system boot)
Definition at line 321 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t port, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi) inline static
Pack a rc_channels_raw message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
port Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows for more than 8 servos.
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
rssi Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 65 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_encode(), and mavlink_test_rc_channels_raw().
static uint16_t mavlink_msg_rc_channels_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t port, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi) inline static
Pack a rc_channels_raw message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
port Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows for more than 8 servos.
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
rssi Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 127 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_encode_chan(), and mavlink_test_rc_channels_raw().