APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_att_pos_mocap.h File Reference
mavlink_msg_att_pos_mocap.h File Reference
Classes
struct __mavlink_att_pos_mocap_t
Macros
#define MAVLINK_MSG_ID_ATT_POS_MOCAP 138
#define MAVLINK_MSG_ID_ATT_POS_MOCAP_LEN 36
#define MAVLINK_MSG_ID_138_LEN 36
#define MAVLINK_MSG_ID_ATT_POS_MOCAP_CRC 109
#define MAVLINK_MSG_ID_138_CRC 109
#define MAVLINK_MSG_ATT_POS_MOCAP_FIELD_Q_LEN 4
#define MAVLINK_MESSAGE_INFO_ATT_POS_MOCAP
Typedefs
typedef struct __mavlink_att_pos_mocap_t mavlink_att_pos_mocap_t
Functions
static uint16_t mavlink_msg_att_pos_mocap_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, const float *q, float x, float y, float z)
Pack a att_pos_mocap message.
static uint16_t mavlink_msg_att_pos_mocap_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, const float *q, float x, float y, float z)
Pack a att_pos_mocap message on a channel.
static uint16_t mavlink_msg_att_pos_mocap_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_att_pos_mocap_t *att_pos_mocap)
Encode a att_pos_mocap struct.
static uint16_t mavlink_msg_att_pos_mocap_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_att_pos_mocap_t *att_pos_mocap)
Encode a att_pos_mocap struct on a channel.
static uint64_t mavlink_msg_att_pos_mocap_get_time_usec (const mavlink_message_t *msg)
Send a att_pos_mocap message.
static uint16_t mavlink_msg_att_pos_mocap_get_q (const mavlink_message_t *msg, float *q)
Get field q from att_pos_mocap message.
static float mavlink_msg_att_pos_mocap_get_x (const mavlink_message_t *msg)
Get field x from att_pos_mocap message.
static float mavlink_msg_att_pos_mocap_get_y (const mavlink_message_t *msg)
Get field y from att_pos_mocap message.
static float mavlink_msg_att_pos_mocap_get_z (const mavlink_message_t *msg)
Get field z from att_pos_mocap message.
static void mavlink_msg_att_pos_mocap_decode (const mavlink_message_t *msg, mavlink_att_pos_mocap_t *att_pos_mocap)
Decode a att_pos_mocap message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ATT_POS_MOCAP
Value:
{ \
    "ATT_POS_MOCAP", \
    5, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_att_pos_mocap_t, time_usec) }, \
         { "q", NULL, MAVLINK_TYPE_FLOAT, 4, 8, offsetof(mavlink_att_pos_mocap_t, q) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_att_pos_mocap_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_att_pos_mocap_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_att_pos_mocap_t, z) }, \
         } \
}
Definition at line 22 of file mavlink_msg_att_pos_mocap.h.
#define MAVLINK_MSG_ATT_POS_MOCAP_FIELD_Q_LEN 4
Definition at line 20 of file mavlink_msg_att_pos_mocap.h.
#define MAVLINK_MSG_ID_138_CRC 109
Definition at line 18 of file mavlink_msg_att_pos_mocap.h.
#define MAVLINK_MSG_ID_138_LEN 36
Definition at line 15 of file mavlink_msg_att_pos_mocap.h.
#define MAVLINK_MSG_ID_ATT_POS_MOCAP 138
Definition at line 3 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_pack(), and mavlink_msg_att_pos_mocap_pack_chan().
#define MAVLINK_MSG_ID_ATT_POS_MOCAP_CRC 109
Definition at line 17 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_pack(), and mavlink_msg_att_pos_mocap_pack_chan().
#define MAVLINK_MSG_ID_ATT_POS_MOCAP_LEN 36
Definition at line 14 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_decode(), mavlink_msg_att_pos_mocap_pack(), and mavlink_msg_att_pos_mocap_pack_chan().
Typedef Documentation
typedef struct __mavlink_att_pos_mocap_t mavlink_att_pos_mocap_t
Function Documentation
static void mavlink_msg_att_pos_mocap_decode (const mavlink_message_t * msg, mavlink_att_pos_mocap_t * att_pos_mocap) inline static
Decode a att_pos_mocap message into a struct.
Parameters
msg The message to decode
att_pos_mocap C-struct to decode the message contents into
Definition at line 286 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_test_att_pos_mocap().
static uint16_t mavlink_msg_att_pos_mocap_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_att_pos_mocap_t * att_pos_mocap) inline static
Encode a att_pos_mocap struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
att_pos_mocap C-struct to read the message contents from
Definition at line 127 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_test_att_pos_mocap().
static uint16_t mavlink_msg_att_pos_mocap_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_att_pos_mocap_t * att_pos_mocap) inline static
Encode a att_pos_mocap struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
att_pos_mocap C-struct to read the message contents from
Definition at line 141 of file mavlink_msg_att_pos_mocap.h.
static uint16_t mavlink_msg_att_pos_mocap_get_q (const mavlink_message_t * msg, float * q) inline static
Get field q from att_pos_mocap message.
Returns
Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
Definition at line 245 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_decode().
static uint64_t mavlink_msg_att_pos_mocap_get_time_usec (const mavlink_message_t * msg) inline static
Send a att_pos_mocap message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (micros since boot or Unix epoch)
q Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
x X position in meters (NED)
y Y position in meters (NED)
z Z position in meters (NED) Get field time_usec from att_pos_mocap message
Returns
Timestamp (micros since boot or Unix epoch)
Definition at line 235 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_decode().
static float mavlink_msg_att_pos_mocap_get_x (const mavlink_message_t * msg) inline static
Get field x from att_pos_mocap message.
Returns
X position in meters (NED)
Definition at line 255 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_decode().
static float mavlink_msg_att_pos_mocap_get_y (const mavlink_message_t * msg) inline static
Get field y from att_pos_mocap message.
Returns
Y position in meters (NED)
Definition at line 265 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_decode().
static float mavlink_msg_att_pos_mocap_get_z (const mavlink_message_t * msg) inline static
Get field z from att_pos_mocap message.
Returns
Z position in meters (NED)
Definition at line 275 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_decode().
static uint16_t mavlink_msg_att_pos_mocap_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, const float * q, float x, float y, float z) inline static
Pack a att_pos_mocap message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
q Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
x X position in meters (NED)
y Y position in meters (NED)
z Z position in meters (NED)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_encode(), and mavlink_test_att_pos_mocap().
static uint16_t mavlink_msg_att_pos_mocap_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, const float * q, float x, float y, float z) inline static
Pack a att_pos_mocap message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
q Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
x X position in meters (NED)
y Y position in meters (NED)
z Z position in meters (NED)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 89 of file mavlink_msg_att_pos_mocap.h.
Referenced by mavlink_msg_att_pos_mocap_encode_chan(), and mavlink_test_att_pos_mocap().