APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_set_actuator_control_target.h File Reference
mavlink_msg_set_actuator_control_target.h File Reference
Classes
struct __mavlink_set_actuator_control_target_t
Macros
#define MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET 139
#define MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET_LEN 43
#define MAVLINK_MSG_ID_139_LEN 43
#define MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET_CRC 168
#define MAVLINK_MSG_ID_139_CRC 168
#define MAVLINK_MSG_SET_ACTUATOR_CONTROL_TARGET_FIELD_CONTROLS_LEN 8
#define MAVLINK_MESSAGE_INFO_SET_ACTUATOR_CONTROL_TARGET
Typedefs
typedef struct __mavlink_set_actuator_control_target_t mavlink_set_actuator_control_target_t
Functions
static uint16_t mavlink_msg_set_actuator_control_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t group_mlx, uint8_t target_system, uint8_t target_component, const float *controls)
Pack a set_actuator_control_target message.
static uint16_t mavlink_msg_set_actuator_control_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t group_mlx, uint8_t target_system, uint8_t target_component, const float *controls)
Pack a set_actuator_control_target message on a channel.
static uint16_t mavlink_msg_set_actuator_control_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_set_actuator_control_target_t *set_actuator_control_target)
Encode a set_actuator_control_target struct.
static uint16_t mavlink_msg_set_actuator_control_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_set_actuator_control_target_t *set_actuator_control_target)
Encode a set_actuator_control_target struct on a channel.
static uint64_t mavlink_msg_set_actuator_control_target_get_time_usec (const mavlink_message_t *msg)
Send a set_actuator_control_target message.
static uint8_t mavlink_msg_set_actuator_control_target_get_group_mlx (const mavlink_message_t *msg)
Get field group_mlx from set_actuator_control_target message.
static uint8_t mavlink_msg_set_actuator_control_target_get_target_system (const mavlink_message_t *msg)
Get field target_system from set_actuator_control_target message.
static uint8_t mavlink_msg_set_actuator_control_target_get_target_component (const mavlink_message_t *msg)
Get field target_component from set_actuator_control_target message.
static uint16_t mavlink_msg_set_actuator_control_target_get_controls (const mavlink_message_t *msg, float *controls)
Get field controls from set_actuator_control_target message.
static void mavlink_msg_set_actuator_control_target_decode (const mavlink_message_t *msg, mavlink_set_actuator_control_target_t *set_actuator_control_target)
Decode a set_actuator_control_target message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SET_ACTUATOR_CONTROL_TARGET
Value:
{ \
    "SET_ACTUATOR_CONTROL_TARGET", \
    5, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_set_actuator_control_target_t, time_usec) }, \
         { "controls", NULL, MAVLINK_TYPE_FLOAT, 8, 8, offsetof(mavlink_set_actuator_control_target_t, controls) }, \
         { "group_mlx", NULL, MAVLINK_TYPE_UINT8_T, 0, 40, offsetof(mavlink_set_actuator_control_target_t, group_mlx) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 41, offsetof(mavlink_set_actuator_control_target_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 42, offsetof(mavlink_set_actuator_control_target_t, target_component) }, \
         } \
}
Definition at line 22 of file mavlink_msg_set_actuator_control_target.h.
#define MAVLINK_MSG_ID_139_CRC 168
Definition at line 18 of file mavlink_msg_set_actuator_control_target.h.
#define MAVLINK_MSG_ID_139_LEN 43
Definition at line 15 of file mavlink_msg_set_actuator_control_target.h.
#define MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET 139
Definition at line 3 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_pack(), and mavlink_msg_set_actuator_control_target_pack_chan().
#define MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET_CRC 168
Definition at line 17 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_pack(), and mavlink_msg_set_actuator_control_target_pack_chan().
#define MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET_LEN 43
Definition at line 14 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_decode(), mavlink_msg_set_actuator_control_target_pack(), and mavlink_msg_set_actuator_control_target_pack_chan().
#define MAVLINK_MSG_SET_ACTUATOR_CONTROL_TARGET_FIELD_CONTROLS_LEN 8
Definition at line 20 of file mavlink_msg_set_actuator_control_target.h.
Typedef Documentation
typedef struct __mavlink_set_actuator_control_target_t mavlink_set_actuator_control_target_t
Function Documentation
static void mavlink_msg_set_actuator_control_target_decode (const mavlink_message_t * msg, mavlink_set_actuator_control_target_t * set_actuator_control_target) inline static
Decode a set_actuator_control_target message into a struct.
Parameters
msg The message to decode
set_actuator_control_target C-struct to decode the message contents into
Definition at line 286 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_test_set_actuator_control_target().
static uint16_t mavlink_msg_set_actuator_control_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_set_actuator_control_target_t * set_actuator_control_target) inline static
Encode a set_actuator_control_target struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
set_actuator_control_target C-struct to read the message contents from
Definition at line 127 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_test_set_actuator_control_target().
static uint16_t mavlink_msg_set_actuator_control_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_set_actuator_control_target_t * set_actuator_control_target) inline static
Encode a set_actuator_control_target struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
set_actuator_control_target C-struct to read the message contents from
Definition at line 141 of file mavlink_msg_set_actuator_control_target.h.
static uint16_t mavlink_msg_set_actuator_control_target_get_controls (const mavlink_message_t * msg, float * controls) inline static
Get field controls from set_actuator_control_target message.
Returns
Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs.
Definition at line 275 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_decode().
static uint8_t mavlink_msg_set_actuator_control_target_get_group_mlx (const mavlink_message_t * msg) inline static
Get field group_mlx from set_actuator_control_target message.
Returns
Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
Definition at line 245 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_decode().
static uint8_t mavlink_msg_set_actuator_control_target_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from set_actuator_control_target message.
Returns
Component ID
Definition at line 265 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_decode().
static uint8_t mavlink_msg_set_actuator_control_target_get_target_system (const mavlink_message_t * msg) inline static
Get field target_system from set_actuator_control_target message.
Returns
System ID
Definition at line 255 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_decode().
static uint64_t mavlink_msg_set_actuator_control_target_get_time_usec (const mavlink_message_t * msg) inline static
Send a set_actuator_control_target message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (micros since boot or Unix epoch)
group_mlx Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
target_system System ID
target_component Component ID
controls Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs. Get field time_usec from set_actuator_control_target message
Returns
Timestamp (micros since boot or Unix epoch)
Definition at line 235 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_decode().
static uint16_t mavlink_msg_set_actuator_control_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t group_mlx, uint8_t target_system, uint8_t target_component, const float * controls) inline static
Pack a set_actuator_control_target message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
group_mlx Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
target_system System ID
target_component Component ID
controls Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_encode(), and mavlink_test_set_actuator_control_target().
static uint16_t mavlink_msg_set_actuator_control_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t group_mlx, uint8_t target_system, uint8_t target_component, const float * controls) inline static
Pack a set_actuator_control_target message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
group_mlx Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
target_system System ID
target_component Component ID
controls Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 89 of file mavlink_msg_set_actuator_control_target.h.
Referenced by mavlink_msg_set_actuator_control_target_encode_chan(), and mavlink_test_set_actuator_control_target().