APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gopro_set_request.h File Reference
mavlink_msg_gopro_set_request.h File Reference
Classes
struct __mavlink_gopro_set_request_t
Macros
#define MAVLINK_MSG_ID_GOPRO_SET_REQUEST 218
#define MAVLINK_MSG_ID_GOPRO_SET_REQUEST_LEN 4
#define MAVLINK_MSG_ID_218_LEN 4
#define MAVLINK_MSG_ID_GOPRO_SET_REQUEST_CRC 115
#define MAVLINK_MSG_ID_218_CRC 115
#define MAVLINK_MESSAGE_INFO_GOPRO_SET_REQUEST
Typedefs
typedef struct __mavlink_gopro_set_request_t mavlink_gopro_set_request_t
Functions
static uint16_t mavlink_msg_gopro_set_request_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t cmd_id, uint8_t value)
Pack a gopro_set_request message.
static uint16_t mavlink_msg_gopro_set_request_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t cmd_id, uint8_t value)
Pack a gopro_set_request message on a channel.
static uint16_t mavlink_msg_gopro_set_request_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gopro_set_request_t *gopro_set_request)
Encode a gopro_set_request struct.
static uint16_t mavlink_msg_gopro_set_request_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gopro_set_request_t *gopro_set_request)
Encode a gopro_set_request struct on a channel.
static uint8_t mavlink_msg_gopro_set_request_get_target_system (const mavlink_message_t *msg)
Send a gopro_set_request message.
static uint8_t mavlink_msg_gopro_set_request_get_target_component (const mavlink_message_t *msg)
Get field target_component from gopro_set_request message.
static uint8_t mavlink_msg_gopro_set_request_get_cmd_id (const mavlink_message_t *msg)
Get field cmd_id from gopro_set_request message.
static uint8_t mavlink_msg_gopro_set_request_get_value (const mavlink_message_t *msg)
Get field value from gopro_set_request message.
static void mavlink_msg_gopro_set_request_decode (const mavlink_message_t *msg, mavlink_gopro_set_request_t *gopro_set_request)
Decode a gopro_set_request message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GOPRO_SET_REQUEST
Value:
{ \
    "GOPRO_SET_REQUEST", \
    4, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gopro_set_request_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gopro_set_request_t, target_component) }, \
         { "cmd_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_gopro_set_request_t, cmd_id) }, \
         { "value", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_gopro_set_request_t, value) }, \
         } \
}
Definition at line 21 of file mavlink_msg_gopro_set_request.h.
#define MAVLINK_MSG_ID_218_CRC 115
Definition at line 17 of file mavlink_msg_gopro_set_request.h.
#define MAVLINK_MSG_ID_218_LEN 4
Definition at line 14 of file mavlink_msg_gopro_set_request.h.
#define MAVLINK_MSG_ID_GOPRO_SET_REQUEST 218
Definition at line 3 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_pack(), and mavlink_msg_gopro_set_request_pack_chan().
#define MAVLINK_MSG_ID_GOPRO_SET_REQUEST_CRC 115
Definition at line 16 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_pack(), and mavlink_msg_gopro_set_request_pack_chan().
#define MAVLINK_MSG_ID_GOPRO_SET_REQUEST_LEN 4
Definition at line 13 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_decode(), mavlink_msg_gopro_set_request_pack(), and mavlink_msg_gopro_set_request_pack_chan().
Typedef Documentation
typedef struct __mavlink_gopro_set_request_t mavlink_gopro_set_request_t
Function Documentation
static void mavlink_msg_gopro_set_request_decode (const mavlink_message_t * msg, mavlink_gopro_set_request_t * gopro_set_request) inline static
Decode a gopro_set_request message into a struct.
Parameters
msg The message to decode
gopro_set_request C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_test_gopro_set_request().
static uint16_t mavlink_msg_gopro_set_request_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gopro_set_request_t * gopro_set_request) inline static
Encode a gopro_set_request struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gopro_set_request C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_test_gopro_set_request().
static uint16_t mavlink_msg_gopro_set_request_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gopro_set_request_t * gopro_set_request) inline static
Encode a gopro_set_request struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gopro_set_request C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_gopro_set_request.h.
static uint8_t mavlink_msg_gopro_set_request_get_cmd_id (const mavlink_message_t * msg) inline static
Get field cmd_id from gopro_set_request message.
Returns
Command ID
Definition at line 250 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_decode().
static uint8_t mavlink_msg_gopro_set_request_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gopro_set_request message.
Returns
Component ID
Definition at line 240 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_decode().
static uint8_t mavlink_msg_gopro_set_request_get_target_system (const mavlink_message_t * msg) inline static
Send a gopro_set_request message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
cmd_id Command ID
value Value Get field target_system from gopro_set_request message
Returns
System ID
Definition at line 230 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_decode().
static uint8_t mavlink_msg_gopro_set_request_get_value (const mavlink_message_t * msg) inline static
Get field value from gopro_set_request message.
Returns
Value
Definition at line 260 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_decode().
static uint16_t mavlink_msg_gopro_set_request_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t cmd_id, uint8_t value) inline static
Pack a gopro_set_request message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
cmd_id Command ID
value Value
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_encode(), and mavlink_test_gopro_set_request().
static uint16_t mavlink_msg_gopro_set_request_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t cmd_id, uint8_t value) inline static
Pack a gopro_set_request message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
cmd_id Command ID
value Value
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_gopro_set_request.h.
Referenced by mavlink_msg_gopro_set_request_encode_chan(), and mavlink_test_gopro_set_request().