APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_ahrs.h File Reference
mavlink_msg_ahrs.h File Reference
Classes
struct __mavlink_ahrs_t
Macros
#define MAVLINK_MSG_ID_AHRS 163
#define MAVLINK_MSG_ID_AHRS_LEN 28
#define MAVLINK_MSG_ID_163_LEN 28
#define MAVLINK_MSG_ID_AHRS_CRC 127
#define MAVLINK_MSG_ID_163_CRC 127
#define MAVLINK_MESSAGE_INFO_AHRS
Typedefs
typedef struct __mavlink_ahrs_t mavlink_ahrs_t
Functions
static uint16_t mavlink_msg_ahrs_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float omegaIx, float omegaIy, float omegaIz, float accel_weight, float renorm_val, float error_rp, float error_yaw)
Pack a ahrs message.
static uint16_t mavlink_msg_ahrs_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float omegaIx, float omegaIy, float omegaIz, float accel_weight, float renorm_val, float error_rp, float error_yaw)
Pack a ahrs message on a channel.
static uint16_t mavlink_msg_ahrs_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_ahrs_t *ahrs)
Encode a ahrs struct.
static uint16_t mavlink_msg_ahrs_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_ahrs_t *ahrs)
Encode a ahrs struct on a channel.
static float mavlink_msg_ahrs_get_omegaIx (const mavlink_message_t *msg)
Send a ahrs message.
static float mavlink_msg_ahrs_get_omegaIy (const mavlink_message_t *msg)
Get field omegaIy from ahrs message.
static float mavlink_msg_ahrs_get_omegaIz (const mavlink_message_t *msg)
Get field omegaIz from ahrs message.
static float mavlink_msg_ahrs_get_accel_weight (const mavlink_message_t *msg)
Get field accel_weight from ahrs message.
static float mavlink_msg_ahrs_get_renorm_val (const mavlink_message_t *msg)
Get field renorm_val from ahrs message.
static float mavlink_msg_ahrs_get_error_rp (const mavlink_message_t *msg)
Get field error_rp from ahrs message.
static float mavlink_msg_ahrs_get_error_yaw (const mavlink_message_t *msg)
Get field error_yaw from ahrs message.
static void mavlink_msg_ahrs_decode (const mavlink_message_t *msg, mavlink_ahrs_t *ahrs)
Decode a ahrs message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AHRS
Value:
{ \
    "AHRS", \
    7, \
    {  { "omegaIx", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_ahrs_t, omegaIx) }, \
         { "omegaIy", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_ahrs_t, omegaIy) }, \
         { "omegaIz", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_ahrs_t, omegaIz) }, \
         { "accel_weight", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_ahrs_t, accel_weight) }, \
         { "renorm_val", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_ahrs_t, renorm_val) }, \
         { "error_rp", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_ahrs_t, error_rp) }, \
         { "error_yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_ahrs_t, error_yaw) }, \
         } \
}
Definition at line 24 of file mavlink_msg_ahrs.h.
#define MAVLINK_MSG_ID_163_CRC 127
Definition at line 20 of file mavlink_msg_ahrs.h.
#define MAVLINK_MSG_ID_163_LEN 28
Definition at line 17 of file mavlink_msg_ahrs.h.
#define MAVLINK_MSG_ID_AHRS 163
Definition at line 3 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_pack(), and mavlink_msg_ahrs_pack_chan().
#define MAVLINK_MSG_ID_AHRS_CRC 127
Definition at line 19 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_pack(), and mavlink_msg_ahrs_pack_chan().
#define MAVLINK_MSG_ID_AHRS_LEN 28
Definition at line 16 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode(), mavlink_msg_ahrs_pack(), and mavlink_msg_ahrs_pack_chan().
Typedef Documentation
typedef struct __mavlink_ahrs_t mavlink_ahrs_t
Function Documentation
static void mavlink_msg_ahrs_decode (const mavlink_message_t * msg, mavlink_ahrs_t * ahrs) inline static
Decode a ahrs message into a struct.
Parameters
msg The message to decode
ahrs C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_ahrs.h.
Referenced by mavlink_test_ahrs().
static uint16_t mavlink_msg_ahrs_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_ahrs_t * ahrs) inline static
Encode a ahrs struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
ahrs C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_ahrs.h.
Referenced by mavlink_test_ahrs().
static uint16_t mavlink_msg_ahrs_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_ahrs_t * ahrs) inline static
Encode a ahrs struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
ahrs C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_ahrs.h.
static float mavlink_msg_ahrs_get_accel_weight (const mavlink_message_t * msg) inline static
Get field accel_weight from ahrs message.
Returns
average accel_weight
Definition at line 299 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static float mavlink_msg_ahrs_get_error_rp (const mavlink_message_t * msg) inline static
Get field error_rp from ahrs message.
Returns
average error_roll_pitch value
Definition at line 319 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static float mavlink_msg_ahrs_get_error_yaw (const mavlink_message_t * msg) inline static
Get field error_yaw from ahrs message.
Returns
average error_yaw value
Definition at line 329 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static float mavlink_msg_ahrs_get_omegaIx (const mavlink_message_t * msg) inline static
Send a ahrs message.
Parameters
chan MAVLink channel to send the message
omegaIx X gyro drift estimate rad/s
omegaIy Y gyro drift estimate rad/s
omegaIz Z gyro drift estimate rad/s
accel_weight average accel_weight
renorm_val average renormalisation value
error_rp average error_roll_pitch value
error_yaw average error_yaw value Get field omegaIx from ahrs message
Returns
X gyro drift estimate rad/s
Definition at line 269 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static float mavlink_msg_ahrs_get_omegaIy (const mavlink_message_t * msg) inline static
Get field omegaIy from ahrs message.
Returns
Y gyro drift estimate rad/s
Definition at line 279 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static float mavlink_msg_ahrs_get_omegaIz (const mavlink_message_t * msg) inline static
Get field omegaIz from ahrs message.
Returns
Z gyro drift estimate rad/s
Definition at line 289 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static float mavlink_msg_ahrs_get_renorm_val (const mavlink_message_t * msg) inline static
Get field renorm_val from ahrs message.
Returns
average renormalisation value
Definition at line 309 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_decode().
static uint16_t mavlink_msg_ahrs_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float omegaIx, float omegaIy, float omegaIz, float accel_weight, float renorm_val, float error_rp, float error_yaw) inline static
Pack a ahrs message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
omegaIx X gyro drift estimate rad/s
omegaIy Y gyro drift estimate rad/s
omegaIz Z gyro drift estimate rad/s
accel_weight average accel_weight
renorm_val average renormalisation value
error_rp average error_roll_pitch value
error_yaw average error_yaw value
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_encode(), and mavlink_test_ahrs().
static uint16_t mavlink_msg_ahrs_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float omegaIx, float omegaIy, float omegaIz, float accel_weight, float renorm_val, float error_rp, float error_yaw) inline static
Pack a ahrs message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
omegaIx X gyro drift estimate rad/s
omegaIy Y gyro drift estimate rad/s
omegaIz Z gyro drift estimate rad/s
accel_weight average accel_weight
renorm_val average renormalisation value
error_rp average error_roll_pitch value
error_yaw average error_yaw value
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_ahrs.h.
Referenced by mavlink_msg_ahrs_encode_chan(), and mavlink_test_ahrs().