APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_autopilot_version.h File Reference
mavlink_msg_autopilot_version.h File Reference
Classes
struct __mavlink_autopilot_version_t
Macros
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION 148
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_LEN 60
#define MAVLINK_MSG_ID_148_LEN 60
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_CRC 178
#define MAVLINK_MSG_ID_148_CRC 178
#define MAVLINK_MSG_AUTOPILOT_VERSION_FIELD_FLIGHT_CUSTOM_VERSION_LEN 8
#define MAVLINK_MSG_AUTOPILOT_VERSION_FIELD_MIDDLEWARE_CUSTOM_VERSION_LEN 8
#define MAVLINK_MSG_AUTOPILOT_VERSION_FIELD_OS_CUSTOM_VERSION_LEN 8
#define MAVLINK_MESSAGE_INFO_AUTOPILOT_VERSION
Typedefs
typedef struct __mavlink_autopilot_version_t mavlink_autopilot_version_t
Functions
static uint16_t mavlink_msg_autopilot_version_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t capabilities, uint32_t flight_sw_version, uint32_t middleware_sw_version, uint32_t os_sw_version, uint32_t board_version, const uint8_t *flight_custom_version, const uint8_t *middleware_custom_version, const uint8_t *os_custom_version, uint16_t vendor_id, uint16_t product_id, uint64_t uid)
Pack a autopilot_version message.
static uint16_t mavlink_msg_autopilot_version_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t capabilities, uint32_t flight_sw_version, uint32_t middleware_sw_version, uint32_t os_sw_version, uint32_t board_version, const uint8_t *flight_custom_version, const uint8_t *middleware_custom_version, const uint8_t *os_custom_version, uint16_t vendor_id, uint16_t product_id, uint64_t uid)
Pack a autopilot_version message on a channel.
static uint16_t mavlink_msg_autopilot_version_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_autopilot_version_t *autopilot_version)
Encode a autopilot_version struct.
static uint16_t mavlink_msg_autopilot_version_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_autopilot_version_t *autopilot_version)
Encode a autopilot_version struct on a channel.
static uint64_t mavlink_msg_autopilot_version_get_capabilities (const mavlink_message_t *msg)
Send a autopilot_version message.
static uint32_t mavlink_msg_autopilot_version_get_flight_sw_version (const mavlink_message_t *msg)
Get field flight_sw_version from autopilot_version message.
static uint32_t mavlink_msg_autopilot_version_get_middleware_sw_version (const mavlink_message_t *msg)
Get field middleware_sw_version from autopilot_version message.
static uint32_t mavlink_msg_autopilot_version_get_os_sw_version (const mavlink_message_t *msg)
Get field os_sw_version from autopilot_version message.
static uint32_t mavlink_msg_autopilot_version_get_board_version (const mavlink_message_t *msg)
Get field board_version from autopilot_version message.
static uint16_t mavlink_msg_autopilot_version_get_flight_custom_version (const mavlink_message_t *msg, uint8_t *flight_custom_version)
Get field flight_custom_version from autopilot_version message.
static uint16_t mavlink_msg_autopilot_version_get_middleware_custom_version (const mavlink_message_t *msg, uint8_t *middleware_custom_version)
Get field middleware_custom_version from autopilot_version message.
static uint16_t mavlink_msg_autopilot_version_get_os_custom_version (const mavlink_message_t *msg, uint8_t *os_custom_version)
Get field os_custom_version from autopilot_version message.
static uint16_t mavlink_msg_autopilot_version_get_vendor_id (const mavlink_message_t *msg)
Get field vendor_id from autopilot_version message.
static uint16_t mavlink_msg_autopilot_version_get_product_id (const mavlink_message_t *msg)
Get field product_id from autopilot_version message.
static uint64_t mavlink_msg_autopilot_version_get_uid (const mavlink_message_t *msg)
Get field uid from autopilot_version message.
static void mavlink_msg_autopilot_version_decode (const mavlink_message_t *msg, mavlink_autopilot_version_t *autopilot_version)
Decode a autopilot_version message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AUTOPILOT_VERSION
Value:
{ \
    "AUTOPILOT_VERSION", \
    11, \
    {  { "capabilities", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_autopilot_version_t, capabilities) }, \
         { "uid", NULL, MAVLINK_TYPE_UINT64_T, 0, 8, offsetof(mavlink_autopilot_version_t, uid) }, \
         { "flight_sw_version", NULL, MAVLINK_TYPE_UINT32_T, 0, 16, offsetof(mavlink_autopilot_version_t, flight_sw_version) }, \
         { "middleware_sw_version", NULL, MAVLINK_TYPE_UINT32_T, 0, 20, offsetof(mavlink_autopilot_version_t, middleware_sw_version) }, \
         { "os_sw_version", NULL, MAVLINK_TYPE_UINT32_T, 0, 24, offsetof(mavlink_autopilot_version_t, os_sw_version) }, \
         { "board_version", NULL, MAVLINK_TYPE_UINT32_T, 0, 28, offsetof(mavlink_autopilot_version_t, board_version) }, \
         { "vendor_id", NULL, MAVLINK_TYPE_UINT16_T, 0, 32, offsetof(mavlink_autopilot_version_t, vendor_id) }, \
         { "product_id", NULL, MAVLINK_TYPE_UINT16_T, 0, 34, offsetof(mavlink_autopilot_version_t, product_id) }, \
         { "flight_custom_version", NULL, MAVLINK_TYPE_UINT8_T, 8, 36, offsetof(mavlink_autopilot_version_t, flight_custom_version) }, \
         { "middleware_custom_version", NULL, MAVLINK_TYPE_UINT8_T, 8, 44, offsetof(mavlink_autopilot_version_t, middleware_custom_version) }, \
         { "os_custom_version", NULL, MAVLINK_TYPE_UINT8_T, 8, 52, offsetof(mavlink_autopilot_version_t, os_custom_version) }, \
         } \
}
Definition at line 30 of file mavlink_msg_autopilot_version.h.
#define MAVLINK_MSG_AUTOPILOT_VERSION_FIELD_FLIGHT_CUSTOM_VERSION_LEN 8
Definition at line 26 of file mavlink_msg_autopilot_version.h.
#define MAVLINK_MSG_AUTOPILOT_VERSION_FIELD_MIDDLEWARE_CUSTOM_VERSION_LEN 8
Definition at line 27 of file mavlink_msg_autopilot_version.h.
#define MAVLINK_MSG_AUTOPILOT_VERSION_FIELD_OS_CUSTOM_VERSION_LEN 8
Definition at line 28 of file mavlink_msg_autopilot_version.h.
#define MAVLINK_MSG_ID_148_CRC 178
Definition at line 24 of file mavlink_msg_autopilot_version.h.
#define MAVLINK_MSG_ID_148_LEN 60
Definition at line 21 of file mavlink_msg_autopilot_version.h.
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION 148
Definition at line 3 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_pack(), and mavlink_msg_autopilot_version_pack_chan().
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_CRC 178
Definition at line 23 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_pack(), and mavlink_msg_autopilot_version_pack_chan().
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_LEN 60
Definition at line 20 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode(), mavlink_msg_autopilot_version_pack(), and mavlink_msg_autopilot_version_pack_chan().
Typedef Documentation
typedef struct __mavlink_autopilot_version_t mavlink_autopilot_version_t
Function Documentation
static void mavlink_msg_autopilot_version_decode (const mavlink_message_t * msg, mavlink_autopilot_version_t * autopilot_version) inline static
Decode a autopilot_version message into a struct.
Parameters
msg The message to decode
autopilot_version C-struct to decode the message contents into
Definition at line 426 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_test_autopilot_version().
static uint16_t mavlink_msg_autopilot_version_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_autopilot_version_t * autopilot_version) inline static
Encode a autopilot_version struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
autopilot_version C-struct to read the message contents from
Definition at line 177 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_test_autopilot_version().
static uint16_t mavlink_msg_autopilot_version_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_autopilot_version_t * autopilot_version) inline static
Encode a autopilot_version struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
autopilot_version C-struct to read the message contents from
Definition at line 191 of file mavlink_msg_autopilot_version.h.
static uint32_t mavlink_msg_autopilot_version_get_board_version (const mavlink_message_t * msg) inline static
Get field board_version from autopilot_version message.
Returns
HW / board version (last 8 bytes should be silicon ID, if any)
Definition at line 355 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint64_t mavlink_msg_autopilot_version_get_capabilities (const mavlink_message_t * msg) inline static
Send a autopilot_version message.
Parameters
chan MAVLink channel to send the message
capabilities bitmask of capabilities (see MAV_PROTOCOL_CAPABILITY enum)
flight_sw_version Firmware version number
middleware_sw_version Middleware version number
os_sw_version Operating system version number
board_version HW / board version (last 8 bytes should be silicon ID, if any)
flight_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
middleware_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
os_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
vendor_id ID of the board vendor
product_id ID of the product
uid UID if provided by hardware Get field capabilities from autopilot_version message
Returns
bitmask of capabilities (see MAV_PROTOCOL_CAPABILITY enum)
Definition at line 315 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint16_t mavlink_msg_autopilot_version_get_flight_custom_version (const mavlink_message_t * msg, uint8_t * flight_custom_version) inline static
Get field flight_custom_version from autopilot_version message.
Returns
Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
Definition at line 365 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint32_t mavlink_msg_autopilot_version_get_flight_sw_version (const mavlink_message_t * msg) inline static
Get field flight_sw_version from autopilot_version message.
Returns
Firmware version number
Definition at line 325 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint16_t mavlink_msg_autopilot_version_get_middleware_custom_version (const mavlink_message_t * msg, uint8_t * middleware_custom_version) inline static
Get field middleware_custom_version from autopilot_version message.
Returns
Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
Definition at line 375 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint32_t mavlink_msg_autopilot_version_get_middleware_sw_version (const mavlink_message_t * msg) inline static
Get field middleware_sw_version from autopilot_version message.
Returns
Middleware version number
Definition at line 335 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint16_t mavlink_msg_autopilot_version_get_os_custom_version (const mavlink_message_t * msg, uint8_t * os_custom_version) inline static
Get field os_custom_version from autopilot_version message.
Returns
Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
Definition at line 385 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint32_t mavlink_msg_autopilot_version_get_os_sw_version (const mavlink_message_t * msg) inline static
Get field os_sw_version from autopilot_version message.
Returns
Operating system version number
Definition at line 345 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint16_t mavlink_msg_autopilot_version_get_product_id (const mavlink_message_t * msg) inline static
Get field product_id from autopilot_version message.
Returns
ID of the product
Definition at line 405 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint64_t mavlink_msg_autopilot_version_get_uid (const mavlink_message_t * msg) inline static
Get field uid from autopilot_version message.
Returns
UID if provided by hardware
Definition at line 415 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint16_t mavlink_msg_autopilot_version_get_vendor_id (const mavlink_message_t * msg) inline static
Get field vendor_id from autopilot_version message.
Returns
ID of the board vendor
Definition at line 395 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_decode().
static uint16_t mavlink_msg_autopilot_version_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t capabilities, uint32_t flight_sw_version, uint32_t middleware_sw_version, uint32_t os_sw_version, uint32_t board_version, const uint8_t * flight_custom_version, const uint8_t * middleware_custom_version, const uint8_t * os_custom_version, uint16_t vendor_id, uint16_t product_id, uint64_t uid) inline static
Pack a autopilot_version message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
capabilities bitmask of capabilities (see MAV_PROTOCOL_CAPABILITY enum)
flight_sw_version Firmware version number
middleware_sw_version Middleware version number
os_sw_version Operating system version number
board_version HW / board version (last 8 bytes should be silicon ID, if any)
flight_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
middleware_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
os_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
vendor_id ID of the board vendor
product_id ID of the product
uid UID if provided by hardware
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 67 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_encode(), and mavlink_test_autopilot_version().
static uint16_t mavlink_msg_autopilot_version_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t capabilities, uint32_t flight_sw_version, uint32_t middleware_sw_version, uint32_t os_sw_version, uint32_t board_version, const uint8_t * flight_custom_version, const uint8_t * middleware_custom_version, const uint8_t * os_custom_version, uint16_t vendor_id, uint16_t product_id, uint64_t uid) inline static
Pack a autopilot_version message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
capabilities bitmask of capabilities (see MAV_PROTOCOL_CAPABILITY enum)
flight_sw_version Firmware version number
middleware_sw_version Middleware version number
os_sw_version Operating system version number
board_version HW / board version (last 8 bytes should be silicon ID, if any)
flight_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
middleware_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
os_custom_version Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases.
vendor_id ID of the board vendor
product_id ID of the product
uid UID if provided by hardware
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 127 of file mavlink_msg_autopilot_version.h.
Referenced by mavlink_msg_autopilot_version_encode_chan(), and mavlink_test_autopilot_version().