APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_mission_ack.h File Reference
mavlink_msg_mission_ack.h File Reference
Classes
struct __mavlink_mission_ack_t
Macros
#define MAVLINK_MSG_ID_MISSION_ACK 47
#define MAVLINK_MSG_ID_MISSION_ACK_LEN 3
#define MAVLINK_MSG_ID_47_LEN 3
#define MAVLINK_MSG_ID_MISSION_ACK_CRC 153
#define MAVLINK_MSG_ID_47_CRC 153
#define MAVLINK_MESSAGE_INFO_MISSION_ACK
Typedefs
typedef struct __mavlink_mission_ack_t mavlink_mission_ack_t
Functions
static uint16_t mavlink_msg_mission_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t type)
Pack a mission_ack message.
static uint16_t mavlink_msg_mission_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t type)
Pack a mission_ack message on a channel.
static uint16_t mavlink_msg_mission_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mission_ack_t *mission_ack)
Encode a mission_ack struct.
static uint16_t mavlink_msg_mission_ack_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mission_ack_t *mission_ack)
Encode a mission_ack struct on a channel.
static uint8_t mavlink_msg_mission_ack_get_target_system (const mavlink_message_t *msg)
Send a mission_ack message.
static uint8_t mavlink_msg_mission_ack_get_target_component (const mavlink_message_t *msg)
Get field target_component from mission_ack message.
static uint8_t mavlink_msg_mission_ack_get_type (const mavlink_message_t *msg)
Get field type from mission_ack message.
static void mavlink_msg_mission_ack_decode (const mavlink_message_t *msg, mavlink_mission_ack_t *mission_ack)
Decode a mission_ack message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MISSION_ACK
Value:
{ \
    "MISSION_ACK", \
    3, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_mission_ack_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_mission_ack_t, target_component) }, \
         { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_mission_ack_t, type) }, \
         } \
}
Definition at line 20 of file mavlink_msg_mission_ack.h.
#define MAVLINK_MSG_ID_47_CRC 153
Definition at line 16 of file mavlink_msg_mission_ack.h.
#define MAVLINK_MSG_ID_47_LEN 3
Definition at line 13 of file mavlink_msg_mission_ack.h.
#define MAVLINK_MSG_ID_MISSION_ACK 47
Definition at line 3 of file mavlink_msg_mission_ack.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_mission_ack_pack(), and mavlink_msg_mission_ack_pack_chan().
#define MAVLINK_MSG_ID_MISSION_ACK_CRC 153
Definition at line 15 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_msg_mission_ack_pack(), and mavlink_msg_mission_ack_pack_chan().
#define MAVLINK_MSG_ID_MISSION_ACK_LEN 3
Definition at line 12 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_msg_mission_ack_decode(), mavlink_msg_mission_ack_pack(), and mavlink_msg_mission_ack_pack_chan().
Typedef Documentation
typedef struct __mavlink_mission_ack_t mavlink_mission_ack_t
Function Documentation
static void mavlink_msg_mission_ack_decode (const mavlink_message_t * msg, mavlink_mission_ack_t * mission_ack) inline static
Decode a mission_ack message into a struct.
Parameters
msg The message to decode
mission_ack C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_test_mission_ack().
static uint16_t mavlink_msg_mission_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mission_ack_t * mission_ack) inline static
Encode a mission_ack struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mission_ack C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_test_mission_ack().
static uint16_t mavlink_msg_mission_ack_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mission_ack_t * mission_ack) inline static
Encode a mission_ack struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mission_ack C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_mission_ack.h.
static uint8_t mavlink_msg_mission_ack_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from mission_ack message.
Returns
Component ID
Definition at line 227 of file mavlink_msg_mission_ack.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_ack_decode().
static uint8_t mavlink_msg_mission_ack_get_target_system (const mavlink_message_t * msg) inline static
Send a mission_ack message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
type See MAV_MISSION_RESULT enum Get field target_system from mission_ack message
Returns
System ID
Definition at line 217 of file mavlink_msg_mission_ack.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_ack_decode().
static uint8_t mavlink_msg_mission_ack_get_type (const mavlink_message_t * msg) inline static
Get field type from mission_ack message.
Returns
See MAV_MISSION_RESULT enum
Definition at line 237 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_msg_mission_ack_decode().
static uint16_t mavlink_msg_mission_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t type) inline static
Pack a mission_ack message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
type See MAV_MISSION_RESULT enum
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_msg_mission_ack_encode(), and mavlink_test_mission_ack().
static uint16_t mavlink_msg_mission_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t type) inline static
Pack a mission_ack message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
type See MAV_MISSION_RESULT enum
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_mission_ack.h.
Referenced by mavlink_msg_mission_ack_encode_chan(), and mavlink_test_mission_ack().