APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_mission_clear_all.h File Reference
mavlink_msg_mission_clear_all.h File Reference
Classes
struct __mavlink_mission_clear_all_t
Macros
#define MAVLINK_MSG_ID_MISSION_CLEAR_ALL 45
#define MAVLINK_MSG_ID_MISSION_CLEAR_ALL_LEN 2
#define MAVLINK_MSG_ID_45_LEN 2
#define MAVLINK_MSG_ID_MISSION_CLEAR_ALL_CRC 232
#define MAVLINK_MSG_ID_45_CRC 232
#define MAVLINK_MESSAGE_INFO_MISSION_CLEAR_ALL
Typedefs
typedef struct __mavlink_mission_clear_all_t mavlink_mission_clear_all_t
Functions
static uint16_t mavlink_msg_mission_clear_all_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a mission_clear_all message.
static uint16_t mavlink_msg_mission_clear_all_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a mission_clear_all message on a channel.
static uint16_t mavlink_msg_mission_clear_all_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mission_clear_all_t *mission_clear_all)
Encode a mission_clear_all struct.
static uint16_t mavlink_msg_mission_clear_all_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mission_clear_all_t *mission_clear_all)
Encode a mission_clear_all struct on a channel.
static uint8_t mavlink_msg_mission_clear_all_get_target_system (const mavlink_message_t *msg)
Send a mission_clear_all message.
static uint8_t mavlink_msg_mission_clear_all_get_target_component (const mavlink_message_t *msg)
Get field target_component from mission_clear_all message.
static void mavlink_msg_mission_clear_all_decode (const mavlink_message_t *msg, mavlink_mission_clear_all_t *mission_clear_all)
Decode a mission_clear_all message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MISSION_CLEAR_ALL
Value:
{ \
    "MISSION_CLEAR_ALL", \
    2, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_mission_clear_all_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_mission_clear_all_t, target_component) }, \
         } \
}
Definition at line 19 of file mavlink_msg_mission_clear_all.h.
#define MAVLINK_MSG_ID_45_CRC 232
Definition at line 15 of file mavlink_msg_mission_clear_all.h.
#define MAVLINK_MSG_ID_45_LEN 2
Definition at line 12 of file mavlink_msg_mission_clear_all.h.
#define MAVLINK_MSG_ID_MISSION_CLEAR_ALL 45
Definition at line 3 of file mavlink_msg_mission_clear_all.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_mission_clear_all_pack(), and mavlink_msg_mission_clear_all_pack_chan().
#define MAVLINK_MSG_ID_MISSION_CLEAR_ALL_CRC 232
Definition at line 14 of file mavlink_msg_mission_clear_all.h.
Referenced by mavlink_msg_mission_clear_all_pack(), and mavlink_msg_mission_clear_all_pack_chan().
#define MAVLINK_MSG_ID_MISSION_CLEAR_ALL_LEN 2
Definition at line 11 of file mavlink_msg_mission_clear_all.h.
Referenced by mavlink_msg_mission_clear_all_decode(), mavlink_msg_mission_clear_all_pack(), and mavlink_msg_mission_clear_all_pack_chan().
Typedef Documentation
typedef struct __mavlink_mission_clear_all_t mavlink_mission_clear_all_t
Function Documentation
static void mavlink_msg_mission_clear_all_decode (const mavlink_message_t * msg, mavlink_mission_clear_all_t * mission_clear_all) inline static
Decode a mission_clear_all message into a struct.
Parameters
msg The message to decode
mission_clear_all C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_mission_clear_all.h.
Referenced by GCS_MAVLINK::handle_mission_clear_all(), and mavlink_test_mission_clear_all().
static uint16_t mavlink_msg_mission_clear_all_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mission_clear_all_t * mission_clear_all) inline static
Encode a mission_clear_all struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mission_clear_all C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_mission_clear_all.h.
Referenced by mavlink_test_mission_clear_all().
static uint16_t mavlink_msg_mission_clear_all_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mission_clear_all_t * mission_clear_all) inline static
Encode a mission_clear_all struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mission_clear_all C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_mission_clear_all.h.
static uint8_t mavlink_msg_mission_clear_all_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from mission_clear_all message.
Returns
Component ID
Definition at line 214 of file mavlink_msg_mission_clear_all.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_clear_all_decode().
static uint8_t mavlink_msg_mission_clear_all_get_target_system (const mavlink_message_t * msg) inline static
Send a mission_clear_all message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID Get field target_system from mission_clear_all message
Returns
System ID
Definition at line 204 of file mavlink_msg_mission_clear_all.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_clear_all_decode().
static uint16_t mavlink_msg_mission_clear_all_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a mission_clear_all message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_mission_clear_all.h.
Referenced by mavlink_msg_mission_clear_all_encode(), and mavlink_test_mission_clear_all().
static uint16_t mavlink_msg_mission_clear_all_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a mission_clear_all message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_mission_clear_all.h.
Referenced by mavlink_msg_mission_clear_all_encode_chan(), and mavlink_test_mission_clear_all().