APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_request_data_stream.h File Reference
mavlink_msg_request_data_stream.h File Reference
Classes
struct __mavlink_request_data_stream_t
Macros
#define MAVLINK_MSG_ID_REQUEST_DATA_STREAM 66
#define MAVLINK_MSG_ID_REQUEST_DATA_STREAM_LEN 6
#define MAVLINK_MSG_ID_66_LEN 6
#define MAVLINK_MSG_ID_REQUEST_DATA_STREAM_CRC 148
#define MAVLINK_MSG_ID_66_CRC 148
#define MAVLINK_MESSAGE_INFO_REQUEST_DATA_STREAM
Typedefs
typedef struct __mavlink_request_data_stream_t mavlink_request_data_stream_t
Functions
static uint16_t mavlink_msg_request_data_stream_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t req_stream_id, uint16_t req_message_rate, uint8_t start_stop)
Pack a request_data_stream message.
static uint16_t mavlink_msg_request_data_stream_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t req_stream_id, uint16_t req_message_rate, uint8_t start_stop)
Pack a request_data_stream message on a channel.
static uint16_t mavlink_msg_request_data_stream_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_request_data_stream_t *request_data_stream)
Encode a request_data_stream struct.
static uint16_t mavlink_msg_request_data_stream_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_request_data_stream_t *request_data_stream)
Encode a request_data_stream struct on a channel.
static uint8_t mavlink_msg_request_data_stream_get_target_system (const mavlink_message_t *msg)
Send a request_data_stream message.
static uint8_t mavlink_msg_request_data_stream_get_target_component (const mavlink_message_t *msg)
Get field target_component from request_data_stream message.
static uint8_t mavlink_msg_request_data_stream_get_req_stream_id (const mavlink_message_t *msg)
Get field req_stream_id from request_data_stream message.
static uint16_t mavlink_msg_request_data_stream_get_req_message_rate (const mavlink_message_t *msg)
Get field req_message_rate from request_data_stream message.
static uint8_t mavlink_msg_request_data_stream_get_start_stop (const mavlink_message_t *msg)
Get field start_stop from request_data_stream message.
static void mavlink_msg_request_data_stream_decode (const mavlink_message_t *msg, mavlink_request_data_stream_t *request_data_stream)
Decode a request_data_stream message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_REQUEST_DATA_STREAM
Value:
{ \
    "REQUEST_DATA_STREAM", \
    5, \
    {  { "req_message_rate", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_request_data_stream_t, req_message_rate) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_request_data_stream_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_request_data_stream_t, target_component) }, \
         { "req_stream_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_request_data_stream_t, req_stream_id) }, \
         { "start_stop", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_request_data_stream_t, start_stop) }, \
         } \
}
Definition at line 22 of file mavlink_msg_request_data_stream.h.
#define MAVLINK_MSG_ID_66_CRC 148
Definition at line 18 of file mavlink_msg_request_data_stream.h.
#define MAVLINK_MSG_ID_66_LEN 6
Definition at line 15 of file mavlink_msg_request_data_stream.h.
#define MAVLINK_MSG_ID_REQUEST_DATA_STREAM 66
Definition at line 3 of file mavlink_msg_request_data_stream.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_request_data_stream_pack(), and mavlink_msg_request_data_stream_pack_chan().
#define MAVLINK_MSG_ID_REQUEST_DATA_STREAM_CRC 148
Definition at line 17 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_pack(), and mavlink_msg_request_data_stream_pack_chan().
#define MAVLINK_MSG_ID_REQUEST_DATA_STREAM_LEN 6
Definition at line 14 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_decode(), mavlink_msg_request_data_stream_pack(), and mavlink_msg_request_data_stream_pack_chan().
Typedef Documentation
typedef struct __mavlink_request_data_stream_t mavlink_request_data_stream_t
Function Documentation
static void mavlink_msg_request_data_stream_decode (const mavlink_message_t * msg, mavlink_request_data_stream_t * request_data_stream) inline static
Decode a request_data_stream message into a struct.
Parameters
msg The message to decode
request_data_stream C-struct to decode the message contents into
Definition at line 294 of file mavlink_msg_request_data_stream.h.
Referenced by GCS_MAVLINK::handle_request_data_stream(), and mavlink_test_request_data_stream().
static uint16_t mavlink_msg_request_data_stream_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_request_data_stream_t * request_data_stream) inline static
Encode a request_data_stream struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
request_data_stream C-struct to read the message contents from
Definition at line 131 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_test_request_data_stream().
static uint16_t mavlink_msg_request_data_stream_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_request_data_stream_t * request_data_stream) inline static
Encode a request_data_stream struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
request_data_stream C-struct to read the message contents from
Definition at line 145 of file mavlink_msg_request_data_stream.h.
static uint16_t mavlink_msg_request_data_stream_get_req_message_rate (const mavlink_message_t * msg) inline static
Get field req_message_rate from request_data_stream message.
Returns
The requested interval between two messages of this type
Definition at line 273 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_decode().
static uint8_t mavlink_msg_request_data_stream_get_req_stream_id (const mavlink_message_t * msg) inline static
Get field req_stream_id from request_data_stream message.
Returns
The ID of the requested data stream
Definition at line 263 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_decode().
static uint8_t mavlink_msg_request_data_stream_get_start_stop (const mavlink_message_t * msg) inline static
Get field start_stop from request_data_stream message.
Returns
1 to start sending, 0 to stop sending.
Definition at line 283 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_decode().
static uint8_t mavlink_msg_request_data_stream_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from request_data_stream message.
Returns
The target requested to send the message stream.
Definition at line 253 of file mavlink_msg_request_data_stream.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_request_data_stream_decode().
static uint8_t mavlink_msg_request_data_stream_get_target_system (const mavlink_message_t * msg) inline static
Send a request_data_stream message.
Parameters
chan MAVLink channel to send the message
target_system The target requested to send the message stream.
target_component The target requested to send the message stream.
req_stream_id The ID of the requested data stream
req_message_rate The requested interval between two messages of this type
start_stop 1 to start sending, 0 to stop sending. Get field target_system from request_data_stream message
Returns
The target requested to send the message stream.
Definition at line 243 of file mavlink_msg_request_data_stream.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_request_data_stream_decode().
static uint16_t mavlink_msg_request_data_stream_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t req_stream_id, uint16_t req_message_rate, uint8_t start_stop) inline static
Pack a request_data_stream message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system The target requested to send the message stream.
target_component The target requested to send the message stream.
req_stream_id The ID of the requested data stream
req_message_rate The requested interval between two messages of this type
start_stop 1 to start sending, 0 to stop sending.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_encode(), and mavlink_test_request_data_stream().
static uint16_t mavlink_msg_request_data_stream_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t req_stream_id, uint16_t req_message_rate, uint8_t start_stop) inline static
Pack a request_data_stream message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system The target requested to send the message stream.
target_component The target requested to send the message stream.
req_stream_id The ID of the requested data stream
req_message_rate The requested interval between two messages of this type
start_stop 1 to start sending, 0 to stop sending.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 91 of file mavlink_msg_request_data_stream.h.
Referenced by mavlink_msg_request_data_stream_encode_chan(), and mavlink_test_request_data_stream().