APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_encapsulated_data.h File Reference
mavlink_msg_encapsulated_data.h File Reference
Classes
struct __mavlink_encapsulated_data_t
Macros
#define MAVLINK_MSG_ID_ENCAPSULATED_DATA 131
#define MAVLINK_MSG_ID_ENCAPSULATED_DATA_LEN 255
#define MAVLINK_MSG_ID_131_LEN 255
#define MAVLINK_MSG_ID_ENCAPSULATED_DATA_CRC 223
#define MAVLINK_MSG_ID_131_CRC 223
#define MAVLINK_MSG_ENCAPSULATED_DATA_FIELD_DATA_LEN 253
#define MAVLINK_MESSAGE_INFO_ENCAPSULATED_DATA
Typedefs
typedef struct __mavlink_encapsulated_data_t mavlink_encapsulated_data_t
Functions
static uint16_t mavlink_msg_encapsulated_data_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t seqnr, const uint8_t *data)
Pack a encapsulated_data message.
static uint16_t mavlink_msg_encapsulated_data_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t seqnr, const uint8_t *data)
Pack a encapsulated_data message on a channel.
static uint16_t mavlink_msg_encapsulated_data_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_encapsulated_data_t *encapsulated_data)
Encode a encapsulated_data struct.
static uint16_t mavlink_msg_encapsulated_data_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_encapsulated_data_t *encapsulated_data)
Encode a encapsulated_data struct on a channel.
static uint16_t mavlink_msg_encapsulated_data_get_seqnr (const mavlink_message_t *msg)
Send a encapsulated_data message.
static uint16_t mavlink_msg_encapsulated_data_get_data (const mavlink_message_t *msg, uint8_t *data)
Get field data from encapsulated_data message.
static void mavlink_msg_encapsulated_data_decode (const mavlink_message_t *msg, mavlink_encapsulated_data_t *encapsulated_data)
Decode a encapsulated_data message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ENCAPSULATED_DATA
Value:
{ \
    "ENCAPSULATED_DATA", \
    2, \
    {  { "seqnr", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_encapsulated_data_t, seqnr) }, \
         { "data", NULL, MAVLINK_TYPE_UINT8_T, 253, 2, offsetof(mavlink_encapsulated_data_t, data) }, \
         } \
}
Definition at line 19 of file mavlink_msg_encapsulated_data.h.
#define MAVLINK_MSG_ENCAPSULATED_DATA_FIELD_DATA_LEN 253
Definition at line 17 of file mavlink_msg_encapsulated_data.h.
#define MAVLINK_MSG_ID_131_CRC 223
Definition at line 15 of file mavlink_msg_encapsulated_data.h.
#define MAVLINK_MSG_ID_131_LEN 255
Definition at line 12 of file mavlink_msg_encapsulated_data.h.
#define MAVLINK_MSG_ID_ENCAPSULATED_DATA 131
Definition at line 3 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_pack(), and mavlink_msg_encapsulated_data_pack_chan().
#define MAVLINK_MSG_ID_ENCAPSULATED_DATA_CRC 223
Definition at line 14 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_pack(), and mavlink_msg_encapsulated_data_pack_chan().
#define MAVLINK_MSG_ID_ENCAPSULATED_DATA_LEN 255
Definition at line 11 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_decode(), mavlink_msg_encapsulated_data_pack(), and mavlink_msg_encapsulated_data_pack_chan().
Typedef Documentation
typedef struct __mavlink_encapsulated_data_t mavlink_encapsulated_data_t
Function Documentation
static void mavlink_msg_encapsulated_data_decode (const mavlink_message_t * msg, mavlink_encapsulated_data_t * encapsulated_data) inline static
Decode a encapsulated_data message into a struct.
Parameters
msg The message to decode
encapsulated_data C-struct to decode the message contents into
Definition at line 217 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_test_encapsulated_data().
static uint16_t mavlink_msg_encapsulated_data_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_encapsulated_data_t * encapsulated_data) inline static
Encode a encapsulated_data struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
encapsulated_data C-struct to read the message contents from
Definition at line 103 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_test_encapsulated_data().
static uint16_t mavlink_msg_encapsulated_data_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_encapsulated_data_t * encapsulated_data) inline static
Encode a encapsulated_data struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
encapsulated_data C-struct to read the message contents from
Definition at line 117 of file mavlink_msg_encapsulated_data.h.
static uint16_t mavlink_msg_encapsulated_data_get_data (const mavlink_message_t * msg, uint8_t * data) inline static
Get field data from encapsulated_data message.
Returns
image data bytes
Definition at line 206 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_decode().
static uint16_t mavlink_msg_encapsulated_data_get_seqnr (const mavlink_message_t * msg) inline static
Send a encapsulated_data message.
Parameters
chan MAVLink channel to send the message
seqnr sequence number (starting with 0 on every transmission)
data image data bytes Get field seqnr from encapsulated_data message
Returns
sequence number (starting with 0 on every transmission)
Definition at line 196 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_decode().
static uint16_t mavlink_msg_encapsulated_data_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t seqnr, const uint8_t * data) inline static
Pack a encapsulated_data message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
seqnr sequence number (starting with 0 on every transmission)
data image data bytes
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_encode(), and mavlink_test_encapsulated_data().
static uint16_t mavlink_msg_encapsulated_data_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t seqnr, const uint8_t * data) inline static
Pack a encapsulated_data message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
seqnr sequence number (starting with 0 on every transmission)
data image data bytes
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 71 of file mavlink_msg_encapsulated_data.h.
Referenced by mavlink_msg_encapsulated_data_encode_chan(), and mavlink_test_encapsulated_data().