APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_hil_controls.h File Reference
mavlink_msg_hil_controls.h File Reference
Classes
struct __mavlink_hil_controls_t
Macros
#define MAVLINK_MSG_ID_HIL_CONTROLS 91
#define MAVLINK_MSG_ID_HIL_CONTROLS_LEN 42
#define MAVLINK_MSG_ID_91_LEN 42
#define MAVLINK_MSG_ID_HIL_CONTROLS_CRC 63
#define MAVLINK_MSG_ID_91_CRC 63
#define MAVLINK_MESSAGE_INFO_HIL_CONTROLS
Typedefs
typedef struct __mavlink_hil_controls_t mavlink_hil_controls_t
Functions
static uint16_t mavlink_msg_hil_controls_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, float roll_ailerons, float pitch_elevator, float yaw_rudder, float throttle, float aux1, float aux2, float aux3, float aux4, uint8_t mode, uint8_t nav_mode)
Pack a hil_controls message.
static uint16_t mavlink_msg_hil_controls_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, float roll_ailerons, float pitch_elevator, float yaw_rudder, float throttle, float aux1, float aux2, float aux3, float aux4, uint8_t mode, uint8_t nav_mode)
Pack a hil_controls message on a channel.
static uint16_t mavlink_msg_hil_controls_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_hil_controls_t *hil_controls)
Encode a hil_controls struct.
static uint16_t mavlink_msg_hil_controls_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_hil_controls_t *hil_controls)
Encode a hil_controls struct on a channel.
static uint64_t mavlink_msg_hil_controls_get_time_usec (const mavlink_message_t *msg)
Send a hil_controls message.
static float mavlink_msg_hil_controls_get_roll_ailerons (const mavlink_message_t *msg)
Get field roll_ailerons from hil_controls message.
static float mavlink_msg_hil_controls_get_pitch_elevator (const mavlink_message_t *msg)
Get field pitch_elevator from hil_controls message.
static float mavlink_msg_hil_controls_get_yaw_rudder (const mavlink_message_t *msg)
Get field yaw_rudder from hil_controls message.
static float mavlink_msg_hil_controls_get_throttle (const mavlink_message_t *msg)
Get field throttle from hil_controls message.
static float mavlink_msg_hil_controls_get_aux1 (const mavlink_message_t *msg)
Get field aux1 from hil_controls message.
static float mavlink_msg_hil_controls_get_aux2 (const mavlink_message_t *msg)
Get field aux2 from hil_controls message.
static float mavlink_msg_hil_controls_get_aux3 (const mavlink_message_t *msg)
Get field aux3 from hil_controls message.
static float mavlink_msg_hil_controls_get_aux4 (const mavlink_message_t *msg)
Get field aux4 from hil_controls message.
static uint8_t mavlink_msg_hil_controls_get_mode (const mavlink_message_t *msg)
Get field mode from hil_controls message.
static uint8_t mavlink_msg_hil_controls_get_nav_mode (const mavlink_message_t *msg)
Get field nav_mode from hil_controls message.
static void mavlink_msg_hil_controls_decode (const mavlink_message_t *msg, mavlink_hil_controls_t *hil_controls)
Decode a hil_controls message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_HIL_CONTROLS
Value:
{ \
    "HIL_CONTROLS", \
    11, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_hil_controls_t, time_usec) }, \
         { "roll_ailerons", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_hil_controls_t, roll_ailerons) }, \
         { "pitch_elevator", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_hil_controls_t, pitch_elevator) }, \
         { "yaw_rudder", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_hil_controls_t, yaw_rudder) }, \
         { "throttle", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_hil_controls_t, throttle) }, \
         { "aux1", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_hil_controls_t, aux1) }, \
         { "aux2", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_hil_controls_t, aux2) }, \
         { "aux3", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_hil_controls_t, aux3) }, \
         { "aux4", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_hil_controls_t, aux4) }, \
         { "mode", NULL, MAVLINK_TYPE_UINT8_T, 0, 40, offsetof(mavlink_hil_controls_t, mode) }, \
         { "nav_mode", NULL, MAVLINK_TYPE_UINT8_T, 0, 41, offsetof(mavlink_hil_controls_t, nav_mode) }, \
         } \
}
Definition at line 28 of file mavlink_msg_hil_controls.h.
#define MAVLINK_MSG_ID_91_CRC 63
Definition at line 24 of file mavlink_msg_hil_controls.h.
#define MAVLINK_MSG_ID_91_LEN 42
Definition at line 21 of file mavlink_msg_hil_controls.h.
#define MAVLINK_MSG_ID_HIL_CONTROLS 91
Definition at line 3 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_pack(), and mavlink_msg_hil_controls_pack_chan().
#define MAVLINK_MSG_ID_HIL_CONTROLS_CRC 63
Definition at line 23 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_pack(), and mavlink_msg_hil_controls_pack_chan().
#define MAVLINK_MSG_ID_HIL_CONTROLS_LEN 42
Definition at line 20 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode(), mavlink_msg_hil_controls_pack(), and mavlink_msg_hil_controls_pack_chan().
Typedef Documentation
typedef struct __mavlink_hil_controls_t mavlink_hil_controls_t
Function Documentation
static void mavlink_msg_hil_controls_decode (const mavlink_message_t * msg, mavlink_hil_controls_t * hil_controls) inline static
Decode a hil_controls message into a struct.
Parameters
msg The message to decode
hil_controls C-struct to decode the message contents into
Definition at line 432 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_test_hil_controls().
static uint16_t mavlink_msg_hil_controls_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_hil_controls_t * hil_controls) inline static
Encode a hil_controls struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
hil_controls C-struct to read the message contents from
Definition at line 179 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_test_hil_controls().
static uint16_t mavlink_msg_hil_controls_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_hil_controls_t * hil_controls) inline static
Encode a hil_controls struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
hil_controls C-struct to read the message contents from
Definition at line 193 of file mavlink_msg_hil_controls.h.
static float mavlink_msg_hil_controls_get_aux1 (const mavlink_message_t * msg) inline static
Get field aux1 from hil_controls message.
Returns
Aux 1, -1 .. 1
Definition at line 371 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_aux2 (const mavlink_message_t * msg) inline static
Get field aux2 from hil_controls message.
Returns
Aux 2, -1 .. 1
Definition at line 381 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_aux3 (const mavlink_message_t * msg) inline static
Get field aux3 from hil_controls message.
Returns
Aux 3, -1 .. 1
Definition at line 391 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_aux4 (const mavlink_message_t * msg) inline static
Get field aux4 from hil_controls message.
Returns
Aux 4, -1 .. 1
Definition at line 401 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static uint8_t mavlink_msg_hil_controls_get_mode (const mavlink_message_t * msg) inline static
Get field mode from hil_controls message.
Returns
System mode (MAV_MODE)
Definition at line 411 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static uint8_t mavlink_msg_hil_controls_get_nav_mode (const mavlink_message_t * msg) inline static
Get field nav_mode from hil_controls message.
Returns
Navigation mode (MAV_NAV_MODE)
Definition at line 421 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_pitch_elevator (const mavlink_message_t * msg) inline static
Get field pitch_elevator from hil_controls message.
Returns
Control output -1 .. 1
Definition at line 341 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_roll_ailerons (const mavlink_message_t * msg) inline static
Get field roll_ailerons from hil_controls message.
Returns
Control output -1 .. 1
Definition at line 331 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_throttle (const mavlink_message_t * msg) inline static
Get field throttle from hil_controls message.
Returns
Throttle 0 .. 1
Definition at line 361 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static uint64_t mavlink_msg_hil_controls_get_time_usec (const mavlink_message_t * msg) inline static
Send a hil_controls message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
roll_ailerons Control output -1 .. 1
pitch_elevator Control output -1 .. 1
yaw_rudder Control output -1 .. 1
throttle Throttle 0 .. 1
aux1 Aux 1, -1 .. 1
aux2 Aux 2, -1 .. 1
aux3 Aux 3, -1 .. 1
aux4 Aux 4, -1 .. 1
mode System mode (MAV_MODE)
nav_mode Navigation mode (MAV_NAV_MODE) Get field time_usec from hil_controls message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 321 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static float mavlink_msg_hil_controls_get_yaw_rudder (const mavlink_message_t * msg) inline static
Get field yaw_rudder from hil_controls message.
Returns
Control output -1 .. 1
Definition at line 351 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_decode().
static uint16_t mavlink_msg_hil_controls_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, float roll_ailerons, float pitch_elevator, float yaw_rudder, float throttle, float aux1, float aux2, float aux3, float aux4, uint8_t mode, uint8_t nav_mode) inline static
Pack a hil_controls message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
roll_ailerons Control output -1 .. 1
pitch_elevator Control output -1 .. 1
yaw_rudder Control output -1 .. 1
throttle Throttle 0 .. 1
aux1 Aux 1, -1 .. 1
aux2 Aux 2, -1 .. 1
aux3 Aux 3, -1 .. 1
aux4 Aux 4, -1 .. 1
mode System mode (MAV_MODE)
nav_mode Navigation mode (MAV_NAV_MODE)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 65 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_encode(), and mavlink_test_hil_controls().
static uint16_t mavlink_msg_hil_controls_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, float roll_ailerons, float pitch_elevator, float yaw_rudder, float throttle, float aux1, float aux2, float aux3, float aux4, uint8_t mode, uint8_t nav_mode) inline static
Pack a hil_controls message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
roll_ailerons Control output -1 .. 1
pitch_elevator Control output -1 .. 1
yaw_rudder Control output -1 .. 1
throttle Throttle 0 .. 1
aux1 Aux 1, -1 .. 1
aux2 Aux 2, -1 .. 1
aux3 Aux 3, -1 .. 1
aux4 Aux 4, -1 .. 1
mode System mode (MAV_MODE)
nav_mode Navigation mode (MAV_NAV_MODE)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 127 of file mavlink_msg_hil_controls.h.
Referenced by mavlink_msg_hil_controls_encode_chan(), and mavlink_test_hil_controls().