APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_debug_vect.h File Reference
mavlink_msg_debug_vect.h File Reference
Classes
struct __mavlink_debug_vect_t
Macros
#define MAVLINK_MSG_ID_DEBUG_VECT 250
#define MAVLINK_MSG_ID_DEBUG_VECT_LEN 30
#define MAVLINK_MSG_ID_250_LEN 30
#define MAVLINK_MSG_ID_DEBUG_VECT_CRC 49
#define MAVLINK_MSG_ID_250_CRC 49
#define MAVLINK_MSG_DEBUG_VECT_FIELD_NAME_LEN 10
#define MAVLINK_MESSAGE_INFO_DEBUG_VECT
Typedefs
typedef struct __mavlink_debug_vect_t mavlink_debug_vect_t
Functions
static uint16_t mavlink_msg_debug_vect_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const char *name, uint64_t time_usec, float x, float y, float z)
Pack a debug_vect message.
static uint16_t mavlink_msg_debug_vect_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const char *name, uint64_t time_usec, float x, float y, float z)
Pack a debug_vect message on a channel.
static uint16_t mavlink_msg_debug_vect_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_debug_vect_t *debug_vect)
Encode a debug_vect struct.
static uint16_t mavlink_msg_debug_vect_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_debug_vect_t *debug_vect)
Encode a debug_vect struct on a channel.
static uint16_t mavlink_msg_debug_vect_get_name (const mavlink_message_t *msg, char *name)
Send a debug_vect message.
static uint64_t mavlink_msg_debug_vect_get_time_usec (const mavlink_message_t *msg)
Get field time_usec from debug_vect message.
static float mavlink_msg_debug_vect_get_x (const mavlink_message_t *msg)
Get field x from debug_vect message.
static float mavlink_msg_debug_vect_get_y (const mavlink_message_t *msg)
Get field y from debug_vect message.
static float mavlink_msg_debug_vect_get_z (const mavlink_message_t *msg)
Get field z from debug_vect message.
static void mavlink_msg_debug_vect_decode (const mavlink_message_t *msg, mavlink_debug_vect_t *debug_vect)
Decode a debug_vect message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DEBUG_VECT
Value:
{ \
    "DEBUG_VECT", \
    5, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_debug_vect_t, time_usec) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_debug_vect_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_debug_vect_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_debug_vect_t, z) }, \
         { "name", NULL, MAVLINK_TYPE_CHAR, 10, 20, offsetof(mavlink_debug_vect_t, name) }, \
         } \
}
Definition at line 22 of file mavlink_msg_debug_vect.h.
#define MAVLINK_MSG_DEBUG_VECT_FIELD_NAME_LEN 10
Definition at line 20 of file mavlink_msg_debug_vect.h.
#define MAVLINK_MSG_ID_250_CRC 49
Definition at line 18 of file mavlink_msg_debug_vect.h.
#define MAVLINK_MSG_ID_250_LEN 30
Definition at line 15 of file mavlink_msg_debug_vect.h.
#define MAVLINK_MSG_ID_DEBUG_VECT 250
Definition at line 3 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_pack(), and mavlink_msg_debug_vect_pack_chan().
#define MAVLINK_MSG_ID_DEBUG_VECT_CRC 49
Definition at line 17 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_pack(), and mavlink_msg_debug_vect_pack_chan().
#define MAVLINK_MSG_ID_DEBUG_VECT_LEN 30
Definition at line 14 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_decode(), mavlink_msg_debug_vect_pack(), and mavlink_msg_debug_vect_pack_chan().
Typedef Documentation
typedef struct __mavlink_debug_vect_t mavlink_debug_vect_t
Function Documentation
static void mavlink_msg_debug_vect_decode (const mavlink_message_t * msg, mavlink_debug_vect_t * debug_vect) inline static
Decode a debug_vect message into a struct.
Parameters
msg The message to decode
debug_vect C-struct to decode the message contents into
Definition at line 286 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_test_debug_vect().
static uint16_t mavlink_msg_debug_vect_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_debug_vect_t * debug_vect) inline static
Encode a debug_vect struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
debug_vect C-struct to read the message contents from
Definition at line 127 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_test_debug_vect().
static uint16_t mavlink_msg_debug_vect_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_debug_vect_t * debug_vect) inline static
Encode a debug_vect struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
debug_vect C-struct to read the message contents from
Definition at line 141 of file mavlink_msg_debug_vect.h.
static uint16_t mavlink_msg_debug_vect_get_name (const mavlink_message_t * msg, char * name) inline static
Send a debug_vect message.
Parameters
chan MAVLink channel to send the message
name Name
time_usec Timestamp
x x
y y
z z Get field name from debug_vect message
Returns
Name
Definition at line 235 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_decode().
static uint64_t mavlink_msg_debug_vect_get_time_usec (const mavlink_message_t * msg) inline static
Get field time_usec from debug_vect message.
Returns
Timestamp
Definition at line 245 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_decode().
static float mavlink_msg_debug_vect_get_x (const mavlink_message_t * msg) inline static
Get field x from debug_vect message.
Returns
x
Definition at line 255 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_decode().
static float mavlink_msg_debug_vect_get_y (const mavlink_message_t * msg) inline static
Get field y from debug_vect message.
Returns
y
Definition at line 265 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_decode().
static float mavlink_msg_debug_vect_get_z (const mavlink_message_t * msg) inline static
Get field z from debug_vect message.
Returns
z
Definition at line 275 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_decode().
static uint16_t mavlink_msg_debug_vect_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const char * name, uint64_t time_usec, float x, float y, float z) inline static
Pack a debug_vect message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
name Name
time_usec Timestamp
x x
y y
z z
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_encode(), and mavlink_test_debug_vect().
static uint16_t mavlink_msg_debug_vect_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const char * name, uint64_t time_usec, float x, float y, float z) inline static
Pack a debug_vect message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
name Name
time_usec Timestamp
x x
y y
z z
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 89 of file mavlink_msg_debug_vect.h.
Referenced by mavlink_msg_debug_vect_encode_chan(), and mavlink_test_debug_vect().