APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_command_ack.h File Reference
mavlink_msg_command_ack.h File Reference
Classes
struct __mavlink_command_ack_t
Macros
#define MAVLINK_MSG_ID_COMMAND_ACK 77
#define MAVLINK_MSG_ID_COMMAND_ACK_LEN 3
#define MAVLINK_MSG_ID_77_LEN 3
#define MAVLINK_MSG_ID_COMMAND_ACK_CRC 143
#define MAVLINK_MSG_ID_77_CRC 143
#define MAVLINK_MESSAGE_INFO_COMMAND_ACK
Typedefs
typedef struct __mavlink_command_ack_t mavlink_command_ack_t
Functions
static uint16_t mavlink_msg_command_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t command, uint8_t result)
Pack a command_ack message.
static uint16_t mavlink_msg_command_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t command, uint8_t result)
Pack a command_ack message on a channel.
static uint16_t mavlink_msg_command_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_command_ack_t *command_ack)
Encode a command_ack struct.
static uint16_t mavlink_msg_command_ack_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_command_ack_t *command_ack)
Encode a command_ack struct on a channel.
static uint16_t mavlink_msg_command_ack_get_command (const mavlink_message_t *msg)
Send a command_ack message.
static uint8_t mavlink_msg_command_ack_get_result (const mavlink_message_t *msg)
Get field result from command_ack message.
static void mavlink_msg_command_ack_decode (const mavlink_message_t *msg, mavlink_command_ack_t *command_ack)
Decode a command_ack message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_COMMAND_ACK
Value:
{ \
    "COMMAND_ACK", \
    2, \
    {  { "command", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_command_ack_t, command) }, \
         { "result", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_command_ack_t, result) }, \
         } \
}
Definition at line 19 of file mavlink_msg_command_ack.h.
#define MAVLINK_MSG_ID_77_CRC 143
Definition at line 15 of file mavlink_msg_command_ack.h.
#define MAVLINK_MSG_ID_77_LEN 3
Definition at line 12 of file mavlink_msg_command_ack.h.
#define MAVLINK_MSG_ID_COMMAND_ACK 77
Definition at line 3 of file mavlink_msg_command_ack.h.
Referenced by _snoop(), mavlink_msg_command_ack_pack(), and mavlink_msg_command_ack_pack_chan().
#define MAVLINK_MSG_ID_COMMAND_ACK_CRC 143
Definition at line 14 of file mavlink_msg_command_ack.h.
Referenced by mavlink_msg_command_ack_pack(), and mavlink_msg_command_ack_pack_chan().
#define MAVLINK_MSG_ID_COMMAND_ACK_LEN 3
Definition at line 11 of file mavlink_msg_command_ack.h.
Referenced by mavlink_msg_command_ack_decode(), mavlink_msg_command_ack_pack(), and mavlink_msg_command_ack_pack_chan().
Typedef Documentation
typedef struct __mavlink_command_ack_t mavlink_command_ack_t
Function Documentation
static void mavlink_msg_command_ack_decode (const mavlink_message_t * msg, mavlink_command_ack_t * command_ack) inline static
Decode a command_ack message into a struct.
Parameters
msg The message to decode
command_ack C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_command_ack.h.
Referenced by mavlink_test_command_ack().
static uint16_t mavlink_msg_command_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_command_ack_t * command_ack) inline static
Encode a command_ack struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
command_ack C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_command_ack.h.
Referenced by mavlink_test_command_ack().
static uint16_t mavlink_msg_command_ack_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_command_ack_t * command_ack) inline static
Encode a command_ack struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
command_ack C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_command_ack.h.
static uint16_t mavlink_msg_command_ack_get_command (const mavlink_message_t * msg) inline static
Send a command_ack message.
Parameters
chan MAVLink channel to send the message
command Command ID, as defined by MAV_CMD enum.
result See MAV_RESULT enum Get field command from command_ack message
Returns
Command ID, as defined by MAV_CMD enum.
Definition at line 204 of file mavlink_msg_command_ack.h.
Referenced by mavlink_msg_command_ack_decode().
static uint8_t mavlink_msg_command_ack_get_result (const mavlink_message_t * msg) inline static
Get field result from command_ack message.
Returns
See MAV_RESULT enum
Definition at line 214 of file mavlink_msg_command_ack.h.
Referenced by mavlink_msg_command_ack_decode().
static uint16_t mavlink_msg_command_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t command, uint8_t result) inline static
Pack a command_ack message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
command Command ID, as defined by MAV_CMD enum.
result See MAV_RESULT enum
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_command_ack.h.
Referenced by mavlink_msg_command_ack_encode(), and mavlink_test_command_ack().
static uint16_t mavlink_msg_command_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t command, uint8_t result) inline static
Pack a command_ack message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
command Command ID, as defined by MAV_CMD enum.
result See MAV_RESULT enum
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_command_ack.h.
Referenced by mavlink_msg_command_ack_encode_chan(), and mavlink_test_command_ack().