APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_sensor_offsets.h File Reference
mavlink_msg_sensor_offsets.h File Reference
Classes
struct __mavlink_sensor_offsets_t
Macros
#define MAVLINK_MSG_ID_SENSOR_OFFSETS 150
#define MAVLINK_MSG_ID_SENSOR_OFFSETS_LEN 42
#define MAVLINK_MSG_ID_150_LEN 42
#define MAVLINK_MSG_ID_SENSOR_OFFSETS_CRC 134
#define MAVLINK_MSG_ID_150_CRC 134
#define MAVLINK_MESSAGE_INFO_SENSOR_OFFSETS
Typedefs
typedef struct __mavlink_sensor_offsets_t mavlink_sensor_offsets_t
Functions
static uint16_t mavlink_msg_sensor_offsets_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z, float mag_declination, int32_t raw_press, int32_t raw_temp, float gyro_cal_x, float gyro_cal_y, float gyro_cal_z, float accel_cal_x, float accel_cal_y, float accel_cal_z)
Pack a sensor_offsets message.
static uint16_t mavlink_msg_sensor_offsets_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z, float mag_declination, int32_t raw_press, int32_t raw_temp, float gyro_cal_x, float gyro_cal_y, float gyro_cal_z, float accel_cal_x, float accel_cal_y, float accel_cal_z)
Pack a sensor_offsets message on a channel.
static uint16_t mavlink_msg_sensor_offsets_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_sensor_offsets_t *sensor_offsets)
Encode a sensor_offsets struct.
static uint16_t mavlink_msg_sensor_offsets_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_sensor_offsets_t *sensor_offsets)
Encode a sensor_offsets struct on a channel.
static int16_t mavlink_msg_sensor_offsets_get_mag_ofs_x (const mavlink_message_t *msg)
Send a sensor_offsets message.
static int16_t mavlink_msg_sensor_offsets_get_mag_ofs_y (const mavlink_message_t *msg)
Get field mag_ofs_y from sensor_offsets message.
static int16_t mavlink_msg_sensor_offsets_get_mag_ofs_z (const mavlink_message_t *msg)
Get field mag_ofs_z from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_mag_declination (const mavlink_message_t *msg)
Get field mag_declination from sensor_offsets message.
static int32_t mavlink_msg_sensor_offsets_get_raw_press (const mavlink_message_t *msg)
Get field raw_press from sensor_offsets message.
static int32_t mavlink_msg_sensor_offsets_get_raw_temp (const mavlink_message_t *msg)
Get field raw_temp from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_gyro_cal_x (const mavlink_message_t *msg)
Get field gyro_cal_x from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_gyro_cal_y (const mavlink_message_t *msg)
Get field gyro_cal_y from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_gyro_cal_z (const mavlink_message_t *msg)
Get field gyro_cal_z from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_accel_cal_x (const mavlink_message_t *msg)
Get field accel_cal_x from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_accel_cal_y (const mavlink_message_t *msg)
Get field accel_cal_y from sensor_offsets message.
static float mavlink_msg_sensor_offsets_get_accel_cal_z (const mavlink_message_t *msg)
Get field accel_cal_z from sensor_offsets message.
static void mavlink_msg_sensor_offsets_decode (const mavlink_message_t *msg, mavlink_sensor_offsets_t *sensor_offsets)
Decode a sensor_offsets message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SENSOR_OFFSETS
Value:
{ \
    "SENSOR_OFFSETS", \
    12, \
    {  { "mag_declination", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_sensor_offsets_t, mag_declination) }, \
         { "raw_press", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_sensor_offsets_t, raw_press) }, \
         { "raw_temp", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_sensor_offsets_t, raw_temp) }, \
         { "gyro_cal_x", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_sensor_offsets_t, gyro_cal_x) }, \
         { "gyro_cal_y", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_sensor_offsets_t, gyro_cal_y) }, \
         { "gyro_cal_z", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_sensor_offsets_t, gyro_cal_z) }, \
         { "accel_cal_x", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_sensor_offsets_t, accel_cal_x) }, \
         { "accel_cal_y", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_sensor_offsets_t, accel_cal_y) }, \
         { "accel_cal_z", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_sensor_offsets_t, accel_cal_z) }, \
         { "mag_ofs_x", NULL, MAVLINK_TYPE_INT16_T, 0, 36, offsetof(mavlink_sensor_offsets_t, mag_ofs_x) }, \
         { "mag_ofs_y", NULL, MAVLINK_TYPE_INT16_T, 0, 38, offsetof(mavlink_sensor_offsets_t, mag_ofs_y) }, \
         { "mag_ofs_z", NULL, MAVLINK_TYPE_INT16_T, 0, 40, offsetof(mavlink_sensor_offsets_t, mag_ofs_z) }, \
         } \
}
Definition at line 29 of file mavlink_msg_sensor_offsets.h.
#define MAVLINK_MSG_ID_150_CRC 134
Definition at line 25 of file mavlink_msg_sensor_offsets.h.
#define MAVLINK_MSG_ID_150_LEN 42
Definition at line 22 of file mavlink_msg_sensor_offsets.h.
#define MAVLINK_MSG_ID_SENSOR_OFFSETS 150
Definition at line 3 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_pack(), and mavlink_msg_sensor_offsets_pack_chan().
#define MAVLINK_MSG_ID_SENSOR_OFFSETS_CRC 134
Definition at line 24 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_pack(), and mavlink_msg_sensor_offsets_pack_chan().
#define MAVLINK_MSG_ID_SENSOR_OFFSETS_LEN 42
Definition at line 21 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode(), mavlink_msg_sensor_offsets_pack(), and mavlink_msg_sensor_offsets_pack_chan().
Typedef Documentation
typedef struct __mavlink_sensor_offsets_t mavlink_sensor_offsets_t
Function Documentation
static void mavlink_msg_sensor_offsets_decode (const mavlink_message_t * msg, mavlink_sensor_offsets_t * sensor_offsets) inline static
Decode a sensor_offsets message into a struct.
Parameters
msg The message to decode
sensor_offsets C-struct to decode the message contents into
Definition at line 455 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_test_sensor_offsets().
static uint16_t mavlink_msg_sensor_offsets_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_sensor_offsets_t * sensor_offsets) inline static
Encode a sensor_offsets struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
sensor_offsets C-struct to read the message contents from
Definition at line 187 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_test_sensor_offsets().
static uint16_t mavlink_msg_sensor_offsets_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_sensor_offsets_t * sensor_offsets) inline static
Encode a sensor_offsets struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
sensor_offsets C-struct to read the message contents from
Definition at line 201 of file mavlink_msg_sensor_offsets.h.
static float mavlink_msg_sensor_offsets_get_accel_cal_x (const mavlink_message_t * msg) inline static
Get field accel_cal_x from sensor_offsets message.
Returns
accel X calibration
Definition at line 424 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static float mavlink_msg_sensor_offsets_get_accel_cal_y (const mavlink_message_t * msg) inline static
Get field accel_cal_y from sensor_offsets message.
Returns
accel Y calibration
Definition at line 434 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static float mavlink_msg_sensor_offsets_get_accel_cal_z (const mavlink_message_t * msg) inline static
Get field accel_cal_z from sensor_offsets message.
Returns
accel Z calibration
Definition at line 444 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static float mavlink_msg_sensor_offsets_get_gyro_cal_x (const mavlink_message_t * msg) inline static
Get field gyro_cal_x from sensor_offsets message.
Returns
gyro X calibration
Definition at line 394 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static float mavlink_msg_sensor_offsets_get_gyro_cal_y (const mavlink_message_t * msg) inline static
Get field gyro_cal_y from sensor_offsets message.
Returns
gyro Y calibration
Definition at line 404 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static float mavlink_msg_sensor_offsets_get_gyro_cal_z (const mavlink_message_t * msg) inline static
Get field gyro_cal_z from sensor_offsets message.
Returns
gyro Z calibration
Definition at line 414 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static float mavlink_msg_sensor_offsets_get_mag_declination (const mavlink_message_t * msg) inline static
Get field mag_declination from sensor_offsets message.
Returns
magnetic declination (radians)
Definition at line 364 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static int16_t mavlink_msg_sensor_offsets_get_mag_ofs_x (const mavlink_message_t * msg) inline static
Send a sensor_offsets message.
Parameters
chan MAVLink channel to send the message
mag_ofs_x magnetometer X offset
mag_ofs_y magnetometer Y offset
mag_ofs_z magnetometer Z offset
mag_declination magnetic declination (radians)
raw_press raw pressure from barometer
raw_temp raw temperature from barometer
gyro_cal_x gyro X calibration
gyro_cal_y gyro Y calibration
gyro_cal_z gyro Z calibration
accel_cal_x accel X calibration
accel_cal_y accel Y calibration
accel_cal_z accel Z calibration Get field mag_ofs_x from sensor_offsets message
Returns
magnetometer X offset
Definition at line 334 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static int16_t mavlink_msg_sensor_offsets_get_mag_ofs_y (const mavlink_message_t * msg) inline static
Get field mag_ofs_y from sensor_offsets message.
Returns
magnetometer Y offset
Definition at line 344 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static int16_t mavlink_msg_sensor_offsets_get_mag_ofs_z (const mavlink_message_t * msg) inline static
Get field mag_ofs_z from sensor_offsets message.
Returns
magnetometer Z offset
Definition at line 354 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static int32_t mavlink_msg_sensor_offsets_get_raw_press (const mavlink_message_t * msg) inline static
Get field raw_press from sensor_offsets message.
Returns
raw pressure from barometer
Definition at line 374 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static int32_t mavlink_msg_sensor_offsets_get_raw_temp (const mavlink_message_t * msg) inline static
Get field raw_temp from sensor_offsets message.
Returns
raw temperature from barometer
Definition at line 384 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_decode().
static uint16_t mavlink_msg_sensor_offsets_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z, float mag_declination, int32_t raw_press, int32_t raw_temp, float gyro_cal_x, float gyro_cal_y, float gyro_cal_z, float accel_cal_x, float accel_cal_y, float accel_cal_z) inline static
Pack a sensor_offsets message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mag_ofs_x magnetometer X offset
mag_ofs_y magnetometer Y offset
mag_ofs_z magnetometer Z offset
mag_declination magnetic declination (radians)
raw_press raw pressure from barometer
raw_temp raw temperature from barometer
gyro_cal_x gyro X calibration
gyro_cal_y gyro Y calibration
gyro_cal_z gyro Z calibration
accel_cal_x accel X calibration
accel_cal_y accel Y calibration
accel_cal_z accel Z calibration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 68 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_encode(), and mavlink_test_sensor_offsets().
static uint16_t mavlink_msg_sensor_offsets_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z, float mag_declination, int32_t raw_press, int32_t raw_temp, float gyro_cal_x, float gyro_cal_y, float gyro_cal_z, float accel_cal_x, float accel_cal_y, float accel_cal_z) inline static
Pack a sensor_offsets message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mag_ofs_x magnetometer X offset
mag_ofs_y magnetometer Y offset
mag_ofs_z magnetometer Z offset
mag_declination magnetic declination (radians)
raw_press raw pressure from barometer
raw_temp raw temperature from barometer
gyro_cal_x gyro X calibration
gyro_cal_y gyro Y calibration
gyro_cal_z gyro Z calibration
accel_cal_x accel X calibration
accel_cal_y accel Y calibration
accel_cal_z accel Z calibration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 133 of file mavlink_msg_sensor_offsets.h.
Referenced by mavlink_msg_sensor_offsets_encode_chan(), and mavlink_test_sensor_offsets().