APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_set_position_target_local_ned.h File Reference
mavlink_msg_set_position_target_local_ned.h File Reference
Classes
struct __mavlink_set_position_target_local_ned_t
Macros
#define MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED 84
#define MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED_LEN 53
#define MAVLINK_MSG_ID_84_LEN 53
#define MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED_CRC 143
#define MAVLINK_MSG_ID_84_CRC 143
#define MAVLINK_MESSAGE_INFO_SET_POSITION_TARGET_LOCAL_NED
Typedefs
typedef struct __mavlink_set_position_target_local_ned_t mavlink_set_position_target_local_ned_t
Functions
static uint16_t mavlink_msg_set_position_target_local_ned_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t target_system, uint8_t target_component, uint8_t coordinate_frame, uint16_t type_mask, float x, float y, float z, float vx, float vy, float vz, float afx, float afy, float afz, float yaw, float yaw_rate)
Pack a set_position_target_local_ned message.
static uint16_t mavlink_msg_set_position_target_local_ned_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t target_system, uint8_t target_component, uint8_t coordinate_frame, uint16_t type_mask, float x, float y, float z, float vx, float vy, float vz, float afx, float afy, float afz, float yaw, float yaw_rate)
Pack a set_position_target_local_ned message on a channel.
static uint16_t mavlink_msg_set_position_target_local_ned_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_set_position_target_local_ned_t *set_position_target_local_ned)
Encode a set_position_target_local_ned struct.
static uint16_t mavlink_msg_set_position_target_local_ned_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_set_position_target_local_ned_t *set_position_target_local_ned)
Encode a set_position_target_local_ned struct on a channel.
static uint32_t mavlink_msg_set_position_target_local_ned_get_time_boot_ms (const mavlink_message_t *msg)
Send a set_position_target_local_ned message.
static uint8_t mavlink_msg_set_position_target_local_ned_get_target_system (const mavlink_message_t *msg)
Get field target_system from set_position_target_local_ned message.
static uint8_t mavlink_msg_set_position_target_local_ned_get_target_component (const mavlink_message_t *msg)
Get field target_component from set_position_target_local_ned message.
static uint8_t mavlink_msg_set_position_target_local_ned_get_coordinate_frame (const mavlink_message_t *msg)
Get field coordinate_frame from set_position_target_local_ned message.
static uint16_t mavlink_msg_set_position_target_local_ned_get_type_mask (const mavlink_message_t *msg)
Get field type_mask from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_x (const mavlink_message_t *msg)
Get field x from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_y (const mavlink_message_t *msg)
Get field y from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_z (const mavlink_message_t *msg)
Get field z from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_vx (const mavlink_message_t *msg)
Get field vx from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_vy (const mavlink_message_t *msg)
Get field vy from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_vz (const mavlink_message_t *msg)
Get field vz from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_afx (const mavlink_message_t *msg)
Get field afx from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_afy (const mavlink_message_t *msg)
Get field afy from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_afz (const mavlink_message_t *msg)
Get field afz from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_yaw (const mavlink_message_t *msg)
Get field yaw from set_position_target_local_ned message.
static float mavlink_msg_set_position_target_local_ned_get_yaw_rate (const mavlink_message_t *msg)
Get field yaw_rate from set_position_target_local_ned message.
static void mavlink_msg_set_position_target_local_ned_decode (const mavlink_message_t *msg, mavlink_set_position_target_local_ned_t *set_position_target_local_ned)
Decode a set_position_target_local_ned message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SET_POSITION_TARGET_LOCAL_NED
Value:
{ \
    "SET_POSITION_TARGET_LOCAL_NED", \
    16, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_set_position_target_local_ned_t, time_boot_ms) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_set_position_target_local_ned_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_set_position_target_local_ned_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_set_position_target_local_ned_t, z) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_set_position_target_local_ned_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_set_position_target_local_ned_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_set_position_target_local_ned_t, vz) }, \
         { "afx", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_set_position_target_local_ned_t, afx) }, \
         { "afy", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_set_position_target_local_ned_t, afy) }, \
         { "afz", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_set_position_target_local_ned_t, afz) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 40, offsetof(mavlink_set_position_target_local_ned_t, yaw) }, \
         { "yaw_rate", NULL, MAVLINK_TYPE_FLOAT, 0, 44, offsetof(mavlink_set_position_target_local_ned_t, yaw_rate) }, \
         { "type_mask", NULL, MAVLINK_TYPE_UINT16_T, 0, 48, offsetof(mavlink_set_position_target_local_ned_t, type_mask) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 50, offsetof(mavlink_set_position_target_local_ned_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 51, offsetof(mavlink_set_position_target_local_ned_t, target_component) }, \
         { "coordinate_frame", NULL, MAVLINK_TYPE_UINT8_T, 0, 52, offsetof(mavlink_set_position_target_local_ned_t, coordinate_frame) }, \
         } \
}
Definition at line 33 of file mavlink_msg_set_position_target_local_ned.h.
#define MAVLINK_MSG_ID_84_CRC 143
Definition at line 29 of file mavlink_msg_set_position_target_local_ned.h.
#define MAVLINK_MSG_ID_84_LEN 53
Definition at line 26 of file mavlink_msg_set_position_target_local_ned.h.
#define MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED 84
Definition at line 3 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_set_position_target_local_ned_pack(), and mavlink_msg_set_position_target_local_ned_pack_chan().
#define MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED_CRC 143
Definition at line 28 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_pack(), and mavlink_msg_set_position_target_local_ned_pack_chan().
#define MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED_LEN 53
Definition at line 25 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode(), mavlink_msg_set_position_target_local_ned_pack(), and mavlink_msg_set_position_target_local_ned_pack_chan().
Typedef Documentation
typedef struct __mavlink_set_position_target_local_ned_t mavlink_set_position_target_local_ned_t
Function Documentation
static void mavlink_msg_set_position_target_local_ned_decode (const mavlink_message_t * msg, mavlink_set_position_target_local_ned_t * set_position_target_local_ned) inline static
Decode a set_position_target_local_ned message into a struct.
Parameters
msg The message to decode
set_position_target_local_ned C-struct to decode the message contents into
Definition at line 547 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_test_set_position_target_local_ned().
static uint16_t mavlink_msg_set_position_target_local_ned_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_set_position_target_local_ned_t * set_position_target_local_ned) inline static
Encode a set_position_target_local_ned struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
set_position_target_local_ned C-struct to read the message contents from
Definition at line 219 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_test_set_position_target_local_ned().
static uint16_t mavlink_msg_set_position_target_local_ned_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_set_position_target_local_ned_t * set_position_target_local_ned) inline static
Encode a set_position_target_local_ned struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
set_position_target_local_ned C-struct to read the message contents from
Definition at line 233 of file mavlink_msg_set_position_target_local_ned.h.
static float mavlink_msg_set_position_target_local_ned_get_afx (const mavlink_message_t * msg) inline static
Get field afx from set_position_target_local_ned message.
Returns
X acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
Definition at line 496 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_afy (const mavlink_message_t * msg) inline static
Get field afy from set_position_target_local_ned message.
Returns
Y acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
Definition at line 506 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_afz (const mavlink_message_t * msg) inline static
Get field afz from set_position_target_local_ned message.
Returns
Z acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
Definition at line 516 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static uint8_t mavlink_msg_set_position_target_local_ned_get_coordinate_frame (const mavlink_message_t * msg) inline static
Get field coordinate_frame from set_position_target_local_ned message.
Returns
Valid options are: MAV_FRAME_LOCAL_NED = 1, MAV_FRAME_LOCAL_OFFSET_NED = 7, MAV_FRAME_BODY_NED = 8, MAV_FRAME_BODY_OFFSET_NED = 9
Definition at line 416 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static uint8_t mavlink_msg_set_position_target_local_ned_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from set_position_target_local_ned message.
Returns
Component ID
Definition at line 406 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_set_position_target_local_ned_decode().
static uint8_t mavlink_msg_set_position_target_local_ned_get_target_system (const mavlink_message_t * msg) inline static
Get field target_system from set_position_target_local_ned message.
Returns
System ID
Definition at line 396 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_set_position_target_local_ned_decode().
static uint32_t mavlink_msg_set_position_target_local_ned_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a set_position_target_local_ned message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp in milliseconds since system boot
target_system System ID
target_component Component ID
coordinate_frame Valid options are: MAV_FRAME_LOCAL_NED = 1, MAV_FRAME_LOCAL_OFFSET_NED = 7, MAV_FRAME_BODY_NED = 8, MAV_FRAME_BODY_OFFSET_NED = 9
type_mask Bitmask to indicate which dimensions should be ignored by the vehicle: a value of 0b0000000000000000 or 0b0000001000000000 indicates that none of the setpoint dimensions should be ignored. If bit 10 is set the floats afx afy afz should be interpreted as force instead of acceleration. Mapping: bit 1: x, bit 2: y, bit 3: z, bit 4: vx, bit 5: vy, bit 6: vz, bit 7: ax, bit 8: ay, bit 9: az, bit 10: is force setpoint, bit 11: yaw, bit 12: yaw rate
x X Position in NED frame in meters
y Y Position in NED frame in meters
z Z Position in NED frame in meters (note, altitude is negative in NED)
vx X velocity in NED frame in meter / s
vy Y velocity in NED frame in meter / s
vz Z velocity in NED frame in meter / s
afx X acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
afy Y acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
afz Z acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
yaw yaw setpoint in rad
yaw_rate yaw rate setpoint in rad/s Get field time_boot_ms from set_position_target_local_ned message
Returns
Timestamp in milliseconds since system boot
Definition at line 386 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static uint16_t mavlink_msg_set_position_target_local_ned_get_type_mask (const mavlink_message_t * msg) inline static
Get field type_mask from set_position_target_local_ned message.
Returns
Bitmask to indicate which dimensions should be ignored by the vehicle: a value of 0b0000000000000000 or 0b0000001000000000 indicates that none of the setpoint dimensions should be ignored. If bit 10 is set the floats afx afy afz should be interpreted as force instead of acceleration. Mapping: bit 1: x, bit 2: y, bit 3: z, bit 4: vx, bit 5: vy, bit 6: vz, bit 7: ax, bit 8: ay, bit 9: az, bit 10: is force setpoint, bit 11: yaw, bit 12: yaw rate
Definition at line 426 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_vx (const mavlink_message_t * msg) inline static
Get field vx from set_position_target_local_ned message.
Returns
X velocity in NED frame in meter / s
Definition at line 466 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_vy (const mavlink_message_t * msg) inline static
Get field vy from set_position_target_local_ned message.
Returns
Y velocity in NED frame in meter / s
Definition at line 476 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_vz (const mavlink_message_t * msg) inline static
Get field vz from set_position_target_local_ned message.
Returns
Z velocity in NED frame in meter / s
Definition at line 486 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_x (const mavlink_message_t * msg) inline static
Get field x from set_position_target_local_ned message.
Returns
X Position in NED frame in meters
Definition at line 436 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_y (const mavlink_message_t * msg) inline static
Get field y from set_position_target_local_ned message.
Returns
Y Position in NED frame in meters
Definition at line 446 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from set_position_target_local_ned message.
Returns
yaw setpoint in rad
Definition at line 526 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_yaw_rate (const mavlink_message_t * msg) inline static
Get field yaw_rate from set_position_target_local_ned message.
Returns
yaw rate setpoint in rad/s
Definition at line 536 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static float mavlink_msg_set_position_target_local_ned_get_z (const mavlink_message_t * msg) inline static
Get field z from set_position_target_local_ned message.
Returns
Z Position in NED frame in meters (note, altitude is negative in NED)
Definition at line 456 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_decode().
static uint16_t mavlink_msg_set_position_target_local_ned_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t target_system, uint8_t target_component, uint8_t coordinate_frame, uint16_t type_mask, float x, float y, float z, float vx, float vy, float vz, float afx, float afy, float afz, float yaw, float yaw_rate) inline static
Pack a set_position_target_local_ned message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp in milliseconds since system boot
target_system System ID
target_component Component ID
coordinate_frame Valid options are: MAV_FRAME_LOCAL_NED = 1, MAV_FRAME_LOCAL_OFFSET_NED = 7, MAV_FRAME_BODY_NED = 8, MAV_FRAME_BODY_OFFSET_NED = 9
type_mask Bitmask to indicate which dimensions should be ignored by the vehicle: a value of 0b0000000000000000 or 0b0000001000000000 indicates that none of the setpoint dimensions should be ignored. If bit 10 is set the floats afx afy afz should be interpreted as force instead of acceleration. Mapping: bit 1: x, bit 2: y, bit 3: z, bit 4: vx, bit 5: vy, bit 6: vz, bit 7: ax, bit 8: ay, bit 9: az, bit 10: is force setpoint, bit 11: yaw, bit 12: yaw rate
x X Position in NED frame in meters
y Y Position in NED frame in meters
z Z Position in NED frame in meters (note, altitude is negative in NED)
vx X velocity in NED frame in meter / s
vy Y velocity in NED frame in meter / s
vz Z velocity in NED frame in meter / s
afx X acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
afy Y acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
afz Z acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
yaw yaw setpoint in rad
yaw_rate yaw rate setpoint in rad/s
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 80 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_encode(), and mavlink_test_set_position_target_local_ned().
static uint16_t mavlink_msg_set_position_target_local_ned_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t target_system, uint8_t target_component, uint8_t coordinate_frame, uint16_t type_mask, float x, float y, float z, float vx, float vy, float vz, float afx, float afy, float afz, float yaw, float yaw_rate) inline static
Pack a set_position_target_local_ned message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp in milliseconds since system boot
target_system System ID
target_component Component ID
coordinate_frame Valid options are: MAV_FRAME_LOCAL_NED = 1, MAV_FRAME_LOCAL_OFFSET_NED = 7, MAV_FRAME_BODY_NED = 8, MAV_FRAME_BODY_OFFSET_NED = 9
type_mask Bitmask to indicate which dimensions should be ignored by the vehicle: a value of 0b0000000000000000 or 0b0000001000000000 indicates that none of the setpoint dimensions should be ignored. If bit 10 is set the floats afx afy afz should be interpreted as force instead of acceleration. Mapping: bit 1: x, bit 2: y, bit 3: z, bit 4: vx, bit 5: vy, bit 6: vz, bit 7: ax, bit 8: ay, bit 9: az, bit 10: is force setpoint, bit 11: yaw, bit 12: yaw rate
x X Position in NED frame in meters
y Y Position in NED frame in meters
z Z Position in NED frame in meters (note, altitude is negative in NED)
vx X velocity in NED frame in meter / s
vy Y velocity in NED frame in meter / s
vz Z velocity in NED frame in meter / s
afx X acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
afy Y acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
afz Z acceleration or force (if bit 10 of type_mask is set) in NED frame in meter / s^2 or N
yaw yaw setpoint in rad
yaw_rate yaw rate setpoint in rad/s
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 157 of file mavlink_msg_set_position_target_local_ned.h.
Referenced by mavlink_msg_set_position_target_local_ned_encode_chan(), and mavlink_test_set_position_target_local_ned().