APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_global_position_int.h File Reference
mavlink_msg_global_position_int.h File Reference
Classes
struct __mavlink_global_position_int_t
Macros
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT 33
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT_LEN 28
#define MAVLINK_MSG_ID_33_LEN 28
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT_CRC 104
#define MAVLINK_MSG_ID_33_CRC 104
#define MAVLINK_MESSAGE_INFO_GLOBAL_POSITION_INT
Typedefs
typedef struct __mavlink_global_position_int_t mavlink_global_position_int_t
Functions
static uint16_t mavlink_msg_global_position_int_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, int32_t lat, int32_t lon, int32_t alt, int32_t relative_alt, int16_t vx, int16_t vy, int16_t vz, uint16_t hdg)
Pack a global_position_int message.
static uint16_t mavlink_msg_global_position_int_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, int32_t lat, int32_t lon, int32_t alt, int32_t relative_alt, int16_t vx, int16_t vy, int16_t vz, uint16_t hdg)
Pack a global_position_int message on a channel.
static uint16_t mavlink_msg_global_position_int_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_global_position_int_t *global_position_int)
Encode a global_position_int struct.
static uint16_t mavlink_msg_global_position_int_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_global_position_int_t *global_position_int)
Encode a global_position_int struct on a channel.
static uint32_t mavlink_msg_global_position_int_get_time_boot_ms (const mavlink_message_t *msg)
Send a global_position_int message.
static int32_t mavlink_msg_global_position_int_get_lat (const mavlink_message_t *msg)
Get field lat from global_position_int message.
static int32_t mavlink_msg_global_position_int_get_lon (const mavlink_message_t *msg)
Get field lon from global_position_int message.
static int32_t mavlink_msg_global_position_int_get_alt (const mavlink_message_t *msg)
Get field alt from global_position_int message.
static int32_t mavlink_msg_global_position_int_get_relative_alt (const mavlink_message_t *msg)
Get field relative_alt from global_position_int message.
static int16_t mavlink_msg_global_position_int_get_vx (const mavlink_message_t *msg)
Get field vx from global_position_int message.
static int16_t mavlink_msg_global_position_int_get_vy (const mavlink_message_t *msg)
Get field vy from global_position_int message.
static int16_t mavlink_msg_global_position_int_get_vz (const mavlink_message_t *msg)
Get field vz from global_position_int message.
static uint16_t mavlink_msg_global_position_int_get_hdg (const mavlink_message_t *msg)
Get field hdg from global_position_int message.
static void mavlink_msg_global_position_int_decode (const mavlink_message_t *msg, mavlink_global_position_int_t *global_position_int)
Decode a global_position_int message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GLOBAL_POSITION_INT
Value:
{ \
    "GLOBAL_POSITION_INT", \
    9, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_global_position_int_t, time_boot_ms) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_global_position_int_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_global_position_int_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_INT32_T, 0, 12, offsetof(mavlink_global_position_int_t, alt) }, \
         { "relative_alt", NULL, MAVLINK_TYPE_INT32_T, 0, 16, offsetof(mavlink_global_position_int_t, relative_alt) }, \
         { "vx", NULL, MAVLINK_TYPE_INT16_T, 0, 20, offsetof(mavlink_global_position_int_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_INT16_T, 0, 22, offsetof(mavlink_global_position_int_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_INT16_T, 0, 24, offsetof(mavlink_global_position_int_t, vz) }, \
         { "hdg", NULL, MAVLINK_TYPE_UINT16_T, 0, 26, offsetof(mavlink_global_position_int_t, hdg) }, \
         } \
}
Definition at line 26 of file mavlink_msg_global_position_int.h.
#define MAVLINK_MSG_ID_33_CRC 104
Definition at line 22 of file mavlink_msg_global_position_int.h.
#define MAVLINK_MSG_ID_33_LEN 28
Definition at line 19 of file mavlink_msg_global_position_int.h.
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT 33
Definition at line 3 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_pack(), and mavlink_msg_global_position_int_pack_chan().
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT_CRC 104
Definition at line 21 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_pack(), and mavlink_msg_global_position_int_pack_chan().
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT_LEN 28
Definition at line 18 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode(), mavlink_msg_global_position_int_pack(), and mavlink_msg_global_position_int_pack_chan().
Typedef Documentation
typedef struct __mavlink_global_position_int_t mavlink_global_position_int_t
Function Documentation
static void mavlink_msg_global_position_int_decode (const mavlink_message_t * msg, mavlink_global_position_int_t * global_position_int) inline static
Decode a global_position_int message into a struct.
Parameters
msg The message to decode
global_position_int C-struct to decode the message contents into
Definition at line 386 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_test_global_position_int().
static uint16_t mavlink_msg_global_position_int_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_global_position_int_t * global_position_int) inline static
Encode a global_position_int struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
global_position_int C-struct to read the message contents from
Definition at line 163 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_test_global_position_int().
static uint16_t mavlink_msg_global_position_int_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_global_position_int_t * global_position_int) inline static
Encode a global_position_int struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
global_position_int C-struct to read the message contents from
Definition at line 177 of file mavlink_msg_global_position_int.h.
static int32_t mavlink_msg_global_position_int_get_alt (const mavlink_message_t * msg) inline static
Get field alt from global_position_int message.
Returns
Altitude in meters, expressed as * 1000 (millimeters), AMSL (not WGS84 - note that virtually all GPS modules provide the AMSL as well)
Definition at line 325 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static uint16_t mavlink_msg_global_position_int_get_hdg (const mavlink_message_t * msg) inline static
Get field hdg from global_position_int message.
Returns
Compass heading in degrees * 100, 0.0..359.99 degrees. If unknown, set to: UINT16_MAX
Definition at line 375 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static int32_t mavlink_msg_global_position_int_get_lat (const mavlink_message_t * msg) inline static
Get field lat from global_position_int message.
Returns
Latitude, expressed as * 1E7
Definition at line 305 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static int32_t mavlink_msg_global_position_int_get_lon (const mavlink_message_t * msg) inline static
Get field lon from global_position_int message.
Returns
Longitude, expressed as * 1E7
Definition at line 315 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static int32_t mavlink_msg_global_position_int_get_relative_alt (const mavlink_message_t * msg) inline static
Get field relative_alt from global_position_int message.
Returns
Altitude above ground in meters, expressed as * 1000 (millimeters)
Definition at line 335 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static uint32_t mavlink_msg_global_position_int_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a global_position_int message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
lat Latitude, expressed as * 1E7
lon Longitude, expressed as * 1E7
alt Altitude in meters, expressed as * 1000 (millimeters), AMSL (not WGS84 - note that virtually all GPS modules provide the AMSL as well)
relative_alt Altitude above ground in meters, expressed as * 1000 (millimeters)
vx Ground X Speed (Latitude), expressed as m/s * 100
vy Ground Y Speed (Longitude), expressed as m/s * 100
vz Ground Z Speed (Altitude), expressed as m/s * 100
hdg Compass heading in degrees * 100, 0.0..359.99 degrees. If unknown, set to: UINT16_MAX Get field time_boot_ms from global_position_int message
Returns
Timestamp (milliseconds since system boot)
Definition at line 295 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static int16_t mavlink_msg_global_position_int_get_vx (const mavlink_message_t * msg) inline static
Get field vx from global_position_int message.
Returns
Ground X Speed (Latitude), expressed as m/s * 100
Definition at line 345 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static int16_t mavlink_msg_global_position_int_get_vy (const mavlink_message_t * msg) inline static
Get field vy from global_position_int message.
Returns
Ground Y Speed (Longitude), expressed as m/s * 100
Definition at line 355 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static int16_t mavlink_msg_global_position_int_get_vz (const mavlink_message_t * msg) inline static
Get field vz from global_position_int message.
Returns
Ground Z Speed (Altitude), expressed as m/s * 100
Definition at line 365 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_decode().
static uint16_t mavlink_msg_global_position_int_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, int32_t lat, int32_t lon, int32_t alt, int32_t relative_alt, int16_t vx, int16_t vy, int16_t vz, uint16_t hdg) inline static
Pack a global_position_int message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
lat Latitude, expressed as * 1E7
lon Longitude, expressed as * 1E7
alt Altitude in meters, expressed as * 1000 (millimeters), AMSL (not WGS84 - note that virtually all GPS modules provide the AMSL as well)
relative_alt Altitude above ground in meters, expressed as * 1000 (millimeters)
vx Ground X Speed (Latitude), expressed as m/s * 100
vy Ground Y Speed (Longitude), expressed as m/s * 100
vz Ground Z Speed (Altitude), expressed as m/s * 100
hdg Compass heading in degrees * 100, 0.0..359.99 degrees. If unknown, set to: UINT16_MAX
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 59 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_encode(), and mavlink_test_global_position_int().
static uint16_t mavlink_msg_global_position_int_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, int32_t lat, int32_t lon, int32_t alt, int32_t relative_alt, int16_t vx, int16_t vy, int16_t vz, uint16_t hdg) inline static
Pack a global_position_int message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
lat Latitude, expressed as * 1E7
lon Longitude, expressed as * 1E7
alt Altitude in meters, expressed as * 1000 (millimeters), AMSL (not WGS84 - note that virtually all GPS modules provide the AMSL as well)
relative_alt Altitude above ground in meters, expressed as * 1000 (millimeters)
vx Ground X Speed (Latitude), expressed as m/s * 100
vy Ground Y Speed (Longitude), expressed as m/s * 100
vz Ground Z Speed (Altitude), expressed as m/s * 100
hdg Compass heading in degrees * 100, 0.0..359.99 degrees. If unknown, set to: UINT16_MAX
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 115 of file mavlink_msg_global_position_int.h.
Referenced by mavlink_msg_global_position_int_encode_chan(), and mavlink_test_global_position_int().