APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_auth_key.h File Reference
mavlink_msg_auth_key.h File Reference
Classes
struct __mavlink_auth_key_t
Macros
#define MAVLINK_MSG_ID_AUTH_KEY 7
#define MAVLINK_MSG_ID_AUTH_KEY_LEN 32
#define MAVLINK_MSG_ID_7_LEN 32
#define MAVLINK_MSG_ID_AUTH_KEY_CRC 119
#define MAVLINK_MSG_ID_7_CRC 119
#define MAVLINK_MSG_AUTH_KEY_FIELD_KEY_LEN 32
#define MAVLINK_MESSAGE_INFO_AUTH_KEY
Typedefs
typedef struct __mavlink_auth_key_t mavlink_auth_key_t
Functions
static uint16_t mavlink_msg_auth_key_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const char *key)
Pack a auth_key message.
static uint16_t mavlink_msg_auth_key_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const char *key)
Pack a auth_key message on a channel.
static uint16_t mavlink_msg_auth_key_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_auth_key_t *auth_key)
Encode a auth_key struct.
static uint16_t mavlink_msg_auth_key_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_auth_key_t *auth_key)
Encode a auth_key struct on a channel.
static uint16_t mavlink_msg_auth_key_get_key (const mavlink_message_t *msg, char *key)
Send a auth_key message.
static void mavlink_msg_auth_key_decode (const mavlink_message_t *msg, mavlink_auth_key_t *auth_key)
Decode a auth_key message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AUTH_KEY
Value:
{ \
    "AUTH_KEY", \
    1, \
    {  { "key", NULL, MAVLINK_TYPE_CHAR, 32, 0, offsetof(mavlink_auth_key_t, key) }, \
         } \
}
Definition at line 18 of file mavlink_msg_auth_key.h.
#define MAVLINK_MSG_AUTH_KEY_FIELD_KEY_LEN 32
Definition at line 16 of file mavlink_msg_auth_key.h.
#define MAVLINK_MSG_ID_7_CRC 119
Definition at line 14 of file mavlink_msg_auth_key.h.
#define MAVLINK_MSG_ID_7_LEN 32
Definition at line 11 of file mavlink_msg_auth_key.h.
#define MAVLINK_MSG_ID_AUTH_KEY 7
Definition at line 3 of file mavlink_msg_auth_key.h.
Referenced by mavlink_msg_auth_key_pack(), and mavlink_msg_auth_key_pack_chan().
#define MAVLINK_MSG_ID_AUTH_KEY_CRC 119
Definition at line 13 of file mavlink_msg_auth_key.h.
Referenced by mavlink_msg_auth_key_pack(), and mavlink_msg_auth_key_pack_chan().
#define MAVLINK_MSG_ID_AUTH_KEY_LEN 32
Definition at line 10 of file mavlink_msg_auth_key.h.
Referenced by mavlink_msg_auth_key_decode(), mavlink_msg_auth_key_pack(), and mavlink_msg_auth_key_pack_chan().
Typedef Documentation
typedef struct __mavlink_auth_key_t mavlink_auth_key_t
Function Documentation
static void mavlink_msg_auth_key_decode (const mavlink_message_t * msg, mavlink_auth_key_t * auth_key) inline static
Decode a auth_key message into a struct.
Parameters
msg The message to decode
auth_key C-struct to decode the message contents into
Definition at line 202 of file mavlink_msg_auth_key.h.
Referenced by mavlink_test_auth_key().
static uint16_t mavlink_msg_auth_key_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_auth_key_t * auth_key) inline static
Encode a auth_key struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
auth_key C-struct to read the message contents from
Definition at line 99 of file mavlink_msg_auth_key.h.
Referenced by mavlink_test_auth_key().
static uint16_t mavlink_msg_auth_key_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_auth_key_t * auth_key) inline static
Encode a auth_key struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
auth_key C-struct to read the message contents from
Definition at line 113 of file mavlink_msg_auth_key.h.
static uint16_t mavlink_msg_auth_key_get_key (const mavlink_message_t * msg, char * key) inline static
Send a auth_key message.
Parameters
chan MAVLink channel to send the message
key key Get field key from auth_key message
Returns
key
Definition at line 191 of file mavlink_msg_auth_key.h.
Referenced by mavlink_msg_auth_key_decode().
static uint16_t mavlink_msg_auth_key_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const char * key) inline static
Pack a auth_key message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
key key
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_auth_key.h.
Referenced by mavlink_msg_auth_key_encode(), and mavlink_test_auth_key().
static uint16_t mavlink_msg_auth_key_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const char * key) inline static
Pack a auth_key message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
key key
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 67 of file mavlink_msg_auth_key.h.
Referenced by mavlink_msg_auth_key_encode_chan(), and mavlink_test_auth_key().