APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_file_transfer_protocol.h File Reference
mavlink_msg_file_transfer_protocol.h File Reference
Classes
struct __mavlink_file_transfer_protocol_t
Macros
#define MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL 110
#define MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL_LEN 254
#define MAVLINK_MSG_ID_110_LEN 254
#define MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL_CRC 84
#define MAVLINK_MSG_ID_110_CRC 84
#define MAVLINK_MSG_FILE_TRANSFER_PROTOCOL_FIELD_PAYLOAD_LEN 251
#define MAVLINK_MESSAGE_INFO_FILE_TRANSFER_PROTOCOL
Typedefs
typedef struct __mavlink_file_transfer_protocol_t mavlink_file_transfer_protocol_t
Functions
static uint16_t mavlink_msg_file_transfer_protocol_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_network, uint8_t target_system, uint8_t target_component, const uint8_t *payload)
Pack a file_transfer_protocol message.
static uint16_t mavlink_msg_file_transfer_protocol_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_network, uint8_t target_system, uint8_t target_component, const uint8_t *payload)
Pack a file_transfer_protocol message on a channel.
static uint16_t mavlink_msg_file_transfer_protocol_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_file_transfer_protocol_t *file_transfer_protocol)
Encode a file_transfer_protocol struct.
static uint16_t mavlink_msg_file_transfer_protocol_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_file_transfer_protocol_t *file_transfer_protocol)
Encode a file_transfer_protocol struct on a channel.
static uint8_t mavlink_msg_file_transfer_protocol_get_target_network (const mavlink_message_t *msg)
Send a file_transfer_protocol message.
static uint8_t mavlink_msg_file_transfer_protocol_get_target_system (const mavlink_message_t *msg)
Get field target_system from file_transfer_protocol message.
static uint8_t mavlink_msg_file_transfer_protocol_get_target_component (const mavlink_message_t *msg)
Get field target_component from file_transfer_protocol message.
static uint16_t mavlink_msg_file_transfer_protocol_get_payload (const mavlink_message_t *msg, uint8_t *payload)
Get field payload from file_transfer_protocol message.
static void mavlink_msg_file_transfer_protocol_decode (const mavlink_message_t *msg, mavlink_file_transfer_protocol_t *file_transfer_protocol)
Decode a file_transfer_protocol message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_FILE_TRANSFER_PROTOCOL
Value:
{ \
    "FILE_TRANSFER_PROTOCOL", \
    4, \
    {  { "target_network", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_file_transfer_protocol_t, target_network) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_file_transfer_protocol_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_file_transfer_protocol_t, target_component) }, \
         { "payload", NULL, MAVLINK_TYPE_UINT8_T, 251, 3, offsetof(mavlink_file_transfer_protocol_t, payload) }, \
         } \
}
Definition at line 21 of file mavlink_msg_file_transfer_protocol.h.
#define MAVLINK_MSG_FILE_TRANSFER_PROTOCOL_FIELD_PAYLOAD_LEN 251
Definition at line 19 of file mavlink_msg_file_transfer_protocol.h.
#define MAVLINK_MSG_ID_110_CRC 84
Definition at line 17 of file mavlink_msg_file_transfer_protocol.h.
#define MAVLINK_MSG_ID_110_LEN 254
Definition at line 14 of file mavlink_msg_file_transfer_protocol.h.
#define MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL 110
Definition at line 3 of file mavlink_msg_file_transfer_protocol.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_file_transfer_protocol_pack(), and mavlink_msg_file_transfer_protocol_pack_chan().
#define MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL_CRC 84
Definition at line 16 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_msg_file_transfer_protocol_pack(), and mavlink_msg_file_transfer_protocol_pack_chan().
#define MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL_LEN 254
Definition at line 13 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_msg_file_transfer_protocol_decode(), mavlink_msg_file_transfer_protocol_pack(), and mavlink_msg_file_transfer_protocol_pack_chan().
Typedef Documentation
typedef struct __mavlink_file_transfer_protocol_t mavlink_file_transfer_protocol_t
Function Documentation
static void mavlink_msg_file_transfer_protocol_decode (const mavlink_message_t * msg, mavlink_file_transfer_protocol_t * file_transfer_protocol) inline static
Decode a file_transfer_protocol message into a struct.
Parameters
msg The message to decode
file_transfer_protocol C-struct to decode the message contents into
Definition at line 263 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_test_file_transfer_protocol().
static uint16_t mavlink_msg_file_transfer_protocol_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_file_transfer_protocol_t * file_transfer_protocol) inline static
Encode a file_transfer_protocol struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
file_transfer_protocol C-struct to read the message contents from
Definition at line 119 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_test_file_transfer_protocol().
static uint16_t mavlink_msg_file_transfer_protocol_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_file_transfer_protocol_t * file_transfer_protocol) inline static
Encode a file_transfer_protocol struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
file_transfer_protocol C-struct to read the message contents from
Definition at line 133 of file mavlink_msg_file_transfer_protocol.h.
static uint16_t mavlink_msg_file_transfer_protocol_get_payload (const mavlink_message_t * msg, uint8_t * payload) inline static
Get field payload from file_transfer_protocol message.
Returns
Variable length payload. The length is defined by the remaining message length when subtracting the header and other fields. The entire content of this block is opaque unless you understand any the encoding message_type. The particular encoding used can be extension specific and might not always be documented as part of the mavlink specification.
Definition at line 252 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_msg_file_transfer_protocol_decode().
static uint8_t mavlink_msg_file_transfer_protocol_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from file_transfer_protocol message.
Returns
Component ID (0 for broadcast)
Definition at line 242 of file mavlink_msg_file_transfer_protocol.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_file_transfer_protocol_decode().
static uint8_t mavlink_msg_file_transfer_protocol_get_target_network (const mavlink_message_t * msg) inline static
Send a file_transfer_protocol message.
Parameters
chan MAVLink channel to send the message
target_network Network ID (0 for broadcast)
target_system System ID (0 for broadcast)
target_component Component ID (0 for broadcast)
payload Variable length payload. The length is defined by the remaining message length when subtracting the header and other fields. The entire content of this block is opaque unless you understand any the encoding message_type. The particular encoding used can be extension specific and might not always be documented as part of the mavlink specification. Get field target_network from file_transfer_protocol message
Returns
Network ID (0 for broadcast)
Definition at line 222 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_msg_file_transfer_protocol_decode().
static uint8_t mavlink_msg_file_transfer_protocol_get_target_system (const mavlink_message_t * msg) inline static
Get field target_system from file_transfer_protocol message.
Returns
System ID (0 for broadcast)
Definition at line 232 of file mavlink_msg_file_transfer_protocol.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_file_transfer_protocol_decode().
static uint16_t mavlink_msg_file_transfer_protocol_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_network, uint8_t target_system, uint8_t target_component, const uint8_t * payload) inline static
Pack a file_transfer_protocol message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_network Network ID (0 for broadcast)
target_system System ID (0 for broadcast)
target_component Component ID (0 for broadcast)
payload Variable length payload. The length is defined by the remaining message length when subtracting the header and other fields. The entire content of this block is opaque unless you understand any the encoding message_type. The particular encoding used can be extension specific and might not always be documented as part of the mavlink specification.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_msg_file_transfer_protocol_encode(), and mavlink_test_file_transfer_protocol().
static uint16_t mavlink_msg_file_transfer_protocol_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_network, uint8_t target_system, uint8_t target_component, const uint8_t * payload) inline static
Pack a file_transfer_protocol message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_network Network ID (0 for broadcast)
target_system System ID (0 for broadcast)
target_component Component ID (0 for broadcast)
payload Variable length payload. The length is defined by the remaining message length when subtracting the header and other fields. The entire content of this block is opaque unless you understand any the encoding message_type. The particular encoding used can be extension specific and might not always be documented as part of the mavlink specification.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 83 of file mavlink_msg_file_transfer_protocol.h.
Referenced by mavlink_msg_file_transfer_protocol_encode_chan(), and mavlink_test_file_transfer_protocol().