APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_data_stream.h File Reference
mavlink_msg_data_stream.h File Reference
Classes
struct __mavlink_data_stream_t
Macros
#define MAVLINK_MSG_ID_DATA_STREAM 67
#define MAVLINK_MSG_ID_DATA_STREAM_LEN 4
#define MAVLINK_MSG_ID_67_LEN 4
#define MAVLINK_MSG_ID_DATA_STREAM_CRC 21
#define MAVLINK_MSG_ID_67_CRC 21
#define MAVLINK_MESSAGE_INFO_DATA_STREAM
Typedefs
typedef struct __mavlink_data_stream_t mavlink_data_stream_t
Functions
static uint16_t mavlink_msg_data_stream_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t stream_id, uint16_t message_rate, uint8_t on_off)
Pack a data_stream message.
static uint16_t mavlink_msg_data_stream_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t stream_id, uint16_t message_rate, uint8_t on_off)
Pack a data_stream message on a channel.
static uint16_t mavlink_msg_data_stream_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_data_stream_t *data_stream)
Encode a data_stream struct.
static uint16_t mavlink_msg_data_stream_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_data_stream_t *data_stream)
Encode a data_stream struct on a channel.
static uint8_t mavlink_msg_data_stream_get_stream_id (const mavlink_message_t *msg)
Send a data_stream message.
static uint16_t mavlink_msg_data_stream_get_message_rate (const mavlink_message_t *msg)
Get field message_rate from data_stream message.
static uint8_t mavlink_msg_data_stream_get_on_off (const mavlink_message_t *msg)
Get field on_off from data_stream message.
static void mavlink_msg_data_stream_decode (const mavlink_message_t *msg, mavlink_data_stream_t *data_stream)
Decode a data_stream message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DATA_STREAM
Value:
{ \
    "DATA_STREAM", \
    3, \
    {  { "message_rate", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_data_stream_t, message_rate) }, \
         { "stream_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_data_stream_t, stream_id) }, \
         { "on_off", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_data_stream_t, on_off) }, \
         } \
}
Definition at line 20 of file mavlink_msg_data_stream.h.
#define MAVLINK_MSG_ID_67_CRC 21
Definition at line 16 of file mavlink_msg_data_stream.h.
#define MAVLINK_MSG_ID_67_LEN 4
Definition at line 13 of file mavlink_msg_data_stream.h.
#define MAVLINK_MSG_ID_DATA_STREAM 67
Definition at line 3 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_pack(), and mavlink_msg_data_stream_pack_chan().
#define MAVLINK_MSG_ID_DATA_STREAM_CRC 21
Definition at line 15 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_pack(), and mavlink_msg_data_stream_pack_chan().
#define MAVLINK_MSG_ID_DATA_STREAM_LEN 4
Definition at line 12 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_decode(), mavlink_msg_data_stream_pack(), and mavlink_msg_data_stream_pack_chan().
Typedef Documentation
typedef struct __mavlink_data_stream_t mavlink_data_stream_t
Function Documentation
static void mavlink_msg_data_stream_decode (const mavlink_message_t * msg, mavlink_data_stream_t * data_stream) inline static
Decode a data_stream message into a struct.
Parameters
msg The message to decode
data_stream C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_data_stream.h.
Referenced by mavlink_test_data_stream().
static uint16_t mavlink_msg_data_stream_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_data_stream_t * data_stream) inline static
Encode a data_stream struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
data_stream C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_data_stream.h.
Referenced by mavlink_test_data_stream().
static uint16_t mavlink_msg_data_stream_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_data_stream_t * data_stream) inline static
Encode a data_stream struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
data_stream C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_data_stream.h.
static uint16_t mavlink_msg_data_stream_get_message_rate (const mavlink_message_t * msg) inline static
Get field message_rate from data_stream message.
Returns
The requested interval between two messages of this type
Definition at line 227 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_decode().
static uint8_t mavlink_msg_data_stream_get_on_off (const mavlink_message_t * msg) inline static
Get field on_off from data_stream message.
Returns
1 stream is enabled, 0 stream is stopped.
Definition at line 237 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_decode().
static uint8_t mavlink_msg_data_stream_get_stream_id (const mavlink_message_t * msg) inline static
Send a data_stream message.
Parameters
chan MAVLink channel to send the message
stream_id The ID of the requested data stream
message_rate The requested interval between two messages of this type
on_off 1 stream is enabled, 0 stream is stopped. Get field stream_id from data_stream message
Returns
The ID of the requested data stream
Definition at line 217 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_decode().
static uint16_t mavlink_msg_data_stream_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t stream_id, uint16_t message_rate, uint8_t on_off) inline static
Pack a data_stream message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
stream_id The ID of the requested data stream
message_rate The requested interval between two messages of this type
on_off 1 stream is enabled, 0 stream is stopped.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_encode(), and mavlink_test_data_stream().
static uint16_t mavlink_msg_data_stream_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t stream_id, uint16_t message_rate, uint8_t on_off) inline static
Pack a data_stream message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
stream_id The ID of the requested data stream
message_rate The requested interval between two messages of this type
on_off 1 stream is enabled, 0 stream is stopped.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_data_stream.h.
Referenced by mavlink_msg_data_stream_encode_chan(), and mavlink_test_data_stream().