APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_mag_cal_progress.h File Reference
mavlink_msg_mag_cal_progress.h File Reference
Classes
struct __mavlink_mag_cal_progress_t
Macros
#define MAVLINK_MSG_ID_MAG_CAL_PROGRESS 191
#define MAVLINK_MSG_ID_MAG_CAL_PROGRESS_LEN 27
#define MAVLINK_MSG_ID_191_LEN 27
#define MAVLINK_MSG_ID_MAG_CAL_PROGRESS_CRC 92
#define MAVLINK_MSG_ID_191_CRC 92
#define MAVLINK_MSG_MAG_CAL_PROGRESS_FIELD_COMPLETION_MASK_LEN 10
#define MAVLINK_MESSAGE_INFO_MAG_CAL_PROGRESS
Typedefs
typedef struct __mavlink_mag_cal_progress_t mavlink_mag_cal_progress_t
Functions
static uint16_t mavlink_msg_mag_cal_progress_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t attempt, uint8_t completion_pct, const uint8_t *completion_mask, float direction_x, float direction_y, float direction_z)
Pack a mag_cal_progress message.
static uint16_t mavlink_msg_mag_cal_progress_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t attempt, uint8_t completion_pct, const uint8_t *completion_mask, float direction_x, float direction_y, float direction_z)
Pack a mag_cal_progress message on a channel.
static uint16_t mavlink_msg_mag_cal_progress_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mag_cal_progress_t *mag_cal_progress)
Encode a mag_cal_progress struct.
static uint16_t mavlink_msg_mag_cal_progress_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mag_cal_progress_t *mag_cal_progress)
Encode a mag_cal_progress struct on a channel.
static uint8_t mavlink_msg_mag_cal_progress_get_compass_id (const mavlink_message_t *msg)
Send a mag_cal_progress message.
static uint8_t mavlink_msg_mag_cal_progress_get_cal_mask (const mavlink_message_t *msg)
Get field cal_mask from mag_cal_progress message.
static uint8_t mavlink_msg_mag_cal_progress_get_cal_status (const mavlink_message_t *msg)
Get field cal_status from mag_cal_progress message.
static uint8_t mavlink_msg_mag_cal_progress_get_attempt (const mavlink_message_t *msg)
Get field attempt from mag_cal_progress message.
static uint8_t mavlink_msg_mag_cal_progress_get_completion_pct (const mavlink_message_t *msg)
Get field completion_pct from mag_cal_progress message.
static uint16_t mavlink_msg_mag_cal_progress_get_completion_mask (const mavlink_message_t *msg, uint8_t *completion_mask)
Get field completion_mask from mag_cal_progress message.
static float mavlink_msg_mag_cal_progress_get_direction_x (const mavlink_message_t *msg)
Get field direction_x from mag_cal_progress message.
static float mavlink_msg_mag_cal_progress_get_direction_y (const mavlink_message_t *msg)
Get field direction_y from mag_cal_progress message.
static float mavlink_msg_mag_cal_progress_get_direction_z (const mavlink_message_t *msg)
Get field direction_z from mag_cal_progress message.
static void mavlink_msg_mag_cal_progress_decode (const mavlink_message_t *msg, mavlink_mag_cal_progress_t *mag_cal_progress)
Decode a mag_cal_progress message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MAG_CAL_PROGRESS
Value:
{ \
    "MAG_CAL_PROGRESS", \
    9, \
    {  { "direction_x", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_mag_cal_progress_t, direction_x) }, \
         { "direction_y", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_mag_cal_progress_t, direction_y) }, \
         { "direction_z", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_mag_cal_progress_t, direction_z) }, \
         { "compass_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 12, offsetof(mavlink_mag_cal_progress_t, compass_id) }, \
         { "cal_mask", NULL, MAVLINK_TYPE_UINT8_T, 0, 13, offsetof(mavlink_mag_cal_progress_t, cal_mask) }, \
         { "cal_status", NULL, MAVLINK_TYPE_UINT8_T, 0, 14, offsetof(mavlink_mag_cal_progress_t, cal_status) }, \
         { "attempt", NULL, MAVLINK_TYPE_UINT8_T, 0, 15, offsetof(mavlink_mag_cal_progress_t, attempt) }, \
         { "completion_pct", NULL, MAVLINK_TYPE_UINT8_T, 0, 16, offsetof(mavlink_mag_cal_progress_t, completion_pct) }, \
         { "completion_mask", NULL, MAVLINK_TYPE_UINT8_T, 10, 17, offsetof(mavlink_mag_cal_progress_t, completion_mask) }, \
         } \
}
Definition at line 26 of file mavlink_msg_mag_cal_progress.h.
#define MAVLINK_MSG_ID_191_CRC 92
Definition at line 22 of file mavlink_msg_mag_cal_progress.h.
#define MAVLINK_MSG_ID_191_LEN 27
Definition at line 19 of file mavlink_msg_mag_cal_progress.h.
#define MAVLINK_MSG_ID_MAG_CAL_PROGRESS 191
Definition at line 3 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_pack(), and mavlink_msg_mag_cal_progress_pack_chan().
#define MAVLINK_MSG_ID_MAG_CAL_PROGRESS_CRC 92
Definition at line 21 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_pack(), and mavlink_msg_mag_cal_progress_pack_chan().
#define MAVLINK_MSG_ID_MAG_CAL_PROGRESS_LEN 27
Definition at line 18 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode(), mavlink_msg_mag_cal_progress_pack(), and mavlink_msg_mag_cal_progress_pack_chan().
#define MAVLINK_MSG_MAG_CAL_PROGRESS_FIELD_COMPLETION_MASK_LEN 10
Definition at line 24 of file mavlink_msg_mag_cal_progress.h.
Typedef Documentation
typedef struct __mavlink_mag_cal_progress_t mavlink_mag_cal_progress_t
Function Documentation
static void mavlink_msg_mag_cal_progress_decode (const mavlink_message_t * msg, mavlink_mag_cal_progress_t * mag_cal_progress) inline static
Decode a mag_cal_progress message into a struct.
Parameters
msg The message to decode
mag_cal_progress C-struct to decode the message contents into
Definition at line 378 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_test_mag_cal_progress().
static uint16_t mavlink_msg_mag_cal_progress_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mag_cal_progress_t * mag_cal_progress) inline static
Encode a mag_cal_progress struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mag_cal_progress C-struct to read the message contents from
Definition at line 159 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_test_mag_cal_progress().
static uint16_t mavlink_msg_mag_cal_progress_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mag_cal_progress_t * mag_cal_progress) inline static
Encode a mag_cal_progress struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mag_cal_progress C-struct to read the message contents from
Definition at line 173 of file mavlink_msg_mag_cal_progress.h.
static uint8_t mavlink_msg_mag_cal_progress_get_attempt (const mavlink_message_t * msg) inline static
Get field attempt from mag_cal_progress message.
Returns
Attempt number
Definition at line 317 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static uint8_t mavlink_msg_mag_cal_progress_get_cal_mask (const mavlink_message_t * msg) inline static
Get field cal_mask from mag_cal_progress message.
Returns
Bitmask of compasses being calibrated
Definition at line 297 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static uint8_t mavlink_msg_mag_cal_progress_get_cal_status (const mavlink_message_t * msg) inline static
Get field cal_status from mag_cal_progress message.
Returns
Status (see MAG_CAL_STATUS enum)
Definition at line 307 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static uint8_t mavlink_msg_mag_cal_progress_get_compass_id (const mavlink_message_t * msg) inline static
Send a mag_cal_progress message.
Parameters
chan MAVLink channel to send the message
compass_id Compass being calibrated
cal_mask Bitmask of compasses being calibrated
cal_status Status (see MAG_CAL_STATUS enum)
attempt Attempt number
completion_pct Completion percentage
completion_mask Bitmask of sphere sections (see http://en.wikipedia.org/wiki/Geodesic_grid)
direction_x Body frame direction vector for display
direction_y Body frame direction vector for display
direction_z Body frame direction vector for display Get field compass_id from mag_cal_progress message
Returns
Compass being calibrated
Definition at line 287 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static uint16_t mavlink_msg_mag_cal_progress_get_completion_mask (const mavlink_message_t * msg, uint8_t * completion_mask) inline static
Get field completion_mask from mag_cal_progress message.
Returns
Bitmask of sphere sections (see http://en.wikipedia.org/wiki/Geodesic_grid)
Definition at line 337 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static uint8_t mavlink_msg_mag_cal_progress_get_completion_pct (const mavlink_message_t * msg) inline static
Get field completion_pct from mag_cal_progress message.
Returns
Completion percentage
Definition at line 327 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static float mavlink_msg_mag_cal_progress_get_direction_x (const mavlink_message_t * msg) inline static
Get field direction_x from mag_cal_progress message.
Returns
Body frame direction vector for display
Definition at line 347 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static float mavlink_msg_mag_cal_progress_get_direction_y (const mavlink_message_t * msg) inline static
Get field direction_y from mag_cal_progress message.
Returns
Body frame direction vector for display
Definition at line 357 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static float mavlink_msg_mag_cal_progress_get_direction_z (const mavlink_message_t * msg) inline static
Get field direction_z from mag_cal_progress message.
Returns
Body frame direction vector for display
Definition at line 367 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_decode().
static uint16_t mavlink_msg_mag_cal_progress_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t attempt, uint8_t completion_pct, const uint8_t * completion_mask, float direction_x, float direction_y, float direction_z) inline static
Pack a mag_cal_progress message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
compass_id Compass being calibrated
cal_mask Bitmask of compasses being calibrated
cal_status Status (see MAG_CAL_STATUS enum)
attempt Attempt number
completion_pct Completion percentage
completion_mask Bitmask of sphere sections (see http://en.wikipedia.org/wiki/Geodesic_grid)
direction_x Body frame direction vector for display
direction_y Body frame direction vector for display
direction_z Body frame direction vector for display
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 59 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_encode(), and mavlink_test_mag_cal_progress().
static uint16_t mavlink_msg_mag_cal_progress_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t compass_id, uint8_t cal_mask, uint8_t cal_status, uint8_t attempt, uint8_t completion_pct, const uint8_t * completion_mask, float direction_x, float direction_y, float direction_z) inline static
Pack a mag_cal_progress message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
compass_id Compass being calibrated
cal_mask Bitmask of compasses being calibrated
cal_status Status (see MAG_CAL_STATUS enum)
attempt Attempt number
completion_pct Completion percentage
completion_mask Bitmask of sphere sections (see http://en.wikipedia.org/wiki/Geodesic_grid)
direction_x Body frame direction vector for display
direction_y Body frame direction vector for display
direction_z Body frame direction vector for display
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 113 of file mavlink_msg_mag_cal_progress.h.
Referenced by mavlink_msg_mag_cal_progress_encode_chan(), and mavlink_test_mag_cal_progress().