APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_rc_channels.h File Reference
mavlink_msg_rc_channels.h File Reference
Classes
struct __mavlink_rc_channels_t
Macros
#define MAVLINK_MSG_ID_RC_CHANNELS 65
#define MAVLINK_MSG_ID_RC_CHANNELS_LEN 42
#define MAVLINK_MSG_ID_65_LEN 42
#define MAVLINK_MSG_ID_RC_CHANNELS_CRC 118
#define MAVLINK_MSG_ID_65_CRC 118
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS
Typedefs
typedef struct __mavlink_rc_channels_t mavlink_rc_channels_t
Functions
static uint16_t mavlink_msg_rc_channels_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t chancount, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint16_t chan13_raw, uint16_t chan14_raw, uint16_t chan15_raw, uint16_t chan16_raw, uint16_t chan17_raw, uint16_t chan18_raw, uint8_t rssi)
Pack a rc_channels message.
static uint16_t mavlink_msg_rc_channels_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t chancount, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint16_t chan13_raw, uint16_t chan14_raw, uint16_t chan15_raw, uint16_t chan16_raw, uint16_t chan17_raw, uint16_t chan18_raw, uint8_t rssi)
Pack a rc_channels message on a channel.
static uint16_t mavlink_msg_rc_channels_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rc_channels_t *rc_channels)
Encode a rc_channels struct.
static uint16_t mavlink_msg_rc_channels_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_rc_channels_t *rc_channels)
Encode a rc_channels struct on a channel.
static uint32_t mavlink_msg_rc_channels_get_time_boot_ms (const mavlink_message_t *msg)
Send a rc_channels message.
static uint8_t mavlink_msg_rc_channels_get_chancount (const mavlink_message_t *msg)
Get field chancount from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan1_raw (const mavlink_message_t *msg)
Get field chan1_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan2_raw (const mavlink_message_t *msg)
Get field chan2_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan3_raw (const mavlink_message_t *msg)
Get field chan3_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan4_raw (const mavlink_message_t *msg)
Get field chan4_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan5_raw (const mavlink_message_t *msg)
Get field chan5_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan6_raw (const mavlink_message_t *msg)
Get field chan6_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan7_raw (const mavlink_message_t *msg)
Get field chan7_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan8_raw (const mavlink_message_t *msg)
Get field chan8_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan9_raw (const mavlink_message_t *msg)
Get field chan9_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan10_raw (const mavlink_message_t *msg)
Get field chan10_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan11_raw (const mavlink_message_t *msg)
Get field chan11_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan12_raw (const mavlink_message_t *msg)
Get field chan12_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan13_raw (const mavlink_message_t *msg)
Get field chan13_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan14_raw (const mavlink_message_t *msg)
Get field chan14_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan15_raw (const mavlink_message_t *msg)
Get field chan15_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan16_raw (const mavlink_message_t *msg)
Get field chan16_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan17_raw (const mavlink_message_t *msg)
Get field chan17_raw from rc_channels message.
static uint16_t mavlink_msg_rc_channels_get_chan18_raw (const mavlink_message_t *msg)
Get field chan18_raw from rc_channels message.
static uint8_t mavlink_msg_rc_channels_get_rssi (const mavlink_message_t *msg)
Get field rssi from rc_channels message.
static void mavlink_msg_rc_channels_decode (const mavlink_message_t *msg, mavlink_rc_channels_t *rc_channels)
Decode a rc_channels message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS
Value:
{ \
    "RC_CHANNELS", \
    21, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_rc_channels_t, time_boot_ms) }, \
         { "chan1_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_rc_channels_t, chan1_raw) }, \
         { "chan2_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_rc_channels_t, chan2_raw) }, \
         { "chan3_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_rc_channels_t, chan3_raw) }, \
         { "chan4_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_rc_channels_t, chan4_raw) }, \
         { "chan5_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_rc_channels_t, chan5_raw) }, \
         { "chan6_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 14, offsetof(mavlink_rc_channels_t, chan6_raw) }, \
         { "chan7_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_rc_channels_t, chan7_raw) }, \
         { "chan8_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_rc_channels_t, chan8_raw) }, \
         { "chan9_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 20, offsetof(mavlink_rc_channels_t, chan9_raw) }, \
         { "chan10_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 22, offsetof(mavlink_rc_channels_t, chan10_raw) }, \
         { "chan11_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 24, offsetof(mavlink_rc_channels_t, chan11_raw) }, \
         { "chan12_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 26, offsetof(mavlink_rc_channels_t, chan12_raw) }, \
         { "chan13_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 28, offsetof(mavlink_rc_channels_t, chan13_raw) }, \
         { "chan14_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 30, offsetof(mavlink_rc_channels_t, chan14_raw) }, \
         { "chan15_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 32, offsetof(mavlink_rc_channels_t, chan15_raw) }, \
         { "chan16_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 34, offsetof(mavlink_rc_channels_t, chan16_raw) }, \
         { "chan17_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 36, offsetof(mavlink_rc_channels_t, chan17_raw) }, \
         { "chan18_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 38, offsetof(mavlink_rc_channels_t, chan18_raw) }, \
         { "chancount", NULL, MAVLINK_TYPE_UINT8_T, 0, 40, offsetof(mavlink_rc_channels_t, chancount) }, \
         { "rssi", NULL, MAVLINK_TYPE_UINT8_T, 0, 41, offsetof(mavlink_rc_channels_t, rssi) }, \
         } \
}
Definition at line 38 of file mavlink_msg_rc_channels.h.
#define MAVLINK_MSG_ID_65_CRC 118
Definition at line 34 of file mavlink_msg_rc_channels.h.
#define MAVLINK_MSG_ID_65_LEN 42
Definition at line 31 of file mavlink_msg_rc_channels.h.
#define MAVLINK_MSG_ID_RC_CHANNELS 65
Definition at line 3 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_pack(), and mavlink_msg_rc_channels_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_CRC 118
Definition at line 33 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_pack(), and mavlink_msg_rc_channels_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_LEN 42
Definition at line 30 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode(), mavlink_msg_rc_channels_pack(), mavlink_msg_rc_channels_pack_chan(), and GCS_MAVLINK::send_radio_in().
Typedef Documentation
typedef struct __mavlink_rc_channels_t mavlink_rc_channels_t
Function Documentation
static void mavlink_msg_rc_channels_decode (const mavlink_message_t * msg, mavlink_rc_channels_t * rc_channels) inline static
Decode a rc_channels message into a struct.
Parameters
msg The message to decode
rc_channels C-struct to decode the message contents into
Definition at line 662 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_test_rc_channels().
static uint16_t mavlink_msg_rc_channels_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rc_channels_t * rc_channels) inline static
Encode a rc_channels struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rc_channels C-struct to read the message contents from
Definition at line 259 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_test_rc_channels().
static uint16_t mavlink_msg_rc_channels_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_rc_channels_t * rc_channels) inline static
Encode a rc_channels struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rc_channels C-struct to read the message contents from
Definition at line 273 of file mavlink_msg_rc_channels.h.
static uint16_t mavlink_msg_rc_channels_get_chan10_raw (const mavlink_message_t * msg) inline static
Get field chan10_raw from rc_channels message.
Returns
RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 561 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan11_raw (const mavlink_message_t * msg) inline static
Get field chan11_raw from rc_channels message.
Returns
RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 571 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan12_raw (const mavlink_message_t * msg) inline static
Get field chan12_raw from rc_channels message.
Returns
RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 581 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan13_raw (const mavlink_message_t * msg) inline static
Get field chan13_raw from rc_channels message.
Returns
RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 591 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan14_raw (const mavlink_message_t * msg) inline static
Get field chan14_raw from rc_channels message.
Returns
RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 601 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan15_raw (const mavlink_message_t * msg) inline static
Get field chan15_raw from rc_channels message.
Returns
RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 611 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan16_raw (const mavlink_message_t * msg) inline static
Get field chan16_raw from rc_channels message.
Returns
RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 621 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan17_raw (const mavlink_message_t * msg) inline static
Get field chan17_raw from rc_channels message.
Returns
RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 631 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan18_raw (const mavlink_message_t * msg) inline static
Get field chan18_raw from rc_channels message.
Returns
RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 641 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan1_raw (const mavlink_message_t * msg) inline static
Get field chan1_raw from rc_channels message.
Returns
RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 471 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan2_raw (const mavlink_message_t * msg) inline static
Get field chan2_raw from rc_channels message.
Returns
RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 481 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan3_raw (const mavlink_message_t * msg) inline static
Get field chan3_raw from rc_channels message.
Returns
RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 491 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan4_raw (const mavlink_message_t * msg) inline static
Get field chan4_raw from rc_channels message.
Returns
RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 501 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan5_raw (const mavlink_message_t * msg) inline static
Get field chan5_raw from rc_channels message.
Returns
RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 511 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan6_raw (const mavlink_message_t * msg) inline static
Get field chan6_raw from rc_channels message.
Returns
RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 521 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan7_raw (const mavlink_message_t * msg) inline static
Get field chan7_raw from rc_channels message.
Returns
RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 531 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan8_raw (const mavlink_message_t * msg) inline static
Get field chan8_raw from rc_channels message.
Returns
RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 541 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_get_chan9_raw (const mavlink_message_t * msg) inline static
Get field chan9_raw from rc_channels message.
Returns
RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
Definition at line 551 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint8_t mavlink_msg_rc_channels_get_chancount (const mavlink_message_t * msg) inline static
Get field chancount from rc_channels message.
Returns
Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.
Definition at line 461 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint8_t mavlink_msg_rc_channels_get_rssi (const mavlink_message_t * msg) inline static
Get field rssi from rc_channels message.
Returns
Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
Definition at line 651 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint32_t mavlink_msg_rc_channels_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a rc_channels message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
chancount Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan9_raw RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan10_raw RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan11_raw RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan12_raw RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan13_raw RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan14_raw RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan15_raw RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan16_raw RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan17_raw RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan18_raw RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
rssi Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown. Get field time_boot_ms from rc_channels message
Returns
Timestamp (milliseconds since system boot)
Definition at line 451 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_decode().
static uint16_t mavlink_msg_rc_channels_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t chancount, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint16_t chan13_raw, uint16_t chan14_raw, uint16_t chan15_raw, uint16_t chan16_raw, uint16_t chan17_raw, uint16_t chan18_raw, uint8_t rssi) inline static
Pack a rc_channels message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
chancount Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan9_raw RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan10_raw RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan11_raw RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan12_raw RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan13_raw RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan14_raw RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan15_raw RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan16_raw RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan17_raw RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan18_raw RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
rssi Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 95 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_encode(), and mavlink_test_rc_channels().
static uint16_t mavlink_msg_rc_channels_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t chancount, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint16_t chan9_raw, uint16_t chan10_raw, uint16_t chan11_raw, uint16_t chan12_raw, uint16_t chan13_raw, uint16_t chan14_raw, uint16_t chan15_raw, uint16_t chan16_raw, uint16_t chan17_raw, uint16_t chan18_raw, uint8_t rssi) inline static
Pack a rc_channels message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
chancount Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan9_raw RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan10_raw RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan11_raw RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan12_raw RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan13_raw RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan14_raw RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan15_raw RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan16_raw RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan17_raw RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
chan18_raw RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
rssi Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 187 of file mavlink_msg_rc_channels.h.
Referenced by mavlink_msg_rc_channels_encode_chan(), and mavlink_test_rc_channels().