APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_compassmot_status.h File Reference
mavlink_msg_compassmot_status.h File Reference
Classes
struct __mavlink_compassmot_status_t
Macros
#define MAVLINK_MSG_ID_COMPASSMOT_STATUS 177
#define MAVLINK_MSG_ID_COMPASSMOT_STATUS_LEN 20
#define MAVLINK_MSG_ID_177_LEN 20
#define MAVLINK_MSG_ID_COMPASSMOT_STATUS_CRC 240
#define MAVLINK_MSG_ID_177_CRC 240
#define MAVLINK_MESSAGE_INFO_COMPASSMOT_STATUS
Typedefs
typedef struct __mavlink_compassmot_status_t mavlink_compassmot_status_t
Functions
static uint16_t mavlink_msg_compassmot_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t throttle, float current, uint16_t interference, float CompensationX, float CompensationY, float CompensationZ)
Pack a compassmot_status message.
static uint16_t mavlink_msg_compassmot_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t throttle, float current, uint16_t interference, float CompensationX, float CompensationY, float CompensationZ)
Pack a compassmot_status message on a channel.
static uint16_t mavlink_msg_compassmot_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_compassmot_status_t *compassmot_status)
Encode a compassmot_status struct.
static uint16_t mavlink_msg_compassmot_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_compassmot_status_t *compassmot_status)
Encode a compassmot_status struct on a channel.
static uint16_t mavlink_msg_compassmot_status_get_throttle (const mavlink_message_t *msg)
Send a compassmot_status message.
static float mavlink_msg_compassmot_status_get_current (const mavlink_message_t *msg)
Get field current from compassmot_status message.
static uint16_t mavlink_msg_compassmot_status_get_interference (const mavlink_message_t *msg)
Get field interference from compassmot_status message.
static float mavlink_msg_compassmot_status_get_CompensationX (const mavlink_message_t *msg)
Get field CompensationX from compassmot_status message.
static float mavlink_msg_compassmot_status_get_CompensationY (const mavlink_message_t *msg)
Get field CompensationY from compassmot_status message.
static float mavlink_msg_compassmot_status_get_CompensationZ (const mavlink_message_t *msg)
Get field CompensationZ from compassmot_status message.
static void mavlink_msg_compassmot_status_decode (const mavlink_message_t *msg, mavlink_compassmot_status_t *compassmot_status)
Decode a compassmot_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_COMPASSMOT_STATUS
Value:
{ \
    "COMPASSMOT_STATUS", \
    6, \
    {  { "current", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_compassmot_status_t, current) }, \
         { "CompensationX", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_compassmot_status_t, CompensationX) }, \
         { "CompensationY", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_compassmot_status_t, CompensationY) }, \
         { "CompensationZ", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_compassmot_status_t, CompensationZ) }, \
         { "throttle", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_compassmot_status_t, throttle) }, \
         { "interference", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_compassmot_status_t, interference) }, \
         } \
}
Definition at line 23 of file mavlink_msg_compassmot_status.h.
#define MAVLINK_MSG_ID_177_CRC 240
Definition at line 19 of file mavlink_msg_compassmot_status.h.
#define MAVLINK_MSG_ID_177_LEN 20
Definition at line 16 of file mavlink_msg_compassmot_status.h.
#define MAVLINK_MSG_ID_COMPASSMOT_STATUS 177
Definition at line 3 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_pack(), and mavlink_msg_compassmot_status_pack_chan().
#define MAVLINK_MSG_ID_COMPASSMOT_STATUS_CRC 240
Definition at line 18 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_pack(), and mavlink_msg_compassmot_status_pack_chan().
#define MAVLINK_MSG_ID_COMPASSMOT_STATUS_LEN 20
Definition at line 15 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode(), mavlink_msg_compassmot_status_pack(), and mavlink_msg_compassmot_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_compassmot_status_t mavlink_compassmot_status_t
Function Documentation
static void mavlink_msg_compassmot_status_decode (const mavlink_message_t * msg, mavlink_compassmot_status_t * compassmot_status) inline static
Decode a compassmot_status message into a struct.
Parameters
msg The message to decode
compassmot_status C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_test_compassmot_status().
static uint16_t mavlink_msg_compassmot_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_compassmot_status_t * compassmot_status) inline static
Encode a compassmot_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
compassmot_status C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_test_compassmot_status().
static uint16_t mavlink_msg_compassmot_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_compassmot_status_t * compassmot_status) inline static
Encode a compassmot_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
compassmot_status C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_compassmot_status.h.
static float mavlink_msg_compassmot_status_get_CompensationX (const mavlink_message_t * msg) inline static
Get field CompensationX from compassmot_status message.
Returns
Motor Compensation X
Definition at line 286 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode().
static float mavlink_msg_compassmot_status_get_CompensationY (const mavlink_message_t * msg) inline static
Get field CompensationY from compassmot_status message.
Returns
Motor Compensation Y
Definition at line 296 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode().
static float mavlink_msg_compassmot_status_get_CompensationZ (const mavlink_message_t * msg) inline static
Get field CompensationZ from compassmot_status message.
Returns
Motor Compensation Z
Definition at line 306 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode().
static float mavlink_msg_compassmot_status_get_current (const mavlink_message_t * msg) inline static
Get field current from compassmot_status message.
Returns
current (amps)
Definition at line 266 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode().
static uint16_t mavlink_msg_compassmot_status_get_interference (const mavlink_message_t * msg) inline static
Get field interference from compassmot_status message.
Returns
interference (percent)
Definition at line 276 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode().
static uint16_t mavlink_msg_compassmot_status_get_throttle (const mavlink_message_t * msg) inline static
Send a compassmot_status message.
Parameters
chan MAVLink channel to send the message
throttle throttle (percent*10)
current current (amps)
interference interference (percent)
CompensationX Motor Compensation X
CompensationY Motor Compensation Y
CompensationZ Motor Compensation Z Get field throttle from compassmot_status message
Returns
throttle (percent*10)
Definition at line 256 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_decode().
static uint16_t mavlink_msg_compassmot_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t throttle, float current, uint16_t interference, float CompensationX, float CompensationY, float CompensationZ) inline static
Pack a compassmot_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
throttle throttle (percent*10)
current current (amps)
interference interference (percent)
CompensationX Motor Compensation X
CompensationY Motor Compensation Y
CompensationZ Motor Compensation Z
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_encode(), and mavlink_test_compassmot_status().
static uint16_t mavlink_msg_compassmot_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t throttle, float current, uint16_t interference, float CompensationX, float CompensationY, float CompensationZ) inline static
Pack a compassmot_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
throttle throttle (percent*10)
current current (amps)
interference interference (percent)
CompensationX Motor Compensation X
CompensationY Motor Compensation Y
CompensationZ Motor Compensation Z
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_compassmot_status.h.
Referenced by mavlink_msg_compassmot_status_encode_chan(), and mavlink_test_compassmot_status().