APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_report.h File Reference
mavlink_msg_gimbal_report.h File Reference
Classes
struct __mavlink_gimbal_report_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_REPORT 200
#define MAVLINK_MSG_ID_GIMBAL_REPORT_LEN 42
#define MAVLINK_MSG_ID_200_LEN 42
#define MAVLINK_MSG_ID_GIMBAL_REPORT_CRC 134
#define MAVLINK_MSG_ID_200_CRC 134
#define MAVLINK_MESSAGE_INFO_GIMBAL_REPORT
Typedefs
typedef struct __mavlink_gimbal_report_t mavlink_gimbal_report_t
Functions
static uint16_t mavlink_msg_gimbal_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float delta_time, float delta_angle_x, float delta_angle_y, float delta_angle_z, float delta_velocity_x, float delta_velocity_y, float delta_velocity_z, float joint_roll, float joint_el, float joint_az)
Pack a gimbal_report message.
static uint16_t mavlink_msg_gimbal_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float delta_time, float delta_angle_x, float delta_angle_y, float delta_angle_z, float delta_velocity_x, float delta_velocity_y, float delta_velocity_z, float joint_roll, float joint_el, float joint_az)
Pack a gimbal_report message on a channel.
static uint16_t mavlink_msg_gimbal_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_report_t *gimbal_report)
Encode a gimbal_report struct.
static uint16_t mavlink_msg_gimbal_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_report_t *gimbal_report)
Encode a gimbal_report struct on a channel.
static uint8_t mavlink_msg_gimbal_report_get_target_system (const mavlink_message_t *msg)
Send a gimbal_report message.
static uint8_t mavlink_msg_gimbal_report_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_time (const mavlink_message_t *msg)
Get field delta_time from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_angle_x (const mavlink_message_t *msg)
Get field delta_angle_x from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_angle_y (const mavlink_message_t *msg)
Get field delta_angle_y from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_angle_z (const mavlink_message_t *msg)
Get field delta_angle_z from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_velocity_x (const mavlink_message_t *msg)
Get field delta_velocity_x from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_velocity_y (const mavlink_message_t *msg)
Get field delta_velocity_y from gimbal_report message.
static float mavlink_msg_gimbal_report_get_delta_velocity_z (const mavlink_message_t *msg)
Get field delta_velocity_z from gimbal_report message.
static float mavlink_msg_gimbal_report_get_joint_roll (const mavlink_message_t *msg)
Get field joint_roll from gimbal_report message.
static float mavlink_msg_gimbal_report_get_joint_el (const mavlink_message_t *msg)
Get field joint_el from gimbal_report message.
static float mavlink_msg_gimbal_report_get_joint_az (const mavlink_message_t *msg)
Get field joint_az from gimbal_report message.
static void mavlink_msg_gimbal_report_decode (const mavlink_message_t *msg, mavlink_gimbal_report_t *gimbal_report)
Decode a gimbal_report message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_REPORT
Value:
{ \
    "GIMBAL_REPORT", \
    12, \
    {  { "delta_time", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_gimbal_report_t, delta_time) }, \
         { "delta_angle_x", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_gimbal_report_t, delta_angle_x) }, \
         { "delta_angle_y", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_gimbal_report_t, delta_angle_y) }, \
         { "delta_angle_z", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_gimbal_report_t, delta_angle_z) }, \
         { "delta_velocity_x", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_gimbal_report_t, delta_velocity_x) }, \
         { "delta_velocity_y", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_gimbal_report_t, delta_velocity_y) }, \
         { "delta_velocity_z", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_gimbal_report_t, delta_velocity_z) }, \
         { "joint_roll", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_gimbal_report_t, joint_roll) }, \
         { "joint_el", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_gimbal_report_t, joint_el) }, \
         { "joint_az", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_gimbal_report_t, joint_az) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 40, offsetof(mavlink_gimbal_report_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 41, offsetof(mavlink_gimbal_report_t, target_component) }, \
         } \
}
Definition at line 29 of file mavlink_msg_gimbal_report.h.
#define MAVLINK_MSG_ID_200_CRC 134
Definition at line 25 of file mavlink_msg_gimbal_report.h.
#define MAVLINK_MSG_ID_200_LEN 42
Definition at line 22 of file mavlink_msg_gimbal_report.h.
#define MAVLINK_MSG_ID_GIMBAL_REPORT 200
Definition at line 3 of file mavlink_msg_gimbal_report.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_gimbal_report_pack(), and mavlink_msg_gimbal_report_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REPORT_CRC 134
Definition at line 24 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_pack(), and mavlink_msg_gimbal_report_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REPORT_LEN 42
Definition at line 21 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode(), mavlink_msg_gimbal_report_pack(), and mavlink_msg_gimbal_report_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_report_t mavlink_gimbal_report_t
Function Documentation
static void mavlink_msg_gimbal_report_decode (const mavlink_message_t * msg, mavlink_gimbal_report_t * gimbal_report) inline static
Decode a gimbal_report message into a struct.
Parameters
msg The message to decode
gimbal_report C-struct to decode the message contents into
Definition at line 455 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_test_gimbal_report().
static uint16_t mavlink_msg_gimbal_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_report_t * gimbal_report) inline static
Encode a gimbal_report struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_report C-struct to read the message contents from
Definition at line 187 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_test_gimbal_report(), and SITL::Gimbal::send_report().
static uint16_t mavlink_msg_gimbal_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_report_t * gimbal_report) inline static
Encode a gimbal_report struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_report C-struct to read the message contents from
Definition at line 201 of file mavlink_msg_gimbal_report.h.
static float mavlink_msg_gimbal_report_get_delta_angle_x (const mavlink_message_t * msg) inline static
Get field delta_angle_x from gimbal_report message.
Returns
Delta angle X (radians)
Definition at line 364 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_delta_angle_y (const mavlink_message_t * msg) inline static
Get field delta_angle_y from gimbal_report message.
Returns
Delta angle Y (radians)
Definition at line 374 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_delta_angle_z (const mavlink_message_t * msg) inline static
Get field delta_angle_z from gimbal_report message.
Returns
Delta angle X (radians)
Definition at line 384 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_delta_time (const mavlink_message_t * msg) inline static
Get field delta_time from gimbal_report message.
Returns
Time since last update (seconds)
Definition at line 354 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_delta_velocity_x (const mavlink_message_t * msg) inline static
Get field delta_velocity_x from gimbal_report message.
Returns
Delta velocity X (m/s)
Definition at line 394 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_delta_velocity_y (const mavlink_message_t * msg) inline static
Get field delta_velocity_y from gimbal_report message.
Returns
Delta velocity Y (m/s)
Definition at line 404 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_delta_velocity_z (const mavlink_message_t * msg) inline static
Get field delta_velocity_z from gimbal_report message.
Returns
Delta velocity Z (m/s)
Definition at line 414 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_joint_az (const mavlink_message_t * msg) inline static
Get field joint_az from gimbal_report message.
Returns
Joint AZ (radians)
Definition at line 444 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_joint_el (const mavlink_message_t * msg) inline static
Get field joint_el from gimbal_report message.
Returns
Joint EL (radians)
Definition at line 434 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static float mavlink_msg_gimbal_report_get_joint_roll (const mavlink_message_t * msg) inline static
Get field joint_roll from gimbal_report message.
Returns
Joint ROLL (radians)
Definition at line 424 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_decode().
static uint8_t mavlink_msg_gimbal_report_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_report message.
Returns
Component ID
Definition at line 344 of file mavlink_msg_gimbal_report.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_gimbal_report_decode().
static uint8_t mavlink_msg_gimbal_report_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_report message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
delta_time Time since last update (seconds)
delta_angle_x Delta angle X (radians)
delta_angle_y Delta angle Y (radians)
delta_angle_z Delta angle X (radians)
delta_velocity_x Delta velocity X (m/s)
delta_velocity_y Delta velocity Y (m/s)
delta_velocity_z Delta velocity Z (m/s)
joint_roll Joint ROLL (radians)
joint_el Joint EL (radians)
joint_az Joint AZ (radians) Get field target_system from gimbal_report message
Returns
System ID
Definition at line 334 of file mavlink_msg_gimbal_report.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_gimbal_report_decode().
static uint16_t mavlink_msg_gimbal_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float delta_time, float delta_angle_x, float delta_angle_y, float delta_angle_z, float delta_velocity_x, float delta_velocity_y, float delta_velocity_z, float joint_roll, float joint_el, float joint_az) inline static
Pack a gimbal_report message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
delta_time Time since last update (seconds)
delta_angle_x Delta angle X (radians)
delta_angle_y Delta angle Y (radians)
delta_angle_z Delta angle X (radians)
delta_velocity_x Delta velocity X (m/s)
delta_velocity_y Delta velocity Y (m/s)
delta_velocity_z Delta velocity Z (m/s)
joint_roll Joint ROLL (radians)
joint_el Joint EL (radians)
joint_az Joint AZ (radians)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 68 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_encode(), and mavlink_test_gimbal_report().
static uint16_t mavlink_msg_gimbal_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float delta_time, float delta_angle_x, float delta_angle_y, float delta_angle_z, float delta_velocity_x, float delta_velocity_y, float delta_velocity_z, float joint_roll, float joint_el, float joint_az) inline static
Pack a gimbal_report message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
delta_time Time since last update (seconds)
delta_angle_x Delta angle X (radians)
delta_angle_y Delta angle Y (radians)
delta_angle_z Delta angle X (radians)
delta_velocity_x Delta velocity X (m/s)
delta_velocity_y Delta velocity Y (m/s)
delta_velocity_z Delta velocity Z (m/s)
joint_roll Joint ROLL (radians)
joint_el Joint EL (radians)
joint_az Joint AZ (radians)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 133 of file mavlink_msg_gimbal_report.h.
Referenced by mavlink_msg_gimbal_report_encode_chan(), and mavlink_test_gimbal_report().