APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_hil_optical_flow.h File Reference
mavlink_msg_hil_optical_flow.h File Reference
Classes
struct __mavlink_hil_optical_flow_t
Macros
#define MAVLINK_MSG_ID_HIL_OPTICAL_FLOW 114
#define MAVLINK_MSG_ID_HIL_OPTICAL_FLOW_LEN 44
#define MAVLINK_MSG_ID_114_LEN 44
#define MAVLINK_MSG_ID_HIL_OPTICAL_FLOW_CRC 237
#define MAVLINK_MSG_ID_114_CRC 237
#define MAVLINK_MESSAGE_INFO_HIL_OPTICAL_FLOW
Typedefs
typedef struct __mavlink_hil_optical_flow_t mavlink_hil_optical_flow_t
Functions
static uint16_t mavlink_msg_hil_optical_flow_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t sensor_id, uint32_t integration_time_us, float integrated_x, float integrated_y, float integrated_xgyro, float integrated_ygyro, float integrated_zgyro, int16_t temperature, uint8_t quality, uint32_t time_delta_distance_us, float distance)
Pack a hil_optical_flow message.
static uint16_t mavlink_msg_hil_optical_flow_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t sensor_id, uint32_t integration_time_us, float integrated_x, float integrated_y, float integrated_xgyro, float integrated_ygyro, float integrated_zgyro, int16_t temperature, uint8_t quality, uint32_t time_delta_distance_us, float distance)
Pack a hil_optical_flow message on a channel.
static uint16_t mavlink_msg_hil_optical_flow_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_hil_optical_flow_t *hil_optical_flow)
Encode a hil_optical_flow struct.
static uint16_t mavlink_msg_hil_optical_flow_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_hil_optical_flow_t *hil_optical_flow)
Encode a hil_optical_flow struct on a channel.
static uint64_t mavlink_msg_hil_optical_flow_get_time_usec (const mavlink_message_t *msg)
Send a hil_optical_flow message.
static uint8_t mavlink_msg_hil_optical_flow_get_sensor_id (const mavlink_message_t *msg)
Get field sensor_id from hil_optical_flow message.
static uint32_t mavlink_msg_hil_optical_flow_get_integration_time_us (const mavlink_message_t *msg)
Get field integration_time_us from hil_optical_flow message.
static float mavlink_msg_hil_optical_flow_get_integrated_x (const mavlink_message_t *msg)
Get field integrated_x from hil_optical_flow message.
static float mavlink_msg_hil_optical_flow_get_integrated_y (const mavlink_message_t *msg)
Get field integrated_y from hil_optical_flow message.
static float mavlink_msg_hil_optical_flow_get_integrated_xgyro (const mavlink_message_t *msg)
Get field integrated_xgyro from hil_optical_flow message.
static float mavlink_msg_hil_optical_flow_get_integrated_ygyro (const mavlink_message_t *msg)
Get field integrated_ygyro from hil_optical_flow message.
static float mavlink_msg_hil_optical_flow_get_integrated_zgyro (const mavlink_message_t *msg)
Get field integrated_zgyro from hil_optical_flow message.
static int16_t mavlink_msg_hil_optical_flow_get_temperature (const mavlink_message_t *msg)
Get field temperature from hil_optical_flow message.
static uint8_t mavlink_msg_hil_optical_flow_get_quality (const mavlink_message_t *msg)
Get field quality from hil_optical_flow message.
static uint32_t mavlink_msg_hil_optical_flow_get_time_delta_distance_us (const mavlink_message_t *msg)
Get field time_delta_distance_us from hil_optical_flow message.
static float mavlink_msg_hil_optical_flow_get_distance (const mavlink_message_t *msg)
Get field distance from hil_optical_flow message.
static void mavlink_msg_hil_optical_flow_decode (const mavlink_message_t *msg, mavlink_hil_optical_flow_t *hil_optical_flow)
Decode a hil_optical_flow message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_HIL_OPTICAL_FLOW
Value:
{ \
    "HIL_OPTICAL_FLOW", \
    12, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_hil_optical_flow_t, time_usec) }, \
         { "integration_time_us", NULL, MAVLINK_TYPE_UINT32_T, 0, 8, offsetof(mavlink_hil_optical_flow_t, integration_time_us) }, \
         { "integrated_x", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_hil_optical_flow_t, integrated_x) }, \
         { "integrated_y", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_hil_optical_flow_t, integrated_y) }, \
         { "integrated_xgyro", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_hil_optical_flow_t, integrated_xgyro) }, \
         { "integrated_ygyro", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_hil_optical_flow_t, integrated_ygyro) }, \
         { "integrated_zgyro", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_hil_optical_flow_t, integrated_zgyro) }, \
         { "time_delta_distance_us", NULL, MAVLINK_TYPE_UINT32_T, 0, 32, offsetof(mavlink_hil_optical_flow_t, time_delta_distance_us) }, \
         { "distance", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_hil_optical_flow_t, distance) }, \
         { "temperature", NULL, MAVLINK_TYPE_INT16_T, 0, 40, offsetof(mavlink_hil_optical_flow_t, temperature) }, \
         { "sensor_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 42, offsetof(mavlink_hil_optical_flow_t, sensor_id) }, \
         { "quality", NULL, MAVLINK_TYPE_UINT8_T, 0, 43, offsetof(mavlink_hil_optical_flow_t, quality) }, \
         } \
}
Definition at line 29 of file mavlink_msg_hil_optical_flow.h.
#define MAVLINK_MSG_ID_114_CRC 237
Definition at line 25 of file mavlink_msg_hil_optical_flow.h.
#define MAVLINK_MSG_ID_114_LEN 44
Definition at line 22 of file mavlink_msg_hil_optical_flow.h.
#define MAVLINK_MSG_ID_HIL_OPTICAL_FLOW 114
Definition at line 3 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_pack(), and mavlink_msg_hil_optical_flow_pack_chan().
#define MAVLINK_MSG_ID_HIL_OPTICAL_FLOW_CRC 237
Definition at line 24 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_pack(), and mavlink_msg_hil_optical_flow_pack_chan().
#define MAVLINK_MSG_ID_HIL_OPTICAL_FLOW_LEN 44
Definition at line 21 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode(), mavlink_msg_hil_optical_flow_pack(), and mavlink_msg_hil_optical_flow_pack_chan().
Typedef Documentation
typedef struct __mavlink_hil_optical_flow_t mavlink_hil_optical_flow_t
Function Documentation
static void mavlink_msg_hil_optical_flow_decode (const mavlink_message_t * msg, mavlink_hil_optical_flow_t * hil_optical_flow) inline static
Decode a hil_optical_flow message into a struct.
Parameters
msg The message to decode
hil_optical_flow C-struct to decode the message contents into
Definition at line 455 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_test_hil_optical_flow().
static uint16_t mavlink_msg_hil_optical_flow_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_hil_optical_flow_t * hil_optical_flow) inline static
Encode a hil_optical_flow struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
hil_optical_flow C-struct to read the message contents from
Definition at line 187 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_test_hil_optical_flow().
static uint16_t mavlink_msg_hil_optical_flow_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_hil_optical_flow_t * hil_optical_flow) inline static
Encode a hil_optical_flow struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
hil_optical_flow C-struct to read the message contents from
Definition at line 201 of file mavlink_msg_hil_optical_flow.h.
static float mavlink_msg_hil_optical_flow_get_distance (const mavlink_message_t * msg) inline static
Get field distance from hil_optical_flow message.
Returns
Distance to the center of the flow field in meters. Positive value (including zero): distance known. Negative value: Unknown distance.
Definition at line 444 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static float mavlink_msg_hil_optical_flow_get_integrated_x (const mavlink_message_t * msg) inline static
Get field integrated_x from hil_optical_flow message.
Returns
Flow in radians around X axis (Sensor RH rotation about the X axis induces a positive flow. Sensor linear motion along the positive Y axis induces a negative flow.)
Definition at line 364 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static float mavlink_msg_hil_optical_flow_get_integrated_xgyro (const mavlink_message_t * msg) inline static
Get field integrated_xgyro from hil_optical_flow message.
Returns
RH rotation around X axis (rad)
Definition at line 384 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static float mavlink_msg_hil_optical_flow_get_integrated_y (const mavlink_message_t * msg) inline static
Get field integrated_y from hil_optical_flow message.
Returns
Flow in radians around Y axis (Sensor RH rotation about the Y axis induces a positive flow. Sensor linear motion along the positive X axis induces a positive flow.)
Definition at line 374 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static float mavlink_msg_hil_optical_flow_get_integrated_ygyro (const mavlink_message_t * msg) inline static
Get field integrated_ygyro from hil_optical_flow message.
Returns
RH rotation around Y axis (rad)
Definition at line 394 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static float mavlink_msg_hil_optical_flow_get_integrated_zgyro (const mavlink_message_t * msg) inline static
Get field integrated_zgyro from hil_optical_flow message.
Returns
RH rotation around Z axis (rad)
Definition at line 404 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static uint32_t mavlink_msg_hil_optical_flow_get_integration_time_us (const mavlink_message_t * msg) inline static
Get field integration_time_us from hil_optical_flow message.
Returns
Integration time in microseconds. Divide integrated_x and integrated_y by the integration time to obtain average flow. The integration time also indicates the.
Definition at line 354 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static uint8_t mavlink_msg_hil_optical_flow_get_quality (const mavlink_message_t * msg) inline static
Get field quality from hil_optical_flow message.
Returns
Optical flow quality / confidence. 0: no valid flow, 255: maximum quality
Definition at line 424 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static uint8_t mavlink_msg_hil_optical_flow_get_sensor_id (const mavlink_message_t * msg) inline static
Get field sensor_id from hil_optical_flow message.
Returns
Sensor ID
Definition at line 344 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static int16_t mavlink_msg_hil_optical_flow_get_temperature (const mavlink_message_t * msg) inline static
Get field temperature from hil_optical_flow message.
Returns
Temperature * 100 in centi-degrees Celsius
Definition at line 414 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static uint32_t mavlink_msg_hil_optical_flow_get_time_delta_distance_us (const mavlink_message_t * msg) inline static
Get field time_delta_distance_us from hil_optical_flow message.
Returns
Time in microseconds since the distance was sampled.
Definition at line 434 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static uint64_t mavlink_msg_hil_optical_flow_get_time_usec (const mavlink_message_t * msg) inline static
Send a hil_optical_flow message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds, synced to UNIX time or since system boot)
sensor_id Sensor ID
integration_time_us Integration time in microseconds. Divide integrated_x and integrated_y by the integration time to obtain average flow. The integration time also indicates the.
integrated_x Flow in radians around X axis (Sensor RH rotation about the X axis induces a positive flow. Sensor linear motion along the positive Y axis induces a negative flow.)
integrated_y Flow in radians around Y axis (Sensor RH rotation about the Y axis induces a positive flow. Sensor linear motion along the positive X axis induces a positive flow.)
integrated_xgyro RH rotation around X axis (rad)
integrated_ygyro RH rotation around Y axis (rad)
integrated_zgyro RH rotation around Z axis (rad)
temperature Temperature * 100 in centi-degrees Celsius
quality Optical flow quality / confidence. 0: no valid flow, 255: maximum quality
time_delta_distance_us Time in microseconds since the distance was sampled.
distance Distance to the center of the flow field in meters. Positive value (including zero): distance known. Negative value: Unknown distance. Get field time_usec from hil_optical_flow message
Returns
Timestamp (microseconds, synced to UNIX time or since system boot)
Definition at line 334 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_decode().
static uint16_t mavlink_msg_hil_optical_flow_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t sensor_id, uint32_t integration_time_us, float integrated_x, float integrated_y, float integrated_xgyro, float integrated_ygyro, float integrated_zgyro, int16_t temperature, uint8_t quality, uint32_t time_delta_distance_us, float distance) inline static
Pack a hil_optical_flow message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds, synced to UNIX time or since system boot)
sensor_id Sensor ID
integration_time_us Integration time in microseconds. Divide integrated_x and integrated_y by the integration time to obtain average flow. The integration time also indicates the.
integrated_x Flow in radians around X axis (Sensor RH rotation about the X axis induces a positive flow. Sensor linear motion along the positive Y axis induces a negative flow.)
integrated_y Flow in radians around Y axis (Sensor RH rotation about the Y axis induces a positive flow. Sensor linear motion along the positive X axis induces a positive flow.)
integrated_xgyro RH rotation around X axis (rad)
integrated_ygyro RH rotation around Y axis (rad)
integrated_zgyro RH rotation around Z axis (rad)
temperature Temperature * 100 in centi-degrees Celsius
quality Optical flow quality / confidence. 0: no valid flow, 255: maximum quality
time_delta_distance_us Time in microseconds since the distance was sampled.
distance Distance to the center of the flow field in meters. Positive value (including zero): distance known. Negative value: Unknown distance.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 68 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_encode(), and mavlink_test_hil_optical_flow().
static uint16_t mavlink_msg_hil_optical_flow_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t sensor_id, uint32_t integration_time_us, float integrated_x, float integrated_y, float integrated_xgyro, float integrated_ygyro, float integrated_zgyro, int16_t temperature, uint8_t quality, uint32_t time_delta_distance_us, float distance) inline static
Pack a hil_optical_flow message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds, synced to UNIX time or since system boot)
sensor_id Sensor ID
integration_time_us Integration time in microseconds. Divide integrated_x and integrated_y by the integration time to obtain average flow. The integration time also indicates the.
integrated_x Flow in radians around X axis (Sensor RH rotation about the X axis induces a positive flow. Sensor linear motion along the positive Y axis induces a negative flow.)
integrated_y Flow in radians around Y axis (Sensor RH rotation about the Y axis induces a positive flow. Sensor linear motion along the positive X axis induces a positive flow.)
integrated_xgyro RH rotation around X axis (rad)
integrated_ygyro RH rotation around Y axis (rad)
integrated_zgyro RH rotation around Z axis (rad)
temperature Temperature * 100 in centi-degrees Celsius
quality Optical flow quality / confidence. 0: no valid flow, 255: maximum quality
time_delta_distance_us Time in microseconds since the distance was sampled.
distance Distance to the center of the flow field in meters. Positive value (including zero): distance known. Negative value: Unknown distance.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 133 of file mavlink_msg_hil_optical_flow.h.
Referenced by mavlink_msg_hil_optical_flow_encode_chan(), and mavlink_test_hil_optical_flow().