APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_attitude_target.h File Reference
mavlink_msg_attitude_target.h File Reference
Classes
struct __mavlink_attitude_target_t
Macros
#define MAVLINK_MSG_ID_ATTITUDE_TARGET 83
#define MAVLINK_MSG_ID_ATTITUDE_TARGET_LEN 37
#define MAVLINK_MSG_ID_83_LEN 37
#define MAVLINK_MSG_ID_ATTITUDE_TARGET_CRC 22
#define MAVLINK_MSG_ID_83_CRC 22
#define MAVLINK_MSG_ATTITUDE_TARGET_FIELD_Q_LEN 4
#define MAVLINK_MESSAGE_INFO_ATTITUDE_TARGET
Typedefs
typedef struct __mavlink_attitude_target_t mavlink_attitude_target_t
Functions
static uint16_t mavlink_msg_attitude_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t type_mask, const float *q, float body_roll_rate, float body_pitch_rate, float body_yaw_rate, float thrust)
Pack a attitude_target message.
static uint16_t mavlink_msg_attitude_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, uint8_t type_mask, const float *q, float body_roll_rate, float body_pitch_rate, float body_yaw_rate, float thrust)
Pack a attitude_target message on a channel.
static uint16_t mavlink_msg_attitude_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_attitude_target_t *attitude_target)
Encode a attitude_target struct.
static uint16_t mavlink_msg_attitude_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_attitude_target_t *attitude_target)
Encode a attitude_target struct on a channel.
static uint32_t mavlink_msg_attitude_target_get_time_boot_ms (const mavlink_message_t *msg)
Send a attitude_target message.
static uint8_t mavlink_msg_attitude_target_get_type_mask (const mavlink_message_t *msg)
Get field type_mask from attitude_target message.
static uint16_t mavlink_msg_attitude_target_get_q (const mavlink_message_t *msg, float *q)
Get field q from attitude_target message.
static float mavlink_msg_attitude_target_get_body_roll_rate (const mavlink_message_t *msg)
Get field body_roll_rate from attitude_target message.
static float mavlink_msg_attitude_target_get_body_pitch_rate (const mavlink_message_t *msg)
Get field body_pitch_rate from attitude_target message.
static float mavlink_msg_attitude_target_get_body_yaw_rate (const mavlink_message_t *msg)
Get field body_yaw_rate from attitude_target message.
static float mavlink_msg_attitude_target_get_thrust (const mavlink_message_t *msg)
Get field thrust from attitude_target message.
static void mavlink_msg_attitude_target_decode (const mavlink_message_t *msg, mavlink_attitude_target_t *attitude_target)
Decode a attitude_target message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ATTITUDE_TARGET
Value:
{ \
    "ATTITUDE_TARGET", \
    7, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_attitude_target_t, time_boot_ms) }, \
         { "q", NULL, MAVLINK_TYPE_FLOAT, 4, 4, offsetof(mavlink_attitude_target_t, q) }, \
         { "body_roll_rate", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_attitude_target_t, body_roll_rate) }, \
         { "body_pitch_rate", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_attitude_target_t, body_pitch_rate) }, \
         { "body_yaw_rate", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_attitude_target_t, body_yaw_rate) }, \
         { "thrust", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_attitude_target_t, thrust) }, \
         { "type_mask", NULL, MAVLINK_TYPE_UINT8_T, 0, 36, offsetof(mavlink_attitude_target_t, type_mask) }, \
         } \
}
Definition at line 24 of file mavlink_msg_attitude_target.h.
#define MAVLINK_MSG_ATTITUDE_TARGET_FIELD_Q_LEN 4
Definition at line 22 of file mavlink_msg_attitude_target.h.
#define MAVLINK_MSG_ID_83_CRC 22
Definition at line 20 of file mavlink_msg_attitude_target.h.
#define MAVLINK_MSG_ID_83_LEN 37
Definition at line 17 of file mavlink_msg_attitude_target.h.
#define MAVLINK_MSG_ID_ATTITUDE_TARGET 83
Definition at line 3 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_pack(), and mavlink_msg_attitude_target_pack_chan().
#define MAVLINK_MSG_ID_ATTITUDE_TARGET_CRC 22
Definition at line 19 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_pack(), and mavlink_msg_attitude_target_pack_chan().
#define MAVLINK_MSG_ID_ATTITUDE_TARGET_LEN 37
Definition at line 16 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode(), mavlink_msg_attitude_target_pack(), and mavlink_msg_attitude_target_pack_chan().
Typedef Documentation
typedef struct __mavlink_attitude_target_t mavlink_attitude_target_t
Function Documentation
static void mavlink_msg_attitude_target_decode (const mavlink_message_t * msg, mavlink_attitude_target_t * attitude_target) inline static
Decode a attitude_target message into a struct.
Parameters
msg The message to decode
attitude_target C-struct to decode the message contents into
Definition at line 332 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_test_attitude_target().
static uint16_t mavlink_msg_attitude_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_attitude_target_t * attitude_target) inline static
Encode a attitude_target struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
attitude_target C-struct to read the message contents from
Definition at line 143 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_test_attitude_target().
static uint16_t mavlink_msg_attitude_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_attitude_target_t * attitude_target) inline static
Encode a attitude_target struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
attitude_target C-struct to read the message contents from
Definition at line 157 of file mavlink_msg_attitude_target.h.
static float mavlink_msg_attitude_target_get_body_pitch_rate (const mavlink_message_t * msg) inline static
Get field body_pitch_rate from attitude_target message.
Returns
Body roll rate in radians per second
Definition at line 301 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static float mavlink_msg_attitude_target_get_body_roll_rate (const mavlink_message_t * msg) inline static
Get field body_roll_rate from attitude_target message.
Returns
Body roll rate in radians per second
Definition at line 291 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static float mavlink_msg_attitude_target_get_body_yaw_rate (const mavlink_message_t * msg) inline static
Get field body_yaw_rate from attitude_target message.
Returns
Body roll rate in radians per second
Definition at line 311 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static uint16_t mavlink_msg_attitude_target_get_q (const mavlink_message_t * msg, float * q) inline static
Get field q from attitude_target message.
Returns
Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
Definition at line 281 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static float mavlink_msg_attitude_target_get_thrust (const mavlink_message_t * msg) inline static
Get field thrust from attitude_target message.
Returns
Collective thrust, normalized to 0 .. 1 (-1 .. 1 for vehicles capable of reverse trust)
Definition at line 321 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static uint32_t mavlink_msg_attitude_target_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a attitude_target message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp in milliseconds since system boot
type_mask Mappings: If any of these bits are set, the corresponding input should be ignored: bit 1: body roll rate, bit 2: body pitch rate, bit 3: body yaw rate. bit 4-bit 7: reserved, bit 8: attitude
q Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
body_roll_rate Body roll rate in radians per second
body_pitch_rate Body roll rate in radians per second
body_yaw_rate Body roll rate in radians per second
thrust Collective thrust, normalized to 0 .. 1 (-1 .. 1 for vehicles capable of reverse trust) Get field time_boot_ms from attitude_target message
Returns
Timestamp in milliseconds since system boot
Definition at line 261 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static uint8_t mavlink_msg_attitude_target_get_type_mask (const mavlink_message_t * msg) inline static
Get field type_mask from attitude_target message.
Returns
Mappings: If any of these bits are set, the corresponding input should be ignored: bit 1: body roll rate, bit 2: body pitch rate, bit 3: body yaw rate. bit 4-bit 7: reserved, bit 8: attitude
Definition at line 271 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_decode().
static uint16_t mavlink_msg_attitude_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t type_mask, const float * q, float body_roll_rate, float body_pitch_rate, float body_yaw_rate, float thrust) inline static
Pack a attitude_target message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp in milliseconds since system boot
type_mask Mappings: If any of these bits are set, the corresponding input should be ignored: bit 1: body roll rate, bit 2: body pitch rate, bit 3: body yaw rate. bit 4-bit 7: reserved, bit 8: attitude
q Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
body_roll_rate Body roll rate in radians per second
body_pitch_rate Body roll rate in radians per second
body_yaw_rate Body roll rate in radians per second
thrust Collective thrust, normalized to 0 .. 1 (-1 .. 1 for vehicles capable of reverse trust)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_encode(), and mavlink_test_attitude_target().
static uint16_t mavlink_msg_attitude_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, uint8_t type_mask, const float * q, float body_roll_rate, float body_pitch_rate, float body_yaw_rate, float thrust) inline static
Pack a attitude_target message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp in milliseconds since system boot
type_mask Mappings: If any of these bits are set, the corresponding input should be ignored: bit 1: body roll rate, bit 2: body pitch rate, bit 3: body yaw rate. bit 4-bit 7: reserved, bit 8: attitude
q Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0)
body_roll_rate Body roll rate in radians per second
body_pitch_rate Body roll rate in radians per second
body_yaw_rate Body roll rate in radians per second
thrust Collective thrust, normalized to 0 .. 1 (-1 .. 1 for vehicles capable of reverse trust)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 101 of file mavlink_msg_attitude_target.h.
Referenced by mavlink_msg_attitude_target_encode_chan(), and mavlink_test_attitude_target().