APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_pid_tuning.h File Reference
mavlink_msg_pid_tuning.h File Reference
Classes
struct __mavlink_pid_tuning_t
Macros
#define MAVLINK_MSG_ID_PID_TUNING 194
#define MAVLINK_MSG_ID_PID_TUNING_LEN 25
#define MAVLINK_MSG_ID_194_LEN 25
#define MAVLINK_MSG_ID_PID_TUNING_CRC 98
#define MAVLINK_MSG_ID_194_CRC 98
#define MAVLINK_MESSAGE_INFO_PID_TUNING
Typedefs
typedef struct __mavlink_pid_tuning_t mavlink_pid_tuning_t
Functions
static uint16_t mavlink_msg_pid_tuning_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t axis, float desired, float achieved, float FF, float P, float I, float D)
Pack a pid_tuning message.
static uint16_t mavlink_msg_pid_tuning_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t axis, float desired, float achieved, float FF, float P, float I, float D)
Pack a pid_tuning message on a channel.
static uint16_t mavlink_msg_pid_tuning_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_pid_tuning_t *pid_tuning)
Encode a pid_tuning struct.
static uint16_t mavlink_msg_pid_tuning_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_pid_tuning_t *pid_tuning)
Encode a pid_tuning struct on a channel.
static uint8_t mavlink_msg_pid_tuning_get_axis (const mavlink_message_t *msg)
Send a pid_tuning message.
static float mavlink_msg_pid_tuning_get_desired (const mavlink_message_t *msg)
Get field desired from pid_tuning message.
static float mavlink_msg_pid_tuning_get_achieved (const mavlink_message_t *msg)
Get field achieved from pid_tuning message.
static float mavlink_msg_pid_tuning_get_FF (const mavlink_message_t *msg)
Get field FF from pid_tuning message.
static float mavlink_msg_pid_tuning_get_P (const mavlink_message_t *msg)
Get field P from pid_tuning message.
static float mavlink_msg_pid_tuning_get_I (const mavlink_message_t *msg)
Get field I from pid_tuning message.
static float mavlink_msg_pid_tuning_get_D (const mavlink_message_t *msg)
Get field D from pid_tuning message.
static void mavlink_msg_pid_tuning_decode (const mavlink_message_t *msg, mavlink_pid_tuning_t *pid_tuning)
Decode a pid_tuning message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_PID_TUNING
Value:
{ \
    "PID_TUNING", \
    7, \
    {  { "desired", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_pid_tuning_t, desired) }, \
         { "achieved", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_pid_tuning_t, achieved) }, \
         { "FF", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_pid_tuning_t, FF) }, \
         { "P", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_pid_tuning_t, P) }, \
         { "I", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_pid_tuning_t, I) }, \
         { "D", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_pid_tuning_t, D) }, \
         { "axis", NULL, MAVLINK_TYPE_UINT8_T, 0, 24, offsetof(mavlink_pid_tuning_t, axis) }, \
         } \
}
Definition at line 24 of file mavlink_msg_pid_tuning.h.
#define MAVLINK_MSG_ID_194_CRC 98
Definition at line 20 of file mavlink_msg_pid_tuning.h.
#define MAVLINK_MSG_ID_194_LEN 25
Definition at line 17 of file mavlink_msg_pid_tuning.h.
#define MAVLINK_MSG_ID_PID_TUNING 194
Definition at line 3 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_pack(), and mavlink_msg_pid_tuning_pack_chan().
#define MAVLINK_MSG_ID_PID_TUNING_CRC 98
Definition at line 19 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_pack(), and mavlink_msg_pid_tuning_pack_chan().
#define MAVLINK_MSG_ID_PID_TUNING_LEN 25
Definition at line 16 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode(), mavlink_msg_pid_tuning_pack(), and mavlink_msg_pid_tuning_pack_chan().
Typedef Documentation
typedef struct __mavlink_pid_tuning_t mavlink_pid_tuning_t
Function Documentation
static void mavlink_msg_pid_tuning_decode (const mavlink_message_t * msg, mavlink_pid_tuning_t * pid_tuning) inline static
Decode a pid_tuning message into a struct.
Parameters
msg The message to decode
pid_tuning C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_test_pid_tuning().
static uint16_t mavlink_msg_pid_tuning_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_pid_tuning_t * pid_tuning) inline static
Encode a pid_tuning struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
pid_tuning C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_test_pid_tuning().
static uint16_t mavlink_msg_pid_tuning_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_pid_tuning_t * pid_tuning) inline static
Encode a pid_tuning struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
pid_tuning C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_pid_tuning.h.
static float mavlink_msg_pid_tuning_get_achieved (const mavlink_message_t * msg) inline static
Get field achieved from pid_tuning message.
Returns
achieved rate (degrees/s)
Definition at line 289 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static uint8_t mavlink_msg_pid_tuning_get_axis (const mavlink_message_t * msg) inline static
Send a pid_tuning message.
Parameters
chan MAVLink channel to send the message
axis axis
desired desired rate (degrees/s)
achieved achieved rate (degrees/s)
FF FF component
P P component
I I component
D D component Get field axis from pid_tuning message
Returns
axis
Definition at line 269 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static float mavlink_msg_pid_tuning_get_D (const mavlink_message_t * msg) inline static
Get field D from pid_tuning message.
Returns
D component
Definition at line 329 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static float mavlink_msg_pid_tuning_get_desired (const mavlink_message_t * msg) inline static
Get field desired from pid_tuning message.
Returns
desired rate (degrees/s)
Definition at line 279 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static float mavlink_msg_pid_tuning_get_FF (const mavlink_message_t * msg) inline static
Get field FF from pid_tuning message.
Returns
FF component
Definition at line 299 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static float mavlink_msg_pid_tuning_get_I (const mavlink_message_t * msg) inline static
Get field I from pid_tuning message.
Returns
I component
Definition at line 319 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static float mavlink_msg_pid_tuning_get_P (const mavlink_message_t * msg) inline static
Get field P from pid_tuning message.
Returns
P component
Definition at line 309 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_decode().
static uint16_t mavlink_msg_pid_tuning_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t axis, float desired, float achieved, float FF, float P, float I, float D) inline static
Pack a pid_tuning message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
axis axis
desired desired rate (degrees/s)
achieved achieved rate (degrees/s)
FF FF component
P P component
I I component
D D component
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_encode(), and mavlink_test_pid_tuning().
static uint16_t mavlink_msg_pid_tuning_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t axis, float desired, float achieved, float FF, float P, float I, float D) inline static
Pack a pid_tuning message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
axis axis
desired desired rate (degrees/s)
achieved achieved rate (degrees/s)
FF FF component
P P component
I I component
D D component
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_pid_tuning.h.
Referenced by mavlink_msg_pid_tuning_encode_chan(), and mavlink_test_pid_tuning().