APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_digicam_control.h File Reference
mavlink_msg_digicam_control.h File Reference
Classes
struct __mavlink_digicam_control_t
Macros
#define MAVLINK_MSG_ID_DIGICAM_CONTROL 155
#define MAVLINK_MSG_ID_DIGICAM_CONTROL_LEN 13
#define MAVLINK_MSG_ID_155_LEN 13
#define MAVLINK_MSG_ID_DIGICAM_CONTROL_CRC 22
#define MAVLINK_MSG_ID_155_CRC 22
#define MAVLINK_MESSAGE_INFO_DIGICAM_CONTROL
Typedefs
typedef struct __mavlink_digicam_control_t mavlink_digicam_control_t
Functions
static uint16_t mavlink_msg_digicam_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t session, uint8_t zoom_pos, int8_t zoom_step, uint8_t focus_lock, uint8_t shot, uint8_t command_id, uint8_t extra_param, float extra_value)
Pack a digicam_control message.
static uint16_t mavlink_msg_digicam_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t session, uint8_t zoom_pos, int8_t zoom_step, uint8_t focus_lock, uint8_t shot, uint8_t command_id, uint8_t extra_param, float extra_value)
Pack a digicam_control message on a channel.
static uint16_t mavlink_msg_digicam_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_digicam_control_t *digicam_control)
Encode a digicam_control struct.
static uint16_t mavlink_msg_digicam_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_digicam_control_t *digicam_control)
Encode a digicam_control struct on a channel.
static uint8_t mavlink_msg_digicam_control_get_target_system (const mavlink_message_t *msg)
Send a digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_target_component (const mavlink_message_t *msg)
Get field target_component from digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_session (const mavlink_message_t *msg)
Get field session from digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_zoom_pos (const mavlink_message_t *msg)
Get field zoom_pos from digicam_control message.
static int8_t mavlink_msg_digicam_control_get_zoom_step (const mavlink_message_t *msg)
Get field zoom_step from digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_focus_lock (const mavlink_message_t *msg)
Get field focus_lock from digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_shot (const mavlink_message_t *msg)
Get field shot from digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_command_id (const mavlink_message_t *msg)
Get field command_id from digicam_control message.
static uint8_t mavlink_msg_digicam_control_get_extra_param (const mavlink_message_t *msg)
Get field extra_param from digicam_control message.
static float mavlink_msg_digicam_control_get_extra_value (const mavlink_message_t *msg)
Get field extra_value from digicam_control message.
static void mavlink_msg_digicam_control_decode (const mavlink_message_t *msg, mavlink_digicam_control_t *digicam_control)
Decode a digicam_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DIGICAM_CONTROL
Value:
{ \
    "DIGICAM_CONTROL", \
    10, \
    {  { "extra_value", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_digicam_control_t, extra_value) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_digicam_control_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_digicam_control_t, target_component) }, \
         { "session", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_digicam_control_t, session) }, \
         { "zoom_pos", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_digicam_control_t, zoom_pos) }, \
         { "zoom_step", NULL, MAVLINK_TYPE_INT8_T, 0, 8, offsetof(mavlink_digicam_control_t, zoom_step) }, \
         { "focus_lock", NULL, MAVLINK_TYPE_UINT8_T, 0, 9, offsetof(mavlink_digicam_control_t, focus_lock) }, \
         { "shot", NULL, MAVLINK_TYPE_UINT8_T, 0, 10, offsetof(mavlink_digicam_control_t, shot) }, \
         { "command_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 11, offsetof(mavlink_digicam_control_t, command_id) }, \
         { "extra_param", NULL, MAVLINK_TYPE_UINT8_T, 0, 12, offsetof(mavlink_digicam_control_t, extra_param) }, \
         } \
}
Definition at line 27 of file mavlink_msg_digicam_control.h.
#define MAVLINK_MSG_ID_155_CRC 22
Definition at line 23 of file mavlink_msg_digicam_control.h.
#define MAVLINK_MSG_ID_155_LEN 13
Definition at line 20 of file mavlink_msg_digicam_control.h.
#define MAVLINK_MSG_ID_DIGICAM_CONTROL 155
Definition at line 3 of file mavlink_msg_digicam_control.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_digicam_control_pack(), and mavlink_msg_digicam_control_pack_chan().
#define MAVLINK_MSG_ID_DIGICAM_CONTROL_CRC 22
Definition at line 22 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_pack(), and mavlink_msg_digicam_control_pack_chan().
#define MAVLINK_MSG_ID_DIGICAM_CONTROL_LEN 13
Definition at line 19 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode(), mavlink_msg_digicam_control_pack(), and mavlink_msg_digicam_control_pack_chan().
Typedef Documentation
typedef struct __mavlink_digicam_control_t mavlink_digicam_control_t
Function Documentation
static void mavlink_msg_digicam_control_decode (const mavlink_message_t * msg, mavlink_digicam_control_t * digicam_control) inline static
Decode a digicam_control message into a struct.
Parameters
msg The message to decode
digicam_control C-struct to decode the message contents into
Definition at line 409 of file mavlink_msg_digicam_control.h.
Referenced by AP_Camera::control_msg(), and mavlink_test_digicam_control().
static uint16_t mavlink_msg_digicam_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_digicam_control_t * digicam_control) inline static
Encode a digicam_control struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
digicam_control C-struct to read the message contents from
Definition at line 171 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_test_digicam_control().
static uint16_t mavlink_msg_digicam_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_digicam_control_t * digicam_control) inline static
Encode a digicam_control struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
digicam_control C-struct to read the message contents from
Definition at line 185 of file mavlink_msg_digicam_control.h.
static uint8_t mavlink_msg_digicam_control_get_command_id (const mavlink_message_t * msg) inline static
Get field command_id from digicam_control message.
Returns
Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
Definition at line 378 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_extra_param (const mavlink_message_t * msg) inline static
Get field extra_param from digicam_control message.
Returns
Extra parameters enumeration (0 means ignore)
Definition at line 388 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static float mavlink_msg_digicam_control_get_extra_value (const mavlink_message_t * msg) inline static
Get field extra_value from digicam_control message.
Returns
Correspondent value to given extra_param
Definition at line 398 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_focus_lock (const mavlink_message_t * msg) inline static
Get field focus_lock from digicam_control message.
Returns
0: unlock focus or keep unlocked, 1: lock focus or keep locked, 3: re-lock focus
Definition at line 358 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_session (const mavlink_message_t * msg) inline static
Get field session from digicam_control message.
Returns
0: stop, 1: start or keep it up //Session control e.g. show/hide lens
Definition at line 328 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_shot (const mavlink_message_t * msg) inline static
Get field shot from digicam_control message.
Returns
0: ignore, 1: shot or start filming
Definition at line 368 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from digicam_control message.
Returns
Component ID
Definition at line 318 of file mavlink_msg_digicam_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_target_system (const mavlink_message_t * msg) inline static
Send a digicam_control message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
session 0: stop, 1: start or keep it up //Session control e.g. show/hide lens
zoom_pos 1 to N //Zoom's absolute position (0 means ignore)
zoom_step -100 to 100 //Zooming step value to offset zoom from the current position
focus_lock 0: unlock focus or keep unlocked, 1: lock focus or keep locked, 3: re-lock focus
shot 0: ignore, 1: shot or start filming
command_id Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
extra_param Extra parameters enumeration (0 means ignore)
extra_value Correspondent value to given extra_param Get field target_system from digicam_control message
Returns
System ID
Definition at line 308 of file mavlink_msg_digicam_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_digicam_control_decode().
static uint8_t mavlink_msg_digicam_control_get_zoom_pos (const mavlink_message_t * msg) inline static
Get field zoom_pos from digicam_control message.
Returns
1 to N //Zoom's absolute position (0 means ignore)
Definition at line 338 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static int8_t mavlink_msg_digicam_control_get_zoom_step (const mavlink_message_t * msg) inline static
Get field zoom_step from digicam_control message.
Returns
-100 to 100 //Zooming step value to offset zoom from the current position
Definition at line 348 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_decode().
static uint16_t mavlink_msg_digicam_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t session, uint8_t zoom_pos, int8_t zoom_step, uint8_t focus_lock, uint8_t shot, uint8_t command_id, uint8_t extra_param, float extra_value) inline static
Pack a digicam_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
session 0: stop, 1: start or keep it up //Session control e.g. show/hide lens
zoom_pos 1 to N //Zoom's absolute position (0 means ignore)
zoom_step -100 to 100 //Zooming step value to offset zoom from the current position
focus_lock 0: unlock focus or keep unlocked, 1: lock focus or keep locked, 3: re-lock focus
shot 0: ignore, 1: shot or start filming
command_id Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
extra_param Extra parameters enumeration (0 means ignore)
extra_value Correspondent value to given extra_param
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_encode(), and mavlink_test_digicam_control().
static uint16_t mavlink_msg_digicam_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t session, uint8_t zoom_pos, int8_t zoom_step, uint8_t focus_lock, uint8_t shot, uint8_t command_id, uint8_t extra_param, float extra_value) inline static
Pack a digicam_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
session 0: stop, 1: start or keep it up //Session control e.g. show/hide lens
zoom_pos 1 to N //Zoom's absolute position (0 means ignore)
zoom_step -100 to 100 //Zooming step value to offset zoom from the current position
focus_lock 0: unlock focus or keep unlocked, 1: lock focus or keep locked, 3: re-lock focus
shot 0: ignore, 1: shot or start filming
command_id Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
extra_param Extra parameters enumeration (0 means ignore)
extra_value Correspondent value to given extra_param
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 121 of file mavlink_msg_digicam_control.h.
Referenced by mavlink_msg_digicam_control_encode_chan(), and mavlink_test_digicam_control().