APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_hil_state_quaternion.h File Reference
mavlink_msg_hil_state_quaternion.h File Reference
Classes
struct __mavlink_hil_state_quaternion_t
Macros
#define MAVLINK_MSG_ID_HIL_STATE_QUATERNION 115
#define MAVLINK_MSG_ID_HIL_STATE_QUATERNION_LEN 64
#define MAVLINK_MSG_ID_115_LEN 64
#define MAVLINK_MSG_ID_HIL_STATE_QUATERNION_CRC 4
#define MAVLINK_MSG_ID_115_CRC 4
#define MAVLINK_MSG_HIL_STATE_QUATERNION_FIELD_ATTITUDE_QUATERNION_LEN 4
#define MAVLINK_MESSAGE_INFO_HIL_STATE_QUATERNION
Typedefs
typedef struct __mavlink_hil_state_quaternion_t mavlink_hil_state_quaternion_t
Functions
static uint16_t mavlink_msg_hil_state_quaternion_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, const float *attitude_quaternion, float rollspeed, float pitchspeed, float yawspeed, int32_t lat, int32_t lon, int32_t alt, int16_t vx, int16_t vy, int16_t vz, uint16_t ind_airspeed, uint16_t true_airspeed, int16_t xacc, int16_t yacc, int16_t zacc)
Pack a hil_state_quaternion message.
static uint16_t mavlink_msg_hil_state_quaternion_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, const float *attitude_quaternion, float rollspeed, float pitchspeed, float yawspeed, int32_t lat, int32_t lon, int32_t alt, int16_t vx, int16_t vy, int16_t vz, uint16_t ind_airspeed, uint16_t true_airspeed, int16_t xacc, int16_t yacc, int16_t zacc)
Pack a hil_state_quaternion message on a channel.
static uint16_t mavlink_msg_hil_state_quaternion_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_hil_state_quaternion_t *hil_state_quaternion)
Encode a hil_state_quaternion struct.
static uint16_t mavlink_msg_hil_state_quaternion_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_hil_state_quaternion_t *hil_state_quaternion)
Encode a hil_state_quaternion struct on a channel.
static uint64_t mavlink_msg_hil_state_quaternion_get_time_usec (const mavlink_message_t *msg)
Send a hil_state_quaternion message.
static uint16_t mavlink_msg_hil_state_quaternion_get_attitude_quaternion (const mavlink_message_t *msg, float *attitude_quaternion)
Get field attitude_quaternion from hil_state_quaternion message.
static float mavlink_msg_hil_state_quaternion_get_rollspeed (const mavlink_message_t *msg)
Get field rollspeed from hil_state_quaternion message.
static float mavlink_msg_hil_state_quaternion_get_pitchspeed (const mavlink_message_t *msg)
Get field pitchspeed from hil_state_quaternion message.
static float mavlink_msg_hil_state_quaternion_get_yawspeed (const mavlink_message_t *msg)
Get field yawspeed from hil_state_quaternion message.
static int32_t mavlink_msg_hil_state_quaternion_get_lat (const mavlink_message_t *msg)
Get field lat from hil_state_quaternion message.
static int32_t mavlink_msg_hil_state_quaternion_get_lon (const mavlink_message_t *msg)
Get field lon from hil_state_quaternion message.
static int32_t mavlink_msg_hil_state_quaternion_get_alt (const mavlink_message_t *msg)
Get field alt from hil_state_quaternion message.
static int16_t mavlink_msg_hil_state_quaternion_get_vx (const mavlink_message_t *msg)
Get field vx from hil_state_quaternion message.
static int16_t mavlink_msg_hil_state_quaternion_get_vy (const mavlink_message_t *msg)
Get field vy from hil_state_quaternion message.
static int16_t mavlink_msg_hil_state_quaternion_get_vz (const mavlink_message_t *msg)
Get field vz from hil_state_quaternion message.
static uint16_t mavlink_msg_hil_state_quaternion_get_ind_airspeed (const mavlink_message_t *msg)
Get field ind_airspeed from hil_state_quaternion message.
static uint16_t mavlink_msg_hil_state_quaternion_get_true_airspeed (const mavlink_message_t *msg)
Get field true_airspeed from hil_state_quaternion message.
static int16_t mavlink_msg_hil_state_quaternion_get_xacc (const mavlink_message_t *msg)
Get field xacc from hil_state_quaternion message.
static int16_t mavlink_msg_hil_state_quaternion_get_yacc (const mavlink_message_t *msg)
Get field yacc from hil_state_quaternion message.
static int16_t mavlink_msg_hil_state_quaternion_get_zacc (const mavlink_message_t *msg)
Get field zacc from hil_state_quaternion message.
static void mavlink_msg_hil_state_quaternion_decode (const mavlink_message_t *msg, mavlink_hil_state_quaternion_t *hil_state_quaternion)
Decode a hil_state_quaternion message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_HIL_STATE_QUATERNION
Value:
{ \
    "HIL_STATE_QUATERNION", \
    16, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_hil_state_quaternion_t, time_usec) }, \
         { "attitude_quaternion", NULL, MAVLINK_TYPE_FLOAT, 4, 8, offsetof(mavlink_hil_state_quaternion_t, attitude_quaternion) }, \
         { "rollspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_hil_state_quaternion_t, rollspeed) }, \
         { "pitchspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_hil_state_quaternion_t, pitchspeed) }, \
         { "yawspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_hil_state_quaternion_t, yawspeed) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 36, offsetof(mavlink_hil_state_quaternion_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 40, offsetof(mavlink_hil_state_quaternion_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_INT32_T, 0, 44, offsetof(mavlink_hil_state_quaternion_t, alt) }, \
         { "vx", NULL, MAVLINK_TYPE_INT16_T, 0, 48, offsetof(mavlink_hil_state_quaternion_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_INT16_T, 0, 50, offsetof(mavlink_hil_state_quaternion_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_INT16_T, 0, 52, offsetof(mavlink_hil_state_quaternion_t, vz) }, \
         { "ind_airspeed", NULL, MAVLINK_TYPE_UINT16_T, 0, 54, offsetof(mavlink_hil_state_quaternion_t, ind_airspeed) }, \
         { "true_airspeed", NULL, MAVLINK_TYPE_UINT16_T, 0, 56, offsetof(mavlink_hil_state_quaternion_t, true_airspeed) }, \
         { "xacc", NULL, MAVLINK_TYPE_INT16_T, 0, 58, offsetof(mavlink_hil_state_quaternion_t, xacc) }, \
         { "yacc", NULL, MAVLINK_TYPE_INT16_T, 0, 60, offsetof(mavlink_hil_state_quaternion_t, yacc) }, \
         { "zacc", NULL, MAVLINK_TYPE_INT16_T, 0, 62, offsetof(mavlink_hil_state_quaternion_t, zacc) }, \
         } \
}
Definition at line 33 of file mavlink_msg_hil_state_quaternion.h.
#define MAVLINK_MSG_HIL_STATE_QUATERNION_FIELD_ATTITUDE_QUATERNION_LEN 4
Definition at line 31 of file mavlink_msg_hil_state_quaternion.h.
#define MAVLINK_MSG_ID_115_CRC 4
Definition at line 29 of file mavlink_msg_hil_state_quaternion.h.
#define MAVLINK_MSG_ID_115_LEN 64
Definition at line 26 of file mavlink_msg_hil_state_quaternion.h.
#define MAVLINK_MSG_ID_HIL_STATE_QUATERNION 115
Definition at line 3 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_pack(), and mavlink_msg_hil_state_quaternion_pack_chan().
#define MAVLINK_MSG_ID_HIL_STATE_QUATERNION_CRC 4
Definition at line 28 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_pack(), and mavlink_msg_hil_state_quaternion_pack_chan().
#define MAVLINK_MSG_ID_HIL_STATE_QUATERNION_LEN 64
Definition at line 25 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode(), mavlink_msg_hil_state_quaternion_pack(), and mavlink_msg_hil_state_quaternion_pack_chan().
Typedef Documentation
typedef struct __mavlink_hil_state_quaternion_t mavlink_hil_state_quaternion_t
Function Documentation
static void mavlink_msg_hil_state_quaternion_decode (const mavlink_message_t * msg, mavlink_hil_state_quaternion_t * hil_state_quaternion) inline static
Decode a hil_state_quaternion message into a struct.
Parameters
msg The message to decode
hil_state_quaternion C-struct to decode the message contents into
Definition at line 539 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_test_hil_state_quaternion().
static uint16_t mavlink_msg_hil_state_quaternion_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_hil_state_quaternion_t * hil_state_quaternion) inline static
Encode a hil_state_quaternion struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
hil_state_quaternion C-struct to read the message contents from
Definition at line 215 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_test_hil_state_quaternion().
static uint16_t mavlink_msg_hil_state_quaternion_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_hil_state_quaternion_t * hil_state_quaternion) inline static
Encode a hil_state_quaternion struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
hil_state_quaternion C-struct to read the message contents from
Definition at line 229 of file mavlink_msg_hil_state_quaternion.h.
static int32_t mavlink_msg_hil_state_quaternion_get_alt (const mavlink_message_t * msg) inline static
Get field alt from hil_state_quaternion message.
Returns
Altitude in meters, expressed as * 1000 (millimeters)
Definition at line 448 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static uint16_t mavlink_msg_hil_state_quaternion_get_attitude_quaternion (const mavlink_message_t * msg, float * attitude_quaternion) inline static
Get field attitude_quaternion from hil_state_quaternion message.
Returns
Vehicle attitude expressed as normalized quaternion in w, x, y, z order (with 1 0 0 0 being the null-rotation)
Definition at line 388 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static uint16_t mavlink_msg_hil_state_quaternion_get_ind_airspeed (const mavlink_message_t * msg) inline static
Get field ind_airspeed from hil_state_quaternion message.
Returns
Indicated airspeed, expressed as m/s * 100
Definition at line 488 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int32_t mavlink_msg_hil_state_quaternion_get_lat (const mavlink_message_t * msg) inline static
Get field lat from hil_state_quaternion message.
Returns
Latitude, expressed as * 1E7
Definition at line 428 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int32_t mavlink_msg_hil_state_quaternion_get_lon (const mavlink_message_t * msg) inline static
Get field lon from hil_state_quaternion message.
Returns
Longitude, expressed as * 1E7
Definition at line 438 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static float mavlink_msg_hil_state_quaternion_get_pitchspeed (const mavlink_message_t * msg) inline static
Get field pitchspeed from hil_state_quaternion message.
Returns
Body frame pitch / theta angular speed (rad/s)
Definition at line 408 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static float mavlink_msg_hil_state_quaternion_get_rollspeed (const mavlink_message_t * msg) inline static
Get field rollspeed from hil_state_quaternion message.
Returns
Body frame roll / phi angular speed (rad/s)
Definition at line 398 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static uint64_t mavlink_msg_hil_state_quaternion_get_time_usec (const mavlink_message_t * msg) inline static
Send a hil_state_quaternion message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
attitude_quaternion Vehicle attitude expressed as normalized quaternion in w, x, y, z order (with 1 0 0 0 being the null-rotation)
rollspeed Body frame roll / phi angular speed (rad/s)
pitchspeed Body frame pitch / theta angular speed (rad/s)
yawspeed Body frame yaw / psi angular speed (rad/s)
lat Latitude, expressed as * 1E7
lon Longitude, expressed as * 1E7
alt Altitude in meters, expressed as * 1000 (millimeters)
vx Ground X Speed (Latitude), expressed as m/s * 100
vy Ground Y Speed (Longitude), expressed as m/s * 100
vz Ground Z Speed (Altitude), expressed as m/s * 100
ind_airspeed Indicated airspeed, expressed as m/s * 100
true_airspeed True airspeed, expressed as m/s * 100
xacc X acceleration (mg)
yacc Y acceleration (mg)
zacc Z acceleration (mg) Get field time_usec from hil_state_quaternion message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 378 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static uint16_t mavlink_msg_hil_state_quaternion_get_true_airspeed (const mavlink_message_t * msg) inline static
Get field true_airspeed from hil_state_quaternion message.
Returns
True airspeed, expressed as m/s * 100
Definition at line 498 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int16_t mavlink_msg_hil_state_quaternion_get_vx (const mavlink_message_t * msg) inline static
Get field vx from hil_state_quaternion message.
Returns
Ground X Speed (Latitude), expressed as m/s * 100
Definition at line 458 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int16_t mavlink_msg_hil_state_quaternion_get_vy (const mavlink_message_t * msg) inline static
Get field vy from hil_state_quaternion message.
Returns
Ground Y Speed (Longitude), expressed as m/s * 100
Definition at line 468 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int16_t mavlink_msg_hil_state_quaternion_get_vz (const mavlink_message_t * msg) inline static
Get field vz from hil_state_quaternion message.
Returns
Ground Z Speed (Altitude), expressed as m/s * 100
Definition at line 478 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int16_t mavlink_msg_hil_state_quaternion_get_xacc (const mavlink_message_t * msg) inline static
Get field xacc from hil_state_quaternion message.
Returns
X acceleration (mg)
Definition at line 508 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int16_t mavlink_msg_hil_state_quaternion_get_yacc (const mavlink_message_t * msg) inline static
Get field yacc from hil_state_quaternion message.
Returns
Y acceleration (mg)
Definition at line 518 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static float mavlink_msg_hil_state_quaternion_get_yawspeed (const mavlink_message_t * msg) inline static
Get field yawspeed from hil_state_quaternion message.
Returns
Body frame yaw / psi angular speed (rad/s)
Definition at line 418 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static int16_t mavlink_msg_hil_state_quaternion_get_zacc (const mavlink_message_t * msg) inline static
Get field zacc from hil_state_quaternion message.
Returns
Z acceleration (mg)
Definition at line 528 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_decode().
static uint16_t mavlink_msg_hil_state_quaternion_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, const float * attitude_quaternion, float rollspeed, float pitchspeed, float yawspeed, int32_t lat, int32_t lon, int32_t alt, int16_t vx, int16_t vy, int16_t vz, uint16_t ind_airspeed, uint16_t true_airspeed, int16_t xacc, int16_t yacc, int16_t zacc) inline static
Pack a hil_state_quaternion message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
attitude_quaternion Vehicle attitude expressed as normalized quaternion in w, x, y, z order (with 1 0 0 0 being the null-rotation)
rollspeed Body frame roll / phi angular speed (rad/s)
pitchspeed Body frame pitch / theta angular speed (rad/s)
yawspeed Body frame yaw / psi angular speed (rad/s)
lat Latitude, expressed as * 1E7
lon Longitude, expressed as * 1E7
alt Altitude in meters, expressed as * 1000 (millimeters)
vx Ground X Speed (Latitude), expressed as m/s * 100
vy Ground Y Speed (Longitude), expressed as m/s * 100
vz Ground Z Speed (Altitude), expressed as m/s * 100
ind_airspeed Indicated airspeed, expressed as m/s * 100
true_airspeed True airspeed, expressed as m/s * 100
xacc X acceleration (mg)
yacc Y acceleration (mg)
zacc Z acceleration (mg)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 80 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_encode(), and mavlink_test_hil_state_quaternion().
static uint16_t mavlink_msg_hil_state_quaternion_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, const float * attitude_quaternion, float rollspeed, float pitchspeed, float yawspeed, int32_t lat, int32_t lon, int32_t alt, int16_t vx, int16_t vy, int16_t vz, uint16_t ind_airspeed, uint16_t true_airspeed, int16_t xacc, int16_t yacc, int16_t zacc) inline static
Pack a hil_state_quaternion message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
attitude_quaternion Vehicle attitude expressed as normalized quaternion in w, x, y, z order (with 1 0 0 0 being the null-rotation)
rollspeed Body frame roll / phi angular speed (rad/s)
pitchspeed Body frame pitch / theta angular speed (rad/s)
yawspeed Body frame yaw / psi angular speed (rad/s)
lat Latitude, expressed as * 1E7
lon Longitude, expressed as * 1E7
alt Altitude in meters, expressed as * 1000 (millimeters)
vx Ground X Speed (Latitude), expressed as m/s * 100
vy Ground Y Speed (Longitude), expressed as m/s * 100
vz Ground Z Speed (Altitude), expressed as m/s * 100
ind_airspeed Indicated airspeed, expressed as m/s * 100
true_airspeed True airspeed, expressed as m/s * 100
xacc X acceleration (mg)
yacc Y acceleration (mg)
zacc Z acceleration (mg)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 155 of file mavlink_msg_hil_state_quaternion.h.
Referenced by mavlink_msg_hil_state_quaternion_encode_chan(), and mavlink_test_hil_state_quaternion().