APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gopro_set_response.h File Reference
mavlink_msg_gopro_set_response.h File Reference
Classes
struct __mavlink_gopro_set_response_t
Macros
#define MAVLINK_MSG_ID_GOPRO_SET_RESPONSE 219
#define MAVLINK_MSG_ID_GOPRO_SET_RESPONSE_LEN 2
#define MAVLINK_MSG_ID_219_LEN 2
#define MAVLINK_MSG_ID_GOPRO_SET_RESPONSE_CRC 47
#define MAVLINK_MSG_ID_219_CRC 47
#define MAVLINK_MESSAGE_INFO_GOPRO_SET_RESPONSE
Typedefs
typedef struct __mavlink_gopro_set_response_t mavlink_gopro_set_response_t
Functions
static uint16_t mavlink_msg_gopro_set_response_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t cmd_id, uint8_t result)
Pack a gopro_set_response message.
static uint16_t mavlink_msg_gopro_set_response_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t cmd_id, uint8_t result)
Pack a gopro_set_response message on a channel.
static uint16_t mavlink_msg_gopro_set_response_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gopro_set_response_t *gopro_set_response)
Encode a gopro_set_response struct.
static uint16_t mavlink_msg_gopro_set_response_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gopro_set_response_t *gopro_set_response)
Encode a gopro_set_response struct on a channel.
static uint8_t mavlink_msg_gopro_set_response_get_cmd_id (const mavlink_message_t *msg)
Send a gopro_set_response message.
static uint8_t mavlink_msg_gopro_set_response_get_result (const mavlink_message_t *msg)
Get field result from gopro_set_response message.
static void mavlink_msg_gopro_set_response_decode (const mavlink_message_t *msg, mavlink_gopro_set_response_t *gopro_set_response)
Decode a gopro_set_response message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GOPRO_SET_RESPONSE
Value:
{ \
    "GOPRO_SET_RESPONSE", \
    2, \
    {  { "cmd_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gopro_set_response_t, cmd_id) }, \
         { "result", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gopro_set_response_t, result) }, \
         } \
}
Definition at line 19 of file mavlink_msg_gopro_set_response.h.
#define MAVLINK_MSG_ID_219_CRC 47
Definition at line 15 of file mavlink_msg_gopro_set_response.h.
#define MAVLINK_MSG_ID_219_LEN 2
Definition at line 12 of file mavlink_msg_gopro_set_response.h.
#define MAVLINK_MSG_ID_GOPRO_SET_RESPONSE 219
Definition at line 3 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_pack(), and mavlink_msg_gopro_set_response_pack_chan().
#define MAVLINK_MSG_ID_GOPRO_SET_RESPONSE_CRC 47
Definition at line 14 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_pack(), and mavlink_msg_gopro_set_response_pack_chan().
#define MAVLINK_MSG_ID_GOPRO_SET_RESPONSE_LEN 2
Definition at line 11 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_decode(), mavlink_msg_gopro_set_response_pack(), and mavlink_msg_gopro_set_response_pack_chan().
Typedef Documentation
typedef struct __mavlink_gopro_set_response_t mavlink_gopro_set_response_t
Function Documentation
static void mavlink_msg_gopro_set_response_decode (const mavlink_message_t * msg, mavlink_gopro_set_response_t * gopro_set_response) inline static
Decode a gopro_set_response message into a struct.
Parameters
msg The message to decode
gopro_set_response C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_test_gopro_set_response().
static uint16_t mavlink_msg_gopro_set_response_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gopro_set_response_t * gopro_set_response) inline static
Encode a gopro_set_response struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gopro_set_response C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_test_gopro_set_response().
static uint16_t mavlink_msg_gopro_set_response_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gopro_set_response_t * gopro_set_response) inline static
Encode a gopro_set_response struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gopro_set_response C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_gopro_set_response.h.
static uint8_t mavlink_msg_gopro_set_response_get_cmd_id (const mavlink_message_t * msg) inline static
Send a gopro_set_response message.
Parameters
chan MAVLink channel to send the message
cmd_id Command ID
result Result Get field cmd_id from gopro_set_response message
Returns
Command ID
Definition at line 204 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_decode().
static uint8_t mavlink_msg_gopro_set_response_get_result (const mavlink_message_t * msg) inline static
Get field result from gopro_set_response message.
Returns
Result
Definition at line 214 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_decode().
static uint16_t mavlink_msg_gopro_set_response_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t cmd_id, uint8_t result) inline static
Pack a gopro_set_response message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
cmd_id Command ID
result Result
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_encode(), and mavlink_test_gopro_set_response().
static uint16_t mavlink_msg_gopro_set_response_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t cmd_id, uint8_t result) inline static
Pack a gopro_set_response message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
cmd_id Command ID
result Result
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_gopro_set_response.h.
Referenced by mavlink_msg_gopro_set_response_encode_chan(), and mavlink_test_gopro_set_response().