APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_autopilot_version_request.h File Reference
mavlink_msg_autopilot_version_request.h File Reference
Classes
struct __mavlink_autopilot_version_request_t
Macros
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_REQUEST 183
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_REQUEST_LEN 2
#define MAVLINK_MSG_ID_183_LEN 2
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_REQUEST_CRC 85
#define MAVLINK_MSG_ID_183_CRC 85
#define MAVLINK_MESSAGE_INFO_AUTOPILOT_VERSION_REQUEST
Typedefs
typedef struct __mavlink_autopilot_version_request_t mavlink_autopilot_version_request_t
Functions
static uint16_t mavlink_msg_autopilot_version_request_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a autopilot_version_request message.
static uint16_t mavlink_msg_autopilot_version_request_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a autopilot_version_request message on a channel.
static uint16_t mavlink_msg_autopilot_version_request_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_autopilot_version_request_t *autopilot_version_request)
Encode a autopilot_version_request struct.
static uint16_t mavlink_msg_autopilot_version_request_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_autopilot_version_request_t *autopilot_version_request)
Encode a autopilot_version_request struct on a channel.
static uint8_t mavlink_msg_autopilot_version_request_get_target_system (const mavlink_message_t *msg)
Send a autopilot_version_request message.
static uint8_t mavlink_msg_autopilot_version_request_get_target_component (const mavlink_message_t *msg)
Get field target_component from autopilot_version_request message.
static void mavlink_msg_autopilot_version_request_decode (const mavlink_message_t *msg, mavlink_autopilot_version_request_t *autopilot_version_request)
Decode a autopilot_version_request message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AUTOPILOT_VERSION_REQUEST
Value:
{ \
    "AUTOPILOT_VERSION_REQUEST", \
    2, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_autopilot_version_request_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_autopilot_version_request_t, target_component) }, \
         } \
}
Definition at line 19 of file mavlink_msg_autopilot_version_request.h.
#define MAVLINK_MSG_ID_183_CRC 85
Definition at line 15 of file mavlink_msg_autopilot_version_request.h.
#define MAVLINK_MSG_ID_183_LEN 2
Definition at line 12 of file mavlink_msg_autopilot_version_request.h.
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_REQUEST 183
Definition at line 3 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_pack(), and mavlink_msg_autopilot_version_request_pack_chan().
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_REQUEST_CRC 85
Definition at line 14 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_pack(), and mavlink_msg_autopilot_version_request_pack_chan().
#define MAVLINK_MSG_ID_AUTOPILOT_VERSION_REQUEST_LEN 2
Definition at line 11 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_decode(), mavlink_msg_autopilot_version_request_pack(), and mavlink_msg_autopilot_version_request_pack_chan().
Typedef Documentation
typedef struct __mavlink_autopilot_version_request_t mavlink_autopilot_version_request_t
Function Documentation
static void mavlink_msg_autopilot_version_request_decode (const mavlink_message_t * msg, mavlink_autopilot_version_request_t * autopilot_version_request) inline static
Decode a autopilot_version_request message into a struct.
Parameters
msg The message to decode
autopilot_version_request C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_test_autopilot_version_request().
static uint16_t mavlink_msg_autopilot_version_request_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_autopilot_version_request_t * autopilot_version_request) inline static
Encode a autopilot_version_request struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
autopilot_version_request C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_test_autopilot_version_request().
static uint16_t mavlink_msg_autopilot_version_request_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_autopilot_version_request_t * autopilot_version_request) inline static
Encode a autopilot_version_request struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
autopilot_version_request C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_autopilot_version_request.h.
static uint8_t mavlink_msg_autopilot_version_request_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from autopilot_version_request message.
Returns
Component ID
Definition at line 214 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_decode().
static uint8_t mavlink_msg_autopilot_version_request_get_target_system (const mavlink_message_t * msg) inline static
Send a autopilot_version_request message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID Get field target_system from autopilot_version_request message
Returns
System ID
Definition at line 204 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_decode().
static uint16_t mavlink_msg_autopilot_version_request_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a autopilot_version_request message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_encode(), and mavlink_test_autopilot_version_request().
static uint16_t mavlink_msg_autopilot_version_request_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a autopilot_version_request message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_autopilot_version_request.h.
Referenced by mavlink_msg_autopilot_version_request_encode_chan(), and mavlink_test_autopilot_version_request().