APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_rc_channels_override.h File Reference
mavlink_msg_rc_channels_override.h File Reference
Classes
struct __mavlink_rc_channels_override_t
Macros
#define MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE 70
#define MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE_LEN 18
#define MAVLINK_MSG_ID_70_LEN 18
#define MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE_CRC 124
#define MAVLINK_MSG_ID_70_CRC 124
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS_OVERRIDE
Typedefs
typedef struct __mavlink_rc_channels_override_t mavlink_rc_channels_override_t
Functions
static uint16_t mavlink_msg_rc_channels_override_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw)
Pack a rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw)
Pack a rc_channels_override message on a channel.
static uint16_t mavlink_msg_rc_channels_override_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rc_channels_override_t *rc_channels_override)
Encode a rc_channels_override struct.
static uint16_t mavlink_msg_rc_channels_override_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_rc_channels_override_t *rc_channels_override)
Encode a rc_channels_override struct on a channel.
static uint8_t mavlink_msg_rc_channels_override_get_target_system (const mavlink_message_t *msg)
Send a rc_channels_override message.
static uint8_t mavlink_msg_rc_channels_override_get_target_component (const mavlink_message_t *msg)
Get field target_component from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan1_raw (const mavlink_message_t *msg)
Get field chan1_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan2_raw (const mavlink_message_t *msg)
Get field chan2_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan3_raw (const mavlink_message_t *msg)
Get field chan3_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan4_raw (const mavlink_message_t *msg)
Get field chan4_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan5_raw (const mavlink_message_t *msg)
Get field chan5_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan6_raw (const mavlink_message_t *msg)
Get field chan6_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan7_raw (const mavlink_message_t *msg)
Get field chan7_raw from rc_channels_override message.
static uint16_t mavlink_msg_rc_channels_override_get_chan8_raw (const mavlink_message_t *msg)
Get field chan8_raw from rc_channels_override message.
static void mavlink_msg_rc_channels_override_decode (const mavlink_message_t *msg, mavlink_rc_channels_override_t *rc_channels_override)
Decode a rc_channels_override message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS_OVERRIDE
Value:
{ \
    "RC_CHANNELS_OVERRIDE", \
    10, \
    {  { "chan1_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_rc_channels_override_t, chan1_raw) }, \
         { "chan2_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_rc_channels_override_t, chan2_raw) }, \
         { "chan3_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_rc_channels_override_t, chan3_raw) }, \
         { "chan4_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_rc_channels_override_t, chan4_raw) }, \
         { "chan5_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_rc_channels_override_t, chan5_raw) }, \
         { "chan6_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_rc_channels_override_t, chan6_raw) }, \
         { "chan7_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_rc_channels_override_t, chan7_raw) }, \
         { "chan8_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 14, offsetof(mavlink_rc_channels_override_t, chan8_raw) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 16, offsetof(mavlink_rc_channels_override_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 17, offsetof(mavlink_rc_channels_override_t, target_component) }, \
         } \
}
Definition at line 27 of file mavlink_msg_rc_channels_override.h.
#define MAVLINK_MSG_ID_70_CRC 124
Definition at line 23 of file mavlink_msg_rc_channels_override.h.
#define MAVLINK_MSG_ID_70_LEN 18
Definition at line 20 of file mavlink_msg_rc_channels_override.h.
#define MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE 70
Definition at line 3 of file mavlink_msg_rc_channels_override.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_rc_channels_override_pack(), and mavlink_msg_rc_channels_override_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE_CRC 124
Definition at line 22 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_pack(), and mavlink_msg_rc_channels_override_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE_LEN 18
Definition at line 19 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode(), mavlink_msg_rc_channels_override_pack(), and mavlink_msg_rc_channels_override_pack_chan().
Typedef Documentation
typedef struct __mavlink_rc_channels_override_t mavlink_rc_channels_override_t
Function Documentation
static void mavlink_msg_rc_channels_override_decode (const mavlink_message_t * msg, mavlink_rc_channels_override_t * rc_channels_override) inline static
Decode a rc_channels_override message into a struct.
Parameters
msg The message to decode
rc_channels_override C-struct to decode the message contents into
Definition at line 409 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_test_rc_channels_override().
static uint16_t mavlink_msg_rc_channels_override_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rc_channels_override_t * rc_channels_override) inline static
Encode a rc_channels_override struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rc_channels_override C-struct to read the message contents from
Definition at line 171 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_test_rc_channels_override().
static uint16_t mavlink_msg_rc_channels_override_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_rc_channels_override_t * rc_channels_override) inline static
Encode a rc_channels_override struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rc_channels_override C-struct to read the message contents from
Definition at line 185 of file mavlink_msg_rc_channels_override.h.
static uint16_t mavlink_msg_rc_channels_override_get_chan1_raw (const mavlink_message_t * msg) inline static
Get field chan1_raw from rc_channels_override message.
Returns
RC channel 1 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 328 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan2_raw (const mavlink_message_t * msg) inline static
Get field chan2_raw from rc_channels_override message.
Returns
RC channel 2 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 338 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan3_raw (const mavlink_message_t * msg) inline static
Get field chan3_raw from rc_channels_override message.
Returns
RC channel 3 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 348 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan4_raw (const mavlink_message_t * msg) inline static
Get field chan4_raw from rc_channels_override message.
Returns
RC channel 4 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 358 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan5_raw (const mavlink_message_t * msg) inline static
Get field chan5_raw from rc_channels_override message.
Returns
RC channel 5 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 368 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan6_raw (const mavlink_message_t * msg) inline static
Get field chan6_raw from rc_channels_override message.
Returns
RC channel 6 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 378 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan7_raw (const mavlink_message_t * msg) inline static
Get field chan7_raw from rc_channels_override message.
Returns
RC channel 7 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 388 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_get_chan8_raw (const mavlink_message_t * msg) inline static
Get field chan8_raw from rc_channels_override message.
Returns
RC channel 8 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Definition at line 398 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_decode().
static uint8_t mavlink_msg_rc_channels_override_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from rc_channels_override message.
Returns
Component ID
Definition at line 318 of file mavlink_msg_rc_channels_override.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_rc_channels_override_decode().
static uint8_t mavlink_msg_rc_channels_override_get_target_system (const mavlink_message_t * msg) inline static
Send a rc_channels_override message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX means to ignore this field. Get field target_system from rc_channels_override message
Returns
System ID
Definition at line 308 of file mavlink_msg_rc_channels_override.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_rc_channels_override_decode().
static uint16_t mavlink_msg_rc_channels_override_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw) inline static
Pack a rc_channels_override message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_encode(), and mavlink_test_rc_channels_override().
static uint16_t mavlink_msg_rc_channels_override_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw) inline static
Pack a rc_channels_override message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
chan1_raw RC channel 1 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan2_raw RC channel 2 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan3_raw RC channel 3 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan4_raw RC channel 4 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan5_raw RC channel 5 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan6_raw RC channel 6 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan7_raw RC channel 7 value, in microseconds. A value of UINT16_MAX means to ignore this field.
chan8_raw RC channel 8 value, in microseconds. A value of UINT16_MAX means to ignore this field.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 121 of file mavlink_msg_rc_channels_override.h.
Referenced by mavlink_msg_rc_channels_override_encode_chan(), and mavlink_test_rc_channels_override().