APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_control.h File Reference
mavlink_msg_gimbal_control.h File Reference
Classes
struct __mavlink_gimbal_control_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_CONTROL 201
#define MAVLINK_MSG_ID_GIMBAL_CONTROL_LEN 14
#define MAVLINK_MSG_ID_201_LEN 14
#define MAVLINK_MSG_ID_GIMBAL_CONTROL_CRC 205
#define MAVLINK_MSG_ID_201_CRC 205
#define MAVLINK_MESSAGE_INFO_GIMBAL_CONTROL
Typedefs
typedef struct __mavlink_gimbal_control_t mavlink_gimbal_control_t
Functions
static uint16_t mavlink_msg_gimbal_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float demanded_rate_x, float demanded_rate_y, float demanded_rate_z)
Pack a gimbal_control message.
static uint16_t mavlink_msg_gimbal_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float demanded_rate_x, float demanded_rate_y, float demanded_rate_z)
Pack a gimbal_control message on a channel.
static uint16_t mavlink_msg_gimbal_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_control_t *gimbal_control)
Encode a gimbal_control struct.
static uint16_t mavlink_msg_gimbal_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_control_t *gimbal_control)
Encode a gimbal_control struct on a channel.
static uint8_t mavlink_msg_gimbal_control_get_target_system (const mavlink_message_t *msg)
Send a gimbal_control message.
static uint8_t mavlink_msg_gimbal_control_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_control message.
static float mavlink_msg_gimbal_control_get_demanded_rate_x (const mavlink_message_t *msg)
Get field demanded_rate_x from gimbal_control message.
static float mavlink_msg_gimbal_control_get_demanded_rate_y (const mavlink_message_t *msg)
Get field demanded_rate_y from gimbal_control message.
static float mavlink_msg_gimbal_control_get_demanded_rate_z (const mavlink_message_t *msg)
Get field demanded_rate_z from gimbal_control message.
static void mavlink_msg_gimbal_control_decode (const mavlink_message_t *msg, mavlink_gimbal_control_t *gimbal_control)
Decode a gimbal_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_CONTROL
Value:
{ \
    "GIMBAL_CONTROL", \
    5, \
    {  { "demanded_rate_x", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_gimbal_control_t, demanded_rate_x) }, \
         { "demanded_rate_y", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_gimbal_control_t, demanded_rate_y) }, \
         { "demanded_rate_z", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_gimbal_control_t, demanded_rate_z) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 12, offsetof(mavlink_gimbal_control_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 13, offsetof(mavlink_gimbal_control_t, target_component) }, \
         } \
}
Definition at line 22 of file mavlink_msg_gimbal_control.h.
#define MAVLINK_MSG_ID_201_CRC 205
Definition at line 18 of file mavlink_msg_gimbal_control.h.
#define MAVLINK_MSG_ID_201_LEN 14
Definition at line 15 of file mavlink_msg_gimbal_control.h.
#define MAVLINK_MSG_ID_GIMBAL_CONTROL 201
Definition at line 3 of file mavlink_msg_gimbal_control.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_gimbal_control_pack(), mavlink_msg_gimbal_control_pack_chan(), and SITL::Gimbal::send_report().
#define MAVLINK_MSG_ID_GIMBAL_CONTROL_CRC 205
Definition at line 17 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_pack(), and mavlink_msg_gimbal_control_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_CONTROL_LEN 14
Definition at line 14 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_decode(), mavlink_msg_gimbal_control_pack(), and mavlink_msg_gimbal_control_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_control_t mavlink_gimbal_control_t
Function Documentation
static void mavlink_msg_gimbal_control_decode (const mavlink_message_t * msg, mavlink_gimbal_control_t * gimbal_control) inline static
Decode a gimbal_control message into a struct.
Parameters
msg The message to decode
gimbal_control C-struct to decode the message contents into
Definition at line 294 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_test_gimbal_control(), and SITL::Gimbal::send_report().
static uint16_t mavlink_msg_gimbal_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_control_t * gimbal_control) inline static
Encode a gimbal_control struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_control C-struct to read the message contents from
Definition at line 131 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_test_gimbal_control().
static uint16_t mavlink_msg_gimbal_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_control_t * gimbal_control) inline static
Encode a gimbal_control struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_control C-struct to read the message contents from
Definition at line 145 of file mavlink_msg_gimbal_control.h.
static float mavlink_msg_gimbal_control_get_demanded_rate_x (const mavlink_message_t * msg) inline static
Get field demanded_rate_x from gimbal_control message.
Returns
Demanded angular rate X (rad/s)
Definition at line 263 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_decode().
static float mavlink_msg_gimbal_control_get_demanded_rate_y (const mavlink_message_t * msg) inline static
Get field demanded_rate_y from gimbal_control message.
Returns
Demanded angular rate Y (rad/s)
Definition at line 273 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_decode().
static float mavlink_msg_gimbal_control_get_demanded_rate_z (const mavlink_message_t * msg) inline static
Get field demanded_rate_z from gimbal_control message.
Returns
Demanded angular rate Z (rad/s)
Definition at line 283 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_decode().
static uint8_t mavlink_msg_gimbal_control_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_control message.
Returns
Component ID
Definition at line 253 of file mavlink_msg_gimbal_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_gimbal_control_decode().
static uint8_t mavlink_msg_gimbal_control_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_control message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
demanded_rate_x Demanded angular rate X (rad/s)
demanded_rate_y Demanded angular rate Y (rad/s)
demanded_rate_z Demanded angular rate Z (rad/s) Get field target_system from gimbal_control message
Returns
System ID
Definition at line 243 of file mavlink_msg_gimbal_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_gimbal_control_decode().
static uint16_t mavlink_msg_gimbal_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float demanded_rate_x, float demanded_rate_y, float demanded_rate_z) inline static
Pack a gimbal_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
demanded_rate_x Demanded angular rate X (rad/s)
demanded_rate_y Demanded angular rate Y (rad/s)
demanded_rate_z Demanded angular rate Z (rad/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_encode(), and mavlink_test_gimbal_control().
static uint16_t mavlink_msg_gimbal_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float demanded_rate_x, float demanded_rate_y, float demanded_rate_z) inline static
Pack a gimbal_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
demanded_rate_x Demanded angular rate X (rad/s)
demanded_rate_y Demanded angular rate Y (rad/s)
demanded_rate_z Demanded angular rate Z (rad/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 91 of file mavlink_msg_gimbal_control.h.
Referenced by mavlink_msg_gimbal_control_encode_chan(), and mavlink_test_gimbal_control().