APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_gps_status.h File Reference
mavlink_msg_gps_status.h File Reference
Classes
struct __mavlink_gps_status_t
Macros
#define MAVLINK_MSG_ID_GPS_STATUS 25
#define MAVLINK_MSG_ID_GPS_STATUS_LEN 101
#define MAVLINK_MSG_ID_25_LEN 101
#define MAVLINK_MSG_ID_GPS_STATUS_CRC 23
#define MAVLINK_MSG_ID_25_CRC 23
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_PRN_LEN 20
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_USED_LEN 20
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_ELEVATION_LEN 20
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_AZIMUTH_LEN 20
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_SNR_LEN 20
#define MAVLINK_MESSAGE_INFO_GPS_STATUS
Typedefs
typedef struct __mavlink_gps_status_t mavlink_gps_status_t
Functions
static uint16_t mavlink_msg_gps_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t satellites_visible, const uint8_t *satellite_prn, const uint8_t *satellite_used, const uint8_t *satellite_elevation, const uint8_t *satellite_azimuth, const uint8_t *satellite_snr)
Pack a gps_status message.
static uint16_t mavlink_msg_gps_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t satellites_visible, const uint8_t *satellite_prn, const uint8_t *satellite_used, const uint8_t *satellite_elevation, const uint8_t *satellite_azimuth, const uint8_t *satellite_snr)
Pack a gps_status message on a channel.
static uint16_t mavlink_msg_gps_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gps_status_t *gps_status)
Encode a gps_status struct.
static uint16_t mavlink_msg_gps_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gps_status_t *gps_status)
Encode a gps_status struct on a channel.
static uint8_t mavlink_msg_gps_status_get_satellites_visible (const mavlink_message_t *msg)
Send a gps_status message.
static uint16_t mavlink_msg_gps_status_get_satellite_prn (const mavlink_message_t *msg, uint8_t *satellite_prn)
Get field satellite_prn from gps_status message.
static uint16_t mavlink_msg_gps_status_get_satellite_used (const mavlink_message_t *msg, uint8_t *satellite_used)
Get field satellite_used from gps_status message.
static uint16_t mavlink_msg_gps_status_get_satellite_elevation (const mavlink_message_t *msg, uint8_t *satellite_elevation)
Get field satellite_elevation from gps_status message.
static uint16_t mavlink_msg_gps_status_get_satellite_azimuth (const mavlink_message_t *msg, uint8_t *satellite_azimuth)
Get field satellite_azimuth from gps_status message.
static uint16_t mavlink_msg_gps_status_get_satellite_snr (const mavlink_message_t *msg, uint8_t *satellite_snr)
Get field satellite_snr from gps_status message.
static void mavlink_msg_gps_status_decode (const mavlink_message_t *msg, mavlink_gps_status_t *gps_status)
Decode a gps_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GPS_STATUS
Value:
{ \
    "GPS_STATUS", \
    6, \
    {  { "satellites_visible", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gps_status_t, satellites_visible) }, \
         { "satellite_prn", NULL, MAVLINK_TYPE_UINT8_T, 20, 1, offsetof(mavlink_gps_status_t, satellite_prn) }, \
         { "satellite_used", NULL, MAVLINK_TYPE_UINT8_T, 20, 21, offsetof(mavlink_gps_status_t, satellite_used) }, \
         { "satellite_elevation", NULL, MAVLINK_TYPE_UINT8_T, 20, 41, offsetof(mavlink_gps_status_t, satellite_elevation) }, \
         { "satellite_azimuth", NULL, MAVLINK_TYPE_UINT8_T, 20, 61, offsetof(mavlink_gps_status_t, satellite_azimuth) }, \
         { "satellite_snr", NULL, MAVLINK_TYPE_UINT8_T, 20, 81, offsetof(mavlink_gps_status_t, satellite_snr) }, \
         } \
}
Definition at line 27 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_AZIMUTH_LEN 20
Definition at line 24 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_ELEVATION_LEN 20
Definition at line 23 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_PRN_LEN 20
Definition at line 21 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_SNR_LEN 20
Definition at line 25 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_GPS_STATUS_FIELD_SATELLITE_USED_LEN 20
Definition at line 22 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_ID_25_CRC 23
Definition at line 19 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_ID_25_LEN 101
Definition at line 16 of file mavlink_msg_gps_status.h.
#define MAVLINK_MSG_ID_GPS_STATUS 25
Definition at line 3 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_pack(), and mavlink_msg_gps_status_pack_chan().
#define MAVLINK_MSG_ID_GPS_STATUS_CRC 23
Definition at line 18 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_pack(), and mavlink_msg_gps_status_pack_chan().
#define MAVLINK_MSG_ID_GPS_STATUS_LEN 101
Definition at line 15 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode(), mavlink_msg_gps_status_pack(), and mavlink_msg_gps_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_gps_status_t mavlink_gps_status_t
Function Documentation
static void mavlink_msg_gps_status_decode (const mavlink_message_t * msg, mavlink_gps_status_t * gps_status) inline static
Decode a gps_status message into a struct.
Parameters
msg The message to decode
gps_status C-struct to decode the message contents into
Definition at line 313 of file mavlink_msg_gps_status.h.
Referenced by mavlink_test_gps_status().
static uint16_t mavlink_msg_gps_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gps_status_t * gps_status) inline static
Encode a gps_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gps_status C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_gps_status.h.
Referenced by mavlink_test_gps_status().
static uint16_t mavlink_msg_gps_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gps_status_t * gps_status) inline static
Encode a gps_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gps_status C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_gps_status.h.
static uint16_t mavlink_msg_gps_status_get_satellite_azimuth (const mavlink_message_t * msg, uint8_t * satellite_azimuth) inline static
Get field satellite_azimuth from gps_status message.
Returns
Direction of satellite, 0: 0 deg, 255: 360 deg.
Definition at line 292 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode().
static uint16_t mavlink_msg_gps_status_get_satellite_elevation (const mavlink_message_t * msg, uint8_t * satellite_elevation) inline static
Get field satellite_elevation from gps_status message.
Returns
Elevation (0: right on top of receiver, 90: on the horizon) of satellite
Definition at line 282 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode().
static uint16_t mavlink_msg_gps_status_get_satellite_prn (const mavlink_message_t * msg, uint8_t * satellite_prn) inline static
Get field satellite_prn from gps_status message.
Returns
Global satellite ID
Definition at line 262 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode().
static uint16_t mavlink_msg_gps_status_get_satellite_snr (const mavlink_message_t * msg, uint8_t * satellite_snr) inline static
Get field satellite_snr from gps_status message.
Returns
Signal to noise ratio of satellite
Definition at line 302 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode().
static uint16_t mavlink_msg_gps_status_get_satellite_used (const mavlink_message_t * msg, uint8_t * satellite_used) inline static
Get field satellite_used from gps_status message.
Returns
0: Satellite not used, 1: used for localization
Definition at line 272 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode().
static uint8_t mavlink_msg_gps_status_get_satellites_visible (const mavlink_message_t * msg) inline static
Send a gps_status message.
Parameters
chan MAVLink channel to send the message
satellites_visible Number of satellites visible
satellite_prn Global satellite ID
satellite_used 0: Satellite not used, 1: used for localization
satellite_elevation Elevation (0: right on top of receiver, 90: on the horizon) of satellite
satellite_azimuth Direction of satellite, 0: 0 deg, 255: 360 deg.
satellite_snr Signal to noise ratio of satellite Get field satellites_visible from gps_status message
Returns
Number of satellites visible
Definition at line 252 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_decode().
static uint16_t mavlink_msg_gps_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t satellites_visible, const uint8_t * satellite_prn, const uint8_t * satellite_used, const uint8_t * satellite_elevation, const uint8_t * satellite_azimuth, const uint8_t * satellite_snr) inline static
Pack a gps_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
satellites_visible Number of satellites visible
satellite_prn Global satellite ID
satellite_used 0: Satellite not used, 1: used for localization
satellite_elevation Elevation (0: right on top of receiver, 90: on the horizon) of satellite
satellite_azimuth Direction of satellite, 0: 0 deg, 255: 360 deg.
satellite_snr Signal to noise ratio of satellite
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 54 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_encode(), and mavlink_test_gps_status().
static uint16_t mavlink_msg_gps_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t satellites_visible, const uint8_t * satellite_prn, const uint8_t * satellite_used, const uint8_t * satellite_elevation, const uint8_t * satellite_azimuth, const uint8_t * satellite_snr) inline static
Pack a gps_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
satellites_visible Number of satellites visible
satellite_prn Global satellite ID
satellite_used 0: Satellite not used, 1: used for localization
satellite_elevation Elevation (0: right on top of receiver, 90: on the horizon) of satellite
satellite_azimuth Direction of satellite, 0: 0 deg, 255: 360 deg.
satellite_snr Signal to noise ratio of satellite
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 99 of file mavlink_msg_gps_status.h.
Referenced by mavlink_msg_gps_status_encode_chan(), and mavlink_test_gps_status().