APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_system_time.h File Reference
mavlink_msg_system_time.h File Reference
Classes
struct __mavlink_system_time_t
Macros
#define MAVLINK_MSG_ID_SYSTEM_TIME 2
#define MAVLINK_MSG_ID_SYSTEM_TIME_LEN 12
#define MAVLINK_MSG_ID_2_LEN 12
#define MAVLINK_MSG_ID_SYSTEM_TIME_CRC 137
#define MAVLINK_MSG_ID_2_CRC 137
#define MAVLINK_MESSAGE_INFO_SYSTEM_TIME
Typedefs
typedef struct __mavlink_system_time_t mavlink_system_time_t
Functions
static uint16_t mavlink_msg_system_time_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_unix_usec, uint32_t time_boot_ms)
Pack a system_time message.
static uint16_t mavlink_msg_system_time_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_unix_usec, uint32_t time_boot_ms)
Pack a system_time message on a channel.
static uint16_t mavlink_msg_system_time_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_system_time_t *system_time)
Encode a system_time struct.
static uint16_t mavlink_msg_system_time_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_system_time_t *system_time)
Encode a system_time struct on a channel.
static uint64_t mavlink_msg_system_time_get_time_unix_usec (const mavlink_message_t *msg)
Send a system_time message.
static uint32_t mavlink_msg_system_time_get_time_boot_ms (const mavlink_message_t *msg)
Get field time_boot_ms from system_time message.
static void mavlink_msg_system_time_decode (const mavlink_message_t *msg, mavlink_system_time_t *system_time)
Decode a system_time message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SYSTEM_TIME
Value:
{ \
    "SYSTEM_TIME", \
    2, \
    {  { "time_unix_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_system_time_t, time_unix_usec) }, \
         { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 8, offsetof(mavlink_system_time_t, time_boot_ms) }, \
         } \
}
Definition at line 19 of file mavlink_msg_system_time.h.
#define MAVLINK_MSG_ID_2_CRC 137
Definition at line 15 of file mavlink_msg_system_time.h.
#define MAVLINK_MSG_ID_2_LEN 12
Definition at line 12 of file mavlink_msg_system_time.h.
#define MAVLINK_MSG_ID_SYSTEM_TIME 2
Definition at line 3 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_pack(), and mavlink_msg_system_time_pack_chan().
#define MAVLINK_MSG_ID_SYSTEM_TIME_CRC 137
Definition at line 14 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_pack(), and mavlink_msg_system_time_pack_chan().
#define MAVLINK_MSG_ID_SYSTEM_TIME_LEN 12
Definition at line 11 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_decode(), mavlink_msg_system_time_pack(), and mavlink_msg_system_time_pack_chan().
Typedef Documentation
typedef struct __mavlink_system_time_t mavlink_system_time_t
Function Documentation
static void mavlink_msg_system_time_decode (const mavlink_message_t * msg, mavlink_system_time_t * system_time) inline static
Decode a system_time message into a struct.
Parameters
msg The message to decode
system_time C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_system_time.h.
Referenced by mavlink_test_system_time().
static uint16_t mavlink_msg_system_time_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_system_time_t * system_time) inline static
Encode a system_time struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
system_time C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_system_time.h.
Referenced by mavlink_test_system_time().
static uint16_t mavlink_msg_system_time_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_system_time_t * system_time) inline static
Encode a system_time struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
system_time C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_system_time.h.
static uint32_t mavlink_msg_system_time_get_time_boot_ms (const mavlink_message_t * msg) inline static
Get field time_boot_ms from system_time message.
Returns
Timestamp of the component clock since boot time in milliseconds.
Definition at line 214 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_decode().
static uint64_t mavlink_msg_system_time_get_time_unix_usec (const mavlink_message_t * msg) inline static
Send a system_time message.
Parameters
chan MAVLink channel to send the message
time_unix_usec Timestamp of the master clock in microseconds since UNIX epoch.
time_boot_ms Timestamp of the component clock since boot time in milliseconds. Get field time_unix_usec from system_time message
Returns
Timestamp of the master clock in microseconds since UNIX epoch.
Definition at line 204 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_decode().
static uint16_t mavlink_msg_system_time_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_unix_usec, uint32_t time_boot_ms) inline static
Pack a system_time message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_unix_usec Timestamp of the master clock in microseconds since UNIX epoch.
time_boot_ms Timestamp of the component clock since boot time in milliseconds.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_encode(), and mavlink_test_system_time().
static uint16_t mavlink_msg_system_time_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_unix_usec, uint32_t time_boot_ms) inline static
Pack a system_time message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_unix_usec Timestamp of the master clock in microseconds since UNIX epoch.
time_boot_ms Timestamp of the component clock since boot time in milliseconds.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_system_time.h.
Referenced by mavlink_msg_system_time_encode_chan(), and mavlink_test_system_time().