APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_timesync.h File Reference
mavlink_msg_timesync.h File Reference
Classes
struct __mavlink_timesync_t
Macros
#define MAVLINK_MSG_ID_TIMESYNC 111
#define MAVLINK_MSG_ID_TIMESYNC_LEN 16
#define MAVLINK_MSG_ID_111_LEN 16
#define MAVLINK_MSG_ID_TIMESYNC_CRC 34
#define MAVLINK_MSG_ID_111_CRC 34
#define MAVLINK_MESSAGE_INFO_TIMESYNC
Typedefs
typedef struct __mavlink_timesync_t mavlink_timesync_t
Functions
static uint16_t mavlink_msg_timesync_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, int64_t tc1, int64_t ts1)
Pack a timesync message.
static uint16_t mavlink_msg_timesync_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, int64_t tc1, int64_t ts1)
Pack a timesync message on a channel.
static uint16_t mavlink_msg_timesync_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_timesync_t *timesync)
Encode a timesync struct.
static uint16_t mavlink_msg_timesync_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_timesync_t *timesync)
Encode a timesync struct on a channel.
static int64_t mavlink_msg_timesync_get_tc1 (const mavlink_message_t *msg)
Send a timesync message.
static int64_t mavlink_msg_timesync_get_ts1 (const mavlink_message_t *msg)
Get field ts1 from timesync message.
static void mavlink_msg_timesync_decode (const mavlink_message_t *msg, mavlink_timesync_t *timesync)
Decode a timesync message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_TIMESYNC
Value:
{ \
    "TIMESYNC", \
    2, \
    {  { "tc1", NULL, MAVLINK_TYPE_INT64_T, 0, 0, offsetof(mavlink_timesync_t, tc1) }, \
         { "ts1", NULL, MAVLINK_TYPE_INT64_T, 0, 8, offsetof(mavlink_timesync_t, ts1) }, \
         } \
}
Definition at line 19 of file mavlink_msg_timesync.h.
#define MAVLINK_MSG_ID_111_CRC 34
Definition at line 15 of file mavlink_msg_timesync.h.
#define MAVLINK_MSG_ID_111_LEN 16
Definition at line 12 of file mavlink_msg_timesync.h.
#define MAVLINK_MSG_ID_TIMESYNC 111
Definition at line 3 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_pack(), and mavlink_msg_timesync_pack_chan().
#define MAVLINK_MSG_ID_TIMESYNC_CRC 34
Definition at line 14 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_pack(), and mavlink_msg_timesync_pack_chan().
#define MAVLINK_MSG_ID_TIMESYNC_LEN 16
Definition at line 11 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_decode(), mavlink_msg_timesync_pack(), and mavlink_msg_timesync_pack_chan().
Typedef Documentation
typedef struct __mavlink_timesync_t mavlink_timesync_t
Function Documentation
static void mavlink_msg_timesync_decode (const mavlink_message_t * msg, mavlink_timesync_t * timesync) inline static
Decode a timesync message into a struct.
Parameters
msg The message to decode
timesync C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_timesync.h.
Referenced by mavlink_test_timesync().
static uint16_t mavlink_msg_timesync_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_timesync_t * timesync) inline static
Encode a timesync struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
timesync C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_timesync.h.
Referenced by mavlink_test_timesync().
static uint16_t mavlink_msg_timesync_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_timesync_t * timesync) inline static
Encode a timesync struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
timesync C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_timesync.h.
static int64_t mavlink_msg_timesync_get_tc1 (const mavlink_message_t * msg) inline static
Send a timesync message.
Parameters
chan MAVLink channel to send the message
tc1 Time sync timestamp 1
ts1 Time sync timestamp 2 Get field tc1 from timesync message
Returns
Time sync timestamp 1
Definition at line 204 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_decode().
static int64_t mavlink_msg_timesync_get_ts1 (const mavlink_message_t * msg) inline static
Get field ts1 from timesync message.
Returns
Time sync timestamp 2
Definition at line 214 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_decode().
static uint16_t mavlink_msg_timesync_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, int64_t tc1, int64_t ts1) inline static
Pack a timesync message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
tc1 Time sync timestamp 1
ts1 Time sync timestamp 2
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_encode(), and mavlink_test_timesync().
static uint16_t mavlink_msg_timesync_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, int64_t tc1, int64_t ts1) inline static
Pack a timesync message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
tc1 Time sync timestamp 1
ts1 Time sync timestamp 2
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_timesync.h.
Referenced by mavlink_msg_timesync_encode_chan(), and mavlink_test_timesync().