APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_param_map_rc.h File Reference
mavlink_msg_param_map_rc.h File Reference
Classes
struct __mavlink_param_map_rc_t
Macros
#define MAVLINK_MSG_ID_PARAM_MAP_RC 50
#define MAVLINK_MSG_ID_PARAM_MAP_RC_LEN 37
#define MAVLINK_MSG_ID_50_LEN 37
#define MAVLINK_MSG_ID_PARAM_MAP_RC_CRC 78
#define MAVLINK_MSG_ID_50_CRC 78
#define MAVLINK_MSG_PARAM_MAP_RC_FIELD_PARAM_ID_LEN 16
#define MAVLINK_MESSAGE_INFO_PARAM_MAP_RC
Typedefs
typedef struct __mavlink_param_map_rc_t mavlink_param_map_rc_t
Functions
static uint16_t mavlink_msg_param_map_rc_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, const char *param_id, int16_t param_index, uint8_t parameter_rc_channel_index, float param_value0, float scale, float param_value_min, float param_value_max)
Pack a param_map_rc message.
static uint16_t mavlink_msg_param_map_rc_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, const char *param_id, int16_t param_index, uint8_t parameter_rc_channel_index, float param_value0, float scale, float param_value_min, float param_value_max)
Pack a param_map_rc message on a channel.
static uint16_t mavlink_msg_param_map_rc_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_param_map_rc_t *param_map_rc)
Encode a param_map_rc struct.
static uint16_t mavlink_msg_param_map_rc_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_param_map_rc_t *param_map_rc)
Encode a param_map_rc struct on a channel.
static uint8_t mavlink_msg_param_map_rc_get_target_system (const mavlink_message_t *msg)
Send a param_map_rc message.
static uint8_t mavlink_msg_param_map_rc_get_target_component (const mavlink_message_t *msg)
Get field target_component from param_map_rc message.
static uint16_t mavlink_msg_param_map_rc_get_param_id (const mavlink_message_t *msg, char *param_id)
Get field param_id from param_map_rc message.
static int16_t mavlink_msg_param_map_rc_get_param_index (const mavlink_message_t *msg)
Get field param_index from param_map_rc message.
static uint8_t mavlink_msg_param_map_rc_get_parameter_rc_channel_index (const mavlink_message_t *msg)
Get field parameter_rc_channel_index from param_map_rc message.
static float mavlink_msg_param_map_rc_get_param_value0 (const mavlink_message_t *msg)
Get field param_value0 from param_map_rc message.
static float mavlink_msg_param_map_rc_get_scale (const mavlink_message_t *msg)
Get field scale from param_map_rc message.
static float mavlink_msg_param_map_rc_get_param_value_min (const mavlink_message_t *msg)
Get field param_value_min from param_map_rc message.
static float mavlink_msg_param_map_rc_get_param_value_max (const mavlink_message_t *msg)
Get field param_value_max from param_map_rc message.
static void mavlink_msg_param_map_rc_decode (const mavlink_message_t *msg, mavlink_param_map_rc_t *param_map_rc)
Decode a param_map_rc message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_PARAM_MAP_RC
Value:
{ \
    "PARAM_MAP_RC", \
    9, \
    {  { "param_value0", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_param_map_rc_t, param_value0) }, \
         { "scale", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_param_map_rc_t, scale) }, \
         { "param_value_min", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_param_map_rc_t, param_value_min) }, \
         { "param_value_max", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_param_map_rc_t, param_value_max) }, \
         { "param_index", NULL, MAVLINK_TYPE_INT16_T, 0, 16, offsetof(mavlink_param_map_rc_t, param_index) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 18, offsetof(mavlink_param_map_rc_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 19, offsetof(mavlink_param_map_rc_t, target_component) }, \
         { "param_id", NULL, MAVLINK_TYPE_CHAR, 16, 20, offsetof(mavlink_param_map_rc_t, param_id) }, \
         { "parameter_rc_channel_index", NULL, MAVLINK_TYPE_UINT8_T, 0, 36, offsetof(mavlink_param_map_rc_t, parameter_rc_channel_index) }, \
         } \
}
Definition at line 26 of file mavlink_msg_param_map_rc.h.
#define MAVLINK_MSG_ID_50_CRC 78
Definition at line 22 of file mavlink_msg_param_map_rc.h.
#define MAVLINK_MSG_ID_50_LEN 37
Definition at line 19 of file mavlink_msg_param_map_rc.h.
#define MAVLINK_MSG_ID_PARAM_MAP_RC 50
Definition at line 3 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_pack(), and mavlink_msg_param_map_rc_pack_chan().
#define MAVLINK_MSG_ID_PARAM_MAP_RC_CRC 78
Definition at line 21 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_pack(), and mavlink_msg_param_map_rc_pack_chan().
#define MAVLINK_MSG_ID_PARAM_MAP_RC_LEN 37
Definition at line 18 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode(), mavlink_msg_param_map_rc_pack(), and mavlink_msg_param_map_rc_pack_chan().
#define MAVLINK_MSG_PARAM_MAP_RC_FIELD_PARAM_ID_LEN 16
Definition at line 24 of file mavlink_msg_param_map_rc.h.
Typedef Documentation
typedef struct __mavlink_param_map_rc_t mavlink_param_map_rc_t
Function Documentation
static void mavlink_msg_param_map_rc_decode (const mavlink_message_t * msg, mavlink_param_map_rc_t * param_map_rc) inline static
Decode a param_map_rc message into a struct.
Parameters
msg The message to decode
param_map_rc C-struct to decode the message contents into
Definition at line 378 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_test_param_map_rc().
static uint16_t mavlink_msg_param_map_rc_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_param_map_rc_t * param_map_rc) inline static
Encode a param_map_rc struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
param_map_rc C-struct to read the message contents from
Definition at line 159 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_test_param_map_rc().
static uint16_t mavlink_msg_param_map_rc_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_param_map_rc_t * param_map_rc) inline static
Encode a param_map_rc struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
param_map_rc C-struct to read the message contents from
Definition at line 173 of file mavlink_msg_param_map_rc.h.
static uint16_t mavlink_msg_param_map_rc_get_param_id (const mavlink_message_t * msg, char * param_id) inline static
Get field param_id from param_map_rc message.
Returns
Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
Definition at line 307 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static int16_t mavlink_msg_param_map_rc_get_param_index (const mavlink_message_t * msg) inline static
Get field param_index from param_map_rc message.
Returns
Parameter index. Send -1 to use the param ID field as identifier (else the param id will be ignored), send -2 to disable any existing map for this rc_channel_index.
Definition at line 317 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static float mavlink_msg_param_map_rc_get_param_value0 (const mavlink_message_t * msg) inline static
Get field param_value0 from param_map_rc message.
Returns
Initial parameter value
Definition at line 337 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static float mavlink_msg_param_map_rc_get_param_value_max (const mavlink_message_t * msg) inline static
Get field param_value_max from param_map_rc message.
Returns
Maximum param value. The protocol does not define if this overwrites an onboard maximum value. (Depends on implementation)
Definition at line 367 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static float mavlink_msg_param_map_rc_get_param_value_min (const mavlink_message_t * msg) inline static
Get field param_value_min from param_map_rc message.
Returns
Minimum param value. The protocol does not define if this overwrites an onboard minimum value. (Depends on implementation)
Definition at line 357 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static uint8_t mavlink_msg_param_map_rc_get_parameter_rc_channel_index (const mavlink_message_t * msg) inline static
Get field parameter_rc_channel_index from param_map_rc message.
Returns
Index of parameter RC channel. Not equal to the RC channel id. Typically correpsonds to a potentiometer-knob on the RC.
Definition at line 327 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static float mavlink_msg_param_map_rc_get_scale (const mavlink_message_t * msg) inline static
Get field scale from param_map_rc message.
Returns
Scale, maps the RC range [-1, 1] to a parameter value
Definition at line 347 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static uint8_t mavlink_msg_param_map_rc_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from param_map_rc message.
Returns
Component ID
Definition at line 297 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static uint8_t mavlink_msg_param_map_rc_get_target_system (const mavlink_message_t * msg) inline static
Send a param_map_rc message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_index Parameter index. Send -1 to use the param ID field as identifier (else the param id will be ignored), send -2 to disable any existing map for this rc_channel_index.
parameter_rc_channel_index Index of parameter RC channel. Not equal to the RC channel id. Typically correpsonds to a potentiometer-knob on the RC.
param_value0 Initial parameter value
scale Scale, maps the RC range [-1, 1] to a parameter value
param_value_min Minimum param value. The protocol does not define if this overwrites an onboard minimum value. (Depends on implementation)
param_value_max Maximum param value. The protocol does not define if this overwrites an onboard maximum value. (Depends on implementation) Get field target_system from param_map_rc message
Returns
System ID
Definition at line 287 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_decode().
static uint16_t mavlink_msg_param_map_rc_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, const char * param_id, int16_t param_index, uint8_t parameter_rc_channel_index, float param_value0, float scale, float param_value_min, float param_value_max) inline static
Pack a param_map_rc message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_index Parameter index. Send -1 to use the param ID field as identifier (else the param id will be ignored), send -2 to disable any existing map for this rc_channel_index.
parameter_rc_channel_index Index of parameter RC channel. Not equal to the RC channel id. Typically correpsonds to a potentiometer-knob on the RC.
param_value0 Initial parameter value
scale Scale, maps the RC range [-1, 1] to a parameter value
param_value_min Minimum param value. The protocol does not define if this overwrites an onboard minimum value. (Depends on implementation)
param_value_max Maximum param value. The protocol does not define if this overwrites an onboard maximum value. (Depends on implementation)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 59 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_encode(), and mavlink_test_param_map_rc().
static uint16_t mavlink_msg_param_map_rc_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, const char * param_id, int16_t param_index, uint8_t parameter_rc_channel_index, float param_value0, float scale, float param_value_min, float param_value_max) inline static
Pack a param_map_rc message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_index Parameter index. Send -1 to use the param ID field as identifier (else the param id will be ignored), send -2 to disable any existing map for this rc_channel_index.
parameter_rc_channel_index Index of parameter RC channel. Not equal to the RC channel id. Typically correpsonds to a potentiometer-knob on the RC.
param_value0 Initial parameter value
scale Scale, maps the RC range [-1, 1] to a parameter value
param_value_min Minimum param value. The protocol does not define if this overwrites an onboard minimum value. (Depends on implementation)
param_value_max Maximum param value. The protocol does not define if this overwrites an onboard maximum value. (Depends on implementation)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 113 of file mavlink_msg_param_map_rc.h.
Referenced by mavlink_msg_param_map_rc_encode_chan(), and mavlink_test_param_map_rc().