APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gopro_heartbeat.h File Reference
mavlink_msg_gopro_heartbeat.h File Reference
Classes
struct __mavlink_gopro_heartbeat_t
Macros
#define MAVLINK_MSG_ID_GOPRO_HEARTBEAT 215
#define MAVLINK_MSG_ID_GOPRO_HEARTBEAT_LEN 1
#define MAVLINK_MSG_ID_215_LEN 1
#define MAVLINK_MSG_ID_GOPRO_HEARTBEAT_CRC 77
#define MAVLINK_MSG_ID_215_CRC 77
#define MAVLINK_MESSAGE_INFO_GOPRO_HEARTBEAT
Typedefs
typedef struct __mavlink_gopro_heartbeat_t mavlink_gopro_heartbeat_t
Functions
static uint16_t mavlink_msg_gopro_heartbeat_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t status)
Pack a gopro_heartbeat message.
static uint16_t mavlink_msg_gopro_heartbeat_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t status)
Pack a gopro_heartbeat message on a channel.
static uint16_t mavlink_msg_gopro_heartbeat_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gopro_heartbeat_t *gopro_heartbeat)
Encode a gopro_heartbeat struct.
static uint16_t mavlink_msg_gopro_heartbeat_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gopro_heartbeat_t *gopro_heartbeat)
Encode a gopro_heartbeat struct on a channel.
static uint8_t mavlink_msg_gopro_heartbeat_get_status (const mavlink_message_t *msg)
Send a gopro_heartbeat message.
static void mavlink_msg_gopro_heartbeat_decode (const mavlink_message_t *msg, mavlink_gopro_heartbeat_t *gopro_heartbeat)
Decode a gopro_heartbeat message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GOPRO_HEARTBEAT
Value:
{ \
    "GOPRO_HEARTBEAT", \
    1, \
    {  { "status", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gopro_heartbeat_t, status) }, \
         } \
}
Definition at line 18 of file mavlink_msg_gopro_heartbeat.h.
#define MAVLINK_MSG_ID_215_CRC 77
Definition at line 14 of file mavlink_msg_gopro_heartbeat.h.
#define MAVLINK_MSG_ID_215_LEN 1
Definition at line 11 of file mavlink_msg_gopro_heartbeat.h.
#define MAVLINK_MSG_ID_GOPRO_HEARTBEAT 215
Definition at line 3 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_msg_gopro_heartbeat_pack(), and mavlink_msg_gopro_heartbeat_pack_chan().
#define MAVLINK_MSG_ID_GOPRO_HEARTBEAT_CRC 77
Definition at line 13 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_msg_gopro_heartbeat_pack(), and mavlink_msg_gopro_heartbeat_pack_chan().
#define MAVLINK_MSG_ID_GOPRO_HEARTBEAT_LEN 1
Definition at line 10 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_msg_gopro_heartbeat_decode(), mavlink_msg_gopro_heartbeat_pack(), and mavlink_msg_gopro_heartbeat_pack_chan().
Typedef Documentation
typedef struct __mavlink_gopro_heartbeat_t mavlink_gopro_heartbeat_t
Function Documentation
static void mavlink_msg_gopro_heartbeat_decode (const mavlink_message_t * msg, mavlink_gopro_heartbeat_t * gopro_heartbeat) inline static
Decode a gopro_heartbeat message into a struct.
Parameters
msg The message to decode
gopro_heartbeat C-struct to decode the message contents into
Definition at line 202 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_test_gopro_heartbeat().
static uint16_t mavlink_msg_gopro_heartbeat_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gopro_heartbeat_t * gopro_heartbeat) inline static
Encode a gopro_heartbeat struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gopro_heartbeat C-struct to read the message contents from
Definition at line 99 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_test_gopro_heartbeat().
static uint16_t mavlink_msg_gopro_heartbeat_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gopro_heartbeat_t * gopro_heartbeat) inline static
Encode a gopro_heartbeat struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gopro_heartbeat C-struct to read the message contents from
Definition at line 113 of file mavlink_msg_gopro_heartbeat.h.
static uint8_t mavlink_msg_gopro_heartbeat_get_status (const mavlink_message_t * msg) inline static
Send a gopro_heartbeat message.
Parameters
chan MAVLink channel to send the message
status Status Get field status from gopro_heartbeat message
Returns
Status
Definition at line 191 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_msg_gopro_heartbeat_decode().
static uint16_t mavlink_msg_gopro_heartbeat_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t status) inline static
Pack a gopro_heartbeat message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
status Status
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_msg_gopro_heartbeat_encode(), and mavlink_test_gopro_heartbeat().
static uint16_t mavlink_msg_gopro_heartbeat_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t status) inline static
Pack a gopro_heartbeat message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
status Status
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 67 of file mavlink_msg_gopro_heartbeat.h.
Referenced by mavlink_msg_gopro_heartbeat_encode_chan(), and mavlink_test_gopro_heartbeat().