APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_landing_target.h File Reference
mavlink_msg_landing_target.h File Reference
Classes
struct __mavlink_landing_target_t
Macros
#define MAVLINK_MSG_ID_LANDING_TARGET 149
#define MAVLINK_MSG_ID_LANDING_TARGET_LEN 30
#define MAVLINK_MSG_ID_149_LEN 30
#define MAVLINK_MSG_ID_LANDING_TARGET_CRC 200
#define MAVLINK_MSG_ID_149_CRC 200
#define MAVLINK_MESSAGE_INFO_LANDING_TARGET
Typedefs
typedef struct __mavlink_landing_target_t mavlink_landing_target_t
Functions
static uint16_t mavlink_msg_landing_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t target_num, uint8_t frame, float angle_x, float angle_y, float distance, float size_x, float size_y)
Pack a landing_target message.
static uint16_t mavlink_msg_landing_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t target_num, uint8_t frame, float angle_x, float angle_y, float distance, float size_x, float size_y)
Pack a landing_target message on a channel.
static uint16_t mavlink_msg_landing_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_landing_target_t *landing_target)
Encode a landing_target struct.
static uint16_t mavlink_msg_landing_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_landing_target_t *landing_target)
Encode a landing_target struct on a channel.
static uint64_t mavlink_msg_landing_target_get_time_usec (const mavlink_message_t *msg)
Send a landing_target message.
static uint8_t mavlink_msg_landing_target_get_target_num (const mavlink_message_t *msg)
Get field target_num from landing_target message.
static uint8_t mavlink_msg_landing_target_get_frame (const mavlink_message_t *msg)
Get field frame from landing_target message.
static float mavlink_msg_landing_target_get_angle_x (const mavlink_message_t *msg)
Get field angle_x from landing_target message.
static float mavlink_msg_landing_target_get_angle_y (const mavlink_message_t *msg)
Get field angle_y from landing_target message.
static float mavlink_msg_landing_target_get_distance (const mavlink_message_t *msg)
Get field distance from landing_target message.
static float mavlink_msg_landing_target_get_size_x (const mavlink_message_t *msg)
Get field size_x from landing_target message.
static float mavlink_msg_landing_target_get_size_y (const mavlink_message_t *msg)
Get field size_y from landing_target message.
static void mavlink_msg_landing_target_decode (const mavlink_message_t *msg, mavlink_landing_target_t *landing_target)
Decode a landing_target message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LANDING_TARGET
Value:
{ \
    "LANDING_TARGET", \
    8, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_landing_target_t, time_usec) }, \
         { "angle_x", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_landing_target_t, angle_x) }, \
         { "angle_y", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_landing_target_t, angle_y) }, \
         { "distance", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_landing_target_t, distance) }, \
         { "size_x", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_landing_target_t, size_x) }, \
         { "size_y", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_landing_target_t, size_y) }, \
         { "target_num", NULL, MAVLINK_TYPE_UINT8_T, 0, 28, offsetof(mavlink_landing_target_t, target_num) }, \
         { "frame", NULL, MAVLINK_TYPE_UINT8_T, 0, 29, offsetof(mavlink_landing_target_t, frame) }, \
         } \
}
Definition at line 25 of file mavlink_msg_landing_target.h.
#define MAVLINK_MSG_ID_149_CRC 200
Definition at line 21 of file mavlink_msg_landing_target.h.
#define MAVLINK_MSG_ID_149_LEN 30
Definition at line 18 of file mavlink_msg_landing_target.h.
#define MAVLINK_MSG_ID_LANDING_TARGET 149
Definition at line 3 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_pack(), and mavlink_msg_landing_target_pack_chan().
#define MAVLINK_MSG_ID_LANDING_TARGET_CRC 200
Definition at line 20 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_pack(), and mavlink_msg_landing_target_pack_chan().
#define MAVLINK_MSG_ID_LANDING_TARGET_LEN 30
Definition at line 17 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode(), mavlink_msg_landing_target_pack(), and mavlink_msg_landing_target_pack_chan().
Typedef Documentation
typedef struct __mavlink_landing_target_t mavlink_landing_target_t
Function Documentation
static void mavlink_msg_landing_target_decode (const mavlink_message_t * msg, mavlink_landing_target_t * landing_target) inline static
Decode a landing_target message into a struct.
Parameters
msg The message to decode
landing_target C-struct to decode the message contents into
Definition at line 363 of file mavlink_msg_landing_target.h.
Referenced by AC_PrecLand_Companion::handle_msg(), and mavlink_test_landing_target().
static uint16_t mavlink_msg_landing_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_landing_target_t * landing_target) inline static
Encode a landing_target struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
landing_target C-struct to read the message contents from
Definition at line 155 of file mavlink_msg_landing_target.h.
Referenced by mavlink_test_landing_target().
static uint16_t mavlink_msg_landing_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_landing_target_t * landing_target) inline static
Encode a landing_target struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
landing_target C-struct to read the message contents from
Definition at line 169 of file mavlink_msg_landing_target.h.
static float mavlink_msg_landing_target_get_angle_x (const mavlink_message_t * msg) inline static
Get field angle_x from landing_target message.
Returns
X-axis angular offset (in radians) of the target from the center of the image
Definition at line 312 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static float mavlink_msg_landing_target_get_angle_y (const mavlink_message_t * msg) inline static
Get field angle_y from landing_target message.
Returns
Y-axis angular offset (in radians) of the target from the center of the image
Definition at line 322 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static float mavlink_msg_landing_target_get_distance (const mavlink_message_t * msg) inline static
Get field distance from landing_target message.
Returns
Distance to the target from the vehicle in meters
Definition at line 332 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static uint8_t mavlink_msg_landing_target_get_frame (const mavlink_message_t * msg) inline static
Get field frame from landing_target message.
Returns
MAV_FRAME enum specifying the whether the following feilds are earth-frame, body-frame, etc.
Definition at line 302 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static float mavlink_msg_landing_target_get_size_x (const mavlink_message_t * msg) inline static
Get field size_x from landing_target message.
Returns
Size in radians of target along x-axis
Definition at line 342 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static float mavlink_msg_landing_target_get_size_y (const mavlink_message_t * msg) inline static
Get field size_y from landing_target message.
Returns
Size in radians of target along y-axis
Definition at line 352 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static uint8_t mavlink_msg_landing_target_get_target_num (const mavlink_message_t * msg) inline static
Get field target_num from landing_target message.
Returns
The ID of the target if multiple targets are present
Definition at line 292 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static uint64_t mavlink_msg_landing_target_get_time_usec (const mavlink_message_t * msg) inline static
Send a landing_target message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (micros since boot or Unix epoch)
target_num The ID of the target if multiple targets are present
frame MAV_FRAME enum specifying the whether the following feilds are earth-frame, body-frame, etc.
angle_x X-axis angular offset (in radians) of the target from the center of the image
angle_y Y-axis angular offset (in radians) of the target from the center of the image
distance Distance to the target from the vehicle in meters
size_x Size in radians of target along x-axis
size_y Size in radians of target along y-axis Get field time_usec from landing_target message
Returns
Timestamp (micros since boot or Unix epoch)
Definition at line 282 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_decode().
static uint16_t mavlink_msg_landing_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t target_num, uint8_t frame, float angle_x, float angle_y, float distance, float size_x, float size_y) inline static
Pack a landing_target message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
target_num The ID of the target if multiple targets are present
frame MAV_FRAME enum specifying the whether the following feilds are earth-frame, body-frame, etc.
angle_x X-axis angular offset (in radians) of the target from the center of the image
angle_y Y-axis angular offset (in radians) of the target from the center of the image
distance Distance to the target from the vehicle in meters
size_x Size in radians of target along x-axis
size_y Size in radians of target along y-axis
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_encode(), and mavlink_test_landing_target().
static uint16_t mavlink_msg_landing_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t target_num, uint8_t frame, float angle_x, float angle_y, float distance, float size_x, float size_y) inline static
Pack a landing_target message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
target_num The ID of the target if multiple targets are present
frame MAV_FRAME enum specifying the whether the following feilds are earth-frame, body-frame, etc.
angle_x X-axis angular offset (in radians) of the target from the center of the image
angle_y Y-axis angular offset (in radians) of the target from the center of the image
distance Distance to the target from the vehicle in meters
size_x Size in radians of target along x-axis
size_y Size in radians of target along y-axis
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 109 of file mavlink_msg_landing_target.h.
Referenced by mavlink_msg_landing_target_encode_chan(), and mavlink_test_landing_target().