APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_report_axis_calibration_status.h File Reference
mavlink_msg_gimbal_report_axis_calibration_status.h File Reference
Classes
struct __mavlink_gimbal_report_axis_calibration_status_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS 212
#define MAVLINK_MSG_ID_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS_LEN 3
#define MAVLINK_MSG_ID_212_LEN 3
#define MAVLINK_MSG_ID_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS_CRC 235
#define MAVLINK_MSG_ID_212_CRC 235
#define MAVLINK_MESSAGE_INFO_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS
Typedefs
typedef struct __mavlink_gimbal_report_axis_calibration_status_t mavlink_gimbal_report_axis_calibration_status_t
Functions
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t yaw_requires_calibration, uint8_t pitch_requires_calibration, uint8_t roll_requires_calibration)
Pack a gimbal_report_axis_calibration_status message.
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t yaw_requires_calibration, uint8_t pitch_requires_calibration, uint8_t roll_requires_calibration)
Pack a gimbal_report_axis_calibration_status message on a channel.
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_report_axis_calibration_status_t *gimbal_report_axis_calibration_status)
Encode a gimbal_report_axis_calibration_status struct.
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_report_axis_calibration_status_t *gimbal_report_axis_calibration_status)
Encode a gimbal_report_axis_calibration_status struct on a channel.
static uint8_t mavlink_msg_gimbal_report_axis_calibration_status_get_yaw_requires_calibration (const mavlink_message_t *msg)
Send a gimbal_report_axis_calibration_status message.
static uint8_t mavlink_msg_gimbal_report_axis_calibration_status_get_pitch_requires_calibration (const mavlink_message_t *msg)
Get field pitch_requires_calibration from gimbal_report_axis_calibration_status message.
static uint8_t mavlink_msg_gimbal_report_axis_calibration_status_get_roll_requires_calibration (const mavlink_message_t *msg)
Get field roll_requires_calibration from gimbal_report_axis_calibration_status message.
static void mavlink_msg_gimbal_report_axis_calibration_status_decode (const mavlink_message_t *msg, mavlink_gimbal_report_axis_calibration_status_t *gimbal_report_axis_calibration_status)
Decode a gimbal_report_axis_calibration_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS
Value:
{ \
    "GIMBAL_REPORT_AXIS_CALIBRATION_STATUS", \
    3, \
    {  { "yaw_requires_calibration", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_report_axis_calibration_status_t, yaw_requires_calibration) }, \
         { "pitch_requires_calibration", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gimbal_report_axis_calibration_status_t, pitch_requires_calibration) }, \
         { "roll_requires_calibration", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_gimbal_report_axis_calibration_status_t, roll_requires_calibration) }, \
         } \
}
Definition at line 20 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
#define MAVLINK_MSG_ID_212_CRC 235
Definition at line 16 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
#define MAVLINK_MSG_ID_212_LEN 3
Definition at line 13 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
#define MAVLINK_MSG_ID_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS 212
Definition at line 3 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_pack(), and mavlink_msg_gimbal_report_axis_calibration_status_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS_CRC 235
Definition at line 15 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_pack(), and mavlink_msg_gimbal_report_axis_calibration_status_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REPORT_AXIS_CALIBRATION_STATUS_LEN 3
Definition at line 12 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_decode(), mavlink_msg_gimbal_report_axis_calibration_status_pack(), and mavlink_msg_gimbal_report_axis_calibration_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_report_axis_calibration_status_t mavlink_gimbal_report_axis_calibration_status_t
Function Documentation
static void mavlink_msg_gimbal_report_axis_calibration_status_decode (const mavlink_message_t * msg, mavlink_gimbal_report_axis_calibration_status_t * gimbal_report_axis_calibration_status) inline static
Decode a gimbal_report_axis_calibration_status message into a struct.
Parameters
msg The message to decode
gimbal_report_axis_calibration_status C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_test_gimbal_report_axis_calibration_status().
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_report_axis_calibration_status_t * gimbal_report_axis_calibration_status) inline static
Encode a gimbal_report_axis_calibration_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_report_axis_calibration_status C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_test_gimbal_report_axis_calibration_status().
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_report_axis_calibration_status_t * gimbal_report_axis_calibration_status) inline static
Encode a gimbal_report_axis_calibration_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_report_axis_calibration_status C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
static uint8_t mavlink_msg_gimbal_report_axis_calibration_status_get_pitch_requires_calibration (const mavlink_message_t * msg) inline static
Get field pitch_requires_calibration from gimbal_report_axis_calibration_status message.
Returns
Whether or not the pitch axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
Definition at line 227 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_decode().
static uint8_t mavlink_msg_gimbal_report_axis_calibration_status_get_roll_requires_calibration (const mavlink_message_t * msg) inline static
Get field roll_requires_calibration from gimbal_report_axis_calibration_status message.
Returns
Whether or not the roll axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
Definition at line 237 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_decode().
static uint8_t mavlink_msg_gimbal_report_axis_calibration_status_get_yaw_requires_calibration (const mavlink_message_t * msg) inline static
Send a gimbal_report_axis_calibration_status message.
Parameters
chan MAVLink channel to send the message
yaw_requires_calibration Whether or not the yaw axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
pitch_requires_calibration Whether or not the pitch axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
roll_requires_calibration Whether or not the roll axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration Get field yaw_requires_calibration from gimbal_report_axis_calibration_status message
Returns
Whether or not the yaw axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
Definition at line 217 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_decode().
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t yaw_requires_calibration, uint8_t pitch_requires_calibration, uint8_t roll_requires_calibration) inline static
Pack a gimbal_report_axis_calibration_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
yaw_requires_calibration Whether or not the yaw axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
pitch_requires_calibration Whether or not the pitch axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
roll_requires_calibration Whether or not the roll axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_encode(), and mavlink_test_gimbal_report_axis_calibration_status().
static uint16_t mavlink_msg_gimbal_report_axis_calibration_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t yaw_requires_calibration, uint8_t pitch_requires_calibration, uint8_t roll_requires_calibration) inline static
Pack a gimbal_report_axis_calibration_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
yaw_requires_calibration Whether or not the yaw axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
pitch_requires_calibration Whether or not the pitch axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
roll_requires_calibration Whether or not the roll axis requires calibration, see GIMBAL_AXIS_CALIBRATION_REQUIRED enumeration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_gimbal_report_axis_calibration_status.h.
Referenced by mavlink_msg_gimbal_report_axis_calibration_status_encode_chan(), and mavlink_test_gimbal_report_axis_calibration_status().