APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_local_position_ned_cov.h File Reference
mavlink_msg_local_position_ned_cov.h File Reference
Classes
struct __mavlink_local_position_ned_cov_t
Macros
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV 64
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV_LEN 181
#define MAVLINK_MSG_ID_64_LEN 181
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV_CRC 82
#define MAVLINK_MSG_ID_64_CRC 82
#define MAVLINK_MSG_LOCAL_POSITION_NED_COV_FIELD_COVARIANCE_LEN 36
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_NED_COV
Typedefs
typedef struct __mavlink_local_position_ned_cov_t mavlink_local_position_ned_cov_t
Functions
static uint16_t mavlink_msg_local_position_ned_cov_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, uint64_t time_utc, uint8_t estimator_type, float x, float y, float z, float vx, float vy, float vz, const float *covariance)
Pack a local_position_ned_cov message.
static uint16_t mavlink_msg_local_position_ned_cov_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, uint64_t time_utc, uint8_t estimator_type, float x, float y, float z, float vx, float vy, float vz, const float *covariance)
Pack a local_position_ned_cov message on a channel.
static uint16_t mavlink_msg_local_position_ned_cov_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_local_position_ned_cov_t *local_position_ned_cov)
Encode a local_position_ned_cov struct.
static uint16_t mavlink_msg_local_position_ned_cov_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_local_position_ned_cov_t *local_position_ned_cov)
Encode a local_position_ned_cov struct on a channel.
static uint32_t mavlink_msg_local_position_ned_cov_get_time_boot_ms (const mavlink_message_t *msg)
Send a local_position_ned_cov message.
static uint64_t mavlink_msg_local_position_ned_cov_get_time_utc (const mavlink_message_t *msg)
Get field time_utc from local_position_ned_cov message.
static uint8_t mavlink_msg_local_position_ned_cov_get_estimator_type (const mavlink_message_t *msg)
Get field estimator_type from local_position_ned_cov message.
static float mavlink_msg_local_position_ned_cov_get_x (const mavlink_message_t *msg)
Get field x from local_position_ned_cov message.
static float mavlink_msg_local_position_ned_cov_get_y (const mavlink_message_t *msg)
Get field y from local_position_ned_cov message.
static float mavlink_msg_local_position_ned_cov_get_z (const mavlink_message_t *msg)
Get field z from local_position_ned_cov message.
static float mavlink_msg_local_position_ned_cov_get_vx (const mavlink_message_t *msg)
Get field vx from local_position_ned_cov message.
static float mavlink_msg_local_position_ned_cov_get_vy (const mavlink_message_t *msg)
Get field vy from local_position_ned_cov message.
static float mavlink_msg_local_position_ned_cov_get_vz (const mavlink_message_t *msg)
Get field vz from local_position_ned_cov message.
static uint16_t mavlink_msg_local_position_ned_cov_get_covariance (const mavlink_message_t *msg, float *covariance)
Get field covariance from local_position_ned_cov message.
static void mavlink_msg_local_position_ned_cov_decode (const mavlink_message_t *msg, mavlink_local_position_ned_cov_t *local_position_ned_cov)
Decode a local_position_ned_cov message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_NED_COV
Value:
{ \
    "LOCAL_POSITION_NED_COV", \
    10, \
    {  { "time_utc", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_local_position_ned_cov_t, time_utc) }, \
         { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 8, offsetof(mavlink_local_position_ned_cov_t, time_boot_ms) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_local_position_ned_cov_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_local_position_ned_cov_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_local_position_ned_cov_t, z) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_local_position_ned_cov_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_local_position_ned_cov_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_local_position_ned_cov_t, vz) }, \
         { "covariance", NULL, MAVLINK_TYPE_FLOAT, 36, 36, offsetof(mavlink_local_position_ned_cov_t, covariance) }, \
         { "estimator_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 180, offsetof(mavlink_local_position_ned_cov_t, estimator_type) }, \
         } \
}
Definition at line 27 of file mavlink_msg_local_position_ned_cov.h.
#define MAVLINK_MSG_ID_64_CRC 82
Definition at line 23 of file mavlink_msg_local_position_ned_cov.h.
#define MAVLINK_MSG_ID_64_LEN 181
Definition at line 20 of file mavlink_msg_local_position_ned_cov.h.
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV 64
Definition at line 3 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_pack(), and mavlink_msg_local_position_ned_cov_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV_CRC 82
Definition at line 22 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_pack(), and mavlink_msg_local_position_ned_cov_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV_LEN 181
Definition at line 19 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode(), mavlink_msg_local_position_ned_cov_pack(), and mavlink_msg_local_position_ned_cov_pack_chan().
#define MAVLINK_MSG_LOCAL_POSITION_NED_COV_FIELD_COVARIANCE_LEN 36
Definition at line 25 of file mavlink_msg_local_position_ned_cov.h.
Typedef Documentation
typedef struct __mavlink_local_position_ned_cov_t mavlink_local_position_ned_cov_t
Function Documentation
static void mavlink_msg_local_position_ned_cov_decode (const mavlink_message_t * msg, mavlink_local_position_ned_cov_t * local_position_ned_cov) inline static
Decode a local_position_ned_cov message into a struct.
Parameters
msg The message to decode
local_position_ned_cov C-struct to decode the message contents into
Definition at line 401 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_test_local_position_ned_cov().
static uint16_t mavlink_msg_local_position_ned_cov_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_local_position_ned_cov_t * local_position_ned_cov) inline static
Encode a local_position_ned_cov struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
local_position_ned_cov C-struct to read the message contents from
Definition at line 167 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_test_local_position_ned_cov().
static uint16_t mavlink_msg_local_position_ned_cov_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_local_position_ned_cov_t * local_position_ned_cov) inline static
Encode a local_position_ned_cov struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
local_position_ned_cov C-struct to read the message contents from
Definition at line 181 of file mavlink_msg_local_position_ned_cov.h.
static uint16_t mavlink_msg_local_position_ned_cov_get_covariance (const mavlink_message_t * msg, float * covariance) inline static
Get field covariance from local_position_ned_cov message.
Returns
Covariance matrix (first six entries are the first ROW, next six entries are the second row, etc.)
Definition at line 390 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static uint8_t mavlink_msg_local_position_ned_cov_get_estimator_type (const mavlink_message_t * msg) inline static
Get field estimator_type from local_position_ned_cov message.
Returns
Class id of the estimator this estimate originated from.
Definition at line 320 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static uint32_t mavlink_msg_local_position_ned_cov_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a local_position_ned_cov message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
time_utc Timestamp (microseconds since UNIX epoch) in UTC. 0 for unknown. Commonly filled by the precision time source of a GPS receiver.
estimator_type Class id of the estimator this estimate originated from.
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
covariance Covariance matrix (first six entries are the first ROW, next six entries are the second row, etc.) Get field time_boot_ms from local_position_ned_cov message
Returns
Timestamp (milliseconds since system boot)
Definition at line 300 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static uint64_t mavlink_msg_local_position_ned_cov_get_time_utc (const mavlink_message_t * msg) inline static
Get field time_utc from local_position_ned_cov message.
Returns
Timestamp (microseconds since UNIX epoch) in UTC. 0 for unknown. Commonly filled by the precision time source of a GPS receiver.
Definition at line 310 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static float mavlink_msg_local_position_ned_cov_get_vx (const mavlink_message_t * msg) inline static
Get field vx from local_position_ned_cov message.
Returns
X Speed
Definition at line 360 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static float mavlink_msg_local_position_ned_cov_get_vy (const mavlink_message_t * msg) inline static
Get field vy from local_position_ned_cov message.
Returns
Y Speed
Definition at line 370 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static float mavlink_msg_local_position_ned_cov_get_vz (const mavlink_message_t * msg) inline static
Get field vz from local_position_ned_cov message.
Returns
Z Speed
Definition at line 380 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static float mavlink_msg_local_position_ned_cov_get_x (const mavlink_message_t * msg) inline static
Get field x from local_position_ned_cov message.
Returns
X Position
Definition at line 330 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static float mavlink_msg_local_position_ned_cov_get_y (const mavlink_message_t * msg) inline static
Get field y from local_position_ned_cov message.
Returns
Y Position
Definition at line 340 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static float mavlink_msg_local_position_ned_cov_get_z (const mavlink_message_t * msg) inline static
Get field z from local_position_ned_cov message.
Returns
Z Position
Definition at line 350 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_decode().
static uint16_t mavlink_msg_local_position_ned_cov_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, uint64_t time_utc, uint8_t estimator_type, float x, float y, float z, float vx, float vy, float vz, const float * covariance) inline static
Pack a local_position_ned_cov message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
time_utc Timestamp (microseconds since UNIX epoch) in UTC. 0 for unknown. Commonly filled by the precision time source of a GPS receiver.
estimator_type Class id of the estimator this estimate originated from.
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
covariance Covariance matrix (first six entries are the first ROW, next six entries are the second row, etc.)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_encode(), and mavlink_test_local_position_ned_cov().
static uint16_t mavlink_msg_local_position_ned_cov_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, uint64_t time_utc, uint8_t estimator_type, float x, float y, float z, float vx, float vy, float vz, const float * covariance) inline static
Pack a local_position_ned_cov message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
time_utc Timestamp (microseconds since UNIX epoch) in UTC. 0 for unknown. Commonly filled by the precision time source of a GPS receiver.
estimator_type Class id of the estimator this estimate originated from.
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
covariance Covariance matrix (first six entries are the first ROW, next six entries are the second row, etc.)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 119 of file mavlink_msg_local_position_ned_cov.h.
Referenced by mavlink_msg_local_position_ned_cov_encode_chan(), and mavlink_test_local_position_ned_cov().