APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_nav_controller_output.h File Reference
mavlink_msg_nav_controller_output.h File Reference
Classes
struct __mavlink_nav_controller_output_t
Macros
#define MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT 62
#define MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT_LEN 26
#define MAVLINK_MSG_ID_62_LEN 26
#define MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT_CRC 183
#define MAVLINK_MSG_ID_62_CRC 183
#define MAVLINK_MESSAGE_INFO_NAV_CONTROLLER_OUTPUT
Typedefs
typedef struct __mavlink_nav_controller_output_t mavlink_nav_controller_output_t
Functions
static uint16_t mavlink_msg_nav_controller_output_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float nav_roll, float nav_pitch, int16_t nav_bearing, int16_t target_bearing, uint16_t wp_dist, float alt_error, float aspd_error, float xtrack_error)
Pack a nav_controller_output message.
static uint16_t mavlink_msg_nav_controller_output_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float nav_roll, float nav_pitch, int16_t nav_bearing, int16_t target_bearing, uint16_t wp_dist, float alt_error, float aspd_error, float xtrack_error)
Pack a nav_controller_output message on a channel.
static uint16_t mavlink_msg_nav_controller_output_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_nav_controller_output_t *nav_controller_output)
Encode a nav_controller_output struct.
static uint16_t mavlink_msg_nav_controller_output_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_nav_controller_output_t *nav_controller_output)
Encode a nav_controller_output struct on a channel.
static float mavlink_msg_nav_controller_output_get_nav_roll (const mavlink_message_t *msg)
Send a nav_controller_output message.
static float mavlink_msg_nav_controller_output_get_nav_pitch (const mavlink_message_t *msg)
Get field nav_pitch from nav_controller_output message.
static int16_t mavlink_msg_nav_controller_output_get_nav_bearing (const mavlink_message_t *msg)
Get field nav_bearing from nav_controller_output message.
static int16_t mavlink_msg_nav_controller_output_get_target_bearing (const mavlink_message_t *msg)
Get field target_bearing from nav_controller_output message.
static uint16_t mavlink_msg_nav_controller_output_get_wp_dist (const mavlink_message_t *msg)
Get field wp_dist from nav_controller_output message.
static float mavlink_msg_nav_controller_output_get_alt_error (const mavlink_message_t *msg)
Get field alt_error from nav_controller_output message.
static float mavlink_msg_nav_controller_output_get_aspd_error (const mavlink_message_t *msg)
Get field aspd_error from nav_controller_output message.
static float mavlink_msg_nav_controller_output_get_xtrack_error (const mavlink_message_t *msg)
Get field xtrack_error from nav_controller_output message.
static void mavlink_msg_nav_controller_output_decode (const mavlink_message_t *msg, mavlink_nav_controller_output_t *nav_controller_output)
Decode a nav_controller_output message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_NAV_CONTROLLER_OUTPUT
Value:
{ \
    "NAV_CONTROLLER_OUTPUT", \
    8, \
    {  { "nav_roll", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_nav_controller_output_t, nav_roll) }, \
         { "nav_pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_nav_controller_output_t, nav_pitch) }, \
         { "alt_error", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_nav_controller_output_t, alt_error) }, \
         { "aspd_error", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_nav_controller_output_t, aspd_error) }, \
         { "xtrack_error", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_nav_controller_output_t, xtrack_error) }, \
         { "nav_bearing", NULL, MAVLINK_TYPE_INT16_T, 0, 20, offsetof(mavlink_nav_controller_output_t, nav_bearing) }, \
         { "target_bearing", NULL, MAVLINK_TYPE_INT16_T, 0, 22, offsetof(mavlink_nav_controller_output_t, target_bearing) }, \
         { "wp_dist", NULL, MAVLINK_TYPE_UINT16_T, 0, 24, offsetof(mavlink_nav_controller_output_t, wp_dist) }, \
         } \
}
Definition at line 25 of file mavlink_msg_nav_controller_output.h.
#define MAVLINK_MSG_ID_62_CRC 183
Definition at line 21 of file mavlink_msg_nav_controller_output.h.
#define MAVLINK_MSG_ID_62_LEN 26
Definition at line 18 of file mavlink_msg_nav_controller_output.h.
#define MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT 62
Definition at line 3 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_pack(), and mavlink_msg_nav_controller_output_pack_chan().
#define MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT_CRC 183
Definition at line 20 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_pack(), and mavlink_msg_nav_controller_output_pack_chan().
#define MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT_LEN 26
Definition at line 17 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode(), mavlink_msg_nav_controller_output_pack(), and mavlink_msg_nav_controller_output_pack_chan().
Typedef Documentation
typedef struct __mavlink_nav_controller_output_t mavlink_nav_controller_output_t
Function Documentation
static void mavlink_msg_nav_controller_output_decode (const mavlink_message_t * msg, mavlink_nav_controller_output_t * nav_controller_output) inline static
Decode a nav_controller_output message into a struct.
Parameters
msg The message to decode
nav_controller_output C-struct to decode the message contents into
Definition at line 363 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_test_nav_controller_output().
static uint16_t mavlink_msg_nav_controller_output_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_nav_controller_output_t * nav_controller_output) inline static
Encode a nav_controller_output struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
nav_controller_output C-struct to read the message contents from
Definition at line 155 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_test_nav_controller_output().
static uint16_t mavlink_msg_nav_controller_output_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_nav_controller_output_t * nav_controller_output) inline static
Encode a nav_controller_output struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
nav_controller_output C-struct to read the message contents from
Definition at line 169 of file mavlink_msg_nav_controller_output.h.
static float mavlink_msg_nav_controller_output_get_alt_error (const mavlink_message_t * msg) inline static
Get field alt_error from nav_controller_output message.
Returns
Current altitude error in meters
Definition at line 332 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static float mavlink_msg_nav_controller_output_get_aspd_error (const mavlink_message_t * msg) inline static
Get field aspd_error from nav_controller_output message.
Returns
Current airspeed error in meters/second
Definition at line 342 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static int16_t mavlink_msg_nav_controller_output_get_nav_bearing (const mavlink_message_t * msg) inline static
Get field nav_bearing from nav_controller_output message.
Returns
Current desired heading in degrees
Definition at line 302 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static float mavlink_msg_nav_controller_output_get_nav_pitch (const mavlink_message_t * msg) inline static
Get field nav_pitch from nav_controller_output message.
Returns
Current desired pitch in degrees
Definition at line 292 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static float mavlink_msg_nav_controller_output_get_nav_roll (const mavlink_message_t * msg) inline static
Send a nav_controller_output message.
Parameters
chan MAVLink channel to send the message
nav_roll Current desired roll in degrees
nav_pitch Current desired pitch in degrees
nav_bearing Current desired heading in degrees
target_bearing Bearing to current MISSION/target in degrees
wp_dist Distance to active MISSION in meters
alt_error Current altitude error in meters
aspd_error Current airspeed error in meters/second
xtrack_error Current crosstrack error on x-y plane in meters Get field nav_roll from nav_controller_output message
Returns
Current desired roll in degrees
Definition at line 282 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static int16_t mavlink_msg_nav_controller_output_get_target_bearing (const mavlink_message_t * msg) inline static
Get field target_bearing from nav_controller_output message.
Returns
Bearing to current MISSION/target in degrees
Definition at line 312 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static uint16_t mavlink_msg_nav_controller_output_get_wp_dist (const mavlink_message_t * msg) inline static
Get field wp_dist from nav_controller_output message.
Returns
Distance to active MISSION in meters
Definition at line 322 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static float mavlink_msg_nav_controller_output_get_xtrack_error (const mavlink_message_t * msg) inline static
Get field xtrack_error from nav_controller_output message.
Returns
Current crosstrack error on x-y plane in meters
Definition at line 352 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_decode().
static uint16_t mavlink_msg_nav_controller_output_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float nav_roll, float nav_pitch, int16_t nav_bearing, int16_t target_bearing, uint16_t wp_dist, float alt_error, float aspd_error, float xtrack_error) inline static
Pack a nav_controller_output message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
nav_roll Current desired roll in degrees
nav_pitch Current desired pitch in degrees
nav_bearing Current desired heading in degrees
target_bearing Bearing to current MISSION/target in degrees
wp_dist Distance to active MISSION in meters
alt_error Current altitude error in meters
aspd_error Current airspeed error in meters/second
xtrack_error Current crosstrack error on x-y plane in meters
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_encode(), and mavlink_test_nav_controller_output().
static uint16_t mavlink_msg_nav_controller_output_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float nav_roll, float nav_pitch, int16_t nav_bearing, int16_t target_bearing, uint16_t wp_dist, float alt_error, float aspd_error, float xtrack_error) inline static
Pack a nav_controller_output message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
nav_roll Current desired roll in degrees
nav_pitch Current desired pitch in degrees
nav_bearing Current desired heading in degrees
target_bearing Bearing to current MISSION/target in degrees
wp_dist Distance to active MISSION in meters
alt_error Current altitude error in meters
aspd_error Current airspeed error in meters/second
xtrack_error Current crosstrack error on x-y plane in meters
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 109 of file mavlink_msg_nav_controller_output.h.
Referenced by mavlink_msg_nav_controller_output_encode_chan(), and mavlink_test_nav_controller_output().