APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_wind.h File Reference
mavlink_msg_wind.h File Reference
Classes
struct __mavlink_wind_t
Macros
#define MAVLINK_MSG_ID_WIND 168
#define MAVLINK_MSG_ID_WIND_LEN 12
#define MAVLINK_MSG_ID_168_LEN 12
#define MAVLINK_MSG_ID_WIND_CRC 1
#define MAVLINK_MSG_ID_168_CRC 1
#define MAVLINK_MESSAGE_INFO_WIND
Typedefs
typedef struct __mavlink_wind_t mavlink_wind_t
Functions
static uint16_t mavlink_msg_wind_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float direction, float speed, float speed_z)
Pack a wind message.
static uint16_t mavlink_msg_wind_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float direction, float speed, float speed_z)
Pack a wind message on a channel.
static uint16_t mavlink_msg_wind_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_wind_t *wind)
Encode a wind struct.
static uint16_t mavlink_msg_wind_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_wind_t *wind)
Encode a wind struct on a channel.
static float mavlink_msg_wind_get_direction (const mavlink_message_t *msg)
Send a wind message.
static float mavlink_msg_wind_get_speed (const mavlink_message_t *msg)
Get field speed from wind message.
static float mavlink_msg_wind_get_speed_z (const mavlink_message_t *msg)
Get field speed_z from wind message.
static void mavlink_msg_wind_decode (const mavlink_message_t *msg, mavlink_wind_t *wind)
Decode a wind message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_WIND
Value:
{ \
    "WIND", \
    3, \
    {  { "direction", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_wind_t, direction) }, \
         { "speed", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_wind_t, speed) }, \
         { "speed_z", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_wind_t, speed_z) }, \
         } \
}
Definition at line 20 of file mavlink_msg_wind.h.
#define MAVLINK_MSG_ID_168_CRC 1
Definition at line 16 of file mavlink_msg_wind.h.
#define MAVLINK_MSG_ID_168_LEN 12
Definition at line 13 of file mavlink_msg_wind.h.
#define MAVLINK_MSG_ID_WIND 168
Definition at line 3 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_pack(), and mavlink_msg_wind_pack_chan().
#define MAVLINK_MSG_ID_WIND_CRC 1
Definition at line 15 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_pack(), and mavlink_msg_wind_pack_chan().
#define MAVLINK_MSG_ID_WIND_LEN 12
Definition at line 12 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_decode(), mavlink_msg_wind_pack(), and mavlink_msg_wind_pack_chan().
Typedef Documentation
typedef struct __mavlink_wind_t mavlink_wind_t
Function Documentation
static void mavlink_msg_wind_decode (const mavlink_message_t * msg, mavlink_wind_t * wind) inline static
Decode a wind message into a struct.
Parameters
msg The message to decode
wind C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_wind.h.
Referenced by mavlink_test_wind().
static uint16_t mavlink_msg_wind_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_wind_t * wind) inline static
Encode a wind struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
wind C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_wind.h.
Referenced by mavlink_test_wind().
static uint16_t mavlink_msg_wind_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_wind_t * wind) inline static
Encode a wind struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
wind C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_wind.h.
static float mavlink_msg_wind_get_direction (const mavlink_message_t * msg) inline static
Send a wind message.
Parameters
chan MAVLink channel to send the message
direction wind direction that wind is coming from (degrees)
speed wind speed in ground plane (m/s)
speed_z vertical wind speed (m/s) Get field direction from wind message
Returns
wind direction that wind is coming from (degrees)
Definition at line 217 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_decode().
static float mavlink_msg_wind_get_speed (const mavlink_message_t * msg) inline static
Get field speed from wind message.
Returns
wind speed in ground plane (m/s)
Definition at line 227 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_decode().
static float mavlink_msg_wind_get_speed_z (const mavlink_message_t * msg) inline static
Get field speed_z from wind message.
Returns
vertical wind speed (m/s)
Definition at line 237 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_decode().
static uint16_t mavlink_msg_wind_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float direction, float speed, float speed_z) inline static
Pack a wind message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
direction wind direction that wind is coming from (degrees)
speed wind speed in ground plane (m/s)
speed_z vertical wind speed (m/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_encode(), and mavlink_test_wind().
static uint16_t mavlink_msg_wind_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float direction, float speed, float speed_z) inline static
Pack a wind message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
direction wind direction that wind is coming from (degrees)
speed wind speed in ground plane (m/s)
speed_z vertical wind speed (m/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_wind.h.
Referenced by mavlink_msg_wind_encode_chan(), and mavlink_test_wind().