APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_change_operator_control_ack.h File Reference
mavlink_msg_change_operator_control_ack.h File Reference
Classes
struct __mavlink_change_operator_control_ack_t
Macros
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK 6
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK_LEN 3
#define MAVLINK_MSG_ID_6_LEN 3
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK_CRC 104
#define MAVLINK_MSG_ID_6_CRC 104
#define MAVLINK_MESSAGE_INFO_CHANGE_OPERATOR_CONTROL_ACK
Typedefs
typedef struct __mavlink_change_operator_control_ack_t mavlink_change_operator_control_ack_t
Functions
static uint16_t mavlink_msg_change_operator_control_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t gcs_system_id, uint8_t control_request, uint8_t ack)
Pack a change_operator_control_ack message.
static uint16_t mavlink_msg_change_operator_control_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t gcs_system_id, uint8_t control_request, uint8_t ack)
Pack a change_operator_control_ack message on a channel.
static uint16_t mavlink_msg_change_operator_control_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_change_operator_control_ack_t *change_operator_control_ack)
Encode a change_operator_control_ack struct.
static uint16_t mavlink_msg_change_operator_control_ack_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_change_operator_control_ack_t *change_operator_control_ack)
Encode a change_operator_control_ack struct on a channel.
static uint8_t mavlink_msg_change_operator_control_ack_get_gcs_system_id (const mavlink_message_t *msg)
Send a change_operator_control_ack message.
static uint8_t mavlink_msg_change_operator_control_ack_get_control_request (const mavlink_message_t *msg)
Get field control_request from change_operator_control_ack message.
static uint8_t mavlink_msg_change_operator_control_ack_get_ack (const mavlink_message_t *msg)
Get field ack from change_operator_control_ack message.
static void mavlink_msg_change_operator_control_ack_decode (const mavlink_message_t *msg, mavlink_change_operator_control_ack_t *change_operator_control_ack)
Decode a change_operator_control_ack message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_CHANGE_OPERATOR_CONTROL_ACK
Value:
{ \
    "CHANGE_OPERATOR_CONTROL_ACK", \
    3, \
    {  { "gcs_system_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_change_operator_control_ack_t, gcs_system_id) }, \
         { "control_request", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_change_operator_control_ack_t, control_request) }, \
         { "ack", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_change_operator_control_ack_t, ack) }, \
         } \
}
Definition at line 20 of file mavlink_msg_change_operator_control_ack.h.
#define MAVLINK_MSG_ID_6_CRC 104
Definition at line 16 of file mavlink_msg_change_operator_control_ack.h.
#define MAVLINK_MSG_ID_6_LEN 3
Definition at line 13 of file mavlink_msg_change_operator_control_ack.h.
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK 6
Definition at line 3 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_pack(), and mavlink_msg_change_operator_control_ack_pack_chan().
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK_CRC 104
Definition at line 15 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_pack(), and mavlink_msg_change_operator_control_ack_pack_chan().
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK_LEN 3
Definition at line 12 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_decode(), mavlink_msg_change_operator_control_ack_pack(), and mavlink_msg_change_operator_control_ack_pack_chan().
Typedef Documentation
typedef struct __mavlink_change_operator_control_ack_t mavlink_change_operator_control_ack_t
Function Documentation
static void mavlink_msg_change_operator_control_ack_decode (const mavlink_message_t * msg, mavlink_change_operator_control_ack_t * change_operator_control_ack) inline static
Decode a change_operator_control_ack message into a struct.
Parameters
msg The message to decode
change_operator_control_ack C-struct to decode the message contents into
Definition at line 248 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_test_change_operator_control_ack().
static uint16_t mavlink_msg_change_operator_control_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_change_operator_control_ack_t * change_operator_control_ack) inline static
Encode a change_operator_control_ack struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
change_operator_control_ack C-struct to read the message contents from
Definition at line 115 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_test_change_operator_control_ack().
static uint16_t mavlink_msg_change_operator_control_ack_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_change_operator_control_ack_t * change_operator_control_ack) inline static
Encode a change_operator_control_ack struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
change_operator_control_ack C-struct to read the message contents from
Definition at line 129 of file mavlink_msg_change_operator_control_ack.h.
static uint8_t mavlink_msg_change_operator_control_ack_get_ack (const mavlink_message_t * msg) inline static
Get field ack from change_operator_control_ack message.
Returns
0: ACK, 1: NACK: Wrong passkey, 2: NACK: Unsupported passkey encryption method, 3: NACK: Already under control
Definition at line 237 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_decode().
static uint8_t mavlink_msg_change_operator_control_ack_get_control_request (const mavlink_message_t * msg) inline static
Get field control_request from change_operator_control_ack message.
Returns
0: request control of this MAV, 1: Release control of this MAV
Definition at line 227 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_decode().
static uint8_t mavlink_msg_change_operator_control_ack_get_gcs_system_id (const mavlink_message_t * msg) inline static
Send a change_operator_control_ack message.
Parameters
chan MAVLink channel to send the message
gcs_system_id ID of the GCS this message
control_request 0: request control of this MAV, 1: Release control of this MAV
ack 0: ACK, 1: NACK: Wrong passkey, 2: NACK: Unsupported passkey encryption method, 3: NACK: Already under control Get field gcs_system_id from change_operator_control_ack message
Returns
ID of the GCS this message
Definition at line 217 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_decode().
static uint16_t mavlink_msg_change_operator_control_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t gcs_system_id, uint8_t control_request, uint8_t ack) inline static
Pack a change_operator_control_ack message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gcs_system_id ID of the GCS this message
control_request 0: request control of this MAV, 1: Release control of this MAV
ack 0: ACK, 1: NACK: Wrong passkey, 2: NACK: Unsupported passkey encryption method, 3: NACK: Already under control
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_encode(), and mavlink_test_change_operator_control_ack().
static uint16_t mavlink_msg_change_operator_control_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t gcs_system_id, uint8_t control_request, uint8_t ack) inline static
Pack a change_operator_control_ack message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gcs_system_id ID of the GCS this message
control_request 0: request control of this MAV, 1: Release control of this MAV
ack 0: ACK, 1: NACK: Wrong passkey, 2: NACK: Unsupported passkey encryption method, 3: NACK: Already under control
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 79 of file mavlink_msg_change_operator_control_ack.h.
Referenced by mavlink_msg_change_operator_control_ack_encode_chan(), and mavlink_test_change_operator_control_ack().