APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_change_operator_control.h File Reference
mavlink_msg_change_operator_control.h File Reference
Classes
struct __mavlink_change_operator_control_t
Macros
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL 5
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_LEN 28
#define MAVLINK_MSG_ID_5_LEN 28
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_CRC 217
#define MAVLINK_MSG_ID_5_CRC 217
#define MAVLINK_MSG_CHANGE_OPERATOR_CONTROL_FIELD_PASSKEY_LEN 25
#define MAVLINK_MESSAGE_INFO_CHANGE_OPERATOR_CONTROL
Typedefs
typedef struct __mavlink_change_operator_control_t mavlink_change_operator_control_t
Functions
static uint16_t mavlink_msg_change_operator_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t control_request, uint8_t version, const char *passkey)
Pack a change_operator_control message.
static uint16_t mavlink_msg_change_operator_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t control_request, uint8_t version, const char *passkey)
Pack a change_operator_control message on a channel.
static uint16_t mavlink_msg_change_operator_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_change_operator_control_t *change_operator_control)
Encode a change_operator_control struct.
static uint16_t mavlink_msg_change_operator_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_change_operator_control_t *change_operator_control)
Encode a change_operator_control struct on a channel.
static uint8_t mavlink_msg_change_operator_control_get_target_system (const mavlink_message_t *msg)
Send a change_operator_control message.
static uint8_t mavlink_msg_change_operator_control_get_control_request (const mavlink_message_t *msg)
Get field control_request from change_operator_control message.
static uint8_t mavlink_msg_change_operator_control_get_version (const mavlink_message_t *msg)
Get field version from change_operator_control message.
static uint16_t mavlink_msg_change_operator_control_get_passkey (const mavlink_message_t *msg, char *passkey)
Get field passkey from change_operator_control message.
static void mavlink_msg_change_operator_control_decode (const mavlink_message_t *msg, mavlink_change_operator_control_t *change_operator_control)
Decode a change_operator_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_CHANGE_OPERATOR_CONTROL
Value:
{ \
    "CHANGE_OPERATOR_CONTROL", \
    4, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_change_operator_control_t, target_system) }, \
         { "control_request", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_change_operator_control_t, control_request) }, \
         { "version", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_change_operator_control_t, version) }, \
         { "passkey", NULL, MAVLINK_TYPE_CHAR, 25, 3, offsetof(mavlink_change_operator_control_t, passkey) }, \
         } \
}
Definition at line 21 of file mavlink_msg_change_operator_control.h.
#define MAVLINK_MSG_CHANGE_OPERATOR_CONTROL_FIELD_PASSKEY_LEN 25
Definition at line 19 of file mavlink_msg_change_operator_control.h.
#define MAVLINK_MSG_ID_5_CRC 217
Definition at line 17 of file mavlink_msg_change_operator_control.h.
#define MAVLINK_MSG_ID_5_LEN 28
Definition at line 14 of file mavlink_msg_change_operator_control.h.
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL 5
Definition at line 3 of file mavlink_msg_change_operator_control.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_change_operator_control_pack(), and mavlink_msg_change_operator_control_pack_chan().
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_CRC 217
Definition at line 16 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_pack(), and mavlink_msg_change_operator_control_pack_chan().
#define MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_LEN 28
Definition at line 13 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_decode(), mavlink_msg_change_operator_control_pack(), and mavlink_msg_change_operator_control_pack_chan().
Typedef Documentation
typedef struct __mavlink_change_operator_control_t mavlink_change_operator_control_t
Function Documentation
static void mavlink_msg_change_operator_control_decode (const mavlink_message_t * msg, mavlink_change_operator_control_t * change_operator_control) inline static
Decode a change_operator_control message into a struct.
Parameters
msg The message to decode
change_operator_control C-struct to decode the message contents into
Definition at line 263 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_test_change_operator_control().
static uint16_t mavlink_msg_change_operator_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_change_operator_control_t * change_operator_control) inline static
Encode a change_operator_control struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
change_operator_control C-struct to read the message contents from
Definition at line 119 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_test_change_operator_control().
static uint16_t mavlink_msg_change_operator_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_change_operator_control_t * change_operator_control) inline static
Encode a change_operator_control struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
change_operator_control C-struct to read the message contents from
Definition at line 133 of file mavlink_msg_change_operator_control.h.
static uint8_t mavlink_msg_change_operator_control_get_control_request (const mavlink_message_t * msg) inline static
Get field control_request from change_operator_control message.
Returns
0: request control of this MAV, 1: Release control of this MAV
Definition at line 232 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_decode().
static uint16_t mavlink_msg_change_operator_control_get_passkey (const mavlink_message_t * msg, char * passkey) inline static
Get field passkey from change_operator_control message.
Returns
Password / Key, depending on version plaintext or encrypted. 25 or less characters, NULL terminated. The characters may involve A-Z, a-z, 0-9, and "!?,.-"
Definition at line 252 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_decode().
static uint8_t mavlink_msg_change_operator_control_get_target_system (const mavlink_message_t * msg) inline static
Send a change_operator_control message.
Parameters
chan MAVLink channel to send the message
target_system System the GCS requests control for
control_request 0: request control of this MAV, 1: Release control of this MAV
version 0: key as plaintext, 1-255: future, different hashing/encryption variants. The GCS should in general use the safest mode possible initially and then gradually move down the encryption level if it gets a NACK message indicating an encryption mismatch.
passkey Password / Key, depending on version plaintext or encrypted. 25 or less characters, NULL terminated. The characters may involve A-Z, a-z, 0-9, and "!?,.-" Get field target_system from change_operator_control message
Returns
System the GCS requests control for
Definition at line 222 of file mavlink_msg_change_operator_control.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_change_operator_control_decode().
static uint8_t mavlink_msg_change_operator_control_get_version (const mavlink_message_t * msg) inline static
Get field version from change_operator_control message.
Returns
0: key as plaintext, 1-255: future, different hashing/encryption variants. The GCS should in general use the safest mode possible initially and then gradually move down the encryption level if it gets a NACK message indicating an encryption mismatch.
Definition at line 242 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_decode().
static uint16_t mavlink_msg_change_operator_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t control_request, uint8_t version, const char * passkey) inline static
Pack a change_operator_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System the GCS requests control for
control_request 0: request control of this MAV, 1: Release control of this MAV
version 0: key as plaintext, 1-255: future, different hashing/encryption variants. The GCS should in general use the safest mode possible initially and then gradually move down the encryption level if it gets a NACK message indicating an encryption mismatch.
passkey Password / Key, depending on version plaintext or encrypted. 25 or less characters, NULL terminated. The characters may involve A-Z, a-z, 0-9, and "!?,.-"
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_encode(), and mavlink_test_change_operator_control().
static uint16_t mavlink_msg_change_operator_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t control_request, uint8_t version, const char * passkey) inline static
Pack a change_operator_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System the GCS requests control for
control_request 0: request control of this MAV, 1: Release control of this MAV
version 0: key as plaintext, 1-255: future, different hashing/encryption variants. The GCS should in general use the safest mode possible initially and then gradually move down the encryption level if it gets a NACK message indicating an encryption mismatch.
passkey Password / Key, depending on version plaintext or encrypted. 25 or less characters, NULL terminated. The characters may involve A-Z, a-z, 0-9, and "!?,.-"
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 83 of file mavlink_msg_change_operator_control.h.
Referenced by mavlink_msg_change_operator_control_encode_chan(), and mavlink_test_change_operator_control().