APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_ekf_status_report.h File Reference
mavlink_msg_ekf_status_report.h File Reference
Classes
struct __mavlink_ekf_status_report_t
Macros
#define MAVLINK_MSG_ID_EKF_STATUS_REPORT 193
#define MAVLINK_MSG_ID_EKF_STATUS_REPORT_LEN 22
#define MAVLINK_MSG_ID_193_LEN 22
#define MAVLINK_MSG_ID_EKF_STATUS_REPORT_CRC 71
#define MAVLINK_MSG_ID_193_CRC 71
#define MAVLINK_MESSAGE_INFO_EKF_STATUS_REPORT
Typedefs
typedef struct __mavlink_ekf_status_report_t mavlink_ekf_status_report_t
Functions
static uint16_t mavlink_msg_ekf_status_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t flags, float velocity_variance, float pos_horiz_variance, float pos_vert_variance, float compass_variance, float terrain_alt_variance)
Pack a ekf_status_report message.
static uint16_t mavlink_msg_ekf_status_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t flags, float velocity_variance, float pos_horiz_variance, float pos_vert_variance, float compass_variance, float terrain_alt_variance)
Pack a ekf_status_report message on a channel.
static uint16_t mavlink_msg_ekf_status_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_ekf_status_report_t *ekf_status_report)
Encode a ekf_status_report struct.
static uint16_t mavlink_msg_ekf_status_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_ekf_status_report_t *ekf_status_report)
Encode a ekf_status_report struct on a channel.
static uint16_t mavlink_msg_ekf_status_report_get_flags (const mavlink_message_t *msg)
Send a ekf_status_report message.
static float mavlink_msg_ekf_status_report_get_velocity_variance (const mavlink_message_t *msg)
Get field velocity_variance from ekf_status_report message.
static float mavlink_msg_ekf_status_report_get_pos_horiz_variance (const mavlink_message_t *msg)
Get field pos_horiz_variance from ekf_status_report message.
static float mavlink_msg_ekf_status_report_get_pos_vert_variance (const mavlink_message_t *msg)
Get field pos_vert_variance from ekf_status_report message.
static float mavlink_msg_ekf_status_report_get_compass_variance (const mavlink_message_t *msg)
Get field compass_variance from ekf_status_report message.
static float mavlink_msg_ekf_status_report_get_terrain_alt_variance (const mavlink_message_t *msg)
Get field terrain_alt_variance from ekf_status_report message.
static void mavlink_msg_ekf_status_report_decode (const mavlink_message_t *msg, mavlink_ekf_status_report_t *ekf_status_report)
Decode a ekf_status_report message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_EKF_STATUS_REPORT
Value:
{ \
    "EKF_STATUS_REPORT", \
    6, \
    {  { "velocity_variance", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_ekf_status_report_t, velocity_variance) }, \
         { "pos_horiz_variance", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_ekf_status_report_t, pos_horiz_variance) }, \
         { "pos_vert_variance", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_ekf_status_report_t, pos_vert_variance) }, \
         { "compass_variance", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_ekf_status_report_t, compass_variance) }, \
         { "terrain_alt_variance", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_ekf_status_report_t, terrain_alt_variance) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT16_T, 0, 20, offsetof(mavlink_ekf_status_report_t, flags) }, \
         } \
}
Definition at line 23 of file mavlink_msg_ekf_status_report.h.
#define MAVLINK_MSG_ID_193_CRC 71
Definition at line 19 of file mavlink_msg_ekf_status_report.h.
#define MAVLINK_MSG_ID_193_LEN 22
Definition at line 16 of file mavlink_msg_ekf_status_report.h.
#define MAVLINK_MSG_ID_EKF_STATUS_REPORT 193
Definition at line 3 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_pack(), and mavlink_msg_ekf_status_report_pack_chan().
#define MAVLINK_MSG_ID_EKF_STATUS_REPORT_CRC 71
Definition at line 18 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_pack(), and mavlink_msg_ekf_status_report_pack_chan().
#define MAVLINK_MSG_ID_EKF_STATUS_REPORT_LEN 22
Definition at line 15 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode(), mavlink_msg_ekf_status_report_pack(), and mavlink_msg_ekf_status_report_pack_chan().
Typedef Documentation
typedef struct __mavlink_ekf_status_report_t mavlink_ekf_status_report_t
Function Documentation
static void mavlink_msg_ekf_status_report_decode (const mavlink_message_t * msg, mavlink_ekf_status_report_t * ekf_status_report) inline static
Decode a ekf_status_report message into a struct.
Parameters
msg The message to decode
ekf_status_report C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_test_ekf_status_report().
static uint16_t mavlink_msg_ekf_status_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_ekf_status_report_t * ekf_status_report) inline static
Encode a ekf_status_report struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
ekf_status_report C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_test_ekf_status_report().
static uint16_t mavlink_msg_ekf_status_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_ekf_status_report_t * ekf_status_report) inline static
Encode a ekf_status_report struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
ekf_status_report C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_ekf_status_report.h.
static float mavlink_msg_ekf_status_report_get_compass_variance (const mavlink_message_t * msg) inline static
Get field compass_variance from ekf_status_report message.
Returns
Compass variance
Definition at line 296 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode().
static uint16_t mavlink_msg_ekf_status_report_get_flags (const mavlink_message_t * msg) inline static
Send a ekf_status_report message.
Parameters
chan MAVLink channel to send the message
flags Flags
velocity_variance Velocity variance
pos_horiz_variance Horizontal Position variance
pos_vert_variance Vertical Position variance
compass_variance Compass variance
terrain_alt_variance Terrain Altitude variance Get field flags from ekf_status_report message
Returns
Flags
Definition at line 256 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode().
static float mavlink_msg_ekf_status_report_get_pos_horiz_variance (const mavlink_message_t * msg) inline static
Get field pos_horiz_variance from ekf_status_report message.
Returns
Horizontal Position variance
Definition at line 276 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode().
static float mavlink_msg_ekf_status_report_get_pos_vert_variance (const mavlink_message_t * msg) inline static
Get field pos_vert_variance from ekf_status_report message.
Returns
Vertical Position variance
Definition at line 286 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode().
static float mavlink_msg_ekf_status_report_get_terrain_alt_variance (const mavlink_message_t * msg) inline static
Get field terrain_alt_variance from ekf_status_report message.
Returns
Terrain Altitude variance
Definition at line 306 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode().
static float mavlink_msg_ekf_status_report_get_velocity_variance (const mavlink_message_t * msg) inline static
Get field velocity_variance from ekf_status_report message.
Returns
Velocity variance
Definition at line 266 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_decode().
static uint16_t mavlink_msg_ekf_status_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t flags, float velocity_variance, float pos_horiz_variance, float pos_vert_variance, float compass_variance, float terrain_alt_variance) inline static
Pack a ekf_status_report message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
flags Flags
velocity_variance Velocity variance
pos_horiz_variance Horizontal Position variance
pos_vert_variance Vertical Position variance
compass_variance Compass variance
terrain_alt_variance Terrain Altitude variance
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_encode(), and mavlink_test_ekf_status_report().
static uint16_t mavlink_msg_ekf_status_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t flags, float velocity_variance, float pos_horiz_variance, float pos_vert_variance, float compass_variance, float terrain_alt_variance) inline static
Pack a ekf_status_report message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
flags Flags
velocity_variance Velocity variance
pos_horiz_variance Horizontal Position variance
pos_vert_variance Vertical Position variance
compass_variance Compass variance
terrain_alt_variance Terrain Altitude variance
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_ekf_status_report.h.
Referenced by mavlink_msg_ekf_status_report_encode_chan(), and mavlink_test_ekf_status_report().