APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_led_control.h File Reference
mavlink_msg_led_control.h File Reference
Classes
struct __mavlink_led_control_t
Macros
#define MAVLINK_MSG_ID_LED_CONTROL 186
#define MAVLINK_MSG_ID_LED_CONTROL_LEN 29
#define MAVLINK_MSG_ID_186_LEN 29
#define MAVLINK_MSG_ID_LED_CONTROL_CRC 72
#define MAVLINK_MSG_ID_186_CRC 72
#define MAVLINK_MSG_LED_CONTROL_FIELD_CUSTOM_BYTES_LEN 24
#define MAVLINK_MESSAGE_INFO_LED_CONTROL
Typedefs
typedef struct __mavlink_led_control_t mavlink_led_control_t
Functions
static uint16_t mavlink_msg_led_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t instance, uint8_t pattern, uint8_t custom_len, const uint8_t *custom_bytes)
Pack a led_control message.
static uint16_t mavlink_msg_led_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t instance, uint8_t pattern, uint8_t custom_len, const uint8_t *custom_bytes)
Pack a led_control message on a channel.
static uint16_t mavlink_msg_led_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_led_control_t *led_control)
Encode a led_control struct.
static uint16_t mavlink_msg_led_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_led_control_t *led_control)
Encode a led_control struct on a channel.
static uint8_t mavlink_msg_led_control_get_target_system (const mavlink_message_t *msg)
Send a led_control message.
static uint8_t mavlink_msg_led_control_get_target_component (const mavlink_message_t *msg)
Get field target_component from led_control message.
static uint8_t mavlink_msg_led_control_get_instance (const mavlink_message_t *msg)
Get field instance from led_control message.
static uint8_t mavlink_msg_led_control_get_pattern (const mavlink_message_t *msg)
Get field pattern from led_control message.
static uint8_t mavlink_msg_led_control_get_custom_len (const mavlink_message_t *msg)
Get field custom_len from led_control message.
static uint16_t mavlink_msg_led_control_get_custom_bytes (const mavlink_message_t *msg, uint8_t *custom_bytes)
Get field custom_bytes from led_control message.
static void mavlink_msg_led_control_decode (const mavlink_message_t *msg, mavlink_led_control_t *led_control)
Decode a led_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LED_CONTROL
Value:
{ \
    "LED_CONTROL", \
    6, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_led_control_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_led_control_t, target_component) }, \
         { "instance", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_led_control_t, instance) }, \
         { "pattern", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_led_control_t, pattern) }, \
         { "custom_len", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_led_control_t, custom_len) }, \
         { "custom_bytes", NULL, MAVLINK_TYPE_UINT8_T, 24, 5, offsetof(mavlink_led_control_t, custom_bytes) }, \
         } \
}
Definition at line 23 of file mavlink_msg_led_control.h.
#define MAVLINK_MSG_ID_186_CRC 72
Definition at line 19 of file mavlink_msg_led_control.h.
#define MAVLINK_MSG_ID_186_LEN 29
Definition at line 16 of file mavlink_msg_led_control.h.
#define MAVLINK_MSG_ID_LED_CONTROL 186
Definition at line 3 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_pack(), and mavlink_msg_led_control_pack_chan().
#define MAVLINK_MSG_ID_LED_CONTROL_CRC 72
Definition at line 18 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_pack(), and mavlink_msg_led_control_pack_chan().
#define MAVLINK_MSG_ID_LED_CONTROL_LEN 29
Definition at line 15 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode(), mavlink_msg_led_control_pack(), and mavlink_msg_led_control_pack_chan().
#define MAVLINK_MSG_LED_CONTROL_FIELD_CUSTOM_BYTES_LEN 24
Definition at line 21 of file mavlink_msg_led_control.h.
Typedef Documentation
typedef struct __mavlink_led_control_t mavlink_led_control_t
Function Documentation
static void mavlink_msg_led_control_decode (const mavlink_message_t * msg, mavlink_led_control_t * led_control) inline static
Decode a led_control message into a struct.
Parameters
msg The message to decode
led_control C-struct to decode the message contents into
Definition at line 309 of file mavlink_msg_led_control.h.
Referenced by OreoLED_PX4::handle_led_control(), and mavlink_test_led_control().
static uint16_t mavlink_msg_led_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_led_control_t * led_control) inline static
Encode a led_control struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
led_control C-struct to read the message contents from
Definition at line 135 of file mavlink_msg_led_control.h.
Referenced by mavlink_test_led_control().
static uint16_t mavlink_msg_led_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_led_control_t * led_control) inline static
Encode a led_control struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
led_control C-struct to read the message contents from
Definition at line 149 of file mavlink_msg_led_control.h.
static uint16_t mavlink_msg_led_control_get_custom_bytes (const mavlink_message_t * msg, uint8_t * custom_bytes) inline static
Get field custom_bytes from led_control message.
Returns
Custom Bytes
Definition at line 298 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode().
static uint8_t mavlink_msg_led_control_get_custom_len (const mavlink_message_t * msg) inline static
Get field custom_len from led_control message.
Returns
Custom Byte Length
Definition at line 288 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode().
static uint8_t mavlink_msg_led_control_get_instance (const mavlink_message_t * msg) inline static
Get field instance from led_control message.
Returns
Instance (LED instance to control or 255 for all LEDs)
Definition at line 268 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode().
static uint8_t mavlink_msg_led_control_get_pattern (const mavlink_message_t * msg) inline static
Get field pattern from led_control message.
Returns
Pattern (see LED_PATTERN_ENUM)
Definition at line 278 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode().
static uint8_t mavlink_msg_led_control_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from led_control message.
Returns
Component ID
Definition at line 258 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode().
static uint8_t mavlink_msg_led_control_get_target_system (const mavlink_message_t * msg) inline static
Send a led_control message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
instance Instance (LED instance to control or 255 for all LEDs)
pattern Pattern (see LED_PATTERN_ENUM)
custom_len Custom Byte Length
custom_bytes Custom Bytes Get field target_system from led_control message
Returns
System ID
Definition at line 248 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_decode().
static uint16_t mavlink_msg_led_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t instance, uint8_t pattern, uint8_t custom_len, const uint8_t * custom_bytes) inline static
Pack a led_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
instance Instance (LED instance to control or 255 for all LEDs)
pattern Pattern (see LED_PATTERN_ENUM)
custom_len Custom Byte Length
custom_bytes Custom Bytes
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_encode(), and mavlink_test_led_control().
static uint16_t mavlink_msg_led_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t instance, uint8_t pattern, uint8_t custom_len, const uint8_t * custom_bytes) inline static
Pack a led_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
instance Instance (LED instance to control or 255 for all LEDs)
pattern Pattern (see LED_PATTERN_ENUM)
custom_len Custom Byte Length
custom_bytes Custom Bytes
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 95 of file mavlink_msg_led_control.h.
Referenced by mavlink_msg_led_control_encode_chan(), and mavlink_test_led_control().