APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_radio.h File Reference
mavlink_msg_radio.h File Reference
Classes
struct __mavlink_radio_t
Macros
#define MAVLINK_MSG_ID_RADIO 166
#define MAVLINK_MSG_ID_RADIO_LEN 9
#define MAVLINK_MSG_ID_166_LEN 9
#define MAVLINK_MSG_ID_RADIO_CRC 21
#define MAVLINK_MSG_ID_166_CRC 21
#define MAVLINK_MESSAGE_INFO_RADIO
Typedefs
typedef struct __mavlink_radio_t mavlink_radio_t
Functions
static uint16_t mavlink_msg_radio_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t rssi, uint8_t remrssi, uint8_t txbuf, uint8_t noise, uint8_t remnoise, uint16_t rxerrors, uint16_t fixed)
Pack a radio message.
static uint16_t mavlink_msg_radio_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t rssi, uint8_t remrssi, uint8_t txbuf, uint8_t noise, uint8_t remnoise, uint16_t rxerrors, uint16_t fixed)
Pack a radio message on a channel.
static uint16_t mavlink_msg_radio_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_radio_t *radio)
Encode a radio struct.
static uint16_t mavlink_msg_radio_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_radio_t *radio)
Encode a radio struct on a channel.
static uint8_t mavlink_msg_radio_get_rssi (const mavlink_message_t *msg)
Send a radio message.
static uint8_t mavlink_msg_radio_get_remrssi (const mavlink_message_t *msg)
Get field remrssi from radio message.
static uint8_t mavlink_msg_radio_get_txbuf (const mavlink_message_t *msg)
Get field txbuf from radio message.
static uint8_t mavlink_msg_radio_get_noise (const mavlink_message_t *msg)
Get field noise from radio message.
static uint8_t mavlink_msg_radio_get_remnoise (const mavlink_message_t *msg)
Get field remnoise from radio message.
static uint16_t mavlink_msg_radio_get_rxerrors (const mavlink_message_t *msg)
Get field rxerrors from radio message.
static uint16_t mavlink_msg_radio_get_fixed (const mavlink_message_t *msg)
Get field fixed from radio message.
static void mavlink_msg_radio_decode (const mavlink_message_t *msg, mavlink_radio_t *radio)
Decode a radio message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RADIO
Value:
{ \
    "RADIO", \
    7, \
    {  { "rxerrors", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_radio_t, rxerrors) }, \
         { "fixed", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_radio_t, fixed) }, \
         { "rssi", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_radio_t, rssi) }, \
         { "remrssi", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_radio_t, remrssi) }, \
         { "txbuf", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_radio_t, txbuf) }, \
         { "noise", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_radio_t, noise) }, \
         { "remnoise", NULL, MAVLINK_TYPE_UINT8_T, 0, 8, offsetof(mavlink_radio_t, remnoise) }, \
         } \
}
Definition at line 24 of file mavlink_msg_radio.h.
#define MAVLINK_MSG_ID_166_CRC 21
Definition at line 20 of file mavlink_msg_radio.h.
#define MAVLINK_MSG_ID_166_LEN 9
Definition at line 17 of file mavlink_msg_radio.h.
#define MAVLINK_MSG_ID_RADIO 166
Definition at line 3 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_pack(), mavlink_msg_radio_pack_chan(), and GCS_MAVLINK::update().
#define MAVLINK_MSG_ID_RADIO_CRC 21
Definition at line 19 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_pack(), and mavlink_msg_radio_pack_chan().
#define MAVLINK_MSG_ID_RADIO_LEN 9
Definition at line 16 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode(), mavlink_msg_radio_pack(), and mavlink_msg_radio_pack_chan().
Typedef Documentation
typedef struct __mavlink_radio_t mavlink_radio_t
Function Documentation
static void mavlink_msg_radio_decode (const mavlink_message_t * msg, mavlink_radio_t * radio) inline static
Decode a radio message into a struct.
Parameters
msg The message to decode
radio C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_radio.h.
Referenced by GCS_MAVLINK::handle_radio_status(), and mavlink_test_radio().
static uint16_t mavlink_msg_radio_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_radio_t * radio) inline static
Encode a radio struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
radio C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_radio.h.
Referenced by mavlink_test_radio().
static uint16_t mavlink_msg_radio_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_radio_t * radio) inline static
Encode a radio struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
radio C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_radio.h.
static uint16_t mavlink_msg_radio_get_fixed (const mavlink_message_t * msg) inline static
Get field fixed from radio message.
Returns
count of error corrected packets
Definition at line 329 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint8_t mavlink_msg_radio_get_noise (const mavlink_message_t * msg) inline static
Get field noise from radio message.
Returns
background noise level
Definition at line 299 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint8_t mavlink_msg_radio_get_remnoise (const mavlink_message_t * msg) inline static
Get field remnoise from radio message.
Returns
remote background noise level
Definition at line 309 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint8_t mavlink_msg_radio_get_remrssi (const mavlink_message_t * msg) inline static
Get field remrssi from radio message.
Returns
remote signal strength
Definition at line 279 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint8_t mavlink_msg_radio_get_rssi (const mavlink_message_t * msg) inline static
Send a radio message.
Parameters
chan MAVLink channel to send the message
rssi local signal strength
remrssi remote signal strength
txbuf how full the tx buffer is as a percentage
noise background noise level
remnoise remote background noise level
rxerrors receive errors
fixed count of error corrected packets Get field rssi from radio message
Returns
local signal strength
Definition at line 269 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint16_t mavlink_msg_radio_get_rxerrors (const mavlink_message_t * msg) inline static
Get field rxerrors from radio message.
Returns
receive errors
Definition at line 319 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint8_t mavlink_msg_radio_get_txbuf (const mavlink_message_t * msg) inline static
Get field txbuf from radio message.
Returns
how full the tx buffer is as a percentage
Definition at line 289 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_decode().
static uint16_t mavlink_msg_radio_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t rssi, uint8_t remrssi, uint8_t txbuf, uint8_t noise, uint8_t remnoise, uint16_t rxerrors, uint16_t fixed) inline static
Pack a radio message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rssi local signal strength
remrssi remote signal strength
txbuf how full the tx buffer is as a percentage
noise background noise level
remnoise remote background noise level
rxerrors receive errors
fixed count of error corrected packets
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_encode(), and mavlink_test_radio().
static uint16_t mavlink_msg_radio_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t rssi, uint8_t remrssi, uint8_t txbuf, uint8_t noise, uint8_t remnoise, uint16_t rxerrors, uint16_t fixed) inline static
Pack a radio message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rssi local signal strength
remrssi remote signal strength
txbuf how full the tx buffer is as a percentage
noise background noise level
remnoise remote background noise level
rxerrors receive errors
fixed count of error corrected packets
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_radio.h.
Referenced by mavlink_msg_radio_encode_chan(), and mavlink_test_radio().