APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_ahrs2.h File Reference
mavlink_msg_ahrs2.h File Reference
Classes
struct __mavlink_ahrs2_t
Macros
#define MAVLINK_MSG_ID_AHRS2 178
#define MAVLINK_MSG_ID_AHRS2_LEN 24
#define MAVLINK_MSG_ID_178_LEN 24
#define MAVLINK_MSG_ID_AHRS2_CRC 47
#define MAVLINK_MSG_ID_178_CRC 47
#define MAVLINK_MESSAGE_INFO_AHRS2
Typedefs
typedef struct __mavlink_ahrs2_t mavlink_ahrs2_t
Functions
static uint16_t mavlink_msg_ahrs2_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng)
Pack a ahrs2 message.
static uint16_t mavlink_msg_ahrs2_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng)
Pack a ahrs2 message on a channel.
static uint16_t mavlink_msg_ahrs2_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_ahrs2_t *ahrs2)
Encode a ahrs2 struct.
static uint16_t mavlink_msg_ahrs2_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_ahrs2_t *ahrs2)
Encode a ahrs2 struct on a channel.
static float mavlink_msg_ahrs2_get_roll (const mavlink_message_t *msg)
Send a ahrs2 message.
static float mavlink_msg_ahrs2_get_pitch (const mavlink_message_t *msg)
Get field pitch from ahrs2 message.
static float mavlink_msg_ahrs2_get_yaw (const mavlink_message_t *msg)
Get field yaw from ahrs2 message.
static float mavlink_msg_ahrs2_get_altitude (const mavlink_message_t *msg)
Get field altitude from ahrs2 message.
static int32_t mavlink_msg_ahrs2_get_lat (const mavlink_message_t *msg)
Get field lat from ahrs2 message.
static int32_t mavlink_msg_ahrs2_get_lng (const mavlink_message_t *msg)
Get field lng from ahrs2 message.
static void mavlink_msg_ahrs2_decode (const mavlink_message_t *msg, mavlink_ahrs2_t *ahrs2)
Decode a ahrs2 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AHRS2
Value:
{ \
    "AHRS2", \
    6, \
    {  { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_ahrs2_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_ahrs2_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_ahrs2_t, yaw) }, \
         { "altitude", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_ahrs2_t, altitude) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 16, offsetof(mavlink_ahrs2_t, lat) }, \
         { "lng", NULL, MAVLINK_TYPE_INT32_T, 0, 20, offsetof(mavlink_ahrs2_t, lng) }, \
         } \
}
Definition at line 23 of file mavlink_msg_ahrs2.h.
#define MAVLINK_MSG_ID_178_CRC 47
Definition at line 19 of file mavlink_msg_ahrs2.h.
#define MAVLINK_MSG_ID_178_LEN 24
Definition at line 16 of file mavlink_msg_ahrs2.h.
#define MAVLINK_MSG_ID_AHRS2 178
Definition at line 3 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_pack(), and mavlink_msg_ahrs2_pack_chan().
#define MAVLINK_MSG_ID_AHRS2_CRC 47
Definition at line 18 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_pack(), and mavlink_msg_ahrs2_pack_chan().
#define MAVLINK_MSG_ID_AHRS2_LEN 24
Definition at line 15 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode(), mavlink_msg_ahrs2_pack(), and mavlink_msg_ahrs2_pack_chan().
Typedef Documentation
typedef struct __mavlink_ahrs2_t mavlink_ahrs2_t
Function Documentation
static void mavlink_msg_ahrs2_decode (const mavlink_message_t * msg, mavlink_ahrs2_t * ahrs2) inline static
Decode a ahrs2 message into a struct.
Parameters
msg The message to decode
ahrs2 C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_test_ahrs2().
static uint16_t mavlink_msg_ahrs2_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_ahrs2_t * ahrs2) inline static
Encode a ahrs2 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
ahrs2 C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_test_ahrs2().
static uint16_t mavlink_msg_ahrs2_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_ahrs2_t * ahrs2) inline static
Encode a ahrs2 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
ahrs2 C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_ahrs2.h.
static float mavlink_msg_ahrs2_get_altitude (const mavlink_message_t * msg) inline static
Get field altitude from ahrs2 message.
Returns
Altitude (MSL)
Definition at line 286 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode().
static int32_t mavlink_msg_ahrs2_get_lat (const mavlink_message_t * msg) inline static
Get field lat from ahrs2 message.
Returns
Latitude in degrees * 1E7
Definition at line 296 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode().
static int32_t mavlink_msg_ahrs2_get_lng (const mavlink_message_t * msg) inline static
Get field lng from ahrs2 message.
Returns
Longitude in degrees * 1E7
Definition at line 306 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode().
static float mavlink_msg_ahrs2_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from ahrs2 message.
Returns
Pitch angle (rad)
Definition at line 266 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode().
static float mavlink_msg_ahrs2_get_roll (const mavlink_message_t * msg) inline static
Send a ahrs2 message.
Parameters
chan MAVLink channel to send the message
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
altitude Altitude (MSL)
lat Latitude in degrees * 1E7
lng Longitude in degrees * 1E7 Get field roll from ahrs2 message
Returns
Roll angle (rad)
Definition at line 256 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode().
static float mavlink_msg_ahrs2_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from ahrs2 message.
Returns
Yaw angle (rad)
Definition at line 276 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_decode().
static uint16_t mavlink_msg_ahrs2_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng) inline static
Pack a ahrs2 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
altitude Altitude (MSL)
lat Latitude in degrees * 1E7
lng Longitude in degrees * 1E7
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_encode(), and mavlink_test_ahrs2().
static uint16_t mavlink_msg_ahrs2_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng) inline static
Pack a ahrs2 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
altitude Altitude (MSL)
lat Latitude in degrees * 1E7
lng Longitude in degrees * 1E7
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_ahrs2.h.
Referenced by mavlink_msg_ahrs2_encode_chan(), and mavlink_test_ahrs2().