APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_raw_pressure.h File Reference
mavlink_msg_raw_pressure.h File Reference
Classes
struct __mavlink_raw_pressure_t
Macros
#define MAVLINK_MSG_ID_RAW_PRESSURE 28
#define MAVLINK_MSG_ID_RAW_PRESSURE_LEN 16
#define MAVLINK_MSG_ID_28_LEN 16
#define MAVLINK_MSG_ID_RAW_PRESSURE_CRC 67
#define MAVLINK_MSG_ID_28_CRC 67
#define MAVLINK_MESSAGE_INFO_RAW_PRESSURE
Typedefs
typedef struct __mavlink_raw_pressure_t mavlink_raw_pressure_t
Functions
static uint16_t mavlink_msg_raw_pressure_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, int16_t press_abs, int16_t press_diff1, int16_t press_diff2, int16_t temperature)
Pack a raw_pressure message.
static uint16_t mavlink_msg_raw_pressure_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, int16_t press_abs, int16_t press_diff1, int16_t press_diff2, int16_t temperature)
Pack a raw_pressure message on a channel.
static uint16_t mavlink_msg_raw_pressure_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_raw_pressure_t *raw_pressure)
Encode a raw_pressure struct.
static uint16_t mavlink_msg_raw_pressure_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_raw_pressure_t *raw_pressure)
Encode a raw_pressure struct on a channel.
static uint64_t mavlink_msg_raw_pressure_get_time_usec (const mavlink_message_t *msg)
Send a raw_pressure message.
static int16_t mavlink_msg_raw_pressure_get_press_abs (const mavlink_message_t *msg)
Get field press_abs from raw_pressure message.
static int16_t mavlink_msg_raw_pressure_get_press_diff1 (const mavlink_message_t *msg)
Get field press_diff1 from raw_pressure message.
static int16_t mavlink_msg_raw_pressure_get_press_diff2 (const mavlink_message_t *msg)
Get field press_diff2 from raw_pressure message.
static int16_t mavlink_msg_raw_pressure_get_temperature (const mavlink_message_t *msg)
Get field temperature from raw_pressure message.
static void mavlink_msg_raw_pressure_decode (const mavlink_message_t *msg, mavlink_raw_pressure_t *raw_pressure)
Decode a raw_pressure message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RAW_PRESSURE
Value:
{ \
    "RAW_PRESSURE", \
    5, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_raw_pressure_t, time_usec) }, \
         { "press_abs", NULL, MAVLINK_TYPE_INT16_T, 0, 8, offsetof(mavlink_raw_pressure_t, press_abs) }, \
         { "press_diff1", NULL, MAVLINK_TYPE_INT16_T, 0, 10, offsetof(mavlink_raw_pressure_t, press_diff1) }, \
         { "press_diff2", NULL, MAVLINK_TYPE_INT16_T, 0, 12, offsetof(mavlink_raw_pressure_t, press_diff2) }, \
         { "temperature", NULL, MAVLINK_TYPE_INT16_T, 0, 14, offsetof(mavlink_raw_pressure_t, temperature) }, \
         } \
}
Definition at line 22 of file mavlink_msg_raw_pressure.h.
#define MAVLINK_MSG_ID_28_CRC 67
Definition at line 18 of file mavlink_msg_raw_pressure.h.
#define MAVLINK_MSG_ID_28_LEN 16
Definition at line 15 of file mavlink_msg_raw_pressure.h.
#define MAVLINK_MSG_ID_RAW_PRESSURE 28
Definition at line 3 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_pack(), and mavlink_msg_raw_pressure_pack_chan().
#define MAVLINK_MSG_ID_RAW_PRESSURE_CRC 67
Definition at line 17 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_pack(), and mavlink_msg_raw_pressure_pack_chan().
#define MAVLINK_MSG_ID_RAW_PRESSURE_LEN 16
Definition at line 14 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_decode(), mavlink_msg_raw_pressure_pack(), and mavlink_msg_raw_pressure_pack_chan().
Typedef Documentation
typedef struct __mavlink_raw_pressure_t mavlink_raw_pressure_t
Function Documentation
static void mavlink_msg_raw_pressure_decode (const mavlink_message_t * msg, mavlink_raw_pressure_t * raw_pressure) inline static
Decode a raw_pressure message into a struct.
Parameters
msg The message to decode
raw_pressure C-struct to decode the message contents into
Definition at line 294 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_test_raw_pressure().
static uint16_t mavlink_msg_raw_pressure_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_raw_pressure_t * raw_pressure) inline static
Encode a raw_pressure struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
raw_pressure C-struct to read the message contents from
Definition at line 131 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_test_raw_pressure().
static uint16_t mavlink_msg_raw_pressure_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_raw_pressure_t * raw_pressure) inline static
Encode a raw_pressure struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
raw_pressure C-struct to read the message contents from
Definition at line 145 of file mavlink_msg_raw_pressure.h.
static int16_t mavlink_msg_raw_pressure_get_press_abs (const mavlink_message_t * msg) inline static
Get field press_abs from raw_pressure message.
Returns
Absolute pressure (raw)
Definition at line 253 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_decode().
static int16_t mavlink_msg_raw_pressure_get_press_diff1 (const mavlink_message_t * msg) inline static
Get field press_diff1 from raw_pressure message.
Returns
Differential pressure 1 (raw)
Definition at line 263 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_decode().
static int16_t mavlink_msg_raw_pressure_get_press_diff2 (const mavlink_message_t * msg) inline static
Get field press_diff2 from raw_pressure message.
Returns
Differential pressure 2 (raw)
Definition at line 273 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_decode().
static int16_t mavlink_msg_raw_pressure_get_temperature (const mavlink_message_t * msg) inline static
Get field temperature from raw_pressure message.
Returns
Raw Temperature measurement (raw)
Definition at line 283 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_decode().
static uint64_t mavlink_msg_raw_pressure_get_time_usec (const mavlink_message_t * msg) inline static
Send a raw_pressure message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
press_abs Absolute pressure (raw)
press_diff1 Differential pressure 1 (raw)
press_diff2 Differential pressure 2 (raw)
temperature Raw Temperature measurement (raw) Get field time_usec from raw_pressure message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 243 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_decode().
static uint16_t mavlink_msg_raw_pressure_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, int16_t press_abs, int16_t press_diff1, int16_t press_diff2, int16_t temperature) inline static
Pack a raw_pressure message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
press_abs Absolute pressure (raw)
press_diff1 Differential pressure 1 (raw)
press_diff2 Differential pressure 2 (raw)
temperature Raw Temperature measurement (raw)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_encode(), and mavlink_test_raw_pressure().
static uint16_t mavlink_msg_raw_pressure_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, int16_t press_abs, int16_t press_diff1, int16_t press_diff2, int16_t temperature) inline static
Pack a raw_pressure message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
press_abs Absolute pressure (raw)
press_diff1 Differential pressure 1 (raw)
press_diff2 Differential pressure 2 (raw)
temperature Raw Temperature measurement (raw)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 91 of file mavlink_msg_raw_pressure.h.
Referenced by mavlink_msg_raw_pressure_encode_chan(), and mavlink_test_raw_pressure().