APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_param_set.h File Reference
mavlink_msg_param_set.h File Reference
Classes
struct __mavlink_param_set_t
Macros
#define MAVLINK_MSG_ID_PARAM_SET 23
#define MAVLINK_MSG_ID_PARAM_SET_LEN 23
#define MAVLINK_MSG_ID_23_LEN 23
#define MAVLINK_MSG_ID_PARAM_SET_CRC 168
#define MAVLINK_MSG_ID_23_CRC 168
#define MAVLINK_MSG_PARAM_SET_FIELD_PARAM_ID_LEN 16
#define MAVLINK_MESSAGE_INFO_PARAM_SET
Typedefs
typedef struct __mavlink_param_set_t mavlink_param_set_t
Functions
static uint16_t mavlink_msg_param_set_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, const char *param_id, float param_value, uint8_t param_type)
Pack a param_set message.
static uint16_t mavlink_msg_param_set_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, const char *param_id, float param_value, uint8_t param_type)
Pack a param_set message on a channel.
static uint16_t mavlink_msg_param_set_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_param_set_t *param_set)
Encode a param_set struct.
static uint16_t mavlink_msg_param_set_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_param_set_t *param_set)
Encode a param_set struct on a channel.
static uint8_t mavlink_msg_param_set_get_target_system (const mavlink_message_t *msg)
Send a param_set message.
static uint8_t mavlink_msg_param_set_get_target_component (const mavlink_message_t *msg)
Get field target_component from param_set message.
static uint16_t mavlink_msg_param_set_get_param_id (const mavlink_message_t *msg, char *param_id)
Get field param_id from param_set message.
static float mavlink_msg_param_set_get_param_value (const mavlink_message_t *msg)
Get field param_value from param_set message.
static uint8_t mavlink_msg_param_set_get_param_type (const mavlink_message_t *msg)
Get field param_type from param_set message.
static void mavlink_msg_param_set_decode (const mavlink_message_t *msg, mavlink_param_set_t *param_set)
Decode a param_set message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_PARAM_SET
Value:
{ \
    "PARAM_SET", \
    5, \
    {  { "param_value", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_param_set_t, param_value) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_param_set_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_param_set_t, target_component) }, \
         { "param_id", NULL, MAVLINK_TYPE_CHAR, 16, 6, offsetof(mavlink_param_set_t, param_id) }, \
         { "param_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 22, offsetof(mavlink_param_set_t, param_type) }, \
         } \
}
Definition at line 22 of file mavlink_msg_param_set.h.
#define MAVLINK_MSG_ID_23_CRC 168
Definition at line 18 of file mavlink_msg_param_set.h.
#define MAVLINK_MSG_ID_23_LEN 23
Definition at line 15 of file mavlink_msg_param_set.h.
#define MAVLINK_MSG_ID_PARAM_SET 23
Definition at line 3 of file mavlink_msg_param_set.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_param_set_pack(), and mavlink_msg_param_set_pack_chan().
#define MAVLINK_MSG_ID_PARAM_SET_CRC 168
Definition at line 17 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_pack(), and mavlink_msg_param_set_pack_chan().
#define MAVLINK_MSG_ID_PARAM_SET_LEN 23
Definition at line 14 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_decode(), mavlink_msg_param_set_pack(), and mavlink_msg_param_set_pack_chan().
#define MAVLINK_MSG_PARAM_SET_FIELD_PARAM_ID_LEN 16
Definition at line 20 of file mavlink_msg_param_set.h.
Typedef Documentation
typedef struct __mavlink_param_set_t mavlink_param_set_t
Function Documentation
static void mavlink_msg_param_set_decode (const mavlink_message_t * msg, mavlink_param_set_t * param_set) inline static
Decode a param_set message into a struct.
Parameters
msg The message to decode
param_set C-struct to decode the message contents into
Definition at line 286 of file mavlink_msg_param_set.h.
Referenced by GCS_MAVLINK::handle_param_set(), and mavlink_test_param_set().
static uint16_t mavlink_msg_param_set_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_param_set_t * param_set) inline static
Encode a param_set struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
param_set C-struct to read the message contents from
Definition at line 127 of file mavlink_msg_param_set.h.
Referenced by loop(), and mavlink_test_param_set().
static uint16_t mavlink_msg_param_set_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_param_set_t * param_set) inline static
Encode a param_set struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
param_set C-struct to read the message contents from
Definition at line 141 of file mavlink_msg_param_set.h.
static uint16_t mavlink_msg_param_set_get_param_id (const mavlink_message_t * msg, char * param_id) inline static
Get field param_id from param_set message.
Returns
Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
Definition at line 255 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_decode().
static uint8_t mavlink_msg_param_set_get_param_type (const mavlink_message_t * msg) inline static
Get field param_type from param_set message.
Returns
Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
Definition at line 275 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_decode().
static float mavlink_msg_param_set_get_param_value (const mavlink_message_t * msg) inline static
Get field param_value from param_set message.
Returns
Onboard parameter value
Definition at line 265 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_decode().
static uint8_t mavlink_msg_param_set_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from param_set message.
Returns
Component ID
Definition at line 245 of file mavlink_msg_param_set.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_param_set_decode().
static uint8_t mavlink_msg_param_set_get_target_system (const mavlink_message_t * msg) inline static
Send a param_set message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_value Onboard parameter value
param_type Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types. Get field target_system from param_set message
Returns
System ID
Definition at line 235 of file mavlink_msg_param_set.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_param_set_decode().
static uint16_t mavlink_msg_param_set_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, const char * param_id, float param_value, uint8_t param_type) inline static
Pack a param_set message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_value Onboard parameter value
param_type Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_encode(), and mavlink_test_param_set().
static uint16_t mavlink_msg_param_set_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, const char * param_id, float param_value, uint8_t param_type) inline static
Pack a param_set message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
param_id Onboard parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
param_value Onboard parameter value
param_type Onboard parameter type: see the MAV_PARAM_TYPE enum for supported data types.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 89 of file mavlink_msg_param_set.h.
Referenced by mavlink_msg_param_set_encode_chan(), and mavlink_test_param_set().