APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_digicam_configure.h File Reference
mavlink_msg_digicam_configure.h File Reference
Classes
struct __mavlink_digicam_configure_t
Macros
#define MAVLINK_MSG_ID_DIGICAM_CONFIGURE 154
#define MAVLINK_MSG_ID_DIGICAM_CONFIGURE_LEN 15
#define MAVLINK_MSG_ID_154_LEN 15
#define MAVLINK_MSG_ID_DIGICAM_CONFIGURE_CRC 84
#define MAVLINK_MSG_ID_154_CRC 84
#define MAVLINK_MESSAGE_INFO_DIGICAM_CONFIGURE
Typedefs
typedef struct __mavlink_digicam_configure_t mavlink_digicam_configure_t
Functions
static uint16_t mavlink_msg_digicam_configure_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t mode, uint16_t shutter_speed, uint8_t aperture, uint8_t iso, uint8_t exposure_type, uint8_t command_id, uint8_t engine_cut_off, uint8_t extra_param, float extra_value)
Pack a digicam_configure message.
static uint16_t mavlink_msg_digicam_configure_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t mode, uint16_t shutter_speed, uint8_t aperture, uint8_t iso, uint8_t exposure_type, uint8_t command_id, uint8_t engine_cut_off, uint8_t extra_param, float extra_value)
Pack a digicam_configure message on a channel.
static uint16_t mavlink_msg_digicam_configure_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_digicam_configure_t *digicam_configure)
Encode a digicam_configure struct.
static uint16_t mavlink_msg_digicam_configure_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_digicam_configure_t *digicam_configure)
Encode a digicam_configure struct on a channel.
static uint8_t mavlink_msg_digicam_configure_get_target_system (const mavlink_message_t *msg)
Send a digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_target_component (const mavlink_message_t *msg)
Get field target_component from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_mode (const mavlink_message_t *msg)
Get field mode from digicam_configure message.
static uint16_t mavlink_msg_digicam_configure_get_shutter_speed (const mavlink_message_t *msg)
Get field shutter_speed from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_aperture (const mavlink_message_t *msg)
Get field aperture from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_iso (const mavlink_message_t *msg)
Get field iso from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_exposure_type (const mavlink_message_t *msg)
Get field exposure_type from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_command_id (const mavlink_message_t *msg)
Get field command_id from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_engine_cut_off (const mavlink_message_t *msg)
Get field engine_cut_off from digicam_configure message.
static uint8_t mavlink_msg_digicam_configure_get_extra_param (const mavlink_message_t *msg)
Get field extra_param from digicam_configure message.
static float mavlink_msg_digicam_configure_get_extra_value (const mavlink_message_t *msg)
Get field extra_value from digicam_configure message.
static void mavlink_msg_digicam_configure_decode (const mavlink_message_t *msg, mavlink_digicam_configure_t *digicam_configure)
Decode a digicam_configure message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DIGICAM_CONFIGURE
Value:
{ \
    "DIGICAM_CONFIGURE", \
    11, \
    {  { "extra_value", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_digicam_configure_t, extra_value) }, \
         { "shutter_speed", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_digicam_configure_t, shutter_speed) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_digicam_configure_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_digicam_configure_t, target_component) }, \
         { "mode", NULL, MAVLINK_TYPE_UINT8_T, 0, 8, offsetof(mavlink_digicam_configure_t, mode) }, \
         { "aperture", NULL, MAVLINK_TYPE_UINT8_T, 0, 9, offsetof(mavlink_digicam_configure_t, aperture) }, \
         { "iso", NULL, MAVLINK_TYPE_UINT8_T, 0, 10, offsetof(mavlink_digicam_configure_t, iso) }, \
         { "exposure_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 11, offsetof(mavlink_digicam_configure_t, exposure_type) }, \
         { "command_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 12, offsetof(mavlink_digicam_configure_t, command_id) }, \
         { "engine_cut_off", NULL, MAVLINK_TYPE_UINT8_T, 0, 13, offsetof(mavlink_digicam_configure_t, engine_cut_off) }, \
         { "extra_param", NULL, MAVLINK_TYPE_UINT8_T, 0, 14, offsetof(mavlink_digicam_configure_t, extra_param) }, \
         } \
}
Definition at line 28 of file mavlink_msg_digicam_configure.h.
#define MAVLINK_MSG_ID_154_CRC 84
Definition at line 24 of file mavlink_msg_digicam_configure.h.
#define MAVLINK_MSG_ID_154_LEN 15
Definition at line 21 of file mavlink_msg_digicam_configure.h.
#define MAVLINK_MSG_ID_DIGICAM_CONFIGURE 154
Definition at line 3 of file mavlink_msg_digicam_configure.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_digicam_configure_pack(), and mavlink_msg_digicam_configure_pack_chan().
#define MAVLINK_MSG_ID_DIGICAM_CONFIGURE_CRC 84
Definition at line 23 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_pack(), and mavlink_msg_digicam_configure_pack_chan().
#define MAVLINK_MSG_ID_DIGICAM_CONFIGURE_LEN 15
Definition at line 20 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode(), mavlink_msg_digicam_configure_pack(), and mavlink_msg_digicam_configure_pack_chan().
Typedef Documentation
typedef struct __mavlink_digicam_configure_t mavlink_digicam_configure_t
Function Documentation
static void mavlink_msg_digicam_configure_decode (const mavlink_message_t * msg, mavlink_digicam_configure_t * digicam_configure) inline static
Decode a digicam_configure message into a struct.
Parameters
msg The message to decode
digicam_configure C-struct to decode the message contents into
Definition at line 432 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_test_digicam_configure().
static uint16_t mavlink_msg_digicam_configure_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_digicam_configure_t * digicam_configure) inline static
Encode a digicam_configure struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
digicam_configure C-struct to read the message contents from
Definition at line 179 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_test_digicam_configure().
static uint16_t mavlink_msg_digicam_configure_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_digicam_configure_t * digicam_configure) inline static
Encode a digicam_configure struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
digicam_configure C-struct to read the message contents from
Definition at line 193 of file mavlink_msg_digicam_configure.h.
static uint8_t mavlink_msg_digicam_configure_get_aperture (const mavlink_message_t * msg) inline static
Get field aperture from digicam_configure message.
Returns
F stop number x 10 //e.g. 28 means 2.8 (0 means ignore)
Definition at line 361 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_command_id (const mavlink_message_t * msg) inline static
Get field command_id from digicam_configure message.
Returns
Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
Definition at line 391 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_engine_cut_off (const mavlink_message_t * msg) inline static
Get field engine_cut_off from digicam_configure message.
Returns
Main engine cut-off time before camera trigger in seconds/10 (0 means no cut-off)
Definition at line 401 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_exposure_type (const mavlink_message_t * msg) inline static
Get field exposure_type from digicam_configure message.
Returns
Exposure type enumeration from 1 to N (0 means ignore)
Definition at line 381 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_extra_param (const mavlink_message_t * msg) inline static
Get field extra_param from digicam_configure message.
Returns
Extra parameters enumeration (0 means ignore)
Definition at line 411 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static float mavlink_msg_digicam_configure_get_extra_value (const mavlink_message_t * msg) inline static
Get field extra_value from digicam_configure message.
Returns
Correspondent value to given extra_param
Definition at line 421 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_iso (const mavlink_message_t * msg) inline static
Get field iso from digicam_configure message.
Returns
ISO enumeration from 1 to N //e.g. 80, 100, 200, Etc (0 means ignore)
Definition at line 371 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_mode (const mavlink_message_t * msg) inline static
Get field mode from digicam_configure message.
Returns
Mode enumeration from 1 to N //P, TV, AV, M, Etc (0 means ignore)
Definition at line 341 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint16_t mavlink_msg_digicam_configure_get_shutter_speed (const mavlink_message_t * msg) inline static
Get field shutter_speed from digicam_configure message.
Returns
Divisor number //e.g. 1000 means 1/1000 (0 means ignore)
Definition at line 351 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from digicam_configure message.
Returns
Component ID
Definition at line 331 of file mavlink_msg_digicam_configure.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_digicam_configure_decode().
static uint8_t mavlink_msg_digicam_configure_get_target_system (const mavlink_message_t * msg) inline static
Send a digicam_configure message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
mode Mode enumeration from 1 to N //P, TV, AV, M, Etc (0 means ignore)
shutter_speed Divisor number //e.g. 1000 means 1/1000 (0 means ignore)
aperture F stop number x 10 //e.g. 28 means 2.8 (0 means ignore)
iso ISO enumeration from 1 to N //e.g. 80, 100, 200, Etc (0 means ignore)
exposure_type Exposure type enumeration from 1 to N (0 means ignore)
command_id Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
engine_cut_off Main engine cut-off time before camera trigger in seconds/10 (0 means no cut-off)
extra_param Extra parameters enumeration (0 means ignore)
extra_value Correspondent value to given extra_param Get field target_system from digicam_configure message
Returns
System ID
Definition at line 321 of file mavlink_msg_digicam_configure.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_digicam_configure_decode().
static uint16_t mavlink_msg_digicam_configure_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t mode, uint16_t shutter_speed, uint8_t aperture, uint8_t iso, uint8_t exposure_type, uint8_t command_id, uint8_t engine_cut_off, uint8_t extra_param, float extra_value) inline static
Pack a digicam_configure message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
mode Mode enumeration from 1 to N //P, TV, AV, M, Etc (0 means ignore)
shutter_speed Divisor number //e.g. 1000 means 1/1000 (0 means ignore)
aperture F stop number x 10 //e.g. 28 means 2.8 (0 means ignore)
iso ISO enumeration from 1 to N //e.g. 80, 100, 200, Etc (0 means ignore)
exposure_type Exposure type enumeration from 1 to N (0 means ignore)
command_id Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
engine_cut_off Main engine cut-off time before camera trigger in seconds/10 (0 means no cut-off)
extra_param Extra parameters enumeration (0 means ignore)
extra_value Correspondent value to given extra_param
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 65 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_encode(), and mavlink_test_digicam_configure().
static uint16_t mavlink_msg_digicam_configure_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t mode, uint16_t shutter_speed, uint8_t aperture, uint8_t iso, uint8_t exposure_type, uint8_t command_id, uint8_t engine_cut_off, uint8_t extra_param, float extra_value) inline static
Pack a digicam_configure message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
mode Mode enumeration from 1 to N //P, TV, AV, M, Etc (0 means ignore)
shutter_speed Divisor number //e.g. 1000 means 1/1000 (0 means ignore)
aperture F stop number x 10 //e.g. 28 means 2.8 (0 means ignore)
iso ISO enumeration from 1 to N //e.g. 80, 100, 200, Etc (0 means ignore)
exposure_type Exposure type enumeration from 1 to N (0 means ignore)
command_id Command Identity (incremental loop: 0 to 255)//A command sent multiple times will be executed or pooled just once
engine_cut_off Main engine cut-off time before camera trigger in seconds/10 (0 means no cut-off)
extra_param Extra parameters enumeration (0 means ignore)
extra_value Correspondent value to given extra_param
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 127 of file mavlink_msg_digicam_configure.h.
Referenced by mavlink_msg_digicam_configure_encode_chan(), and mavlink_test_digicam_configure().