APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_terrain_report.h File Reference
mavlink_msg_terrain_report.h File Reference
Classes
struct __mavlink_terrain_report_t
Macros
#define MAVLINK_MSG_ID_TERRAIN_REPORT 136
#define MAVLINK_MSG_ID_TERRAIN_REPORT_LEN 22
#define MAVLINK_MSG_ID_136_LEN 22
#define MAVLINK_MSG_ID_TERRAIN_REPORT_CRC 1
#define MAVLINK_MSG_ID_136_CRC 1
#define MAVLINK_MESSAGE_INFO_TERRAIN_REPORT
Typedefs
typedef struct __mavlink_terrain_report_t mavlink_terrain_report_t
Functions
static uint16_t mavlink_msg_terrain_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, int32_t lat, int32_t lon, uint16_t spacing, float terrain_height, float current_height, uint16_t pending, uint16_t loaded)
Pack a terrain_report message.
static uint16_t mavlink_msg_terrain_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, int32_t lat, int32_t lon, uint16_t spacing, float terrain_height, float current_height, uint16_t pending, uint16_t loaded)
Pack a terrain_report message on a channel.
static uint16_t mavlink_msg_terrain_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_terrain_report_t *terrain_report)
Encode a terrain_report struct.
static uint16_t mavlink_msg_terrain_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_terrain_report_t *terrain_report)
Encode a terrain_report struct on a channel.
static int32_t mavlink_msg_terrain_report_get_lat (const mavlink_message_t *msg)
Send a terrain_report message.
static int32_t mavlink_msg_terrain_report_get_lon (const mavlink_message_t *msg)
Get field lon from terrain_report message.
static uint16_t mavlink_msg_terrain_report_get_spacing (const mavlink_message_t *msg)
Get field spacing from terrain_report message.
static float mavlink_msg_terrain_report_get_terrain_height (const mavlink_message_t *msg)
Get field terrain_height from terrain_report message.
static float mavlink_msg_terrain_report_get_current_height (const mavlink_message_t *msg)
Get field current_height from terrain_report message.
static uint16_t mavlink_msg_terrain_report_get_pending (const mavlink_message_t *msg)
Get field pending from terrain_report message.
static uint16_t mavlink_msg_terrain_report_get_loaded (const mavlink_message_t *msg)
Get field loaded from terrain_report message.
static void mavlink_msg_terrain_report_decode (const mavlink_message_t *msg, mavlink_terrain_report_t *terrain_report)
Decode a terrain_report message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_TERRAIN_REPORT
Value:
{ \
    "TERRAIN_REPORT", \
    7, \
    {  { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 0, offsetof(mavlink_terrain_report_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_terrain_report_t, lon) }, \
         { "terrain_height", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_terrain_report_t, terrain_height) }, \
         { "current_height", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_terrain_report_t, current_height) }, \
         { "spacing", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_terrain_report_t, spacing) }, \
         { "pending", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_terrain_report_t, pending) }, \
         { "loaded", NULL, MAVLINK_TYPE_UINT16_T, 0, 20, offsetof(mavlink_terrain_report_t, loaded) }, \
         } \
}
Definition at line 24 of file mavlink_msg_terrain_report.h.
#define MAVLINK_MSG_ID_136_CRC 1
Definition at line 20 of file mavlink_msg_terrain_report.h.
#define MAVLINK_MSG_ID_136_LEN 22
Definition at line 17 of file mavlink_msg_terrain_report.h.
#define MAVLINK_MSG_ID_TERRAIN_REPORT 136
Definition at line 3 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_pack(), and mavlink_msg_terrain_report_pack_chan().
#define MAVLINK_MSG_ID_TERRAIN_REPORT_CRC 1
Definition at line 19 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_pack(), and mavlink_msg_terrain_report_pack_chan().
#define MAVLINK_MSG_ID_TERRAIN_REPORT_LEN 22
Definition at line 16 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode(), mavlink_msg_terrain_report_pack(), and mavlink_msg_terrain_report_pack_chan().
Typedef Documentation
typedef struct __mavlink_terrain_report_t mavlink_terrain_report_t
Function Documentation
static void mavlink_msg_terrain_report_decode (const mavlink_message_t * msg, mavlink_terrain_report_t * terrain_report) inline static
Decode a terrain_report message into a struct.
Parameters
msg The message to decode
terrain_report C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_test_terrain_report().
static uint16_t mavlink_msg_terrain_report_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_terrain_report_t * terrain_report) inline static
Encode a terrain_report struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
terrain_report C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_test_terrain_report().
static uint16_t mavlink_msg_terrain_report_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_terrain_report_t * terrain_report) inline static
Encode a terrain_report struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
terrain_report C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_terrain_report.h.
static float mavlink_msg_terrain_report_get_current_height (const mavlink_message_t * msg) inline static
Get field current_height from terrain_report message.
Returns
Current vehicle height above lat/lon terrain height (meters)
Definition at line 309 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static int32_t mavlink_msg_terrain_report_get_lat (const mavlink_message_t * msg) inline static
Send a terrain_report message.
Parameters
chan MAVLink channel to send the message
lat Latitude (degrees *10^7)
lon Longitude (degrees *10^7)
spacing grid spacing (zero if terrain at this location unavailable)
terrain_height Terrain height in meters AMSL
current_height Current vehicle height above lat/lon terrain height (meters)
pending Number of 4x4 terrain blocks waiting to be received or read from disk
loaded Number of 4x4 terrain blocks in memory Get field lat from terrain_report message
Returns
Latitude (degrees *10^7)
Definition at line 269 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static uint16_t mavlink_msg_terrain_report_get_loaded (const mavlink_message_t * msg) inline static
Get field loaded from terrain_report message.
Returns
Number of 4x4 terrain blocks in memory
Definition at line 329 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static int32_t mavlink_msg_terrain_report_get_lon (const mavlink_message_t * msg) inline static
Get field lon from terrain_report message.
Returns
Longitude (degrees *10^7)
Definition at line 279 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static uint16_t mavlink_msg_terrain_report_get_pending (const mavlink_message_t * msg) inline static
Get field pending from terrain_report message.
Returns
Number of 4x4 terrain blocks waiting to be received or read from disk
Definition at line 319 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static uint16_t mavlink_msg_terrain_report_get_spacing (const mavlink_message_t * msg) inline static
Get field spacing from terrain_report message.
Returns
grid spacing (zero if terrain at this location unavailable)
Definition at line 289 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static float mavlink_msg_terrain_report_get_terrain_height (const mavlink_message_t * msg) inline static
Get field terrain_height from terrain_report message.
Returns
Terrain height in meters AMSL
Definition at line 299 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_decode().
static uint16_t mavlink_msg_terrain_report_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, int32_t lat, int32_t lon, uint16_t spacing, float terrain_height, float current_height, uint16_t pending, uint16_t loaded) inline static
Pack a terrain_report message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
lat Latitude (degrees *10^7)
lon Longitude (degrees *10^7)
spacing grid spacing (zero if terrain at this location unavailable)
terrain_height Terrain height in meters AMSL
current_height Current vehicle height above lat/lon terrain height (meters)
pending Number of 4x4 terrain blocks waiting to be received or read from disk
loaded Number of 4x4 terrain blocks in memory
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_encode(), and mavlink_test_terrain_report().
static uint16_t mavlink_msg_terrain_report_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, int32_t lat, int32_t lon, uint16_t spacing, float terrain_height, float current_height, uint16_t pending, uint16_t loaded) inline static
Pack a terrain_report message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
lat Latitude (degrees *10^7)
lon Longitude (degrees *10^7)
spacing grid spacing (zero if terrain at this location unavailable)
terrain_height Terrain height in meters AMSL
current_height Current vehicle height above lat/lon terrain height (meters)
pending Number of 4x4 terrain blocks waiting to be received or read from disk
loaded Number of 4x4 terrain blocks in memory
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_terrain_report.h.
Referenced by mavlink_msg_terrain_report_encode_chan(), and mavlink_test_terrain_report().