APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_command_long.h File Reference
mavlink_msg_command_long.h File Reference
Classes
struct __mavlink_command_long_t
Macros
#define MAVLINK_MSG_ID_COMMAND_LONG 76
#define MAVLINK_MSG_ID_COMMAND_LONG_LEN 33
#define MAVLINK_MSG_ID_76_LEN 33
#define MAVLINK_MSG_ID_COMMAND_LONG_CRC 152
#define MAVLINK_MSG_ID_76_CRC 152
#define MAVLINK_MESSAGE_INFO_COMMAND_LONG
Typedefs
typedef struct __mavlink_command_long_t mavlink_command_long_t
Functions
static uint16_t mavlink_msg_command_long_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t command, uint8_t confirmation, float param1, float param2, float param3, float param4, float param5, float param6, float param7)
Pack a command_long message.
static uint16_t mavlink_msg_command_long_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t command, uint8_t confirmation, float param1, float param2, float param3, float param4, float param5, float param6, float param7)
Pack a command_long message on a channel.
static uint16_t mavlink_msg_command_long_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_command_long_t *command_long)
Encode a command_long struct.
static uint16_t mavlink_msg_command_long_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_command_long_t *command_long)
Encode a command_long struct on a channel.
static uint8_t mavlink_msg_command_long_get_target_system (const mavlink_message_t *msg)
Send a command_long message.
static uint8_t mavlink_msg_command_long_get_target_component (const mavlink_message_t *msg)
Get field target_component from command_long message.
static uint16_t mavlink_msg_command_long_get_command (const mavlink_message_t *msg)
Get field command from command_long message.
static uint8_t mavlink_msg_command_long_get_confirmation (const mavlink_message_t *msg)
Get field confirmation from command_long message.
static float mavlink_msg_command_long_get_param1 (const mavlink_message_t *msg)
Get field param1 from command_long message.
static float mavlink_msg_command_long_get_param2 (const mavlink_message_t *msg)
Get field param2 from command_long message.
static float mavlink_msg_command_long_get_param3 (const mavlink_message_t *msg)
Get field param3 from command_long message.
static float mavlink_msg_command_long_get_param4 (const mavlink_message_t *msg)
Get field param4 from command_long message.
static float mavlink_msg_command_long_get_param5 (const mavlink_message_t *msg)
Get field param5 from command_long message.
static float mavlink_msg_command_long_get_param6 (const mavlink_message_t *msg)
Get field param6 from command_long message.
static float mavlink_msg_command_long_get_param7 (const mavlink_message_t *msg)
Get field param7 from command_long message.
static void mavlink_msg_command_long_decode (const mavlink_message_t *msg, mavlink_command_long_t *command_long)
Decode a command_long message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_COMMAND_LONG
Value:
{ \
    "COMMAND_LONG", \
    11, \
    {  { "param1", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_command_long_t, param1) }, \
         { "param2", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_command_long_t, param2) }, \
         { "param3", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_command_long_t, param3) }, \
         { "param4", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_command_long_t, param4) }, \
         { "param5", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_command_long_t, param5) }, \
         { "param6", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_command_long_t, param6) }, \
         { "param7", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_command_long_t, param7) }, \
         { "command", NULL, MAVLINK_TYPE_UINT16_T, 0, 28, offsetof(mavlink_command_long_t, command) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 30, offsetof(mavlink_command_long_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 31, offsetof(mavlink_command_long_t, target_component) }, \
         { "confirmation", NULL, MAVLINK_TYPE_UINT8_T, 0, 32, offsetof(mavlink_command_long_t, confirmation) }, \
         } \
}
Definition at line 28 of file mavlink_msg_command_long.h.
#define MAVLINK_MSG_ID_76_CRC 152
Definition at line 24 of file mavlink_msg_command_long.h.
#define MAVLINK_MSG_ID_76_LEN 33
Definition at line 21 of file mavlink_msg_command_long.h.
#define MAVLINK_MSG_ID_COMMAND_LONG 76
Definition at line 3 of file mavlink_msg_command_long.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_command_long_pack(), and mavlink_msg_command_long_pack_chan().
#define MAVLINK_MSG_ID_COMMAND_LONG_CRC 152
Definition at line 23 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_pack(), and mavlink_msg_command_long_pack_chan().
#define MAVLINK_MSG_ID_COMMAND_LONG_LEN 33
Definition at line 20 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode(), mavlink_msg_command_long_pack(), mavlink_msg_command_long_pack_chan(), and AP_Mount_SToRM32::send_do_mount_control().
Typedef Documentation
typedef struct __mavlink_command_long_t mavlink_command_long_t
Function Documentation
static void mavlink_msg_command_long_decode (const mavlink_message_t * msg, mavlink_command_long_t * command_long) inline static
Decode a command_long message into a struct.
Parameters
msg The message to decode
command_long C-struct to decode the message contents into
Definition at line 432 of file mavlink_msg_command_long.h.
Referenced by mavlink_test_command_long().
static uint16_t mavlink_msg_command_long_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_command_long_t * command_long) inline static
Encode a command_long struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
command_long C-struct to read the message contents from
Definition at line 179 of file mavlink_msg_command_long.h.
Referenced by AP_Camera::configure(), AP_Camera::control(), mavlink_test_command_long(), and AP_Camera::trigger_pic().
static uint16_t mavlink_msg_command_long_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_command_long_t * command_long) inline static
Encode a command_long struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
command_long C-struct to read the message contents from
Definition at line 193 of file mavlink_msg_command_long.h.
static uint16_t mavlink_msg_command_long_get_command (const mavlink_message_t * msg) inline static
Get field command from command_long message.
Returns
Command ID, as defined by MAV_CMD enum.
Definition at line 341 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static uint8_t mavlink_msg_command_long_get_confirmation (const mavlink_message_t * msg) inline static
Get field confirmation from command_long message.
Returns
0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
Definition at line 351 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param1 (const mavlink_message_t * msg) inline static
Get field param1 from command_long message.
Returns
Parameter 1, as defined by MAV_CMD enum.
Definition at line 361 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param2 (const mavlink_message_t * msg) inline static
Get field param2 from command_long message.
Returns
Parameter 2, as defined by MAV_CMD enum.
Definition at line 371 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param3 (const mavlink_message_t * msg) inline static
Get field param3 from command_long message.
Returns
Parameter 3, as defined by MAV_CMD enum.
Definition at line 381 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param4 (const mavlink_message_t * msg) inline static
Get field param4 from command_long message.
Returns
Parameter 4, as defined by MAV_CMD enum.
Definition at line 391 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param5 (const mavlink_message_t * msg) inline static
Get field param5 from command_long message.
Returns
Parameter 5, as defined by MAV_CMD enum.
Definition at line 401 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param6 (const mavlink_message_t * msg) inline static
Get field param6 from command_long message.
Returns
Parameter 6, as defined by MAV_CMD enum.
Definition at line 411 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static float mavlink_msg_command_long_get_param7 (const mavlink_message_t * msg) inline static
Get field param7 from command_long message.
Returns
Parameter 7, as defined by MAV_CMD enum.
Definition at line 421 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_decode().
static uint8_t mavlink_msg_command_long_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from command_long message.
Returns
Component which should execute the command, 0 for all components
Definition at line 331 of file mavlink_msg_command_long.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_command_long_decode().
static uint8_t mavlink_msg_command_long_get_target_system (const mavlink_message_t * msg) inline static
Send a command_long message.
Parameters
chan MAVLink channel to send the message
target_system System which should execute the command
target_component Component which should execute the command, 0 for all components
command Command ID, as defined by MAV_CMD enum.
confirmation 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
param1 Parameter 1, as defined by MAV_CMD enum.
param2 Parameter 2, as defined by MAV_CMD enum.
param3 Parameter 3, as defined by MAV_CMD enum.
param4 Parameter 4, as defined by MAV_CMD enum.
param5 Parameter 5, as defined by MAV_CMD enum.
param6 Parameter 6, as defined by MAV_CMD enum.
param7 Parameter 7, as defined by MAV_CMD enum. Get field target_system from command_long message
Returns
System which should execute the command
Definition at line 321 of file mavlink_msg_command_long.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_command_long_decode().
static uint16_t mavlink_msg_command_long_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t command, uint8_t confirmation, float param1, float param2, float param3, float param4, float param5, float param6, float param7) inline static
Pack a command_long message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System which should execute the command
target_component Component which should execute the command, 0 for all components
command Command ID, as defined by MAV_CMD enum.
confirmation 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
param1 Parameter 1, as defined by MAV_CMD enum.
param2 Parameter 2, as defined by MAV_CMD enum.
param3 Parameter 3, as defined by MAV_CMD enum.
param4 Parameter 4, as defined by MAV_CMD enum.
param5 Parameter 5, as defined by MAV_CMD enum.
param6 Parameter 6, as defined by MAV_CMD enum.
param7 Parameter 7, as defined by MAV_CMD enum.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 65 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_encode(), and mavlink_test_command_long().
static uint16_t mavlink_msg_command_long_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t command, uint8_t confirmation, float param1, float param2, float param3, float param4, float param5, float param6, float param7) inline static
Pack a command_long message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System which should execute the command
target_component Component which should execute the command, 0 for all components
command Command ID, as defined by MAV_CMD enum.
confirmation 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
param1 Parameter 1, as defined by MAV_CMD enum.
param2 Parameter 2, as defined by MAV_CMD enum.
param3 Parameter 3, as defined by MAV_CMD enum.
param4 Parameter 4, as defined by MAV_CMD enum.
param5 Parameter 5, as defined by MAV_CMD enum.
param6 Parameter 6, as defined by MAV_CMD enum.
param7 Parameter 7, as defined by MAV_CMD enum.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 127 of file mavlink_msg_command_long.h.
Referenced by mavlink_msg_command_long_encode_chan(), and mavlink_test_command_long().