APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_battery_status.h File Reference
mavlink_msg_battery_status.h File Reference
Classes
struct __mavlink_battery_status_t
Macros
#define MAVLINK_MSG_ID_BATTERY_STATUS 147
#define MAVLINK_MSG_ID_BATTERY_STATUS_LEN 36
#define MAVLINK_MSG_ID_147_LEN 36
#define MAVLINK_MSG_ID_BATTERY_STATUS_CRC 154
#define MAVLINK_MSG_ID_147_CRC 154
#define MAVLINK_MSG_BATTERY_STATUS_FIELD_VOLTAGES_LEN 10
#define MAVLINK_MESSAGE_INFO_BATTERY_STATUS
Typedefs
typedef struct __mavlink_battery_status_t mavlink_battery_status_t
Functions
static uint16_t mavlink_msg_battery_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t id, uint8_t battery_function, uint8_t type, int16_t temperature, const uint16_t *voltages, int16_t current_battery, int32_t current_consumed, int32_t energy_consumed, int8_t battery_remaining)
Pack a battery_status message.
static uint16_t mavlink_msg_battery_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t id, uint8_t battery_function, uint8_t type, int16_t temperature, const uint16_t *voltages, int16_t current_battery, int32_t current_consumed, int32_t energy_consumed, int8_t battery_remaining)
Pack a battery_status message on a channel.
static uint16_t mavlink_msg_battery_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_battery_status_t *battery_status)
Encode a battery_status struct.
static uint16_t mavlink_msg_battery_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_battery_status_t *battery_status)
Encode a battery_status struct on a channel.
static uint8_t mavlink_msg_battery_status_get_id (const mavlink_message_t *msg)
Send a battery_status message.
static uint8_t mavlink_msg_battery_status_get_battery_function (const mavlink_message_t *msg)
Get field battery_function from battery_status message.
static uint8_t mavlink_msg_battery_status_get_type (const mavlink_message_t *msg)
Get field type from battery_status message.
static int16_t mavlink_msg_battery_status_get_temperature (const mavlink_message_t *msg)
Get field temperature from battery_status message.
static uint16_t mavlink_msg_battery_status_get_voltages (const mavlink_message_t *msg, uint16_t *voltages)
Get field voltages from battery_status message.
static int16_t mavlink_msg_battery_status_get_current_battery (const mavlink_message_t *msg)
Get field current_battery from battery_status message.
static int32_t mavlink_msg_battery_status_get_current_consumed (const mavlink_message_t *msg)
Get field current_consumed from battery_status message.
static int32_t mavlink_msg_battery_status_get_energy_consumed (const mavlink_message_t *msg)
Get field energy_consumed from battery_status message.
static int8_t mavlink_msg_battery_status_get_battery_remaining (const mavlink_message_t *msg)
Get field battery_remaining from battery_status message.
static void mavlink_msg_battery_status_decode (const mavlink_message_t *msg, mavlink_battery_status_t *battery_status)
Decode a battery_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_BATTERY_STATUS
Value:
{ \
    "BATTERY_STATUS", \
    9, \
    {  { "current_consumed", NULL, MAVLINK_TYPE_INT32_T, 0, 0, offsetof(mavlink_battery_status_t, current_consumed) }, \
         { "energy_consumed", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_battery_status_t, energy_consumed) }, \
         { "temperature", NULL, MAVLINK_TYPE_INT16_T, 0, 8, offsetof(mavlink_battery_status_t, temperature) }, \
         { "voltages", NULL, MAVLINK_TYPE_UINT16_T, 10, 10, offsetof(mavlink_battery_status_t, voltages) }, \
         { "current_battery", NULL, MAVLINK_TYPE_INT16_T, 0, 30, offsetof(mavlink_battery_status_t, current_battery) }, \
         { "id", NULL, MAVLINK_TYPE_UINT8_T, 0, 32, offsetof(mavlink_battery_status_t, id) }, \
         { "battery_function", NULL, MAVLINK_TYPE_UINT8_T, 0, 33, offsetof(mavlink_battery_status_t, battery_function) }, \
         { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 34, offsetof(mavlink_battery_status_t, type) }, \
         { "battery_remaining", NULL, MAVLINK_TYPE_INT8_T, 0, 35, offsetof(mavlink_battery_status_t, battery_remaining) }, \
         } \
}
Definition at line 26 of file mavlink_msg_battery_status.h.
#define MAVLINK_MSG_BATTERY_STATUS_FIELD_VOLTAGES_LEN 10
Definition at line 24 of file mavlink_msg_battery_status.h.
#define MAVLINK_MSG_ID_147_CRC 154
Definition at line 22 of file mavlink_msg_battery_status.h.
#define MAVLINK_MSG_ID_147_LEN 36
Definition at line 19 of file mavlink_msg_battery_status.h.
#define MAVLINK_MSG_ID_BATTERY_STATUS 147
Definition at line 3 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_pack(), and mavlink_msg_battery_status_pack_chan().
#define MAVLINK_MSG_ID_BATTERY_STATUS_CRC 154
Definition at line 21 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_pack(), and mavlink_msg_battery_status_pack_chan().
#define MAVLINK_MSG_ID_BATTERY_STATUS_LEN 36
Definition at line 18 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode(), mavlink_msg_battery_status_pack(), and mavlink_msg_battery_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_battery_status_t mavlink_battery_status_t
Function Documentation
static void mavlink_msg_battery_status_decode (const mavlink_message_t * msg, mavlink_battery_status_t * battery_status) inline static
Decode a battery_status message into a struct.
Parameters
msg The message to decode
battery_status C-struct to decode the message contents into
Definition at line 378 of file mavlink_msg_battery_status.h.
Referenced by mavlink_test_battery_status().
static uint16_t mavlink_msg_battery_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_battery_status_t * battery_status) inline static
Encode a battery_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
battery_status C-struct to read the message contents from
Definition at line 159 of file mavlink_msg_battery_status.h.
Referenced by mavlink_test_battery_status().
static uint16_t mavlink_msg_battery_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_battery_status_t * battery_status) inline static
Encode a battery_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
battery_status C-struct to read the message contents from
Definition at line 173 of file mavlink_msg_battery_status.h.
static uint8_t mavlink_msg_battery_status_get_battery_function (const mavlink_message_t * msg) inline static
Get field battery_function from battery_status message.
Returns
Function of the battery
Definition at line 297 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static int8_t mavlink_msg_battery_status_get_battery_remaining (const mavlink_message_t * msg) inline static
Get field battery_remaining from battery_status message.
Returns
Remaining battery energy: (0%: 0, 100%: 100), -1: autopilot does not estimate the remaining battery
Definition at line 367 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static int16_t mavlink_msg_battery_status_get_current_battery (const mavlink_message_t * msg) inline static
Get field current_battery from battery_status message.
Returns
Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
Definition at line 337 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static int32_t mavlink_msg_battery_status_get_current_consumed (const mavlink_message_t * msg) inline static
Get field current_consumed from battery_status message.
Returns
Consumed charge, in milliampere hours (1 = 1 mAh), -1: autopilot does not provide mAh consumption estimate
Definition at line 347 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static int32_t mavlink_msg_battery_status_get_energy_consumed (const mavlink_message_t * msg) inline static
Get field energy_consumed from battery_status message.
Returns
Consumed energy, in 100*Joules (intergrated U*I*dt) (1 = 100 Joule), -1: autopilot does not provide energy consumption estimate
Definition at line 357 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static uint8_t mavlink_msg_battery_status_get_id (const mavlink_message_t * msg) inline static
Send a battery_status message.
Parameters
chan MAVLink channel to send the message
id Battery ID
battery_function Function of the battery
type Type (chemistry) of the battery
temperature Temperature of the battery in centi-degrees celsius. INT16_MAX for unknown temperature.
voltages Battery voltage of cells, in millivolts (1 = 1 millivolt)
current_battery Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
current_consumed Consumed charge, in milliampere hours (1 = 1 mAh), -1: autopilot does not provide mAh consumption estimate
energy_consumed Consumed energy, in 100*Joules (intergrated U*I*dt) (1 = 100 Joule), -1: autopilot does not provide energy consumption estimate
battery_remaining Remaining battery energy: (0%: 0, 100%: 100), -1: autopilot does not estimate the remaining battery Get field id from battery_status message
Returns
Battery ID
Definition at line 287 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static int16_t mavlink_msg_battery_status_get_temperature (const mavlink_message_t * msg) inline static
Get field temperature from battery_status message.
Returns
Temperature of the battery in centi-degrees celsius. INT16_MAX for unknown temperature.
Definition at line 317 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static uint8_t mavlink_msg_battery_status_get_type (const mavlink_message_t * msg) inline static
Get field type from battery_status message.
Returns
Type (chemistry) of the battery
Definition at line 307 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static uint16_t mavlink_msg_battery_status_get_voltages (const mavlink_message_t * msg, uint16_t * voltages) inline static
Get field voltages from battery_status message.
Returns
Battery voltage of cells, in millivolts (1 = 1 millivolt)
Definition at line 327 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_decode().
static uint16_t mavlink_msg_battery_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t id, uint8_t battery_function, uint8_t type, int16_t temperature, const uint16_t * voltages, int16_t current_battery, int32_t current_consumed, int32_t energy_consumed, int8_t battery_remaining) inline static
Pack a battery_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
id Battery ID
battery_function Function of the battery
type Type (chemistry) of the battery
temperature Temperature of the battery in centi-degrees celsius. INT16_MAX for unknown temperature.
voltages Battery voltage of cells, in millivolts (1 = 1 millivolt)
current_battery Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
current_consumed Consumed charge, in milliampere hours (1 = 1 mAh), -1: autopilot does not provide mAh consumption estimate
energy_consumed Consumed energy, in 100*Joules (intergrated U*I*dt) (1 = 100 Joule), -1: autopilot does not provide energy consumption estimate
battery_remaining Remaining battery energy: (0%: 0, 100%: 100), -1: autopilot does not estimate the remaining battery
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 59 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_encode(), and mavlink_test_battery_status().
static uint16_t mavlink_msg_battery_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t id, uint8_t battery_function, uint8_t type, int16_t temperature, const uint16_t * voltages, int16_t current_battery, int32_t current_consumed, int32_t energy_consumed, int8_t battery_remaining) inline static
Pack a battery_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
id Battery ID
battery_function Function of the battery
type Type (chemistry) of the battery
temperature Temperature of the battery in centi-degrees celsius. INT16_MAX for unknown temperature.
voltages Battery voltage of cells, in millivolts (1 = 1 millivolt)
current_battery Battery current, in 10*milliamperes (1 = 10 milliampere), -1: autopilot does not measure the current
current_consumed Consumed charge, in milliampere hours (1 = 1 mAh), -1: autopilot does not provide mAh consumption estimate
energy_consumed Consumed energy, in 100*Joules (intergrated U*I*dt) (1 = 100 Joule), -1: autopilot does not provide energy consumption estimate
battery_remaining Remaining battery energy: (0%: 0, 100%: 100), -1: autopilot does not estimate the remaining battery
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 113 of file mavlink_msg_battery_status.h.
Referenced by mavlink_msg_battery_status_encode_chan(), and mavlink_test_battery_status().