APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_servo_output_raw.h File Reference
mavlink_msg_servo_output_raw.h File Reference
Classes
struct __mavlink_servo_output_raw_t
Macros
#define MAVLINK_MSG_ID_SERVO_OUTPUT_RAW 36
#define MAVLINK_MSG_ID_SERVO_OUTPUT_RAW_LEN 21
#define MAVLINK_MSG_ID_36_LEN 21
#define MAVLINK_MSG_ID_SERVO_OUTPUT_RAW_CRC 222
#define MAVLINK_MSG_ID_36_CRC 222
#define MAVLINK_MESSAGE_INFO_SERVO_OUTPUT_RAW
Typedefs
typedef struct __mavlink_servo_output_raw_t mavlink_servo_output_raw_t
Functions
static uint16_t mavlink_msg_servo_output_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_usec, uint8_t port, uint16_t servo1_raw, uint16_t servo2_raw, uint16_t servo3_raw, uint16_t servo4_raw, uint16_t servo5_raw, uint16_t servo6_raw, uint16_t servo7_raw, uint16_t servo8_raw)
Pack a servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_usec, uint8_t port, uint16_t servo1_raw, uint16_t servo2_raw, uint16_t servo3_raw, uint16_t servo4_raw, uint16_t servo5_raw, uint16_t servo6_raw, uint16_t servo7_raw, uint16_t servo8_raw)
Pack a servo_output_raw message on a channel.
static uint16_t mavlink_msg_servo_output_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_servo_output_raw_t *servo_output_raw)
Encode a servo_output_raw struct.
static uint16_t mavlink_msg_servo_output_raw_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_servo_output_raw_t *servo_output_raw)
Encode a servo_output_raw struct on a channel.
static uint32_t mavlink_msg_servo_output_raw_get_time_usec (const mavlink_message_t *msg)
Send a servo_output_raw message.
static uint8_t mavlink_msg_servo_output_raw_get_port (const mavlink_message_t *msg)
Get field port from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo1_raw (const mavlink_message_t *msg)
Get field servo1_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo2_raw (const mavlink_message_t *msg)
Get field servo2_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo3_raw (const mavlink_message_t *msg)
Get field servo3_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo4_raw (const mavlink_message_t *msg)
Get field servo4_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo5_raw (const mavlink_message_t *msg)
Get field servo5_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo6_raw (const mavlink_message_t *msg)
Get field servo6_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo7_raw (const mavlink_message_t *msg)
Get field servo7_raw from servo_output_raw message.
static uint16_t mavlink_msg_servo_output_raw_get_servo8_raw (const mavlink_message_t *msg)
Get field servo8_raw from servo_output_raw message.
static void mavlink_msg_servo_output_raw_decode (const mavlink_message_t *msg, mavlink_servo_output_raw_t *servo_output_raw)
Decode a servo_output_raw message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SERVO_OUTPUT_RAW
Value:
{ \
    "SERVO_OUTPUT_RAW", \
    10, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_servo_output_raw_t, time_usec) }, \
         { "servo1_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_servo_output_raw_t, servo1_raw) }, \
         { "servo2_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_servo_output_raw_t, servo2_raw) }, \
         { "servo3_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_servo_output_raw_t, servo3_raw) }, \
         { "servo4_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_servo_output_raw_t, servo4_raw) }, \
         { "servo5_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_servo_output_raw_t, servo5_raw) }, \
         { "servo6_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 14, offsetof(mavlink_servo_output_raw_t, servo6_raw) }, \
         { "servo7_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_servo_output_raw_t, servo7_raw) }, \
         { "servo8_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_servo_output_raw_t, servo8_raw) }, \
         { "port", NULL, MAVLINK_TYPE_UINT8_T, 0, 20, offsetof(mavlink_servo_output_raw_t, port) }, \
         } \
}
Definition at line 27 of file mavlink_msg_servo_output_raw.h.
#define MAVLINK_MSG_ID_36_CRC 222
Definition at line 23 of file mavlink_msg_servo_output_raw.h.
#define MAVLINK_MSG_ID_36_LEN 21
Definition at line 20 of file mavlink_msg_servo_output_raw.h.
#define MAVLINK_MSG_ID_SERVO_OUTPUT_RAW 36
Definition at line 3 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_pack(), and mavlink_msg_servo_output_raw_pack_chan().
#define MAVLINK_MSG_ID_SERVO_OUTPUT_RAW_CRC 222
Definition at line 22 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_pack(), and mavlink_msg_servo_output_raw_pack_chan().
#define MAVLINK_MSG_ID_SERVO_OUTPUT_RAW_LEN 21
Definition at line 19 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode(), mavlink_msg_servo_output_raw_pack(), and mavlink_msg_servo_output_raw_pack_chan().
Typedef Documentation
typedef struct __mavlink_servo_output_raw_t mavlink_servo_output_raw_t
Function Documentation
static void mavlink_msg_servo_output_raw_decode (const mavlink_message_t * msg, mavlink_servo_output_raw_t * servo_output_raw) inline static
Decode a servo_output_raw message into a struct.
Parameters
msg The message to decode
servo_output_raw C-struct to decode the message contents into
Definition at line 409 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_test_servo_output_raw().
static uint16_t mavlink_msg_servo_output_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_servo_output_raw_t * servo_output_raw) inline static
Encode a servo_output_raw struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
servo_output_raw C-struct to read the message contents from
Definition at line 171 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_test_servo_output_raw().
static uint16_t mavlink_msg_servo_output_raw_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_servo_output_raw_t * servo_output_raw) inline static
Encode a servo_output_raw struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
servo_output_raw C-struct to read the message contents from
Definition at line 185 of file mavlink_msg_servo_output_raw.h.
static uint8_t mavlink_msg_servo_output_raw_get_port (const mavlink_message_t * msg) inline static
Get field port from servo_output_raw message.
Returns
Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows to encode more than 8 servos.
Definition at line 318 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo1_raw (const mavlink_message_t * msg) inline static
Get field servo1_raw from servo_output_raw message.
Returns
Servo output 1 value, in microseconds
Definition at line 328 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo2_raw (const mavlink_message_t * msg) inline static
Get field servo2_raw from servo_output_raw message.
Returns
Servo output 2 value, in microseconds
Definition at line 338 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo3_raw (const mavlink_message_t * msg) inline static
Get field servo3_raw from servo_output_raw message.
Returns
Servo output 3 value, in microseconds
Definition at line 348 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo4_raw (const mavlink_message_t * msg) inline static
Get field servo4_raw from servo_output_raw message.
Returns
Servo output 4 value, in microseconds
Definition at line 358 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo5_raw (const mavlink_message_t * msg) inline static
Get field servo5_raw from servo_output_raw message.
Returns
Servo output 5 value, in microseconds
Definition at line 368 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo6_raw (const mavlink_message_t * msg) inline static
Get field servo6_raw from servo_output_raw message.
Returns
Servo output 6 value, in microseconds
Definition at line 378 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo7_raw (const mavlink_message_t * msg) inline static
Get field servo7_raw from servo_output_raw message.
Returns
Servo output 7 value, in microseconds
Definition at line 388 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_get_servo8_raw (const mavlink_message_t * msg) inline static
Get field servo8_raw from servo_output_raw message.
Returns
Servo output 8 value, in microseconds
Definition at line 398 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint32_t mavlink_msg_servo_output_raw_get_time_usec (const mavlink_message_t * msg) inline static
Send a servo_output_raw message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since system boot)
port Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows to encode more than 8 servos.
servo1_raw Servo output 1 value, in microseconds
servo2_raw Servo output 2 value, in microseconds
servo3_raw Servo output 3 value, in microseconds
servo4_raw Servo output 4 value, in microseconds
servo5_raw Servo output 5 value, in microseconds
servo6_raw Servo output 6 value, in microseconds
servo7_raw Servo output 7 value, in microseconds
servo8_raw Servo output 8 value, in microseconds Get field time_usec from servo_output_raw message
Returns
Timestamp (microseconds since system boot)
Definition at line 308 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_decode().
static uint16_t mavlink_msg_servo_output_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_usec, uint8_t port, uint16_t servo1_raw, uint16_t servo2_raw, uint16_t servo3_raw, uint16_t servo4_raw, uint16_t servo5_raw, uint16_t servo6_raw, uint16_t servo7_raw, uint16_t servo8_raw) inline static
Pack a servo_output_raw message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since system boot)
port Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows to encode more than 8 servos.
servo1_raw Servo output 1 value, in microseconds
servo2_raw Servo output 2 value, in microseconds
servo3_raw Servo output 3 value, in microseconds
servo4_raw Servo output 4 value, in microseconds
servo5_raw Servo output 5 value, in microseconds
servo6_raw Servo output 6 value, in microseconds
servo7_raw Servo output 7 value, in microseconds
servo8_raw Servo output 8 value, in microseconds
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_encode(), and mavlink_test_servo_output_raw().
static uint16_t mavlink_msg_servo_output_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_usec, uint8_t port, uint16_t servo1_raw, uint16_t servo2_raw, uint16_t servo3_raw, uint16_t servo4_raw, uint16_t servo5_raw, uint16_t servo6_raw, uint16_t servo7_raw, uint16_t servo8_raw) inline static
Pack a servo_output_raw message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since system boot)
port Servo output port (set of 8 outputs = 1 port). Most MAVs will just use one, but this allows to encode more than 8 servos.
servo1_raw Servo output 1 value, in microseconds
servo2_raw Servo output 2 value, in microseconds
servo3_raw Servo output 3 value, in microseconds
servo4_raw Servo output 4 value, in microseconds
servo5_raw Servo output 5 value, in microseconds
servo6_raw Servo output 6 value, in microseconds
servo7_raw Servo output 7 value, in microseconds
servo8_raw Servo output 8 value, in microseconds
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 121 of file mavlink_msg_servo_output_raw.h.
Referenced by mavlink_msg_servo_output_raw_encode_chan(), and mavlink_test_servo_output_raw().