APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_data96.h File Reference
mavlink_msg_data96.h File Reference
Classes
struct __mavlink_data96_t
Macros
#define MAVLINK_MSG_ID_DATA96 172
#define MAVLINK_MSG_ID_DATA96_LEN 98
#define MAVLINK_MSG_ID_172_LEN 98
#define MAVLINK_MSG_ID_DATA96_CRC 22
#define MAVLINK_MSG_ID_172_CRC 22
#define MAVLINK_MSG_DATA96_FIELD_DATA_LEN 96
#define MAVLINK_MESSAGE_INFO_DATA96
Typedefs
typedef struct __mavlink_data96_t mavlink_data96_t
Functions
static uint16_t mavlink_msg_data96_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t type, uint8_t len, const uint8_t *data)
Pack a data96 message.
static uint16_t mavlink_msg_data96_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t type, uint8_t len, const uint8_t *data)
Pack a data96 message on a channel.
static uint16_t mavlink_msg_data96_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_data96_t *data96)
Encode a data96 struct.
static uint16_t mavlink_msg_data96_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_data96_t *data96)
Encode a data96 struct on a channel.
static uint8_t mavlink_msg_data96_get_type (const mavlink_message_t *msg)
Send a data96 message.
static uint8_t mavlink_msg_data96_get_len (const mavlink_message_t *msg)
Get field len from data96 message.
static uint16_t mavlink_msg_data96_get_data (const mavlink_message_t *msg, uint8_t *data)
Get field data from data96 message.
static void mavlink_msg_data96_decode (const mavlink_message_t *msg, mavlink_data96_t *data96)
Decode a data96 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DATA96
Value:
{ \
    "DATA96", \
    3, \
    {  { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_data96_t, type) }, \
         { "len", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_data96_t, len) }, \
         { "data", NULL, MAVLINK_TYPE_UINT8_T, 96, 2, offsetof(mavlink_data96_t, data) }, \
         } \
}
Definition at line 20 of file mavlink_msg_data96.h.
#define MAVLINK_MSG_DATA96_FIELD_DATA_LEN 96
Definition at line 18 of file mavlink_msg_data96.h.
#define MAVLINK_MSG_ID_172_CRC 22
Definition at line 16 of file mavlink_msg_data96.h.
#define MAVLINK_MSG_ID_172_LEN 98
Definition at line 13 of file mavlink_msg_data96.h.
#define MAVLINK_MSG_ID_DATA96 172
Definition at line 3 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_pack(), and mavlink_msg_data96_pack_chan().
#define MAVLINK_MSG_ID_DATA96_CRC 22
Definition at line 15 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_pack(), and mavlink_msg_data96_pack_chan().
#define MAVLINK_MSG_ID_DATA96_LEN 98
Definition at line 12 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_decode(), mavlink_msg_data96_pack(), and mavlink_msg_data96_pack_chan().
Typedef Documentation
typedef struct __mavlink_data96_t mavlink_data96_t
Function Documentation
static void mavlink_msg_data96_decode (const mavlink_message_t * msg, mavlink_data96_t * data96) inline static
Decode a data96 message into a struct.
Parameters
msg The message to decode
data96 C-struct to decode the message contents into
Definition at line 240 of file mavlink_msg_data96.h.
Referenced by mavlink_test_data96().
static uint16_t mavlink_msg_data96_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_data96_t * data96) inline static
Encode a data96 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
data96 C-struct to read the message contents from
Definition at line 111 of file mavlink_msg_data96.h.
Referenced by mavlink_test_data96().
static uint16_t mavlink_msg_data96_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_data96_t * data96) inline static
Encode a data96 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
data96 C-struct to read the message contents from
Definition at line 125 of file mavlink_msg_data96.h.
static uint16_t mavlink_msg_data96_get_data (const mavlink_message_t * msg, uint8_t * data) inline static
Get field data from data96 message.
Returns
raw data
Definition at line 229 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_decode().
static uint8_t mavlink_msg_data96_get_len (const mavlink_message_t * msg) inline static
Get field len from data96 message.
Returns
data length
Definition at line 219 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_decode().
static uint8_t mavlink_msg_data96_get_type (const mavlink_message_t * msg) inline static
Send a data96 message.
Parameters
chan MAVLink channel to send the message
type data type
len data length
data raw data Get field type from data96 message
Returns
data type
Definition at line 209 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_decode().
static uint16_t mavlink_msg_data96_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t type, uint8_t len, const uint8_t * data) inline static
Pack a data96 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
type data type
len data length
data raw data
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_encode(), and mavlink_test_data96().
static uint16_t mavlink_msg_data96_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t type, uint8_t len, const uint8_t * data) inline static
Pack a data96 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
type data type
len data length
data raw data
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 77 of file mavlink_msg_data96.h.
Referenced by mavlink_msg_data96_encode_chan(), and mavlink_test_data96().