APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_scaled_pressure2.h File Reference
mavlink_msg_scaled_pressure2.h File Reference
Classes
struct __mavlink_scaled_pressure2_t
Macros
#define MAVLINK_MSG_ID_SCALED_PRESSURE2 137
#define MAVLINK_MSG_ID_SCALED_PRESSURE2_LEN 14
#define MAVLINK_MSG_ID_137_LEN 14
#define MAVLINK_MSG_ID_SCALED_PRESSURE2_CRC 195
#define MAVLINK_MSG_ID_137_CRC 195
#define MAVLINK_MESSAGE_INFO_SCALED_PRESSURE2
Typedefs
typedef struct __mavlink_scaled_pressure2_t mavlink_scaled_pressure2_t
Functions
static uint16_t mavlink_msg_scaled_pressure2_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature)
Pack a scaled_pressure2 message.
static uint16_t mavlink_msg_scaled_pressure2_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature)
Pack a scaled_pressure2 message on a channel.
static uint16_t mavlink_msg_scaled_pressure2_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_scaled_pressure2_t *scaled_pressure2)
Encode a scaled_pressure2 struct.
static uint16_t mavlink_msg_scaled_pressure2_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_scaled_pressure2_t *scaled_pressure2)
Encode a scaled_pressure2 struct on a channel.
static uint32_t mavlink_msg_scaled_pressure2_get_time_boot_ms (const mavlink_message_t *msg)
Send a scaled_pressure2 message.
static float mavlink_msg_scaled_pressure2_get_press_abs (const mavlink_message_t *msg)
Get field press_abs from scaled_pressure2 message.
static float mavlink_msg_scaled_pressure2_get_press_diff (const mavlink_message_t *msg)
Get field press_diff from scaled_pressure2 message.
static int16_t mavlink_msg_scaled_pressure2_get_temperature (const mavlink_message_t *msg)
Get field temperature from scaled_pressure2 message.
static void mavlink_msg_scaled_pressure2_decode (const mavlink_message_t *msg, mavlink_scaled_pressure2_t *scaled_pressure2)
Decode a scaled_pressure2 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SCALED_PRESSURE2
Value:
{ \
    "SCALED_PRESSURE2", \
    4, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_scaled_pressure2_t, time_boot_ms) }, \
         { "press_abs", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_scaled_pressure2_t, press_abs) }, \
         { "press_diff", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_scaled_pressure2_t, press_diff) }, \
         { "temperature", NULL, MAVLINK_TYPE_INT16_T, 0, 12, offsetof(mavlink_scaled_pressure2_t, temperature) }, \
         } \
}
Definition at line 21 of file mavlink_msg_scaled_pressure2.h.
#define MAVLINK_MSG_ID_137_CRC 195
Definition at line 17 of file mavlink_msg_scaled_pressure2.h.
#define MAVLINK_MSG_ID_137_LEN 14
Definition at line 14 of file mavlink_msg_scaled_pressure2.h.
#define MAVLINK_MSG_ID_SCALED_PRESSURE2 137
Definition at line 3 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_pack(), and mavlink_msg_scaled_pressure2_pack_chan().
#define MAVLINK_MSG_ID_SCALED_PRESSURE2_CRC 195
Definition at line 16 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_pack(), and mavlink_msg_scaled_pressure2_pack_chan().
#define MAVLINK_MSG_ID_SCALED_PRESSURE2_LEN 14
Definition at line 13 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_decode(), mavlink_msg_scaled_pressure2_pack(), and mavlink_msg_scaled_pressure2_pack_chan().
Typedef Documentation
typedef struct __mavlink_scaled_pressure2_t mavlink_scaled_pressure2_t
Function Documentation
static void mavlink_msg_scaled_pressure2_decode (const mavlink_message_t * msg, mavlink_scaled_pressure2_t * scaled_pressure2) inline static
Decode a scaled_pressure2 message into a struct.
Parameters
msg The message to decode
scaled_pressure2 C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_test_scaled_pressure2().
static uint16_t mavlink_msg_scaled_pressure2_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_scaled_pressure2_t * scaled_pressure2) inline static
Encode a scaled_pressure2 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
scaled_pressure2 C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_test_scaled_pressure2().
static uint16_t mavlink_msg_scaled_pressure2_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_scaled_pressure2_t * scaled_pressure2) inline static
Encode a scaled_pressure2 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
scaled_pressure2 C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_scaled_pressure2.h.
static float mavlink_msg_scaled_pressure2_get_press_abs (const mavlink_message_t * msg) inline static
Get field press_abs from scaled_pressure2 message.
Returns
Absolute pressure (hectopascal)
Definition at line 240 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_decode().
static float mavlink_msg_scaled_pressure2_get_press_diff (const mavlink_message_t * msg) inline static
Get field press_diff from scaled_pressure2 message.
Returns
Differential pressure 1 (hectopascal)
Definition at line 250 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_decode().
static int16_t mavlink_msg_scaled_pressure2_get_temperature (const mavlink_message_t * msg) inline static
Get field temperature from scaled_pressure2 message.
Returns
Temperature measurement (0.01 degrees celsius)
Definition at line 260 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_decode().
static uint32_t mavlink_msg_scaled_pressure2_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a scaled_pressure2 message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
press_abs Absolute pressure (hectopascal)
press_diff Differential pressure 1 (hectopascal)
temperature Temperature measurement (0.01 degrees celsius) Get field time_boot_ms from scaled_pressure2 message
Returns
Timestamp (milliseconds since system boot)
Definition at line 230 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_decode().
static uint16_t mavlink_msg_scaled_pressure2_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature) inline static
Pack a scaled_pressure2 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
press_abs Absolute pressure (hectopascal)
press_diff Differential pressure 1 (hectopascal)
temperature Temperature measurement (0.01 degrees celsius)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_encode(), and mavlink_test_scaled_pressure2().
static uint16_t mavlink_msg_scaled_pressure2_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature) inline static
Pack a scaled_pressure2 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
press_abs Absolute pressure (hectopascal)
press_diff Differential pressure 1 (hectopascal)
temperature Temperature measurement (0.01 degrees celsius)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_scaled_pressure2.h.
Referenced by mavlink_msg_scaled_pressure2_encode_chan(), and mavlink_test_scaled_pressure2().