APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_set_mag_offsets.h File Reference
mavlink_msg_set_mag_offsets.h File Reference
Classes
struct __mavlink_set_mag_offsets_t
Macros
#define MAVLINK_MSG_ID_SET_MAG_OFFSETS 151
#define MAVLINK_MSG_ID_SET_MAG_OFFSETS_LEN 8
#define MAVLINK_MSG_ID_151_LEN 8
#define MAVLINK_MSG_ID_SET_MAG_OFFSETS_CRC 219
#define MAVLINK_MSG_ID_151_CRC 219
#define MAVLINK_MESSAGE_INFO_SET_MAG_OFFSETS
Typedefs
typedef struct __mavlink_set_mag_offsets_t mavlink_set_mag_offsets_t
Functions
static uint16_t mavlink_msg_set_mag_offsets_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z)
Pack a set_mag_offsets message.
static uint16_t mavlink_msg_set_mag_offsets_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z)
Pack a set_mag_offsets message on a channel.
static uint16_t mavlink_msg_set_mag_offsets_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_set_mag_offsets_t *set_mag_offsets)
Encode a set_mag_offsets struct.
static uint16_t mavlink_msg_set_mag_offsets_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_set_mag_offsets_t *set_mag_offsets)
Encode a set_mag_offsets struct on a channel.
static uint8_t mavlink_msg_set_mag_offsets_get_target_system (const mavlink_message_t *msg)
Send a set_mag_offsets message.
static uint8_t mavlink_msg_set_mag_offsets_get_target_component (const mavlink_message_t *msg)
Get field target_component from set_mag_offsets message.
static int16_t mavlink_msg_set_mag_offsets_get_mag_ofs_x (const mavlink_message_t *msg)
Get field mag_ofs_x from set_mag_offsets message.
static int16_t mavlink_msg_set_mag_offsets_get_mag_ofs_y (const mavlink_message_t *msg)
Get field mag_ofs_y from set_mag_offsets message.
static int16_t mavlink_msg_set_mag_offsets_get_mag_ofs_z (const mavlink_message_t *msg)
Get field mag_ofs_z from set_mag_offsets message.
static void mavlink_msg_set_mag_offsets_decode (const mavlink_message_t *msg, mavlink_set_mag_offsets_t *set_mag_offsets)
Decode a set_mag_offsets message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SET_MAG_OFFSETS
Value:
{ \
    "SET_MAG_OFFSETS", \
    5, \
    {  { "mag_ofs_x", NULL, MAVLINK_TYPE_INT16_T, 0, 0, offsetof(mavlink_set_mag_offsets_t, mag_ofs_x) }, \
         { "mag_ofs_y", NULL, MAVLINK_TYPE_INT16_T, 0, 2, offsetof(mavlink_set_mag_offsets_t, mag_ofs_y) }, \
         { "mag_ofs_z", NULL, MAVLINK_TYPE_INT16_T, 0, 4, offsetof(mavlink_set_mag_offsets_t, mag_ofs_z) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_set_mag_offsets_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_set_mag_offsets_t, target_component) }, \
         } \
}
Definition at line 22 of file mavlink_msg_set_mag_offsets.h.
#define MAVLINK_MSG_ID_151_CRC 219
Definition at line 18 of file mavlink_msg_set_mag_offsets.h.
#define MAVLINK_MSG_ID_151_LEN 8
Definition at line 15 of file mavlink_msg_set_mag_offsets.h.
#define MAVLINK_MSG_ID_SET_MAG_OFFSETS 151
Definition at line 3 of file mavlink_msg_set_mag_offsets.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_set_mag_offsets_pack(), and mavlink_msg_set_mag_offsets_pack_chan().
#define MAVLINK_MSG_ID_SET_MAG_OFFSETS_CRC 219
Definition at line 17 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_pack(), and mavlink_msg_set_mag_offsets_pack_chan().
#define MAVLINK_MSG_ID_SET_MAG_OFFSETS_LEN 8
Definition at line 14 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_decode(), mavlink_msg_set_mag_offsets_pack(), and mavlink_msg_set_mag_offsets_pack_chan().
Typedef Documentation
typedef struct __mavlink_set_mag_offsets_t mavlink_set_mag_offsets_t
Function Documentation
static void mavlink_msg_set_mag_offsets_decode (const mavlink_message_t * msg, mavlink_set_mag_offsets_t * set_mag_offsets) inline static
Decode a set_mag_offsets message into a struct.
Parameters
msg The message to decode
set_mag_offsets C-struct to decode the message contents into
Definition at line 294 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_test_set_mag_offsets().
static uint16_t mavlink_msg_set_mag_offsets_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_set_mag_offsets_t * set_mag_offsets) inline static
Encode a set_mag_offsets struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
set_mag_offsets C-struct to read the message contents from
Definition at line 131 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_test_set_mag_offsets().
static uint16_t mavlink_msg_set_mag_offsets_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_set_mag_offsets_t * set_mag_offsets) inline static
Encode a set_mag_offsets struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
set_mag_offsets C-struct to read the message contents from
Definition at line 145 of file mavlink_msg_set_mag_offsets.h.
static int16_t mavlink_msg_set_mag_offsets_get_mag_ofs_x (const mavlink_message_t * msg) inline static
Get field mag_ofs_x from set_mag_offsets message.
Returns
magnetometer X offset
Definition at line 263 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_decode().
static int16_t mavlink_msg_set_mag_offsets_get_mag_ofs_y (const mavlink_message_t * msg) inline static
Get field mag_ofs_y from set_mag_offsets message.
Returns
magnetometer Y offset
Definition at line 273 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_decode().
static int16_t mavlink_msg_set_mag_offsets_get_mag_ofs_z (const mavlink_message_t * msg) inline static
Get field mag_ofs_z from set_mag_offsets message.
Returns
magnetometer Z offset
Definition at line 283 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_decode().
static uint8_t mavlink_msg_set_mag_offsets_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from set_mag_offsets message.
Returns
Component ID
Definition at line 253 of file mavlink_msg_set_mag_offsets.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_set_mag_offsets_decode().
static uint8_t mavlink_msg_set_mag_offsets_get_target_system (const mavlink_message_t * msg) inline static
Send a set_mag_offsets message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
mag_ofs_x magnetometer X offset
mag_ofs_y magnetometer Y offset
mag_ofs_z magnetometer Z offset Get field target_system from set_mag_offsets message
Returns
System ID
Definition at line 243 of file mavlink_msg_set_mag_offsets.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_set_mag_offsets_decode().
static uint16_t mavlink_msg_set_mag_offsets_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z) inline static
Pack a set_mag_offsets message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
mag_ofs_x magnetometer X offset
mag_ofs_y magnetometer Y offset
mag_ofs_z magnetometer Z offset
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_encode(), and mavlink_test_set_mag_offsets().
static uint16_t mavlink_msg_set_mag_offsets_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int16_t mag_ofs_x, int16_t mag_ofs_y, int16_t mag_ofs_z) inline static
Pack a set_mag_offsets message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
mag_ofs_x magnetometer X offset
mag_ofs_y magnetometer Y offset
mag_ofs_z magnetometer Z offset
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 91 of file mavlink_msg_set_mag_offsets.h.
Referenced by mavlink_msg_set_mag_offsets_encode_chan(), and mavlink_test_set_mag_offsets().