APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_ahrs3.h File Reference
mavlink_msg_ahrs3.h File Reference
Classes
struct __mavlink_ahrs3_t
Macros
#define MAVLINK_MSG_ID_AHRS3 182
#define MAVLINK_MSG_ID_AHRS3_LEN 40
#define MAVLINK_MSG_ID_182_LEN 40
#define MAVLINK_MSG_ID_AHRS3_CRC 229
#define MAVLINK_MSG_ID_182_CRC 229
#define MAVLINK_MESSAGE_INFO_AHRS3
Typedefs
typedef struct __mavlink_ahrs3_t mavlink_ahrs3_t
Functions
static uint16_t mavlink_msg_ahrs3_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng, float v1, float v2, float v3, float v4)
Pack a ahrs3 message.
static uint16_t mavlink_msg_ahrs3_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng, float v1, float v2, float v3, float v4)
Pack a ahrs3 message on a channel.
static uint16_t mavlink_msg_ahrs3_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_ahrs3_t *ahrs3)
Encode a ahrs3 struct.
static uint16_t mavlink_msg_ahrs3_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_ahrs3_t *ahrs3)
Encode a ahrs3 struct on a channel.
static float mavlink_msg_ahrs3_get_roll (const mavlink_message_t *msg)
Send a ahrs3 message.
static float mavlink_msg_ahrs3_get_pitch (const mavlink_message_t *msg)
Get field pitch from ahrs3 message.
static float mavlink_msg_ahrs3_get_yaw (const mavlink_message_t *msg)
Get field yaw from ahrs3 message.
static float mavlink_msg_ahrs3_get_altitude (const mavlink_message_t *msg)
Get field altitude from ahrs3 message.
static int32_t mavlink_msg_ahrs3_get_lat (const mavlink_message_t *msg)
Get field lat from ahrs3 message.
static int32_t mavlink_msg_ahrs3_get_lng (const mavlink_message_t *msg)
Get field lng from ahrs3 message.
static float mavlink_msg_ahrs3_get_v1 (const mavlink_message_t *msg)
Get field v1 from ahrs3 message.
static float mavlink_msg_ahrs3_get_v2 (const mavlink_message_t *msg)
Get field v2 from ahrs3 message.
static float mavlink_msg_ahrs3_get_v3 (const mavlink_message_t *msg)
Get field v3 from ahrs3 message.
static float mavlink_msg_ahrs3_get_v4 (const mavlink_message_t *msg)
Get field v4 from ahrs3 message.
static void mavlink_msg_ahrs3_decode (const mavlink_message_t *msg, mavlink_ahrs3_t *ahrs3)
Decode a ahrs3 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AHRS3
Value:
{ \
    "AHRS3", \
    10, \
    {  { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_ahrs3_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_ahrs3_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_ahrs3_t, yaw) }, \
         { "altitude", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_ahrs3_t, altitude) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 16, offsetof(mavlink_ahrs3_t, lat) }, \
         { "lng", NULL, MAVLINK_TYPE_INT32_T, 0, 20, offsetof(mavlink_ahrs3_t, lng) }, \
         { "v1", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_ahrs3_t, v1) }, \
         { "v2", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_ahrs3_t, v2) }, \
         { "v3", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_ahrs3_t, v3) }, \
         { "v4", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_ahrs3_t, v4) }, \
         } \
}
Definition at line 27 of file mavlink_msg_ahrs3.h.
#define MAVLINK_MSG_ID_182_CRC 229
Definition at line 23 of file mavlink_msg_ahrs3.h.
#define MAVLINK_MSG_ID_182_LEN 40
Definition at line 20 of file mavlink_msg_ahrs3.h.
#define MAVLINK_MSG_ID_AHRS3 182
Definition at line 3 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_pack(), and mavlink_msg_ahrs3_pack_chan().
#define MAVLINK_MSG_ID_AHRS3_CRC 229
Definition at line 22 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_pack(), and mavlink_msg_ahrs3_pack_chan().
#define MAVLINK_MSG_ID_AHRS3_LEN 40
Definition at line 19 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode(), mavlink_msg_ahrs3_pack(), and mavlink_msg_ahrs3_pack_chan().
Typedef Documentation
typedef struct __mavlink_ahrs3_t mavlink_ahrs3_t
Function Documentation
static void mavlink_msg_ahrs3_decode (const mavlink_message_t * msg, mavlink_ahrs3_t * ahrs3) inline static
Decode a ahrs3 message into a struct.
Parameters
msg The message to decode
ahrs3 C-struct to decode the message contents into
Definition at line 409 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_test_ahrs3().
static uint16_t mavlink_msg_ahrs3_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_ahrs3_t * ahrs3) inline static
Encode a ahrs3 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
ahrs3 C-struct to read the message contents from
Definition at line 171 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_test_ahrs3().
static uint16_t mavlink_msg_ahrs3_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_ahrs3_t * ahrs3) inline static
Encode a ahrs3 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
ahrs3 C-struct to read the message contents from
Definition at line 185 of file mavlink_msg_ahrs3.h.
static float mavlink_msg_ahrs3_get_altitude (const mavlink_message_t * msg) inline static
Get field altitude from ahrs3 message.
Returns
Altitude (MSL)
Definition at line 338 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static int32_t mavlink_msg_ahrs3_get_lat (const mavlink_message_t * msg) inline static
Get field lat from ahrs3 message.
Returns
Latitude in degrees * 1E7
Definition at line 348 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static int32_t mavlink_msg_ahrs3_get_lng (const mavlink_message_t * msg) inline static
Get field lng from ahrs3 message.
Returns
Longitude in degrees * 1E7
Definition at line 358 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from ahrs3 message.
Returns
Pitch angle (rad)
Definition at line 318 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_roll (const mavlink_message_t * msg) inline static
Send a ahrs3 message.
Parameters
chan MAVLink channel to send the message
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
altitude Altitude (MSL)
lat Latitude in degrees * 1E7
lng Longitude in degrees * 1E7
v1 test variable1
v2 test variable2
v3 test variable3
v4 test variable4 Get field roll from ahrs3 message
Returns
Roll angle (rad)
Definition at line 308 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_v1 (const mavlink_message_t * msg) inline static
Get field v1 from ahrs3 message.
Returns
test variable1
Definition at line 368 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_v2 (const mavlink_message_t * msg) inline static
Get field v2 from ahrs3 message.
Returns
test variable2
Definition at line 378 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_v3 (const mavlink_message_t * msg) inline static
Get field v3 from ahrs3 message.
Returns
test variable3
Definition at line 388 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_v4 (const mavlink_message_t * msg) inline static
Get field v4 from ahrs3 message.
Returns
test variable4
Definition at line 398 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static float mavlink_msg_ahrs3_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from ahrs3 message.
Returns
Yaw angle (rad)
Definition at line 328 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_decode().
static uint16_t mavlink_msg_ahrs3_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng, float v1, float v2, float v3, float v4) inline static
Pack a ahrs3 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
altitude Altitude (MSL)
lat Latitude in degrees * 1E7
lng Longitude in degrees * 1E7
v1 test variable1
v2 test variable2
v3 test variable3
v4 test variable4
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_encode(), and mavlink_test_ahrs3().
static uint16_t mavlink_msg_ahrs3_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float roll, float pitch, float yaw, float altitude, int32_t lat, int32_t lng, float v1, float v2, float v3, float v4) inline static
Pack a ahrs3 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
altitude Altitude (MSL)
lat Latitude in degrees * 1E7
lng Longitude in degrees * 1E7
v1 test variable1
v2 test variable2
v3 test variable3
v4 test variable4
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 121 of file mavlink_msg_ahrs3.h.
Referenced by mavlink_msg_ahrs3_encode_chan(), and mavlink_test_ahrs3().