APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_airspeed_autocal.h File Reference
mavlink_msg_airspeed_autocal.h File Reference
Classes
struct __mavlink_airspeed_autocal_t
Macros
#define MAVLINK_MSG_ID_AIRSPEED_AUTOCAL 174
#define MAVLINK_MSG_ID_AIRSPEED_AUTOCAL_LEN 48
#define MAVLINK_MSG_ID_174_LEN 48
#define MAVLINK_MSG_ID_AIRSPEED_AUTOCAL_CRC 167
#define MAVLINK_MSG_ID_174_CRC 167
#define MAVLINK_MESSAGE_INFO_AIRSPEED_AUTOCAL
Typedefs
typedef struct __mavlink_airspeed_autocal_t mavlink_airspeed_autocal_t
Functions
static uint16_t mavlink_msg_airspeed_autocal_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float vx, float vy, float vz, float diff_pressure, float EAS2TAS, float ratio, float state_x, float state_y, float state_z, float Pax, float Pby, float Pcz)
Pack a airspeed_autocal message.
static uint16_t mavlink_msg_airspeed_autocal_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float vx, float vy, float vz, float diff_pressure, float EAS2TAS, float ratio, float state_x, float state_y, float state_z, float Pax, float Pby, float Pcz)
Pack a airspeed_autocal message on a channel.
static uint16_t mavlink_msg_airspeed_autocal_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_airspeed_autocal_t *airspeed_autocal)
Encode a airspeed_autocal struct.
static uint16_t mavlink_msg_airspeed_autocal_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_airspeed_autocal_t *airspeed_autocal)
Encode a airspeed_autocal struct on a channel.
static float mavlink_msg_airspeed_autocal_get_vx (const mavlink_message_t *msg)
Send a airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_vy (const mavlink_message_t *msg)
Get field vy from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_vz (const mavlink_message_t *msg)
Get field vz from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_diff_pressure (const mavlink_message_t *msg)
Get field diff_pressure from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_EAS2TAS (const mavlink_message_t *msg)
Get field EAS2TAS from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_ratio (const mavlink_message_t *msg)
Get field ratio from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_state_x (const mavlink_message_t *msg)
Get field state_x from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_state_y (const mavlink_message_t *msg)
Get field state_y from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_state_z (const mavlink_message_t *msg)
Get field state_z from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_Pax (const mavlink_message_t *msg)
Get field Pax from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_Pby (const mavlink_message_t *msg)
Get field Pby from airspeed_autocal message.
static float mavlink_msg_airspeed_autocal_get_Pcz (const mavlink_message_t *msg)
Get field Pcz from airspeed_autocal message.
static void mavlink_msg_airspeed_autocal_decode (const mavlink_message_t *msg, mavlink_airspeed_autocal_t *airspeed_autocal)
Decode a airspeed_autocal message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AIRSPEED_AUTOCAL
Value:
{ \
    "AIRSPEED_AUTOCAL", \
    12, \
    {  { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_airspeed_autocal_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_airspeed_autocal_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_airspeed_autocal_t, vz) }, \
         { "diff_pressure", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_airspeed_autocal_t, diff_pressure) }, \
         { "EAS2TAS", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_airspeed_autocal_t, EAS2TAS) }, \
         { "ratio", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_airspeed_autocal_t, ratio) }, \
         { "state_x", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_airspeed_autocal_t, state_x) }, \
         { "state_y", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_airspeed_autocal_t, state_y) }, \
         { "state_z", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_airspeed_autocal_t, state_z) }, \
         { "Pax", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_airspeed_autocal_t, Pax) }, \
         { "Pby", NULL, MAVLINK_TYPE_FLOAT, 0, 40, offsetof(mavlink_airspeed_autocal_t, Pby) }, \
         { "Pcz", NULL, MAVLINK_TYPE_FLOAT, 0, 44, offsetof(mavlink_airspeed_autocal_t, Pcz) }, \
         } \
}
Definition at line 29 of file mavlink_msg_airspeed_autocal.h.
#define MAVLINK_MSG_ID_174_CRC 167
Definition at line 25 of file mavlink_msg_airspeed_autocal.h.
#define MAVLINK_MSG_ID_174_LEN 48
Definition at line 22 of file mavlink_msg_airspeed_autocal.h.
#define MAVLINK_MSG_ID_AIRSPEED_AUTOCAL 174
Definition at line 3 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_pack(), and mavlink_msg_airspeed_autocal_pack_chan().
#define MAVLINK_MSG_ID_AIRSPEED_AUTOCAL_CRC 167
Definition at line 24 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_pack(), and mavlink_msg_airspeed_autocal_pack_chan().
#define MAVLINK_MSG_ID_AIRSPEED_AUTOCAL_LEN 48
Definition at line 21 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode(), mavlink_msg_airspeed_autocal_pack(), and mavlink_msg_airspeed_autocal_pack_chan().
Typedef Documentation
typedef struct __mavlink_airspeed_autocal_t mavlink_airspeed_autocal_t
Function Documentation
static void mavlink_msg_airspeed_autocal_decode (const mavlink_message_t * msg, mavlink_airspeed_autocal_t * airspeed_autocal) inline static
Decode a airspeed_autocal message into a struct.
Parameters
msg The message to decode
airspeed_autocal C-struct to decode the message contents into
Definition at line 455 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_test_airspeed_autocal().
static uint16_t mavlink_msg_airspeed_autocal_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_airspeed_autocal_t * airspeed_autocal) inline static
Encode a airspeed_autocal struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
airspeed_autocal C-struct to read the message contents from
Definition at line 187 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_test_airspeed_autocal().
static uint16_t mavlink_msg_airspeed_autocal_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_airspeed_autocal_t * airspeed_autocal) inline static
Encode a airspeed_autocal struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
airspeed_autocal C-struct to read the message contents from
Definition at line 201 of file mavlink_msg_airspeed_autocal.h.
static float mavlink_msg_airspeed_autocal_get_diff_pressure (const mavlink_message_t * msg) inline static
Get field diff_pressure from airspeed_autocal message.
Returns
Differential pressure pascals
Definition at line 364 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_EAS2TAS (const mavlink_message_t * msg) inline static
Get field EAS2TAS from airspeed_autocal message.
Returns
Estimated to true airspeed ratio
Definition at line 374 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_Pax (const mavlink_message_t * msg) inline static
Get field Pax from airspeed_autocal message.
Returns
EKF Pax
Definition at line 424 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_Pby (const mavlink_message_t * msg) inline static
Get field Pby from airspeed_autocal message.
Returns
EKF Pby
Definition at line 434 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_Pcz (const mavlink_message_t * msg) inline static
Get field Pcz from airspeed_autocal message.
Returns
EKF Pcz
Definition at line 444 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_ratio (const mavlink_message_t * msg) inline static
Get field ratio from airspeed_autocal message.
Returns
Airspeed ratio
Definition at line 384 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_state_x (const mavlink_message_t * msg) inline static
Get field state_x from airspeed_autocal message.
Returns
EKF state x
Definition at line 394 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_state_y (const mavlink_message_t * msg) inline static
Get field state_y from airspeed_autocal message.
Returns
EKF state y
Definition at line 404 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_state_z (const mavlink_message_t * msg) inline static
Get field state_z from airspeed_autocal message.
Returns
EKF state z
Definition at line 414 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_vx (const mavlink_message_t * msg) inline static
Send a airspeed_autocal message.
Parameters
chan MAVLink channel to send the message
vx GPS velocity north m/s
vy GPS velocity east m/s
vz GPS velocity down m/s
diff_pressure Differential pressure pascals
EAS2TAS Estimated to true airspeed ratio
ratio Airspeed ratio
state_x EKF state x
state_y EKF state y
state_z EKF state z
Pax EKF Pax
Pby EKF Pby
Pcz EKF Pcz Get field vx from airspeed_autocal message
Returns
GPS velocity north m/s
Definition at line 334 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_vy (const mavlink_message_t * msg) inline static
Get field vy from airspeed_autocal message.
Returns
GPS velocity east m/s
Definition at line 344 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static float mavlink_msg_airspeed_autocal_get_vz (const mavlink_message_t * msg) inline static
Get field vz from airspeed_autocal message.
Returns
GPS velocity down m/s
Definition at line 354 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_decode().
static uint16_t mavlink_msg_airspeed_autocal_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float vx, float vy, float vz, float diff_pressure, float EAS2TAS, float ratio, float state_x, float state_y, float state_z, float Pax, float Pby, float Pcz) inline static
Pack a airspeed_autocal message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
vx GPS velocity north m/s
vy GPS velocity east m/s
vz GPS velocity down m/s
diff_pressure Differential pressure pascals
EAS2TAS Estimated to true airspeed ratio
ratio Airspeed ratio
state_x EKF state x
state_y EKF state y
state_z EKF state z
Pax EKF Pax
Pby EKF Pby
Pcz EKF Pcz
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 68 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_encode(), and mavlink_test_airspeed_autocal().
static uint16_t mavlink_msg_airspeed_autocal_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float vx, float vy, float vz, float diff_pressure, float EAS2TAS, float ratio, float state_x, float state_y, float state_z, float Pax, float Pby, float Pcz) inline static
Pack a airspeed_autocal message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
vx GPS velocity north m/s
vy GPS velocity east m/s
vz GPS velocity down m/s
diff_pressure Differential pressure pascals
EAS2TAS Estimated to true airspeed ratio
ratio Airspeed ratio
state_x EKF state x
state_y EKF state y
state_z EKF state z
Pax EKF Pax
Pby EKF Pby
Pcz EKF Pcz
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 133 of file mavlink_msg_airspeed_autocal.h.
Referenced by mavlink_msg_airspeed_autocal_encode_chan(), and mavlink_test_airspeed_autocal().