APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_statustext.h File Reference
mavlink_msg_statustext.h File Reference
Classes
struct __mavlink_statustext_t
Macros
#define MAVLINK_MSG_ID_STATUSTEXT 253
#define MAVLINK_MSG_ID_STATUSTEXT_LEN 51
#define MAVLINK_MSG_ID_253_LEN 51
#define MAVLINK_MSG_ID_STATUSTEXT_CRC 83
#define MAVLINK_MSG_ID_253_CRC 83
#define MAVLINK_MSG_STATUSTEXT_FIELD_TEXT_LEN 50
#define MAVLINK_MESSAGE_INFO_STATUSTEXT
Typedefs
typedef struct __mavlink_statustext_t mavlink_statustext_t
Functions
static uint16_t mavlink_msg_statustext_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t severity, const char *text)
Pack a statustext message.
static uint16_t mavlink_msg_statustext_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t severity, const char *text)
Pack a statustext message on a channel.
static uint16_t mavlink_msg_statustext_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_statustext_t *statustext)
Encode a statustext struct.
static uint16_t mavlink_msg_statustext_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_statustext_t *statustext)
Encode a statustext struct on a channel.
static uint8_t mavlink_msg_statustext_get_severity (const mavlink_message_t *msg)
Send a statustext message.
static uint16_t mavlink_msg_statustext_get_text (const mavlink_message_t *msg, char *text)
Get field text from statustext message.
static void mavlink_msg_statustext_decode (const mavlink_message_t *msg, mavlink_statustext_t *statustext)
Decode a statustext message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_STATUSTEXT
Value:
{ \
    "STATUSTEXT", \
    2, \
    {  { "severity", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_statustext_t, severity) }, \
         { "text", NULL, MAVLINK_TYPE_CHAR, 50, 1, offsetof(mavlink_statustext_t, text) }, \
         } \
}
Definition at line 19 of file mavlink_msg_statustext.h.
#define MAVLINK_MSG_ID_253_CRC 83
Definition at line 15 of file mavlink_msg_statustext.h.
#define MAVLINK_MSG_ID_253_LEN 51
Definition at line 12 of file mavlink_msg_statustext.h.
#define MAVLINK_MSG_ID_STATUSTEXT 253
Definition at line 3 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_pack(), and mavlink_msg_statustext_pack_chan().
#define MAVLINK_MSG_ID_STATUSTEXT_CRC 83
Definition at line 14 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_pack(), and mavlink_msg_statustext_pack_chan().
#define MAVLINK_MSG_ID_STATUSTEXT_LEN 51
Definition at line 11 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_decode(), mavlink_msg_statustext_pack(), mavlink_msg_statustext_pack_chan(), AP_InertialSensor_UserInteract_MAVLink::printf(), GCS_MAVLINK::send_statustext_all(), and GCS_MAVLINK::send_text().
#define MAVLINK_MSG_STATUSTEXT_FIELD_TEXT_LEN 50
Definition at line 17 of file mavlink_msg_statustext.h.
Typedef Documentation
typedef struct __mavlink_statustext_t mavlink_statustext_t
Function Documentation
static void mavlink_msg_statustext_decode (const mavlink_message_t * msg, mavlink_statustext_t * statustext) inline static
Decode a statustext message into a struct.
Parameters
msg The message to decode
statustext C-struct to decode the message contents into
Definition at line 217 of file mavlink_msg_statustext.h.
Referenced by mavlink_test_statustext().
static uint16_t mavlink_msg_statustext_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_statustext_t * statustext) inline static
Encode a statustext struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
statustext C-struct to read the message contents from
Definition at line 103 of file mavlink_msg_statustext.h.
Referenced by mavlink_test_statustext().
static uint16_t mavlink_msg_statustext_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_statustext_t * statustext) inline static
Encode a statustext struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
statustext C-struct to read the message contents from
Definition at line 117 of file mavlink_msg_statustext.h.
static uint8_t mavlink_msg_statustext_get_severity (const mavlink_message_t * msg) inline static
Send a statustext message.
Parameters
chan MAVLink channel to send the message
severity Severity of status. Relies on the definitions within RFC-5424. See enum MAV_SEVERITY.
text Status text message, without null termination character Get field severity from statustext message
Returns
Severity of status. Relies on the definitions within RFC-5424. See enum MAV_SEVERITY.
Definition at line 196 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_decode().
static uint16_t mavlink_msg_statustext_get_text (const mavlink_message_t * msg, char * text) inline static
Get field text from statustext message.
Returns
Status text message, without null termination character
Definition at line 206 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_decode().
static uint16_t mavlink_msg_statustext_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t severity, const char * text) inline static
Pack a statustext message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
severity Severity of status. Relies on the definitions within RFC-5424. See enum MAV_SEVERITY.
text Status text message, without null termination character
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_encode(), and mavlink_test_statustext().
static uint16_t mavlink_msg_statustext_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t severity, const char * text) inline static
Pack a statustext message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
severity Severity of status. Relies on the definitions within RFC-5424. See enum MAV_SEVERITY.
text Status text message, without null termination character
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 71 of file mavlink_msg_statustext.h.
Referenced by mavlink_msg_statustext_encode_chan(), and mavlink_test_statustext().