APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_home_offset_calibration_result.h File Reference
mavlink_msg_gimbal_home_offset_calibration_result.h File Reference
Classes
struct __mavlink_gimbal_home_offset_calibration_result_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT 205
#define MAVLINK_MSG_ID_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT_LEN 1
#define MAVLINK_MSG_ID_205_LEN 1
#define MAVLINK_MSG_ID_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT_CRC 63
#define MAVLINK_MSG_ID_205_CRC 63
#define MAVLINK_MESSAGE_INFO_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT
Typedefs
typedef struct __mavlink_gimbal_home_offset_calibration_result_t mavlink_gimbal_home_offset_calibration_result_t
Functions
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t calibration_result)
Pack a gimbal_home_offset_calibration_result message.
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t calibration_result)
Pack a gimbal_home_offset_calibration_result message on a channel.
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_home_offset_calibration_result_t *gimbal_home_offset_calibration_result)
Encode a gimbal_home_offset_calibration_result struct.
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_home_offset_calibration_result_t *gimbal_home_offset_calibration_result)
Encode a gimbal_home_offset_calibration_result struct on a channel.
static uint8_t mavlink_msg_gimbal_home_offset_calibration_result_get_calibration_result (const mavlink_message_t *msg)
Send a gimbal_home_offset_calibration_result message.
static void mavlink_msg_gimbal_home_offset_calibration_result_decode (const mavlink_message_t *msg, mavlink_gimbal_home_offset_calibration_result_t *gimbal_home_offset_calibration_result)
Decode a gimbal_home_offset_calibration_result message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT
Value:
{ \
    "GIMBAL_HOME_OFFSET_CALIBRATION_RESULT", \
    1, \
    {  { "calibration_result", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_home_offset_calibration_result_t, calibration_result) }, \
         } \
}
Definition at line 18 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
#define MAVLINK_MSG_ID_205_CRC 63
Definition at line 14 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
#define MAVLINK_MSG_ID_205_LEN 1
Definition at line 11 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
#define MAVLINK_MSG_ID_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT 205
Definition at line 3 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_msg_gimbal_home_offset_calibration_result_pack(), and mavlink_msg_gimbal_home_offset_calibration_result_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT_CRC 63
Definition at line 13 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_msg_gimbal_home_offset_calibration_result_pack(), and mavlink_msg_gimbal_home_offset_calibration_result_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_HOME_OFFSET_CALIBRATION_RESULT_LEN 1
Definition at line 10 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_msg_gimbal_home_offset_calibration_result_decode(), mavlink_msg_gimbal_home_offset_calibration_result_pack(), and mavlink_msg_gimbal_home_offset_calibration_result_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_home_offset_calibration_result_t mavlink_gimbal_home_offset_calibration_result_t
Function Documentation
static void mavlink_msg_gimbal_home_offset_calibration_result_decode (const mavlink_message_t * msg, mavlink_gimbal_home_offset_calibration_result_t * gimbal_home_offset_calibration_result) inline static
Decode a gimbal_home_offset_calibration_result message into a struct.
Parameters
msg The message to decode
gimbal_home_offset_calibration_result C-struct to decode the message contents into
Definition at line 202 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_test_gimbal_home_offset_calibration_result().
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_home_offset_calibration_result_t * gimbal_home_offset_calibration_result) inline static
Encode a gimbal_home_offset_calibration_result struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_home_offset_calibration_result C-struct to read the message contents from
Definition at line 99 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_test_gimbal_home_offset_calibration_result().
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_home_offset_calibration_result_t * gimbal_home_offset_calibration_result) inline static
Encode a gimbal_home_offset_calibration_result struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_home_offset_calibration_result C-struct to read the message contents from
Definition at line 113 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
static uint8_t mavlink_msg_gimbal_home_offset_calibration_result_get_calibration_result (const mavlink_message_t * msg) inline static
Send a gimbal_home_offset_calibration_result message.
Parameters
chan MAVLink channel to send the message
calibration_result The result of the home offset calibration Get field calibration_result from gimbal_home_offset_calibration_result message
Returns
The result of the home offset calibration
Definition at line 191 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_msg_gimbal_home_offset_calibration_result_decode().
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t calibration_result) inline static
Pack a gimbal_home_offset_calibration_result message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
calibration_result The result of the home offset calibration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_msg_gimbal_home_offset_calibration_result_encode(), and mavlink_test_gimbal_home_offset_calibration_result().
static uint16_t mavlink_msg_gimbal_home_offset_calibration_result_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t calibration_result) inline static
Pack a gimbal_home_offset_calibration_result message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
calibration_result The result of the home offset calibration
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 67 of file mavlink_msg_gimbal_home_offset_calibration_result.h.
Referenced by mavlink_msg_gimbal_home_offset_calibration_result_encode_chan(), and mavlink_test_gimbal_home_offset_calibration_result().