APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/mavlink_helpers.h File Reference
mavlink_helpers.h File Reference
#include "string.h"
#include "checksum.h"
#include "mavlink_types.h"
#include "mavlink_conversions.h"
Classes
union __mavlink_bitfield
Macros
#define MAVLINK_HELPER
Functions
MAVLINK_HELPER mavlink_status_t * mavlink_get_channel_status (uint8_t chan)
MAVLINK_HELPER mavlink_message_t * mavlink_get_channel_buffer (uint8_t chan)
MAVLINK_HELPER void mavlink_reset_channel_status (uint8_t chan)
Reset the status of a channel.
MAVLINK_HELPER uint16_t mavlink_finalize_message_chan (mavlink_message_t *msg, uint8_t system_id, uint8_t component_id, uint8_t chan, uint8_t length)
Finalize a MAVLink message with channel assignment.
MAVLINK_HELPER uint16_t mavlink_finalize_message (mavlink_message_t *msg, uint8_t system_id, uint8_t component_id, uint8_t length)
Finalize a MAVLink message with MAVLINK_COMM_0 as default channel.
MAVLINK_HELPER uint16_t mavlink_msg_to_send_buffer (uint8_t *buffer, const mavlink_message_t *msg)
Pack a message to send it over a serial byte stream.
MAVLINK_HELPER void mavlink_start_checksum (mavlink_message_t *msg)
MAVLINK_HELPER void mavlink_update_checksum (mavlink_message_t *msg, uint8_t c)
MAVLINK_HELPER uint8_t mavlink_frame_char_buffer (mavlink_message_t *rxmsg, mavlink_status_t *status, uint8_t c, mavlink_message_t *r_message, mavlink_status_t *r_mavlink_status)
MAVLINK_HELPER uint8_t mavlink_frame_char (uint8_t chan, uint8_t c, mavlink_message_t *r_message, mavlink_status_t *r_mavlink_status)
MAVLINK_HELPER uint8_t mavlink_parse_char (uint8_t chan, uint8_t c, mavlink_message_t *r_message, mavlink_status_t *r_mavlink_status)
MAVLINK_HELPER uint8_t put_bitfield_n_by_index (int32_t b, uint8_t bits, uint8_t packet_index, uint8_t bit_index, uint8_t *r_bit_index, uint8_t *buffer)
Put a bitfield of length 1-32 bit into the buffer.
Macro Definition Documentation
#define MAVLINK_HELPER
Definition at line 10 of file mavlink_helpers.h.
Function Documentation
MAVLINK_HELPER uint16_t mavlink_finalize_message (mavlink_message_t * msg, uint8_t system_id, uint8_t component_id, uint8_t length)
Finalize a MAVLink message with MAVLINK_COMM_0 as default channel.
Definition at line 105 of file mavlink_helpers.h.
Referenced by mavlink_msg_actuator_control_target_pack(), mavlink_msg_ahrs2_pack(), mavlink_msg_ahrs3_pack(), mavlink_msg_ahrs_pack(), mavlink_msg_airspeed_autocal_pack(), mavlink_msg_ap_adc_pack(), mavlink_msg_att_pos_mocap_pack(), mavlink_msg_attitude_pack(), mavlink_msg_attitude_quaternion_cov_pack(), mavlink_msg_attitude_quaternion_pack(), mavlink_msg_attitude_target_pack(), mavlink_msg_auth_key_pack(), mavlink_msg_autopilot_version_pack(), mavlink_msg_autopilot_version_request_pack(), mavlink_msg_battery2_pack(), mavlink_msg_battery_status_pack(), mavlink_msg_camera_feedback_pack(), mavlink_msg_camera_status_pack(), mavlink_msg_change_operator_control_ack_pack(), mavlink_msg_change_operator_control_pack(), mavlink_msg_command_ack_pack(), mavlink_msg_command_int_pack(), mavlink_msg_command_long_pack(), mavlink_msg_compassmot_status_pack(), mavlink_msg_data16_pack(), mavlink_msg_data32_pack(), mavlink_msg_data64_pack(), mavlink_msg_data96_pack(), mavlink_msg_data_stream_pack(), mavlink_msg_data_transmission_handshake_pack(), mavlink_msg_debug_pack(), mavlink_msg_debug_vect_pack(), mavlink_msg_digicam_configure_pack(), mavlink_msg_digicam_control_pack(), mavlink_msg_distance_sensor_pack(), mavlink_msg_ekf_status_report_pack(), mavlink_msg_encapsulated_data_pack(), mavlink_msg_fence_fetch_point_pack(), mavlink_msg_fence_point_pack(), mavlink_msg_fence_status_pack(), mavlink_msg_file_transfer_protocol_pack(), mavlink_msg_gimbal_axis_calibration_progress_pack(), mavlink_msg_gimbal_control_pack(), mavlink_msg_gimbal_erase_firmware_and_config_pack(), mavlink_msg_gimbal_factory_parameters_loaded_pack(), mavlink_msg_gimbal_home_offset_calibration_result_pack(), mavlink_msg_gimbal_perform_factory_tests_pack(), mavlink_msg_gimbal_report_axis_calibration_status_pack(), mavlink_msg_gimbal_report_factory_tests_progress_pack(), mavlink_msg_gimbal_report_pack(), mavlink_msg_gimbal_request_axis_calibration_pack(), mavlink_msg_gimbal_request_axis_calibration_status_pack(), mavlink_msg_gimbal_reset_pack(), mavlink_msg_gimbal_set_factory_parameters_pack(), mavlink_msg_gimbal_set_home_offsets_pack(), mavlink_msg_global_position_int_cov_pack(), mavlink_msg_global_position_int_pack(), mavlink_msg_global_vision_position_estimate_pack(), mavlink_msg_gopro_get_request_pack(), mavlink_msg_gopro_get_response_pack(), mavlink_msg_gopro_heartbeat_pack(), mavlink_msg_gopro_set_request_pack(), mavlink_msg_gopro_set_response_pack(), mavlink_msg_gps2_raw_pack(), mavlink_msg_gps2_rtk_pack(), mavlink_msg_gps_global_origin_pack(), mavlink_msg_gps_inject_data_pack(), mavlink_msg_gps_raw_int_pack(), mavlink_msg_gps_rtk_pack(), mavlink_msg_gps_status_pack(), mavlink_msg_heartbeat_pack(), mavlink_msg_highres_imu_pack(), mavlink_msg_hil_controls_pack(), mavlink_msg_hil_gps_pack(), mavlink_msg_hil_optical_flow_pack(), mavlink_msg_hil_rc_inputs_raw_pack(), mavlink_msg_hil_sensor_pack(), mavlink_msg_hil_state_pack(), mavlink_msg_hil_state_quaternion_pack(), mavlink_msg_home_position_pack(), mavlink_msg_hwstatus_pack(), mavlink_msg_landing_target_pack(), mavlink_msg_led_control_pack(), mavlink_msg_limits_status_pack(), mavlink_msg_local_position_ned_cov_pack(), mavlink_msg_local_position_ned_pack(), mavlink_msg_local_position_ned_system_global_offset_pack(), mavlink_msg_log_data_pack(), mavlink_msg_log_entry_pack(), mavlink_msg_log_erase_pack(), mavlink_msg_log_request_data_pack(), mavlink_msg_log_request_end_pack(), mavlink_msg_log_request_list_pack(), mavlink_msg_mag_cal_progress_pack(), mavlink_msg_mag_cal_report_pack(), mavlink_msg_manual_control_pack(), mavlink_msg_manual_setpoint_pack(), mavlink_msg_meminfo_pack(), mavlink_msg_memory_vect_pack(), mavlink_msg_mission_ack_pack(), mavlink_msg_mission_clear_all_pack(), mavlink_msg_mission_count_pack(), mavlink_msg_mission_current_pack(), mavlink_msg_mission_item_int_pack(), mavlink_msg_mission_item_pack(), mavlink_msg_mission_item_reached_pack(), mavlink_msg_mission_request_list_pack(), mavlink_msg_mission_request_pack(), mavlink_msg_mission_request_partial_list_pack(), mavlink_msg_mission_set_current_pack(), mavlink_msg_mission_write_partial_list_pack(), mavlink_msg_mount_configure_pack(), mavlink_msg_mount_control_pack(), mavlink_msg_mount_status_pack(), mavlink_msg_named_value_float_pack(), mavlink_msg_named_value_int_pack(), mavlink_msg_nav_controller_output_pack(), mavlink_msg_optical_flow_pack(), mavlink_msg_optical_flow_rad_pack(), mavlink_msg_param_map_rc_pack(), mavlink_msg_param_request_list_pack(), mavlink_msg_param_request_read_pack(), mavlink_msg_param_set_pack(), mavlink_msg_param_value_pack(), mavlink_msg_pid_tuning_pack(), mavlink_msg_ping_pack(), mavlink_msg_position_target_global_int_pack(), mavlink_msg_position_target_local_ned_pack(), mavlink_msg_power_status_pack(), mavlink_msg_radio_pack(), mavlink_msg_radio_status_pack(), mavlink_msg_rally_fetch_point_pack(), mavlink_msg_rally_point_pack(), mavlink_msg_rangefinder_pack(), mavlink_msg_raw_imu_pack(), mavlink_msg_raw_pressure_pack(), mavlink_msg_rc_channels_override_pack(), mavlink_msg_rc_channels_pack(), mavlink_msg_rc_channels_raw_pack(), mavlink_msg_rc_channels_scaled_pack(), mavlink_msg_request_data_stream_pack(), mavlink_msg_rpm_pack(), mavlink_msg_safety_allowed_area_pack(), mavlink_msg_safety_set_allowed_area_pack(), mavlink_msg_scaled_imu2_pack(), mavlink_msg_scaled_imu3_pack(), mavlink_msg_scaled_imu_pack(), mavlink_msg_scaled_pressure2_pack(), mavlink_msg_scaled_pressure3_pack(), mavlink_msg_scaled_pressure_pack(), mavlink_msg_sensor_offsets_pack(), mavlink_msg_serial_control_pack(), mavlink_msg_servo_output_raw_pack(), mavlink_msg_set_actuator_control_target_pack(), mavlink_msg_set_attitude_target_pack(), mavlink_msg_set_gps_global_origin_pack(), mavlink_msg_set_home_position_pack(), mavlink_msg_set_mag_offsets_pack(), mavlink_msg_set_mode_pack(), mavlink_msg_set_position_target_global_int_pack(), mavlink_msg_set_position_target_local_ned_pack(), mavlink_msg_sim_state_pack(), mavlink_msg_simstate_pack(), mavlink_msg_statustext_pack(), mavlink_msg_sys_status_pack(), mavlink_msg_system_time_pack(), mavlink_msg_terrain_check_pack(), mavlink_msg_terrain_data_pack(), mavlink_msg_terrain_report_pack(), mavlink_msg_terrain_request_pack(), mavlink_msg_timesync_pack(), mavlink_msg_v2_extension_pack(), mavlink_msg_vfr_hud_pack(), mavlink_msg_vibration_pack(), mavlink_msg_vicon_position_estimate_pack(), mavlink_msg_vision_position_estimate_pack(), mavlink_msg_vision_speed_estimate_pack(), and mavlink_msg_wind_pack().
MAVLINK_HELPER uint16_t mavlink_finalize_message_chan (mavlink_message_t * msg, uint8_t system_id, uint8_t component_id, uint8_t chan, uint8_t length)
Finalize a MAVLink message with channel assignment.
This function calculates the checksum and sets length and aircraft id correctly. It assumes that the message id and the payload are already correctly set. This function can also be used if the message header has already been written before (as in mavlink_msg_xxx_pack instead of mavlink_msg_xxx_pack_headerless), it just introduces little extra overhead.
Parameters
msg Message to finalize
system_id Id of the sending (this) system, 1-127
length Message length
Definition at line 71 of file mavlink_helpers.h.
Referenced by mavlink_finalize_message(), mavlink_msg_actuator_control_target_pack_chan(), mavlink_msg_ahrs2_pack_chan(), mavlink_msg_ahrs3_pack_chan(), mavlink_msg_ahrs_pack_chan(), mavlink_msg_airspeed_autocal_pack_chan(), mavlink_msg_ap_adc_pack_chan(), mavlink_msg_att_pos_mocap_pack_chan(), mavlink_msg_attitude_pack_chan(), mavlink_msg_attitude_quaternion_cov_pack_chan(), mavlink_msg_attitude_quaternion_pack_chan(), mavlink_msg_attitude_target_pack_chan(), mavlink_msg_auth_key_pack_chan(), mavlink_msg_autopilot_version_pack_chan(), mavlink_msg_autopilot_version_request_pack_chan(), mavlink_msg_battery2_pack_chan(), mavlink_msg_battery_status_pack_chan(), mavlink_msg_camera_feedback_pack_chan(), mavlink_msg_camera_status_pack_chan(), mavlink_msg_change_operator_control_ack_pack_chan(), mavlink_msg_change_operator_control_pack_chan(), mavlink_msg_command_ack_pack_chan(), mavlink_msg_command_int_pack_chan(), mavlink_msg_command_long_pack_chan(), mavlink_msg_compassmot_status_pack_chan(), mavlink_msg_data16_pack_chan(), mavlink_msg_data32_pack_chan(), mavlink_msg_data64_pack_chan(), mavlink_msg_data96_pack_chan(), mavlink_msg_data_stream_pack_chan(), mavlink_msg_data_transmission_handshake_pack_chan(), mavlink_msg_debug_pack_chan(), mavlink_msg_debug_vect_pack_chan(), mavlink_msg_digicam_configure_pack_chan(), mavlink_msg_digicam_control_pack_chan(), mavlink_msg_distance_sensor_pack_chan(), mavlink_msg_ekf_status_report_pack_chan(), mavlink_msg_encapsulated_data_pack_chan(), mavlink_msg_fence_fetch_point_pack_chan(), mavlink_msg_fence_point_pack_chan(), mavlink_msg_fence_status_pack_chan(), mavlink_msg_file_transfer_protocol_pack_chan(), mavlink_msg_gimbal_axis_calibration_progress_pack_chan(), mavlink_msg_gimbal_control_pack_chan(), mavlink_msg_gimbal_erase_firmware_and_config_pack_chan(), mavlink_msg_gimbal_factory_parameters_loaded_pack_chan(), mavlink_msg_gimbal_home_offset_calibration_result_pack_chan(), mavlink_msg_gimbal_perform_factory_tests_pack_chan(), mavlink_msg_gimbal_report_axis_calibration_status_pack_chan(), mavlink_msg_gimbal_report_factory_tests_progress_pack_chan(), mavlink_msg_gimbal_report_pack_chan(), mavlink_msg_gimbal_request_axis_calibration_pack_chan(), mavlink_msg_gimbal_request_axis_calibration_status_pack_chan(), mavlink_msg_gimbal_reset_pack_chan(), mavlink_msg_gimbal_set_factory_parameters_pack_chan(), mavlink_msg_gimbal_set_home_offsets_pack_chan(), mavlink_msg_global_position_int_cov_pack_chan(), mavlink_msg_global_position_int_pack_chan(), mavlink_msg_global_vision_position_estimate_pack_chan(), mavlink_msg_gopro_get_request_pack_chan(), mavlink_msg_gopro_get_response_pack_chan(), mavlink_msg_gopro_heartbeat_pack_chan(), mavlink_msg_gopro_set_request_pack_chan(), mavlink_msg_gopro_set_response_pack_chan(), mavlink_msg_gps2_raw_pack_chan(), mavlink_msg_gps2_rtk_pack_chan(), mavlink_msg_gps_global_origin_pack_chan(), mavlink_msg_gps_inject_data_pack_chan(), mavlink_msg_gps_raw_int_pack_chan(), mavlink_msg_gps_rtk_pack_chan(), mavlink_msg_gps_status_pack_chan(), mavlink_msg_heartbeat_pack_chan(), mavlink_msg_highres_imu_pack_chan(), mavlink_msg_hil_controls_pack_chan(), mavlink_msg_hil_gps_pack_chan(), mavlink_msg_hil_optical_flow_pack_chan(), mavlink_msg_hil_rc_inputs_raw_pack_chan(), mavlink_msg_hil_sensor_pack_chan(), mavlink_msg_hil_state_pack_chan(), mavlink_msg_hil_state_quaternion_pack_chan(), mavlink_msg_home_position_pack_chan(), mavlink_msg_hwstatus_pack_chan(), mavlink_msg_landing_target_pack_chan(), mavlink_msg_led_control_pack_chan(), mavlink_msg_limits_status_pack_chan(), mavlink_msg_local_position_ned_cov_pack_chan(), mavlink_msg_local_position_ned_pack_chan(), mavlink_msg_local_position_ned_system_global_offset_pack_chan(), mavlink_msg_log_data_pack_chan(), mavlink_msg_log_entry_pack_chan(), mavlink_msg_log_erase_pack_chan(), mavlink_msg_log_request_data_pack_chan(), mavlink_msg_log_request_end_pack_chan(), mavlink_msg_log_request_list_pack_chan(), mavlink_msg_mag_cal_progress_pack_chan(), mavlink_msg_mag_cal_report_pack_chan(), mavlink_msg_manual_control_pack_chan(), mavlink_msg_manual_setpoint_pack_chan(), mavlink_msg_meminfo_pack_chan(), mavlink_msg_memory_vect_pack_chan(), mavlink_msg_mission_ack_pack_chan(), mavlink_msg_mission_clear_all_pack_chan(), mavlink_msg_mission_count_pack_chan(), mavlink_msg_mission_current_pack_chan(), mavlink_msg_mission_item_int_pack_chan(), mavlink_msg_mission_item_pack_chan(), mavlink_msg_mission_item_reached_pack_chan(), mavlink_msg_mission_request_list_pack_chan(), mavlink_msg_mission_request_pack_chan(), mavlink_msg_mission_request_partial_list_pack_chan(), mavlink_msg_mission_set_current_pack_chan(), mavlink_msg_mission_write_partial_list_pack_chan(), mavlink_msg_mount_configure_pack_chan(), mavlink_msg_mount_control_pack_chan(), mavlink_msg_mount_status_pack_chan(), mavlink_msg_named_value_float_pack_chan(), mavlink_msg_named_value_int_pack_chan(), mavlink_msg_nav_controller_output_pack_chan(), mavlink_msg_optical_flow_pack_chan(), mavlink_msg_optical_flow_rad_pack_chan(), mavlink_msg_param_map_rc_pack_chan(), mavlink_msg_param_request_list_pack_chan(), mavlink_msg_param_request_read_pack_chan(), mavlink_msg_param_set_pack_chan(), mavlink_msg_param_value_pack_chan(), mavlink_msg_pid_tuning_pack_chan(), mavlink_msg_ping_pack_chan(), mavlink_msg_position_target_global_int_pack_chan(), mavlink_msg_position_target_local_ned_pack_chan(), mavlink_msg_power_status_pack_chan(), mavlink_msg_radio_pack_chan(), mavlink_msg_radio_status_pack_chan(), mavlink_msg_rally_fetch_point_pack_chan(), mavlink_msg_rally_point_pack_chan(), mavlink_msg_rangefinder_pack_chan(), mavlink_msg_raw_imu_pack_chan(), mavlink_msg_raw_pressure_pack_chan(), mavlink_msg_rc_channels_override_pack_chan(), mavlink_msg_rc_channels_pack_chan(), mavlink_msg_rc_channels_raw_pack_chan(), mavlink_msg_rc_channels_scaled_pack_chan(), mavlink_msg_request_data_stream_pack_chan(), mavlink_msg_rpm_pack_chan(), mavlink_msg_safety_allowed_area_pack_chan(), mavlink_msg_safety_set_allowed_area_pack_chan(), mavlink_msg_scaled_imu2_pack_chan(), mavlink_msg_scaled_imu3_pack_chan(), mavlink_msg_scaled_imu_pack_chan(), mavlink_msg_scaled_pressure2_pack_chan(), mavlink_msg_scaled_pressure3_pack_chan(), mavlink_msg_scaled_pressure_pack_chan(), mavlink_msg_sensor_offsets_pack_chan(), mavlink_msg_serial_control_pack_chan(), mavlink_msg_servo_output_raw_pack_chan(), mavlink_msg_set_actuator_control_target_pack_chan(), mavlink_msg_set_attitude_target_pack_chan(), mavlink_msg_set_gps_global_origin_pack_chan(), mavlink_msg_set_home_position_pack_chan(), mavlink_msg_set_mag_offsets_pack_chan(), mavlink_msg_set_mode_pack_chan(), mavlink_msg_set_position_target_global_int_pack_chan(), mavlink_msg_set_position_target_local_ned_pack_chan(), mavlink_msg_sim_state_pack_chan(), mavlink_msg_simstate_pack_chan(), mavlink_msg_statustext_pack_chan(), mavlink_msg_sys_status_pack_chan(), mavlink_msg_system_time_pack_chan(), mavlink_msg_terrain_check_pack_chan(), mavlink_msg_terrain_data_pack_chan(), mavlink_msg_terrain_report_pack_chan(), mavlink_msg_terrain_request_pack_chan(), mavlink_msg_timesync_pack_chan(), mavlink_msg_v2_extension_pack_chan(), mavlink_msg_vfr_hud_pack_chan(), mavlink_msg_vibration_pack_chan(), mavlink_msg_vicon_position_estimate_pack_chan(), mavlink_msg_vision_position_estimate_pack_chan(), mavlink_msg_vision_speed_estimate_pack_chan(), and mavlink_msg_wind_pack_chan().
MAVLINK_HELPER uint8_t mavlink_frame_char (uint8_t chan, uint8_t c, mavlink_message_t * r_message, mavlink_status_t * r_mavlink_status)
This is a convenience function which handles the complete MAVLink parsing. the function will parse one byte at a time and return the complete packet once it could be successfully decoded. This function will return 0, 1 or 2 (MAVLINK_FRAMING_INCOMPLETE, MAVLINK_FRAMING_OK or MAVLINK_FRAMING_BAD_CRC)
Messages are parsed into an internal buffer (one for each channel). When a complete message is received it is copies into *returnMsg and the channel's status is copied into *returnStats.
Parameters
chan ID of the current channel. This allows to parse different channels with this function. a channel is not a physical message channel like a serial port, but a logic partition of the communication streams in this case. COMM_NB is the limit for the number of channels on MCU (e.g. ARM7), while COMM_NB_HIGH is the limit for the number of channels in Linux/Windows
c The char to parse
returnMsg NULL if no message could be decoded, the message data else
returnStats if a message was decoded, this is filled with the channel's stats
Returns
0 if no message could be decoded, 1 on good message and CRC, 2 on bad CRC
A typical use scenario of this function call is:
 #include <mavlink.h>
 mavlink_message_t msg;
 int chan = 0;
 while(serial.bytesAvailable > 0)
 {
   uint8_t byte = serial.getNextByte();
   if (mavlink_frame_char(chan, byte, &msg) != MAVLINK_FRAMING_INCOMPLETE)
     {
     printf("Received message with ID %d, sequence: %d from component %d of system %d", msg.msgid, msg.seq, msg.compid, msg.sysid);
     }
 }
Definition at line 465 of file mavlink_helpers.h.
Referenced by mavlink_parse_char().
MAVLINK_HELPER uint8_t mavlink_frame_char_buffer (mavlink_message_t * rxmsg, mavlink_status_t * status, uint8_t c, mavlink_message_t * r_message, mavlink_status_t * r_mavlink_status)
This is a varient of mavlink_frame_char() but with caller supplied parsing buffers. It is useful when you want to create a MAVLink parser in a library that doesn't use any global variables
Parameters
rxmsg parsing message buffer
status parsing starus buffer
c The char to parse
returnMsg NULL if no message could be decoded, the message data else
returnStats if a message was decoded, this is filled with the channel's stats
Returns
0 if no message could be decoded, 1 on good message and CRC, 2 on bad CRC
A typical use scenario of this function call is:
 #include <mavlink.h>
 mavlink_message_t msg;
 int chan = 0;
 while(serial.bytesAvailable > 0)
 {
   uint8_t byte = serial.getNextByte();
   if (mavlink_frame_char(chan, byte, &msg) != MAVLINK_FRAMING_INCOMPLETE)
     {
     printf("Received message with ID %d, sequence: %d from component %d of system %d", msg.msgid, msg.seq, msg.compid, msg.sysid);
     }
 }
Definition at line 240 of file mavlink_helpers.h.
Referenced by mavlink_frame_char(), and SITL::Gimbal::send_report().
MAVLINK_HELPER mavlink_message_t* mavlink_get_channel_buffer (uint8_t chan)
Definition at line 33 of file mavlink_helpers.h.
Referenced by mavlink_frame_char(), and mavlink_parse_char().
MAVLINK_HELPER mavlink_status_t* mavlink_get_channel_status (uint8_t chan)
Definition at line 17 of file mavlink_helpers.h.
Referenced by comm_is_idle(), mavlink_finalize_message_chan(), mavlink_frame_char(), mavlink_parse_char(), mavlink_reset_channel_status(), and SITL::Gimbal::send_report().
MAVLINK_HELPER uint16_t mavlink_msg_to_send_buffer (uint8_t * buffer, const mavlink_message_t * msg)
Pack a message to send it over a serial byte stream.
Definition at line 174 of file mavlink_helpers.h.
Referenced by mavlink_test_actuator_control_target(), mavlink_test_ahrs(), mavlink_test_ahrs2(), mavlink_test_ahrs3(), mavlink_test_airspeed_autocal(), mavlink_test_ap_adc(), mavlink_test_att_pos_mocap(), mavlink_test_attitude(), mavlink_test_attitude_quaternion(), mavlink_test_attitude_quaternion_cov(), mavlink_test_attitude_target(), mavlink_test_auth_key(), mavlink_test_autopilot_version(), mavlink_test_autopilot_version_request(), mavlink_test_battery2(), mavlink_test_battery_status(), mavlink_test_camera_feedback(), mavlink_test_camera_status(), mavlink_test_change_operator_control(), mavlink_test_change_operator_control_ack(), mavlink_test_command_ack(), mavlink_test_command_int(), mavlink_test_command_long(), mavlink_test_compassmot_status(), mavlink_test_data16(), mavlink_test_data32(), mavlink_test_data64(), mavlink_test_data96(), mavlink_test_data_stream(), mavlink_test_data_transmission_handshake(), mavlink_test_debug(), mavlink_test_debug_vect(), mavlink_test_digicam_configure(), mavlink_test_digicam_control(), mavlink_test_distance_sensor(), mavlink_test_ekf_status_report(), mavlink_test_encapsulated_data(), mavlink_test_fence_fetch_point(), mavlink_test_fence_point(), mavlink_test_fence_status(), mavlink_test_file_transfer_protocol(), mavlink_test_gimbal_axis_calibration_progress(), mavlink_test_gimbal_control(), mavlink_test_gimbal_erase_firmware_and_config(), mavlink_test_gimbal_factory_parameters_loaded(), mavlink_test_gimbal_home_offset_calibration_result(), mavlink_test_gimbal_perform_factory_tests(), mavlink_test_gimbal_report(), mavlink_test_gimbal_report_axis_calibration_status(), mavlink_test_gimbal_report_factory_tests_progress(), mavlink_test_gimbal_request_axis_calibration(), mavlink_test_gimbal_request_axis_calibration_status(), mavlink_test_gimbal_reset(), mavlink_test_gimbal_set_factory_parameters(), mavlink_test_gimbal_set_home_offsets(), mavlink_test_global_position_int(), mavlink_test_global_position_int_cov(), mavlink_test_global_vision_position_estimate(), mavlink_test_gopro_get_request(), mavlink_test_gopro_get_response(), mavlink_test_gopro_heartbeat(), mavlink_test_gopro_set_request(), mavlink_test_gopro_set_response(), mavlink_test_gps2_raw(), mavlink_test_gps2_rtk(), mavlink_test_gps_global_origin(), mavlink_test_gps_inject_data(), mavlink_test_gps_raw_int(), mavlink_test_gps_rtk(), mavlink_test_gps_status(), mavlink_test_heartbeat(), mavlink_test_highres_imu(), mavlink_test_hil_controls(), mavlink_test_hil_gps(), mavlink_test_hil_optical_flow(), mavlink_test_hil_rc_inputs_raw(), mavlink_test_hil_sensor(), mavlink_test_hil_state(), mavlink_test_hil_state_quaternion(), mavlink_test_home_position(), mavlink_test_hwstatus(), mavlink_test_landing_target(), mavlink_test_led_control(), mavlink_test_limits_status(), mavlink_test_local_position_ned(), mavlink_test_local_position_ned_cov(), mavlink_test_local_position_ned_system_global_offset(), mavlink_test_log_data(), mavlink_test_log_entry(), mavlink_test_log_erase(), mavlink_test_log_request_data(), mavlink_test_log_request_end(), mavlink_test_log_request_list(), mavlink_test_mag_cal_progress(), mavlink_test_mag_cal_report(), mavlink_test_manual_control(), mavlink_test_manual_setpoint(), mavlink_test_meminfo(), mavlink_test_memory_vect(), mavlink_test_mission_ack(), mavlink_test_mission_clear_all(), mavlink_test_mission_count(), mavlink_test_mission_current(), mavlink_test_mission_item(), mavlink_test_mission_item_int(), mavlink_test_mission_item_reached(), mavlink_test_mission_request(), mavlink_test_mission_request_list(), mavlink_test_mission_request_partial_list(), mavlink_test_mission_set_current(), mavlink_test_mission_write_partial_list(), mavlink_test_mount_configure(), mavlink_test_mount_control(), mavlink_test_mount_status(), mavlink_test_named_value_float(), mavlink_test_named_value_int(), mavlink_test_nav_controller_output(), mavlink_test_optical_flow(), mavlink_test_optical_flow_rad(), mavlink_test_param_map_rc(), mavlink_test_param_request_list(), mavlink_test_param_request_read(), mavlink_test_param_set(), mavlink_test_param_value(), mavlink_test_pid_tuning(), mavlink_test_ping(), mavlink_test_position_target_global_int(), mavlink_test_position_target_local_ned(), mavlink_test_power_status(), mavlink_test_radio(), mavlink_test_radio_status(), mavlink_test_rally_fetch_point(), mavlink_test_rally_point(), mavlink_test_rangefinder(), mavlink_test_raw_imu(), mavlink_test_raw_pressure(), mavlink_test_rc_channels(), mavlink_test_rc_channels_override(), mavlink_test_rc_channels_raw(), mavlink_test_rc_channels_scaled(), mavlink_test_request_data_stream(), mavlink_test_rpm(), mavlink_test_safety_allowed_area(), mavlink_test_safety_set_allowed_area(), mavlink_test_scaled_imu(), mavlink_test_scaled_imu2(), mavlink_test_scaled_imu3(), mavlink_test_scaled_pressure(), mavlink_test_scaled_pressure2(), mavlink_test_scaled_pressure3(), mavlink_test_sensor_offsets(), mavlink_test_serial_control(), mavlink_test_servo_output_raw(), mavlink_test_set_actuator_control_target(), mavlink_test_set_attitude_target(), mavlink_test_set_gps_global_origin(), mavlink_test_set_home_position(), mavlink_test_set_mag_offsets(), mavlink_test_set_mode(), mavlink_test_set_position_target_global_int(), mavlink_test_set_position_target_local_ned(), mavlink_test_sim_state(), mavlink_test_simstate(), mavlink_test_statustext(), mavlink_test_sys_status(), mavlink_test_system_time(), mavlink_test_terrain_check(), mavlink_test_terrain_data(), mavlink_test_terrain_report(), mavlink_test_terrain_request(), mavlink_test_timesync(), mavlink_test_v2_extension(), mavlink_test_vfr_hud(), mavlink_test_vibration(), mavlink_test_vicon_position_estimate(), mavlink_test_vision_position_estimate(), mavlink_test_vision_speed_estimate(), and mavlink_test_wind().
MAVLINK_HELPER uint8_t mavlink_parse_char (uint8_t chan, uint8_t c, mavlink_message_t * r_message, mavlink_status_t * r_mavlink_status)
This is a convenience function which handles the complete MAVLink parsing. the function will parse one byte at a time and return the complete packet once it could be successfully decoded. This function will return 0 or 1.
Messages are parsed into an internal buffer (one for each channel). When a complete message is received it is copies into *returnMsg and the channel's status is copied into *returnStats.
Parameters
chan ID of the current channel. This allows to parse different channels with this function. a channel is not a physical message channel like a serial port, but a logic partition of the communication streams in this case. COMM_NB is the limit for the number of channels on MCU (e.g. ARM7), while COMM_NB_HIGH is the limit for the number of channels in Linux/Windows
c The char to parse
returnMsg NULL if no message could be decoded, the message data else
returnStats if a message was decoded, this is filled with the channel's stats
Returns
0 if no message could be decoded or bad CRC, 1 on good message and CRC
A typical use scenario of this function call is:
 #include <mavlink.h>
 mavlink_message_t msg;
 int chan = 0;
 while(serial.bytesAvailable > 0)
 {
   uint8_t byte = serial.getNextByte();
   if (mavlink_parse_char(chan, byte, &msg))
     {
     printf("Received message with ID %d, sequence: %d from component %d of system %d", msg.msgid, msg.seq, msg.compid, msg.sysid);
     }
 }
Definition at line 515 of file mavlink_helpers.h.
Referenced by simplegcs_update(), and GCS_MAVLINK::update().
MAVLINK_HELPER void mavlink_reset_channel_status (uint8_t chan)
Reset the status of a channel.
Definition at line 49 of file mavlink_helpers.h.
MAVLINK_HELPER void mavlink_start_checksum (mavlink_message_t * msg)
Definition at line 196 of file mavlink_helpers.h.
Referenced by mavlink_frame_char_buffer(), and mavlink_parse_char().
MAVLINK_HELPER void mavlink_update_checksum (mavlink_message_t * msg, uint8_t c)
Definition at line 201 of file mavlink_helpers.h.
Referenced by mavlink_frame_char_buffer().
MAVLINK_HELPER uint8_t put_bitfield_n_by_index (int32_t b, uint8_t bits, uint8_t packet_index, uint8_t bit_index, uint8_t * r_bit_index, uint8_t * buffer)
Put a bitfield of length 1-32 bit into the buffer.
Parameters
b the value to add, will be encoded in the bitfield
bits number of bits to use to encode b, e.g. 1 for boolean, 2, 3, etc.
packet_index the position in the packet (the index of the first byte to use)
bit_index the position in the byte (the index of the first bit to use)
buffer packet buffer to write into
Returns
new position of the last used byte in the buffer
Definition at line 546 of file mavlink_helpers.h.