APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_actuator_control_target.h File Reference
mavlink_msg_actuator_control_target.h File Reference
Classes
struct __mavlink_actuator_control_target_t
Macros
#define MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET 140
#define MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET_LEN 41
#define MAVLINK_MSG_ID_140_LEN 41
#define MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET_CRC 181
#define MAVLINK_MSG_ID_140_CRC 181
#define MAVLINK_MSG_ACTUATOR_CONTROL_TARGET_FIELD_CONTROLS_LEN 8
#define MAVLINK_MESSAGE_INFO_ACTUATOR_CONTROL_TARGET
Typedefs
typedef struct __mavlink_actuator_control_target_t mavlink_actuator_control_target_t
Functions
static uint16_t mavlink_msg_actuator_control_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t group_mlx, const float *controls)
Pack a actuator_control_target message.
static uint16_t mavlink_msg_actuator_control_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t group_mlx, const float *controls)
Pack a actuator_control_target message on a channel.
static uint16_t mavlink_msg_actuator_control_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_actuator_control_target_t *actuator_control_target)
Encode a actuator_control_target struct.
static uint16_t mavlink_msg_actuator_control_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_actuator_control_target_t *actuator_control_target)
Encode a actuator_control_target struct on a channel.
static uint64_t mavlink_msg_actuator_control_target_get_time_usec (const mavlink_message_t *msg)
Send a actuator_control_target message.
static uint8_t mavlink_msg_actuator_control_target_get_group_mlx (const mavlink_message_t *msg)
Get field group_mlx from actuator_control_target message.
static uint16_t mavlink_msg_actuator_control_target_get_controls (const mavlink_message_t *msg, float *controls)
Get field controls from actuator_control_target message.
static void mavlink_msg_actuator_control_target_decode (const mavlink_message_t *msg, mavlink_actuator_control_target_t *actuator_control_target)
Decode a actuator_control_target message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ACTUATOR_CONTROL_TARGET
Value:
{ \
    "ACTUATOR_CONTROL_TARGET", \
    3, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_actuator_control_target_t, time_usec) }, \
         { "controls", NULL, MAVLINK_TYPE_FLOAT, 8, 8, offsetof(mavlink_actuator_control_target_t, controls) }, \
         { "group_mlx", NULL, MAVLINK_TYPE_UINT8_T, 0, 40, offsetof(mavlink_actuator_control_target_t, group_mlx) }, \
         } \
}
Definition at line 20 of file mavlink_msg_actuator_control_target.h.
#define MAVLINK_MSG_ACTUATOR_CONTROL_TARGET_FIELD_CONTROLS_LEN 8
Definition at line 18 of file mavlink_msg_actuator_control_target.h.
#define MAVLINK_MSG_ID_140_CRC 181
Definition at line 16 of file mavlink_msg_actuator_control_target.h.
#define MAVLINK_MSG_ID_140_LEN 41
Definition at line 13 of file mavlink_msg_actuator_control_target.h.
#define MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET 140
Definition at line 3 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_pack(), and mavlink_msg_actuator_control_target_pack_chan().
#define MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET_CRC 181
Definition at line 15 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_pack(), and mavlink_msg_actuator_control_target_pack_chan().
#define MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET_LEN 41
Definition at line 12 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_decode(), mavlink_msg_actuator_control_target_pack(), and mavlink_msg_actuator_control_target_pack_chan().
Typedef Documentation
typedef struct __mavlink_actuator_control_target_t mavlink_actuator_control_target_t
Function Documentation
static void mavlink_msg_actuator_control_target_decode (const mavlink_message_t * msg, mavlink_actuator_control_target_t * actuator_control_target) inline static
Decode a actuator_control_target message into a struct.
Parameters
msg The message to decode
actuator_control_target C-struct to decode the message contents into
Definition at line 240 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_test_actuator_control_target().
static uint16_t mavlink_msg_actuator_control_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_actuator_control_target_t * actuator_control_target) inline static
Encode a actuator_control_target struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
actuator_control_target C-struct to read the message contents from
Definition at line 111 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_test_actuator_control_target().
static uint16_t mavlink_msg_actuator_control_target_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_actuator_control_target_t * actuator_control_target) inline static
Encode a actuator_control_target struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
actuator_control_target C-struct to read the message contents from
Definition at line 125 of file mavlink_msg_actuator_control_target.h.
static uint16_t mavlink_msg_actuator_control_target_get_controls (const mavlink_message_t * msg, float * controls) inline static
Get field controls from actuator_control_target message.
Returns
Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs.
Definition at line 229 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_decode().
static uint8_t mavlink_msg_actuator_control_target_get_group_mlx (const mavlink_message_t * msg) inline static
Get field group_mlx from actuator_control_target message.
Returns
Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
Definition at line 219 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_decode().
static uint64_t mavlink_msg_actuator_control_target_get_time_usec (const mavlink_message_t * msg) inline static
Send a actuator_control_target message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (micros since boot or Unix epoch)
group_mlx Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
controls Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs. Get field time_usec from actuator_control_target message
Returns
Timestamp (micros since boot or Unix epoch)
Definition at line 209 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_decode().
static uint16_t mavlink_msg_actuator_control_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t group_mlx, const float * controls) inline static
Pack a actuator_control_target message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
group_mlx Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
controls Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_encode(), and mavlink_test_actuator_control_target().
static uint16_t mavlink_msg_actuator_control_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t group_mlx, const float * controls) inline static
Pack a actuator_control_target message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (micros since boot or Unix epoch)
group_mlx Actuator group. The "_mlx" indicates this is a multi-instance message and a MAVLink parser should use this field to difference between instances.
controls Actuator controls. Normed to -1..+1 where 0 is neutral position. Throttle for single rotation direction motors is 0..1, negative range for reverse direction. Standard mapping for attitude controls (group 0): (index 0-7): roll, pitch, yaw, throttle, flaps, spoilers, airbrakes, landing gear. Load a pass-through mixer to repurpose them as generic outputs.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 77 of file mavlink_msg_actuator_control_target.h.
Referenced by mavlink_msg_actuator_control_target_encode_chan(), and mavlink_test_actuator_control_target().