APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_mission_request_partial_list.h File Reference
mavlink_msg_mission_request_partial_list.h File Reference
Classes
struct __mavlink_mission_request_partial_list_t
Macros
#define MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST 37
#define MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST_LEN 6
#define MAVLINK_MSG_ID_37_LEN 6
#define MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST_CRC 212
#define MAVLINK_MSG_ID_37_CRC 212
#define MAVLINK_MESSAGE_INFO_MISSION_REQUEST_PARTIAL_LIST
Typedefs
typedef struct __mavlink_mission_request_partial_list_t mavlink_mission_request_partial_list_t
Functions
static uint16_t mavlink_msg_mission_request_partial_list_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int16_t start_index, int16_t end_index)
Pack a mission_request_partial_list message.
static uint16_t mavlink_msg_mission_request_partial_list_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int16_t start_index, int16_t end_index)
Pack a mission_request_partial_list message on a channel.
static uint16_t mavlink_msg_mission_request_partial_list_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mission_request_partial_list_t *mission_request_partial_list)
Encode a mission_request_partial_list struct.
static uint16_t mavlink_msg_mission_request_partial_list_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mission_request_partial_list_t *mission_request_partial_list)
Encode a mission_request_partial_list struct on a channel.
static uint8_t mavlink_msg_mission_request_partial_list_get_target_system (const mavlink_message_t *msg)
Send a mission_request_partial_list message.
static uint8_t mavlink_msg_mission_request_partial_list_get_target_component (const mavlink_message_t *msg)
Get field target_component from mission_request_partial_list message.
static int16_t mavlink_msg_mission_request_partial_list_get_start_index (const mavlink_message_t *msg)
Get field start_index from mission_request_partial_list message.
static int16_t mavlink_msg_mission_request_partial_list_get_end_index (const mavlink_message_t *msg)
Get field end_index from mission_request_partial_list message.
static void mavlink_msg_mission_request_partial_list_decode (const mavlink_message_t *msg, mavlink_mission_request_partial_list_t *mission_request_partial_list)
Decode a mission_request_partial_list message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MISSION_REQUEST_PARTIAL_LIST
Value:
{ \
    "MISSION_REQUEST_PARTIAL_LIST", \
    4, \
    {  { "start_index", NULL, MAVLINK_TYPE_INT16_T, 0, 0, offsetof(mavlink_mission_request_partial_list_t, start_index) }, \
         { "end_index", NULL, MAVLINK_TYPE_INT16_T, 0, 2, offsetof(mavlink_mission_request_partial_list_t, end_index) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_mission_request_partial_list_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_mission_request_partial_list_t, target_component) }, \
         } \
}
Definition at line 21 of file mavlink_msg_mission_request_partial_list.h.
#define MAVLINK_MSG_ID_37_CRC 212
Definition at line 17 of file mavlink_msg_mission_request_partial_list.h.
#define MAVLINK_MSG_ID_37_LEN 6
Definition at line 14 of file mavlink_msg_mission_request_partial_list.h.
#define MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST 37
Definition at line 3 of file mavlink_msg_mission_request_partial_list.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_mission_request_partial_list_pack(), and mavlink_msg_mission_request_partial_list_pack_chan().
#define MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST_CRC 212
Definition at line 16 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_msg_mission_request_partial_list_pack(), and mavlink_msg_mission_request_partial_list_pack_chan().
#define MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST_LEN 6
Definition at line 13 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_msg_mission_request_partial_list_decode(), mavlink_msg_mission_request_partial_list_pack(), and mavlink_msg_mission_request_partial_list_pack_chan().
Typedef Documentation
typedef struct __mavlink_mission_request_partial_list_t mavlink_mission_request_partial_list_t
Function Documentation
static void mavlink_msg_mission_request_partial_list_decode (const mavlink_message_t * msg, mavlink_mission_request_partial_list_t * mission_request_partial_list) inline static
Decode a mission_request_partial_list message into a struct.
Parameters
msg The message to decode
mission_request_partial_list C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_test_mission_request_partial_list().
static uint16_t mavlink_msg_mission_request_partial_list_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mission_request_partial_list_t * mission_request_partial_list) inline static
Encode a mission_request_partial_list struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mission_request_partial_list C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_test_mission_request_partial_list().
static uint16_t mavlink_msg_mission_request_partial_list_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mission_request_partial_list_t * mission_request_partial_list) inline static
Encode a mission_request_partial_list struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mission_request_partial_list C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_mission_request_partial_list.h.
static int16_t mavlink_msg_mission_request_partial_list_get_end_index (const mavlink_message_t * msg) inline static
Get field end_index from mission_request_partial_list message.
Returns
End index, -1 by default (-1: send list to end). Else a valid index of the list
Definition at line 260 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_msg_mission_request_partial_list_decode().
static int16_t mavlink_msg_mission_request_partial_list_get_start_index (const mavlink_message_t * msg) inline static
Get field start_index from mission_request_partial_list message.
Returns
Start index, 0 by default
Definition at line 250 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_msg_mission_request_partial_list_decode().
static uint8_t mavlink_msg_mission_request_partial_list_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from mission_request_partial_list message.
Returns
Component ID
Definition at line 240 of file mavlink_msg_mission_request_partial_list.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_request_partial_list_decode().
static uint8_t mavlink_msg_mission_request_partial_list_get_target_system (const mavlink_message_t * msg) inline static
Send a mission_request_partial_list message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
start_index Start index, 0 by default
end_index End index, -1 by default (-1: send list to end). Else a valid index of the list Get field target_system from mission_request_partial_list message
Returns
System ID
Definition at line 230 of file mavlink_msg_mission_request_partial_list.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mission_request_partial_list_decode().
static uint16_t mavlink_msg_mission_request_partial_list_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int16_t start_index, int16_t end_index) inline static
Pack a mission_request_partial_list message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
start_index Start index, 0 by default
end_index End index, -1 by default (-1: send list to end). Else a valid index of the list
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_msg_mission_request_partial_list_encode(), and mavlink_test_mission_request_partial_list().
static uint16_t mavlink_msg_mission_request_partial_list_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int16_t start_index, int16_t end_index) inline static
Pack a mission_request_partial_list message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
start_index Start index, 0 by default
end_index End index, -1 by default (-1: send list to end). Else a valid index of the list
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_mission_request_partial_list.h.
Referenced by mavlink_msg_mission_request_partial_list_encode_chan(), and mavlink_test_mission_request_partial_list().