APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_terrain_request.h File Reference
mavlink_msg_terrain_request.h File Reference
Classes
struct __mavlink_terrain_request_t
Macros
#define MAVLINK_MSG_ID_TERRAIN_REQUEST 133
#define MAVLINK_MSG_ID_TERRAIN_REQUEST_LEN 18
#define MAVLINK_MSG_ID_133_LEN 18
#define MAVLINK_MSG_ID_TERRAIN_REQUEST_CRC 6
#define MAVLINK_MSG_ID_133_CRC 6
#define MAVLINK_MESSAGE_INFO_TERRAIN_REQUEST
Typedefs
typedef struct __mavlink_terrain_request_t mavlink_terrain_request_t
Functions
static uint16_t mavlink_msg_terrain_request_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, int32_t lat, int32_t lon, uint16_t grid_spacing, uint64_t mask)
Pack a terrain_request message.
static uint16_t mavlink_msg_terrain_request_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, int32_t lat, int32_t lon, uint16_t grid_spacing, uint64_t mask)
Pack a terrain_request message on a channel.
static uint16_t mavlink_msg_terrain_request_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_terrain_request_t *terrain_request)
Encode a terrain_request struct.
static uint16_t mavlink_msg_terrain_request_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_terrain_request_t *terrain_request)
Encode a terrain_request struct on a channel.
static int32_t mavlink_msg_terrain_request_get_lat (const mavlink_message_t *msg)
Send a terrain_request message.
static int32_t mavlink_msg_terrain_request_get_lon (const mavlink_message_t *msg)
Get field lon from terrain_request message.
static uint16_t mavlink_msg_terrain_request_get_grid_spacing (const mavlink_message_t *msg)
Get field grid_spacing from terrain_request message.
static uint64_t mavlink_msg_terrain_request_get_mask (const mavlink_message_t *msg)
Get field mask from terrain_request message.
static void mavlink_msg_terrain_request_decode (const mavlink_message_t *msg, mavlink_terrain_request_t *terrain_request)
Decode a terrain_request message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_TERRAIN_REQUEST
Value:
{ \
    "TERRAIN_REQUEST", \
    4, \
    {  { "mask", "0x%07x", MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_terrain_request_t, mask) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_terrain_request_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 12, offsetof(mavlink_terrain_request_t, lon) }, \
         { "grid_spacing", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_terrain_request_t, grid_spacing) }, \
         } \
}
Definition at line 21 of file mavlink_msg_terrain_request.h.
#define MAVLINK_MSG_ID_133_CRC 6
Definition at line 17 of file mavlink_msg_terrain_request.h.
#define MAVLINK_MSG_ID_133_LEN 18
Definition at line 14 of file mavlink_msg_terrain_request.h.
#define MAVLINK_MSG_ID_TERRAIN_REQUEST 133
Definition at line 3 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_pack(), and mavlink_msg_terrain_request_pack_chan().
#define MAVLINK_MSG_ID_TERRAIN_REQUEST_CRC 6
Definition at line 16 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_pack(), and mavlink_msg_terrain_request_pack_chan().
#define MAVLINK_MSG_ID_TERRAIN_REQUEST_LEN 18
Definition at line 13 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_decode(), mavlink_msg_terrain_request_pack(), and mavlink_msg_terrain_request_pack_chan().
Typedef Documentation
typedef struct __mavlink_terrain_request_t mavlink_terrain_request_t
Function Documentation
static void mavlink_msg_terrain_request_decode (const mavlink_message_t * msg, mavlink_terrain_request_t * terrain_request) inline static
Decode a terrain_request message into a struct.
Parameters
msg The message to decode
terrain_request C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_test_terrain_request().
static uint16_t mavlink_msg_terrain_request_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_terrain_request_t * terrain_request) inline static
Encode a terrain_request struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
terrain_request C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_test_terrain_request().
static uint16_t mavlink_msg_terrain_request_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_terrain_request_t * terrain_request) inline static
Encode a terrain_request struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
terrain_request C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_terrain_request.h.
static uint16_t mavlink_msg_terrain_request_get_grid_spacing (const mavlink_message_t * msg) inline static
Get field grid_spacing from terrain_request message.
Returns
Grid spacing in meters
Definition at line 250 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_decode().
static int32_t mavlink_msg_terrain_request_get_lat (const mavlink_message_t * msg) inline static
Send a terrain_request message.
Parameters
chan MAVLink channel to send the message
lat Latitude of SW corner of first grid (degrees *10^7)
lon Longitude of SW corner of first grid (in degrees *10^7)
grid_spacing Grid spacing in meters
mask Bitmask of requested 4x4 grids (row major 8x7 array of grids, 56 bits) Get field lat from terrain_request message
Returns
Latitude of SW corner of first grid (degrees *10^7)
Definition at line 230 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_decode().
static int32_t mavlink_msg_terrain_request_get_lon (const mavlink_message_t * msg) inline static
Get field lon from terrain_request message.
Returns
Longitude of SW corner of first grid (in degrees *10^7)
Definition at line 240 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_decode().
static uint64_t mavlink_msg_terrain_request_get_mask (const mavlink_message_t * msg) inline static
Get field mask from terrain_request message.
Returns
Bitmask of requested 4x4 grids (row major 8x7 array of grids, 56 bits)
Definition at line 260 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_decode().
static uint16_t mavlink_msg_terrain_request_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, int32_t lat, int32_t lon, uint16_t grid_spacing, uint64_t mask) inline static
Pack a terrain_request message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
lat Latitude of SW corner of first grid (degrees *10^7)
lon Longitude of SW corner of first grid (in degrees *10^7)
grid_spacing Grid spacing in meters
mask Bitmask of requested 4x4 grids (row major 8x7 array of grids, 56 bits)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_encode(), and mavlink_test_terrain_request().
static uint16_t mavlink_msg_terrain_request_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, int32_t lat, int32_t lon, uint16_t grid_spacing, uint64_t mask) inline static
Pack a terrain_request message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
lat Latitude of SW corner of first grid (degrees *10^7)
lon Longitude of SW corner of first grid (in degrees *10^7)
grid_spacing Grid spacing in meters
mask Bitmask of requested 4x4 grids (row major 8x7 array of grids, 56 bits)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_terrain_request.h.
Referenced by mavlink_msg_terrain_request_encode_chan(), and mavlink_test_terrain_request().