APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_request_axis_calibration.h File Reference
mavlink_msg_gimbal_request_axis_calibration.h File Reference
Classes
struct __mavlink_gimbal_request_axis_calibration_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION 213
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_LEN 2
#define MAVLINK_MSG_ID_213_LEN 2
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_CRC 14
#define MAVLINK_MSG_ID_213_CRC 14
#define MAVLINK_MESSAGE_INFO_GIMBAL_REQUEST_AXIS_CALIBRATION
Typedefs
typedef struct __mavlink_gimbal_request_axis_calibration_t mavlink_gimbal_request_axis_calibration_t
Functions
static uint16_t mavlink_msg_gimbal_request_axis_calibration_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a gimbal_request_axis_calibration message.
static uint16_t mavlink_msg_gimbal_request_axis_calibration_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component)
Pack a gimbal_request_axis_calibration message on a channel.
static uint16_t mavlink_msg_gimbal_request_axis_calibration_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_request_axis_calibration_t *gimbal_request_axis_calibration)
Encode a gimbal_request_axis_calibration struct.
static uint16_t mavlink_msg_gimbal_request_axis_calibration_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_request_axis_calibration_t *gimbal_request_axis_calibration)
Encode a gimbal_request_axis_calibration struct on a channel.
static uint8_t mavlink_msg_gimbal_request_axis_calibration_get_target_system (const mavlink_message_t *msg)
Send a gimbal_request_axis_calibration message.
static uint8_t mavlink_msg_gimbal_request_axis_calibration_get_target_component (const mavlink_message_t *msg)
Get field target_component from gimbal_request_axis_calibration message.
static void mavlink_msg_gimbal_request_axis_calibration_decode (const mavlink_message_t *msg, mavlink_gimbal_request_axis_calibration_t *gimbal_request_axis_calibration)
Decode a gimbal_request_axis_calibration message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_REQUEST_AXIS_CALIBRATION
Value:
{ \
    "GIMBAL_REQUEST_AXIS_CALIBRATION", \
    2, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_request_axis_calibration_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gimbal_request_axis_calibration_t, target_component) }, \
         } \
}
Definition at line 19 of file mavlink_msg_gimbal_request_axis_calibration.h.
#define MAVLINK_MSG_ID_213_CRC 14
Definition at line 15 of file mavlink_msg_gimbal_request_axis_calibration.h.
#define MAVLINK_MSG_ID_213_LEN 2
Definition at line 12 of file mavlink_msg_gimbal_request_axis_calibration.h.
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION 213
Definition at line 3 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_pack(), and mavlink_msg_gimbal_request_axis_calibration_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_CRC 14
Definition at line 14 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_pack(), and mavlink_msg_gimbal_request_axis_calibration_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_REQUEST_AXIS_CALIBRATION_LEN 2
Definition at line 11 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_decode(), mavlink_msg_gimbal_request_axis_calibration_pack(), and mavlink_msg_gimbal_request_axis_calibration_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_request_axis_calibration_t mavlink_gimbal_request_axis_calibration_t
Function Documentation
static void mavlink_msg_gimbal_request_axis_calibration_decode (const mavlink_message_t * msg, mavlink_gimbal_request_axis_calibration_t * gimbal_request_axis_calibration) inline static
Decode a gimbal_request_axis_calibration message into a struct.
Parameters
msg The message to decode
gimbal_request_axis_calibration C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_test_gimbal_request_axis_calibration().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_request_axis_calibration_t * gimbal_request_axis_calibration) inline static
Encode a gimbal_request_axis_calibration struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_request_axis_calibration C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_test_gimbal_request_axis_calibration().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_request_axis_calibration_t * gimbal_request_axis_calibration) inline static
Encode a gimbal_request_axis_calibration struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_request_axis_calibration C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_gimbal_request_axis_calibration.h.
static uint8_t mavlink_msg_gimbal_request_axis_calibration_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gimbal_request_axis_calibration message.
Returns
Component ID
Definition at line 214 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_decode().
static uint8_t mavlink_msg_gimbal_request_axis_calibration_get_target_system (const mavlink_message_t * msg) inline static
Send a gimbal_request_axis_calibration message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID Get field target_system from gimbal_request_axis_calibration message
Returns
System ID
Definition at line 204 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_decode().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a gimbal_request_axis_calibration message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_encode(), and mavlink_test_gimbal_request_axis_calibration().
static uint16_t mavlink_msg_gimbal_request_axis_calibration_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component) inline static
Pack a gimbal_request_axis_calibration message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_gimbal_request_axis_calibration.h.
Referenced by mavlink_msg_gimbal_request_axis_calibration_encode_chan(), and mavlink_test_gimbal_request_axis_calibration().