APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_fence_status.h File Reference
mavlink_msg_fence_status.h File Reference
Classes
struct __mavlink_fence_status_t
Macros
#define MAVLINK_MSG_ID_FENCE_STATUS 162
#define MAVLINK_MSG_ID_FENCE_STATUS_LEN 8
#define MAVLINK_MSG_ID_162_LEN 8
#define MAVLINK_MSG_ID_FENCE_STATUS_CRC 189
#define MAVLINK_MSG_ID_162_CRC 189
#define MAVLINK_MESSAGE_INFO_FENCE_STATUS
Typedefs
typedef struct __mavlink_fence_status_t mavlink_fence_status_t
Functions
static uint16_t mavlink_msg_fence_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t breach_status, uint16_t breach_count, uint8_t breach_type, uint32_t breach_time)
Pack a fence_status message.
static uint16_t mavlink_msg_fence_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t breach_status, uint16_t breach_count, uint8_t breach_type, uint32_t breach_time)
Pack a fence_status message on a channel.
static uint16_t mavlink_msg_fence_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_fence_status_t *fence_status)
Encode a fence_status struct.
static uint16_t mavlink_msg_fence_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_fence_status_t *fence_status)
Encode a fence_status struct on a channel.
static uint8_t mavlink_msg_fence_status_get_breach_status (const mavlink_message_t *msg)
Send a fence_status message.
static uint16_t mavlink_msg_fence_status_get_breach_count (const mavlink_message_t *msg)
Get field breach_count from fence_status message.
static uint8_t mavlink_msg_fence_status_get_breach_type (const mavlink_message_t *msg)
Get field breach_type from fence_status message.
static uint32_t mavlink_msg_fence_status_get_breach_time (const mavlink_message_t *msg)
Get field breach_time from fence_status message.
static void mavlink_msg_fence_status_decode (const mavlink_message_t *msg, mavlink_fence_status_t *fence_status)
Decode a fence_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_FENCE_STATUS
Value:
{ \
    "FENCE_STATUS", \
    4, \
    {  { "breach_time", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_fence_status_t, breach_time) }, \
         { "breach_count", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_fence_status_t, breach_count) }, \
         { "breach_status", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_fence_status_t, breach_status) }, \
         { "breach_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_fence_status_t, breach_type) }, \
         } \
}
Definition at line 21 of file mavlink_msg_fence_status.h.
#define MAVLINK_MSG_ID_162_CRC 189
Definition at line 17 of file mavlink_msg_fence_status.h.
#define MAVLINK_MSG_ID_162_LEN 8
Definition at line 14 of file mavlink_msg_fence_status.h.
#define MAVLINK_MSG_ID_FENCE_STATUS 162
Definition at line 3 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_pack(), and mavlink_msg_fence_status_pack_chan().
#define MAVLINK_MSG_ID_FENCE_STATUS_CRC 189
Definition at line 16 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_pack(), and mavlink_msg_fence_status_pack_chan().
#define MAVLINK_MSG_ID_FENCE_STATUS_LEN 8
Definition at line 13 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_decode(), mavlink_msg_fence_status_pack(), and mavlink_msg_fence_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_fence_status_t mavlink_fence_status_t
Function Documentation
static void mavlink_msg_fence_status_decode (const mavlink_message_t * msg, mavlink_fence_status_t * fence_status) inline static
Decode a fence_status message into a struct.
Parameters
msg The message to decode
fence_status C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_fence_status.h.
Referenced by mavlink_test_fence_status().
static uint16_t mavlink_msg_fence_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_fence_status_t * fence_status) inline static
Encode a fence_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
fence_status C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_fence_status.h.
Referenced by mavlink_test_fence_status().
static uint16_t mavlink_msg_fence_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_fence_status_t * fence_status) inline static
Encode a fence_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
fence_status C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_fence_status.h.
static uint16_t mavlink_msg_fence_status_get_breach_count (const mavlink_message_t * msg) inline static
Get field breach_count from fence_status message.
Returns
number of fence breaches
Definition at line 240 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_decode().
static uint8_t mavlink_msg_fence_status_get_breach_status (const mavlink_message_t * msg) inline static
Send a fence_status message.
Parameters
chan MAVLink channel to send the message
breach_status 0 if currently inside fence, 1 if outside
breach_count number of fence breaches
breach_type last breach type (see FENCE_BREACH_* enum)
breach_time time of last breach in milliseconds since boot Get field breach_status from fence_status message
Returns
0 if currently inside fence, 1 if outside
Definition at line 230 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_decode().
static uint32_t mavlink_msg_fence_status_get_breach_time (const mavlink_message_t * msg) inline static
Get field breach_time from fence_status message.
Returns
time of last breach in milliseconds since boot
Definition at line 260 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_decode().
static uint8_t mavlink_msg_fence_status_get_breach_type (const mavlink_message_t * msg) inline static
Get field breach_type from fence_status message.
Returns
last breach type (see FENCE_BREACH_* enum)
Definition at line 250 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_decode().
static uint16_t mavlink_msg_fence_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t breach_status, uint16_t breach_count, uint8_t breach_type, uint32_t breach_time) inline static
Pack a fence_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
breach_status 0 if currently inside fence, 1 if outside
breach_count number of fence breaches
breach_type last breach type (see FENCE_BREACH_* enum)
breach_time time of last breach in milliseconds since boot
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_encode(), and mavlink_test_fence_status().
static uint16_t mavlink_msg_fence_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t breach_status, uint16_t breach_count, uint8_t breach_type, uint32_t breach_time) inline static
Pack a fence_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
breach_status 0 if currently inside fence, 1 if outside
breach_count number of fence breaches
breach_type last breach type (see FENCE_BREACH_* enum)
breach_time time of last breach in milliseconds since boot
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_fence_status.h.
Referenced by mavlink_msg_fence_status_encode_chan(), and mavlink_test_fence_status().