APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_mount_status.h File Reference
mavlink_msg_mount_status.h File Reference
Classes
struct __mavlink_mount_status_t
Macros
#define MAVLINK_MSG_ID_MOUNT_STATUS 158
#define MAVLINK_MSG_ID_MOUNT_STATUS_LEN 14
#define MAVLINK_MSG_ID_158_LEN 14
#define MAVLINK_MSG_ID_MOUNT_STATUS_CRC 134
#define MAVLINK_MSG_ID_158_CRC 134
#define MAVLINK_MESSAGE_INFO_MOUNT_STATUS
Typedefs
typedef struct __mavlink_mount_status_t mavlink_mount_status_t
Functions
static uint16_t mavlink_msg_mount_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int32_t pointing_a, int32_t pointing_b, int32_t pointing_c)
Pack a mount_status message.
static uint16_t mavlink_msg_mount_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int32_t pointing_a, int32_t pointing_b, int32_t pointing_c)
Pack a mount_status message on a channel.
static uint16_t mavlink_msg_mount_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mount_status_t *mount_status)
Encode a mount_status struct.
static uint16_t mavlink_msg_mount_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mount_status_t *mount_status)
Encode a mount_status struct on a channel.
static uint8_t mavlink_msg_mount_status_get_target_system (const mavlink_message_t *msg)
Send a mount_status message.
static uint8_t mavlink_msg_mount_status_get_target_component (const mavlink_message_t *msg)
Get field target_component from mount_status message.
static int32_t mavlink_msg_mount_status_get_pointing_a (const mavlink_message_t *msg)
Get field pointing_a from mount_status message.
static int32_t mavlink_msg_mount_status_get_pointing_b (const mavlink_message_t *msg)
Get field pointing_b from mount_status message.
static int32_t mavlink_msg_mount_status_get_pointing_c (const mavlink_message_t *msg)
Get field pointing_c from mount_status message.
static void mavlink_msg_mount_status_decode (const mavlink_message_t *msg, mavlink_mount_status_t *mount_status)
Decode a mount_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MOUNT_STATUS
Value:
{ \
    "MOUNT_STATUS", \
    5, \
    {  { "pointing_a", NULL, MAVLINK_TYPE_INT32_T, 0, 0, offsetof(mavlink_mount_status_t, pointing_a) }, \
         { "pointing_b", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_mount_status_t, pointing_b) }, \
         { "pointing_c", NULL, MAVLINK_TYPE_INT32_T, 0, 8, offsetof(mavlink_mount_status_t, pointing_c) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 12, offsetof(mavlink_mount_status_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 13, offsetof(mavlink_mount_status_t, target_component) }, \
         } \
}
Definition at line 22 of file mavlink_msg_mount_status.h.
#define MAVLINK_MSG_ID_158_CRC 134
Definition at line 18 of file mavlink_msg_mount_status.h.
#define MAVLINK_MSG_ID_158_LEN 14
Definition at line 15 of file mavlink_msg_mount_status.h.
#define MAVLINK_MSG_ID_MOUNT_STATUS 158
Definition at line 3 of file mavlink_msg_mount_status.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_mount_status_pack(), and mavlink_msg_mount_status_pack_chan().
#define MAVLINK_MSG_ID_MOUNT_STATUS_CRC 134
Definition at line 17 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_pack(), and mavlink_msg_mount_status_pack_chan().
#define MAVLINK_MSG_ID_MOUNT_STATUS_LEN 14
Definition at line 14 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_decode(), mavlink_msg_mount_status_pack(), and mavlink_msg_mount_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_mount_status_t mavlink_mount_status_t
Function Documentation
static void mavlink_msg_mount_status_decode (const mavlink_message_t * msg, mavlink_mount_status_t * mount_status) inline static
Decode a mount_status message into a struct.
Parameters
msg The message to decode
mount_status C-struct to decode the message contents into
Definition at line 294 of file mavlink_msg_mount_status.h.
Referenced by mavlink_test_mount_status().
static uint16_t mavlink_msg_mount_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mount_status_t * mount_status) inline static
Encode a mount_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mount_status C-struct to read the message contents from
Definition at line 131 of file mavlink_msg_mount_status.h.
Referenced by mavlink_test_mount_status().
static uint16_t mavlink_msg_mount_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mount_status_t * mount_status) inline static
Encode a mount_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mount_status C-struct to read the message contents from
Definition at line 145 of file mavlink_msg_mount_status.h.
static int32_t mavlink_msg_mount_status_get_pointing_a (const mavlink_message_t * msg) inline static
Get field pointing_a from mount_status message.
Returns
pitch(deg*100)
Definition at line 263 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_decode().
static int32_t mavlink_msg_mount_status_get_pointing_b (const mavlink_message_t * msg) inline static
Get field pointing_b from mount_status message.
Returns
roll(deg*100)
Definition at line 273 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_decode().
static int32_t mavlink_msg_mount_status_get_pointing_c (const mavlink_message_t * msg) inline static
Get field pointing_c from mount_status message.
Returns
yaw(deg*100)
Definition at line 283 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_decode().
static uint8_t mavlink_msg_mount_status_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from mount_status message.
Returns
Component ID
Definition at line 253 of file mavlink_msg_mount_status.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mount_status_decode().
static uint8_t mavlink_msg_mount_status_get_target_system (const mavlink_message_t * msg) inline static
Send a mount_status message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
pointing_a pitch(deg*100)
pointing_b roll(deg*100)
pointing_c yaw(deg*100) Get field target_system from mount_status message
Returns
System ID
Definition at line 243 of file mavlink_msg_mount_status.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_mount_status_decode().
static uint16_t mavlink_msg_mount_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int32_t pointing_a, int32_t pointing_b, int32_t pointing_c) inline static
Pack a mount_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
pointing_a pitch(deg*100)
pointing_b roll(deg*100)
pointing_c yaw(deg*100)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_encode(), and mavlink_test_mount_status().
static uint16_t mavlink_msg_mount_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int32_t pointing_a, int32_t pointing_b, int32_t pointing_c) inline static
Pack a mount_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
pointing_a pitch(deg*100)
pointing_b roll(deg*100)
pointing_c yaw(deg*100)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 91 of file mavlink_msg_mount_status.h.
Referenced by mavlink_msg_mount_status_encode_chan(), and mavlink_test_mount_status().