APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_vfr_hud.h File Reference
mavlink_msg_vfr_hud.h File Reference
Classes
struct __mavlink_vfr_hud_t
Macros
#define MAVLINK_MSG_ID_VFR_HUD 74
#define MAVLINK_MSG_ID_VFR_HUD_LEN 20
#define MAVLINK_MSG_ID_74_LEN 20
#define MAVLINK_MSG_ID_VFR_HUD_CRC 20
#define MAVLINK_MSG_ID_74_CRC 20
#define MAVLINK_MESSAGE_INFO_VFR_HUD
Typedefs
typedef struct __mavlink_vfr_hud_t mavlink_vfr_hud_t
Functions
static uint16_t mavlink_msg_vfr_hud_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float airspeed, float groundspeed, int16_t heading, uint16_t throttle, float alt, float climb)
Pack a vfr_hud message.
static uint16_t mavlink_msg_vfr_hud_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float airspeed, float groundspeed, int16_t heading, uint16_t throttle, float alt, float climb)
Pack a vfr_hud message on a channel.
static uint16_t mavlink_msg_vfr_hud_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_vfr_hud_t *vfr_hud)
Encode a vfr_hud struct.
static uint16_t mavlink_msg_vfr_hud_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_vfr_hud_t *vfr_hud)
Encode a vfr_hud struct on a channel.
static float mavlink_msg_vfr_hud_get_airspeed (const mavlink_message_t *msg)
Send a vfr_hud message.
static float mavlink_msg_vfr_hud_get_groundspeed (const mavlink_message_t *msg)
Get field groundspeed from vfr_hud message.
static int16_t mavlink_msg_vfr_hud_get_heading (const mavlink_message_t *msg)
Get field heading from vfr_hud message.
static uint16_t mavlink_msg_vfr_hud_get_throttle (const mavlink_message_t *msg)
Get field throttle from vfr_hud message.
static float mavlink_msg_vfr_hud_get_alt (const mavlink_message_t *msg)
Get field alt from vfr_hud message.
static float mavlink_msg_vfr_hud_get_climb (const mavlink_message_t *msg)
Get field climb from vfr_hud message.
static void mavlink_msg_vfr_hud_decode (const mavlink_message_t *msg, mavlink_vfr_hud_t *vfr_hud)
Decode a vfr_hud message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_VFR_HUD
Value:
{ \
    "VFR_HUD", \
    6, \
    {  { "airspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_vfr_hud_t, airspeed) }, \
         { "groundspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_vfr_hud_t, groundspeed) }, \
         { "alt", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_vfr_hud_t, alt) }, \
         { "climb", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_vfr_hud_t, climb) }, \
         { "heading", NULL, MAVLINK_TYPE_INT16_T, 0, 16, offsetof(mavlink_vfr_hud_t, heading) }, \
         { "throttle", NULL, MAVLINK_TYPE_UINT16_T, 0, 18, offsetof(mavlink_vfr_hud_t, throttle) }, \
         } \
}
Definition at line 23 of file mavlink_msg_vfr_hud.h.
#define MAVLINK_MSG_ID_74_CRC 20
Definition at line 19 of file mavlink_msg_vfr_hud.h.
#define MAVLINK_MSG_ID_74_LEN 20
Definition at line 16 of file mavlink_msg_vfr_hud.h.
#define MAVLINK_MSG_ID_VFR_HUD 74
Definition at line 3 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_pack(), and mavlink_msg_vfr_hud_pack_chan().
#define MAVLINK_MSG_ID_VFR_HUD_CRC 20
Definition at line 18 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_pack(), and mavlink_msg_vfr_hud_pack_chan().
#define MAVLINK_MSG_ID_VFR_HUD_LEN 20
Definition at line 15 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode(), mavlink_msg_vfr_hud_pack(), and mavlink_msg_vfr_hud_pack_chan().
Typedef Documentation
typedef struct __mavlink_vfr_hud_t mavlink_vfr_hud_t
Function Documentation
static void mavlink_msg_vfr_hud_decode (const mavlink_message_t * msg, mavlink_vfr_hud_t * vfr_hud) inline static
Decode a vfr_hud message into a struct.
Parameters
msg The message to decode
vfr_hud C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_test_vfr_hud().
static uint16_t mavlink_msg_vfr_hud_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_vfr_hud_t * vfr_hud) inline static
Encode a vfr_hud struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
vfr_hud C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_test_vfr_hud().
static uint16_t mavlink_msg_vfr_hud_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_vfr_hud_t * vfr_hud) inline static
Encode a vfr_hud struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
vfr_hud C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_vfr_hud.h.
static float mavlink_msg_vfr_hud_get_airspeed (const mavlink_message_t * msg) inline static
Send a vfr_hud message.
Parameters
chan MAVLink channel to send the message
airspeed Current airspeed in m/s
groundspeed Current ground speed in m/s
heading Current heading in degrees, in compass units (0..360, 0=north)
throttle Current throttle setting in integer percent, 0 to 100
alt Current altitude (MSL), in meters
climb Current climb rate in meters/second Get field airspeed from vfr_hud message
Returns
Current airspeed in m/s
Definition at line 256 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode().
static float mavlink_msg_vfr_hud_get_alt (const mavlink_message_t * msg) inline static
Get field alt from vfr_hud message.
Returns
Current altitude (MSL), in meters
Definition at line 296 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode().
static float mavlink_msg_vfr_hud_get_climb (const mavlink_message_t * msg) inline static
Get field climb from vfr_hud message.
Returns
Current climb rate in meters/second
Definition at line 306 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode().
static float mavlink_msg_vfr_hud_get_groundspeed (const mavlink_message_t * msg) inline static
Get field groundspeed from vfr_hud message.
Returns
Current ground speed in m/s
Definition at line 266 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode().
static int16_t mavlink_msg_vfr_hud_get_heading (const mavlink_message_t * msg) inline static
Get field heading from vfr_hud message.
Returns
Current heading in degrees, in compass units (0..360, 0=north)
Definition at line 276 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode().
static uint16_t mavlink_msg_vfr_hud_get_throttle (const mavlink_message_t * msg) inline static
Get field throttle from vfr_hud message.
Returns
Current throttle setting in integer percent, 0 to 100
Definition at line 286 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_decode().
static uint16_t mavlink_msg_vfr_hud_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float airspeed, float groundspeed, int16_t heading, uint16_t throttle, float alt, float climb) inline static
Pack a vfr_hud message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
airspeed Current airspeed in m/s
groundspeed Current ground speed in m/s
heading Current heading in degrees, in compass units (0..360, 0=north)
throttle Current throttle setting in integer percent, 0 to 100
alt Current altitude (MSL), in meters
climb Current climb rate in meters/second
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_encode(), and mavlink_test_vfr_hud().
static uint16_t mavlink_msg_vfr_hud_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float airspeed, float groundspeed, int16_t heading, uint16_t throttle, float alt, float climb) inline static
Pack a vfr_hud message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
airspeed Current airspeed in m/s
groundspeed Current ground speed in m/s
heading Current heading in degrees, in compass units (0..360, 0=north)
throttle Current throttle setting in integer percent, 0 to 100
alt Current altitude (MSL), in meters
climb Current climb rate in meters/second
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_vfr_hud.h.
Referenced by mavlink_msg_vfr_hud_encode_chan(), and mavlink_test_vfr_hud().