APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_log_request_list.h File Reference
mavlink_msg_log_request_list.h File Reference
Classes
struct __mavlink_log_request_list_t
Macros
#define MAVLINK_MSG_ID_LOG_REQUEST_LIST 117
#define MAVLINK_MSG_ID_LOG_REQUEST_LIST_LEN 6
#define MAVLINK_MSG_ID_117_LEN 6
#define MAVLINK_MSG_ID_LOG_REQUEST_LIST_CRC 128
#define MAVLINK_MSG_ID_117_CRC 128
#define MAVLINK_MESSAGE_INFO_LOG_REQUEST_LIST
Typedefs
typedef struct __mavlink_log_request_list_t mavlink_log_request_list_t
Functions
static uint16_t mavlink_msg_log_request_list_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t start, uint16_t end)
Pack a log_request_list message.
static uint16_t mavlink_msg_log_request_list_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t start, uint16_t end)
Pack a log_request_list message on a channel.
static uint16_t mavlink_msg_log_request_list_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_log_request_list_t *log_request_list)
Encode a log_request_list struct.
static uint16_t mavlink_msg_log_request_list_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_log_request_list_t *log_request_list)
Encode a log_request_list struct on a channel.
static uint8_t mavlink_msg_log_request_list_get_target_system (const mavlink_message_t *msg)
Send a log_request_list message.
static uint8_t mavlink_msg_log_request_list_get_target_component (const mavlink_message_t *msg)
Get field target_component from log_request_list message.
static uint16_t mavlink_msg_log_request_list_get_start (const mavlink_message_t *msg)
Get field start from log_request_list message.
static uint16_t mavlink_msg_log_request_list_get_end (const mavlink_message_t *msg)
Get field end from log_request_list message.
static void mavlink_msg_log_request_list_decode (const mavlink_message_t *msg, mavlink_log_request_list_t *log_request_list)
Decode a log_request_list message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOG_REQUEST_LIST
Value:
{ \
    "LOG_REQUEST_LIST", \
    4, \
    {  { "start", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_log_request_list_t, start) }, \
         { "end", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_log_request_list_t, end) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_log_request_list_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_log_request_list_t, target_component) }, \
         } \
}
Definition at line 21 of file mavlink_msg_log_request_list.h.
#define MAVLINK_MSG_ID_117_CRC 128
Definition at line 17 of file mavlink_msg_log_request_list.h.
#define MAVLINK_MSG_ID_117_LEN 6
Definition at line 14 of file mavlink_msg_log_request_list.h.
#define MAVLINK_MSG_ID_LOG_REQUEST_LIST 117
Definition at line 3 of file mavlink_msg_log_request_list.h.
Referenced by MAVLink_routing::get_targets(), GCS_MAVLINK::handle_log_message(), mavlink_msg_log_request_list_pack(), and mavlink_msg_log_request_list_pack_chan().
#define MAVLINK_MSG_ID_LOG_REQUEST_LIST_CRC 128
Definition at line 16 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_msg_log_request_list_pack(), and mavlink_msg_log_request_list_pack_chan().
#define MAVLINK_MSG_ID_LOG_REQUEST_LIST_LEN 6
Definition at line 13 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_msg_log_request_list_decode(), mavlink_msg_log_request_list_pack(), and mavlink_msg_log_request_list_pack_chan().
Typedef Documentation
typedef struct __mavlink_log_request_list_t mavlink_log_request_list_t
Function Documentation
static void mavlink_msg_log_request_list_decode (const mavlink_message_t * msg, mavlink_log_request_list_t * log_request_list) inline static
Decode a log_request_list message into a struct.
Parameters
msg The message to decode
log_request_list C-struct to decode the message contents into
Definition at line 271 of file mavlink_msg_log_request_list.h.
Referenced by GCS_MAVLINK::handle_log_request_list(), and mavlink_test_log_request_list().
static uint16_t mavlink_msg_log_request_list_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_log_request_list_t * log_request_list) inline static
Encode a log_request_list struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
log_request_list C-struct to read the message contents from
Definition at line 123 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_test_log_request_list().
static uint16_t mavlink_msg_log_request_list_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_log_request_list_t * log_request_list) inline static
Encode a log_request_list struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
log_request_list C-struct to read the message contents from
Definition at line 137 of file mavlink_msg_log_request_list.h.
static uint16_t mavlink_msg_log_request_list_get_end (const mavlink_message_t * msg) inline static
Get field end from log_request_list message.
Returns
Last log id (0xffff for last available)
Definition at line 260 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_msg_log_request_list_decode().
static uint16_t mavlink_msg_log_request_list_get_start (const mavlink_message_t * msg) inline static
Get field start from log_request_list message.
Returns
First log id (0 for first available)
Definition at line 250 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_msg_log_request_list_decode().
static uint8_t mavlink_msg_log_request_list_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from log_request_list message.
Returns
Component ID
Definition at line 240 of file mavlink_msg_log_request_list.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_log_request_list_decode().
static uint8_t mavlink_msg_log_request_list_get_target_system (const mavlink_message_t * msg) inline static
Send a log_request_list message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
start First log id (0 for first available)
end Last log id (0xffff for last available) Get field target_system from log_request_list message
Returns
System ID
Definition at line 230 of file mavlink_msg_log_request_list.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_log_request_list_decode().
static uint16_t mavlink_msg_log_request_list_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t start, uint16_t end) inline static
Pack a log_request_list message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
start First log id (0 for first available)
end Last log id (0xffff for last available)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_msg_log_request_list_encode(), and mavlink_test_log_request_list().
static uint16_t mavlink_msg_log_request_list_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t start, uint16_t end) inline static
Pack a log_request_list message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
start First log id (0 for first available)
end Last log id (0xffff for last available)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 85 of file mavlink_msg_log_request_list.h.
Referenced by mavlink_msg_log_request_list_encode_chan(), and mavlink_test_log_request_list().