APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_rally_point.h File Reference
mavlink_msg_rally_point.h File Reference
Classes
struct __mavlink_rally_point_t
Macros
#define MAVLINK_MSG_ID_RALLY_POINT 175
#define MAVLINK_MSG_ID_RALLY_POINT_LEN 19
#define MAVLINK_MSG_ID_175_LEN 19
#define MAVLINK_MSG_ID_RALLY_POINT_CRC 138
#define MAVLINK_MSG_ID_175_CRC 138
#define MAVLINK_MESSAGE_INFO_RALLY_POINT
Typedefs
typedef struct __mavlink_rally_point_t mavlink_rally_point_t
Functions
static uint16_t mavlink_msg_rally_point_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, int32_t lat, int32_t lng, int16_t alt, int16_t break_alt, uint16_t land_dir, uint8_t flags)
Pack a rally_point message.
static uint16_t mavlink_msg_rally_point_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, int32_t lat, int32_t lng, int16_t alt, int16_t break_alt, uint16_t land_dir, uint8_t flags)
Pack a rally_point message on a channel.
static uint16_t mavlink_msg_rally_point_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rally_point_t *rally_point)
Encode a rally_point struct.
static uint16_t mavlink_msg_rally_point_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_rally_point_t *rally_point)
Encode a rally_point struct on a channel.
static uint8_t mavlink_msg_rally_point_get_target_system (const mavlink_message_t *msg)
Send a rally_point message.
static uint8_t mavlink_msg_rally_point_get_target_component (const mavlink_message_t *msg)
Get field target_component from rally_point message.
static uint8_t mavlink_msg_rally_point_get_idx (const mavlink_message_t *msg)
Get field idx from rally_point message.
static uint8_t mavlink_msg_rally_point_get_count (const mavlink_message_t *msg)
Get field count from rally_point message.
static int32_t mavlink_msg_rally_point_get_lat (const mavlink_message_t *msg)
Get field lat from rally_point message.
static int32_t mavlink_msg_rally_point_get_lng (const mavlink_message_t *msg)
Get field lng from rally_point message.
static int16_t mavlink_msg_rally_point_get_alt (const mavlink_message_t *msg)
Get field alt from rally_point message.
static int16_t mavlink_msg_rally_point_get_break_alt (const mavlink_message_t *msg)
Get field break_alt from rally_point message.
static uint16_t mavlink_msg_rally_point_get_land_dir (const mavlink_message_t *msg)
Get field land_dir from rally_point message.
static uint8_t mavlink_msg_rally_point_get_flags (const mavlink_message_t *msg)
Get field flags from rally_point message.
static void mavlink_msg_rally_point_decode (const mavlink_message_t *msg, mavlink_rally_point_t *rally_point)
Decode a rally_point message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RALLY_POINT
Value:
{ \
    "RALLY_POINT", \
    10, \
    {  { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 0, offsetof(mavlink_rally_point_t, lat) }, \
         { "lng", NULL, MAVLINK_TYPE_INT32_T, 0, 4, offsetof(mavlink_rally_point_t, lng) }, \
         { "alt", NULL, MAVLINK_TYPE_INT16_T, 0, 8, offsetof(mavlink_rally_point_t, alt) }, \
         { "break_alt", NULL, MAVLINK_TYPE_INT16_T, 0, 10, offsetof(mavlink_rally_point_t, break_alt) }, \
         { "land_dir", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_rally_point_t, land_dir) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 14, offsetof(mavlink_rally_point_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 15, offsetof(mavlink_rally_point_t, target_component) }, \
         { "idx", NULL, MAVLINK_TYPE_UINT8_T, 0, 16, offsetof(mavlink_rally_point_t, idx) }, \
         { "count", NULL, MAVLINK_TYPE_UINT8_T, 0, 17, offsetof(mavlink_rally_point_t, count) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT8_T, 0, 18, offsetof(mavlink_rally_point_t, flags) }, \
         } \
}
Definition at line 27 of file mavlink_msg_rally_point.h.
#define MAVLINK_MSG_ID_175_CRC 138
Definition at line 23 of file mavlink_msg_rally_point.h.
#define MAVLINK_MSG_ID_175_LEN 19
Definition at line 20 of file mavlink_msg_rally_point.h.
#define MAVLINK_MSG_ID_RALLY_POINT 175
Definition at line 3 of file mavlink_msg_rally_point.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_rally_point_pack(), and mavlink_msg_rally_point_pack_chan().
#define MAVLINK_MSG_ID_RALLY_POINT_CRC 138
Definition at line 22 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_pack(), and mavlink_msg_rally_point_pack_chan().
#define MAVLINK_MSG_ID_RALLY_POINT_LEN 19
Definition at line 19 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode(), mavlink_msg_rally_point_pack(), and mavlink_msg_rally_point_pack_chan().
Typedef Documentation
typedef struct __mavlink_rally_point_t mavlink_rally_point_t
Function Documentation
static void mavlink_msg_rally_point_decode (const mavlink_message_t * msg, mavlink_rally_point_t * rally_point) inline static
Decode a rally_point message into a struct.
Parameters
msg The message to decode
rally_point C-struct to decode the message contents into
Definition at line 409 of file mavlink_msg_rally_point.h.
Referenced by mavlink_test_rally_point().
static uint16_t mavlink_msg_rally_point_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rally_point_t * rally_point) inline static
Encode a rally_point struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rally_point C-struct to read the message contents from
Definition at line 171 of file mavlink_msg_rally_point.h.
Referenced by mavlink_test_rally_point().
static uint16_t mavlink_msg_rally_point_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_rally_point_t * rally_point) inline static
Encode a rally_point struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rally_point C-struct to read the message contents from
Definition at line 185 of file mavlink_msg_rally_point.h.
static int16_t mavlink_msg_rally_point_get_alt (const mavlink_message_t * msg) inline static
Get field alt from rally_point message.
Returns
Transit / loiter altitude in meters relative to home
Definition at line 368 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static int16_t mavlink_msg_rally_point_get_break_alt (const mavlink_message_t * msg) inline static
Get field break_alt from rally_point message.
Returns
Break altitude in meters relative to home
Definition at line 378 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static uint8_t mavlink_msg_rally_point_get_count (const mavlink_message_t * msg) inline static
Get field count from rally_point message.
Returns
total number of points (for sanity checking)
Definition at line 338 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static uint8_t mavlink_msg_rally_point_get_flags (const mavlink_message_t * msg) inline static
Get field flags from rally_point message.
Returns
See RALLY_FLAGS enum for definition of the bitmask.
Definition at line 398 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static uint8_t mavlink_msg_rally_point_get_idx (const mavlink_message_t * msg) inline static
Get field idx from rally_point message.
Returns
point index (first point is 0)
Definition at line 328 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static uint16_t mavlink_msg_rally_point_get_land_dir (const mavlink_message_t * msg) inline static
Get field land_dir from rally_point message.
Returns
Heading to aim for when landing. In centi-degrees.
Definition at line 388 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static int32_t mavlink_msg_rally_point_get_lat (const mavlink_message_t * msg) inline static
Get field lat from rally_point message.
Returns
Latitude of point in degrees * 1E7
Definition at line 348 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static int32_t mavlink_msg_rally_point_get_lng (const mavlink_message_t * msg) inline static
Get field lng from rally_point message.
Returns
Longitude of point in degrees * 1E7
Definition at line 358 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_decode().
static uint8_t mavlink_msg_rally_point_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from rally_point message.
Returns
Component ID
Definition at line 318 of file mavlink_msg_rally_point.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_rally_point_decode().
static uint8_t mavlink_msg_rally_point_get_target_system (const mavlink_message_t * msg) inline static
Send a rally_point message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
idx point index (first point is 0)
count total number of points (for sanity checking)
lat Latitude of point in degrees * 1E7
lng Longitude of point in degrees * 1E7
alt Transit / loiter altitude in meters relative to home
break_alt Break altitude in meters relative to home
land_dir Heading to aim for when landing. In centi-degrees.
flags See RALLY_FLAGS enum for definition of the bitmask. Get field target_system from rally_point message
Returns
System ID
Definition at line 308 of file mavlink_msg_rally_point.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_rally_point_decode().
static uint16_t mavlink_msg_rally_point_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, int32_t lat, int32_t lng, int16_t alt, int16_t break_alt, uint16_t land_dir, uint8_t flags) inline static
Pack a rally_point message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
idx point index (first point is 0)
count total number of points (for sanity checking)
lat Latitude of point in degrees * 1E7
lng Longitude of point in degrees * 1E7
alt Transit / loiter altitude in meters relative to home
break_alt Break altitude in meters relative to home
land_dir Heading to aim for when landing. In centi-degrees.
flags See RALLY_FLAGS enum for definition of the bitmask.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_encode(), and mavlink_test_rally_point().
static uint16_t mavlink_msg_rally_point_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t idx, uint8_t count, int32_t lat, int32_t lng, int16_t alt, int16_t break_alt, uint16_t land_dir, uint8_t flags) inline static
Pack a rally_point message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
idx point index (first point is 0)
count total number of points (for sanity checking)
lat Latitude of point in degrees * 1E7
lng Longitude of point in degrees * 1E7
alt Transit / loiter altitude in meters relative to home
break_alt Break altitude in meters relative to home
land_dir Heading to aim for when landing. In centi-degrees.
flags See RALLY_FLAGS enum for definition of the bitmask.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 121 of file mavlink_msg_rally_point.h.
Referenced by mavlink_msg_rally_point_encode_chan(), and mavlink_test_rally_point().