APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_ap_adc.h File Reference
mavlink_msg_ap_adc.h File Reference
Classes
struct __mavlink_ap_adc_t
Macros
#define MAVLINK_MSG_ID_AP_ADC 153
#define MAVLINK_MSG_ID_AP_ADC_LEN 12
#define MAVLINK_MSG_ID_153_LEN 12
#define MAVLINK_MSG_ID_AP_ADC_CRC 188
#define MAVLINK_MSG_ID_153_CRC 188
#define MAVLINK_MESSAGE_INFO_AP_ADC
Typedefs
typedef struct __mavlink_ap_adc_t mavlink_ap_adc_t
Functions
static uint16_t mavlink_msg_ap_adc_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t adc1, uint16_t adc2, uint16_t adc3, uint16_t adc4, uint16_t adc5, uint16_t adc6)
Pack a ap_adc message.
static uint16_t mavlink_msg_ap_adc_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t adc1, uint16_t adc2, uint16_t adc3, uint16_t adc4, uint16_t adc5, uint16_t adc6)
Pack a ap_adc message on a channel.
static uint16_t mavlink_msg_ap_adc_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_ap_adc_t *ap_adc)
Encode a ap_adc struct.
static uint16_t mavlink_msg_ap_adc_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_ap_adc_t *ap_adc)
Encode a ap_adc struct on a channel.
static uint16_t mavlink_msg_ap_adc_get_adc1 (const mavlink_message_t *msg)
Send a ap_adc message.
static uint16_t mavlink_msg_ap_adc_get_adc2 (const mavlink_message_t *msg)
Get field adc2 from ap_adc message.
static uint16_t mavlink_msg_ap_adc_get_adc3 (const mavlink_message_t *msg)
Get field adc3 from ap_adc message.
static uint16_t mavlink_msg_ap_adc_get_adc4 (const mavlink_message_t *msg)
Get field adc4 from ap_adc message.
static uint16_t mavlink_msg_ap_adc_get_adc5 (const mavlink_message_t *msg)
Get field adc5 from ap_adc message.
static uint16_t mavlink_msg_ap_adc_get_adc6 (const mavlink_message_t *msg)
Get field adc6 from ap_adc message.
static void mavlink_msg_ap_adc_decode (const mavlink_message_t *msg, mavlink_ap_adc_t *ap_adc)
Decode a ap_adc message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_AP_ADC
Value:
{ \
    "AP_ADC", \
    6, \
    {  { "adc1", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_ap_adc_t, adc1) }, \
         { "adc2", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_ap_adc_t, adc2) }, \
         { "adc3", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_ap_adc_t, adc3) }, \
         { "adc4", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_ap_adc_t, adc4) }, \
         { "adc5", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_ap_adc_t, adc5) }, \
         { "adc6", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_ap_adc_t, adc6) }, \
         } \
}
Definition at line 23 of file mavlink_msg_ap_adc.h.
#define MAVLINK_MSG_ID_153_CRC 188
Definition at line 19 of file mavlink_msg_ap_adc.h.
#define MAVLINK_MSG_ID_153_LEN 12
Definition at line 16 of file mavlink_msg_ap_adc.h.
#define MAVLINK_MSG_ID_AP_ADC 153
Definition at line 3 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_pack(), and mavlink_msg_ap_adc_pack_chan().
#define MAVLINK_MSG_ID_AP_ADC_CRC 188
Definition at line 18 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_pack(), and mavlink_msg_ap_adc_pack_chan().
#define MAVLINK_MSG_ID_AP_ADC_LEN 12
Definition at line 15 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode(), mavlink_msg_ap_adc_pack(), and mavlink_msg_ap_adc_pack_chan().
Typedef Documentation
typedef struct __mavlink_ap_adc_t mavlink_ap_adc_t
Function Documentation
static void mavlink_msg_ap_adc_decode (const mavlink_message_t * msg, mavlink_ap_adc_t * ap_adc) inline static
Decode a ap_adc message into a struct.
Parameters
msg The message to decode
ap_adc C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_test_ap_adc().
static uint16_t mavlink_msg_ap_adc_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_ap_adc_t * ap_adc) inline static
Encode a ap_adc struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
ap_adc C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_test_ap_adc().
static uint16_t mavlink_msg_ap_adc_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_ap_adc_t * ap_adc) inline static
Encode a ap_adc struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
ap_adc C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_ap_adc.h.
static uint16_t mavlink_msg_ap_adc_get_adc1 (const mavlink_message_t * msg) inline static
Send a ap_adc message.
Parameters
chan MAVLink channel to send the message
adc1 ADC output 1
adc2 ADC output 2
adc3 ADC output 3
adc4 ADC output 4
adc5 ADC output 5
adc6 ADC output 6 Get field adc1 from ap_adc message
Returns
ADC output 1
Definition at line 256 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode().
static uint16_t mavlink_msg_ap_adc_get_adc2 (const mavlink_message_t * msg) inline static
Get field adc2 from ap_adc message.
Returns
ADC output 2
Definition at line 266 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode().
static uint16_t mavlink_msg_ap_adc_get_adc3 (const mavlink_message_t * msg) inline static
Get field adc3 from ap_adc message.
Returns
ADC output 3
Definition at line 276 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode().
static uint16_t mavlink_msg_ap_adc_get_adc4 (const mavlink_message_t * msg) inline static
Get field adc4 from ap_adc message.
Returns
ADC output 4
Definition at line 286 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode().
static uint16_t mavlink_msg_ap_adc_get_adc5 (const mavlink_message_t * msg) inline static
Get field adc5 from ap_adc message.
Returns
ADC output 5
Definition at line 296 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode().
static uint16_t mavlink_msg_ap_adc_get_adc6 (const mavlink_message_t * msg) inline static
Get field adc6 from ap_adc message.
Returns
ADC output 6
Definition at line 306 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_decode().
static uint16_t mavlink_msg_ap_adc_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t adc1, uint16_t adc2, uint16_t adc3, uint16_t adc4, uint16_t adc5, uint16_t adc6) inline static
Pack a ap_adc message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
adc1 ADC output 1
adc2 ADC output 2
adc3 ADC output 3
adc4 ADC output 4
adc5 ADC output 5
adc6 ADC output 6
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_encode(), and mavlink_test_ap_adc().
static uint16_t mavlink_msg_ap_adc_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t adc1, uint16_t adc2, uint16_t adc3, uint16_t adc4, uint16_t adc5, uint16_t adc6) inline static
Pack a ap_adc message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
adc1 ADC output 1
adc2 ADC output 2
adc3 ADC output 3
adc4 ADC output 4
adc5 ADC output 5
adc6 ADC output 6
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_ap_adc.h.
Referenced by mavlink_msg_ap_adc_encode_chan(), and mavlink_test_ap_adc().