APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_gimbal_factory_parameters_loaded.h File Reference
mavlink_msg_gimbal_factory_parameters_loaded.h File Reference
Classes
struct __mavlink_gimbal_factory_parameters_loaded_t
Macros
#define MAVLINK_MSG_ID_GIMBAL_FACTORY_PARAMETERS_LOADED 207
#define MAVLINK_MSG_ID_GIMBAL_FACTORY_PARAMETERS_LOADED_LEN 1
#define MAVLINK_MSG_ID_207_LEN 1
#define MAVLINK_MSG_ID_GIMBAL_FACTORY_PARAMETERS_LOADED_CRC 201
#define MAVLINK_MSG_ID_207_CRC 201
#define MAVLINK_MESSAGE_INFO_GIMBAL_FACTORY_PARAMETERS_LOADED
Typedefs
typedef struct __mavlink_gimbal_factory_parameters_loaded_t mavlink_gimbal_factory_parameters_loaded_t
Functions
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t dummy)
Pack a gimbal_factory_parameters_loaded message.
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t dummy)
Pack a gimbal_factory_parameters_loaded message on a channel.
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gimbal_factory_parameters_loaded_t *gimbal_factory_parameters_loaded)
Encode a gimbal_factory_parameters_loaded struct.
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_gimbal_factory_parameters_loaded_t *gimbal_factory_parameters_loaded)
Encode a gimbal_factory_parameters_loaded struct on a channel.
static uint8_t mavlink_msg_gimbal_factory_parameters_loaded_get_dummy (const mavlink_message_t *msg)
Send a gimbal_factory_parameters_loaded message.
static void mavlink_msg_gimbal_factory_parameters_loaded_decode (const mavlink_message_t *msg, mavlink_gimbal_factory_parameters_loaded_t *gimbal_factory_parameters_loaded)
Decode a gimbal_factory_parameters_loaded message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GIMBAL_FACTORY_PARAMETERS_LOADED
Value:
{ \
    "GIMBAL_FACTORY_PARAMETERS_LOADED", \
    1, \
    {  { "dummy", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gimbal_factory_parameters_loaded_t, dummy) }, \
         } \
}
Definition at line 18 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
#define MAVLINK_MSG_ID_207_CRC 201
Definition at line 14 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
#define MAVLINK_MSG_ID_207_LEN 1
Definition at line 11 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
#define MAVLINK_MSG_ID_GIMBAL_FACTORY_PARAMETERS_LOADED 207
Definition at line 3 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_msg_gimbal_factory_parameters_loaded_pack(), and mavlink_msg_gimbal_factory_parameters_loaded_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_FACTORY_PARAMETERS_LOADED_CRC 201
Definition at line 13 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_msg_gimbal_factory_parameters_loaded_pack(), and mavlink_msg_gimbal_factory_parameters_loaded_pack_chan().
#define MAVLINK_MSG_ID_GIMBAL_FACTORY_PARAMETERS_LOADED_LEN 1
Definition at line 10 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_msg_gimbal_factory_parameters_loaded_decode(), mavlink_msg_gimbal_factory_parameters_loaded_pack(), and mavlink_msg_gimbal_factory_parameters_loaded_pack_chan().
Typedef Documentation
typedef struct __mavlink_gimbal_factory_parameters_loaded_t mavlink_gimbal_factory_parameters_loaded_t
Function Documentation
static void mavlink_msg_gimbal_factory_parameters_loaded_decode (const mavlink_message_t * msg, mavlink_gimbal_factory_parameters_loaded_t * gimbal_factory_parameters_loaded) inline static
Decode a gimbal_factory_parameters_loaded message into a struct.
Parameters
msg The message to decode
gimbal_factory_parameters_loaded C-struct to decode the message contents into
Definition at line 202 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_test_gimbal_factory_parameters_loaded().
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gimbal_factory_parameters_loaded_t * gimbal_factory_parameters_loaded) inline static
Encode a gimbal_factory_parameters_loaded struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gimbal_factory_parameters_loaded C-struct to read the message contents from
Definition at line 99 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_test_gimbal_factory_parameters_loaded().
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_gimbal_factory_parameters_loaded_t * gimbal_factory_parameters_loaded) inline static
Encode a gimbal_factory_parameters_loaded struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
gimbal_factory_parameters_loaded C-struct to read the message contents from
Definition at line 113 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
static uint8_t mavlink_msg_gimbal_factory_parameters_loaded_get_dummy (const mavlink_message_t * msg) inline static
Send a gimbal_factory_parameters_loaded message.
Parameters
chan MAVLink channel to send the message
dummy Dummy field because mavgen doesn't allow messages with no fields Get field dummy from gimbal_factory_parameters_loaded message
Returns
Dummy field because mavgen doesn't allow messages with no fields
Definition at line 191 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_msg_gimbal_factory_parameters_loaded_decode().
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t dummy) inline static
Pack a gimbal_factory_parameters_loaded message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
dummy Dummy field because mavgen doesn't allow messages with no fields
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_msg_gimbal_factory_parameters_loaded_encode(), and mavlink_test_gimbal_factory_parameters_loaded().
static uint16_t mavlink_msg_gimbal_factory_parameters_loaded_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t dummy) inline static
Pack a gimbal_factory_parameters_loaded message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
dummy Dummy field because mavgen doesn't allow messages with no fields
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 67 of file mavlink_msg_gimbal_factory_parameters_loaded.h.
Referenced by mavlink_msg_gimbal_factory_parameters_loaded_encode_chan(), and mavlink_test_gimbal_factory_parameters_loaded().