APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_rangefinder.h File Reference
mavlink_msg_rangefinder.h File Reference
Classes
struct __mavlink_rangefinder_t
Macros
#define MAVLINK_MSG_ID_RANGEFINDER 173
#define MAVLINK_MSG_ID_RANGEFINDER_LEN 8
#define MAVLINK_MSG_ID_173_LEN 8
#define MAVLINK_MSG_ID_RANGEFINDER_CRC 83
#define MAVLINK_MSG_ID_173_CRC 83
#define MAVLINK_MESSAGE_INFO_RANGEFINDER
Typedefs
typedef struct __mavlink_rangefinder_t mavlink_rangefinder_t
Functions
static uint16_t mavlink_msg_rangefinder_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float distance, float voltage)
Pack a rangefinder message.
static uint16_t mavlink_msg_rangefinder_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float distance, float voltage)
Pack a rangefinder message on a channel.
static uint16_t mavlink_msg_rangefinder_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rangefinder_t *rangefinder)
Encode a rangefinder struct.
static uint16_t mavlink_msg_rangefinder_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_rangefinder_t *rangefinder)
Encode a rangefinder struct on a channel.
static float mavlink_msg_rangefinder_get_distance (const mavlink_message_t *msg)
Send a rangefinder message.
static float mavlink_msg_rangefinder_get_voltage (const mavlink_message_t *msg)
Get field voltage from rangefinder message.
static void mavlink_msg_rangefinder_decode (const mavlink_message_t *msg, mavlink_rangefinder_t *rangefinder)
Decode a rangefinder message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RANGEFINDER
Value:
{ \
    "RANGEFINDER", \
    2, \
    {  { "distance", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_rangefinder_t, distance) }, \
         { "voltage", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_rangefinder_t, voltage) }, \
         } \
}
Definition at line 19 of file mavlink_msg_rangefinder.h.
#define MAVLINK_MSG_ID_173_CRC 83
Definition at line 15 of file mavlink_msg_rangefinder.h.
#define MAVLINK_MSG_ID_173_LEN 8
Definition at line 12 of file mavlink_msg_rangefinder.h.
#define MAVLINK_MSG_ID_RANGEFINDER 173
Definition at line 3 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_pack(), and mavlink_msg_rangefinder_pack_chan().
#define MAVLINK_MSG_ID_RANGEFINDER_CRC 83
Definition at line 14 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_pack(), and mavlink_msg_rangefinder_pack_chan().
#define MAVLINK_MSG_ID_RANGEFINDER_LEN 8
Definition at line 11 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_decode(), mavlink_msg_rangefinder_pack(), and mavlink_msg_rangefinder_pack_chan().
Typedef Documentation
typedef struct __mavlink_rangefinder_t mavlink_rangefinder_t
Function Documentation
static void mavlink_msg_rangefinder_decode (const mavlink_message_t * msg, mavlink_rangefinder_t * rangefinder) inline static
Decode a rangefinder message into a struct.
Parameters
msg The message to decode
rangefinder C-struct to decode the message contents into
Definition at line 225 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_test_rangefinder().
static uint16_t mavlink_msg_rangefinder_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rangefinder_t * rangefinder) inline static
Encode a rangefinder struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rangefinder C-struct to read the message contents from
Definition at line 107 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_test_rangefinder().
static uint16_t mavlink_msg_rangefinder_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_rangefinder_t * rangefinder) inline static
Encode a rangefinder struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
rangefinder C-struct to read the message contents from
Definition at line 121 of file mavlink_msg_rangefinder.h.
static float mavlink_msg_rangefinder_get_distance (const mavlink_message_t * msg) inline static
Send a rangefinder message.
Parameters
chan MAVLink channel to send the message
distance distance in meters
voltage raw voltage if available, zero otherwise Get field distance from rangefinder message
Returns
distance in meters
Definition at line 204 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_decode().
static float mavlink_msg_rangefinder_get_voltage (const mavlink_message_t * msg) inline static
Get field voltage from rangefinder message.
Returns
raw voltage if available, zero otherwise
Definition at line 214 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_decode().
static uint16_t mavlink_msg_rangefinder_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float distance, float voltage) inline static
Pack a rangefinder message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
distance distance in meters
voltage raw voltage if available, zero otherwise
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_encode(), and mavlink_test_rangefinder().
static uint16_t mavlink_msg_rangefinder_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float distance, float voltage) inline static
Pack a rangefinder message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
distance distance in meters
voltage raw voltage if available, zero otherwise
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 73 of file mavlink_msg_rangefinder.h.
Referenced by mavlink_msg_rangefinder_encode_chan(), and mavlink_test_rangefinder().