APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_raw_imu.h File Reference
mavlink_msg_raw_imu.h File Reference
Classes
struct __mavlink_raw_imu_t
Macros
#define MAVLINK_MSG_ID_RAW_IMU 27
#define MAVLINK_MSG_ID_RAW_IMU_LEN 26
#define MAVLINK_MSG_ID_27_LEN 26
#define MAVLINK_MSG_ID_RAW_IMU_CRC 144
#define MAVLINK_MSG_ID_27_CRC 144
#define MAVLINK_MESSAGE_INFO_RAW_IMU
Typedefs
typedef struct __mavlink_raw_imu_t mavlink_raw_imu_t
Functions
static uint16_t mavlink_msg_raw_imu_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag)
Pack a raw_imu message.
static uint16_t mavlink_msg_raw_imu_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag)
Pack a raw_imu message on a channel.
static uint16_t mavlink_msg_raw_imu_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_raw_imu_t *raw_imu)
Encode a raw_imu struct.
static uint16_t mavlink_msg_raw_imu_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_raw_imu_t *raw_imu)
Encode a raw_imu struct on a channel.
static uint64_t mavlink_msg_raw_imu_get_time_usec (const mavlink_message_t *msg)
Send a raw_imu message.
static int16_t mavlink_msg_raw_imu_get_xacc (const mavlink_message_t *msg)
Get field xacc from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_yacc (const mavlink_message_t *msg)
Get field yacc from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_zacc (const mavlink_message_t *msg)
Get field zacc from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_xgyro (const mavlink_message_t *msg)
Get field xgyro from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_ygyro (const mavlink_message_t *msg)
Get field ygyro from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_zgyro (const mavlink_message_t *msg)
Get field zgyro from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_xmag (const mavlink_message_t *msg)
Get field xmag from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_ymag (const mavlink_message_t *msg)
Get field ymag from raw_imu message.
static int16_t mavlink_msg_raw_imu_get_zmag (const mavlink_message_t *msg)
Get field zmag from raw_imu message.
static void mavlink_msg_raw_imu_decode (const mavlink_message_t *msg, mavlink_raw_imu_t *raw_imu)
Decode a raw_imu message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RAW_IMU
Value:
{ \
    "RAW_IMU", \
    10, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_raw_imu_t, time_usec) }, \
         { "xacc", NULL, MAVLINK_TYPE_INT16_T, 0, 8, offsetof(mavlink_raw_imu_t, xacc) }, \
         { "yacc", NULL, MAVLINK_TYPE_INT16_T, 0, 10, offsetof(mavlink_raw_imu_t, yacc) }, \
         { "zacc", NULL, MAVLINK_TYPE_INT16_T, 0, 12, offsetof(mavlink_raw_imu_t, zacc) }, \
         { "xgyro", NULL, MAVLINK_TYPE_INT16_T, 0, 14, offsetof(mavlink_raw_imu_t, xgyro) }, \
         { "ygyro", NULL, MAVLINK_TYPE_INT16_T, 0, 16, offsetof(mavlink_raw_imu_t, ygyro) }, \
         { "zgyro", NULL, MAVLINK_TYPE_INT16_T, 0, 18, offsetof(mavlink_raw_imu_t, zgyro) }, \
         { "xmag", NULL, MAVLINK_TYPE_INT16_T, 0, 20, offsetof(mavlink_raw_imu_t, xmag) }, \
         { "ymag", NULL, MAVLINK_TYPE_INT16_T, 0, 22, offsetof(mavlink_raw_imu_t, ymag) }, \
         { "zmag", NULL, MAVLINK_TYPE_INT16_T, 0, 24, offsetof(mavlink_raw_imu_t, zmag) }, \
         } \
}
Definition at line 27 of file mavlink_msg_raw_imu.h.
#define MAVLINK_MSG_ID_27_CRC 144
Definition at line 23 of file mavlink_msg_raw_imu.h.
#define MAVLINK_MSG_ID_27_LEN 26
Definition at line 20 of file mavlink_msg_raw_imu.h.
#define MAVLINK_MSG_ID_RAW_IMU 27
Definition at line 3 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_pack(), and mavlink_msg_raw_imu_pack_chan().
#define MAVLINK_MSG_ID_RAW_IMU_CRC 144
Definition at line 22 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_pack(), and mavlink_msg_raw_imu_pack_chan().
#define MAVLINK_MSG_ID_RAW_IMU_LEN 26
Definition at line 19 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode(), mavlink_msg_raw_imu_pack(), and mavlink_msg_raw_imu_pack_chan().
Typedef Documentation
typedef struct __mavlink_raw_imu_t mavlink_raw_imu_t
Function Documentation
static void mavlink_msg_raw_imu_decode (const mavlink_message_t * msg, mavlink_raw_imu_t * raw_imu) inline static
Decode a raw_imu message into a struct.
Parameters
msg The message to decode
raw_imu C-struct to decode the message contents into
Definition at line 409 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_test_raw_imu().
static uint16_t mavlink_msg_raw_imu_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_raw_imu_t * raw_imu) inline static
Encode a raw_imu struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
raw_imu C-struct to read the message contents from
Definition at line 171 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_test_raw_imu().
static uint16_t mavlink_msg_raw_imu_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_raw_imu_t * raw_imu) inline static
Encode a raw_imu struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
raw_imu C-struct to read the message contents from
Definition at line 185 of file mavlink_msg_raw_imu.h.
static uint64_t mavlink_msg_raw_imu_get_time_usec (const mavlink_message_t * msg) inline static
Send a raw_imu message.
Parameters
chan MAVLink channel to send the message
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
xacc X acceleration (raw)
yacc Y acceleration (raw)
zacc Z acceleration (raw)
xgyro Angular speed around X axis (raw)
ygyro Angular speed around Y axis (raw)
zgyro Angular speed around Z axis (raw)
xmag X Magnetic field (raw)
ymag Y Magnetic field (raw)
zmag Z Magnetic field (raw) Get field time_usec from raw_imu message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 308 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_xacc (const mavlink_message_t * msg) inline static
Get field xacc from raw_imu message.
Returns
X acceleration (raw)
Definition at line 318 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_xgyro (const mavlink_message_t * msg) inline static
Get field xgyro from raw_imu message.
Returns
Angular speed around X axis (raw)
Definition at line 348 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_xmag (const mavlink_message_t * msg) inline static
Get field xmag from raw_imu message.
Returns
X Magnetic field (raw)
Definition at line 378 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_yacc (const mavlink_message_t * msg) inline static
Get field yacc from raw_imu message.
Returns
Y acceleration (raw)
Definition at line 328 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_ygyro (const mavlink_message_t * msg) inline static
Get field ygyro from raw_imu message.
Returns
Angular speed around Y axis (raw)
Definition at line 358 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_ymag (const mavlink_message_t * msg) inline static
Get field ymag from raw_imu message.
Returns
Y Magnetic field (raw)
Definition at line 388 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_zacc (const mavlink_message_t * msg) inline static
Get field zacc from raw_imu message.
Returns
Z acceleration (raw)
Definition at line 338 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_zgyro (const mavlink_message_t * msg) inline static
Get field zgyro from raw_imu message.
Returns
Angular speed around Z axis (raw)
Definition at line 368 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static int16_t mavlink_msg_raw_imu_get_zmag (const mavlink_message_t * msg) inline static
Get field zmag from raw_imu message.
Returns
Z Magnetic field (raw)
Definition at line 398 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_decode().
static uint16_t mavlink_msg_raw_imu_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag) inline static
Pack a raw_imu message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
xacc X acceleration (raw)
yacc Y acceleration (raw)
zacc Z acceleration (raw)
xgyro Angular speed around X axis (raw)
ygyro Angular speed around Y axis (raw)
zgyro Angular speed around Z axis (raw)
xmag X Magnetic field (raw)
ymag Y Magnetic field (raw)
zmag Z Magnetic field (raw)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 62 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_encode(), and mavlink_test_raw_imu().
static uint16_t mavlink_msg_raw_imu_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag) inline static
Pack a raw_imu message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
xacc X acceleration (raw)
yacc Y acceleration (raw)
zacc Z acceleration (raw)
xgyro Angular speed around X axis (raw)
ygyro Angular speed around Y axis (raw)
zgyro Angular speed around Z axis (raw)
xmag X Magnetic field (raw)
ymag Y Magnetic field (raw)
zmag Z Magnetic field (raw)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 121 of file mavlink_msg_raw_imu.h.
Referenced by mavlink_msg_raw_imu_encode_chan(), and mavlink_test_raw_imu().