APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_limits_status.h File Reference
mavlink_msg_limits_status.h File Reference
Classes
struct __mavlink_limits_status_t
Macros
#define MAVLINK_MSG_ID_LIMITS_STATUS 167
#define MAVLINK_MSG_ID_LIMITS_STATUS_LEN 22
#define MAVLINK_MSG_ID_167_LEN 22
#define MAVLINK_MSG_ID_LIMITS_STATUS_CRC 144
#define MAVLINK_MSG_ID_167_CRC 144
#define MAVLINK_MESSAGE_INFO_LIMITS_STATUS
Typedefs
typedef struct __mavlink_limits_status_t mavlink_limits_status_t
Functions
static uint16_t mavlink_msg_limits_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t limits_state, uint32_t last_trigger, uint32_t last_action, uint32_t last_recovery, uint32_t last_clear, uint16_t breach_count, uint8_t mods_enabled, uint8_t mods_required, uint8_t mods_triggered)
Pack a limits_status message.
static uint16_t mavlink_msg_limits_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t limits_state, uint32_t last_trigger, uint32_t last_action, uint32_t last_recovery, uint32_t last_clear, uint16_t breach_count, uint8_t mods_enabled, uint8_t mods_required, uint8_t mods_triggered)
Pack a limits_status message on a channel.
static uint16_t mavlink_msg_limits_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_limits_status_t *limits_status)
Encode a limits_status struct.
static uint16_t mavlink_msg_limits_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_limits_status_t *limits_status)
Encode a limits_status struct on a channel.
static uint8_t mavlink_msg_limits_status_get_limits_state (const mavlink_message_t *msg)
Send a limits_status message.
static uint32_t mavlink_msg_limits_status_get_last_trigger (const mavlink_message_t *msg)
Get field last_trigger from limits_status message.
static uint32_t mavlink_msg_limits_status_get_last_action (const mavlink_message_t *msg)
Get field last_action from limits_status message.
static uint32_t mavlink_msg_limits_status_get_last_recovery (const mavlink_message_t *msg)
Get field last_recovery from limits_status message.
static uint32_t mavlink_msg_limits_status_get_last_clear (const mavlink_message_t *msg)
Get field last_clear from limits_status message.
static uint16_t mavlink_msg_limits_status_get_breach_count (const mavlink_message_t *msg)
Get field breach_count from limits_status message.
static uint8_t mavlink_msg_limits_status_get_mods_enabled (const mavlink_message_t *msg)
Get field mods_enabled from limits_status message.
static uint8_t mavlink_msg_limits_status_get_mods_required (const mavlink_message_t *msg)
Get field mods_required from limits_status message.
static uint8_t mavlink_msg_limits_status_get_mods_triggered (const mavlink_message_t *msg)
Get field mods_triggered from limits_status message.
static void mavlink_msg_limits_status_decode (const mavlink_message_t *msg, mavlink_limits_status_t *limits_status)
Decode a limits_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LIMITS_STATUS
Value:
{ \
    "LIMITS_STATUS", \
    9, \
    {  { "last_trigger", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_limits_status_t, last_trigger) }, \
         { "last_action", NULL, MAVLINK_TYPE_UINT32_T, 0, 4, offsetof(mavlink_limits_status_t, last_action) }, \
         { "last_recovery", NULL, MAVLINK_TYPE_UINT32_T, 0, 8, offsetof(mavlink_limits_status_t, last_recovery) }, \
         { "last_clear", NULL, MAVLINK_TYPE_UINT32_T, 0, 12, offsetof(mavlink_limits_status_t, last_clear) }, \
         { "breach_count", NULL, MAVLINK_TYPE_UINT16_T, 0, 16, offsetof(mavlink_limits_status_t, breach_count) }, \
         { "limits_state", NULL, MAVLINK_TYPE_UINT8_T, 0, 18, offsetof(mavlink_limits_status_t, limits_state) }, \
         { "mods_enabled", NULL, MAVLINK_TYPE_UINT8_T, 0, 19, offsetof(mavlink_limits_status_t, mods_enabled) }, \
         { "mods_required", NULL, MAVLINK_TYPE_UINT8_T, 0, 20, offsetof(mavlink_limits_status_t, mods_required) }, \
         { "mods_triggered", NULL, MAVLINK_TYPE_UINT8_T, 0, 21, offsetof(mavlink_limits_status_t, mods_triggered) }, \
         } \
}
Definition at line 26 of file mavlink_msg_limits_status.h.
#define MAVLINK_MSG_ID_167_CRC 144
Definition at line 22 of file mavlink_msg_limits_status.h.
#define MAVLINK_MSG_ID_167_LEN 22
Definition at line 19 of file mavlink_msg_limits_status.h.
#define MAVLINK_MSG_ID_LIMITS_STATUS 167
Definition at line 3 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_pack(), and mavlink_msg_limits_status_pack_chan().
#define MAVLINK_MSG_ID_LIMITS_STATUS_CRC 144
Definition at line 21 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_pack(), and mavlink_msg_limits_status_pack_chan().
#define MAVLINK_MSG_ID_LIMITS_STATUS_LEN 22
Definition at line 18 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode(), mavlink_msg_limits_status_pack(), and mavlink_msg_limits_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_limits_status_t mavlink_limits_status_t
Function Documentation
static void mavlink_msg_limits_status_decode (const mavlink_message_t * msg, mavlink_limits_status_t * limits_status) inline static
Decode a limits_status message into a struct.
Parameters
msg The message to decode
limits_status C-struct to decode the message contents into
Definition at line 386 of file mavlink_msg_limits_status.h.
Referenced by mavlink_test_limits_status().
static uint16_t mavlink_msg_limits_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_limits_status_t * limits_status) inline static
Encode a limits_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
limits_status C-struct to read the message contents from
Definition at line 163 of file mavlink_msg_limits_status.h.
Referenced by mavlink_test_limits_status().
static uint16_t mavlink_msg_limits_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_limits_status_t * limits_status) inline static
Encode a limits_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
limits_status C-struct to read the message contents from
Definition at line 177 of file mavlink_msg_limits_status.h.
static uint16_t mavlink_msg_limits_status_get_breach_count (const mavlink_message_t * msg) inline static
Get field breach_count from limits_status message.
Returns
number of fence breaches
Definition at line 345 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint32_t mavlink_msg_limits_status_get_last_action (const mavlink_message_t * msg) inline static
Get field last_action from limits_status message.
Returns
time of last recovery action in milliseconds since boot
Definition at line 315 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint32_t mavlink_msg_limits_status_get_last_clear (const mavlink_message_t * msg) inline static
Get field last_clear from limits_status message.
Returns
time of last all-clear in milliseconds since boot
Definition at line 335 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint32_t mavlink_msg_limits_status_get_last_recovery (const mavlink_message_t * msg) inline static
Get field last_recovery from limits_status message.
Returns
time of last successful recovery in milliseconds since boot
Definition at line 325 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint32_t mavlink_msg_limits_status_get_last_trigger (const mavlink_message_t * msg) inline static
Get field last_trigger from limits_status message.
Returns
time of last breach in milliseconds since boot
Definition at line 305 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint8_t mavlink_msg_limits_status_get_limits_state (const mavlink_message_t * msg) inline static
Send a limits_status message.
Parameters
chan MAVLink channel to send the message
limits_state state of AP_Limits, (see enum LimitState, LIMITS_STATE)
last_trigger time of last breach in milliseconds since boot
last_action time of last recovery action in milliseconds since boot
last_recovery time of last successful recovery in milliseconds since boot
last_clear time of last all-clear in milliseconds since boot
breach_count number of fence breaches
mods_enabled AP_Limit_Module bitfield of enabled modules, (see enum moduleid or LIMIT_MODULE)
mods_required AP_Limit_Module bitfield of required modules, (see enum moduleid or LIMIT_MODULE)
mods_triggered AP_Limit_Module bitfield of triggered modules, (see enum moduleid or LIMIT_MODULE) Get field limits_state from limits_status message
Returns
state of AP_Limits, (see enum LimitState, LIMITS_STATE)
Definition at line 295 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint8_t mavlink_msg_limits_status_get_mods_enabled (const mavlink_message_t * msg) inline static
Get field mods_enabled from limits_status message.
Returns
AP_Limit_Module bitfield of enabled modules, (see enum moduleid or LIMIT_MODULE)
Definition at line 355 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint8_t mavlink_msg_limits_status_get_mods_required (const mavlink_message_t * msg) inline static
Get field mods_required from limits_status message.
Returns
AP_Limit_Module bitfield of required modules, (see enum moduleid or LIMIT_MODULE)
Definition at line 365 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint8_t mavlink_msg_limits_status_get_mods_triggered (const mavlink_message_t * msg) inline static
Get field mods_triggered from limits_status message.
Returns
AP_Limit_Module bitfield of triggered modules, (see enum moduleid or LIMIT_MODULE)
Definition at line 375 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_decode().
static uint16_t mavlink_msg_limits_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t limits_state, uint32_t last_trigger, uint32_t last_action, uint32_t last_recovery, uint32_t last_clear, uint16_t breach_count, uint8_t mods_enabled, uint8_t mods_required, uint8_t mods_triggered) inline static
Pack a limits_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
limits_state state of AP_Limits, (see enum LimitState, LIMITS_STATE)
last_trigger time of last breach in milliseconds since boot
last_action time of last recovery action in milliseconds since boot
last_recovery time of last successful recovery in milliseconds since boot
last_clear time of last all-clear in milliseconds since boot
breach_count number of fence breaches
mods_enabled AP_Limit_Module bitfield of enabled modules, (see enum moduleid or LIMIT_MODULE)
mods_required AP_Limit_Module bitfield of required modules, (see enum moduleid or LIMIT_MODULE)
mods_triggered AP_Limit_Module bitfield of triggered modules, (see enum moduleid or LIMIT_MODULE)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 59 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_encode(), and mavlink_test_limits_status().
static uint16_t mavlink_msg_limits_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t limits_state, uint32_t last_trigger, uint32_t last_action, uint32_t last_recovery, uint32_t last_clear, uint16_t breach_count, uint8_t mods_enabled, uint8_t mods_required, uint8_t mods_triggered) inline static
Pack a limits_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
limits_state state of AP_Limits, (see enum LimitState, LIMITS_STATE)
last_trigger time of last breach in milliseconds since boot
last_action time of last recovery action in milliseconds since boot
last_recovery time of last successful recovery in milliseconds since boot
last_clear time of last all-clear in milliseconds since boot
breach_count number of fence breaches
mods_enabled AP_Limit_Module bitfield of enabled modules, (see enum moduleid or LIMIT_MODULE)
mods_required AP_Limit_Module bitfield of required modules, (see enum moduleid or LIMIT_MODULE)
mods_triggered AP_Limit_Module bitfield of triggered modules, (see enum moduleid or LIMIT_MODULE)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 115 of file mavlink_msg_limits_status.h.
Referenced by mavlink_msg_limits_status_encode_chan(), and mavlink_test_limits_status().