APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_camera_status.h File Reference
mavlink_msg_camera_status.h File Reference
Classes
struct __mavlink_camera_status_t
Macros
#define MAVLINK_MSG_ID_CAMERA_STATUS 179
#define MAVLINK_MSG_ID_CAMERA_STATUS_LEN 29
#define MAVLINK_MSG_ID_179_LEN 29
#define MAVLINK_MSG_ID_CAMERA_STATUS_CRC 189
#define MAVLINK_MSG_ID_179_CRC 189
#define MAVLINK_MESSAGE_INFO_CAMERA_STATUS
Typedefs
typedef struct __mavlink_camera_status_t mavlink_camera_status_t
Functions
static uint16_t mavlink_msg_camera_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, uint8_t event_id, float p1, float p2, float p3, float p4)
Pack a camera_status message.
static uint16_t mavlink_msg_camera_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, uint8_t event_id, float p1, float p2, float p3, float p4)
Pack a camera_status message on a channel.
static uint16_t mavlink_msg_camera_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_camera_status_t *camera_status)
Encode a camera_status struct.
static uint16_t mavlink_msg_camera_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_camera_status_t *camera_status)
Encode a camera_status struct on a channel.
static uint64_t mavlink_msg_camera_status_get_time_usec (const mavlink_message_t *msg)
Send a camera_status message.
static uint8_t mavlink_msg_camera_status_get_target_system (const mavlink_message_t *msg)
Get field target_system from camera_status message.
static uint8_t mavlink_msg_camera_status_get_cam_idx (const mavlink_message_t *msg)
Get field cam_idx from camera_status message.
static uint16_t mavlink_msg_camera_status_get_img_idx (const mavlink_message_t *msg)
Get field img_idx from camera_status message.
static uint8_t mavlink_msg_camera_status_get_event_id (const mavlink_message_t *msg)
Get field event_id from camera_status message.
static float mavlink_msg_camera_status_get_p1 (const mavlink_message_t *msg)
Get field p1 from camera_status message.
static float mavlink_msg_camera_status_get_p2 (const mavlink_message_t *msg)
Get field p2 from camera_status message.
static float mavlink_msg_camera_status_get_p3 (const mavlink_message_t *msg)
Get field p3 from camera_status message.
static float mavlink_msg_camera_status_get_p4 (const mavlink_message_t *msg)
Get field p4 from camera_status message.
static void mavlink_msg_camera_status_decode (const mavlink_message_t *msg, mavlink_camera_status_t *camera_status)
Decode a camera_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_CAMERA_STATUS
Value:
{ \
    "CAMERA_STATUS", \
    9, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_camera_status_t, time_usec) }, \
         { "p1", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_camera_status_t, p1) }, \
         { "p2", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_camera_status_t, p2) }, \
         { "p3", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_camera_status_t, p3) }, \
         { "p4", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_camera_status_t, p4) }, \
         { "img_idx", NULL, MAVLINK_TYPE_UINT16_T, 0, 24, offsetof(mavlink_camera_status_t, img_idx) }, \
         { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 26, offsetof(mavlink_camera_status_t, target_system) }, \
         { "cam_idx", NULL, MAVLINK_TYPE_UINT8_T, 0, 27, offsetof(mavlink_camera_status_t, cam_idx) }, \
         { "event_id", NULL, MAVLINK_TYPE_UINT8_T, 0, 28, offsetof(mavlink_camera_status_t, event_id) }, \
         } \
}
Definition at line 26 of file mavlink_msg_camera_status.h.
#define MAVLINK_MSG_ID_179_CRC 189
Definition at line 22 of file mavlink_msg_camera_status.h.
#define MAVLINK_MSG_ID_179_LEN 29
Definition at line 19 of file mavlink_msg_camera_status.h.
#define MAVLINK_MSG_ID_CAMERA_STATUS 179
Definition at line 3 of file mavlink_msg_camera_status.h.
Referenced by MAVLink_routing::get_targets(), mavlink_msg_camera_status_pack(), and mavlink_msg_camera_status_pack_chan().
#define MAVLINK_MSG_ID_CAMERA_STATUS_CRC 189
Definition at line 21 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_pack(), and mavlink_msg_camera_status_pack_chan().
#define MAVLINK_MSG_ID_CAMERA_STATUS_LEN 29
Definition at line 18 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode(), mavlink_msg_camera_status_pack(), and mavlink_msg_camera_status_pack_chan().
Typedef Documentation
typedef struct __mavlink_camera_status_t mavlink_camera_status_t
Function Documentation
static void mavlink_msg_camera_status_decode (const mavlink_message_t * msg, mavlink_camera_status_t * camera_status) inline static
Decode a camera_status message into a struct.
Parameters
msg The message to decode
camera_status C-struct to decode the message contents into
Definition at line 386 of file mavlink_msg_camera_status.h.
Referenced by mavlink_test_camera_status().
static uint16_t mavlink_msg_camera_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_camera_status_t * camera_status) inline static
Encode a camera_status struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
camera_status C-struct to read the message contents from
Definition at line 163 of file mavlink_msg_camera_status.h.
Referenced by mavlink_test_camera_status().
static uint16_t mavlink_msg_camera_status_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_camera_status_t * camera_status) inline static
Encode a camera_status struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
camera_status C-struct to read the message contents from
Definition at line 177 of file mavlink_msg_camera_status.h.
static uint8_t mavlink_msg_camera_status_get_cam_idx (const mavlink_message_t * msg) inline static
Get field cam_idx from camera_status message.
Returns
Camera ID
Definition at line 315 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static uint8_t mavlink_msg_camera_status_get_event_id (const mavlink_message_t * msg) inline static
Get field event_id from camera_status message.
Returns
See CAMERA_STATUS_TYPES enum for definition of the bitmask
Definition at line 335 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static uint16_t mavlink_msg_camera_status_get_img_idx (const mavlink_message_t * msg) inline static
Get field img_idx from camera_status message.
Returns
Image index
Definition at line 325 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static float mavlink_msg_camera_status_get_p1 (const mavlink_message_t * msg) inline static
Get field p1 from camera_status message.
Returns
Parameter 1 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
Definition at line 345 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static float mavlink_msg_camera_status_get_p2 (const mavlink_message_t * msg) inline static
Get field p2 from camera_status message.
Returns
Parameter 2 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
Definition at line 355 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static float mavlink_msg_camera_status_get_p3 (const mavlink_message_t * msg) inline static
Get field p3 from camera_status message.
Returns
Parameter 3 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
Definition at line 365 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static float mavlink_msg_camera_status_get_p4 (const mavlink_message_t * msg) inline static
Get field p4 from camera_status message.
Returns
Parameter 4 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
Definition at line 375 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static uint8_t mavlink_msg_camera_status_get_target_system (const mavlink_message_t * msg) inline static
Get field target_system from camera_status message.
Returns
System ID
Definition at line 305 of file mavlink_msg_camera_status.h.
Referenced by MAVLink_routing::get_targets(), and mavlink_msg_camera_status_decode().
static uint64_t mavlink_msg_camera_status_get_time_usec (const mavlink_message_t * msg) inline static
Send a camera_status message.
Parameters
chan MAVLink channel to send the message
time_usec Image timestamp (microseconds since UNIX epoch, according to camera clock)
target_system System ID
cam_idx Camera ID
img_idx Image index
event_id See CAMERA_STATUS_TYPES enum for definition of the bitmask
p1 Parameter 1 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p2 Parameter 2 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p3 Parameter 3 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p4 Parameter 4 (meaning depends on event, see CAMERA_STATUS_TYPES enum) Get field time_usec from camera_status message
Returns
Image timestamp (microseconds since UNIX epoch, according to camera clock)
Definition at line 295 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_decode().
static uint16_t mavlink_msg_camera_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, uint8_t event_id, float p1, float p2, float p3, float p4) inline static
Pack a camera_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_usec Image timestamp (microseconds since UNIX epoch, according to camera clock)
target_system System ID
cam_idx Camera ID
img_idx Image index
event_id See CAMERA_STATUS_TYPES enum for definition of the bitmask
p1 Parameter 1 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p2 Parameter 2 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p3 Parameter 3 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p4 Parameter 4 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 59 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_encode(), and mavlink_test_camera_status().
static uint16_t mavlink_msg_camera_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_usec, uint8_t target_system, uint8_t cam_idx, uint16_t img_idx, uint8_t event_id, float p1, float p2, float p3, float p4) inline static
Pack a camera_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_usec Image timestamp (microseconds since UNIX epoch, according to camera clock)
target_system System ID
cam_idx Camera ID
img_idx Image index
event_id See CAMERA_STATUS_TYPES enum for definition of the bitmask
p1 Parameter 1 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p2 Parameter 2 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p3 Parameter 3 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
p4 Parameter 4 (meaning depends on event, see CAMERA_STATUS_TYPES enum)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 115 of file mavlink_msg_camera_status.h.
Referenced by mavlink_msg_camera_status_encode_chan(), and mavlink_test_camera_status().