APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_manual_control.h File Reference
mavlink_msg_manual_control.h File Reference
Classes
struct __mavlink_manual_control_t
Macros
#define MAVLINK_MSG_ID_MANUAL_CONTROL 69
#define MAVLINK_MSG_ID_MANUAL_CONTROL_LEN 11
#define MAVLINK_MSG_ID_69_LEN 11
#define MAVLINK_MSG_ID_MANUAL_CONTROL_CRC 243
#define MAVLINK_MSG_ID_69_CRC 243
#define MAVLINK_MESSAGE_INFO_MANUAL_CONTROL
Typedefs
typedef struct __mavlink_manual_control_t mavlink_manual_control_t
Functions
static uint16_t mavlink_msg_manual_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target, int16_t x, int16_t y, int16_t z, int16_t r, uint16_t buttons)
Pack a manual_control message.
static uint16_t mavlink_msg_manual_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target, int16_t x, int16_t y, int16_t z, int16_t r, uint16_t buttons)
Pack a manual_control message on a channel.
static uint16_t mavlink_msg_manual_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_manual_control_t *manual_control)
Encode a manual_control struct.
static uint16_t mavlink_msg_manual_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_manual_control_t *manual_control)
Encode a manual_control struct on a channel.
static uint8_t mavlink_msg_manual_control_get_target (const mavlink_message_t *msg)
Send a manual_control message.
static int16_t mavlink_msg_manual_control_get_x (const mavlink_message_t *msg)
Get field x from manual_control message.
static int16_t mavlink_msg_manual_control_get_y (const mavlink_message_t *msg)
Get field y from manual_control message.
static int16_t mavlink_msg_manual_control_get_z (const mavlink_message_t *msg)
Get field z from manual_control message.
static int16_t mavlink_msg_manual_control_get_r (const mavlink_message_t *msg)
Get field r from manual_control message.
static uint16_t mavlink_msg_manual_control_get_buttons (const mavlink_message_t *msg)
Get field buttons from manual_control message.
static void mavlink_msg_manual_control_decode (const mavlink_message_t *msg, mavlink_manual_control_t *manual_control)
Decode a manual_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MANUAL_CONTROL
Value:
{ \
    "MANUAL_CONTROL", \
    6, \
    {  { "x", NULL, MAVLINK_TYPE_INT16_T, 0, 0, offsetof(mavlink_manual_control_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_INT16_T, 0, 2, offsetof(mavlink_manual_control_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_INT16_T, 0, 4, offsetof(mavlink_manual_control_t, z) }, \
         { "r", NULL, MAVLINK_TYPE_INT16_T, 0, 6, offsetof(mavlink_manual_control_t, r) }, \
         { "buttons", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_manual_control_t, buttons) }, \
         { "target", NULL, MAVLINK_TYPE_UINT8_T, 0, 10, offsetof(mavlink_manual_control_t, target) }, \
         } \
}
Definition at line 23 of file mavlink_msg_manual_control.h.
#define MAVLINK_MSG_ID_69_CRC 243
Definition at line 19 of file mavlink_msg_manual_control.h.
#define MAVLINK_MSG_ID_69_LEN 11
Definition at line 16 of file mavlink_msg_manual_control.h.
#define MAVLINK_MSG_ID_MANUAL_CONTROL 69
Definition at line 3 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_pack(), and mavlink_msg_manual_control_pack_chan().
#define MAVLINK_MSG_ID_MANUAL_CONTROL_CRC 243
Definition at line 18 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_pack(), and mavlink_msg_manual_control_pack_chan().
#define MAVLINK_MSG_ID_MANUAL_CONTROL_LEN 11
Definition at line 15 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode(), mavlink_msg_manual_control_pack(), and mavlink_msg_manual_control_pack_chan().
Typedef Documentation
typedef struct __mavlink_manual_control_t mavlink_manual_control_t
Function Documentation
static void mavlink_msg_manual_control_decode (const mavlink_message_t * msg, mavlink_manual_control_t * manual_control) inline static
Decode a manual_control message into a struct.
Parameters
msg The message to decode
manual_control C-struct to decode the message contents into
Definition at line 317 of file mavlink_msg_manual_control.h.
Referenced by mavlink_test_manual_control().
static uint16_t mavlink_msg_manual_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_manual_control_t * manual_control) inline static
Encode a manual_control struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
manual_control C-struct to read the message contents from
Definition at line 139 of file mavlink_msg_manual_control.h.
Referenced by mavlink_test_manual_control().
static uint16_t mavlink_msg_manual_control_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_manual_control_t * manual_control) inline static
Encode a manual_control struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
manual_control C-struct to read the message contents from
Definition at line 153 of file mavlink_msg_manual_control.h.
static uint16_t mavlink_msg_manual_control_get_buttons (const mavlink_message_t * msg) inline static
Get field buttons from manual_control message.
Returns
A bitfield corresponding to the joystick buttons' current state, 1 for pressed, 0 for released. The lowest bit corresponds to Button 1.
Definition at line 306 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static int16_t mavlink_msg_manual_control_get_r (const mavlink_message_t * msg) inline static
Get field r from manual_control message.
Returns
R-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a twisting of the joystick, with counter-clockwise being 1000 and clockwise being -1000, and the yaw of a vehicle.
Definition at line 296 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint8_t mavlink_msg_manual_control_get_target (const mavlink_message_t * msg) inline static
Send a manual_control message.
Parameters
chan MAVLink channel to send the message
target The system to be controlled.
x X-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to forward(1000)-backward(-1000) movement on a joystick and the pitch of a vehicle.
y Y-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to left(-1000)-right(1000) movement on a joystick and the roll of a vehicle.
z Z-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a separate slider movement with maximum being 1000 and minimum being -1000 on a joystick and the thrust of a vehicle.
r R-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a twisting of the joystick, with counter-clockwise being 1000 and clockwise being -1000, and the yaw of a vehicle.
buttons A bitfield corresponding to the joystick buttons' current state, 1 for pressed, 0 for released. The lowest bit corresponds to Button 1. Get field target from manual_control message
Returns
The system to be controlled.
Definition at line 256 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static int16_t mavlink_msg_manual_control_get_x (const mavlink_message_t * msg) inline static
Get field x from manual_control message.
Returns
X-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to forward(1000)-backward(-1000) movement on a joystick and the pitch of a vehicle.
Definition at line 266 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static int16_t mavlink_msg_manual_control_get_y (const mavlink_message_t * msg) inline static
Get field y from manual_control message.
Returns
Y-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to left(-1000)-right(1000) movement on a joystick and the roll of a vehicle.
Definition at line 276 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static int16_t mavlink_msg_manual_control_get_z (const mavlink_message_t * msg) inline static
Get field z from manual_control message.
Returns
Z-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a separate slider movement with maximum being 1000 and minimum being -1000 on a joystick and the thrust of a vehicle.
Definition at line 286 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint16_t mavlink_msg_manual_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target, int16_t x, int16_t y, int16_t z, int16_t r, uint16_t buttons) inline static
Pack a manual_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target The system to be controlled.
x X-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to forward(1000)-backward(-1000) movement on a joystick and the pitch of a vehicle.
y Y-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to left(-1000)-right(1000) movement on a joystick and the roll of a vehicle.
z Z-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a separate slider movement with maximum being 1000 and minimum being -1000 on a joystick and the thrust of a vehicle.
r R-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a twisting of the joystick, with counter-clockwise being 1000 and clockwise being -1000, and the yaw of a vehicle.
buttons A bitfield corresponding to the joystick buttons' current state, 1 for pressed, 0 for released. The lowest bit corresponds to Button 1.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_encode(), and mavlink_test_manual_control().
static uint16_t mavlink_msg_manual_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target, int16_t x, int16_t y, int16_t z, int16_t r, uint16_t buttons) inline static
Pack a manual_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
target The system to be controlled.
x X-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to forward(1000)-backward(-1000) movement on a joystick and the pitch of a vehicle.
y Y-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to left(-1000)-right(1000) movement on a joystick and the roll of a vehicle.
z Z-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a separate slider movement with maximum being 1000 and minimum being -1000 on a joystick and the thrust of a vehicle.
r R-axis, normalized to the range [-1000,1000]. A value of INT16_MAX indicates that this axis is invalid. Generally corresponds to a twisting of the joystick, with counter-clockwise being 1000 and clockwise being -1000, and the yaw of a vehicle.
buttons A bitfield corresponding to the joystick buttons' current state, 1 for pressed, 0 for released. The lowest bit corresponds to Button 1.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 97 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_encode_chan(), and mavlink_test_manual_control().