APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_local_position_ned.h File Reference
mavlink_msg_local_position_ned.h File Reference
Classes
struct __mavlink_local_position_ned_t
Macros
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED 32
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_LEN 28
#define MAVLINK_MSG_ID_32_LEN 28
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_CRC 185
#define MAVLINK_MSG_ID_32_CRC 185
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_NED
Typedefs
typedef struct __mavlink_local_position_ned_t mavlink_local_position_ned_t
Functions
static uint16_t mavlink_msg_local_position_ned_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time_boot_ms, float x, float y, float z, float vx, float vy, float vz)
Pack a local_position_ned message.
static uint16_t mavlink_msg_local_position_ned_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time_boot_ms, float x, float y, float z, float vx, float vy, float vz)
Pack a local_position_ned message on a channel.
static uint16_t mavlink_msg_local_position_ned_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_local_position_ned_t *local_position_ned)
Encode a local_position_ned struct.
static uint16_t mavlink_msg_local_position_ned_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_local_position_ned_t *local_position_ned)
Encode a local_position_ned struct on a channel.
static uint32_t mavlink_msg_local_position_ned_get_time_boot_ms (const mavlink_message_t *msg)
Send a local_position_ned message.
static float mavlink_msg_local_position_ned_get_x (const mavlink_message_t *msg)
Get field x from local_position_ned message.
static float mavlink_msg_local_position_ned_get_y (const mavlink_message_t *msg)
Get field y from local_position_ned message.
static float mavlink_msg_local_position_ned_get_z (const mavlink_message_t *msg)
Get field z from local_position_ned message.
static float mavlink_msg_local_position_ned_get_vx (const mavlink_message_t *msg)
Get field vx from local_position_ned message.
static float mavlink_msg_local_position_ned_get_vy (const mavlink_message_t *msg)
Get field vy from local_position_ned message.
static float mavlink_msg_local_position_ned_get_vz (const mavlink_message_t *msg)
Get field vz from local_position_ned message.
static void mavlink_msg_local_position_ned_decode (const mavlink_message_t *msg, mavlink_local_position_ned_t *local_position_ned)
Decode a local_position_ned message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_NED
Value:
{ \
    "LOCAL_POSITION_NED", \
    7, \
    {  { "time_boot_ms", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_local_position_ned_t, time_boot_ms) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_local_position_ned_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_local_position_ned_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_local_position_ned_t, z) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_local_position_ned_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_local_position_ned_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_local_position_ned_t, vz) }, \
         } \
}
Definition at line 24 of file mavlink_msg_local_position_ned.h.
#define MAVLINK_MSG_ID_32_CRC 185
Definition at line 20 of file mavlink_msg_local_position_ned.h.
#define MAVLINK_MSG_ID_32_LEN 28
Definition at line 17 of file mavlink_msg_local_position_ned.h.
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED 32
Definition at line 3 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_pack(), and mavlink_msg_local_position_ned_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_CRC 185
Definition at line 19 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_pack(), and mavlink_msg_local_position_ned_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED_LEN 28
Definition at line 16 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode(), mavlink_msg_local_position_ned_pack(), and mavlink_msg_local_position_ned_pack_chan().
Typedef Documentation
typedef struct __mavlink_local_position_ned_t mavlink_local_position_ned_t
Function Documentation
static void mavlink_msg_local_position_ned_decode (const mavlink_message_t * msg, mavlink_local_position_ned_t * local_position_ned) inline static
Decode a local_position_ned message into a struct.
Parameters
msg The message to decode
local_position_ned C-struct to decode the message contents into
Definition at line 340 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_test_local_position_ned().
static uint16_t mavlink_msg_local_position_ned_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_local_position_ned_t * local_position_ned) inline static
Encode a local_position_ned struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
local_position_ned C-struct to read the message contents from
Definition at line 147 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_test_local_position_ned().
static uint16_t mavlink_msg_local_position_ned_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_local_position_ned_t * local_position_ned) inline static
Encode a local_position_ned struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
local_position_ned C-struct to read the message contents from
Definition at line 161 of file mavlink_msg_local_position_ned.h.
static uint32_t mavlink_msg_local_position_ned_get_time_boot_ms (const mavlink_message_t * msg) inline static
Send a local_position_ned message.
Parameters
chan MAVLink channel to send the message
time_boot_ms Timestamp (milliseconds since system boot)
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed Get field time_boot_ms from local_position_ned message
Returns
Timestamp (milliseconds since system boot)
Definition at line 269 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static float mavlink_msg_local_position_ned_get_vx (const mavlink_message_t * msg) inline static
Get field vx from local_position_ned message.
Returns
X Speed
Definition at line 309 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static float mavlink_msg_local_position_ned_get_vy (const mavlink_message_t * msg) inline static
Get field vy from local_position_ned message.
Returns
Y Speed
Definition at line 319 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static float mavlink_msg_local_position_ned_get_vz (const mavlink_message_t * msg) inline static
Get field vz from local_position_ned message.
Returns
Z Speed
Definition at line 329 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static float mavlink_msg_local_position_ned_get_x (const mavlink_message_t * msg) inline static
Get field x from local_position_ned message.
Returns
X Position
Definition at line 279 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static float mavlink_msg_local_position_ned_get_y (const mavlink_message_t * msg) inline static
Get field y from local_position_ned message.
Returns
Y Position
Definition at line 289 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static float mavlink_msg_local_position_ned_get_z (const mavlink_message_t * msg) inline static
Get field z from local_position_ned message.
Returns
Z Position
Definition at line 299 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_decode().
static uint16_t mavlink_msg_local_position_ned_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time_boot_ms, float x, float y, float z, float vx, float vy, float vz) inline static
Pack a local_position_ned message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_encode(), and mavlink_test_local_position_ned().
static uint16_t mavlink_msg_local_position_ned_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time_boot_ms, float x, float y, float z, float vx, float vy, float vz) inline static
Pack a local_position_ned message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
time_boot_ms Timestamp (milliseconds since system boot)
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 103 of file mavlink_msg_local_position_ned.h.
Referenced by mavlink_msg_local_position_ned_encode_chan(), and mavlink_test_local_position_ned().