APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/common/mavlink_msg_mission_item_reached.h File Reference
mavlink_msg_mission_item_reached.h File Reference
Classes
struct __mavlink_mission_item_reached_t
Macros
#define MAVLINK_MSG_ID_MISSION_ITEM_REACHED 46
#define MAVLINK_MSG_ID_MISSION_ITEM_REACHED_LEN 2
#define MAVLINK_MSG_ID_46_LEN 2
#define MAVLINK_MSG_ID_MISSION_ITEM_REACHED_CRC 11
#define MAVLINK_MSG_ID_46_CRC 11
#define MAVLINK_MESSAGE_INFO_MISSION_ITEM_REACHED
Typedefs
typedef struct __mavlink_mission_item_reached_t mavlink_mission_item_reached_t
Functions
static uint16_t mavlink_msg_mission_item_reached_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t seq)
Pack a mission_item_reached message.
static uint16_t mavlink_msg_mission_item_reached_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t seq)
Pack a mission_item_reached message on a channel.
static uint16_t mavlink_msg_mission_item_reached_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_mission_item_reached_t *mission_item_reached)
Encode a mission_item_reached struct.
static uint16_t mavlink_msg_mission_item_reached_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_mission_item_reached_t *mission_item_reached)
Encode a mission_item_reached struct on a channel.
static uint16_t mavlink_msg_mission_item_reached_get_seq (const mavlink_message_t *msg)
Send a mission_item_reached message.
static void mavlink_msg_mission_item_reached_decode (const mavlink_message_t *msg, mavlink_mission_item_reached_t *mission_item_reached)
Decode a mission_item_reached message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MISSION_ITEM_REACHED
Value:
{ \
    "MISSION_ITEM_REACHED", \
    1, \
    {  { "seq", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_mission_item_reached_t, seq) }, \
         } \
}
Definition at line 18 of file mavlink_msg_mission_item_reached.h.
#define MAVLINK_MSG_ID_46_CRC 11
Definition at line 14 of file mavlink_msg_mission_item_reached.h.
#define MAVLINK_MSG_ID_46_LEN 2
Definition at line 11 of file mavlink_msg_mission_item_reached.h.
#define MAVLINK_MSG_ID_MISSION_ITEM_REACHED 46
Definition at line 3 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_msg_mission_item_reached_pack(), and mavlink_msg_mission_item_reached_pack_chan().
#define MAVLINK_MSG_ID_MISSION_ITEM_REACHED_CRC 11
Definition at line 13 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_msg_mission_item_reached_pack(), and mavlink_msg_mission_item_reached_pack_chan().
#define MAVLINK_MSG_ID_MISSION_ITEM_REACHED_LEN 2
Definition at line 10 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_msg_mission_item_reached_decode(), mavlink_msg_mission_item_reached_pack(), and mavlink_msg_mission_item_reached_pack_chan().
Typedef Documentation
typedef struct __mavlink_mission_item_reached_t mavlink_mission_item_reached_t
Function Documentation
static void mavlink_msg_mission_item_reached_decode (const mavlink_message_t * msg, mavlink_mission_item_reached_t * mission_item_reached) inline static
Decode a mission_item_reached message into a struct.
Parameters
msg The message to decode
mission_item_reached C-struct to decode the message contents into
Definition at line 202 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_test_mission_item_reached().
static uint16_t mavlink_msg_mission_item_reached_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_mission_item_reached_t * mission_item_reached) inline static
Encode a mission_item_reached struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mission_item_reached C-struct to read the message contents from
Definition at line 99 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_test_mission_item_reached().
static uint16_t mavlink_msg_mission_item_reached_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_mission_item_reached_t * mission_item_reached) inline static
Encode a mission_item_reached struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
mission_item_reached C-struct to read the message contents from
Definition at line 113 of file mavlink_msg_mission_item_reached.h.
static uint16_t mavlink_msg_mission_item_reached_get_seq (const mavlink_message_t * msg) inline static
Send a mission_item_reached message.
Parameters
chan MAVLink channel to send the message
seq Sequence Get field seq from mission_item_reached message
Returns
Sequence
Definition at line 191 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_msg_mission_item_reached_decode().
static uint16_t mavlink_msg_mission_item_reached_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t seq) inline static
Pack a mission_item_reached message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_msg_mission_item_reached_encode(), and mavlink_test_mission_item_reached().
static uint16_t mavlink_msg_mission_item_reached_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t seq) inline static
Pack a mission_item_reached message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 67 of file mavlink_msg_mission_item_reached.h.
Referenced by mavlink_msg_mission_item_reached_encode_chan(), and mavlink_test_mission_item_reached().