APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v1.0/ardupilotmega/mavlink_msg_data32.h File Reference
mavlink_msg_data32.h File Reference
Classes
struct __mavlink_data32_t
Macros
#define MAVLINK_MSG_ID_DATA32 170
#define MAVLINK_MSG_ID_DATA32_LEN 34
#define MAVLINK_MSG_ID_170_LEN 34
#define MAVLINK_MSG_ID_DATA32_CRC 73
#define MAVLINK_MSG_ID_170_CRC 73
#define MAVLINK_MSG_DATA32_FIELD_DATA_LEN 32
#define MAVLINK_MESSAGE_INFO_DATA32
Typedefs
typedef struct __mavlink_data32_t mavlink_data32_t
Functions
static uint16_t mavlink_msg_data32_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t type, uint8_t len, const uint8_t *data)
Pack a data32 message.
static uint16_t mavlink_msg_data32_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t type, uint8_t len, const uint8_t *data)
Pack a data32 message on a channel.
static uint16_t mavlink_msg_data32_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_data32_t *data32)
Encode a data32 struct.
static uint16_t mavlink_msg_data32_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const mavlink_data32_t *data32)
Encode a data32 struct on a channel.
static uint8_t mavlink_msg_data32_get_type (const mavlink_message_t *msg)
Send a data32 message.
static uint8_t mavlink_msg_data32_get_len (const mavlink_message_t *msg)
Get field len from data32 message.
static uint16_t mavlink_msg_data32_get_data (const mavlink_message_t *msg, uint8_t *data)
Get field data from data32 message.
static void mavlink_msg_data32_decode (const mavlink_message_t *msg, mavlink_data32_t *data32)
Decode a data32 message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_DATA32
Value:
{ \
    "DATA32", \
    3, \
    {  { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_data32_t, type) }, \
         { "len", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_data32_t, len) }, \
         { "data", NULL, MAVLINK_TYPE_UINT8_T, 32, 2, offsetof(mavlink_data32_t, data) }, \
         } \
}
Definition at line 20 of file mavlink_msg_data32.h.
#define MAVLINK_MSG_DATA32_FIELD_DATA_LEN 32
Definition at line 18 of file mavlink_msg_data32.h.
#define MAVLINK_MSG_ID_170_CRC 73
Definition at line 16 of file mavlink_msg_data32.h.
#define MAVLINK_MSG_ID_170_LEN 34
Definition at line 13 of file mavlink_msg_data32.h.
#define MAVLINK_MSG_ID_DATA32 170
Definition at line 3 of file mavlink_msg_data32.h.
Referenced by handle_message(), mavlink_msg_data32_pack(), and mavlink_msg_data32_pack_chan().
#define MAVLINK_MSG_ID_DATA32_CRC 73
Definition at line 15 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_pack(), and mavlink_msg_data32_pack_chan().
#define MAVLINK_MSG_ID_DATA32_LEN 34
Definition at line 12 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_decode(), mavlink_msg_data32_pack(), and mavlink_msg_data32_pack_chan().
Typedef Documentation
typedef struct __mavlink_data32_t mavlink_data32_t
Function Documentation
static void mavlink_msg_data32_decode (const mavlink_message_t * msg, mavlink_data32_t * data32) inline static
Decode a data32 message into a struct.
Parameters
msg The message to decode
data32 C-struct to decode the message contents into
Definition at line 240 of file mavlink_msg_data32.h.
Referenced by gcs_console_handle_data32(), and mavlink_test_data32().
static uint16_t mavlink_msg_data32_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_data32_t * data32) inline static
Encode a data32 struct.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
data32 C-struct to read the message contents from
Definition at line 111 of file mavlink_msg_data32.h.
Referenced by mavlink_test_data32().
static uint16_t mavlink_msg_data32_encode_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const mavlink_data32_t * data32) inline static
Encode a data32 struct on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
data32 C-struct to read the message contents from
Definition at line 125 of file mavlink_msg_data32.h.
static uint16_t mavlink_msg_data32_get_data (const mavlink_message_t * msg, uint8_t * data) inline static
Get field data from data32 message.
Returns
raw data
Definition at line 229 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_decode().
static uint8_t mavlink_msg_data32_get_len (const mavlink_message_t * msg) inline static
Get field len from data32 message.
Returns
data length
Definition at line 219 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_decode().
static uint8_t mavlink_msg_data32_get_type (const mavlink_message_t * msg) inline static
Send a data32 message.
Parameters
chan MAVLink channel to send the message
type data type
len data length
data raw data Get field type from data32 message
Returns
data type
Definition at line 209 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_decode().
static uint16_t mavlink_msg_data32_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t type, uint8_t len, const uint8_t * data) inline static
Pack a data32 message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
type data type
len data length
data raw data
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_encode(), and mavlink_test_data32().
static uint16_t mavlink_msg_data32_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t type, uint8_t len, const uint8_t * data) inline static
Pack a data32 message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message will be sent over
msg The MAVLink message to compress the data into
type data type
len data length
data raw data
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 77 of file mavlink_msg_data32.h.
Referenced by mavlink_msg_data32_encode_chan(), and mavlink_test_data32().