APM:Libraries: SITL Namespace Reference
SITL Namespace Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Classes
class Aircraft
class Balloon
class CRRCSim
class FGNetFDM
class Frame
class Gazebo
class Gimbal
class Helicopter
class JSBSim
class last_letter
class Motor
class MultiCopter
class SimRover
class SITL
struct sitl_fdm
class Tracker
Variables
Motor m (90, false, 1)
static const Motor quad_plus_motors [4]
static const Motor quad_x_motors [4]
static const Motor hexa_motors [6]
static const Motor hexax_motors [6]
static const Motor octa_motors [8]
static const Motor octa_quad_motors [8]
static const Frame supported_frames []
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Variable Documentation
const Motor SITL::hexa_motors[6] static
Initial value:
=
{
    Motor(60,   false, 1),
    Motor(60,   true,  7),
    Motor(180,  true,  4),
    Motor(180,  false, 8),
    Motor(-60,  true,  2),
    Motor(-60,  false, 3),
}
Definition at line 44 of file SIM_Multicopter.cpp.
const Motor SITL::hexax_motors[6] static
Initial value:
=
{
    Motor(30,  false,  7),
    Motor(90,  true,   1),
    Motor(150, false,  4),
    Motor(210, true,   8),
    Motor(270, false,  2),
    Motor(330, true,   3)
}
Definition at line 54 of file SIM_Multicopter.cpp.
Motor SITL::m(90, false, 1)
Referenced by Quaternion::earth_to_body(), Quaternion::from_vector312(), AP_Limits::init(), AP_Limit_Module::link(), missing_rotations(), AP_Limits::modules(), AP_Limits::modules_add(), AP_Limits::modules_count(), AP_Limits::modules_last(), Matrix3< float >::operator*=(), Matrix3< float >::operator+=(), Matrix3< float >::operator-=(), AP_HAL::Print::printNumber(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_frame_transforms(), test_quaternion(), and Quaternion::to_vector312().
const Motor SITL::octa_motors[8] static
Initial value:
=
{
    Motor(0,    true,  1),
    Motor(180,  true,  2),
    Motor(45,   false, 3),
    Motor(135,  false, 4),
    Motor(-45,  false, 5),
    Motor(-135, false, 6),
    Motor(270,  true,  7),
    Motor(90,   true,  8)
}
Definition at line 64 of file SIM_Multicopter.cpp.
const Motor SITL::octa_quad_motors[8] static
Initial value:
=
{
    Motor(  45, false, 1),
    Motor( -45, true,  2),
    Motor(-135, false, 3),
    Motor( 135, true,  4),
    Motor( -45, false, 5),
    Motor(  45, true,  6),
    Motor( 135, false, 7),
    Motor(-135, true,  8)
}
Definition at line 76 of file SIM_Multicopter.cpp.
const Motor SITL::quad_plus_motors[4] static
Initial value:
=
{
    Motor(90,  false,  1),
    Motor(270, false,  2),
    Motor(0,   true,   3),
    Motor(180, true,   4)
}
Definition at line 28 of file SIM_Multicopter.cpp.
const Motor SITL::quad_x_motors[4] static
Initial value:
=
{
    Motor(45,  false,  1),
    Motor(225, false,  2),
    Motor(315, true,   3),
    Motor(135, true,   4)
}
Definition at line 36 of file SIM_Multicopter.cpp.
const Frame SITL::supported_frames[] static
Initial value:
=
{
    Frame("+",         4, quad_plus_motors),
    Frame("quad",      4, quad_plus_motors),
    Frame("copter",    4, quad_plus_motors),
    Frame("x",         4, quad_x_motors),
    Frame("hexa",      6, hexa_motors),
    Frame("hexax",     6, hexax_motors),
    Frame("octa",      8, octa_motors),
    Frame("octa-quad", 8, octa_quad_motors)
}
Definition at line 91 of file SIM_Multicopter.cpp.