APM:Libraries: libraries/AP_Math/polygon.cpp File Reference
polygon.cpp File Reference
#include "AP_Math.h"
Macros
#define sign(x) ((x)<0 ? -1 : 1)
Functions
bool Polygon_outside (const Vector2l &P, const Vector2l *V, unsigned n)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
bool Polygon_complete (const Vector2l *V, unsigned n)
Macro Definition Documentation
#define sign (x) ((x)<0 ? -1 : 1)
Referenced by AP_Declination::get_lookup_value(), Polygon_outside(), and print_vprintf().
Function Documentation
bool Polygon_complete (const Vector2l * V, unsigned n)
Definition at line 88 of file polygon.cpp.
Referenced by AP_Limit_Geofence::boundary_correct(), and setup().
bool Polygon_outside (const Vector2l & P, const Vector2l * V, unsigned n)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 38 of file polygon.cpp.
Referenced by AP_Limit_Geofence::boundary_correct(), setup(), and AP_Limit_Geofence::triggered().