APM:Libraries: libraries/AP_HAL_FLYMAPLE/examples/Semaphore/Semaphore.cpp File Reference
Semaphore.cpp File Reference
#include <AP_Common/AP_Common.h>
#include <AP_Math/AP_Math.h>
#include <AP_Param/AP_Param.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL_FLYMAPLE/AP_HAL_FLYMAPLE.h>
Macros
#define PIN_A0 15
#define PIN_A1 16
#define PIN_A2 17
#define PIN_A3 18
Functions
void blink_a0 ()
void blink_a1 ()
void blink_a2 ()
void blink_a3 ()
void setup_pin (int pin_num)
void setup (void)
void async_blinker (uint32_t millis)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_HAL::Semaphore * sem
uint32_t async_last_run = 0
Macro Definition Documentation
#define PIN_A0 15
Definition at line 15 of file Semaphore.cpp.
Referenced by blink_a0(), and setup().
#define PIN_A1 16
Definition at line 16 of file Semaphore.cpp.
Referenced by blink_a1(), and setup().
#define PIN_A2 17
Definition at line 17 of file Semaphore.cpp.
Referenced by blink_a2(), and setup().
#define PIN_A3 18
Definition at line 18 of file Semaphore.cpp.
Referenced by blink_a3(), and setup().
Function Documentation
AP_HAL_MAIN ()
void async_blinker (uint32_t millis)
Definition at line 89 of file Semaphore.cpp.
Referenced by setup().
void blink_a0 ()
Definition at line 26 of file Semaphore.cpp.
Referenced by async_blinker().
void blink_a1 ()
Definition at line 33 of file Semaphore.cpp.
Referenced by async_blinker().
void blink_a2 ()
Definition at line 41 of file Semaphore.cpp.
Referenced by loop().
void blink_a3 ()
Definition at line 48 of file Semaphore.cpp.
Referenced by loop().
void loop (void)
Definition at line 102 of file Semaphore.cpp.
void setup (void)
Definition at line 63 of file Semaphore.cpp.
void setup_pin (int pin_num)
Definition at line 55 of file Semaphore.cpp.
Referenced by setup().
Variable Documentation
uint32_t async_last_run = 0
Definition at line 88 of file Semaphore.cpp.
Referenced by async_blinker().
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 8 of file Semaphore.cpp.
AP_HAL::Semaphore* sem
Create a Semaphore for this test.
Definition at line 24 of file Semaphore.cpp.