APM:Libraries: libraries/GCS_Console/examples/Console/simplegcs.cpp File Reference
simplegcs.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <GCS_MAVLink/GCS_MAVLink.h>
#include <GCS_Console/GCS_Console.h>
#include "simplegcs.h"
Macros
#define CHECK_PAYLOAD_SIZE(id) if (payload_space < MAVLINK_MSG_ID_ ## id ## _LEN) return false
Functions
void send_heartbeat (mavlink_channel_t chan)
bool try_send_message (mavlink_channel_t chan, int msgid)
bool try_send_statustext (mavlink_channel_t chan, const char *text, int len)
void simplegcs_update (mavlink_channel_t chan)
void handle_message (mavlink_channel_t chan, mavlink_message_t *msg)
Variables
const AP_HAL::HAL & hal
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Macro Definition Documentation
#define CHECK_PAYLOAD_SIZE (id) if (payload_space < MAVLINK_MSG_ID_ ## id ## _LEN) return false
Definition at line 26 of file simplegcs.cpp.
Referenced by try_send_message(), and try_send_statustext().
Function Documentation
void handle_message (mavlink_channel_t chan, mavlink_message_t * msg)
Definition at line 73 of file simplegcs.cpp.
Referenced by simplegcs_update().
void send_heartbeat (mavlink_channel_t chan)
Definition at line 9 of file simplegcs.cpp.
Referenced by try_send_message().
void simplegcs_update (mavlink_channel_t chan)
Definition at line 60 of file simplegcs.cpp.
Referenced by loop().
bool try_send_message (mavlink_channel_t chan, int msgid)
Definition at line 28 of file simplegcs.cpp.
Referenced by loop().
bool try_send_statustext (mavlink_channel_t chan, const char * text, int len)
Definition at line 42 of file simplegcs.cpp.
Referenced by flush_console_to_statustext(), and setup().
Variable Documentation
const AP_HAL::HAL& hal
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 10 of file AC_PID_test.cpp.