APM:Libraries: libraries/AP_HAL_SITL/sitl_gps.cpp File Reference
sitl_gps.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "AP_HAL_SITL.h"
#include "AP_HAL_SITL_Namespace.h"
#include "HAL_SITL_Class.h"
#include <AP_Math/AP_Math.h>
#include <SITL/SITL.h>
#include "Scheduler.h"
#include "UARTDriver.h"
#include <AP_GPS/AP_GPS.h>
#include <AP_GPS/AP_GPS_UBLOX.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <time.h>
#include <stdio.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
Classes
struct gps_state
Functions
static void gps_time (uint16_t *time_week, uint32_t *time_week_ms)
static void swap_uint32 (uint32_t *v, uint8_t n)
static void mtk_checksum (const uint8_t *data, uint8_t n, uint8_t *ck_a, uint8_t *ck_b)
Variables
const AP_HAL::HAL & hal
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static uint8_t next_gps_index
static uint8_t gps_delay
static struct gps_state gps_state
static struct gps_state gps2_state
Function Documentation
static void gps_time (uint16_t * time_week, uint32_t * time_week_ms) static
Definition at line 154 of file sitl_gps.cpp.
Referenced by HALSITL::SITL_State::_update_gps_sbp(), HALSITL::SITL_State::_update_gps_ubx(), and DataFlash_Class::Log_Write_Camera().
static void mtk_checksum (const uint8_t * data, uint8_t n, uint8_t * ck_a, uint8_t * ck_b) static
Definition at line 300 of file sitl_gps.cpp.
Referenced by HALSITL::SITL_State::_update_gps_mtk(), HALSITL::SITL_State::_update_gps_mtk16(), and HALSITL::SITL_State::_update_gps_mtk19().
static void swap_uint32 (uint32_t * v, uint8_t n) static
Definition at line 289 of file sitl_gps.cpp.
Referenced by HALSITL::SITL_State::_update_gps_mtk().
Variable Documentation
struct gps_state gps2_state static
uint8_t gps_delay static
Definition at line 38 of file sitl_gps.cpp.
Referenced by HALSITL::SITL_State::_update_gps().
struct gps_state gps_state static
const AP_HAL::HAL& hal
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 10 of file AC_PID_test.cpp.
uint8_t next_gps_index static
Definition at line 37 of file sitl_gps.cpp.
Referenced by HALSITL::SITL_State::_update_gps().