APM:Libraries: libraries/StorageManager/examples/StorageTest/StorageTest.cpp File Reference
StorageTest.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <StorageManager/StorageManager.h>
Macros
#define DO_INITIALISATION 1
Functions
static uint16_t get_random (void)
static uint8_t pvalue (uint16_t offset)
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static StorageAccess all_storage [4]
Macro Definition Documentation
#define DO_INITIALISATION 1
Definition at line 12 of file StorageTest.cpp.
Function Documentation
AP_HAL_MAIN ()
static uint16_t get_random (void) static
Definition at line 27 of file StorageTest.cpp.
Referenced by loop().
void loop (void)
Definition at line 58 of file StorageTest.cpp.
static uint8_t pvalue (uint16_t offset) static
Definition at line 39 of file StorageTest.cpp.
Referenced by loop(), and setup().
void setup (void)
Definition at line 44 of file StorageTest.cpp.
Variable Documentation
StorageAccess all_storage[4] static
Initial value:
= {
    StorageAccess(StorageManager::StorageParam),
    StorageAccess(StorageManager::StorageMission),
    StorageAccess(StorageManager::StorageFence),
    StorageAccess(StorageManager::StorageRally)
}
Definition at line 17 of file StorageTest.cpp.
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 10 of file StorageTest.cpp.
Referenced by AP_HAL::get_HAL().